### ISSUE TITLE
[Bug]: HttpRequestException

### ISSUE THREAD

**Issue by LLLLLinJH** [DGP-Studio/Snap.Hutao#100]
### Windows 版本

25211.1010

### Snap Hutao 版本

1.1.8.0

### 发生了什么？

打开软件
显示HttpRequestException
元数据校验文件下载失败

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
重启App

**Comment by zzwtsy** [comment]
是否挂了代理？
我在关掉代理后解决了这个问题

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by LLLLLinJH** [comment]
已解决，由于人在海外未挂V回国导致
挂回国后应用正常:D

**Comment by Masterain98** [comment]
@zzwtsy @LLLLLinJH 

麻烦提供一下大致的地理位置，以及主机 tracert 到 `hutao-metadata.snapgenshin.com`的结果（如下图，使用 cmd/PowerShell 即可）
```
tracert hutao-metadata.snapgenshin.com
```
![image](https://user-images.githubusercontent.com/10614984/194769915-a3bf0695-3947-49cf-88a9-20e7e9ea1c51.png)

**Comment by LLLLLinJH** [comment]
地址：中国香港 
![image](https://user-images.githubusercontent.com/52768701/194785309-f4740c1f-3418-428f-8972-e09735fbca6c.png)

**Comment by zzwtsy** [comment]
位置：安徽六安
![屏幕截图 2022-10-10 081811](https://user-images.githubusercontent.com/58852496/194786219-44ad4bb2-21fd-4a56-999a-5d4599b18df6.png)
另外以下网址也不能加入代理
```text
enka-api.hut.ao
static.snapgenshin.com
hutao-metadata.snapgenshin.com
```

**Comment by Masterain98** [comment]
@LLLLLinJH @zzwtsy 
远程服务器目前都没有问题。

问题来源是[Windows APP Container Loopback的限制](https://learn.microsoft.com/zh-CN/windows/iot-core/develop-your-app/loopback)。当你启用系统代理的时候，胡桃工具箱因为被禁止连接到本地地址，实际上是没有任何网络连接的。

如果你使用的 Clash 代理程序，可以使用  TUN 模式并禁止系统代理来解决该问题；或者也可以通过[ Windows 8 AppContainer Loopback Utility](https://www.telerik.com/fiddler/add-ons) 解除 APP Container Loopback 限制。
![image](https://user-images.githubusercontent.com/10614984/194798010-33a76d5d-75ed-40b6-a5a3-85df234cb892.png)

**Comment by zzwtsy** [comment]
> 
非常感谢，问题已经解决

**Comment by 1980035966** [comment]
在外国怎么办？玩的国服
