### ISSUE TITLE
[Bug]: 闪退

### ISSUE THREAD

**Issue by johnwickk1211** [DGP-Studio/Snap.Hutao#1002]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2338

### Snap Hutao 版本

1.7.6.0

### 设备 ID

打不开

### 问题分类

安装和环境

### 发生了什么？

错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x64e841c5
错误模块名称: Microsoft.ui.xaml.dll，版本: 3.1.4.0，时间戳: 0x343afd70
异常代码: 0xc000027b
错误偏移量: 0x00000000003b9584

### 你期望发生的行为？

软件可以正常打开

### 最后一步

- [ ] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
错误日志不包含关键信息；增加开始崩溃前的操作描述

**Comment by Lightczx** [comment]
1.7.7版本已经发布，如果1.7.7依旧存在问题可以重新开启此issue

**Comment by kudoukouki** [comment]
> 1.7.7版本已经发布，如果1.7.7尚存在问题可以重新开启此问题

我更新1.7.7.0了，点击启动游戏还是闪退

**Comment by Masterain98** [comment]
> 我更新1.7.7.0了，点击启动游戏还是闪退

提供日志

**Comment by zfonlyone** [comment]
下载最新版本胡桃，然后打开数据文件夹清除ServerCache，然后重启胡桃，重新下载转换文件就不会闪退了

**Comment by Lightczx** [comment]
closing this because no response from author
