### ISSUE TITLE
[Bug]: HoYoLAB 账号网页登陆网页错误

### ISSUE THREAD

**Issue by Xhichn** [DGP-Studio/Snap.Hutao#1007]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.7.0

### 问题分类

安装和环境

### 发生了什么？

在用户面板点击HoYoLAB“网页登陆”按钮后会跳转到miHoYo通行证的登陆界面

### 你期望发生的行为？

点击HoYoLAB“网页登陆”按钮后正确显示hoyoverse账号登陆网页

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Xhichn** [comment]
除了网页显示问题，发现 `ISupportLoginByWebView.cs` 还有另一处错误导致无法处理 Cookie
https://github.com/DGP-Studio/Snap.Hutao/blob/65179a340f9c49704d7c4e034f57c3c339fa39e3/src/Snap.Hutao/Snap.Hutao/View/Page/ISupportLoginByWebView.cs#L36C52-L36C52

**Comment by prpjzz** [comment]
> 除了网页显示问题，发现 `ISupportLoginByWebView.cs` 还有另一处错误导致无法处理 Cookie https://github.com/DGP-Studio/Snap.Hutao/blob/65179a340f9c49704d7c4e034f57c3c339fa39e3/src/Snap.Hutao/Snap.Hutao/View/Page/ISupportLoginByWebView.cs#L36C52-L36C52

I'm in the same situation, the reason is highly likely that HoYoLAB's original cookie doesn't have stoken fields like MiYouShe
