### ISSUE TITLE
[Bug]: 导出的UIGF Json版本中gacha_type这一字段与UIGF标准不一致

### ISSUE THREAD

**Issue by CHxCOOH** [DGP-Studio/Snap.Hutao#101]
### Windows 版本

22621.521

### Snap Hutao 版本

1.1.8.0

### 发生了什么？

导出的json中每个list里面的对象中gacha_type字段为NoviceWish、PermanentWish、AvatarEventWish2、AvatarEventWish、WeaponEventWish中的一种，而不是预期的100、200、301、302、400，这导致了胡桃导出的json导入到snap.genshin或者其他工具时可能会报错。

### 你期望发生的行为？

一个当前版本胡桃导出的json片段示例：
```json
    {
      "uigf_gacha_type": "200",
      "gacha_type": "PermanentWish",
      "item_id": "",
      "count": "1",
      "time": "2020-11-07 00:41:41",
      "name": "魔导绪论",
      "item_type": "武器",
      "rank_type": "3",
      "id": 1000000000000000080
    }
```
实际上应该是：
```json
    {
      "uigf_gacha_type": "200",
      "gacha_type": "200",
      "item_id": "",
      "count": "1",
      "time": "2020-11-07 00:41:41",
      "name": "魔导绪论",
      "item_type": "武器",
      "rank_type": "3",
      "id": 1000000000000000080
    }
```

### 相关的崩溃日志 位于 `%HOMEPATH%/Documents/Hutao/Log.db`

```shell
无
```

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
导出功能尚未制作完成
