### ISSUE TITLE
[Bug]: 国际服登录 显示cookie无效 登录不上

### ISSUE THREAD

**Issue by gobugong** [DGP-Studio/Snap.Hutao#1011]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

版本	Windows 11 专业版 版本	21H2 安装日期	‎2023/‎8/‎20 ‎星期日 操作系统版本	22000.2538 体验	Windows 功能体验包 1000.22001.1000.0

### Snap Hutao 版本

1.7.9

### 设备 ID

058581DA6743E81F872E2175921E4EC0

### 问题分类

玩家查询

### 发生了什么？

![Snipaste_2023-10-13_16-13-23](https://github.com/DGP-Studio/Snap.Hutao/assets/102224598/6bbcd452-6323-448a-8a74-37280e43ebe6)
![Snipaste_2023-10-13_16-15-49](https://github.com/DGP-Studio/Snap.Hutao/assets/102224598/f8993f1e-a7c2-4302-9323-f5d22bb89851)
![Snipaste_2023-10-13_16-29-55](https://github.com/DGP-Studio/Snap.Hutao/assets/102224598/e3cb14bc-bc0a-42d3-8cbb-fda5ad0461ab)

### 你期望发生的行为？

自己搭的节点网络错误 在浏览器正常用其实 不过这个已经解决了 换成别的节点了 登上之后换过两个号轮流登录 这两个号都是无效cookie 录入不进去 账号信息自然也没办法 希望解决一下吧国际服太难了 试了一下国服我是正常的 检测stoken正常吧大概 国际服无效哟 

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by prpjzz** [comment]
I'm in the same situation, the reason is highly likely that HoYoLAB's original cookie doesn't have stoken fields like MiYouShe

**Comment by gobugong** [comment]
问过开发这个原神小帮手的作者说stoken比较难抓取 本来折腾半天 最后依旧没整好stoken 不然我就直接手动输入了 网页抓取的只有token好像 说是需要更高等级的 比较难 但是他那边确实可以签到等等的 是需要输入ltuid跟ltoken就行这种解决方案 下图：
![Snipaste_2023-10-13_19-05-24](https://github.com/DGP-Studio/Snap.Hutao/assets/102224598/6205af3e-40b4-405c-8093-656c8e08d9c0)
加油 dc用起来真的不直观 这种客户端能加进来就再好不过了

**Comment by zplinus** [comment]
弱弱问下这个什么时候能release？

**Comment by Lightczx** [comment]
预计本周五前
