### ISSUE TITLE
[Feat]: 希望养成计划可以添加未上线的角色和武器

### ISSUE THREAD

**Issue by qiuqiu-2** [DGP-Studio/Snap.Hutao#1014]
### Background & Motivation 背景与动机

因为未上线的角色需要提前准备材料，所以需要提前添加进养成计划中，以便提前准备角色和武器的升级与突破材料。比如4.1版本下半才进入卡池的角色莱欧斯利，虽然角色还未上线，但是角色和武器的突破材料都是已知的，胡桃中也可以查到相应的角色与武器资料，缺无法被添加进养成计划中，
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67945933/623f85b4-4bcb-42fc-b4e3-a712599b76f3)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67945933/ccf0cca3-8d46-48e2-a863-02f815a96603)
这或许是个BUG？或者是故意这么设计的？但这并不是“内鬼”行为（如水神这种官方未发布的就算内鬼行为，但莱欧斯利本就是4.1进卡池的角色）。除此之外软件“寻空”就可以添加这类未上线但是已知的角色进养成计划中，但我更喜欢“胡桃”，所以希望胡桃也可以添加这一功能。

### Detail of the Feature 想要实现或优化的功能

能够将当前版本上线但还未进卡池的角色与武器添加进养成计划中。如4.1上线但在4.1下半才进卡池的角色莱欧斯利，在角色资料界面可以看到他的突破材料但无法添加进养成计划。

**Comment by Lightczx** [comment]
养成计划使用米游社API，无法添加未实装角色
