### ISSUE TITLE
[Feat]: 首页的更新提示公告可以在展示前判断下版本，已经更新过的无需展示

### ISSUE THREAD

**Issue by abandonstudy** [DGP-Studio/Snap.Hutao#1015]
### Background & Motivation 背景与动机

无

### Detail of the Feature 想要实现或优化的功能

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/ed5edc0d-698d-4013-97c3-5a5638e34254)
看到公告，我去把1.7.9的msix包下完了，结果发现Microsoft Store已经自动帮我升级了，晕死
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/8d9b9a23-c608-47c6-9ee6-2e230989115e)

**Comment by Masterain98** [comment]
你可以通过窗口左上角的标题确认版本
