### ISSUE TITLE
[Feat]: 养成计划记忆养成目标

### ISSUE THREAD

**Issue by zhang258027** [DGP-Studio/Snap.Hutao#1016]
### Background & Motivation 背景与动机

背景：回归上线后浏览<养成计划>，总想不起来设定了什么，只能看到所需资源

动机：利用<养成计划>规划角色培养

### Detail of the Feature 想要实现或优化的功能

希望能在<养成计划>里能显示计划内容，如：角色等级、天赋等级的规划

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/5961702a-e944-4b0f-93bb-26b7f75f8931)
