### ISSUE TITLE
[Bug]: 更新之后进入胡桃界面窗口大小不正常

### ISSUE THREAD

**Issue by QGhappyChenCheng** [DGP-Studio/Snap.Hutao#1017]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3086

### Snap Hutao 版本

1.7.9

### 设备 ID

47B76EAA777B5A50E1A2EB30E3A05623

### 问题分类

用户界面

### 发生了什么？

更新1.7.9版本后（包括23.10.11.3）工具箱打开会直接撑满整个屏幕。14寸屏幕（分辨率2240x1400）拖不到标题栏，四边角全部都在屏幕和状态栏之外；16寸屏幕（分辨率2560x1600）勉强能碰到标题栏把工具箱拉下来换成最大化才能恢复正常显示。

### 你期望发生的行为？

希望可以设置为默认最大化窗口进入胡桃，或者回调一下工具箱窗口的默认分辨率？

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
intended behavior
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/31ae45be-40de-4b55-8917-872dd785fcdb)
