### ISSUE TITLE
[Bug]: 在游戏路径中设置为国际服之后,点击启动游戏选项卡后,界面卡死,一段时间后崩溃

### ISSUE THREAD

**Issue by jinyiwei2012** [DGP-Studio/Snap.Hutao#1018]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

25967.1010

### Snap Hutao 版本

1.7.9.0

### 设备 ID

AE0F0658DA74DCC7CF3884CFE15C698A

### 问题分类

游戏启动器

### 发生了什么？

在游戏路径中设置为国际服之后,点击启动游戏选项卡后,界面卡死,一段时间后崩溃
出错应用程序名称： Snap.Hutao.exe，版本： 1.0.0.0，时间戳： 0x6514d416
出错模块名称： CoreMessagingXP.dll， 版本： 10.0.22624.1046，时间戳： 0xbc9f21de
异常代码： 0xc000027b
错误偏移： 0x000000000008f52c
出错进程 ID： 0x3858
出错应用程序开始时间： 0x1D9FE9D12FC92BD
Faulting 应用程序路径： C:\Program Files\WindowsApps\7f0db578-026f-4e0b-a75b-d5d06bb0a74c_2023.10.13.6_x64__fp4j87wfz3je2\Snap.Hutao.exe
Faulting 模块路径： C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
Report ID： de8892b6-fa34-4842-b4d9-929bb9edf7fc
Faulting 包全名： 7f0db578-026f-4e0b-a75b-d5d06bb0a74c_2023.10.13.6_x64__fp4j87wfz3je2
Faulting 程序包相对应用程序 ID： App 个
出错应用程序名称： Snap.Hutao.exe，版本： 1.0.0.0，时间戳： 0x64e841c5
出错模块名称： Microsoft.ui.xaml.dll， 版本： 3.1.4.0，时间戳： 0xac5fca29
异常代码： 0xc000027b
错误偏移： 0x00000000003b95e4
出错进程 ID： 0x388C
出错应用程序开始时间： 0x1D9FE9F21C85B7A
Faulting 应用程序路径： C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.9.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
Faulting 模块路径： C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report ID： 63c27105-c8b9-40b0-9ab9-d3594e8f1979
Faulting 包全名： 60568DGPStudio.SnapHutao_1.7.9.0_x64__ebfp3nyc27j86
Faulting 程序包相对应用程序 ID： App 个

### 你期望发生的行为？

可以正常启动

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
1.7.10应该修复了此问题，如果问题依旧存在可以重新开启此 Issue

**Comment by jinyiwei2012** [comment]
出错应用程序名称： Snap.Hutao.exe，版本： 1.0.0.0，时间戳： 0x64e841c5
出错模块名称： CoreMessagingXP.dll， 版本： 10.0.22624.1046，时间戳： 0xbc9f21de
异常代码： 0xc000027b
错误偏移： 0x000000000008f52c
出错进程 ID： 0x7170
出错应用程序开始时间： 0x1DA03A6A327290C
Faulting 应用程序路径： C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
Faulting 模块路径： C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
Report ID： 28a1e77c-459d-4338-b941-914c67d3a3de
Faulting 包全名： 60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86
Faulting 程序包相对应用程序 ID： App 个

> 1.7.10应该修复了此问题，如果问题依旧存在可以重新开启此 Issue

**Comment by Lightczx** [comment]
下版本修复
