### ISSUE TITLE
[Network]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by SamSs666** [DGP-Studio/Snap.Hutao#1022]
### 提交你的网络诊断报告

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/116129129/6910fca1-0a4f-4adf-a540-b15495bd4e0c)

开软件以后等几秒种就出现这个错误。
然后Wish History 和 Achievements两个页面点击以后不显示任何内容。

### 你的地理位置

澳大利亚

### 你的运营商

其它

### 你的问题

完全无法连接服务器

**Comment by Masterain98** [comment]
检查你的DNS设置
