### ISSUE TITLE
[Bug]: 内嵌米游社网页无法回退

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1023]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2428

### Snap Hutao 版本

1.7.9.0

### 问题分类

用户界面

### 发生了什么？

胡桃没有对内嵌的米游社客户端做部分特殊处理，导致进行如下操作时会出现异常：

> 以下步骤为个人产生异常进行步骤，其余**同类型步骤**亦可能导致程序异常

1. 左侧菜单栏选中用户，弹窗选中“我的角色”
2. 点击窗口右上角分享按钮即可

至此，实现“我的角色”页面异常

尝试如下方式，未能使其返回正确页面：

1. 退出子窗口，选择领取签到奖励，退出，再次打开我的角色窗口

尝试如下方式，正确返回页面但是用户信息错误：

1. 退出子窗口，切换当前用户，再次打开我的角色窗口
    此时，所打开角色数据并非选中用户角色数据，而是米游社设置中的默认角色数据

尝试如下方式，正确返回页面：

1. 应用重启

### 你期望发生的行为？

1. 提供正确 callback，使其完成操作后正常回退
2. 提供回退/跳转模拟按键，回退或强制跳转回首页

在上述测试过程中，发现了切换用户导致的 与 https://github.com/DGP-Studio/Snap.Hutao/issues/1003  不同的新 Bug

> 尝试如下方式，正确返回页面但是用户信息错误：
>
> 1. 退出子窗口，切换当前用户，再次打开我的角色窗口
 >    此时，所打开角色数据并非选中用户角色数据，而是米游社设置中的默认角色数据

个人认为出现原因与本 issue 等同，故不再新提

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
> 1. 退出子窗口，切换当前用户，再次打开我的角色窗口
>    此时，所打开角色数据并非选中用户角色数据，而是米游社设置中的默认角色数据

需要在米游社内切换，目前没有在程序内执行相关的切换真实选中角色的逻辑
