### ISSUE TITLE
[Bug]: 无边框和全屏选项无法同时生效

### ISSUE THREAD

**Issue by Tianyuweiyang** [DGP-Studio/Snap.Hutao#1028]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2428

### Snap Hutao 版本

1.710.0

### 设备 ID

C5BEE15C35000CE082F71A1ED80C8DBD

### 问题分类

其它

### 发生了什么？

明明没有设置东西，更新后就发生无边框与全屏无法同时生效
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/98724156/0da2a563-9f6a-4187-9492-ffd3d2260505)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/98724156/a6f809d4-f2e2-4013-bab1-cd8468abd6b3)
qi'dong启动不了

### 你期望发生的行为？

解决这个问题，这个问题在上个版本没有出现过，谢谢

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
无边框与独占全屏必须且只能选择一个。
目前提示有一定误导性，会在后续版本修正

**Comment by Tianyuweiyang** [comment]
不能像之前那样用窗口化启动了吗？

**Comment by Lightczx** [comment]
当前版本不能这么做，后续版本会修复

**Comment by Tianyuweiyang** [comment]
谢谢你的回答

**Comment by 79mario** [comment]
选择了一个后启动还是提示全屏和无边框无法同时生效，无法启动游戏

**Comment by Lightczx** [comment]
> 无边框与独占全屏必须且只能选择一个。 目前提示有一定误导性，会在后续版本修正

【无边框】【独占全屏】不是【全屏】

**Comment by Actuallymax** [comment]
独占全屏 不勾选
全屏  勾选
无边框 不勾选

依然会提示这个无法启动
