### ISSUE TITLE
[Feat]: 自定义窗口参数

### ISSUE THREAD

**Issue by qhy040404** [DGP-Studio/Snap.Hutao#1029]
### Background & Motivation 背景与动机

#1020 #1028

我认为窗口参数的设定本身就是一个可选项，用户可以在游戏内设定后，后期直接沿用游戏内参数，而不需要每次重新传入相关参数。

### Detail of the Feature 想要实现或优化的功能

外观相关设置添加一个总的开关，默认可以是开启

**Comment by Lightczx** [comment]
Internal workitem
https://github.com/orgs/DGP-Studio/projects/2?query=itemId%3D21524601&pane=issue&itemId=21524601

**Comment by Lightczx** [comment]
implemented in https://github.com/DGP-Studio/Snap.Hutao/commit/59d62f931dbaf28e53ee93494e927be7acc877e1
