### ISSUE TITLE
[Bug]: 1.7.10.0版本无法正常窗口化启动游戏

### ISSUE THREAD

**Issue by myzzh5** [DGP-Studio/Snap.Hutao#1031]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2428

### Snap Hutao 版本

1.7.10.0

### 问题分类

游戏启动器

### 发生了什么？

所有设置均未动过，为啥更新后一定要全屏或者无边框才能启动游戏
![{637A7E54-094B-4ee6-8B4B-2E8988BEF938}](https://github.com/DGP-Studio/Snap.Hutao/assets/39124372/b78f4382-157c-4f26-ab29-40f743e313e6)
![{07D8DFF5-8542-417d-8E63-516B279483D3}](https://github.com/DGP-Studio/Snap.Hutao/assets/39124372/cd782a10-7105-4000-85ef-522cb4996212)

### 你期望发生的行为？

启动器回归更新前的版本，没必要强制全屏或者无边框窗口，我就习惯做完每日直接右上角关掉游戏

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
Duplicate of #1028
