### ISSUE TITLE
[Bug]: 软件被杀毒软件删除后重新安装导致启动次数被重置

### ISSUE THREAD

**Issue by hoiyuyiu** [DGP-Studio/Snap.Hutao#1038]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23570.1000

### Snap Hutao 版本

1.7.11.0

### 设备 ID

602E0E8AEC0FB85C85FFED6945C6D501

### 问题分类

安装和环境

### 发生了什么？

白天提示更新到1.7.11后及时进行了更新，晚上想打开时却遇到了卡巴斯基的报毒（以前从未遇到过）并自动删除了（下附报错信息），尝试恢复无果，便启动微软商店重新安装，安装后抽卡数据等均有保存，遗憾的是胡桃的启动次数似乎被重置了，略感遗憾请问是否能尝试恢复？
重新安装后打开胡桃并没有遇到杀毒软件报错，看起来一切尚好

报错信息：
事件: 检测到恶意对象
应用程序: A Snap Hutao Software
用户: （隐去）
组件: 系统监控
结果说明: 检测到
类型: 木马
名称: PDM:Trojan.Win32.Generic
威胁级别: 高
对象类型: 进程
对象路径: c:\program files\windowsapps\60568dgpstudio.snaphutao_1.7.11.0_x64__ebfp3nyc27j86
对象名称: snap.hutao.exe
原因: 数据库
数据库发布日期: 昨天，周五 20 10 23 23:36:00

### 你期望发生的行为？

不知什么原因出现了偶然的卡巴斯基报错，导致未来得及阻止被删掉软件了，从Snap.Genshin开始就一直用，从来没遇到过这种问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Scighost** [comment]
很遗憾，启动次数是存储在应用内部的某个位置，它会因为应用卸载而完全删除，不存在恢复的可能。但是你可以请求 @Lightczx 开发一个手动修改此值的功能。

**Comment by hoiyuyiu** [comment]
@Lightczx 请问能否将启动次数像抽卡记录一样存在本地或者存在云端（胡桃账号下？），以避免类似情况，或在重装应用时出现的启动次数丢失的情况
（我的几百次启动啊啊啊啊啊）

**Comment by hoiyuyiu** [comment]
我的胡桃被再次删除了，不知道是之前添加了排除项的原因还是什么，没有能在杀毒软件中查看到相关报错，总之就是导致软件无法被打开，而微软商店中也没有出现重新安装的选项

**Comment by Lightczx** [comment]
排除 `%programfiles%/WindowsApps` 目录 与 `%userprofile%/Documents/Hutao`

**Comment by Lightczx** [comment]
> 几百次启动

启动次数不和任何其他功能挂钩，应该无所谓吧

**Comment by hoiyuyiu** [comment]
> > 几百次启动
> 
> 启动次数不和任何其他功能挂钩，应该无所谓吧

确实无所谓，只是想着有个类似里程碑之类的记录一下，权当提个建议罢了，无关紧要了。（主要是又被删了一次，我释怀了）

**Comment by Lightczx** [comment]
#1040
