### ISSUE TITLE
[Feat]: 文档和反馈页面

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1039]
### Background & Motivation 背景与动机

增强用户反馈和文档入口

### Detail of the Feature 想要实现或优化的功能

- 增加问题反馈在客户端显眼位置的入口
- 增加内置客户端的文档搜索 （API可用）

**Comment by Masterain98** [comment]
跳转至 https://status.hut.ao 的入口也需要加入

**Comment by Masterain98** [comment]
- 搜索 API
  - Endpoint: `https://{Application-ID}-dsn.algolia.net/1/indexes/*/queries`
  - Type: `POST`
  - Body:
  ```
  {
    "requests": [
      {"query": "keyword",
        "indexName": "hutao"
      }
      ]
  }
  ```

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/cf81ae46-31e4-42d0-b793-28759bc23129)
