### ISSUE TITLE
[Bug]: 卡巴斯基报毒 PDM:Trojan.Win32.Generic

### ISSUE THREAD

**Issue by ChrisKimZHT** [DGP-Studio/Snap.Hutao#1040]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19044.3570

### Snap Hutao 版本

1.7.11.0

### 问题分类

其它

### 发生了什么？

```
事件: 检测到恶意对象
应用程序: A Snap Hutao Software
用户: DSKTOP-CHRISKIM\ChrisKim
用户类型: 活动用户
组件: 系统监控
结果说明: 检测到
类型: 木马
名称: PDM:Trojan.Win32.Generic
威胁级别: 高
对象类型: 进程
对象路径: c:\program files\windowsapps\60568dgpstudio.snaphutao_1.7.11.0_x64__ebfp3nyc27j86
对象名称: snap.hutao.exe
原因: 数据库
数据库发布日期: 今天，2023/10/21 15:35:00
```

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by ChrisKimZHT** [comment]
与 #1038 表现不同的是，我重新安装后持续报毒，启动即删除，无法正常启动。

**Comment by Masterain98** [comment]
可能是读写数据库的操作被判定为恶意行为了，我试了下将msix包上传扫描结果是没问题的。这个可能得向卡巴斯基反馈了，暂时的解决方案应该就是拉进白名单了（如果它有的话）

**Comment by hoiyuyiu** [comment]
> 与 #1038 表现不同的是，我重新安装后持续报毒，启动即删除，无法正常启动。

我的也又被删了，但可能是因为我之前添加了排除项的原因，这次没有任何提示

**Comment by Masterain98** [comment]
使用的是卡巴斯基的具体哪一款产品？@ChrisKimZHT @hoiyuyiu

**Comment by ad030405** [comment]
> 使用的是卡巴斯基的具体哪一款产品？@ChrisKimZHT @hoiyuyiu

 我也遇到了这个问题，使用的为卡巴斯基 Plus（原卡巴斯基全方位安全软件），版本为 21.14.5.462，操作系统为 Windows 10 专业版。今天中午启动 Hutao 时它还没有报毒，刚刚启动后它报毒并直接删除了 Hutao 的 exe 文件。现在我已重新安装，暂时没有报毒。

**Comment by hoiyuyiu** [comment]
> 使用的是卡巴斯基的具体哪一款产品？@ChrisKimZHT @hoiyuyiu

我使用的是卡巴斯基免费版（之前在贴吧找到的，现在好像直接下载不到了），但我不清楚如何查看版本号。操作系统win11dev23570。因为今天软件又被删除了一次，但今天打开了不止一次，所以怀疑是软件的某个行为才导致被杀了（不太懂，猜的）。
由于使用卡巴斯基排除应用程序时无法访问WindowsApps目录，所以只能先通过索引找到胡桃.exe的位置再导入回卡巴斯基里排除（此方法是否可行暂未验证），具体情况我在#1038中进行过反馈

**Comment by ChrisKimZHT** [comment]
> 使用的是卡巴斯基的具体哪一款产品？@ChrisKimZHT @hoiyuyiu 

卡巴斯基安全软件

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/f86e3dc9-f295-442f-9e0f-5f99980969b2)

Report sent to Kaspersky. Waiting for response.
Case ID: INC000015817051.
The latest Snap Hutao scan result can be found at https://opentip.kaspersky.com/31589E734F19879615404E36F23017E312291A685773D6800F75DF6104E1902A

**Comment by Masterain98** [comment]
可以提供一份卡巴斯基相关日志的截图吗？

**Comment by ChrisKimZHT** [comment]
> 可以提供一份卡巴斯基相关日志的截图吗？包含完整卡巴斯基界面的。

![a](https://github.com/DGP-Studio/Snap.Hutao/assets/49368462/cc0c9ceb-8a08-48e1-933c-11f1d2994200)

**Comment by hoiyuyiu** [comment]
> 可以提供一份卡巴斯基相关日志的截图吗？包含完整卡巴斯基界面的。

![Cache_724f796dbaadff3a.jpg](https://github.com/DGP-Studio/Snap.Hutao/assets/61400426/32782e7a-7981-454d-8468-98dff94c3338)

**Comment by Masterain98** [comment]
麻烦提供一份在卡巴斯基报毒后的系统日志，方法在下面的文档中

https://support.kaspersky.com/common/diagnostics/15544

**Comment by Masterain98** [comment]
我稍后会在虚拟机中尝试看能不能复现一下

**Comment by hoiyuyiu** [comment]
> 我稍后会在虚拟机中尝试看能不能复现一下

现在遇到个问题就是日志对应

**Comment by Masterain98** [comment]
> > 我稍后会在虚拟机中尝试看能不能复现一下
> 
> 现在遇到个问题就是日志对应文件夹打包后超出允许上传文件大小（29MB），我该如何提供呢

可以邮箱发送到 support@dgp-studio.cn，或者从Discord/QQ群里找到我私聊发来

**Comment by Masterain98** [comment]
> 我稍后会在虚拟机中尝试看能不能复现一下

未成功复现

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/ee05bf12-e30a-4b00-bb9b-8f1d325a47bf)

**Comment by hoiyuyiu** [comment]
> > > 我稍后会在虚拟机中尝试看能不能复现一下
> > 
> > 现在遇到个问题就是日志对应文件夹打包后超出允许上传文件大小（29MB），我该如何提供呢
> 
> 可以邮箱发送到 support@dgp-studio.cn，或者从Discord/QQ群里找到我私聊发来

已传送至邮箱，请查收

**Comment by Masterain98** [comment]
> 已传送至邮箱，请查收

我这里还没有收到。还是整个网盘分享吧。

**Comment by hoiyuyiu** [comment]
> > 已传送至邮箱，请查收
> 
> 我这里还没有收到。还是整个网盘分享吧。

 https://pan.baidu.com/s/1039e7QQ3VlkyBA1PnZmKTw 提取码：ow03

**Comment by Masterain98** [comment]
转发给卡巴斯基了

**Comment by Masterain98** [comment]
> I appreciate the patience you have shown. I apologize for my delayed response.
> 
> Our Virus Analysts have just replied, informing us that they forwarded the information to the responsible group.
> 
> We will inform you once an update becomes available.

**Comment by Masterain98** [comment]
> Dear customer,
> 
> Hello,
> 
> Thank you for your kind understanding and we appreciate your patience on this.
> 
> Please find our experts' response to your query below:
> 
> The detection has already been fixed on 23 Oct 2023.

Fixed
