### ISSUE TITLE
[Bug]: 国际服账号无法正常登录

### ISSUE THREAD

**Issue by zplinus** [DGP-Studio/Snap.Hutao#1042]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3570

### Snap Hutao 版本

1.7.11

### 设备 ID

BF215E3F584E6D63841D9FECD9C3E474

### 问题分类

角色信息面板

### 发生了什么？

打开客户端，选择使用HoYoLab登录
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/77de584d-56b7-44eb-a819-40d14659c9b2)

在登录后，选择”我已登录“，程序会闪退， 但是重新开启后，会看到账号如下：

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/1e0be630-5a06-47f6-91d7-cadb841bba27)

选择”我的角色“，会弹出一个空白的页面，并且一直空白，无法选择角色
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/203a9096-8bdb-46f8-b115-1a1c60c0b3d4)

想使用功能如深渊会提示需要选一个用户与角色，无法使用：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/4b8faeaf-7cee-4fee-bb8f-f0e8e0b8c1f9)

选择左侧”我的角色“里的任何一个选项，都没有反应
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/e6d2ff1e-476d-4b78-94ee-cd84abe72cdf)
（点上面的任何一个选项，都没有反应）

### 你期望发生的行为？

能够正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/53eb2237-40a1-4395-a058-ab5eb3848c20)

**Comment by Masterain98** [comment]
@Lightczx Exception on the uninitialized accounts to avoid the crash?

**Comment by Lightczx** [comment]
I need an account like this one

**Comment by zplinus** [comment]
> 在使用本功能前，你需要使用官方的米游社 App 登录你的帐号以初始化你的米游社功能

我已经在手机的app和网页上都登录过同一个账号了哇？虽然仍然显示的是user_xxx的格式
![f707ca558843d223e09a54973e9e784](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/f7c01081-1556-4fd7-9c47-f4ac0fe50cff)

**Comment by Masterain98** [comment]
问题还能持续复现吗？似乎确实和账号初始化无关。

**Comment by zplinus** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/3e6bd467-be78-416a-a110-8c4fd9d5de52)

我发现我这里没有用户名，我尝试创建一个再重新使用一下

**Comment by zplinus** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67522187/0ffb146c-b2fd-439d-b69c-6a5d5d1c77f0)
虽然我设置的名字，但是还是能复现，而且在列表里仍然显示的是旧user id （不知道是不是API这边有延迟需要Propagate？）

**Comment by zplinus** [comment]
> 问题还能持续复现吗？似乎确实和账号初始化无关。

稳定复现，每一次都一样，选择“我已登录”后鼠标几秒会变成loading的样子，然后程序会消失，重新打开后，有用户显示，但是没办法点角色

**Comment by Lightczx** [comment]
@zplinus 发送你的账号密码到 support@dgp-studio.cn

**Comment by Lightczx** [comment]
closing as no response
