### ISSUE TITLE
[Bug]: 无法启动游戏，已按照文档开启长路径功能但还是显示未开启

### ISSUE THREAD

**Issue by sweetcolaer** [DGP-Studio/Snap.Hutao#1043]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2428

### Snap Hutao 版本

1.7.11.0

### 设备 ID

146B90BDAD01C7C51325E2783A3AE25C

### 问题分类

游戏启动器

### 发生了什么？

我无法在工具箱中启动游戏，错误原因是RuntimeEnvironmentException未开启长路径功能，我在查询文档中发现了解决方法，下载压缩包解压运行添加注册表之后还是无法启动，错误依旧是RuntimeEnvironmentException未开启长路径功能，我后续自行寻找解决方法利用gpedit.msc启用win32长路径以及注册表中longpathsenabled的值后尝试依旧发生了错误，为此我来寻求帮助让我可以在工具箱里运行游戏

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by sweetcolaer** [comment]
<img width="303" alt="联想截图_20231024042606" src="https://github.com/DGP-Studio/Snap.Hutao/assets/125554784/c88227b2-1ef6-4e04-8a27-fca85aafe32c">
<img width="521" alt="联想截图_20231024042540" src="https://github.com/DGP-Studio/Snap.Hutao/assets/12
<img width="487" alt="联想截图_20231024042624" src="https://github.com/DGP-Studio/Snap.Hutao/assets/125554784/92170c80-9387-401c-9764-c63ddc10f35f">
5554784/9a677c08-96f8-42b6-8053-6a87f49807bf">

**Comment by sweetcolaer** [comment]
<img width="303" alt="联想截图_20231024042606" src="https://github.com/DGP-Studio/Snap.Hutao/assets/125554784/6c649a93-69dd-4ffc-a98c-bb450c9fc61b">
<img width="521" alt="联想截图_20231024042540" src="https://github.com/DGP-Studio/Snap.Hutao/assets/125554784/06749600-a5fb-4d78-9360-f049c104412b">

<img width="487" alt="联想截图_20231024042624" src="https://github.com/DGP-Studio/Snap.Hutao/assets/125554784/cab8ed63-c7a2-48e3-994e-e0081c27ad02">

**Comment by Lightczx** [comment]
装个Python试试，或者装商店里的powershell然后把胡桃使用的powershell指定为商店版的（虽然会很难找到安装位置）

closing as no code resolution can be provided
