### ISSUE TITLE
[ENG][Bug]: Converting Client

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao#1044]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [fixed issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D), and it's not a duplicated issue

### Windows Version

19044.3570

### Snap Hutao Version

1.7.11

### Device ID

FA1D62A0F8737EF738814EF8F70B6208

### Issue Category

Game Launcher

### What Happened?

Error while convert from Overseas to CN and vice versa.
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/5da0d115-19a3-4d01-b0bf-b5446ed98770)

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
network issue, check by yourself

**Comment by prpjzz** [comment]
i think your network it no issue, because i change from wireless to wired and the problem still happen.

**Comment by Lightczx** [comment]
Completely fine when ISP is China Mobile or China Telecom.

**Comment by Lightczx** [comment]
It's just because you have a unstable network

**Comment by prpjzz** [comment]
I tried it on another machine, and yes, maybe the problem was on my device.
