### ISSUE TITLE
[Bug]: CoreMessagingXP.dll错误

### ISSUE THREAD

**Issue by abc45628** [DGP-Studio/Snap.Hutao#1046]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2428

### Snap Hutao 版本

1.7.11.0

### 问题分类

安装和环境

### 发生了什么？

商店安装后就打开，提示下载环境，下载完就进去主界面，然后就卡主了，过十几秒就闪退了，。之后每次打开都是过十几秒闪退，期间一直都操作不了

错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x64e841c5
错误模块名称: CoreMessagingXP.dll，版本: 10.0.22624.1046，时间戳: 0xbc9f21de
异常代码: 0xc000027b
错误偏移量: 0x000000000008f52c
错误进程 ID: 0x0x914
错误应用程序启动时间: 0x0x1DA094853CFBB4E
错误应用程序路径: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
报告 ID: 2ed637b5-b77c-428d-b65a-572a647c567e
错误程序包全名: 60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86
错误程序包相对应用程序 ID: App

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
提供设备Id
