### ISSUE TITLE
[Bug]:打开胡桃直接卡死，之后闪退

### ISSUE THREAD

**Issue by Shenyuan220** [DGP-Studio/Snap.Hutao#1047]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2506

### Snap Hutao 版本

1.7.11.0

### 问题分类

用户界面

### 发生了什么？

如题，打开胡桃主界面后卡死无法操作，之后闪退
另外，我看到了已解决的问题内有一个进入启动游戏界面闪退的，不确定是不是与我的问题相同
设备ID尝试获取了，但是输出的十六进制字符串为空

### 你期望发生的行为？

希望正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
换台电脑试一下

**Comment by Shenyuan220** [comment]
今天拿朋友电脑试了，没问题了👌
