### ISSUE TITLE
[Bug]: 程序闪退

### ISSUE THREAD

**Issue by bingyunhe** [DGP-Studio/Snap.Hutao#1048]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

win11 22H2 22621.2428

### Snap Hutao 版本

微软商店下载最新版本

### 设备 ID

程序崩溃，脚本启用后同样闪退

### 问题分类

安装和环境

### 发生了什么？

启动后无响应，几秒后闪退

### 你期望发生的行为？

正常启动

https://github.com/DGP-Studio/Snap.Hutao/assets/75605943/87061b91-2dde-4b0b-930d-2c514d255112

### 最后一步

- [ ] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
脚本输出的ID呢

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/10e35141-4dfd-45a0-8935-fd426e731d51)
你是真的一项不做

**Comment by bingyunhe** [comment]
> ![image](https://user-images.githubusercontent.com/10614984/278796296-10e35141-4dfd-45a0-8935-fd426e731d51.png) 你是真的一项不做

我写了脚本也崩溃不显示，另外请问.net错误在哪里查看呢

**Comment by Masterain98** [comment]
事件查看器中很容易找到，如果你真的找不到可以试试 [这个脚本](https://github.com/DGP-Studio/ISSUE_TEMPLATES/releases/download/dump_log_script/dump_log_zh.ps1)

**Comment by bingyunhe** [comment]
> 事件查看器中很容易找到，如果你真的找不到可以试试 [这个脚本](https://github.com/DGP-Studio/ISSUE_TEMPLATES/releases/download/dump_log_script/dump_log_zh.ps1)

你好，我好像找到了

错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x64e841c5
错误模块名称: CoreMessagingXP.dll，版本: 10.0.22624.1046，时间戳: 0xbc9f21de
异常代码: 0xc000027b
错误偏移量: 0x000000000008f52c
错误进程 ID: 0x0x1110
错误应用程序启动时间: 0x0x1DA096B6265DE38
错误应用程序路径: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
报告 ID: dedca484-5cdb-4109-874f-03f14bbe7153
错误程序包全名: 60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86
错误程序包相对应用程序 ID: App

是否是这个

**Comment by Masterain98** [comment]
顺带一提，如果使用 Windows PowerShell 或者 Windows Terminal 执行 PowerShell 脚本，即使出现错误，窗口也不会退出

**Comment by bingyunhe** [comment]
> 顺带一提，如果使用 Windows PowerShell 或者 Windows Terminal 执行 PowerShell 脚本，即使出现错误，窗口也不会退出
> 
> 在下载脚本的目录，按住Shift+右键，选择在本目录使用 PowerShell，然后在 PS 窗口中输入 `./GetHutaoDeviceId.ps1` （建议使用 Tab 键自动补全）也是可以运行脚本的

好的，是我系统禁用脚本，启用后查询为794C8D0673CC830756E57F5D4551B982

**Comment by bingyunhe** [comment]
> /log 794C8D0673CC830756E57F5D4551B982

请问我应该如何提供更多系统信息来解决这个问题，因为我目前情况是像提供的视频那样可以稳定复现的

**Comment by Lightczx** [comment]
删除Userdata.db后重试

**Comment by bingyunhe** [comment]
> 删除Userdata.db后重试

删除后重试依旧闪退

**Comment by Lightczx** [comment]
加群反馈，需要安装 VisualStudio 远程调试

**Comment by bingyunhe** [comment]
> 加群反馈，需要安装 VisualStudio 远程调试

进群密码我找不到欸

**Comment by Masterain98** [comment]
现在应该是不需要密码的

**Comment by bingyunhe** [comment]
> 现在应该是不需要密码的

那不知道啊，一群一直不放我进去
