### ISSUE TITLE
[ENG][Bug]: 启动胡桃崩溃

### ISSUE THREAD

**Issue by Wang-zhechao** [DGP-Studio/Snap.Hutao#1049]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [fixed issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D), and it's not a duplicated issue

### Windows Version

windows11 22H2

### Snap Hutao Version

1.7.11.0

### Issue Category

File Cache

### What Happened?

1.打开胡桃 

预期：
成功启动到界面
实际：
程序崩溃闪退

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Wang-zhechao** [comment]
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/1049#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/1049#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-10-28T07:17:32.8954971Z" /> 
  <EventRecordID>24615</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="18272" ThreadID="4180" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-4RJI65F</Computer> 
  <Security UserID="S-1-5-21-3356211426-2117375148-2701888102-1001" /> 
  </System>
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/1049#) <EventData>
  <Data Name="AppName">Snap.Hutao.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">64e841c5</Data> 
  <Data Name="ModuleName">CoreMessagingXP.dll</Data> 
  <Data Name="ModuleVersion">10.0.22624.1046</Data> 
  <Data Name="ModuleTimeStamp">bc9f21de</Data> 
  <Data Name="ExceptionCode">c000027b</Data> 
  <Data Name="FaultingOffset">000000000008f52c</Data> 
  <Data Name="ProcessId">0x2a9c</Data> 
  <Data Name="ProcessCreationTime">0x1da096ecfb8ba7e</Data> 
  <Data Name="AppPath">C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86\Snap.Hutao.exe</Data> 
  <Data Name="ModulePath">C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll</Data> 
  <Data Name="IntegratorReportId">4c3472a6-edc5-4308-90e8-67e3cefc5aaf</Data> 
  <Data Name="PackageFullName">60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86</Data> 
  <Data Name="PackageRelativeAppId">App</Data> 
  </EventData>
  </Event>

**Comment by Wang-zhechao** [comment]
日志名称:          Application
来源:            Application Error
日期:            2023/10/28 15:17:32
事件 ID:         1000
任务类别:          应用程序崩溃事件
级别:            错误
关键字:           
用户:            DESKTOP-4RJI65F\475031247
计算机:           DESKTOP-4RJI65F
描述:
错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x64e841c5
错误模块名称: CoreMessagingXP.dll，版本: 10.0.22624.1046，时间戳: 0xbc9f21de
异常代码: 0xc000027b
错误偏移量: 0x000000000008f52c
错误进程 ID: 0x0x2A9C
错误应用程序启动时间: 0x0x1DA096ECFB8BA7E
错误应用程序路径: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
报告 ID: 4c3472a6-edc5-4308-90e8-67e3cefc5aaf
错误程序包全名: 60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86
错误程序包相对应用程序 ID: App
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-10-28T07:17:32.8954971Z" />
    <EventRecordID>24615</EventRecordID>
    <Correlation />
    <Execution ProcessID="18272" ThreadID="4180" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-4RJI65F</Computer>
    <Security UserID="S-1-5-21-3356211426-2117375148-2701888102-1001" />
  </System>
  <EventData>
    <Data Name="AppName">Snap.Hutao.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">64e841c5</Data>
    <Data Name="ModuleName">CoreMessagingXP.dll</Data>
    <Data Name="ModuleVersion">10.0.22624.1046</Data>
    <Data Name="ModuleTimeStamp">bc9f21de</Data>
    <Data Name="ExceptionCode">c000027b</Data>
    <Data Name="FaultingOffset">000000000008f52c</Data>
    <Data Name="ProcessId">0x2a9c</Data>
    <Data Name="ProcessCreationTime">0x1da096ecfb8ba7e</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86\Snap.Hutao.exe</Data>
    <Data Name="ModulePath">C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll</Data>
    <Data Name="IntegratorReportId">4c3472a6-edc5-4308-90e8-67e3cefc5aaf</Data>
    <Data Name="PackageFullName">60568DGPStudio.SnapHutao_1.7.11.0_x64__ebfp3nyc27j86</Data>
    <Data Name="PackageRelativeAppId">App</Data>
  </EventData>
</Event>

**Comment by Lightczx** [comment]
加群反馈

**Comment by Lightczx** [comment]
不要加开发群

**Comment by Lightczx** [comment]
你是在哪看到的开发群号，发截图
