### ISSUE TITLE
[已有功能优化建议]：F8自动连点

### ISSUE THREAD

**Issue by nhzx** [DGP-Studio/Snap.Hutao#1058]
### 背景与动机

在胡桃工具箱运行过程中，如果期间打开其他软件，软件中包含快捷键为F8(及其相关快捷键）时，会出现连点效果从而干扰其他软件的正常运行。

### 想要实现或优化的功能

在设置中添加“启用F8自动连点功能”选项开关，可以在用户不需要该功能时禁用该功能以避免不必要的麻烦

**Comment by Lightczx** [comment]
#961

**Comment by Masterain98** [comment]
Duplicate of #961
