### ISSUE TITLE
[Bug]: 无法注册胡桃账号

### ISSUE THREAD

**Issue by 1235789gzy1** [DGP-Studio/Snap.Hutao#1059]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3570

### Snap Hutao 版本

1.7.14.0

### 设备 ID

4C6F0BC012F7073F788AB48EA0C8BE7D

### 问题分类

胡桃帐号

### 发生了什么？

无法注册胡桃账号，获取并填入验证码后，点击密码输入框仍然无法输入密码

### 你期望发生的行为？

输入正确的验证码后能够输入密码

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/ffc6ff16-b07a-4269-b1c0-0d72f638d977)

验证码长度感觉也可以限制一下
