### ISSUE TITLE
[Bug]: 通过米游社接口获取角色信息报错5003

### ISSUE THREAD

**Issue by mengluo04** [DGP-Studio/Snap.Hutao#1060]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.1.14

### 问题分类

角色信息面板

### 发生了什么？

从米游社获取数据相关接口全部报错5003

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by mengluo04** [comment]
> 请更新至最新版本: 稳定版: [1.7.14](https://apps.microsoft.com/store/detail/snap-hutao/9PH4NXJ2JN52) 测试版: [2023.10.31.6](https://github.com/DGP-Studio/Snap.Hutao/releases/download/2023.10.31.6/Snap.Hutao.Alpha-2023.10.31.6.msix)

打错版本号了，release页面下载的最细的，1.7.14

**Comment by version4** [comment]
已更新到1.7.14版本，还是报错5003

**Comment by a251231** [comment]
遇到了同样的错误 已更新到1.7.15版本，还是报错5003

**Comment by mengluo04** [comment]
> 遇到了同样的错误 已更新到1.7.15版本，还是报错5003

现在还是等待发布状态，代码还在开发分支，估计要等等

**Comment by Masterain98** [comment]
> 现在还是等待发布状态，代码还在开发分支，估计要等等

周末不会发更新，因为我们提交了微软也因为非工作日而不会审核

**Comment by Lightczx** [comment]
4.2更新前不会发布新版本

**Comment by Jerry-code-Song** [comment]
我于2023.12.14在1.8.4版本中实时便笺页刷新角色信息时遇到了这个问题，并且在昨天仍然成功刷新获取了信息，具体报错为：

状态：5003|信息：

**Comment by mengluo04** [comment]
> 我于2023.12.14在1.8.4版本中实时便笺页刷新角色信息时遇到了这个问题，并且在昨天仍然成功刷新获取了信息，具体报错为：
> 
> 状态：5003|信息：
目前只有在实时便签页面点验证账号，使用webview嵌入米游社的便签页面进行账号验证才能正常使用

**Comment by Mqpzi** [comment]
1.8.4依然报错，状态：1034｜信息：验证失败，请手动验证或前往「米游社—我的角色」页面查看

**Comment by Lightczx** [comment]
米桑上强度了🤡

**Comment by mengluo04** [comment]
> 1.8.4依然报错，状态：1034｜信息：验证失败，请手动验证或前往「米游社—我的角色」页面查看

风控好像又升级了

**Comment by mengluo04** [comment]
> 米桑上强度了🤡

最开始是星铁加了验证码，然后原也加了，然后星铁又加了设备注册，模拟一下就行了，原这边不行，打码验证了都报5003

**Comment by Jerry-code-Song** [comment]
早前用的寻空在这方面G了很久了，不意外另外，星铁也有对应的APP吗，请问叫什么，我想下载一下
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年12月14日 22:04
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [DGP-Studio/Snap.Hutao] [Bug]: 通过米游社接口获取角色信息报错5003 (Issue #1060)
        
      
    
  


米桑上强度了🤡

最开始是星铁加了验证码，然后原也加了，然后星铁又加了设备注册，模拟一下就行了，原这边不行，打码验证了都报5003

**Comment by Jerry-code-Song** [comment]
早前用的寻空在这方面G了很久了，不意外~~另外，星铁也有对应的APP吗，请问叫什么，我想下载一下

**Comment by mengluo04** [comment]
> 早前用的寻空在这方面G了很久了，不意外~~另外，星铁也有对应的APP吗，请问叫什么，我想下载一下

有QQ群机器人或者QQ频道机器人，我是从开源项目拿的接口和参数，自己处理的数据

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7210491356
可以试试这个，但是对我自己并不管用

**Comment by Jerry-code-Song** [comment]
> > 早前用的寻空在这方面G了很久了，不意外~~另外，星铁也有对应的APP吗，请问叫什么，我想下载一下
> 
> 有QQ群机器人或者QQ频道机器人，我是从开源项目拿的接口和参数，自己处理的数据

咦？QQ群还有这个功能？可以拉我进群吗

**Comment by mengluo04** [comment]
> > > 早前用的寻空在这方面G了很久了，不意外~~另外，星铁也有对应的APP吗，请问叫什么，我想下载一下
> > 
> > 
> > 有QQ群机器人或者QQ频道机器人，我是从开源项目拿的接口和参数，自己处理的数据
> 
> 咦？QQ群还有这个功能？可以拉我进群吗

不是群的功能，是单独部署的服务，把qq消息监听了而已，b站随便搜一下都有很多群
