### ISSUE TITLE
关于分辨率列表

### ISSUE THREAD

**Issue by liuzipeng** [DGP-Studio/Snap.Hutao#1062]
### 背景与动机

个人经常使用窗口化和全屏之间切换，每次手手动输入分辨率太麻烦，希望能添加一个选项列表，列出常见分辨率，和自定义分辨率

### 想要实现或优化的功能

个人经常使用窗口化和全屏之间切换，每次手手动输入分辨率太麻烦，希望能添加一个选项列表，列出常见分辨率，和自定义分辨率

**Comment by Lightczx** [comment]
@liuzipeng 你正在使用哪些分辨率

**Comment by liuzipeng** [comment]
2560*1440 & 1920*1080

**Comment by wazk9595** [comment]
> 2560_1440 & 1920_1080

你可以试着按下ALT+ENTER来切换全屏与窗口化
