### ISSUE TITLE
[Feat]: 右键启动游戏，只有一个账号，跳过账号选择

### ISSUE THREAD

**Issue by yxok200** [DGP-Studio/Snap.Hutao#1066]
### 背景与动机

就是磁贴右键启动的时候，如果只有一个账号，能否跳过账号选择直接启动游戏呢
QAQ咸鱼期日常收菜，想着能省一步是一步吧【捂脸】

### 想要实现或优化的功能

就是磁贴右键启动的时候，如果只有一个账号，能否跳过账号选择直接启动游戏呢
QAQ咸鱼期日常收菜，想着能省一步是一步吧【捂脸】

**Comment by Lightczx** [comment]
由于启动时必须要校验游戏客户端服务器类型，必须弹出对话框，因此无法在没有任何窗口打开的情况下实现此功能
