### ISSUE TITLE
[Bug]:实时便签验证用户失败

### ISSUE THREAD

**Issue by limory01** [DGP-Studio/Snap.Hutao#1067]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2506

### Snap Hutao 版本

1.7.14.0

### 设备 ID

96CC673BAACEA853467DF3CEFF5CF14A

### 问题分类

实时便笺

### 发生了什么？

 实时便签界面，验证当前用户与角色失败。
![屏幕截图 2023-11-01 165516](https://github.com/DGP-Studio/Snap.Hutao/assets/75538429/3267b228-84b2-4aa1-8c52-b4e52c0e5020)

一直显示当前账号存在风险，暂无数据。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by limory01** [comment]
已更新至最新版本，仍未解决。

**Comment by Lightczx** [comment]
#1060
