### ISSUE TITLE
养成计划数量过多时，滑动滚轮无法让单个角色及武器下的材料进行滚动，只能让整个界面滚动

### ISSUE THREAD

**Issue by wazk9595** [DGP-Studio/Snap.Hutao#1068]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2506

### Snap Hutao 版本

1.7.15.0

### 设备 ID

664D840C39095D3A9387FC434462826F

### 问题分类

养成计算

### 发生了什么？

当养成计划数量过多时，超过了整个屏幕界面，这个时候滑动滚轮无法让单个角色及武器下的材料进行滚动，只能让整个界面滚动。

### 你期望发生的行为？

在将鼠标移动到指定的角色及武器上并且滑动滚轮时，可以使指定的目标滚动，而不是让整个界面滚动。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/3693699d-d1cb-4fb7-b1d3-24f84e0294e9)

不知道这样看上去怎么样
