### ISSUE TITLE
[Feat]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by Chris20020101** [DGP-Studio/Snap.Hutao#107]
### 你想要实现或优化的功能？

解锁帧数启动游戏，感谢

**Comment by AdminRoc** [comment]
你好，如[SnapGenshin](https://github.com/DGP-Studio/Snap.Genshin) 项目的Readme以及胡桃的[项目首页](https://hut.ao/) 所示，这些常用功能都会陆续迁移至Hutao项目中，敬请期待。
