### ISSUE TITLE
[Bug]: 设置页面滑动到最底部后往上滑动失效

### ISSUE THREAD

**Issue by bbcyz** [DGP-Studio/Snap.Hutao#1072]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2506

### Snap Hutao 版本

1.7.15.0

### 设备 ID

64F225E85AB88AA3BFBA9115BA88A2AE

### 问题分类

用户界面

### 发生了什么？

如图，当设置页面滑动到最底部时，再向上方滑动将会失效，表现为滑动又瞬间返回底部
![1221](https://github.com/DGP-Studio/Snap.Hutao/assets/71243267/40d54294-af64-403a-adab-0c5603e22077)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
无法复现，可以在管理员模式下尝试

**Comment by qhy040404** [comment]
复现步骤：**没有maintainer和LicensedDeveloper权限的胡桃账号**
设置拉到如图位置，刚好是胡桃账号那个Expander中item被重载的位置

可能是因为那两个有权限的card的visibility默认是visible，重载导致整个页面拉长又变短

**Comment by Lightczx** [comment]
依旧无法复现

**Comment by qhy040404** [comment]
https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/f0a19432-de36-43d1-9554-9683545dbbbb

主要就卡在胡桃账户那个expander里的item重载不上

**Comment by Lightczx** [comment]
@bbcyz @qhy040404 可以看下这个 Windows 设置的值么
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/3b9d7879-f6e1-4043-8021-f33281054190)

**Comment by qhy040404** [comment]
3

**Comment by Lightczx** [comment]
改成5看看能不能复现 @qhy040404

**Comment by qhy040404** [comment]
不稳定复现

**Comment by Lightczx** [comment]
滚动的稍微快一点都复现不出来🤡

**Comment by qhy040404** [comment]
🤣👉

**Comment by bbcyz** [comment]
> @bbcyz @qhy040404 可以看下这个 Windows 设置的值么 ![image](https://user-images.githubusercontent.com/36357191/280601187-3b9d7879-f6e1-4043-8021-f33281054190.png)

和开发者的一样
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/71243267/510b0942-1ebf-4baf-93c3-534a5ba16789)
