### ISSUE TITLE
为资源下载添加复制按钮

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1074]
### 背景与动机

不用打开浏览器了

### 想要实现或优化的功能

1. 在对应资源后添加复制按钮
2. 在分组行里添加一个复制按钮能复制该组内全部资源的链接，一行一个资源链接

**Comment by Lightczx** [comment]
> 1. 在对应资源后添加复制按钮

Done

> 2\. 在分组行里添加一个复制按钮能复制该组内全部资源的链接，一行一个资源链接

Working

**Comment by qhy040404** [comment]
416c6f15a66e1b0abfd7601dd908ac6fc04fb650 这个不是变成只能复制了吗

**Comment by Lightczx** [comment]
> [416c6f1](https://github.com/DGP-Studio/Snap.Hutao/commit/416c6f15a66e1b0abfd7601dd908ac6fc04fb650) 这个不是变成只能复制了吗

Intended
