### ISSUE TITLE
[Bug]: 关于养成计划中新建计划的使用

### ISSUE THREAD

**Issue by Waldbeisepel** [DGP-Studio/Snap.Hutao#1079]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2506

### Snap Hutao 版本

1.7.16.0

### 设备 ID

A324F3BC0FB987218CD034F5C4C325FE

### 问题分类

养成计算

### 发生了什么？

在1.7.16.0版本更新之前，**养成计划中的新建计划**即使不同的计划单加入了**相同的角色**之间**是互不干扰的**。例如计划A中加入那维莱特天赋1/1/1升级至10/10/10，计划B中加入那维莱特天赋8/8/8升级至10/10/10是互不干扰的，但在更新之后更改计划B的那维天赋等级会同步到计划A里

### 你期望发生的行为？

希望可以像之前那样，养成计划中的新建计划之间互不影响

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
实际上是 ItemRepeater的首个物品没有刷新导致的

**Comment by Lightczx** [comment]
暂时可以通过将项目滚动到可见区域外后滚动回来修改物品完成情况
