### ISSUE TITLE
[Bug]: 武器祈愿大保底计算出错

### ISSUE THREAD

**Issue by Twilight217** [DGP-Studio/Snap.Hutao#108]
### Windows 版本

19042.1706

### Snap Hutao 版本

1.1.9.0

### 发生了什么？

![image](https://user-images.githubusercontent.com/44659263/195841630-40f1a399-519f-4945-9e25-3f60273be396.png)
武器大保底计算出错，如图，有过崩溃，反复导入数据后显示记录，uigf_json与log.db文件在压缩包内
[file.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9785983/file.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
正常的数据是什么样的@Twilight217

**Comment by Twilight217** [comment]
> 正常的数据是什么样的@Twilight217

若水不是大保底，终末也不是大保底，赤沙才是大保底，剩下的都没错

**Comment by Lightczx** [comment]
保底与定轨非同个机制
