### ISSUE TITLE
[Feat]: 为 Snap Hutao 添加 Discord Rich Presence

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1082]
### 背景与动机

Docs: https://discord.com/developers/docs/rich-presence/how-to
类似的还有国内平台：https://developer.kookapp.cn/doc/http/game

### 想要实现或优化的功能

- [ ] 显示 Snap Hutao 运行状态，增加跳转胡桃官网和 Discord 频道的按钮
- [ ] 在国服游戏时增加原神的游戏状态
- [ ] 功能应当是可关闭的

**Comment by Lightczx** [comment]
SDK WIP https://github.com/DGP-Studio/Snap.Discord.GameSDK
