### ISSUE TITLE
[Bug]: 启动游戏 页面崩溃

### ISSUE THREAD

**Issue by 1235789gzy1** [DGP-Studio/Snap.Hutao#1083]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621

### Snap Hutao 版本

1.7.16.0

### 设备 ID

903A34B361A9F2C9F61E60BC38ACD646

### 问题分类

游戏启动器

### 发生了什么？

点击胡桃的 启动游戏 界面按钮后，胡桃崩溃
官方启动器和游戏本体均可以启动原神

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by 1235789gzy1** [comment]
https://github.com/DGP-Studio/Snap.Hutao/assets/52618207/58f9bb16-36ea-48d4-83a8-0a3ff4bc2f6a

**Comment by Masterain98** [comment]
视频上传失败。检查是否有系统日志中的错误。

**Comment by 1235789gzy1** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52618207/c96e8f18-ec57-4cdf-bec1-7c42a44b3218)

错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x653067fb
错误模块名称: CoreMessagingXP.dll，版本: 10.0.22624.1046，时间戳: 0xbc9f21de
异常代码: 0xc000027b
错误偏移量: 0x000000000008f52c
错误进程 ID: 0x0x46B4
错误应用程序启动时间: 0x0x1DA13D08252A0D4
错误应用程序路径: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.16.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
报告 ID: b35257cb-0926-46e4-a2e2-5c22c40b40c4
错误程序包全名: 60568DGPStudio.SnapHutao_1.7.16.0_x64__ebfp3nyc27j86
错误程序包相对应用程序 ID: App
