### ISSUE TITLE
[Bug]: 登录成功等弹窗未翻译

### ISSUE THREAD

**Issue by Tangweirui2021** [DGP-Studio/Snap.Hutao#1088]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.2700

### Snap Hutao 版本

1.7.16

### 问题分类

用户界面

### 发生了什么？

在登录成功时产生的弹窗的结果未翻译
![屏幕截图 2023-11-11 143944](https://github.com/DGP-Studio/Snap.Hutao/assets/85839291/5a943881-9611-4955-beb2-f074d9f87fe4)
查看代码后发现弹窗直接使用了服务端的返回值
![屏幕截图 2023-11-11 145755](https://github.com/DGP-Studio/Snap.Hutao/assets/85839291/e02732e9-d17b-4997-9361-31ac2689f49f)
其它的一些代码也存在直接使用未翻译的返回值的情况

### 你期望发生的行为？

弹窗内容应当在客户端解析返回值后显示对应语言的信息

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Tangweirui2021** [comment]
如果可以的话，我希望可以让我修改代码进行贡献

**Comment by Lightczx** [comment]
> 其它的一些代码也存在直接使用未翻译的返回值的情况

能全部指出一下么 @Tangweirui2021

**Comment by Tangweirui2021** [comment]
目前我还没有完全检查，但是可以确认的是在同一个文件中的
RegisterCommand、UnregisterCommand、ResetPasswordCommand
都直接使用了返回的 response.Message

**Comment by Tangweirui2021** [comment]
已经提交PR
