### ISSUE TITLE
[Bug]: 使用的是最新的版本却提示需要升级

### ISSUE THREAD

**Issue by JulienZeng** [DGP-Studio/Snap.Hutao#1093]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2428

### Snap Hutao 版本

1.7.16

### 设备 ID

2023955FCAC72C29A01C501401674050

### 问题分类

用户界面

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/77975074/38bc2fb7-f43d-4001-acfa-233bc2c2386c)
如图，左上角版本号与官网文档中的最新版本一致，但提示版本过低，而且除了主页和启动游戏这两个界面可以正常使用外，其他所有页面都为空或者显示加载中。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Cat-in-Rosemary** [comment]
https://status.hut.ao/#/
服务器似乎有问题

**Comment by JulienZeng** [comment]
那好多看起来可以脱机使用的功能在服务器出现异常的情况下不能使用，是不是不太合理

**Comment by Masterain98** [comment]
部分元数据文件（频繁热更新的角色信息、武器信息）所使用的云托管服务出现了问题，正在处理，预计在数分钟之内恢复正常。


> 那好多看起来可以脱机使用的功能在服务器出现异常的情况下不能使用，是不是不太合理

因为在部分版本中元数据会出现 break change，所以胡桃会对部分元数据网络请求中的错误进行一次判断。若错误状态和预期的一致，客户端会判断有新的 break change，从而将错误转化为更新提示，以避免闪退的问题。本次出现的问题应该是 404 文件不存在错误。

**Comment by Masterain98** [comment]
> https://status.hut.ao/#/ 服务器似乎有问题

感谢提醒。监控数据源出现了问题，是一个凑巧发生的，另一个故障。💔

**Comment by Masterain98** [comment]
如果仍然有问题请直接at我

**Comment by Lightczx** [comment]
> 本次出现的问题应该是 404 文件不存在错误。

能转成其他的错误代码么 @Masterain98

**Comment by Masterain98** [comment]
Expect to be fixed by DGP-Studio/General-Management#6
