### ISSUE TITLE
祈愿记录——导入UIGF Json功能无法使用，且提供的报错通知有误

### ISSUE THREAD

**Issue by NIANHUAmoran** [DGP-Studio/Snap.Hutao#1095]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2428

### Snap Hutao 版本

1.7.16.0

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录——导入UIGF Json功能无法使用，程序提供的报错消息为：“无法打开文件选择器，轻勿在管理员模式下使用此功能 找不到元素，(0x88070490)”，但已经在Powershell中修改了打开指令为C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Start-Process shell:AppsFolder\60568DGPStudio.SnapHutao_ebfp3nyc27j86!App“，去掉了以管理员方式启动的-Verb RunAs选项依旧显示如上报错消息，在普通模式启动下的实时便笺——通知设置已经可以正常设置(原本此功能也需要在非管理员模式下启动)，在寻求多方帮助后依旧无法解决此问题，合理怀疑本程序的导入UIGF Json功能或者文件选择器打开功能存在BUG，望尽快修复，我的6个月之前的祈愿记录只能通过此方式导入，已购买胡桃云，望早日将记录通过导入UIGF Json的方式添加到胡桃工具箱，再传至胡桃云中，感谢

### 你期望发生的行为？

我期望能成功在程序内打开文件选择器，导入我的UIGF Json

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你试过从开始菜单启动么

**Comment by NIANHUAmoran** [comment]
> 你试过从开始菜单启动么 @NIANHUAmoran
当然试过，也是同样的结果

**Comment by NIANHUAmoran** [comment]
我可以把我的json发给你导入吗

**Comment by Lightczx** [comment]
你可以加一下 928732285 并且遵照指引设置下环境方便我远程调试一下么

**Comment by Lightczx** [comment]
Will be fixed once #1096 fixed
