### ISSUE TITLE
养成计划闪退！

### ISSUE THREAD

**Issue by Ancoruza** [DGP-Studio/Snap.Hutao#1097]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19044.3208

### Snap Hutao 版本

1.7.17

### 设备 ID

CADF23F9A77B3072F4309CCEE3037EE2

### 问题分类

养成计算

### 发生了什么？

【养成计划】功能闪退。
无论是直接点击[养成计划]，还是在【角色】或【武器】资料界面里添加，都会促使软件闪退无法使用。

### 你期望发生的行为？

修复此BUG
使功能可正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
导出祈愿与成就数据后删除Userdata.db

**Comment by Ancoruza** [comment]
【养成计划】功能虽以恢复正常。但出现“刷新异常”现象。。
首次[添加角色计划]正常显示，再新建[武器计划]后[角色]里面的部分内容被替换为[武器]内容
再次更新[角色]内容，[武器]内容又显示为[角色]部分内容
> 首次[添加角色计划] ——正常显示
![QQ截图20231114131634](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/4ca44a94-82da-4a9e-8cd3-812f0fad7af3)

> 新建[添加武器计划] ——正常显示
![QQ截图20231114131747](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/ceea8760-3435-4def-b42f-b09a8cfbcb80)

> 查看[角色计划] 一栏——显示异常，部分内容被“新添置的武器计划”顶替
![QQ截图20231114131803](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/fe7443f0-4329-4abc-bc95-397d2cd20f3f)

> 重新更新[角色计划] → 查看[武器计划] 一栏——显示异常，部分内容被“新添置的角色计划”顶替
![QQ截图20231114131847](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/e89e6852-0d97-4ee1-9655-06cfdcd4f12c)
![QQ截图20231114131902](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/5554b58d-3c5d-4d2c-94d1-b067d3c782d5)
