### ISSUE TITLE
[Bug]: 养成计划“添加新资料”后显示异常

### ISSUE THREAD

**Issue by Ancoruza** [DGP-Studio/Snap.Hutao#1099]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19044.3208

### Snap Hutao 版本

1.7.17

### 设备 ID

CADF23F9A77B3072F4309CCEE3037EE2

### 问题分类

养成计算

### 发生了什么？

【养成计划】功能出现“添加新资料”后显示异常现象
首次[添加角色计划资料]正常显示，再新建[武器计划资料]后[角色计划]里面的部分内容被替换为[刚添加武器资料]内容
再次更新[角色]内容，[武器]内容又显示为[角色]部分内容

### 你期望发生的行为？

修复此问题
使界面正常显示

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Ancoruza** [comment]
附图：

> 首次[添加角色计划] ——正常显示
![01-首次 添加角色计划  ——正常显示](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/21f5c7cb-c953-468d-ac2e-3482afaebd1a)

> 新建[添加武器计划] ——正常显示
![02-新建 添加武器计划  ——正常显示](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/17907a66-2bda-4a46-a625-f37bbb7676be)

> 查看[角色计划] 一栏——显示异常，部分内容被"新添置的武器计划"顶替
![03-查看 角色计划  一栏——显示异常，部分内容被新添置的武器计划顶替](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/a0e5643e-5bf7-4401-ae31-e96ad4eed0ad)

> 重新更新[角色计划] → 查看[武器计划] 一栏——显示异常，部分内容被"新添置的角色计划"顶替
![04-重新更新 角色计划  → 查看 武器计划  一栏——显示异常，部分内容被新添置的角色计划顶替(1)](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/8b341a0c-fbac-47ff-a411-a8dc261725a0)
![04-重新更新 角色计划  → 查看 武器计划  一栏——显示异常，部分内容被新添置的角色计划顶替(2)](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/c946663a-0064-4186-b9c5-00d46cb5372f)

**Comment by Lightczx** [comment]
> 重新更新[角色计划] → 查看[武器计划] 一栏——显示异常，部分内容被"新添置的角色计划"顶替

这个时候是正常的吧

**Comment by Ancoruza** [comment]
是的。
这个是[角色资料]被后添加的[武器资料]篡改后，又重新“添加了一次[角色资料]”，所以显示正常了。但同时，[武器资料]又被篡改了

**Comment by Ancoruza** [comment]
附动图：

> 
![BUG 养成计划显示异常(压缩)](https://github.com/DGP-Studio/Snap.Hutao/assets/150766705/f81c879a-dc18-49aa-bb7b-038e3b2edf13)

**Comment by Lightczx** [comment]
> [武器资料]又被篡改了

只是显示问题，实际数据再不修改的情况下重启可以正常显示

**Comment by Lightczx** [comment]
新版本实际上依旧存在非第一排的物品刷新异常的问题
