### ISSUE TITLE
[Feat]: 在有胡桃云权限的情况下添加部分自动操作

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1100]
### 背景与动机

增强数据可靠性

### 想要实现或优化的功能

在客户端已登录胡桃账号且有权限的情况下：
- 获取深渊记录后自动上传战斗记录
- 获取祈愿数据后自动上传祈愿记录

上述行为应可以关闭

**Comment by Lightczx** [comment]
Tracked by #1394
