### ISSUE TITLE
[Feat]: 关于启动游戏里的服务器切换功能

### ISSUE THREAD

**Issue by Avenger233** [DGP-Studio/Snap.Hutao#1102]
### 背景与动机

![37b79482b9014a90cc134d88ef773912b31bee72](https://github.com/DGP-Studio/Snap.Hutao/assets/51845433/48ec24ae-0efd-4f66-a3eb-90f4e58e83d1)

### 想要实现或优化的功能

可否单独拿出，或者只替换文件，并不启动游戏

**Comment by Lightczx** [comment]
不启动的理由是什么 @Avenger233

**Comment by Lightczx** [comment]
你应该让别的东西去做转服

**Comment by Masterain98** [comment]
建议先学会好好说话 :)
