### ISSUE TITLE
[Bug]: 深境螺旋的怪物配置不正确 (2023.11.16-2023.12.01期)

### ISSUE THREAD

**Issue by yamei333** [DGP-Studio/Snap.Hutao#1104]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3570

### Snap Hutao 版本

1.7.17.0

### 问题分类

其它

### 发生了什么？

深境螺旋的怪物配置不正确 (2023.11.16-2023.12.01期)
※我在对比 http://www.yuhengcup.top/abyss 之后发现数据是测试服v1的数据

### 你期望发生的行为？

深境螺旋的怪物配置正确

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Metadata/commit/9cdff42e6153d0e38a347b17213a69fc26d20d9a

**Comment by yamei333** [comment]
如何刷新新数据呢, 我现在点击界面上的刷新数据似乎没有效果

**Comment by Lightczx** [comment]
等待我们的部署完成，后再次启动即可，大概需要10-30分钟

**Comment by Lightczx** [comment]
国内用户会下载[此镜像](https://jihulab.com/DGP-Studio/Snap.Metadata)内的文件.
等待其同步后触发自动部署。
