### ISSUE TITLE
[Feat]: 快捷兑换cdk

### ISSUE THREAD

**Issue by qhy040404** [DGP-Studio/Snap.Hutao#1107]
### 背景与动机

做完部分发放cdk的活动后快捷兑换兑换码

### 想要实现或优化的功能

在胡桃里兑换游戏兑换码

### 附加内容

CHN:
https://hk4e-api.mihoyo.com/common/apicdkey/api/exchangeCdkey

Host: hk4e-api.mihoyo.com
User-Agent: UnityPlayer/2017.4.30f1 (UnityWebRequest/1.0, libcurl/7.51.0-DEV)
Accept: */*
Accept-Encoding: identity
X-Unity-Version: 2017.4.30f1

sign_type	2
auth_appid	apicdkey
authkey_ver	1
cdkey	CDKCDKCDKCDK
lang	zh-cn
device_type	pc
game_version	(from YuanShen_Data\Persistent\audio_revision data_revision silence_revision)
authkey	authkey
game_biz	hk4e_cn

Hoyoverse:
https://sg-hk4e-api.hoyoverse.com/common/apicdkey/api/webExchangeCdkey (Hoyolab api from https://genshin.hoyoverse.com/en/gift)

Default cookie (Hoyolab)

uid
region
cdkey
game_biz
lang

**Comment by Lightczx** [comment]
国服的兑换码需要抓取游戏内Authkey才能正常使用，仅国际服可实现无抓取兑换操作
