### ISSUE TITLE
[Feat]: 怪物图鉴添加怪物全身图

### ISSUE THREAD

**Issue by AllesUgo** [DGP-Studio/Snap.Hutao#1108]
### 背景与动机

部分怪物的头像相似，难以区分。  
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67179426/0755df19-a431-4cf7-957b-356a8e7353b9)

### 想要实现或优化的功能

在怪物图鉴中添加怪物全身图，就像角色图鉴一样，方便区分不同的怪物。

**Comment by Lightczx** [comment]
只有周本Boss存在全身图
