### ISSUE TITLE
【功能请求】希望可以在祈愿界面添加一个复制祈愿url的按钮

### ISSUE THREAD

**Issue by liuzipeng** [DGP-Studio/Snap.Hutao#1109]
### 背景与动机

想要复制url在隔壁使用

### 想要实现或优化的功能

希望可以在祈愿界面添加一个复制祈愿url的按钮

**Comment by Lightczx** [comment]
具体是哪款应用 @liuzipeng

**Comment by Lightczx** [comment]
closing for no response
