### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by f59375543** [DGP-Studio/Snap.Hutao#111]
### Windows 版本

19044.2006

### Snap Hutao 版本

1.1.9

### 发生了什么？

选择导入Excel没有反应

![捕获](https://user-images.githubusercontent.com/43315911/195980237-8f7b696d-cd4f-41e7-9b06-dcbf36782e13.PNG)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
#47
