### ISSUE TITLE
[Feat]: 将“游戏路径”设置和其它用户数据分开存放

### ISSUE THREAD

**Issue by dingwen07** [DGP-Studio/Snap.Hutao#1115]
### 背景与动机

使用 OneDrive 等云存储的[已知文件夹移动](https://learn.microsoft.com/zh-cn/sharepoint/redirect-known-folders)功能时，用户的“文档”目录会被跨设备同步，然而“游戏路径”设置是特定于设备的，因此不应该和其他可以漫游的设置和数据一起存放在用户文档目录下。

虽然提供了更改整个数据目录的功能，但是这样就不能使用云存储同步数据了。

### 想要实现或优化的功能

将特定于设备的设置保存到 `%LOCALAPPDATA%` 下。

**Comment by Lightczx** [comment]
实现 #526 后可以解决这个问题
