### ISSUE TITLE
[Bug]: 自动连点无法使用 Alt 辅助按键

### ISSUE THREAD

**Issue by Ireeul** [DGP-Studio/Snap.Hutao#1119]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2715

### Snap Hutao 版本

1.8.0.0

### 设备 ID

529ADD8D820ABD958975CA17A43BF644

### 问题分类

其它

### 发生了什么？

版本更新后连点功能似乎无法正常生效了，尝试过切换开关修改按键都没有成功开启过连点功能。另外切换在关之后再次打开程序会没法重新打开自动连点在右上角的UI，功能由于不生效也不知道有没有问题。

### 你期望发生的行为？

修复自动连点功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
自动连点只在管理员模式下生效，非管理员只能更改快捷键设置与是否启用

**Comment by Ireeul** [comment]
我是以管理员模式打开的，用的管理员模式的桌面快捷方式

**Comment by Lightczx** [comment]
使用管理员开启后需要重启才会生效

**Comment by Ireeul** [comment]
依然没有生效

**Comment by Lightczx** [comment]
你设置了什么快捷键

**Comment by Ireeul** [comment]
最开始没有动设置，想要用F8没有成功，现在动了设置是Alt+F10

**Comment by Lightczx** [comment]
> 最开始没有动设置，想要用F8没有成功，现在动了设置是Alt+F10

Alt绑定目前无法生效，请尝试其他的按键

**Comment by Ireeul** [comment]
改成F10之后目前可以使用了，辛苦了
