### ISSUE TITLE
[Feat]: 角色资料页面新增角色养成素材显示

### ISSUE THREAD

**Issue by Donte1l** [DGP-Studio/Snap.Hutao#112]
### 你想要实现或优化的功能？

Snap原神有，但是Hutao没有这个功能
![image](https://user-images.githubusercontent.com/43703892/196022099-4ab99a2b-e2d8-4549-bfaf-dfe86668b920.png)
![image](https://user-images.githubusercontent.com/43703892/196022109-5a808703-e40d-467a-b643-4ff8fb4e6b70.png)

**Comment by Lightczx** [comment]
#92
