### ISSUE TITLE
建议增强筛选功能

### ISSUE THREAD

**Issue by nomeqc** [DGP-Studio/Snap.Hutao#1120]
### 背景与动机

【角色资料】【武器资料】不支持模糊搜索，用起来很不方便

### 想要实现或优化的功能

建议增强【角色资料】【武器资料】搜索，增加模糊搜索，提高用户体验。

**Comment by Lightczx** [comment]
只会支持搜索完整名称
搜索时使用空格分隔查询词

目前角色可以按 全名/所属地区/武器类型/星级/体型 筛选
武器可以按 全名/武器类型/星级/主属性 筛选

**Comment by Lightczx** [comment]
Tracked by #1394
