### ISSUE TITLE
[Bug]: 安装失败

### ISSUE THREAD

**Issue by jinyiwei2012** [DGP-Studio/Snap.Hutao#1125]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

25992.1000

### Snap Hutao 版本

1.8.0.0

### 设备 ID

AE0F0658DA74DCC7CF3884CFE15C698A

### 问题分类

安装和环境

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/116472418/7fdabcb0-efc0-452f-8d33-19117194e950)
无法安装
应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。

### 你期望发生的行为？

正常安装

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
非正式版的操作系统无法正常安装，是微软的问题
