### ISSUE TITLE
启动游戏-资源下载中的文件YuanShen_4.2.0.zip下载链接无效

### ISSUE THREAD

**Issue by abandonstudy** [DGP-Studio/Snap.Hutao#1126]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3693

### Snap Hutao 版本

1.8.0.0

### 问题分类

安装和环境

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/33c803bb-b72e-4d56-8b3d-bc567a8c3d21)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/af6ae977-15f1-40cd-ba80-17a2d25b0b61)
正确的链接似乎应为https://github.com/MAnggiarMustofa/GI-Download-Library/blob/main/GenshinImpact/Client/4.2.0.md
  中的7个分卷压缩包

### 你期望发生的行为？

正常下载

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
原神目前已经不提供完整包了
