### ISSUE TITLE
武器、怪物图片无法加载

### ISSUE THREAD

**Issue by pigwantacat** [DGP-Studio/Snap.Hutao#1128]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2715

### Snap Hutao 版本

1.8.0.0

### 设备 ID

D2F95558028B055877B26892D42B9E31

### 问题分类

安装和环境

### 发生了什么？

武器、怪物图片无法加载
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/79680042/f34e0ccf-75aa-4211-8f85-dd39a4f1507e)

### 你期望发生的行为？

武器、怪物图片无法加载
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/79680042/604ec97c-fb18-460e-ad1e-43f4b5f9e363)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
设置重置图片资源
