### ISSUE TITLE
成就导入功能

### ISSUE THREAD

**Issue by Mesopotamia913** [DGP-Studio/Snap.Hutao#1132]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2715

### Snap Hutao 版本

1.8.0.0

### 问题分类

成就管理

### 发生了什么？

导入成就文件时，无法识别json文件
![微信图片_20231128023113](https://github.com/DGP-Studio/Snap.Hutao/assets/76770327/33ec70a6-9035-4f91-8472-73cd9ab6e4f5)
![微信图片_20231128023219](https://github.com/DGP-Studio/Snap.Hutao/assets/76770327/3b354828-4ff2-415c-b68a-b76cb8e4864b)

### 你期望发生的行为？

能够正确识别json文件并导入成就

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
Duplicate of #1124
