### ISSUE TITLE
[Bug]: 运行出现 the service has not been started. 

### ISSUE THREAD

**Issue by vannon47** [DGP-Studio/Snap.Hutao#1133]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3693

### Snap Hutao 版本

1.8.0.0

### 设备 ID

114CCA201D0CECA724606AEF52545220

### 问题分类

安装和环境

### 发生了什么？

下载MXIS（我的Microsoft store 常年关闭，并且有好几个microsoft store服务我关了）
安装完成后无法启动，有两个报错：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/41172914/c3dbdd02-85e7-4839-8959-41202827d148)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/41172914/871a1354-747c-450b-ab70-5c82dace6fe6)

在event log 里找到如下报错：
1. Application Error
Faulting application name: Snap.Hutao.exe, version: 1.0.0.0, time stamp: 0x65410000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3636, time stamp: 0x326edcef
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x38c
Faulting application start time: 0x01da21993b8a0b69
Faulting application path: E:\60568DGPStudio.SnapHutao_1.8.0.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: abd8a366-2117-48db-91ef-26f112b2798c
Faulting package full name: 
Faulting package-relative application ID: 

2. .NET Runtime
Faulting application name: Snap.Hutao.exe, version: 1.0.0.0, time stamp: 0x65410000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3636, time stamp: 0x326edcef
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x38c
Faulting application start time: 0x01da21993b8a0b69
Faulting application path: E:\60568DGPStudio.SnapHutao_1.8.0.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: abd8a366-2117-48db-91ef-26f112b2798c
Faulting package full name: 
Faulting package-relative application ID: 

### 你期望发生的行为？

帮忙解决下这个安装报错问题，不知道是不是我禁用了不知哪个service 还是dependent安装不全？

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
原因：《我的Microsoft store 常年关闭》

**Comment by vannon47** [comment]
基本上每次microsoft store 安装都不正常，所以一般程序都是直接找安装包下载

**Comment by Lightczx** [comment]
不支持没有商店的Windows

**Comment by vannon47** [comment]
.....

**Comment by Masterain98** [comment]
![Screenshot_20231127-181502.png](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/72592192-9d8d-40b0-bb2a-e654cbdb80c9)
