### ISSUE TITLE
[Bug]: 1.8.1启动时闪退

### ISSUE THREAD

**Issue by qhy040404** [DGP-Studio/Snap.Hutao#1134]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23585.1001

### Snap Hutao 版本

1.8.1.0

### 设备 ID

EEE9865DDEB54348C60C0E5F34A64FE1

### 问题分类

安装和环境

### 发生了什么？

一开就crash
源
Snap.Hutao

摘要
已停止工作

日期
‎2023/‎11/‎28 下午 12:05

状态
准备上载

描述
错误的应用程序路径:	C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.8.1.0_x64__ebfp3nyc27j86\Snap.Hutao.exe

问题签名
问题事件名称:	MoBEX
程序包全名:	60568DGPStudio.SnapHutao_1.8.1.0_x64__ebfp3nyc27j86
应用程序名:	praid:App
应用程序版本:	1.0.0.0
应用程序时间戳:	65410000
故障模块名称:	coreclr.dll
故障模块版本:	8.0.23.53103
故障模块时间戳:	65411660
异常偏移:	00000000003c9aa8
异常代码:	c0000005
异常数据:	0000000000000008
OS 版本:	10.0.23585.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	66f9
其他信息 2:	66f98d9abdc24f24f8c3a8b3adf9f8a0
其他信息 3:	d5e2
其他信息 4:	d5e2542990006fe7a60059bad6eeeb6f

帮助描述问题的文件
minidump.mdmp
WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20231122_1_EC_0_inject.etl
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20231122_1_EC_0.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector.etl
memory.csv
sysinfo.txt
WERInternalRequest.xml
AppCompat.txt
memory.hdmp
WERDataCollectionStatus.txt

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFE06809AA8 (0x00007FFE06440000) with exit code 0x80131506.

**Comment by kakairin** [comment]
一样的问题，今天开机打开启动器自动更新之后，一开就闪退。设备idEB7D87AE4D153CED3853D02D830541EE

**Comment by qiuqiu-2** [comment]
一样的问题，我今天打开自动更新了以后就一直闪退，重新安装以后也是自动闪退

**Comment by Lightczx** [comment]
1.8.2 会尽快发布

**Comment by EndesrDragons** [comment]
1.8.2更新了吗？求求

**Comment by kakairin** [comment]
还没，我树脂满了😭

**Comment by LCYBFF** [comment]
白屏，闪退，卸载不了

**Comment by Lightczx** [comment]
1.8.2 版本被微软退审了，新版本会耽误几天

**Comment by xiaooloong** [comment]
使用 1.8.1 的临时解决办法是下载 Discord 安装启动后再启动胡桃工具。

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/f95c5887-bfe5-4b44-93f5-2651ad4f34fc)
1.8.3 已经提交了，最快明天下午就能通过（如果能通过）

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/f95c5887-bfe5-4b44-93f5-2651ad4f34fc)
1.8.3 已经提交了，最快明天下午就能通过（如果能通过）
