### ISSUE TITLE
[Bug]: 更新最新版本后，Snap Hutao出现了闪退问题

### ISSUE THREAD

**Issue by AnrayAnn** [DGP-Studio/Snap.Hutao#1137]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2715

### Snap Hutao 版本

1.8.1.0

### 设备 ID

E026852440258F3B9284634FFE7D7F54

### 问题分类

安装和环境

### 发生了什么？

更新前可以正常使用此应用
在更新最新版本，程序在下载完成所有数据后，再次启动出现崩溃
已重装、重启，以管理员身份启动，均无法解决问题
以下为.net错误详情

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1023</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-11-28T05:54:40.8381149Z" /> 
  <EventRecordID>23234</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="21852" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Anray</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: Snap.Hutao.exe CoreCLR Version: 8.0.23.53103 .NET Version: 8.0.0 Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFE4E4C9AA8 (0x00007FFE4E100000) with exit code 0x80131506.</Data> 
  </EventData>
  </Event>

以下为应用崩溃详情

[-](https://github.com/DGP-Studio/Snap.Hutao/issues/new?assignees=&labels=BUG%2Cpriority%3Anone&projects=&template=CHS-bug-report.yml&title=%5BBug%5D%3A+%E5%9C%A8%E8%BF%99%E9%87%8C%E5%A1%AB%E5%86%99%E4%B8%80%E4%B8%AA%E5%90%88%E9%80%82%E7%9A%84%E6%A0%87%E9%A2%98#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/new?assignees=&labels=BUG%2Cpriority%3Anone&projects=&template=CHS-bug-report.yml&title=%5BBug%5D%3A+%E5%9C%A8%E8%BF%99%E9%87%8C%E5%A1%AB%E5%86%99%E4%B8%80%E4%B8%AA%E5%90%88%E9%80%82%E7%9A%84%E6%A0%87%E9%A2%98#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-11-28T05:54:41.0611370Z" /> 
  <EventRecordID>23235</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="15784" ThreadID="22648" /> 
  <Channel>Application</Channel> 
  <Computer>Anray</Computer> 
  <Security UserID="S-1-5-21-3570127131-3555890303-4022026392-1001" /> 
  </System>
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/new?assignees=&labels=BUG%2Cpriority%3Anone&projects=&template=CHS-bug-report.yml&title=%5BBug%5D%3A+%E5%9C%A8%E8%BF%99%E9%87%8C%E5%A1%AB%E5%86%99%E4%B8%80%E4%B8%AA%E5%90%88%E9%80%82%E7%9A%84%E6%A0%87%E9%A2%98#) <EventData>
  <Data Name="AppName">Snap.Hutao.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">65410000</Data> 
  <Data Name="ModuleName">coreclr.dll</Data> 
  <Data Name="ModuleVersion">8.0.23.53103</Data> 
  <Data Name="ModuleTimeStamp">65411660</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">00000000003c9aa8</Data> 
  <Data Name="ProcessId">0x555c</Data> 
  <Data Name="ProcessCreationTime">0x1da21bf5f7c0dc7</Data> 
  <Data Name="AppPath">C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.8.1.0_x64__ebfp3nyc27j86\Snap.Hutao.exe</Data> 
  <Data Name="ModulePath">C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\coreclr.dll</Data> 
  <Data Name="IntegratorReportId">d624d3c1-92d1-491a-9768-a54ad37b4630</Data> 
  <Data Name="PackageFullName">60568DGPStudio.SnapHutao_1.8.1.0_x64__ebfp3nyc27j86</Data> 
  <Data Name="PackageRelativeAppId">APP</Data> 
  </EventData>
  </Event>

### 你期望发生的行为？

正常启动

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1134

**Comment by AnrayAnn** [comment]
日志名称:          Application
来源:            .NET Runtime
日期:            2023/11/28 13:54:40
事件 ID:         1023
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           Anray
描述:
Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFE4E4C9AA8 (0x00007FFE4E100000) with exit code 0x80131506.

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-11-28T05:54:40.8381149Z" />
    <EventRecordID>23234</EventRecordID>
    <Correlation />
    <Execution ProcessID="21852" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Anray</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFE4E4C9AA8 (0x00007FFE4E100000) with exit code 0x80131506.
</Data>
  </EventData>
</Event>

**Comment by AnrayAnn** [comment]
`日志名称:          Application
来源:            .NET Runtime
日期:            2023/11/28 13:54:40
事件 ID:         1023
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           Anray
描述:
Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFE4E4C9AA8 (0x00007FFE4E100000) with exit code 0x80131506.

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-11-28T05:54:40.8381149Z" />
    <EventRecordID>23234</EventRecordID>
    <Correlation />
    <Execution ProcessID="21852" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Anray</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFE4E4C9AA8 (0x00007FFE4E100000) with exit code 0x80131506.
</Data>
  </EventData>
</Event>`

**Comment by AnrayAnn** [comment]
[.net错误.txt](https://github.com/DGP-Studio/Snap.Hutao/files/13484140/default.net.txt)
