### ISSUE TITLE
[Bug]: 更新windowsdesktop-runtime-8.0.0-win-x64后无法打开snap胡桃

### ISSUE THREAD

**Issue by zzh010619** [DGP-Studio/Snap.Hutao#1141]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22000.2538

### Snap Hutao 版本

最新版

### 设备 ID

UserName

### 问题分类

安装和环境

### 发生了什么？

今天打开snap胡桃时要求先更新windowsdesktop-runtime-8.0.0-win-x64，但在下载安装后再次打开snap胡桃时只会鼠标转圈并且闪退。关机重启或者卸载重新安装snap胡桃仍然无法打开，一直闪退。在没有安装windowsdesktop-runtime-8.0.0-win-x64前并没有这个问题，但是无法打开软件
<img width="1115" alt="1701173412071" src="https://github.com/DGP-Studio/Snap.Hutao/assets/152281128/3f9c3803-e12f-4f73-85c9-ddbc575575fd">

### 你期望发生的行为？

打开软件

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1134
