### ISSUE TITLE
[Bug]: 1.8.3点击启动游戏没有反应

### ISSUE THREAD

**Issue by justforfhx** [DGP-Studio/Snap.Hutao#1150]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2715

### Snap Hutao 版本

1.8.3

### 设备 ID

D3FD7327BB429D35D99AEF301215CE5B

### 问题分类

游戏启动器

### 发生了什么？

1.8.0升级到1.8.3后，点击启动游戏，闪过“正在转换客户端”弹窗后，没有反应，无法启动游戏

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
管理员模式下么 @justforfhx

**Comment by justforfhx** [comment]
是的，管理员模式下启动，而且非管理员模式也无法启动游戏

**Comment by Lightczx** [comment]
游戏路径在哪

**Comment by justforfhx** [comment]
就是按照要求的，F:\Genshin\Genshin Impact\Genshin Impact Game\YuanShen.exe，我在1.8.0版本可以正常启动游戏

**Comment by Lightczx** [comment]
看下启动游戏时任务管理器里面有没有原神

**Comment by justforfhx** [comment]
神奇，我刚才重启电脑之后，也没有成功启动，但是按照你说的在任务管理器最最最下面发现了一个原神的任务进程，结束进程后正常了
