### ISSUE TITLE
[Bug]: 快捷方式无法正常工作

### ISSUE THREAD

**Issue by Fullang** [DGP-Studio/Snap.Hutao#1151]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2715

### Snap Hutao 版本

1.8.3.0

### 问题分类

安装和环境

### 发生了什么？

快捷方式无法正常打开，我也不知道snap hutao的安装位置![image](https://github.com/DGP-Studio/Snap.Hutao/assets/138115607/0880ca7d-90f5-4382-a5ed-dfc637f3e1be)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
可以暂时用开始菜单

**Comment by Fullang** [comment]
更新1.8.4.0后问题仍然存在
