### ISSUE TITLE
[Bug]: 我的电脑所有版本都闪退

### ISSUE THREAD

**Issue by MrWang886** [DGP-Studio/Snap.Hutao#1158]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2468

### Snap Hutao 版本

1.8.4.0

### 设备 ID

F342C92B936655089147E695D316E307

### 问题分类

安装和环境

### 发生了什么？

无 .NET错误日志

### 你期望发生的行为？

打开软件时，就一瞬间能看见app的窗口然后就没了反应了

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@MrWang886 提供崩溃日志
