### ISSUE TITLE
[Bug]:HttpRequestException

### ISSUE THREAD

**Issue by Kalsist** [DGP-Studio/Snap.Hutao#116]
### Windows 版本

19043.2130

### Snap Hutao 版本

1.1.11.0

### 发生了什么？

解除了APP Container Loopback 限制但还是出现这个，也没开代理，clash的tun模式一开就没网

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Kalsist** [comment]
![image](https://user-images.githubusercontent.com/115934051/196115702-e4b1904f-d6c4-46bf-b3cb-e39f7a2332be.png)

**Comment by Lightczx** [comment]
Track

- [ ] #123
