### ISSUE TITLE
[Feat]: Hide Email on Homepage application

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao#1160]
### Background & Motivation

I think this should be added to the app because I'm a person who sometimes uses Hutao and uses it while recording videos, and it doesn't make sense to display email on the app's homepage.

### Detail of the Feature

You can add a button in the settings section to hide the Email section at the home page, or hide this information from the beginning.

**Comment by Lightczx** [comment]
## Alternative Design
Introducing a `NickName` field in our server, retrieve from `Passport/UserInfo`
