### ISSUE TITLE
[Bug]: 不能正常启动游戏

### ISSUE THREAD

**Issue by wanxidehuanxiangxiang** [DGP-Studio/Snap.Hutao#1165]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.8.4.0

### 设备 ID

165C1E3277E3C32886426F2B84C6E950

### 问题分类

游戏启动器

### 发生了什么？

在胡桃1.8.0.0时可以正常使用，在提示需要升级后更新了胡桃1.8.4.0版本，我重新启动胡桃客户端，点击启动游戏，但是没有任何反应，通过卸载胡桃客户端，重装之后，点击启动还是不可以正常启动后，查阅文档没有相关描述后来反馈。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
closing for no response
