### ISSUE TITLE
[Bug]: 无法在启动游戏页面启动游戏

### ISSUE THREAD

**Issue by DSakura207** [DGP-Studio/Snap.Hutao#1167]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2715

### Snap Hutao 版本

1.8.4.0

### 设备 ID

2DA44F8264495636ACC5D4C0BC30C148

### 问题分类

游戏启动器

### 发生了什么？

以非管理员模式运行时，在启动游戏标签无法启动游戏，提示切换服务器失败。

### 你期望发生的行为？

游戏应正常启动。
非管理员模式运行时，在此页面启动游戏在1.8.4.0之前并无异常。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
管理员启动，选一下服务器
