### ISSUE TITLE
[Feat]: 是否可以添加个后台运行的选项而不是直接关闭？

### ISSUE THREAD

**Issue by nfieoek** [DGP-Studio/Snap.Hutao#1168]
### 背景与动机

 目前我没有找到可以设置后台运行的功能，每次启动就忍不住点了右上角叉掉然后直接关闭 导致帧率解锁功能又无了，文档里也没找到这个后台运行的设置描述，不知道有没有

### 想要实现或优化的功能

设置里面加个是否关闭设置 又直接关闭，询问，后台运行三个选项， 首次关闭的时候询问是否关闭还是后台运行

**Comment by Masterain98** [comment]
Duplicate of #492

Search existed issues before posting a new one.
