### ISSUE TITLE
[Feat]: 刚需一个用户数据目录修改功能

### ISSUE THREAD

**Issue by cworld1** [DGP-Studio/Snap.Hutao#117]
### 你想要实现或优化的功能？

对于习惯使用用户文档目录作为Onedrive同步目录，或是系统盘常常爆满且文档目录不方便迁移的用户而言，在里面塞太多数据文件显然是难以接受且不满足可持续发展思路的。希望能增加修改应用数据目录的选项。

**Comment by Natural12349978** [comment]
其实可以对windows个人用户的文档文件夹进行修改，让其不在系统盘之内

**Comment by cworld1** [comment]
> 其实可以对windows个人用户的文档文件夹进行修改，让其不在系统盘之内

不是系统盘的问题，是 Onedrive 同步的问题，在正常的设置下，Onedrive 会自动同步文档文件夹下的所有内容，这是合理的，而这里面塞应用数据，在正常使用系统习惯上，这是不合理的。

**Comment by bryarrow** [comment]
对的，现在的设置使得Onedrive一直在同步数据更改，不合适

**Comment by AdminRoc** [comment]
请查看文档，有相关说明

**Comment by bryarrow** [comment]
抱歉，可否指出具体是哪段文档？我没有找到

**Comment by bryarrow** [comment]
> 请查看文档，有相关说明

如果您是指变更安装位置，那么我们提的是变更数据文件夹的位置，而非安装位置

**Comment by EricZhang233** [comment]
Developer可以考虑将现有的“%Userprofile%\Documents\HuTao”存储路径移至并迁移到“%Appdata%\HuTao”路径，毕竟按照微软开发规范来说应用数据就应该存在“%Appdata%”目录的
suggest :)

**Comment by EricZhang233** [comment]
> Developer可以考虑将现有的“%Userprofile%\Documents\HuTao”存储路径移至并迁移到“%Appdata%\HuTao”路径，毕竟按照微软开发规范来说应用数据就应该存在“%Appdata%”目录的 suggest :)

【Advanced Feature】亦可以考虑支持修改路径，因为存在部分用户重装系统但想保留祈愿记录的需求，这样可以按照用户意愿修改到系统盘以外的文件夹。例如我现在就出于上述需求，将Hutao的数据文件保存到D盘下某个目录内，但硬链接到程序需要的“%Userprofile%\Documents\HuTao”路径。硬链接指令如下`mklink /d %Userprofile%\Documents\HuTao D:\Program\Gamefiles\Genshin\Tools\HuTao`

**Comment by cworld1** [comment]
感谢🥰
