### ISSUE TITLE
添加一些额外的启动参数或者自定义启动参数

### ISSUE THREAD

**Issue by NONAME-2121237** [DGP-Studio/Snap.Hutao#1173]
### 背景与动机

最近发现了能用普通pc原神启动云串流状态的参数，我的win恰巧有触屏就能直接用触屏玩原神了
.\YuanShen.exe use_mobile_platform -is_clould 1 -platform_type CLOUD_THIRD_PARTY_MOBLE
但是HuTao目前不能自定义启动参数我只好手搓bat了

### 想要实现或优化的功能

添加下云原神触屏启动参数或者开放自定义启动参数

**Comment by Lightczx** [comment]
实际上只需要 `-platform_type CLOUD_THIRD_PARTY_MOBLE`
