### ISSUE TITLE
[Feat]: 自动签到

### ISSUE THREAD

**Issue by fhzzzs** [DGP-Studio/Snap.Hutao#1180]
### 背景与动机

如果能够在snap hutao内添加 启动游戏时自动签到的功能的话 就不需要每天点击签到了

### 想要实现或优化的功能

在设置内添加启动游戏自动签到

**Comment by qhy040404** [comment]
Internal item
https://github.com/orgs/DGP-Studio/projects/2/views/1?pane=issue&itemId=21526452

**Comment by Lightczx** [comment]
Tracked by #1394
