### ISSUE TITLE
[Bug]: 打开软件就报错5003，且实时便签也无法使用

### ISSUE THREAD

**Issue by FM-123** [DGP-Studio/Snap.Hutao#1181]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

21H2

### Snap Hutao 版本

1.8.4.0

### 设备 ID

0CEED9FE302BDDAE911B2C3395B425FA

### 问题分类

实时便笺

### 发生了什么？

打开软件就报错5003，且实时便签功能
![Uploading QQ图片20231216131254.png…]()
也无法使用（已重新登录账号，仍然报错无法成功显示，有时报错1034
![Snipaste_2023-12-16_13-14-13](https://github.com/DGP-Studio/Snap.Hutao/assets/83116487/b2c309f0-2d3b-4169-95f9-47b63bd2366b)
）

### 你期望发生的行为？

咨询如何解决
![QQ图片20231216131254](https://github.com/DGP-Studio/Snap.Hutao/assets/83116487/2247a8f8-17e1-473a-9521-5a2df508c401)
![QQ图片20231216131311](https://github.com/DGP-Studio/Snap.Hutao/assets/83116487/52fe8e07-8ea6-4cb3-b59d-470a62089acc)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by FM-123** [comment]
系统是win11，22000.2538
![Uploading Snipaste_2023-12-16_13-19-10.png…]()

**Comment by FM-123** [comment]
![Uploading Snipaste_2023-12-16_13-19-10.png…]()

**Comment by qhy040404** [comment]
#1060

**Comment by qhy040404** [comment]
Duplicate of #1060
