### ISSUE TITLE
可以j加个自定义启动参数吗？

### ISSUE THREAD

**Issue by NumberFive555** [DGP-Studio/Snap.Hutao#1186]
### 背景与动机

手机串流电脑游玩，这个参数能让pc版启动移动端ui

### 想要实现或优化的功能

自定义启动参数
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50335564/e978b8fb-7190-4458-9039-e3424223f2f4)

**Comment by qhy040404** [comment]
Duplicate of #1173
