### ISSUE TITLE
Want to contribute to add lang ID or indonesian Bahasa

### ISSUE THREAD

**Issue by NatsumeAoii** [DGP-Studio/Snap.Hutao#1188]
### 背景与动机

to make sure the reader maybe from indonesia can easily read within their own native language

### 想要实现或优化的功能

add lang ID or Indonesian Bahasa

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/bd48aa09-32f3-480f-a8c9-302cd3176524)
Hi @NatsumeAoii .I've add the language entry in https://translate.hut.ao
You can now go and translate it if you may.

**Comment by Lightczx** [comment]
Once some amount of the string is translated, I'll make the language visible in App

**Comment by NatsumeAoii** [comment]
Thank you for ur response, Working on it rn!

**Comment by NatsumeAoii** [comment]
Hello! I'd like to inform you that I have already finished the translation. If possible, could you please review it? Thanks in advance.

**Comment by Lightczx** [comment]
Translations will be merged when we are about to publish for every formal release
And translations correctness will not be checked unless an issue is created on crowdin.

**Comment by NatsumeAoii** [comment]
Understood. Please keep me informed if there are any translation projects that we could collaborate on.

**Comment by Lightczx** [comment]
@NatsumeAoii https://github.com/DGP-Studio/Snap.Hutao.Docs

**Comment by NatsumeAoii** [comment]
Already working on it rn, i will PR it as soon as possible

**Comment by Masterain98** [comment]
> Already working on it rn, i will PR it as soon as possible

Please check the latest PR https://github.com/DGP-Studio/Snap.Hutao.Docs/pull/84, there are some big changes in home page, navbar and quick-start documents. Make sure you branch is not outdated.

**Comment by NatsumeAoii** [comment]
I am currently utilizing Git on Visual Studio Code to ensure that all aspects are consistently updated.
