### ISSUE TITLE
[Bug]: 公告活动页面异常且刷新祈愿无效

### ISSUE THREAD

**Issue by XHMSY** [DGP-Studio/Snap.Hutao#119]
### Windows 版本

19044.1706

### Snap Hutao 版本

1.1.11.0

### 发生了什么？

![1665998581084](https://user-images.githubusercontent.com/115984309/196140898-ca78541a-ccb6-448f-bc6f-3673d1df3966.jpg)
公告页面都变成这样
曾经因为刷新祈愿记录崩溃过
从缓存刷新点了提示这个
![1665999110181](https://user-images.githubusercontent.com/115984309/196143051-2a1800bb-70c3-49a5-b3bc-b55108784031.png)
stoken刷新点了没反应
游戏祈愿历史页面打开了 缓存刷新打开时也设置了正常游戏本体路径

### 你期望发生的行为？

活动公告变正常
正常使用刷新功能

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by XHMSY** [comment]
崩溃日志我不知道怎么上传

**Comment by Lightczx** [comment]
公告页面有什么奇怪的地方么

**Comment by ICMYS** [comment]
> 崩溃日志我不知道怎么上传

公告应该就是这样的，至于祈愿，目前是不会将url明文写入data_2缓存了，需要把代理模式加回来

**Comment by Lightczx** [comment]
> > 崩溃日志我不知道怎么上传
> 
> 公告应该就是这样的，至于祈愿，目前是不会将url明文写入data_2缓存了，需要把代理模式加回来

使用stoken

**Comment by AlbertWen-AW** [comment]
> > > 崩溃日志我不知道怎么上传
> > 
> > 
> > 公告应该就是这样的，至于祈愿，目前是不会将url明文写入data_2缓存了，需要把代理模式加回来
> 
> 使用stoken

点Stoken刷新没有反应

**Comment by XHMSY** [comment]
> > > > 崩溃日志我不知道怎么上传
> > > 
> > > 
> > > 公告应该就是这样的，至于祈愿，目前是不会将url明文写入data_2缓存了，需要把代理模式加回来
> > 
> > 
> > 使用stoken
> 
> 点Stoken刷新没有反应

我也是 有点懵
