### ISSUE TITLE
[Bug]: 解锁FPS在4.3失效

### ISSUE THREAD

**Issue by luluxiaoyu** [DGP-Studio/Snap.Hutao#1190]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.2915

### Snap Hutao 版本

1.8.4

### 设备 ID

A177DC0C71F6F70F35FB289C47220C3C

### 问题分类

游戏启动器

### 发生了什么？

解锁FPS在4.3失效
https://github.com/34736384/genshin-fps-unlock 此项目已更新，希望适配

### 你期望发生的行为？

解锁fps

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by XiaohangShi2000** [comment]
我也遇到了同样的问题

**Comment by Lightczx** [comment]
@luluxiaoyu @XiaohangShi2000 
https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7270311466

**Comment by luluxiaoyu** [comment]
使用该alpha版本时出现问题
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/58876608/adc9b9f8-93ca-42ca-92c5-07491906cf13)

**Comment by panghu259900** [comment]
使用alpha测试版本时遇到的无法启动的问题
![Uploading 微信图片_20231220123953.png…]()

**Comment by panghu259900** [comment]
使用alpha测试版本时遇到的无法启动的问题
![微信图片_20231220123953](https://github.com/DGP-Studio/Snap.Hutao/assets/154399068/8f1bfb04-f8f2-4cae-9702-72b84753b3e2)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7271087900 @panghu259900 看看这个

**Comment by Masterain98** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7271087900  看看这个

works for me

**Comment by luluxiaoyu** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7271087900 @panghu259900 看看这个

可以了

**Comment by Paperside** [comment]
我也遇到了一样的问题

**Comment by Wieso97** [comment]
> 使用该alpha版本时出现问题 ![image](https://private-user-images.githubusercontent.com/58876608/291775496-adc9b9f8-93ca-42ca-92c5-07491906cf13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjY0NDYsIm5iZiI6MTcwMzA2NjE0NiwicGF0aCI6Ii81ODg3NjYwOC8yOTE3NzU0OTYtYWRjOWI5ZjgtOTNjYS00MmNhLTkyYzUtMDc0OTE5MDZjZjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5NTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MTliZDVhZGVlZWUyODM2NjU0M2FhMDc4Mzg2YWVmNTkwOWMyOTBiNDAxY2QzYTIzNjk1YTM5YWNmZDdjMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8FZAB7s5SxKUTSEchBNWhyXBQm_UwZUO4dTFwnDdTxA)

一样的问题。求热补丁修复

**Comment by aaahai00** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7271087900 @panghu259900 看看这个

能用

**Comment by BaiLuQiShuang** [comment]
所以是怎么解决的？等待下一个版本发布吗？还是按照fix#1190改文件？感觉那个有点看不懂哈哈

**Comment by aaahai00** [comment]
> 所以是怎么解决的？等待下一个版本发布吗？还是按照fix#1190改文件？感觉那个有点看不懂哈哈

可以等待下一个版本发布，或者直接安装测试版，链接里那个压缩包解压出来就是安装包，安装前要先把证书装了不然装不上

**Comment by BaiLuQiShuang** [comment]
> > 所以是怎么解决的？等待下一个版本发布吗？还是按照fix#1190改文件？感觉那个有点看不懂哈哈
> 
> 可以等待下一个版本发布，或者直接安装测试版，链接里那个压缩包解压出来就是安装包，安装前要先把证书装了不然装不上

好的，谢谢 :)
