### ISSUE TITLE
[Bug]: 4.3版本更新后解锁帧率功能失效

### ISSUE THREAD

**Issue by darkwy123** [DGP-Studio/Snap.Hutao#1193]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.1848

### Snap Hutao 版本

1.8.5.0

### 设备 ID

73670DC813284DA79ACBDDA928D4C516

### 问题分类

游戏启动器

### 发生了什么？

4.3版本更新后，解锁帧率功能失效

### 你期望发生的行为？

麻烦赶紧修修，60帧真的卡

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1190

**Comment by Masterain98** [comment]
Duplicate of #1190

**Comment by luluxiaoyu** [comment]
> ### 检查清单
> * [x]  我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
> * [x]  我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
> * [x]  我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题
> 
> ### Windows 版本
> 22621.1848
> 
> ### Snap Hutao 版本
> 1.8.5.0
> 
> ### 设备 ID
> 73670DC813284DA79ACBDDA928D4C516
> 
> ### 问题分类
> 游戏启动器
> 
> ### 发生了什么？
> 4.3版本更新后，解锁帧率功能失效
> 
> ### 你期望发生的行为？
> 麻烦赶紧修修，60帧真的卡
> 
> ### 最后一步
> * [x]  我认为上述的描述已经足以详细，以允许开发人员能复现该问题

可以先用着 https://github.com/34736384/genshin-fps-unlock
