### ISSUE TITLE
[Bug]: 游戏帧率解锁失败

### ISSUE THREAD

**Issue by williambacteria** [DGP-Studio/Snap.Hutao#1194]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows11 23H2{22631.2715}

### Snap Hutao 版本

1.8.4.0

### 设备 ID

23FC649120862BA9B48A4013476287B4

### 问题分类

游戏启动器

### 发生了什么？

2023年12年20日原神更新版本后，胡桃工具箱高级功能解锁帧率功能失效，在工具箱启动游戏后一直提示“正在尝试解锁帧率上限”，进入游戏后帧率未解锁。

### 你期望发生的行为？

版本更新后

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
Duplicate of #1190
