### ISSUE TITLE
[Bug]: 4.3祈愿卡池没有显示

### ISSUE THREAD

**Issue by fuyuan233** [DGP-Studio/Snap.Hutao#1195]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3803

### Snap Hutao 版本

1.8.4.0

### 设备 ID

C41188A19F89D26715BD11508E7E8F51

### 问题分类

祈愿记录

### 发生了什么？

4.3更新后祈愿卡池没有显示出来，该版本卡池内抽卡数据不可以看到

### 你期望发生的行为？

在祈愿记录中显示4.3版本对应的卡池

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
已热修
