### ISSUE TITLE
[Bug]: 关闭游戏后无法再次启动

### ISSUE THREAD

**Issue by SuperOrange2000** [DGP-Studio/Snap.Hutao#1196]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.1992

### Snap Hutao 版本

1.8.4.0

### 设备 ID

834F9B05B1145A6E22F688B509214F13

### 问题分类

游戏启动器

### 发生了什么？

每次打开工具箱的第一次启动游戏正常，关闭游戏后再次点击启动无法正常工作。其中点击主页的启动游戏无任何反应，点击启动游戏页面的启动游戏短暂出现“正在转换客户端”。此问题在更新工具箱版本后出现，但无法确定之前使用的工具箱版本。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
检查任务管理器中是否存在游戏进程

**Comment by SuperOrange2000** [comment]
我并没有在任务管理器中看到相关进程。
