### ISSUE TITLE
[Bug]: 胡桃云获取验证码总是提示“验证码请求过快”

### ISSUE THREAD

**Issue by ckfrank** [DGP-Studio/Snap.Hutao#1197]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2861

### Snap Hutao 版本

1.8.4.0

### 设备 ID

25B07241880EF22D4DEFB69EBEE5564F

### 问题分类

胡桃云

### 发生了什么？

注册或者修改胡桃云密码时，获取验证码步骤总是提示“验证码请求过快，请过1分钟后再试”，距离上次点击获取已经远超一分钟，并且邮箱（@live.cn或@qq.com）都没有收到过任何验证码
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/19375542/a0670e70-499a-4a83-a4d4-891daaeb7150)

### 你期望发生的行为？

多设备使用者，希望能够正确注册和获取验证码以便进行多设备信息同步

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
检查你的垃圾邮件

**Comment by ckfrank** [comment]
已检查，验证码并没有发到垃圾邮件
________________________________

**Comment by Masterain98** [comment]
在第一次请求验证码的时候就出现了操作频繁的提示吗？

**Comment by cokebar** [comment]
我也是一样的问题 第一次就提示操作频繁 后面无论如何尝试都是一样

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/e9276b93-c90b-4c37-9417-3c61271dc9dd)

在Alpha版中复现了一种无输出错误的情况

**Comment by Lightczx** [comment]
阿里云限制

**Comment by Lightczx** [comment]
已由服务端热更新修复

**Comment by cokebar** [comment]
我这里还是一样 未解决

**Comment by qhy040404** [comment]
那只能是你的邮箱问题了 检查你的垃圾箱 我这测试没问题

**Comment by Masterain98** [comment]
@DGP-Studio/hutao-dev 客户端上建议处理下非预期的错误，提示用户联系开发者
