### ISSUE TITLE
无法登陆米游社账号

### ISSUE THREAD

**Issue by AjimuRin** [DGP-Studio/Snap.Hutao#120]
### Windows 版本

22623.746

### Snap Hutao 版本

1.1.11.0

### 发生了什么？

使用米游社进行登陆时会显示“请先添加对应用户的米游社cookie”而无法登陆
使用手动添加cookie时会显示“此cookie不完整，添加失败”
![QQ截图20221017194307](https://user-images.githubusercontent.com/115994344/196168994-cef8f7ee-244d-465f-87b7-4d993583fe85.png)
![QQ图片20221017194612](https://user-images.githubusercontent.com/115994344/196169123-94a82185-0884-4c7e-b23f-68092267fa2b.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by ICMYS** [comment]
手动输入cookie的部分，需要包含ltuid、ltoken、account_id和cookie_token，缺少的话会提示不完整
目前程序内登录米哈游通行证是为了获取stoken，主要是用于各种api，例如兑换道具、生成authKey来读取祈愿记录（目前有问题）
（其实是可以通过米游社登录来获取的，不知道为什么作者没写）

**Comment by AjimuRin** [comment]
按照帮助文档提示的方法无法获得account_id与cookie_token

**Comment by Chris-zixuan** [comment]
遇到了同样的问题，能够查看 属性统计。 无法查看祈愿记录
