### ISSUE TITLE
添加云原神的启动项

### ISSUE THREAD

**Issue by zhoucAndrew** [DGP-Studio/Snap.Hutao#1202]
### 背景与动机

添加云原神启动项可以不用手动打开云原神，也能增加流畅度

### 想要实现或优化的功能

添加云原神的启动项

**Comment by qhy040404** [comment]
Duplicate of #1146

**Comment by Lightczx** [comment]
实际上是 #524 但是目前来看没有这方面的打算

**Comment by qhy040404** [comment]
Duplicate of #524
