### ISSUE TITLE
[Bug]: JSBridge 回退异常

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1208]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23606.10000

### Snap Hutao 版本

1.9.0.0

### 设备 ID

FA47BE878C143D2FE18785B660EF114A

### 问题分类

签到

### 发生了什么？

对 JSBridge 的回退持续操作，最终会引向 `about:blank` 页面，且在未重启、未切换账号的情况下无法恢复

### 你期望发生的行为？

考虑对回退添加校验，当路由与窗口打开时相同时隐藏 webview

（或者/并）优化子 Webview 调用逻辑，在窗口调用显示时与启动后初次调用处理相同

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
> 考虑对回退添加校验，当路由与窗口打开时相同时隐藏 webview
> 
> （或者/并）优化子 Webview 调用逻辑，在窗口调用显示时与启动后初次调用处理相同

无法理解
