### ISSUE TITLE
[Bug]: 资料页面渲染异常

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1209]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23606.10000

### Snap Hutao 版本

1.9.0.0

### 设备 ID

FA47BE878C143D2FE18785B660EF114A

### 问题分类

胡桃数据库

### 发生了什么？

> 未在类似页面进行操作，不确保是否存在相同问题

重复点击展开角色资料，会导致角色资料无渲染，（在滚动后恢复正常）

### 你期望发生的行为？

点击展开后正常显示内容

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
WinUI issue
