### ISSUE TITLE
[Bug]: 首页公告图片加载异常

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1210]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23606.10000

### Snap Hutao 版本

1.9.0.0

### 设备 ID

FA47BE878C143D2FE18785B660EF114A

### 问题分类

公告

### 发生了什么？

> 不确定是否能够复现加载失败

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/cba29c1f-f8c8-4a68-b853-345223663310)

可能是缓存机制的存在，在公告封面图未成功完全加载的情况下，除重启应用外，暂未找到其他使改界面重新加载的方法

### 你期望发生的行为？

考虑如下两种方案：

1. 检测图片是否加载完全，未完全尝试重新加载
2. 每次回到首页时重新加载公告组件

> 最后一步必选太草了

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你需要手动删除缓存
