### ISSUE TITLE
[Bug]: 在点击工具栏启动游戏、主页启动游戏框内齿轮后程序直接闪退消失，直接点击主页启动游戏可以打开游戏

### ISSUE THREAD

**Issue by zimo233lol** [DGP-Studio/Snap.Hutao#1212]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2506

### Snap Hutao 版本

1.9.0.0

### 设备 ID

47188F604D01B75F7664BC3A2A6D9E55

### 问题分类

游戏启动器

### 发生了什么？

错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x65410000
错误模块名称: Microsoft.ui.xaml.dll，版本: 3.1.4.0，时间戳: 0x49d9bb27
异常代码: 0xc000027b
错误偏移量: 0x00000000003b78a4
错误进程 ID: 0x0x5364
错误应用程序启动时间: 0x0x1DA35700C8D4ABF
错误应用程序路径: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.9.0.0_x64__wbnnev551gwxy\Snap.Hutao.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1049.117.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
报告 ID: c754675b-8f02-4ee3-bd9a-3c34e390d0b9
错误程序包全名: 60568DGPStudio.SnapHutao_1.9.0.0_x64__wbnnev551gwxy
错误程序包相对应用程序 ID: App

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
可以远程吗

**Comment by zimo233lol** [comment]
怎么操作

**Comment by qhy040404** [comment]
加大群找管理

**Comment by Masterain98** [comment]
> 加大群找管理

[910780153](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=DmW_LDX35YEr1CQZwjZ6x4JYP03soai2&authKey=z3PzXsuYlaPTm%2FW7TyE0o9KNz7H6LA%2BTEZ4mK2BE9%2Fcz0HhH3s1qgbydciAmrGeg&noverify=0&group_code=910780153)
