### ISSUE TITLE
实时便笺无法刷新

### ISSUE THREAD

**Issue by zhoucAndrew** [DGP-Studio/Snap.Hutao#1213]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

2023.12.23.5

### 设备 ID

0D91D8ACDC56E02861E1E2CF679F81BF

### 问题分类

实时便笺

### 发生了什么？

刷新实时便笺时出现-10001 invalid request，验证当前用户角色显示V2.10以下版本将无法使用战绩，需要更新米游社。

### 你期望发生的行为？

正常刷新实时便笺

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
测试版问题不会修复

**Comment by zhoucAndrew** [comment]
已更新到正式版，仍然会出现此问题。
版本：1.9.0.0
