### ISSUE TITLE
[Feat]: 增加强开dx12 Vulkan功能

### ISSUE THREAD

**Issue by yangFenTuoZi** [DGP-Studio/Snap.Hutao#1219]
### 背景与动机

部分用户可能会用到

### 想要实现或优化的功能

在启动参数后面增加`-force-d3d12`可以强制开启dx12
增加`-force-vulkan`可以强开Vulkan（本人试过，不会闪退，官方应该是早就做好了支持）
希望可以增加到启动参数中

**Comment by yangFenTuoZi** [comment]
也可以增加自定义启动参数

**Comment by Masterain98** [comment]
Duplicate of #884

**Comment by Lightczx** [comment]
> 本人试过，不会闪退，官方应该是早就做好了支持

不会闪退，但是也不会有任何性能提升

**Comment by 940842546** [comment]
并没有用 你用小飞机看 实际还是用的dx11

**Comment by 940842546** [comment]
不如研究怎么用dxvk转译运行
