### ISSUE TITLE
[Bug] 更新1.9以后祈愿记录异常

### ISSUE THREAD

**Issue by dsfdghg** [DGP-Studio/Snap.Hutao#1220]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3803

### Snap Hutao 版本

1.9

### 设备 ID

6FFFE036C6CD586258EB215DA49A0377

### 问题分类

祈愿记录

### 发生了什么？

更新1.9以后祈愿记录少了，祈愿中间少了一些祈愿记录

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
上传你的祈愿记录 Json

**Comment by dsfdghg** [comment]
[Uploading 500914011.json…]()

**Comment by Masterain98** [comment]
你等上传完了再发送

**Comment by dsfdghg** [comment]
[Uploading 500914011.json…]()

**Comment by dsfdghg** [comment]
[Uploading 500914011.json…]()

**Comment by dsfdghg** [comment]
[Uploading 500914011.json…]()

**Comment by dsfdghg** [comment]
[Uploading 500914011.json…]()

**Comment by dsfdghg** [comment]
[500914011.json](https://github.com/DGP-Studio/Snap.Hutao/files/13763451/500914011.json)

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/40244575-50bc-40ca-b6bb-76ab3d903802)

少了什么？

**Comment by dsfdghg** [comment]
目前已知的少了2023.6月的记录3.7的八重神子

**Comment by Lightczx** [comment]
1.9的祈愿记录是升级后自动出现的还是你从老版本导出再导入的 @dsfdghg

**Comment by dsfdghg** [comment]
升级之后他自动出现的记录只到心海，后面的是重新刷新出来的

**Comment by Lightczx** [comment]
你应该中途换过数据路径
