### ISSUE TITLE
[Bug]: 1.9 版本安装错误 0x80073CF0/0x80070570

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1221]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows 10 22H2

### Snap Hutao 版本

1.9.1

### 问题分类

安装和环境

## 情况1

msix 安装包所在目前权限错误

```
 Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80070005, 拒绝访问。
 错误 0x80070005: 从位置 Snap.Hutao.1.9.1.msix 中打开程序包失败。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] 18de53f0-3663-000b-a17b-de186336da01，
或使用命令行 G et-AppPackageLog -ActivityID 18de53f0-3663-000b-a17b-de186336da01
所在位置 行:1 字符: 1
+ Add-AppxPackage .\Snap.Hutao.1.9.1.msix
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (D:\hutao\Snap.Hutao.1.9.1.msix:String) [Add-AppxPackage]，
    PSSecurityException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPac
   kageCommand
```

## 情况2

原因未知

```
0x80070570 Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed
```

```
Time                      ID           Message
----                      --           -------
2023/12/24 21:32:46       603          已使用主参数 Snap.Hutao.1.9.1.msix 以及选项 0 和 0 开始对程序包执行部署 Add 操作。要获取有关诊断应用部
                                       署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=235160。
2023/12/24 21:32:46       495          MsixvcStagingSession 中的 Common::Deployment::MsixvcStagingSession::GetManifestReader 失败，出现错误 0
                                       x80070570。
2023/12/24 21:32:46       402          错误 0x80070570: 从位置 Snap.Hutao.1.9.1.msix 中读取部件清单(manifest)失败，错误为: 文件或目录损坏且无
                                       法读取。
                                       。
2023/12/24 21:32:46       404          程序包  的 AppX 部署操作失败，错误为 0x80073CF0。此失败的具体错误文本是: MsixvcStagingSession 中的 Com
                                       mon::Deployment::MsixvcStagingSession::GetManifestReader 失败，出现错误 0x80070570。

```

![99e88674db5088708d43d20770b0ca8c](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/af446354-97f1-452d-9a64-d38a51ef20c1)
![a70d321089d712ea36beb261e488f123](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/593ba0db-0f02-4f0c-adab-3b2ed7598e92)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
该问题与证书验证有关，但在调试过程中没有发现用户有CA证书问题

**Comment by Masterain98** [comment]
有其它项目的用户提出更改appx安装目录可以解决

**Comment by Masterain98** [comment]
时间戳验证错误可能是原因之一

**Comment by NOWorEVER** [comment]
今天弄了一上午，一打开【Snap.Hutao.1.9.1.msix】就无限循环powershell。不管是用管理员模式打开powershell也没办法。
后面发现可以在 【管理员模式下的powershell】中运行： Add-AppxPackage -Path  【这边填你的安装包路径，也可以拖动进窗口，会自动填充】
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/57054154/6d979340-e912-4a50-9354-e48022787c0f)
弄完在开始菜单里面打开就行了

**Comment by Masterain98** [comment]
> 今天弄了一上午，一打开【Snap.Hutao.1.9.1.msix】就无限循环powershell。不管是用管理员模式打开powershell也没办法。
> 后面发现可以在 【管理员模式下的powershell】中运行： Add-AppxPackage -Path  【这边填你的安装包路径，也可以拖动进窗口，会自动填充】
> ![image](https://github.com/DGP-Studio/Snap.Hutao/assets/57054154/6d979340-e912-4a50-9354-e48022787c0f)
> 弄完在开始菜单里面打开就行了

你这个原因是app installer被破坏了，跑题

**Comment by NOWorEVER** [comment]
我只是提供一个安装思路，app installer各种检查就是没问题。也可能系统是有问题的

**Comment by Masterain98** [comment]
> 我只是提供一个安装思路，app installer各种检查就是没问题。也可能系统是有问题的

胡桃一直不给PS安装方法原因是不正常的系统下，就算补上了，也不知道还有多少缺少的组件，未来还有为什么问题那不知道。所以我们只原版系统环境。

**Comment by Lightczx** [comment]
在管理员模式下 Add-AppxPackage
