### ISSUE TITLE
[Bug]: 1.9 版本安装错误  应用未启动

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1222]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows 11 22H2

### Snap Hutao 版本

1.9.1

### 问题分类

安装和环境

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/5c7646e2-1fcc-410c-8bdf-06ea6e8bf006)

多个案例出现该问题，初步环境检测没有问题。msix包无法启动（显示上图错误），使用add-appxpackage可以安装。预计用户在安装更新时出现错误。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
## Checklist 

- [ ] 目录权限
- [ ] 文件权限
- [ ] App Installer 状态
- [ ] Microsoft.VCLibs.x64.14.00.Desktop.appx
- [ ] Microsoft.UI.Xaml.2.8.x64.appx
- [ ] CA 证书

**Comment by Lightczx** [comment]
使用 Add-AppxPackage
