### ISSUE TITLE
[Bug]: 1.9 版本安装错误 0x80040154

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1223]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows 11 22H2

### Snap Hutao 版本

1.9.1

### 问题分类

安装和环境

### 发生了什么？

多个不同的错误描述使用了该错误代码，可能需要分别讨论
![11080394eb0361551f4272da37dfea89](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/017f8f43-8836-427d-aac6-59f62aaafcf2)

根据社区结论，被破坏的系统组件有较大概率是问题来源，但具体原因不明。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
依旧是以管理员权限安装
