### ISSUE TITLE
建议连点增加鼠标侧键

### ISSUE THREAD

**Issue by dyak472007** [DGP-Studio/Snap.Hutao#1226]
### 背景与动机

按键盘还是太麻烦了

### 想要实现或优化的功能

增加鼠标侧键连点的选项

**Comment by qhy040404** [comment]
那个列表是系统给的，侧键如果没有修改过绑定一般为xbutton1或xbutton2

**Comment by Lightczx** [comment]
鼠标侧键按键事件属于鼠标事件
无法绑定快捷键
