### ISSUE TITLE
帧率解锁失效

### ISSUE THREAD

**Issue by MangoGong** [DGP-Studio/Snap.Hutao#1229]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.91.0

### 设备 ID

906F2537A6E1C4DA6BC5DD1F320FA1E8

### 问题分类

其它

### 发生了什么？

在原神更新4.3版本后，帧率解锁功能失效，进入游戏后通过Geforce Experience查看帧率为60fps。

### 你期望发生的行为？

修复此BUG

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/110ed98c-c338-4e38-b03c-8571edbc144b)

**Comment by MangoGong** [comment]
已关闭垂直同步

**Comment by Lightczx** [comment]
@MangoGong 在启动游戏页面中启动游戏，检查右上角是否出现解锁帧率成功字样

**Comment by MangoGong** [comment]
无，并且发现另一款解锁软件unlockfps_clr必须打开Windows8的兼容模式才能正常使用

**Comment by Lightczx** [comment]
设备问题

**Comment by MangoGong** [comment]
感谢回答
