### ISSUE TITLE
[Feat]: 每日便笺WebhookPost数据追加账户识别字段

### ISSUE THREAD

**Issue by yamei333** [DGP-Studio/Snap.Hutao#1230]
### 背景与动机

每日便笺Webhook提供的数据, 在拥有多个账号的情况下, 他分为多次Post, 并且Post数据看不出属于哪个号

### 想要实现或优化的功能

- 每日便笺Webhook希望增加对账户的识别字段(UID之类的)
- (可选)每日便笺Webhook的Post可以变为1次

**Comment by Lightczx** [comment]
@yamei333 在Header中增加一个字段可以接受么

**Comment by yamei333** [comment]
都行, 只要能识别

**Comment by Lightczx** [comment]
Header `x-uid`
