### ISSUE TITLE
[Feat]: 在Steam/Epic商店上架

### ISSUE THREAD

**Issue by w-xy** [DGP-Studio/Snap.Hutao#1231]
### 背景与动机

看开发日志上说因为签名的限制，从1.9.0版本开始，不再从微软商店发布新版本。这样的话，虽然还是可以通过Github或者官网来下载安装包，但是毕竟会有一些门槛在的，有点不利于Hutao的传播。

### 想要实现或优化的功能

是否考虑把Steam商店当作一个额外的分发渠道呢？不仅可以提供一个发布平台，也许下载量上去了还可以起到拓展新用户的作用。

**Comment by Masterain98** [comment]
1. Steam不支持msix格式应用
2. 胡桃有网站，国内有镜像

**Comment by qhy040404** [comment]
steam appid 100刀一个👏
