### ISSUE TITLE
[Feat]: 预设Hoyolab帐号的角色优先次序

### ISSUE THREAD

**Issue by KevkiOuO** [DGP-Studio/Snap.Hutao#1233]
### 背景与动机

由于我在亚服有个不玩的号，导致每次启动胡桃使用与Hoyolab相关的功能（例如上载深渊使用率、查询角色）都需要重新选择自己在港服的大号，无法保存选项，即时Hoyolab战绩已经显示大号还是要重新选
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/155013059/577655c9-3ab4-42e5-8c3e-f021d6eb0515)

### 想要实现或优化的功能

希望可以保存上一次选了的，或者新增一个根据uid预设选择的选项，或者用拉条的方式调较优先次序

**Comment by KevkiOuO** [comment]
> 需要在Hoyolab中自行选择默认角色

hoyolab 没有这个选项，战绩那边选了也没有用

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by Lightczx** [comment]
Tracked by #1394
