### ISSUE TITLE
[Bug]: 米游社验证失败横幅重复出现并占满整个UI界面

### ISSUE THREAD

**Issue by Solar-Matrix-Core** [DGP-Studio/Snap.Hutao#1237]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.1.0

### 设备 ID

9F9FED62306B8D875CB11AEA1194CD80

### 问题分类

用户界面

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52311106/c29a86b7-b313-4768-9083-8a26421d1d64)

如图所示，一般过了一天左右或者更短的时间会弹出米游社校验失败的横幅（这应该是正常的？），此时会提醒需要手动验证。
更新1.9版本后，这个横幅开始疯狂重复弹出，经常启动原神然后过一段时间关闭了就占满整个UI，而且横幅出现太多次（经常就十几二十个横幅），点掉它都要很久。

### 你期望发生的行为？

横幅应该只出现一次（印象中1.9版本之前没有此问题）。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你实时便笺开了自动刷新，但是一直在弹验证码

**Comment by Solar-Matrix-Core** [comment]
> 你实时便笺开了自动刷新，但是一直在弹验证码

并没有
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52311106/0dd45bc4-f27a-4db2-a67f-67c42a7eefb2)

**Comment by qhy040404** [comment]
更新1.9之前是不是开了，如果之前开过就是之前的任务没有删掉

**Comment by qhy040404** [comment]
你可以打开在关闭自动刷新看问题有没有解决

**Comment by Solar-Matrix-Core** [comment]
> 你可以打开在关闭自动刷新看问题有没有解决

1.9之前也没开，我关闭再打开试试看吧

——不过就算开了自动刷新然后一直弹验证码，也不考虑让这个横幅只出现一次吗？

**Comment by qhy040404** [comment]
因为对应的是多次请求，又不是一次的

**Comment by Lightczx** [comment]
按文档中方法删除实时便笺计划任务即可

**Comment by Solar-Matrix-Core** [comment]
> 按文档中方法删除实时便笺计划任务即可


![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52311106/367db280-25e9-4b17-8a61-9a20897ed472)

这个功能似乎每次打开胡桃就会自动打开，这是正常的吗？
