### ISSUE TITLE
[Bug]: 窗口无法拖动,TaskSwitcher 中窗口不显示图标

### ISSUE THREAD

**Issue by TsubakiAwa** [DGP-Studio/Snap.Hutao#124]
### Windows 版本

21H2 (19044.2130)

### Snap Hutao 版本

1.1.11.0

### 发生了什么？

Win+tab 窗口不显示左上角图标
![image](https://user-images.githubusercontent.com/53134066/196342215-0a0bade2-daf3-4a3f-8d7b-48a1bac33c5a.png)

[1.1.7+ 版本无法拖动窗口](https://hut.ao/FAQ/most-frequent-questions.html#_1-1-7-%E7%89%88%E6%9C%AC%E6%97%A0%E6%B3%95%E6%8B%96%E5%8A%A8%E7%AA%97%E5%8F%A3)  

>     如需移动窗口，可以尝试先缩小胡桃工具箱窗口再移动窗口。

 尝试了还是不行不了，如果能修一下就好了
![3 (3)](https://user-images.githubusercontent.com/53134066/196345080-daebf20c-0d02-4c12-93ea-176f3a0718fe.gif)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/2976

**Comment by himesamanoyume** [comment]
我发现光标放在程序下边缘随意拉动一下 改变窗口高度就可以拖动了

**Comment by Lightczx** [comment]
TaskSwitcher中的图标暂时没有办法替换为胡桃的图标，窗口拖动的问题已经解决了，如果确有图标的需求可以另外单独开个新 Issue
