### ISSUE TITLE
[Bug]: 元数据校验文件下载失败

### ISSUE THREAD

**Issue by lyz3124140647** [DGP-Studio/Snap.Hutao#1240]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.1.0

### 设备 ID

胡桃服务

### 问题分类

安装和环境

### 发生了什么？

<img width="1280" alt="屏幕截图 2023-12-30 235248" src="https://github.com/DGP-Studio/Snap.Hutao/assets/115634910/bb4e80f3-58f0-49c9-ada6-dceaa5b63e3a">
几乎全部功能都用不了

### 你期望发生的行为？

正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
无网络服务

**Comment by lyz3124140647** [comment]
> 无网络服务

假如无网络服务，那我这条反馈又是怎么发出来的呢

**Comment by Masterain98** [comment]
使用了代理服务，并且没有解除 Windows Container Loopback 限制，导致容器无网络。

**Comment by Masterain98** [comment]
很明显，issue模版里的第一条你是完全没看就点了。

**Comment by lyz3124140647** [comment]
> 使用了代理服务，并且没有解除 Windows Container Loopback 限制，导致容器无网络。

懂了

**Comment by lyz3124140647** [comment]
> 很明显，issue模版里检查清单的第一条你是完全没看就点了。帮你去掉了。

看肯定是看了，但是这个问题描述太模糊了，我在里面根本找不到关于我这个问题的解答，你们知道这个报错的原因，肯定能在文档里面一下找到解决方法，我不是工程师，我就是一普通用户，这两句报错，我根本就联想不到是代理问题，我又怎么去常见问题里面找答案

**Comment by Lightczx** [comment]
@Masterain98 
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/c1d44bb0-1c82-4940-810a-d15e0e756070)
这一节应该单独分出来好点吧，不应该限定在502下

**Comment by Lightczx** [comment]
但是奇怪的是公告是能正常加载的，元数据却不行，大概有其他的问题在

**Comment by lyz3124140647** [comment]
第一次报错的时候我记得确实动过代理，但是之后的几天，不开也会报错，如果说开代理会因为回环导致无法连接服务器，那我正常打开也报错又是因为什么呢，我截得那张图就是在不开代理的情况下发生的

**Comment by lyz3124140647** [comment]
现在不知道为什么又自己好了，我都没有关回环限制

**Comment by Masterain98** [comment]
> 但是奇怪的是公告是能正常加载的，元数据却不行，大概有其他的问题在

653366069 建议直接显示出 `米游社连接错误`
`ConnectionError` 后建议增加网络连接错误的显示

**Comment by Masterain98** [comment]
@Lightczx FYI, docs updated

https://hut.ao/zh/advanced/exceptions.html#httprequestexception-%E5%85%83%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E5%A4%B1%E8%B4%A5

**Comment by Lightczx** [comment]
> 653366069 建议直接显示出 `米游社连接错误`

653366069 是 **任何形式的请求错误**的 Fallback 代码，不限定于米游社

**Comment by Masterain98** [comment]
> 653366069 是 **任何形式的请求错误**的 Fallback 代码，不限定于米游社

能不能在弹出错误时，显示出是哪个主机连接错误了

**Comment by Lightczx** [comment]
> 能不能在弹出错误时，显示出是哪个主机连接错误了

目前只有元数据会显示成这样的 HTTP xxx 格式，其他的全都是 653366069
