### ISSUE TITLE
[Bug]: 首次启动或更新后启动，在下载基本图像资源时，若下载出现异常，无法手动强制刷新，会导致一直无法进入程序

### ISSUE THREAD

**Issue by Mornwind** [DGP-Studio/Snap.Hutao#1242]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.1.0

### 设备 ID

2284404B6582A6892BC0A2CCAAAD243D

### 问题分类

安装和环境

### 发生了什么？

首次启动或更新后启动，在下载基本图像资源时，一旦下载或网络出现异常，用户无法及时强制刷新下载进程，状态会一直卡在“文件下载异常”或“等待中”两种状态不动（见下图1）。
刚才我遇到这种情况时，把程序关闭重开也未能解决。而且重开后，程序不核实是否已下载，又把所有的下载任务又重新进行了一遍，然后继续卡在那几个任务上。最后，就算前面的任务已经下载完成，那几个卡住的任务仍然一直处于“等待中”，不进行下载，导致程序一直卡在下载资源这里，无法启动。
![QQ截图20231231190412](https://github.com/DGP-Studio/Snap.Hutao/assets/38060040/eb627946-9e7e-4f7e-b7a9-258203b720e3)

### 你期望发生的行为？

① 在下载基本资源的界面中，能考虑增加一个对单个下载任务的强制刷新以及全部强制刷新的按钮，可以手动刷新下载状态，也能让一直处于“等待中”的任务开始下载。
② 开始下载资源前，对已下载的资源进行一次检测，避免重复下载浪费时间。

附：Snap.Hutao Error Log
[Snap.Hutao Error Log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/13800927/Snap.Hutao.Error.Log.txt)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
重启程序即可跳过该步骤

**Comment by Lightczx** [comment]
等待其自行退出即可
