### ISSUE TITLE
[Feat]: 未登录胡桃账号用户上传深渊数据前进行提醒

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1245]
### 背景与动机

目前的逻辑是这样的：

1. 对于已登录胡桃账号的用户，初次上传深渊数据，获赠时长
2. 对于未登录胡桃账号的用户，初次上传深渊数据，返回无法获赠时长提示
3. 在2的前提下，用户注册胡桃账号，再次上传深渊数据，返回非首次上传无法获赠时长提示

成功拉到注册用户但是体验--

### 想要实现或优化的功能

在初次上传前对未登录胡桃账号的用户进行提醒，如`当前未登录胡桃账号，上传深渊数据无法获赠时长`

**Comment by Lightczx** [comment]
Tracked by #1394
