### ISSUE TITLE
[Feat]: 内置地图工具功能

### ISSUE THREAD

**Issue by ZonghuiWang** [DGP-Studio/Snap.Hutao#1248]
### 背景与动机

现在找材料，神瞳和打怪需要频繁的切换网页和游戏，非常麻烦，我相信大部分玩家都需要一个可以游戏内置的地图工具，标记勾选的神瞳，材料，怪物的位置，这个功能如果可以实现将会像魔兽大脚一样使本工具箱成为玩家人手必备的神器

### 想要实现或优化的功能

实现游戏内置的地图标记功能，标记怪物，神瞳，材料等位置

**Comment by Masterain98** [comment]
推荐使用 https://yuanshen.site/docs/
