### ISSUE TITLE
[Bug]: 导入抽卡记录失败

### ISSUE THREAD

**Issue by pan-hong-bo** [DGP-Studio/Snap.Hutao#1249]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

11

### Snap Hutao 版本

1.9.1

### 设备 ID

6C20B1D3E02F2326B8957C5A9EF4194A

### 问题分类

安装和环境

### 发生了什么？

我从提瓦特小助手中导出了UIGF格式的抽卡记录，在导入胡桃工具箱的时候发生了异常InvalidOperationException
数据包含异常物品,ld: 1650362760009958383

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by pan-hong-bo** [comment]
导入抽卡记录失败

**Comment by pan-hong-bo** [comment]
6C20B1D3E02F2326B8957C5A9EF4194A

**Comment by pan-hong-bo** [comment]
![Uploading cfa92a2a8004ef1a2be21d10d55f921.png…]()

**Comment by Lightczx** [comment]
是提瓦特小助手导出的对吧

**Comment by pan-hong-bo** [comment]
> 是提瓦特小助手导出的对吧

是的
![Uploading e2f42d421685c99933e3c49942e161b.png…]()

**Comment by Lightczx** [comment]
找小助手去，给我们没关系

**Comment by pan-hong-bo** [comment]
> 找小助手去，跟我们没关系

他们给的json格式有问题是嘛？

**Comment by BTMuli** [comment]
https://github.com/BTMuli/TGAssistant/blob/master/scripts%2FverifyUIGF.ts
