### ISSUE TITLE
无法更新祈愿记录和导出EXCEL

### ISSUE THREAD

**Issue by oaxoaw** [DGP-Studio/Snap.Hutao#125]
V1.1.9.0中，从缓存中 无法更新祈愿记录，导出excel选项也无响应，josn文件可以导出，但是其他祈愿记录软件导入时无法识别。想保存之前的祈愿记录，期待您的回复

**Comment by Lightczx** [comment]
缓存模式已经无法使用，很快会移除。
json文件提供一下

**Comment by oaxoaw** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月18日 19:16
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [DGP-Studio/Snap.Hutao] 无法更新祈愿记录和导出EXCEL (Issue #125)


缓存模式已经无法使用，很快会移除。
json文件提供一下

―
