### ISSUE TITLE
[Bug]: Cannot start Yuanshen.exe through Snap Hutao 1.9.1.0

### ISSUE THREAD

**Issue by MyTearDrop** [DGP-Studio/Snap.Hutao#1251]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.1.0

### 设备 ID

D19B2E340AD6A204813C0F2B60EF35E2

### 问题分类

游戏启动器

### 发生了什么？

Hello Guys,
[Snap.Hutao Error Log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/13811087/Snap.Hutao.Error.Log.txt)
![ResultException](https://github.com/DGP-Studio/Snap.Hutao/assets/139571859/fd1f8f83-8050-476f-834c-7ab1ae5dfba5)

This problem happended on last Sunday, I tried start Yuanshen.exe in Snap Hutao but a notify "ResultException InternalError" displayed.
What I tried: 1, re-install Snap Hutao. 2, re-set Yuanshen.exe path. 3, Disable all start options. 4, Reboot PC. 5, repair .Net 8.

### 你期望发生的行为？

How can fix it?

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
reboot your discord or close it

**Comment by MyTearDrop** [comment]
OK, get it. But can u give some advise why caused by discord? is trues Cheat Engine...
