### ISSUE TITLE
[Bug]: 国内网络环境下应用内更新速度太慢

### ISSUE THREAD

**Issue by YYl04** [DGP-Studio/Snap.Hutao#1258]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.2915

### Snap Hutao 版本

1.91.0

### 设备 ID

6CB672ACC91E7D36A97E7AD28CCF1814

### 问题分类

其它

### 发生了什么？

目前国内网络环境下的更新速度太慢，还不如去官网或GitHub下载安装包。还有就是自动安装更新容易打断用户操作
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/95568556/fdc4e52f-2a73-41c0-b314-f010f413dd92)

### 你期望发生的行为？

希望修复下载速度过慢和归零的问题以及让用户选择是否更新（考虑到目前1.92/1.93版本出现的问题）。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@Masterain98 国内 API 返回 Github 与极狐双链接

**Comment by YYl04** [comment]
重新开了一次卡在这了emm
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/95568556/82c956a5-be60-4672-9e54-f613c04f8289)

**Comment by YYl04** [comment]
好吧，可能确实是我网比较烂，但是极狐还是下得动的
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/95568556/e85b43ed-38f3-4860-9d2b-96bdbca48402)

**Comment by rainRb** [comment]
我这边在路由器端部署了openclash，GitHub下载网速也正常，但是应用内更新试了四次都卡住了，希望能设置一个手动选择更新源或者手动开关自动更新功能
