### ISSUE TITLE
[Bug]: 启动游戏时提示“切换服务器失败”

### ISSUE THREAD

**Issue by rainRb** [DGP-Studio/Snap.Hutao#1262]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2861

### Snap Hutao 版本

1.9.4.0

### 设备 ID

AF6D60BFC06DD2BEE70EC720ED950AD2

### 问题分类

游戏启动器

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/97787236/6bcb5c15-bef6-4953-9a6e-5bdae08cbacb)
点击启动游戏时无法启动游戏，而是弹出“切换服务器失败”，在调试控制台中也没有显示任何东西，但我并没有使用过切换服务器的功能。
当使用原神官方客户端时可以正常启动。
之前在1.9.1.0的版本可以正常使用。
已尝试过重启电脑，卸载然后重新安装Snap Hutao，关闭“启动参数”开关，开关“高级功能”开关，选择其他服务器，检查网络并尝试使用热点连接，在原神官方启动器内修复文件，删除Snap Hutao中的转换服务器缓存。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/97787236/ef3d3469-1132-4d5e-83ef-f3866dc464cd)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/97787236/fc747a1d-41a0-4ffc-9a9e-52d706b94e43)

### 你期望发生的行为？

启动原神并进入的是官方默认的服务器，我并不想更换服务器

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
当前版本不支持 C:/Program Files 路径

**Comment by XiaohangShi2000** [comment]
我也遇到了相同的问题，在启动游戏栏会无法启动，在主页点击“启动游戏”是可以正常启动的，解锁帧率上限的高级功能也是正常的

**Comment by shum-elli** [comment]
+1
