### ISSUE TITLE
自动连点功能 手柄适配

### ISSUE THREAD

**Issue by dumpling13** [DGP-Studio/Snap.Hutao#1268]
### 背景与动机

自动连点功能 可以出一个手柄版本的适配么 目前好像只能用鼠标连点 感谢

### 想要实现或优化的功能

自动连点功能 可以出一个手柄版本的适配么 目前好像只能用鼠标连点 感谢

**Comment by qhy040404** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/292a6a13-0f68-4d3e-b86e-856d4bd10abc)
去测gamepad开头的，我相信你看得懂

**Comment by dumpling13** [comment]
> ![image](https://private-user-images.githubusercontent.com/45379733/294504665-292a6a13-0f68-4d3e-b86e-856d4bd10abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjA4NzYsIm5iZiI6MTcwNDQ2MDU3NiwicGF0aCI6Ii80NTM3OTczMy8yOTQ1MDQ2NjUtMjkyYTZhMTMtMGY2OC00ZDNlLWI4NmUtODU2ZDRiZDEwYWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEzMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjOGZhMWY5YWYyOGZkZjNhZGZlNDFhYTYzZTYwOWQ5NzA2NjNkNzgzNDhiOGQ0NGY3MzNkYjAwYThkMTRkYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aEkDLryOmnX-enI3qdENSHrdPDirl8y4TIJM4qTvgqk) 去测gamepad开头的，我相信你看得懂

这个是开关快捷键设置 没用 是想要实现游戏内 一直按手柄A键的连点

**Comment by Lightczx** [comment]
> 这个是开关快捷键设置 没用

设置并按下按键后胡桃的标题栏的指示器不会变化么

**Comment by dumpling13** [comment]
> > 这个是开关快捷键设置 没用
> 
> 设置并按下按键后胡桃的标题栏的指示器不会变化么

![111](https://github.com/DGP-Studio/Snap.Hutao/assets/117969279/6ccfa6c6-5e55-42a6-8ad0-4b6054f1ffc3)
设置了A键 一直按 标题栏没变的

**Comment by Lightczx** [comment]
做不了
