### ISSUE TITLE
[Bug]: 创建的快捷方式链接至任务栏后无法以管理员权限启动

### ISSUE THREAD

**Issue by qq2473577621** [DGP-Studio/Snap.Hutao#1269]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.4.0

### 问题分类

安装和环境

### 发生了什么？

![lnk](https://github.com/DGP-Studio/Snap.Hutao/assets/87268494/3fab1444-c0fa-4a1f-80ae-e0227ff6b27f)
![lnk2](https://github.com/DGP-Studio/Snap.Hutao/assets/87268494/0bc36937-f90e-47d1-b31a-cd6af760a938)
1.9.4.0版本中创建的快捷方式链接至任务栏后，单击是以普通用户权限运行（桌面中直接单击可正常管理员权限启动），看起来任务栏中像是直接指定到了exe在的位置，而之前版本则是使用powershell进行启动，链接到任务栏中也可正常管理员启动。

### 你期望发生的行为？

创建的快捷方式链接至任务栏后直接点击即可

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
intended
