### ISSUE TITLE
[Bug]: 属性统计界面程序崩溃

### ISSUE THREAD

**Issue by j36k** [DGP-Studio/Snap.Hutao#127]
### Windows 版本

22623.746

### Snap Hutao 版本

1.1.12.0

### 发生了什么？

![微信截图_20221018193819](https://user-images.githubusercontent.com/104725216/196429019-54618475-3ea1-482e-be26-40ce849afe89.png)
[打开胡桃点击属性统计界面，显示如图所示，反复切换点击后程序崩溃,可复现]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9810265/Log.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by misaka10384** [comment]
这个问题我之前遇到过  本来也打算反馈一波 但是1.1.9之后我就没这个问题了  以为修复了我就没管了.jpg

**Comment by KyrieNO1** [comment]
Windows11 22621.674在1.1.11和1.1.12也都遇到过这个问题

**Comment by Lightczx** [comment]
备份数据后删除 User.db

**Comment by j36k** [comment]
删除userdata.db后问题消失
