### ISSUE TITLE
[Bug]: 米游社验证失败横幅即便在“自动刷新”关闭的情况下也会反复弹出

### ISSUE THREAD

**Issue by Solar-Matrix-Core** [DGP-Studio/Snap.Hutao#1272]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.4.0

### 设备 ID

9F9FED62306B8D875CB11AEA1194CD80

### 问题分类

实时便笺

### 发生了什么？

如图所示

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52311106/db9683a8-50f9-4c18-b106-b5425f1cc4a5)

之前提过了这个bug，被认为是操作问题而关闭：https://github.com/DGP-Studio/Snap.Hutao/issues/1237

但是我反复重试了，即便是关掉了自动刷新，这个横幅仍然会反复弹出（我不确定上个issue里提到的“按照文档关闭实时便笺”是不是指关闭自动刷新），而且存在关闭自动刷新、下次启动胡桃自动刷新就会重新被打开的情况。

我很确定1.9.0以前（不含）的版本没有这个问题，因为我此前知道开自动刷新会弹出验证失败横幅的情况所以一直是关着它然后手动刷新的。

### 你期望发生的行为？

如果关闭自动刷新，那么不应该弹出验证失败的横幅。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Solar-Matrix-Core** [comment]
> 请更新至最新版本: 稳定版: [1.9.4](https://api.snapgenshin.com/patch/hutao/download) 测试版: [2024.1.5.1](https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7423197372/artifacts/1150138415)

标记错误了版本，已更新为1.9.4

**Comment by Solar-Matrix-Core** [comment]
现在如果我尝试关闭自动刷新，下面的选项仍然可选（这应该是bug吧）：

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52311106/158d7de8-71f9-4f13-921e-3616e0fcefbb)

然后如果我打开自动刷新，再切换时间，就会提示这个：

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52311106/adb95b7e-007e-4b6e-91a7-ca8b444c2191)

但是这个在管理员模式下是无法更改的

**Comment by Lightczx** [comment]
关闭自动刷新后如果下方的选项依旧可选说明任务计划没有成功删除，需要按文档说明删除，并且你的Windows账户类型不支持你使用这个功能，删除后请不要尝试打开

**Comment by Lightczx** [comment]
下个版本会修正UI上的相关问题，但是像你这样的注册任务计划失败的结果不会改变
