### ISSUE TITLE
[Bug]: 登录 HoyoLab 报错 2001

### ISSUE THREAD

**Issue by MUKAPP** [DGP-Studio/Snap.Hutao#1275]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26020.1000

### Snap Hutao 版本

1.9.4.0

### 问题分类

其它

### 发生了什么？

登录 HoyoLab时报错：2001 sign in error
![a0aae2a5e092b0b525e37c21f7971633](https://github.com/DGP-Studio/Snap.Hutao/assets/41848070/52c4d5d5-4cc5-4e56-8190-552eafcc4ebe)

---

When signing in to HoyoLab, error 2001 "sign in error" appeared.

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
需要先登录Hoyolab
