### ISSUE TITLE
[Feat]: 我好懒啊 你能帮帮我吗

### ISSUE THREAD

**Issue by misaka10384** [DGP-Studio/Snap.Hutao#1278]
### 背景与动机

不想开设置

### 想要实现或优化的功能

从这样
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/61707010/783879e0-df4a-40b9-8bb7-441f7e7fd896)
变成这样 
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/61707010/948571f6-bff6-4b3a-a116-be0903a43ae8)

**Comment by QGhappyChenCheng** [comment]
6

**Comment by Masterain98** [comment]
原神没有HDR

**Comment by AkaHanshan** [comment]
玩原神玩的

**Comment by QGhappyChenCheng** [comment]
> 玩原神玩的

nnd 不如元梦之星的一根弔毛

**Comment by Lightczx** [comment]
没有太大的实现意义
