### ISSUE TITLE
[Bug]: 资源下载的用语更新

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1279]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows 22H2

### Snap Hutao 版本

1.9.4

### 问题分类

用户界面

### 发生了什么？

- 建议将 `客户端` 更换为 `完整包` 以和 `增量包` 对应
- 预下载版本可以增加 `预下载 - ` 这样的前缀

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
> * 预下载版本可以增加 `预下载 - ` 这样的前缀

预下载开放时提供的文件名已经足够表达上下文含义
