### ISSUE TITLE
[Feat]: Add Support of HoYoLAB Official Tools

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1280]
### Background & Motivation

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/e550495c-e072-40d8-8751-99a0cac40669)

For CN bbs, MiHoYo provides their official tools via a website, so Snap Hutao can load it in a WebView pop-up with its URL. This is a also a good entry point to let users manually identify if their account is under CAPTCHA status.

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/9c2b7d0d-3889-401a-8e3a-315265d76f13)

However, the same tools in HoYoLAB are provided by API and rendered by the browser. This is the reason why `Official Tools` is still not supported with HoYoLAB accounts in Snap Hutao.

### Detail of the Feature

Due to the difference in source, this may be a challenging job.

**Comment by Lightczx** [comment]
Tracked by #1394
