### ISSUE TITLE
解锁帧率不彻底

### ISSUE THREAD

**Issue by ZCCCK666** [DGP-Studio/Snap.Hutao#1281]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2715

### Snap Hutao 版本

最新1.9.4.0

### 设备 ID

DD5460500BCDFCBFB00ADC660A392D6D

### 问题分类

安装和环境

### 发生了什么？

进入游戏锁30帧，但是打开游戏内设置画面，又恢复我调的84帧，回到游戏画面， 又锁30帧

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/7e191928-74e4-4abb-b6db-e9a9b08c4abe)
