### ISSUE TITLE
[Bug]: 启动游戏时显示内存匹配遇到问题

### ISSUE THREAD

**Issue by pubproprietary** [DGP-Studio/Snap.Hutao#1288]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.2921

### Snap Hutao 版本

1.9.4.0

### 设备 ID

7D28D9ADA5BD313DF6FB93989ACB6DF9

### 问题分类

游戏启动器

### 发生了什么？

<img width="426" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/89008799/b21d39a3-3d1a-490c-8a0c-b845dfe0fc11">
点击启动游戏时会弹出该提示，无论是否在管理员模式下，而官方启动器则能正常启动。
设置为解锁120帧，分辨率2560*1600，覆盖默认的全屏状态

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
关杀软试一下

**Comment by Lightczx** [comment]
> 无论是否在管理员模式下

非管理员模式不可能弹出这个

**Comment by pubproprietary** [comment]
噢，光速解决了，我重新设置了一下游戏路径然后他就能正常打开了（一开始出现问题的时候是弹出窗口然后出现进程，加载一开始的白屏然后yuanshen.exe无响应）

**Comment by Lightczx** [comment]
![42dfc376908b51a877a05a8a7a8696f9](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/b855f697-4cc2-4f20-bb63-c58223afa10a)
