### ISSUE TITLE
[Bug]: 无法使用MSIX安装包安装程序

### ISSUE THREAD

**Issue by FM-123** [DGP-Studio/Snap.Hutao#1296]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

win11 21H2

### Snap Hutao 版本

1.9.5

### 问题分类

安装和环境

### 发生了什么？

无法使用MSIX安装包安装程序，安装时提示“此应用包不支持通过应用安装程序安装，因为它使用了某些受限制的功能。”；但并未提示证书异常相关问题，也并未报出错误提示。
使用Snap.Hutao.Deployment安装，安装窗口闪退，无法安装
![Snipaste_2024-01-12_00-33-25](https://github.com/DGP-Studio/Snap.Hutao/assets/83116487/7d50b25e-f5af-40aa-995c-b3c01914f860)
![Snipaste_2024-01-12_00-33-33](https://github.com/DGP-Studio/Snap.Hutao/assets/83116487/d04f4888-85ae-418f-aef1-57d4d509fdf5)

### 你期望发生的行为？

可以有解决方案

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
[Snap.Hutao.Deployment.zip](https://github.com/DGP-Studio/Snap.Hutao/files/13910399/Snap.Hutao.Deployment.zip)

@FM-123 试试这个版本

**Comment by ahoujanai** [comment]
该问题是否已解决，我遇到相同问题，解决办法是什么？

**Comment by Lightczx** [comment]
> 该问题是否已解决，我遇到相同问题，解决办法是什么？

甚至就在你回复的上面

**Comment by FM-123** [comment]
> 该问题是否已解决，我遇到相同问题，解决办法是什么？

一直无法安装，我是用github中的代码项目运行的，楼上回复了一个Snap.Hutao.Deploymen，你可以试试

**Comment by ahoujanai** [comment]
> > 该问题是否已解决，我遇到相同问题，解决办法是什么？
> 
> 一直无法安装，我是用github中的代码项目运行的，楼上回复了一个Snap.Hutao.Deploymen，你可以试试

已下载该文件Snap.Hutao.Deploymen打开后下载的安装包安装，但是与原来的问题一样，依然无法安装

**Comment by Masterain98** [comment]
> 已下载该文件Snap.Hutao.Deploymen打开后下载的安装包安装，但是与原来的问题一样，依然无法安装

提供截图

**Comment by ahoujanai** [comment]
> > 该问题是否已解决，我遇到相同问题，解决办法是什么？
> 
> 一直无法安装，我是用github中的代码项目运行的，楼上回复了一个Snap.Hutao.Deploymen，你可以试试

重新尝试已成功安装，谢谢！

**Comment by ahoujanai** [comment]
> > 已下载该文件Snap.Hutao.Deploymen打开后下载的安装包安装，但是与原来的问题一样，依然无法安装
> 
> 提供截图

重新尝试已成功安装，谢谢！

**Comment by ChrisKimZHT** [comment]
Windows 11 23H2 同样出现该问题，是否是程序包有异常？
