### ISSUE TITLE
[Feat]: 加入一个可以决定“胡桃”自动更新的开关

### ISSUE THREAD

**Issue by ZTJun** [DGP-Studio/Snap.Hutao#1297]
### 背景与动机

如题，外地出差的时候连接手机热点非常容易出现带宽不足的情况，如果加入这个开关可以自主决定“胡桃”自动下载的行为就很好了，还能避免境外高额的计费数据花费。

### 想要实现或优化的功能

建议加入一个是否自动下载“胡桃”更新的开关，或跟随Windows设置中的“按流量计费的连接”来决定自动数据下载的行为。如果处于离线或设定的网络状态则显示目前处于的状态并停止自动下载。

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by Masterain98** [comment]
建议：
1. 在获取到更新信息时，在右上角现有的位置显示 `有更新可用`；在胡桃每次启动的时候弹窗提示，询问用户是否更新
2. 在用户手动确认后再开始下载和安装
3. 若用户选择稍后再更新，保持右上角按钮存在，点击后可以再次进入处理更新的逻辑
---
可选的改进：
1. 通过一个额外的按钮和webview2来显示更新日志（我还是建议抄寻空）
2. 判断系统设置中的 `按流量计费的连接` 设置项并增加对应的二步确认提示

**Comment by ZTJun** [comment]
> 建议：
> 
> 1. 在获取到更新信息时，在右上角现有的位置显示 `有更新可用`；在胡桃每次启动的时候弹窗提示，询问用户是否更新
> 2. 在用户手动确认后再开始下载和安装
> 3. 若用户选择稍后再更新，保持右上角按钮存在，点击后可以再次进入处理更新的逻辑
> 
> 可选的改进：
> 
> 1. 通过一个额外的按钮和webview2来显示更新日志（我还是建议抄寻空）
> 2. 判断系统设置中的 `按流量计费的连接` 设置项并增加对应的二步确认提示

btw，建议提供 `跳过当前版本更新` 的选项，以免新版本功能缺失或改动以便跳过版本

**Comment by Lightczx** [comment]
> btw，建议提供 `跳过当前版本更新` 的选项，以免新版本功能缺失或改动以便跳过版本

@Masterain98 FYI again

**Comment by Masterain98** [comment]
> > btw，建议提供 `跳过当前版本更新` 的选项，以免新版本功能缺失或改动以便跳过版本
> 
> @Masterain98 FYI again

我认为第一点已经足够覆盖这一想法了，如果真的有问题，hotfix吧

**Comment by Lightczx** [comment]
Tracked by #1394
