### ISSUE TITLE
[Feat]: 无感接口模板添加至剪切板

### ISSUE THREAD

**Issue by halointernet** [DGP-Studio/Snap.Hutao#1298]
### 背景与动机

在输入无感接口的位置因为容易输错导致配置不生效

### 想要实现或优化的功能

添加模板至剪切板，然后进行自行更改，方便用户使用，防止写错

**Comment by qhy040404** [comment]
程序内现有文档已经足够详细

**Comment by Lightczx** [comment]
> validate的值（0 or 1 ）,写的并不明确 大多数人非技术人员并不知道0 和 1 代表着什么，个人觉得可以优化一下

如果你使用现成的验证服务，无需知晓此值的含义
如果你打算自行实现服务，那么此值的含义在你实现的过程中也会通过其他渠道了解
