### ISSUE TITLE
[Bug]: 无法正常启动hutao

### ISSUE THREAD

**Issue by Genicur** [DGP-Studio/Snap.Hutao#1299]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.2921

### Snap Hutao 版本

1.9.5.0

### 问题分类

其它

### 发生了什么？

无法正常启动，提示”你需要转到高级选项进行Snap Hutao并选择"修复"。如果仍然遇到问题，请重新安装此应用或与管理员联系。“
已经尝试过上述的修复和重装hutao，并看过常见问题，没有相关解决方案
我该如何协助解决？
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/93466263/6bd6c701-c030-4de5-baed-32557ad87795)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by 6mod9** [comment]
一样的情况，昨晚还能正常用的，今天早上就打不开了，重新安装也不能进入

**Comment by Lightczx** [comment]
@Genicur @6mod9 之前是否安装了商店版本

**Comment by 6mod9** [comment]
> @Genicur @6mod9 之前是否安装了商店版本
是，最早一直用的微软商店版本，后来卸载换的新版

**Comment by Lightczx** [comment]
加远程调试群 928732285

**Comment by 6mod9** [comment]
> 加远程调试群 928732285

验证问题是什么？

**Comment by Genicur** [comment]
> @Genicur @6mod9 之前是否安装了商店版本

是的

**Comment by Lightczx** [comment]
> 验证问题是什么？

先加公告群，找管理拉

**Comment by qhy040404** [comment]
管理员powershell运行
```powershell
net stop appxsvc; net start appxsvc; Invoke-WebRequest -Uri https://aka.ms/windowsappsdk/1.4/latest/windowsappruntimeinstall-x64.exe -OutFile $env:temp/windowsappruntimeinstall-x64.exe; Invoke-Expression $env:temp/windowsappruntimeinstall-x64.exe
```
