### ISSUE TITLE
无法使用MSIX下载，显示：应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。

### ISSUE THREAD

**Issue by Therm4l** [DGP-Studio/Snap.Hutao#1300]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3007

### Snap Hutao 版本

1.9.5.0

### 设备 ID

806A19E0142E03A07B77FE612446A974

### 问题分类

安装和环境

### 发生了什么？

# 情景描述
今天打开的时候，报错无法运行，需要打开Windows高级操作进行修复等。然后修复后无效，删除重新使用msix安装包进行安装。

# 安装问题
下载安装包后进行安装，显示“应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。”
<img width="489" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/122506724/a476ff4c-4c77-4626-9f06-edf2ca5e0123">

### 你期望发生的行为？

期望可以正常安装并使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/88f992f6-5510-4985-9ade-424ba315a897)
你已阅读个屁

**Comment by Masterain98** [comment]
https://hut.ao/zh/advanced/dependency.html

**Comment by Lightczx** [comment]
#1299

**Comment by Therm4l** [comment]
不好意思，确实没看到有人反馈了问题，就看了个标题
