### ISSUE TITLE
[Bug]: 文件系统权限不足，无法转换服务器

### ISSUE THREAD

**Issue by kakairin** [DGP-Studio/Snap.Hutao#1301]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3007

### Snap Hutao 版本

1.9.5.0

### 设备 ID

EB7D87AE4D153CED3853D02D830541EE

### 问题分类

游戏启动器

### 发生了什么？

转换服务器时提示文件系统权限不足，无法转换。已经是管理员模式运行的了。

### 你期望发生的行为？

解决无法转换服务器的问题
PS：发送管理员模式启动的快捷方式到桌面后，点击桌面的快捷方式可以管理员模式运行，但是把快捷方式发送到启动栏后，点击启动栏的图标运行胡桃是普通模式，之前的版本不是这样的，这个能不能改回去...

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
原神路径在哪

**Comment by kakairin** [comment]
> @kakairin 你的原神路径在哪

没有日志可能是我又退回1.9.1版本了，路径在C:\Program Files\Genshin Impact\Genshin Impact Game

**Comment by qhy040404** [comment]
用1.9.1写1.9.5
![42dfc376908b51a877a05a8a7a8696f9](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/1d9812c6-46e6-4720-8388-1c8300ee3323)

**Comment by kakairin** [comment]
> 用1.9.1写1.9.5 ![42dfc376908b51a877a05a8a7a8696f9](https://private-user-images.githubusercontent.com/45379733/296145435-1d9812c6-46e6-4720-8388-1c8300ee3323.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDE3ODEsIm5iZiI6MTcwNTA0MTQ4MSwicGF0aCI6Ii80NTM3OTczMy8yOTYxNDU0MzUtMWQ5ODEyYzYtNDZlNi00NzIwLTgzODgtMWM4MzAwZWUzMzIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNjM4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmQyNWI5ZWQ3NjVkNDFhZjdiOWU1Njc0YTA3NjE0NzlkZWFjZWY0ZTZjODc4NGQyMDc4ZmM0ZGI5YmM3OTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h_7JwQCjWSCQwg_RiPpcZnNbgU6nABJhYBMgnPpQv6c)

1.9.5出问题才退回1.9.1，看清楚。

**Comment by qhy040404** [comment]
原神安装在c盘不支持转换服务器，要转换服务器安到其他盘

**Comment by Lightczx** [comment]
> C:\Program Files\Genshin Impact\Genshin Impact Game

不支持 Program Files 路径，另外不支持回退版本使用

**Comment by gaohui2004** [comment]
同问
