### ISSUE TITLE
实时便笺优化

### ISSUE THREAD

**Issue by home110120** [DGP-Studio/Snap.Hutao#1303]
### 背景与动机

1. 实时便笺自动刷新选项都过于频繁，易导致认证问题。
2. 出现认证问题时，Webhook不会有消息

### 想要实现或优化的功能

1. 增加更多更长的实时便笺自动刷新间隔，或是支持自定义时间。
2. 出现认证问题时，依然发送Webhook（可以使用一个变量表示是不是有认证问题，这个变量在无认证问题时也可以保留）

**Comment by Lightczx** [comment]
> 1. 实时便笺自动刷新选项都过于频繁，易导致认证问题

你想多久刷新一次

**Comment by Lightczx** [comment]
closing for no response
