### ISSUE TITLE
[Feat]: 启动游戏检测账号增加提示

### ISSUE THREAD

**Issue by qhy040404** [DGP-Studio/Snap.Hutao#1305]
### 背景与动机

特定情况下点击检测账号无任何反馈

### 想要实现或优化的功能

账号存在时，`$"""账号"{account.Name}"已存在"""`
B服，`"Bilibili 服账号切换暂不支持"`

**Comment by Lightczx** [comment]
> 注册表无记录时，`"游戏内未登录"`

不应该有这个的检测，否则会有人因为设备问题掉线产生混淆

**Comment by qhy040404** [comment]
> 注册表无记录时，`"游戏内未登录"`

这个我是指`null`的时候

**Comment by Lightczx** [comment]
> > 注册表无记录时，`"游戏内未登录"`
> 
> 这个我是指`null`的时候

如果用户见到过这个提示一次，那么如果在下次他掉登录时之前检测的账号无法收到这个提示
他会认为这是我们的问题

**Comment by qhy040404** [comment]
合理

**Comment by Lightczx** [comment]
Tracked by #1394
