### ISSUE TITLE
[Localization] pt-BR notice

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Hutao#1306]
Hi, @t0piy .
We found that you are trying to localize our application into pt-BR at https://github.com/t0piy/Snap.Hutao
If you are meant to add the translation into our application, and you don't want to work in vain:
Please visit [crowdin](https://crowdin.com/project/snap-hutao) and we do translation work here.

Please let us known if you take any action. thanks!

**Comment by t0piy** [comment]
Isn't there a way to import the file I modified...?

**Comment by t0piy** [comment]
From what I understand, it is possible to import files, however this is not possible with ´.resx´

**Comment by Masterain98** [comment]
@Lightczx take a try to add the new resx to see if Crowdin can identify it

**Comment by Masterain98** [comment]
@t0piy Can you start a Pull Request to add your work to the dev branch? So we can check if Crowdin can import them in this way. If this doesn't work, I will contact Crowdin for help.

**Comment by qhy040404** [comment]
Hello @t0piy , we noticed that you haven't opened the pull request for a long time, so we opened the pull request and merged it into the develop branch. Now you can go to crowdin to complete your translation. Thank you for your contribution.
