### ISSUE TITLE
任务栏快捷图标管理员身份运行

### ISSUE THREAD

**Issue by Etealunesphilar** [DGP-Studio/Snap.Hutao#1309]
### 背景与动机

旧版本更新上来（至少1.9.4）设置的任务栏快捷打开直接就是管理员运行，过去好像也没有非管理员运营过。
但是最近电脑重做系统最新版win10重新安装后（1.9.5）发现固定在任务栏后打开，并不是管理员权限打开的。并且反馈中心中的方法，创建管理员运行的桌面图标拖到任务栏上也变成了不能管理员运行打开的方式。
甚至网上搜到的那个任务栏固定图标所在位置里没有胡桃，这种应用真是特殊，，，
希望能有在固定在任务栏以管理员运行快捷方式的方法，功能

### 想要实现或优化的功能

希望能有在固定在任务栏以管理员运行快捷方式的方法，功能

**Comment by qhy040404** [comment]
intended

**Comment by Masterain98** [comment]
> 创建管理员运行的桌面图标拖到任务栏上也变成了不能管理员运行打开的方式


我这么操作是没有问题的

**Comment by Lightczx** [comment]
> 创建管理员运行的桌面图标拖到任务栏上也变成了不能管理员运行打开的方式

更换了启动方式，不再支持手动固定到任务栏的快捷方式以管理员模式启动
