### ISSUE TITLE
[Bug]: user not exist

### ISSUE THREAD

**Issue by za7ek** [DGP-Studio/Snap.Hutao#1310]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3930

### Snap Hutao 版本

1.9.5.0

### 设备 ID

C51B51294CC507FBEBA2E40166979C22

### 问题分类

用户界面

### 发生了什么？

账号登陆，选择米游社-网页登陆。登陆成功后，点击右上角“我已登陆”，提示此cookie 无效，操作失败，和 状态：-20001|信息：user not exist

### 你期望发生的行为？

账号登陆成功，能够正常显示自己的账号信息

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
账号未初始化

**Comment by za7ek** [comment]
> 账号未初始化

请问下是需要在哪里操作，米哈游官网么？

**Comment by qhy040404** [comment]
下载米游社登登录一次

**Comment by za7ek** [comment]
> 下载米游社登登录一次

万分感谢，已经解决了
