### ISSUE TITLE
[Bug]: 流浪者角色资料异常

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1316]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23615.1000

### Snap Hutao 版本

1.9.5.0

### 设备 ID

FA47BE878C143D2FE18785B660EF114A

### 问题分类

Wiki

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/cdbda0bf-3af4-4001-b67c-ffd273b7164f)

### 你期望发生的行为？

改成对应 i18n 的流浪者的名字

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/a1ac7f48-935b-437f-b325-9c5c94ec08a3)

**Comment by Mikachu2333** [comment]
1.9.6.0仍未修复

![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/5ab273e4-9bb8-474f-8ce4-0f73014d5089)

**Comment by Mikachu2333** [comment]
已提交胡桃数据的pr，通过简单粗暴的替换修正了相关内容

**Comment by BTMuli** [comment]
@Lightczx 衣装没改

**Comment by Mikachu2333** [comment]
> 已提交胡桃数据的pr，通过简单粗暴的替换修正了相关内容

唔，因为被提醒胡桃的数据为全自动生成，无人工干预，继续等待修复中……

**Comment by qhy040404** [comment]
8b1613d 已修复此问题

**Comment by Lightczx** [comment]
如果存在其他文本未替换的问题请开新Issue
