### ISSUE TITLE
[Feat]: 希望可以在树脂便笺界面添加启动游戏选项

### ISSUE THREAD

**Issue by Griselda-droid** [DGP-Studio/Snap.Hutao#1318]
### 背景与动机

在便笺界面查看树脂后却不能直接启动满树脂的账号

### 想要实现或优化的功能

在便笺界面查看树脂后之前启动游戏，更合理方便

**Comment by Lightczx** [comment]
# UI/UX Implementation Details

* 在树脂卡片的顶部添加启动游戏按钮
* 未绑定到账号的卡片不应显示

# Backend Implementation Details
由于需要实现在实时便笺界面启动游戏，需要在一定程度上重构启动游戏视图模型

* 需要将主页启动游戏卡片/启动游戏页面/实时便笺卡片启动游戏按钮的公用部分提取，并注册为全局单例
* 需要注意与任务栏快速启动窗口使用的视图模型的交互（实际上与启动游戏页面相同）

**Comment by Lightczx** [comment]
Tracked by #1394
