### ISSUE TITLE
[Feat]: 提取米游社顶部nav内容

### ISSUE THREAD

**Issue by qhy040404** [DGP-Studio/Snap.Hutao#1319]
### 背景与动机

[30s速通原神4.4前瞻](https://b23.tv/fEcmPKQ)

[WebStatic](https://webstatic.mihoyo.com/bbs/event/live/index.html?act_id=ea202401171132210592&mhy_presentation_style=fullscreen&game_biz=hk4e&utm_source=share&utm_medium=bbs&utm_campaign=app)

<details>
<summary>逆天言论</summary>

![IMG_4481](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/c8d2fe7d-e584-4119-b186-166a7a4cbd8c)

### 想要实现或优化的功能

![IMG_4482](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/7f11790f-85ac-4023-8f41-91c6b9ec2202)

</details>

**Comment by BTMuli** [comment]
![79dc5a98e8c8b54a461a94e93adebba9](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/1c8faa2e-3516-4d17-8041-d146bfdd0f5c)

**Comment by BTMuli** [comment]
参考效果：
![我的视频 mp4_20240119_221054 549](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/d29a4279-b968-49d3-8d8c-03d2b7afa181)

API：`https://bbs-api.miyoushe.com/apihub/api/home/new?gids={gid}`

返回类型：[src/types/BBS/Navigator.d.ts](https://github.com/BTMuli/TeyvatGuide/blob/6625428af445f019ef12e397b3b2013c915b22ce/src/types/BBS/Navigator.d.ts)

**Comment by Lightczx** [comment]
Tracked by https://github.com/DGP-Studio/Snap.Hutao/issues/1394

**Comment by Lightczx** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/issues/73
