### ISSUE TITLE
希望每次启动游戏的时候都能把分辨率修改为当前屏幕分辨率

### ISSUE THREAD

**Issue by zhongshen6** [DGP-Studio/Snap.Hutao#1320]
### 背景与动机

我经常在不同的屏幕上启动游戏，在电脑上时使用2k分辨率启动，躺床上使用串流时是2560×1600，用手机串流触屏原神时是2410x1080，这导致我每次切换都需要在游戏内重新设置分辨率，因为hutao的快捷设置分辨率没有2560x1600和2410x1080

### 想要实现或优化的功能

希望能每次启动游戏都能自动设置游戏分辨率为屏幕分辨率，或者添加自定义的快捷分辨率选项，也希望可以在主页的启动游戏选项旁边添加触屏启动的按键，每次都在启动参数里修改太麻烦了

**Comment by Lightczx** [comment]
> 希望能每次启动游戏都能自动设置游戏分辨率为屏幕分辨率

肯定不行

> 或者添加自定义的快捷分辨率选项

可以为你专门添加你想要的这两个分辨率选项

> 也希望可以在主页的启动游戏选项旁边添加触屏启动的按键

暂不考虑
