### ISSUE TITLE
[Bug]: 尝试移动程序安装位置时出现错误

### ISSUE THREAD

**Issue by RainThings** [DGP-Studio/Snap.Hutao#1321]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.5.0

### 问题分类

安装和环境

### 使用管理员权限操作，尝试将APP从C盘移动到F盘，尝试UI操作失败，以下是使用PowerShell操作返回的错误信息

> PS F:\Users\RainThings> Move-AppxPackage -Package "60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy" -Volume F:\

Move-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF6, 无法注册包。
60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy功能授权失败，错误代码为 0x800701C5.
注意: 有关其他信息，请在事件日志中查找 [ActivityId] af212382-4b3c-000b-c57d-28af3c4bda01，或使用命令行 Get-AppPackageLog -ActivityID af212382-4b3c-000b-c57d-28af3c4bda01
所在位置 行:1 字符: 1
+ Move-AppxPackage -Package "60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnn ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (60568DGPStudio....__wbnnev551gwxy:String) [Move-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.MoveAppxPackageCommand

> PS F:\Users\RainThings> Get-AppPackageLog -ActivityID af212382-4b3c-000b-c57d-28af3c4bda01

Time                     ID           Message
----                      --           -------
2024/1/20 21:33:50        603          已使用主参数 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy 以及选项 ForceA
                                       pplicationShutdownOption 和 0 开始对程序包执行部署 MovePackageOperation 操作。要                                        获取有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=23                                        5160。                                                                           2024/1/20 21:33:50        10002        正在为程序包 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy 上的 MovePackag                                        eOperation 操作创建复原文件 C:\ProgramData\Microsoft\Windows\AppRepository\75a74                                        310-0265-4364-812a-93246e8c5fc9_S-1-5-21-2803740048-3683319017-457715079-1001_17                                        .rslc。                                                                          2024/1/20 21:33:50        607          已从队列中取消程序包 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy 的部署                                         MovePackageOperation 操作，并且正在为用户 S-1-5-21-2803740048-3683319017-4577150                                        79-1001 运行该部署。                                                             2024/1/20 21:33:50        216          应用部件清单(manifest)验证警告: 声明的命名空间 http://schemas.microsoft.com/deve                                        loper/appx/2015/build 不适用，在清单处理期间将忽略它。                           2024/1/20 21:33:50        9643         0x0: TerminateApplications 成功。                                                2024/1/20 21:33:50        9643         0x0: TerminateApplications 成功。                                                2024/1/20 21:33:50        10000        即将为程序包 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy 提供服务。将程                                         序包状态设置为 disabled 时返回 0x0。                                             2024/1/20 21:33:50        9643         0x0: TerminateApplications 成功。                                                2024/1/20 21:33:50        9643         0x0: TerminateApplications 成功。
2024/1/20 21:33:52        9548         60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy功能授权失败，错误代码为 0x80
                                       0701C5.
2024/1/20 21:33:52        306          错误 0x800701C5: 在处理请求时，由于以下错误，系统无法注册 windows.capability 扩
                                       展: 无法为此应用程序授权请求的功能。
                                       。
2024/1/20 21:33:52        316          错误 0x800701C5: 无法注册请求，因为在注册 windows.capability 扩展期间遇到以下错
                                       误: 无法为此应用程序授权请求的功能。
                                       。
2024/1/20 21:33:52        300          错误 0x80073CF6: 由于以下错误，无法注册 60568DGPStudio.SnapHutao_wbnnev551gwxy
                                       程序包: 无法注册包。
                                       。
2024/1/20 21:33:52        605          上次达到的成功状态为 MutablePackageDirectoryAdd。在达到下一状态 MachineRegisterA
                                       dd 之前发生故障。hr: 0x80073CF6
2024/1/20 21:33:52        10001        已完成为程序包 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy 提供服务。将
                                       程序包状态设置为 enabled 时返回 0x0。
2024/1/20 21:33:52        401          从  (AppxManifest.xml)  使用程序包 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev5
                                       51gwxy 中的目标卷 F: 执行的部署 MovePackageOperation 操作失败，错误为 0x80073CF6
                                       。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=2351
                                       60。
2024/1/20 21:33:52        698          从  (AppxManifest.xml)  使用程序包 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev5
                                       51gwxy 中的目标卷 F: 执行的部署 MovePackageOperation 操作失败，错误为 0x80073CF6
                                       。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=2351
                                       60。
2024/1/20 21:33:52        404          程序包 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy 的 AppX 部署操作失败
                                       ，错误为 0x80073CF6。此失败的具体错误文本是: 60568DGPStudio.SnapHutao_1.9.5.0_x6
                                       4__wbnnev551gwxy功能授权失败，错误代码为 0x800701C5.

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
只支持安装前已更改好默认的安装盘符，不支持安装后移动包体
