### ISSUE TITLE
[Bug]: 删除游戏内网页缓存错误信息

### ISSUE THREAD

**Issue by YuntongGuo** [DGP-Studio/Snap.Hutao#1324]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3930

### Snap Hutao 版本

1.9.5.0

### 问题分类

其它

### 发生了什么？

打开游戏时尝试删除游戏内网页缓存会显示： 清除失败，文件目录权限不足，请使用管理员模式重试。
即使用管理员模式也显示相同信息。

### 你期望发生的行为？

因打开游戏造成无法删除最好有单独的错误信息，否则会造成误导。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
打开游戏哪来的删除游戏内缓存？

**Comment by Lightczx** [comment]
> 打开游戏时

@YuntongGuo 不打开游戏能删么

**Comment by Lightczx** [comment]
closing for no response
