### ISSUE TITLE
[Bug]: 无法打开祈愿记录，且提示HttpRequestException 元数据校验文件下载失败以及653366069

### ISSUE THREAD

**Issue by Guozhaohe7** [DGP-Studio/Snap.Hutao#1325]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3007

### Snap Hutao 版本

1.9.5.0

### 设备 ID

237FA3BD09DCCCE83C4893A3D2546718

### 问题分类

祈愿记录

### 发生了什么？

每次启动hutao后弹出HttpRequestException 元数据校验文件下载失败以及多次弹出状态653366069
同时祈愿记录为灰白状态无法正确打开
已经使用文档的 PowerShell 命令解除计算机中所有容器化应用的 Loopback 限制仍未解决
可以正常游戏，网络也一切正常并未使用代理

### 你期望发生的行为？

无错误弹窗且能够打开祈愿记录

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
检查你能不能用浏览器打开米游社

**Comment by Guozhaohe7** [comment]
> 检查你能不能用浏览器打开米游社 @Guozhaohe7

可以

**Comment by qhy040404** [comment]
那我建议你手动检查一下你的代理设置

**Comment by Guozhaohe7** [comment]
这个样子应该没有问题吧？
![微信截图_20240124223112](https://github.com/DGP-Studio/Snap.Hutao/assets/73378487/e4245e5d-b0e8-4f2d-8962-1c350d557cde)


> 那我建议你手动检查一下你的代理设置

**Comment by qhy040404** [comment]
在国内还是国外

**Comment by Guozhaohe7** [comment]
> 在国内还是国外

国内

**Comment by qhy040404** [comment]
去设置里打开调试控制台，重启胡桃，弹出报错后把控制台截图发上来

**Comment by Guozhaohe7** [comment]
> 去设置里打开调试控制台，重启胡桃，弹出报错后把控制台截图发上来

![Uploading 微信截图_20240124233501.png…]()

**Comment by Guozhaohe7** [comment]
> 去设置里打开调试控制台，重启胡桃，弹出报错后把控制台截图发上来

![Uploading 微信截图_20240124233501.png…]()

**Comment by qhy040404** [comment]
你图没传上来 @Guozhaohe7

**Comment by Guozhaohe7** [comment]
> 你图没传上来 @Guozhaohe7

![Uploading 微信截图_20240124233501.png…]()

**Comment by qhy040404** [comment]
还是没传上来![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/985f27fe-6470-47a9-961c-9ff45f174eda)

**Comment by qhy040404** [comment]
你能不能等uploading完了再comment
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/12498d33-63fa-4742-86cc-cf57accfef12)

**Comment by Guozhaohe7** [comment]
![mmexport1706110875777](https://github.com/DGP-Studio/Snap.Hutao/assets/73378487/58a616c6-c237-487c-aa87-b193629a6cad)

**Comment by qhy040404** [comment]
你试试你能访问 https://homa.snapgenshin.com/ 吗

**Comment by Guozhaohe7** [comment]
> 你试试你能访问 https://homa.snapgenshin.com/ 吗
不能

**Comment by Guozhaohe7** [comment]
> 你试试你能访问 https://homa.snapgenshin.com/ 吗

不能

**Comment by qhy040404** [comment]
检查你的hosts是否ban掉了snapgenshin.com相关域名。如果没有的话，更换你的DNS。

**Comment by Guozhaohe7** [comment]
> 检查你的hosts是否ban掉了snapgenshin.com相关域名。如果没有的话，更换你的DNS。

hosts里没有snapgenshin.com所以问题居然是因为我把dns设置成了4.2.2.1？？不能吧？这不是微软的dns么。。你们这也上架了微软商店😰好吧明天改一下试试，之前不用微软这个dns都没法在微软商店更新😭

**Comment by qhy040404** [comment]
你可以试试`nslookup api.snapgenshin.com`和`nslookup homa.snapgenshin.com` 看看能不能正常返回解析ip

**Comment by Masterain98** [comment]
> hosts里没有snapgenshin.com所以问题居然是因为我把dns设置成了4.2.2.1？？不能吧？这不是微软的dns么。。你们这也上架了微软商店😰好吧明天改一下试试，之前不用微软这个dns都没法在微软商店更新😭

这不是微软的 DNS，请使用在中国地区有服务的 DNS 服务器
