### ISSUE TITLE
[Bug]: 胡桃云上传祈愿记录时会不定时闪退

### ISSUE THREAD

**Issue by Georgebillion** [DGP-Studio/Snap.Hutao#1328]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.2846

### Snap Hutao 版本

1.9.5

### 设备 ID

713B2DC293772C50780E258915CA3D71

### 问题分类

祈愿记录

### 发生了什么？

在上传祈愿记录到胡桃云时，胡桃本体会有概率闪退，且发生在打开胡桃程序一段时间后

### 你期望发生的行为？

修复该问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@Georgebillion 提供你的胡桃通行证邮箱与你上传时的UID

**Comment by Georgebillion** [comment]
> @Georgebillion 提供你的胡桃通行证邮箱与你上传时的UID

zhhyylove8@163.com UID:142967086

**Comment by Lightczx** [comment]
@Georgebillion 官网找公告群，加群找管理拉你进远程调试群

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao.Server/commit/9062307ecd6b98d05323bacc5a2def9b2e9fb57d
