### ISSUE TITLE
[Bug]: 刷新祈愿历史记录错误

### ISSUE THREAD

**Issue by KnightPeink** [DGP-Studio/Snap.Hutao#133]
### Windows 版本

19045.2130

### Snap Hutao 版本

1.1.13

### 发生了什么？

点击从缓存刷新提示：
![image](https://user-images.githubusercontent.com/73388556/197334925-0278c174-dd85-4233-8c15-e5e09579b14b.png)

### 你期望发生的行为？

可以修改hutao的原神内置浏览器缓存路径

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
已知问题，下版本修复
