### ISSUE TITLE
[Feat]: 在启动游戏功能中增加账号排序、新增账号的选项

### ISSUE THREAD

**Issue by retaker** [DGP-Studio/Snap.Hutao#1334]
### 背景与动机

1. 增加账号排序。 
   有时我可能会登录4-5个帐号，但是最经常使用的只有2个，我希望增加账号排序功能，让我常用的账号永远保持在列表上方。
2. 提供新增账号选项
   我发现有时我在已经保存的账号中点了退出账号，再从重新登录别的账号，一天之后，我的所有已经保存的账号都需要重新登录了。我希望有一个新增账号的选项，可以提供一个干净、独立的登录界面，登录成功后录入保存账号，就不会影响其他账号的登录状态了。

### 想要实现或优化的功能

如上所述。

**Comment by Masterain98** [comment]
#1233

**Comment by retaker** [comment]
> #1233

这个是功能1，关于功能2或者说我之前保存的账号经常需要重新登录的问题我是否需要重开issue？

**Comment by qhy040404** [comment]
> #1233 

不是一个东西

**Comment by qhy040404** [comment]
> 2. 提供新增账号选项

原神本身的登录页面本来就相当于全新的登录了，你所有登录状态掉了应该是因为你更换了网络环境。原神的登录状态与记录的网络环境是关联的

**Comment by qhy040404** [comment]
> 希望有一个新增账号的选项，可以提供一个干净、独立的登录界面

看来你是想要米哈游把我们几个送进去

**Comment by Lightczx** [comment]
@qhy040404 他的意思应该是清空注册表之类的操作

@retaker 实际上你在掉登录之后直接删除对应的账号即可，重新登录后重新检测就能正常使用

**Comment by qhy040404** [comment]
> 功能2或者说我之前保存的账号经常需要重新登录的问题我是否需要重开issue？

https://hut.ao/zh/advanced/FAQ.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B8%B8%E6%88%8F%E7%99%BB%E5%BD%95%E7%8A%B6%E6%80%81%E4%BC%9A%E5%A4%B1%E6%95%88-%E5%AF%BC%E8%87%B4%E5%88%87%E6%8D%A2%E8%B4%A6%E5%8F%B7%E5%8A%9F%E8%83%BD%E6%97%A0%E6%95%88

**Comment by retaker** [comment]
> @qhy040404 他的意思应该是清空注册表之类的操作
> 
> @retaker 实际上你在掉登录之后直接删除对应的账号即可，重新登录后重新检测就能正常使用

好的，我也是一直这么操作的。只是我不是很明白他为什么经常掉登录，我的网络环境也没有变过，这几次是每次添加一个临时的别人的账号之后都会掉所有的登录。
