### ISSUE TITLE
星穹铁道相关的功能更新

### ISSUE THREAD

**Issue by tiantianyigntao5** [DGP-Studio/Snap.Hutao#1336]
### 背景与动机

希望提供有关星穹铁道的工具和功能

### 想要实现或优化的功能

1.角色资料（角色材料、行迹、基础数值、命途、属性、适用光锥等）
2.光锥资料（光锥适用命途、光锥背景故事、光锥效果、光锥基础数值、适用等）
3.遗器资料（遗器背景故事、遗器套装效果、适用角色数据统计等）
4.启动星穹铁道（类比原神的启动游戏设置）
5.模拟宇宙祝福、奇物、事件资料
6.混沌回忆战绩统计及数据库
7.虚构叙事战绩统计及数据库
8.敌人资料（怪物名称，弱点，属性抗性等）

**Comment by Lightczx** [comment]
#701
