### ISSUE TITLE
[Feat]: 服务器间切换账号时可以同时切换服务器

### ISSUE THREAD

**Issue by HaloStudent233** [DGP-Studio/Snap.Hutao#1340]
### 背景与动机

因为有国服账号和国际服账号，所以希望在切换账号的同时切换服务器

### 想要实现或优化的功能

同标题，在切换至另一个服务器上的账号时可以同时切换服务器，就不用再到设置里切换服务器了

**Comment by qhy040404** [comment]
切换服务器后对应保存的帐号列表是会变化的国服不会保存国际服账号的

**Comment by HaloStudent233** [comment]
> 切换服务器后对应保存的帐号列表是会变化的，国服不会保存国际服账号的

但是可以在首页启动的账号列表里显示所有服务器保存的账号供选择，再根据选择的账号所对应的服务器启动

**Comment by qhy040404** [comment]
不做

**Comment by Lightczx** [comment]
PR Welcome
