### ISSUE TITLE
[Feat]: 复刻倒计时

### ISSUE THREAD

**Issue by qhy040404** [DGP-Studio/Snap.Hutao#1341]
### 背景与动机

想买甘雨皮，想看上次复刻

### 想要实现或优化的功能

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/d01313d9-04da-462c-8d70-44e0ea9c2c01)

**Comment by Lightczx** [comment]
@Masterain98 action配置一下

**Comment by Lightczx** [comment]
Tracked by #1394
