### ISSUE TITLE
[Bug]: 工具-> 我的角色同步问题

### ISSUE THREAD

**Issue by Jackthepotatoes** [DGP-Studio/Snap.Hutao#1343]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows insider Preview 26020.1000

### Snap Hutao 版本

1.9.5

### 设备 ID

A5062F48ECC1F066E2D393ABFCF598AB

### 问题分类

角色信息面板

### 发生了什么？

通过游戏内角色橱窗同步角色信息显示游戏维护中
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/95580038/11282468-e074-4a8b-9550-245ae2ee5ae6)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
enka api维护中，与胡桃无关

**Comment by Masterain98** [comment]
Check status at http://status.enka.network/

**Comment by Masterain98** [comment]
@Lightczx 建议修改提示为“Enka API 维护中”

**Comment by Lightczx** [comment]
> @Lightczx 建议修改提示为“Enka API 维护中”

API返回如此，Enka自身维护有另外的提示
