### ISSUE TITLE
[Bug]: 祈願紀錄錯誤

### ISSUE THREAD

**Issue by Starywa** [DGP-Studio/Snap.Hutao#1344]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3085

### Snap Hutao 版本

1.9.5

### 设备 ID

8E6CFB906B18C38DCBAA42BE4D06D5DF

### 问题分类

祈愿记录

### 发生了什么？

![螢幕擷取畫面 2024-01-31 133834](https://github.com/DGP-Studio/Snap.Hutao/assets/86212695/feee1d02-b477-456b-8fe3-46fce403c61b)
![螢幕擷取畫面 2024-01-31 135830](https://github.com/DGP-Studio/Snap.Hutao/assets/86212695/4050b8b4-b031-4c88-a589-aa1788af0c7e)
![螢幕擷取畫面 2024-01-31 133937](https://github.com/DGP-Studio/Snap.Hutao/assets/86212695/332d29c5-e978-4b98-8948-c7fa1ac33aa6)

統計紀錄是錯誤的，總覽、歷史、角色、武器都沒有錯誤。

### 最后一步

- [ ] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
统计是胡桃云上上传数据的统计，与你的本地记录无关
