### ISSUE TITLE
一键刷新所有账号的祈愿记录

### ISSUE THREAD

**Issue by 144-144** [DGP-Studio/Snap.Hutao#1346]
### 背景与动机

# 背景：
拥有多个原神账号，且都在胡桃统计祈愿记录。  
刷新祈愿记录时，首先要在侧栏选中要刷新的账号，这个步骤需要移动3次鼠标、精准点击2次。  
# 动机
若能一键刷新所有账号的祈愿记录，无视侧栏选择的米游社账号，可以节省上述操作，大幅降低手腕压力。

### 想要实现或优化的功能

在“祈愿记录”页面设置“刷新所有账号”按钮，单击一次即可刷新所有米游社账号的祈愿记录，无视侧栏选择的米游社账号。

**Comment by Lightczx** [comment]
> 可以节省上述操作，大幅降低手腕压力

我觉得没什么必要，但是 PR Welcome
