### ISSUE TITLE
[Bug]: 获取战绩数据返回【5003】错误，且无法打开验证界面

### ISSUE THREAD

**Issue by HongyuS** [DGP-Studio/Snap.Hutao#1350]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23620.1000

### Snap Hutao 版本

1.9.5.0

### 设备 ID

8ADB9CD73911E258EB44828FE721AAFC

### 问题分类

玩家查询

### 发生了什么？

尝试通过 Hutao 获取战绩数据失败
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/44023928/1662a28d-d54d-4204-93b6-109d043eeff5)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/44023928/9297e0ab-3f39-4f0c-b6f5-c38357be79ce)

### 你期望发生的行为？

旅行工具中正常情况下应该弹出验证界面，验证后功能可正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
@HongyuS 手机米游社可以正常查看吗

**Comment by BTMuli** [comment]
> Hutao或其他第三方访问直接5003，米游社正常

@HongyuS 我的也一样吗🤔

**Comment by HongyuS** [comment]
> > Hutao或其他第三方访问直接5003，米游社正常
> 
> @HongyuS 我的也一样吗🤔

一样的，没能幸免

**Comment by mengluo04** [comment]
我也是，这半个月接口突然又5003了

**Comment by zztmercury** [comment]
触发风控后，在非常用设备上用米游社也无法查看数据，不会出人机验证

**Comment by Lightczx** [comment]
避免使用Q群机器人，尽可能少的使用第三方软件可以很大程度上降低5003出现的几率

**Comment by mengluo04** [comment]
> 避免使用Q群机器人，尽可能少的使用第三方软件可以很大程度上降低5003出现的几率

没用机器人，自己写的服务然后调接口的，札记接口没问题

**Comment by BTMuli** [comment]
> 札记接口没问题

5003只会出现在部分接口上

**Comment by Lightczx** [comment]
> > 避免使用Q群机器人，尽可能少的使用第三方软件可以很大程度上降低5003出现的几率
> 
> 没用机器人，自己写的服务然后调接口的，札记接口没问题

和机器人一个道理

**Comment by qhy040404** [comment]
> > 避免使用Q群机器人，尽可能少的使用第三方软件可以很大程度上降低5003出现的几率
> 
> 
> 
> 没用机器人，自己写的服务然后调接口的，札记接口没问题

处理fingerprint了吗，没处理那5003正常

**Comment by mengluo04** [comment]
> > > 避免使用Q群机器人，尽可能少的使用第三方软件可以很大程度上降低5003出现的几率
> > 
> > 
> > 没用机器人，自己写的服务然后调接口的，札记接口没问题
> 
> 处理fingerprint了吗，没处理那5003正常

只加了device_id和device_fp，之前正常，后面出现一段时间5003，用胡桃能验证，然后不报5003，报1034可以正常过码。最近又5003了，胡桃上面都是5003
