### ISSUE TITLE
[Feat]: 在祈愿记录的【角色】和【武器】中增加设置以允许显示从未抽到过的物品

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1355]
### 背景与动机

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/a9c018c5-4f3f-4ad3-99b7-4513bec8b1de)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/7216a646-a10d-4ba2-a9e2-f208e1e78b4a)

我要看还有什么角色/武器的图鉴没解锁的

### 想要实现或优化的功能

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/f99e84fd-d4d4-4b4e-8f4d-20eeac22f6c4)

类似该项设置，在胡桃设置中增加选项以显示未抽到的物品

**Comment by Lightczx** [comment]
Tracked by #1394
