### ISSUE TITLE
[Bug]: Windows HDR开关无法长期生效（仅第一次打开时生效）

### ISSUE THREAD

**Issue by qakcn** [DGP-Studio/Snap.Hutao#1357]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3007

### Snap Hutao 版本

1.9.5.0

### 设备 ID

A2025760328284AF45975203C39E0691

### 问题分类

游戏启动器

### 发生了什么？

Windows HDR开关，打开后，会添加相关注册表键值并设置为1。运行过一次游戏后，注册表相关键值会被设置为0。

此时胡桃工具箱里开关还是显示打开。

并且，重新开关选项时，注册表相关键值也不会变动。

### 你期望发生的行为？

希望：

* 在相关键值被游戏重置时，能检测并显示当前状态。
* **或**：在打开胡桃工具箱时，能根据当前开关重新设置注册表键值。
* **或**：至少在重新开关选项时，能重新设置注册表键值。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
注册表写入会在启动游戏时执行，请在通过胡桃启动游戏后再检查注册表。

**Comment by qhy040404** [comment]
此开关与注册表内当前键值无关，开关打开后，胡桃会在每一次启动游戏时设置键值

**Comment by qakcn** [comment]
> 此开关与注册表内当前键值无关，开关打开后，胡桃会在每一次启动游戏时设置键值

我是使用其他启动器（即胡桃工具箱用于时长统计的Starward），该启动器暂未提供HDR相关设置，所以我希望用胡桃工具箱来开启相关设置，但是继续使用其他启动器启动。

**Comment by qhy040404** [comment]
对不起不不可以

**Comment by Lightczx** [comment]
> 我是使用其他启动器（即胡桃工具箱用于时长统计的Starward），该启动器暂未提供HDR相关设置，所以我希望用胡桃工具箱来开启相关设置，但是继续使用其他启动器启动。

@Scighost 你的用户来我这拉...
