### ISSUE TITLE
[Bug]: 窗口无法拖动

### ISSUE THREAD

**Issue by SIyiyouzi** [DGP-Studio/Snap.Hutao#136]
### Windows 版本

21H1（内部版本19043.928）

### Snap Hutao 版本

1.1.13

### 发生了什么？

窗口可以调节大小，但是无法拖动

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
#124
