### ISSUE TITLE
[Bug]: Win10 启动后闪退

### ISSUE THREAD

**Issue by super-yamato** [DGP-Studio/Snap.Hutao#1361]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3930

### Snap Hutao 版本

1.9.5

### 设备 ID

91B5924AF27D73CD869569C6DB4EEB2A

### 问题分类

安装和环境

### 发生了什么？

卸载后重新安装能够正常配置，配置完成后显示主界面容器框后自动关闭，后续打开亦是如此。
事件查看器能够找到的与hutao有关的日志如下
日志1（来源：Windows Error Reporting，时间id:1001）
> 故障存储段 2229077057287623111，类型 5
> 事件名称: MoAppCrash
> 响应: 不可用
> Cab ID: 0
> 
> 问题签名:
> P1: 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy
> P2: praid:App
> P3: 1.0.0.0
> P4: 65680000
> P5: combase.dll
> P6: 10.0.19041.3636
> P7: 613e7d3d
> P8: 80000013
> P9: 000000000001ccfa
> P10: 
日志2（来源：Application Error，事件id：1000）
> 错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x65680000
> 错误模块名称: KERNELBASE.dll，版本: 10.0.19041.3930，时间戳: 0x9141f979
> 异常代码: 0xc000027b
> 错误偏移量: 0x000000000012db22
> 错误进程 ID: 0xc288
> 错误应用程序启动时间: 0x01da55d25b761b63
> 错误应用程序路径: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy\Snap.Hutao.exe
> 错误模块路径: C:\Windows\System32\KERNELBASE.dll
> 报告 ID: bbf8e80f-b438-4f7e-b8e6-8fcb51ba23d0
> 错误程序包全名: 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy
> 错误程序包相对应用程序 ID: App
日志3（来源：Application Hang，事件id：1002）
> 程序 Snap.Hutao.exe 版本 1.0.0.0 已停止与 Windows 交互并关闭。若要查看是否有关于该问题的详细信息，请检查“安全性与维护”控制面板中的问题历史记录。
>  进程 ID: 8310
>  开始时间: 01da513264ba5acb
>  终止时间: 4294967295
>  应用程序路径: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy\Snap.Hutao.exe
>  报告 ID: 31c7e3e3-367f-4b67-acbd-48c7760731b7
>  错误程序包全名: 60568DGPStudio.SnapHutao_1.9.5.0_x64__wbnnev551gwxy
>  错误程序包相关应用程序 ID: App
>  挂起类型: Quiesce

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
运行[诊断工具](https://github.com/DGP-Automation/ISSUE_TEMPLATES/releases/download/diagnosis_tools/Snap.Hutao.DiagTools.exe)后上传log文件

**Comment by Lightczx** [comment]
> 19045.3930

更新到4xxx
