### ISSUE TITLE
[Feat]: 希望实时便签自动刷新不用非管理员模式下更改

### ISSUE THREAD

**Issue by Llishushu** [DGP-Studio/Snap.Hutao#1362]
### 背景与动机

每次启动默认都是管理员模式，试过很多方法都不行，没有办法修改定时刷新

### 想要实现或优化的功能

希望自动刷新可以在管理员模式下修改或其他解决方法

**Comment by qhy040404** [comment]
默认管理员模式启动是你的系统问题。管理员模式下修改此设置会引起权限问题。
