### ISSUE TITLE
[Bug]: 首页公告下滑至底部导致崩溃

### ISSUE THREAD

**Issue by HaloStudent233** [DGP-Studio/Snap.Hutao#1365]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3007

### Snap Hutao 版本

1.9.5.0

### 问题分类

公告

### 发生了什么？

在首页公告处下滑至底部，会导致白屏，继续下滑进入未响应状态

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HaloStudent233** [comment]
https://github.com/DGP-Studio/Snap.Hutao/assets/60351161/ea2e52ab-8729-4ea3-a53f-b8166a04c6ed

**Comment by Masterain98** [comment]
提供设备ID并检查系统日志.NET错误

**Comment by HaloStudent233** [comment]
> 提供设备ID并检查系统日志.NET错误

92422675ACD728C978408671428B4019
用了诊断工具但是什么都没有

**Comment by qhy040404** [comment]
fixed by f06825f246f1ee6510f8fac2c9617655c1449eef
