### ISSUE TITLE
[Bug]: 上传深渊记录时，出现653366069错误

### ISSUE THREAD

**Issue by ShyOvO** [DGP-Studio/Snap.Hutao#1367]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3996

### Snap Hutao 版本

1.9.5.0

### 问题分类

胡桃云

### 发生了什么？

上传深渊记录时出现如下错误，请见截图。已尝试关闭代理工具并重启电脑，问题依旧。尝试寻找官方文档中的“[解除了 Windows 容器 Loopback 限制]”但我无法找到此超链接对应的解决方法。重新登陆胡桃云账号后再次上传记录问题依旧。
这个问题是上周突然出现的，此前相同系统版本上传记录是没有问题的。我12月使用Windows11时亦没有此问题。
![screenshot](https://github.com/DGP-Studio/Snap.Hutao/assets/156396425/6b1e5c47-f538-4067-a360-a384e644f802)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
Duplicate of #1351

**Comment by Masterain98** [comment]
点击“检查清单”中第三条中，唯一的那一个链接
