### ISSUE TITLE
[Feat]: 关于高级启动添加HDR选项

### ISSUE THREAD

**Issue by BestGreed** [DGP-Studio/Snap.Hutao#1369]
### 背景与动机

原神4.0后Win版包内已经有了被隐藏的HDR选项，如果工具箱能同步加上这个功能就好了

### 想要实现或优化的功能

高级启动器添加启用HDR选项，应该做一个检查注册表状态的功能或者每次都覆写项就可以实现吧

**Comment by BestGreed** [comment]
> 你是什么版本的客户端？

官服，好像我更新工具箱后有这个功能了

**Comment by BestGreed** [comment]
> 你是什么版本的客户端？

但是这样解锁高刷的选项又没有了，HDR和高刷不应该冲突吧

**Comment by qhy040404** [comment]
你胡桃什么版本

**Comment by BestGreed** [comment]
> 你胡桃什么版本

1.9.5.0 msix

**Comment by qhy040404** [comment]
Duplicate of #1055
