### ISSUE TITLE
胡桃祈愿记录

### ISSUE THREAD

**Issue by Ncnci1** [DGP-Studio/Snap.Hutao#137]
### Windows 版本

25227.1010

### Snap Hutao 版本

1.1.4

### 发生了什么？

胡桃祈愿记录找不到原神内置浏览器缓存路径

### 你期望发生的行为？

作者大大看一一下

### 相关的崩溃日志 位于 `%HOMEPATH%/Documents/Hutao/Log.db`

```shell
..
```

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Masterain98** [comment]
参考文档使用 Stoken刷新[https://hut.ao/features/wish-export.html](https://hut.ao/features/wish-export.html)
