### ISSUE TITLE
[Bug]: 1.9.5.0 到 1.9.6.0 无法通过客户端更新

### ISSUE THREAD

**Issue by Anyayay** [DGP-Studio/Snap.Hutao#1372]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23620.1000

### Snap Hutao 版本

1.9.5.0

### 设备 ID

CC150C1981C5E256B27E53C66E7D57F9

### 问题分类

安装和环境

### 发生了什么？

1.9.5.0 到 1.9.6.0 无法通过客户端更新

客户端检测得到更新并提示是否立即安装时，选择安装并对UAC允许后，程序没有任何反应，重启程序后仍未更新

### 你期望发生的行为？

应进行更新

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
请手动下载deployment并使用deployment进行更新，如deployment报错，请将截图发送至此issue

**Comment by Anyayay** [comment]
我已通过deployment正常更新，只是最好确认在应用内更新的功能是否出现问题

**Comment by Lightczx** [comment]
目前未收到类似反馈，排除程序问题

**Comment by isolitude** [comment]
同样的问题，在程序内点击安装，允许UAC后没有任何反应，但在user/文档/Hutao/UpdateCache 文件夹下已经下载了新版本的 .msix文件，打开即可正常更新。
可能和OneDrive同步有关？Hutao启动的时候OneDrive同步会卡住。
