### ISSUE TITLE
希望将胡桃之前版本的纯白背景作为可选项添加回来

### ISSUE THREAD

**Issue by hg429108** [DGP-Studio/Snap.Hutao#1373]
### 背景与动机

胡桃1.9.0~1.9.5用户，2/7更新至1.9.6后，尝试在设置中还原之前版本的纯白背景，无果

### 想要实现或优化的功能

希望将之前的「纯白背景」在【设置—外观】中以一个可选项存在；或以图片资源存放在【Hutao\Background】目录下

**Comment by Masterain98** [comment]
> 尝试在设置中还原之前版本的纯白背景，无果

因为没有这个选项，这个是下一版本需要实现的。你现在能做的就是放一张白色图片仍在背景目录中。


> 或以图片资源存放在【Hutao\Background】目录下

程序做不到，但你可以自己手动去放一个

**Comment by Lightczx** [comment]
Tracked by #1394
