### ISSUE TITLE
[Bug]: 胡桃1.96:此应用包不支持通过应用安装程序安装，因为它使用了某些受限制的功能。

### ISSUE THREAD

**Issue by XA2005** [DGP-Studio/Snap.Hutao#1376]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

windows11专业版22631.3007

### Snap Hutao 版本

1.96

### 设备 ID

070DB3CB81E7C6BF9768F870BF39E9CD

### 问题分类

安装和环境

### 发生了什么？

<img width="490" alt="屏幕截图 2024-02-08 123618" src="https://github.com/DGP-Studio/Snap.Hutao/assets/137900703/45e67c9d-7628-475b-9953-9e3740e024ba">
<img width="960" alt="屏幕截图 2024-02-08 022519" src="https://github.com/DGP-Studio/Snap.Hutao/assets/137900703/946d8e5f-c126-411e-bc44-f99ba42697ec">
<img width="960" alt="屏幕截图 2024-02-08 022448" src="https://github.com/DGP-Studio/Snap.Hutao/assets/137900703/770512e0-c185-42dc-97c8-c592a5961b5d">

### 你期望发生的行为？

我不认为上述的描述已经足以详细，但是我也没有发现如何有关的日志文件。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
使用 Snap.Hutao.Deployment

**Comment by qhy040404** [comment]
- [x] 我**未**阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
