### ISSUE TITLE
好像现在版本修改注册表开启原生HDR已经失效了

### ISSUE THREAD

**Issue by boom6904** [DGP-Studio/Snap.Hutao#1377]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3007

### Snap Hutao 版本

1.9.6.0

### 设备 ID

38F84A7FF79DEA355765AE41FF08A527

### 问题分类

其它

### 发生了什么？

好像现在版本修改注册表开启原生HDR已经失效了，在windows注册表里原神项下已经没有"WINDOWS_HDR_ON"值了，自己添加的也没有效果

### 你期望发生的行为？

只是发现了，网上找很久发现没人在说，想告诉一下

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
留着防止有人说好端端的功能为什么移除
（上次移除多开就有人叫）
