### ISSUE TITLE
祈愿记录增加可修改的历史记录

### ISSUE THREAD

**Issue by 2022429454** [DGP-Studio/Snap.Hutao#1381]
### 背景与动机

原来是使用小程序记录抽卡记录，现在转为使用胡桃工具箱，通过自动刷新产生的记录不包含半年前的抽卡记录，由于小程序中的记录无法导出，想要增加可供修改的历史记录。
![1](https://github.com/DGP-Studio/Snap.Hutao/assets/159567842/a3c6bd0e-a246-43f6-bc2d-5458bf178b9b)
![2](https://github.com/DGP-Studio/Snap.Hutao/assets/159567842/82056a26-12e1-4f86-b319-95c2b126af7d)

### 想要实现或优化的功能

在手动刷新的祈愿记录后加入空白记录，可以自行更改抽取的角色和抽取次数。

**Comment by Masterain98** [comment]
不会支持该功能。微信小程序使用UIGF格式导出。

**Comment by qhy040404** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/c0c7137c-001f-4438-bbab-3ef14c6673d0)
