### ISSUE TITLE
[Bug]: 无法以非管理员模式打开程序

### ISSUE THREAD

**Issue by cubershark** [DGP-Studio/Snap.Hutao#1382]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.9.6.0

### 设备 ID

5E566D8B92E8FD4270AA0991A3443381

### 问题分类

实时便笺

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/108975185/d026f9c0-0403-4e4f-9b68-a34da41e79a2)
无法以非管理员的模式进入程序，因此无法修改自动刷新的选项

### 你期望发生的行为？

可以以一般模式进入程序，且可以启动自动刷新的功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
> 无法以非管理员的模式进入程序

如果你确定使用的是普通方式启动的应用，而不是含有管理员模式启动方式的快捷方式，则意味着你的Windows操作系统账户出现了权限问题（该问题常见于精简版系统和一键安装系统脚本）。如果是这一原因则从软件侧无法处理该问题，重新安装原版系统。
