### ISSUE TITLE
读取cookie时报错

### ISSUE THREAD

**Issue by vziwmdu** [DGP-Studio/Snap.Hutao#1383]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26052.1100

### Snap Hutao 版本

1.9.6.0

### 设备 ID

4816E17FBE905499E6088C8119F6BD0B

### 问题分类

安装和环境

### 发生了什么？

使用“网页登陆”登录HoyoLab时，点击“我已登录”后提示“无效的cookie”。账号以及密码均正确，并且我此前已经成功登录米游社。使用CheckNetIsolation.exe解除网络限制后，该问题依然存在。

### 你期望发生的行为？

希望可以得知造成此现象的原因并得到解决方法。除此之外，工具箱的通知信息位于画面底部，不够明显，并且报错通知存在的时间太短，不方便查看。希望可以添加一个“收件箱”的功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/8fb7ab65-e1c0-4085-8439-ebb1bd200c66)

疑似有问题。我这里能成功添加，但添加成功的时候不会弹出成功提示。

**Comment by qhy040404** [comment]
请先登录hoyolab进行社区账号初始化

**Comment by Lightczx** [comment]
> 使用“网页登陆”登录HoyoLab时，点击“我已登录”后提示“无效的cookie”。账号以及密码均正确，并且我此前已经成功登录米游社。

你想登录米游社还是 HoYoLAB

> 除此之外，工具箱的通知信息位于画面底部，不够明显，并且报错通知存在的时间太短，不方便查看。希望可以添加一个“收件箱”的功能

夹杂在 Bug 反馈中的功能请求不会受理，确有需求请你额外单开 Issue

**Comment by vziwmdu** [comment]
我在国服与国际服都有账号，所以我的期望是可以同时登陆米游社与HoYoLAB。我提到米游社是想强调一下只有在登陆HoYoLAB时遇到了问题，或许使你产生了一些误解。
________________________________
发件人: DismissedLight ***@***.***>
发送时间: 2024年2月10日 18:17
收件人: DGP-Studio/Snap.Hutao ***@***.***>
抄送: vziwmdu ***@***.***>; Author ***@***.***>
主题: Re: [DGP-Studio/Snap.Hutao] 读取cookie时报错 (Issue #1383)


使用“网页登陆”登录HoyoLab时，点击“我已登录”后提示“无效的cookie”。账号以及密码均正确，并且我此前已经成功登录米游社。

你想登录米游社还是 HoYoLAB

除此之外，工具箱的通知信息位于画面底部，不够明显，并且报错通知存在的时间太短，不方便查看。希望可以添加一个“收件箱”的功能

夹杂在 Bug 反馈中的功能请求不会受理，确有需求请你额外单开 Issue

―

**Comment by qhy040404** [comment]
> 并且我此前已经成功登录米游社。

你是否登陆过HoyoLAB并完成社区初始化

**Comment by vziwmdu** [comment]
初始化？是指诸如绑定用户名、绑定手机号一类的操作吗？

________________________________

**Comment by qhy040404** [comment]
上hoyolab弄社区昵称什么的

**Comment by vziwmdu** [comment]
如果初始化是指绑定用户名、绑定手机号一类的操作，那我确实没有初始化账号，我只是用邮箱注册了一个账号。

________________________________

**Comment by vziwmdu** [comment]
没有

________________________________

**Comment by vziwmdu** [comment]
是指在这个界面设置头像和昵称吗？

________________________________
