### ISSUE TITLE
转换客户端时保持画面设置不变

### ISSUE THREAD

**Issue by abandonstudy** [DGP-Studio/Snap.Hutao#1384]
### 背景与动机

在国服更改画面设置后，首次转换至国际服，画面设置会重置回默认，需手动更改为和国服一致。
目前国际服和国服的画面设置似乎是分开存储的，希望各个客户端共用一份画面设置

### 想要实现或优化的功能

同上

**Comment by qhy040404** [comment]
国服和国际服保存的画面设置在注册表里是两个不同的字段。

**Comment by Lightczx** [comment]
> 希望各个客户端共用一份画面设置

不可能
