### ISSUE TITLE
[Bug]: 账号疑似会被他人代替？

### ISSUE THREAD

**Issue by TigerShota** [DGP-Studio/Snap.Hutao#1385]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3007

### Snap Hutao 版本

1.9.6.0

### 问题分类

游戏启动器

### 发生了什么？

似乎一台电脑保存了A账号后，另一台电脑也保存A账号，此时前一台电脑的A账号会失去登录态。前几个版本不会出现此类情况。+-

### 你期望发生的行为？

可以两台电脑同时保存A账号。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
问原神去
