### ISSUE TITLE
希望切换账号的功能能支持B服

### ISSUE THREAD

**Issue by hg429108** [DGP-Studio/Snap.Hutao#1386]
### 背景与动机

虽然通过米游社扫码登录，胡桃添加了两个B服账号，且在启动游戏前切至另一账号，但登录游戏时仍为原先的B服账号，无法切至另一个B服账号

### 想要实现或优化的功能

希望在胡桃内切换至另一B服账号后，随后（通过胡桃）登录游戏时也能切至对应账号

**Comment by hg429108** [comment]
<img width="417" alt="屏幕截图 2024-02-10 001419" src="https://github.com/DGP-Studio/Snap.Hutao/assets/102448974/f4bd4cca-3d22-46c2-9de3-e39cfed9508e">

**Comment by Lightczx** [comment]
PR Welcome
