### ISSUE TITLE
[Bug]: 成就管理界面无法正常启动

### ISSUE THREAD

**Issue by Guest-Liang** [DGP-Studio/Snap.Hutao#1387]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3085

### Snap Hutao 版本

1.9.6.0

### 设备 ID

908AE36E00746998FB6C0FB50CE989AC

### 问题分类

成就管理

### 发生了什么？

# 非管理员启动
在非管理员身份下启动胡桃，放大应用程序到全屏（或者不放大，保持窗口化不变），然后点击成就管理，程序能加载初始界面，但是后续无法启动，在成就管理界面卡死，随后程序崩溃退出：   
## 非管理员+放大窗口到全屏   
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/cb287fd7-ae00-4d65-9180-ce7a66e95c78)   
## 非管理员+保持窗口化   
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/ae1dbf9a-bca8-41e9-950b-759879aff582)
## 事件查看器截图   
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/243701a4-407c-4a05-b1c9-6cf22e062ece)   
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/eaa72743-a496-485e-ae62-00dd6cc4b59a)

   
# 管理员启动
随后尝试使用管理员身份启动胡桃，包括工具内点击“以管理员身份重启”和胡桃创建的管理员身份快捷方式启动，问题变为放大窗口到全屏再点击后能复现，但保持窗口化则启动成功      
## 管理员身份+放大窗口到全屏
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/89307cf5-cb2f-41c9-a9c3-dbb558b0e119)
## 管理员身份+保持窗口化
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/15bd2d31-2f7a-4243-8e72-853450de3af9)
### 你期望发生的行为？

无论窗口化与否都应当正确渲染成就管理界面

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Guest-Liang** [comment]
即使以管理员身份+窗口化能成功启动，但切换至别的标签后再点击回到”成就管理“，胡桃也会崩溃退出

https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/e4433f3c-baf1-4ba7-999a-e888eebf07db

**Comment by Guest-Liang** [comment]
> 你系统设置中屏幕分辨率和文本大小设置的值是什么？

2560x1440，175%缩放

**Comment by Lightczx** [comment]
调整你的文本大小直到不会崩溃即可，没有其他的解决方案
