### ISSUE TITLE
[Feat]: 更多的背景图选项

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1389]
### 背景与动机

- [ ] #1373
- [ ] 实装每日图片（在每次启动客户端时请求一次数据就行了）

### 想要实现或优化的功能

程序设置中应提供选项，选择壁纸
- [ ] 无背景 （白色）
- [x] 本地图片目录
- [x] 原神官方启动器图
- [ ] [bing 每日图片](https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1) -> `https://api.snapgenshin.com/wallpaper/bing`
- [ ] [胡桃每日图片](http://api.snapgenshin.com/wallpaper/today) ~~（尚未上线）~~ 已上线

**Comment by qhy040404** [comment]
还有启动器图

**Comment by Lightczx** [comment]
Tracked by #1394
