### ISSUE TITLE
[Feat]: 添加新 feature 的时候，必要时提供对应的功能开关。

### ISSUE THREAD

**Issue by ChrisKimZHT** [DGP-Studio/Snap.Hutao#1390]
### 背景与动机

首先感谢 Snap Hutao 开发团队的无私奉献，我了解开源软件由志愿者自发维护，但我仍然想对开发团队提出一点自己的拙见。

我认为开发组在加入新 feat 的时候，需要考虑一下该 feat 是否为**每个用户**都需要的。如果不是，则应当设计开关，否则就跟国内 APP 一样会加入很多无用的**臃肿**功能。或者在开发新 feat 前，进行一定程度的用户调研，确定用户需求。

在我印象中，让我觉得莫名其妙的 feat 有以下：

- 自动连点：[1.7.6](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.7.6) 引入，占用右上角区域，不太雅观，好在到 [1.7.17](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.7.17) 提供了开关。
- 背景图片：[1.9.6](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.9.6) 引入，摧毁了本来非常优雅的亚克力效果，还没有加入开关。

### 想要实现或优化的功能

在加入一些并不是每个用户需要的 feature 时，同时设计对应的开关。

**Comment by Masterain98** [comment]
#1389

**Comment by Masterain98** [comment]
> 进行一定程度的用户调研，确定用户需求

任何人都可以在 GitHub Issues 页面上对开启状态的 issue 发起评论。如果没人反对，且开发者觉得可以，那就可以做。目前没有更多的人手去做调研这种商业化的工作。

**Comment by ChrisKimZHT** [comment]
> 任何人都可以在 GitHub Issues 页面上对开启状态的 issue 发起评论。如果没人反对，且开发者觉得可以，那就可以做。目前没有更多的人手去做调研这种商业化的工作。

那就希望开发组在必要情况下，对新功能提供开关。发了新功能然后用户又来提 issue 请求开关，反而感觉效率更低。

**Comment by Masterain98** [comment]
自动连点是希尔自己要做的（他需要的功能），对我而言也就是个 good to have 级别的 feature，但我同意最初的设计挺难看的。能变成现在这样还得是有其他开发者参与才有变化的。不要问我为什么不改，我不写C#，只能催希尔改。

为什么亚克力效果没了，因为引入了背景图功能（这是SG的传统功能，所以我是支持的），我是认为挺好看的。但是如果是纯色背景，在新的设计下就会变得更难看，所以在上线前几个小时内，又加了官方启动器图片的显示作为默认效果。背景图片功能在设计时，计划做后端的每日图片推送（类似于Bing每日图片），帮助懒得放图的用户号。如果你问为什么没做完就推了更新，答案是有急需休夫的bug需要通过新版客户端更新来解决。

性能问题我觉得不用担心，希尔是一个有性能洁癖的人，如果没人帮他，客户端只会更丑 XD

1.9.6版本包体积变大仅仅是因为内置了Windows App SDK。

**Comment by Lightczx** [comment]
就俩人开发的客户端要求别太多

**Comment by Lightczx** [comment]
不是不想加开关
纯粹就是人手不足，又面临必须发版修复深渊上传错误的节点，功能开发了一半处于GA状态，不得不发布
如果人手充足你的建议就不会存在问题了

对于你提到的效率问题
确实效率很低，但是我们缺人。

总结：用户逆天需求多，开发人员却相反的少
