### ISSUE TITLE
管理员身份运行胡桃，未勾选更改启动参数启用游戏后，游戏分辨率被修改

### ISSUE THREAD

**Issue by abandonstudy** [DGP-Studio/Snap.Hutao#1393]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3930

### Snap Hutao 版本

1.9.6.0

### 设备 ID

1BFD1497A6C48BFAF1FD9C51045D50F3

### 问题分类

游戏启动器

### 发生了什么？

管理员身份运行胡桃时分辨率被更改
官方启动器启动游戏，设置分辨率为1366*768，关闭游戏
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/4786de64-ced9-4a6f-ab47-e9230f4ab4d0)

使用hutao启动游戏（更改启动参数设置为关），启动游戏
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/17da747e-dfa8-497f-8961-ceb73a02b8d8)

分辨率被更改为1920*1080
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/547a8295-c7a0-4add-9f5c-057d648180c5)

### 你期望发生的行为？

未勾选更改启动参数时不改变分辨率

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
游戏内分辨率设置完成后把游戏设置关了再关游戏试试
