### ISSUE TITLE
[Bug]:必須登入米遊社/HoYoLab並選定一個用戶與角色

### ISSUE THREAD

**Issue by RJFAC** [DGP-Studio/Snap.Hutao#1395]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22000.2713

### Snap Hutao 版本

1.9.6.0

### 设备 ID

4B263104B9BECC724DFC70A8EEA7F25A

### 问题分类

祈愿记录

### 发生了什么？

已登入Hoyolab帳號，國際服(亞服)
![圖片](https://github.com/DGP-Studio/Snap.Hutao/assets/78807750/5b18e958-a659-4926-a8fd-7ea9325ff3d5)

啟動遊戲頁面，點選綁定當前用戶的角色
跳出錯誤訊息：必須登入米遊社/HoYoLab並選定一個用戶與角色
![圖片](https://github.com/DGP-Studio/Snap.Hutao/assets/78807750/3515f03a-cbd8-4197-9e9f-ae33224115dd)

我的角色頁面，三個同步按鈕皆無反應
![圖片](https://github.com/DGP-Studio/Snap.Hutao/assets/78807750/a0bf8ead-6bc7-4492-98df-3ad8802a0ee6)

祈願紀錄頁面，點選SToken重整
跳出錯誤訊息：必須登入米遊社/HoYoLab並選定一個用戶與角色
![圖片](https://github.com/DGP-Studio/Snap.Hutao/assets/78807750/d781bc66-c1de-4b99-8e41-6698011ad4fb)

即時便籤頁面功能正常
![圖片](https://github.com/DGP-Studio/Snap.Hutao/assets/78807750/089436be-a9be-4c16-9622-581e40a087ec)

### 你期望发生的行为？

我希望能正常使用上述功能，請告訴我應該如何操作，謝謝。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
HoYoLAB账号初始化了吗？看上去并没有，而且也没有实际的原神游戏账号和HoYoverse账号绑定。

**Comment by qhy040404** [comment]
在设置点击删除所有用户后重新登录hoyolab帐号

**Comment by Masterain98** [comment]
使用官方的HoYoLAB登录使用一次

**Comment by qhy040404** [comment]
手机hoyolab客户端登录一次

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/b3b6e3ee-d83a-4a7c-91cb-ba2d4b95e689)
HoYoLAB登录后用户名不会是默认名称

**Comment by Lightczx** [comment]
备份祈愿/成就数据并删除 %userprofile%/Documents/Userdata.db
