### ISSUE TITLE
[Bug]: 上传深渊记录失败，存在无效的数据

### ISSUE THREAD

**Issue by lwh9346** [DGP-Studio/Snap.Hutao#1396]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3007

### Snap Hutao 版本

1.9.6.0

### 设备 ID

F442DC1880A7645A9E870A4065E8885B

### 问题分类

胡桃数据库

### 发生了什么？

本人UID 295383769，使用胡桃工具箱上传深渊记录时提示“上传深渊记录失败，存在无效的数据”
工具箱深渊板块显示的时间、人物角色等数据均与米游舍无异
工具箱获取且仅获取到以下两次深渊的记录：
![本期深渊数据](https://github.com/DGP-Studio/Snap.Hutao/assets/58882256/26848137-4056-43fb-8f78-3164d860935d)
![上期深渊数据](https://github.com/DGP-Studio/Snap.Hutao/assets/58882256/e17e0216-8481-42cc-a84a-fae605db8239)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao.Server/commit/2709d655da42492698422473ed408998ff0ba941
