### ISSUE TITLE
[Bug]: 当Discord以管理员权限运行时，用普通权限开启胡桃会闪退

### ISSUE THREAD

**Issue by script-1024** [DGP-Studio/Snap.Hutao#1400]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.3140

### Snap Hutao 版本

1.9.6.0

### 设备 ID

8796217F06C2C31C62EB672432844EAC

### 问题分类

其它

### 发生了什么？

Discord 安装目录: `C:\User\<username>\AppData\Local\Discord\`
Snap.Hutao 安装目录: `C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.9.6.0_x64__wbnnev551gwxy\`

#### 问题复现方式
1. 电脑开机后使用 **管理员权限** 运行 Discord
2. 使用普通权限运行胡桃 `⚠️闪退`

#### 尝试寻找问题
* 重启电脑
    1. 重复上述操作 `⚠️闪退`

* 提高权限
    1. 运行 Discord（管理员）
    2. 运行胡桃（管理员） `✅正常`
    3. 运行胡桃（普通） `⚠️闪退`

* 结束 Discord 进程
    1. 先运行胡桃（普通or管理员） `✅皆正常`
    2. 运行 Discord（管理员） `✅未闪退`

* 卸载重装胡桃
    1. 运行 Discord（管理员）
    2. 运行胡桃（管理员） `✅正常`
    3. 运行胡桃（普通） `⚠️闪退`

* 怀疑问题或许和 dc 权限有关
    1. 运行 Discord（普通）
    2. 运行胡桃（普通or管理员） `✅皆正常`

* 卸载重装 Discord
    1. 运行 Discord（普通）
    2. 运行胡桃（普通） `✅正常`
    3. 运行 Discord（管理员）
    4. 运行胡桃（普通） `⚠️问题未解决`

* 使用另一台电脑尝试（Win11 x64 Build 22635.2921，Discord 版本相同）
    1. 运行 Discord（管理员）
    2. 运行胡桃（普通） 1.8.4~1.9.1 `✅正常`
    3. 运行胡桃（普通） 1.9.2~1.9.6 `⚠️闪退`
    4. 运行胡桃（管理员）任意版本 `✅皆正常`

## 附件

问题日志 [Snap.Hutao Error Log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/14312187/Snap.Hutao.Error.Log.txt)

调试控制台 [Snap.Hutao Debug Console Log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/14312286/Snap.Hutao.Debug.Console.Log.txt)

调试控制台内提到的 `%AppData%\discord\module_data\crashlogs\<时间>.log`
[2023_09_22T14_25_00_781Z-0-events.log](https://github.com/DGP-Studio/Snap.Hutao/files/14312717/2023_09_22T14_25_00_781Z-0-events.log)

#### Discord 客户端版本信息
* stable 266957 (7f1baf2)
* Host 1.0.9033 x86 (43813)
* Windows 11 64-bit (10.0.22635)
---
*令人摸不着头脑的神奇 bug ... 我也不知道和 dc 到底有什么关系*

### 你期望发生的行为？

正常启动，胡桃之前的版本没有这个问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
issue 写得挺好，但为什么要管理员模式启动 Discord

**Comment by script-1024** [comment]
一些有反作弊系统的游戏（比如原神），会以管理员模式运行，如果不给 Discord 管理员权限，游戏叠加画面、按键发话等功能无法正常使用，并且无法在直播时传递游戏声音

![Discord Ask Permission Dialog](https://github.com/DGP-Studio/Snap.Hutao/assets/95626542/6b9ce65a-1ffd-416e-bfdf-dfa8829eb276)
