### ISSUE TITLE
[Feat]: 希望增加一个文件夹，以多个md文件的形式反馈与解决alpha版中的各类问题

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1406]
### 背景与动机

如题，发现在群里面反馈会因为消息堆叠和他人回复造成逻辑混乱抓不住重点，希望通过如题的方式解决。

### 想要实现或优化的功能

Alpha程序反馈

**Comment by Lightczx** [comment]
开Issue即可
