### ISSUE TITLE
希望添加任务栏中右键可以管理员模式启动的选项

### ISSUE THREAD

**Issue by mowegel** [DGP-Studio/Snap.Hutao#1409]
### 背景与动机

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36895742/118fbb42-9226-4990-aafc-1cdce7f86234)
因为桌面不放图标，启动程序后再开启管理员较为繁琐，所以希望添加右键管理员模式运行

### 想要实现或优化的功能

在任务栏图标右键启动时可以选择管理员模式启动
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36895742/45dde1dc-0e5b-4548-a334-9bc0dc16033e)

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/5b55f43f-1cff-4724-88d8-dec359d7d6c9)

**Comment by Lightczx** [comment]
> ![image](https://private-user-images.githubusercontent.com/10614984/306184526-5b55f43f-1cff-4724-88d8-dec359d7d6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NzczODcsIm5iZiI6MTcwODQ3NzA4NywicGF0aCI6Ii8xMDYxNDk4NC8zMDYxODQ1MjYtNWI1NWY0M2YtMWNmZi00NzI0LTg4ZDgtZGVjMzU5ZDdkNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAwNTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ODY3NDNjZGYyNGQ0YzFlYmIxOWU5MWUzZjRhZWJjNDk3NjZjOGYxODlkNzMyZjg5ZDkyNThmZDM5NjY4NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ITpojBIOfmlUIO4fEaWqu8TWo2otIYDXQBm-Dy4NJI)

确实
