### ISSUE TITLE
[Feat]: 能否提供导入非UIGF格式抽卡成就平台数据的功能

### ISSUE THREAD

**Issue by putaomeiyoupi** [DGP-Studio/Snap.Hutao#1410]
### 背景与动机

祈愿记录功能的软件有很多，同时也有很多并没有采用UIGF标准，对于一些用量比较大的、广泛的，但是没有采用UIGF标准的平台，能否提供数据导入功能，比如paimon.moe

### 想要实现或优化的功能

导入paimon.moe平台的祈愿记录导出文件。

**Comment by Lightczx** [comment]
让他们支持 UIGF 去

**Comment by BTMuli** [comment]
https://github.com/MadeBaruna/paimon-moe/issues/312

https://github.com/MadeBaruna/paimon-moe/issues/437

**Comment by Masterain98** [comment]
可以使用 https://github.com/Masterain98/UIGF-Converter 转化为 UIGF 数据格式
