### ISSUE TITLE
[Bug]: 1.9.7 版本选择“无背景图片”并不能恢复亚克力效果

### ISSUE THREAD

**Issue by ChrisKimZHT** [DGP-Studio/Snap.Hutao#1416]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631/3155

### Snap Hutao 版本

1.9.7.0

### 问题分类

安装和环境

### 发生了什么？

在 `1.9.6` 背景图更新后，我反馈请求恢复 `1.9.5` 无背景图的亚克力效果，`1.9.7` 提供了无背景图选项，但是亚克力效果仍然消失。

怀疑程序在 UI 和桌面之间直接添加了一层纯白图片来实现无背景图的功能，但是这会导致亚克力效果失效。

对比如下：

1.9.5 Acrylic
![1 9 5 acrylic](https://github.com/DGP-Studio/Snap.Hutao/assets/49368462/e10045f0-35fa-4013-ab1f-3790d4da9fc9)

1.9.7 Acrylic
![1 9 7 acrylic](https://github.com/DGP-Studio/Snap.Hutao/assets/49368462/636c1214-c3f9-4d6e-9741-8c8e8e107903)

### 你期望发生的行为？

希望开发组能够恢复亚克力效果。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
Intended

**Comment by ChrisKimZHT** [comment]
> Intended

If this effect is intentionally adjusted by you, then we hope you can provide a feature to disable program update pop-ups, allowing users to stay on the old version.

**Comment by Masterain98** [comment]
> 怀疑程序在 UI 和桌面之间直接添加了一层纯白图片来实现无背景图的功能，但是这会导致亚克力效果失效。

在主程序窗口中做了限制，一切背景材质都被禁用了。如果你启用了某种背景材质，再次进入到用户引导界面等非主程序窗口时，仍然是有背景材质生效的。

> 为什么主程序中的背景材质要被禁用

因为要做背景图片功能

> 为什么要做背景图片功能

1. 因为这是 SG 的传统特色，胡桃项目只是因为没时间做
2. 有不少人催做该功能

> 为什么做了背景图，背景材质就会失效

因为基于有背景的设计重新做了样式，在这基础上的背景材质真的不好看，尤其是暗色模式下。且由于禁用背景材质和背景图片功能是同一更改，所有参与测试和开发的人员都认为背景图片带来的效果远远好于任意背景材质，故无人询问是否要保留主程序窗口的背景材质（参与该项更改中的成员只有我使用亚克力，而我当时在看到效果后也是认为带着背景材质是不好看的）

> 那能不能让用户去试试新设计下的背景材质效果呢？（这是我仅能争取到的，也是我认为足够的）

从当前最新的 Alpha 版本和下一个正式版起，用户设置中的背景材质项将再次对主程序窗口生效，默认值为 None，需要用户手动选择启用。该选项和背景选项不冲突。

---

> If this effect is intentionally adjusted by you, then we hope you can provide a feature to disable program update pop-ups, allowing users to stay on the old version.

**我个人的回答是：绝对不可能** 。作为用户，我能理解新版本程序带来的变化会带来新的学习成本，在本已忙碌的生活中，无关紧要但不得不做的事情可能会令人厌恶。但作为开发者，尤其是一个人手不足项目的开发者，能让所有用户跟着升级是一个奢望。旧版本中的已知问题和新的已知问题，可能早已在新版本中修复，但无意义的提问不会停止，解决这一问题最好的方法就是帮助用户升级到最新版本。

诚然当前胡桃的更新模块有比较明显的缺陷，比如 #1297 （这一项到现在没有做的原因我们没有 UI 设计师来帮助开发团队构建原型），但设计的逻辑一定是允许用户暂时不升级，而不会是长期地赖在某个版本。

---

所有的程序更改都不可能满足所有人的愿望。在开发时，用户只能提供想法，虽然是有价值的，但也经常是不切实际的，因为在实施时有太多的限制了（无论是主观的还是客观的）。一个想法，从用户的构想到最终的实现往往是有差距的。在这个过程中，各个主体产生的影响力大小大致是： `操刀该部分的开发者 >>> 开发团队其它人员 > 外部合作者和 Alpha 测试人员 >>>>>>> 用户`。用户最终看到的，可能是改过N次的妥协方案了。

---

Resolved by c30c8b1
