### ISSUE TITLE
希望胡桃工具箱更新后，更新桌面的管理员快捷方式名称

### ISSUE THREAD

**Issue by 144-144** [DGP-Studio/Snap.Hutao#1417]
### 背景与动机

工具箱更新到1.9.7.0后，桌面管理员快捷方式的名称仍为“胡桃 1.9.6.0”，虽然能正常打开，但是看着别扭。

### 想要实现或优化的功能

希望工具箱更新后，删除以前添加的管理员快捷方式，再添加已经新版的快捷方式。

**Comment by qhy040404** [comment]
看着别扭请你自己重命名
