### ISSUE TITLE
[Bug]: 导入提瓦特小助手祈愿记录崩溃闪退

### ISSUE THREAD

**Issue by putaomeiyoupi** [DGP-Studio/Snap.Hutao#1418]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3155

### Snap Hutao 版本

1.9.7.0

### 设备 ID

ECD1F80EB7B017D3B1DE9577570C3B87

### 问题分类

祈愿记录

### 发生了什么？

导入从提瓦塔小助手导出的祈愿记录，然后就程序闪退了。

### 你期望发生的行为？

希望将提瓦特小助手的祈愿记录与胡桃的合并。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/156564853/19a86283-ea87-4f5d-8ff6-f8b6451ab300)

https://github.com/DGP-Studio/Snap.Hutao/assets/156564853/447fe232-a6f8-4f72-bd97-78d9e8171ba3

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
请提供小助手导出的json文件

**Comment by putaomeiyoupi** [comment]
> 请提供小助手导出的json文件 @putaomeiyoupi

[159860962.json](https://github.com/DGP-Studio/Snap.Hutao/files/14374078/159860962.json)

**Comment by zhaobozhen** [comment]
[椰羊UIAF1.1.20240319211629.json](https://github.com/DGP-Studio/Snap.Hutao/files/14651165/UIAF1.1.20240319211629.json)
这份样本也会闪退，供参考

**Comment by Lightczx** [comment]
> [椰羊UIAF1.1.20240319211629.json](https://github.com/DGP-Studio/Snap.Hutao/files/14651165/UIAF1.1.20240319211629.json) 这份样本也会闪退，供参考

如果你确实遇到问题，请新开Issue，不要在无关的Issue下跟评
