### ISSUE TITLE
[Bug]: 祈愿记录页面

### ISSUE THREAD

**Issue by Ryn-cn** [DGP-Studio/Snap.Hutao#1422]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3155

### Snap Hutao 版本

1.9.7.0

### 设备 ID

D60DF85179544718493D41932C225113

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录页面如图片所示，上面标签栏红色箭头的数字UID选择可以切换不同账号的祈愿记录。
但是标签栏上的”刷新“是按照胡桃左下角蓝色箭头所示的账号来更新的。
在切换账号上会有割裂感。
。
如果多账号就会出现这样的情景：
“我在祈愿记录页面上方标签栏选择了UID1浏览， 然后在页面上方逐步点击选择查看UID2，UID3，UID4，
看到4号的时候打算刷新记录浏览， 但是点击刷新之后又自动跳回UID1刷新， 以为出了什么问题，多次选择UID4刷新依然跳回UID1的祈愿记录。
最终发现更新记录需要手动到胡桃界面左下角选择对应第4个账号的米友社ID， 再回去点击上方标签栏的”刷新“ 才可以逐步对各个账号的祈愿记录刷新
即使我现在清楚知道如此操作，仍旧会有割裂感，上方显示的是数字UID， 下方显示的是米友社头像名字，类似的功能却不通用。”

### 你期望发生的行为？

初次登录米友社账号， 则默认刷新祈愿记录是此账号。
以后点击祈愿记录页面的刷新， 进行刷新的则按照“祈愿记录”界面上方的数字UID选项来刷新对应记录。
PS：登录米友社账号直接就在祈愿记录页面上方UID标签也增加上对应账号

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你图呢？

**Comment by Masterain98** [comment]
你完全没有理解刷新功能。祈愿记录是可以通过导入功能导入你没有甚至无法登录账号记录的数据的。

刷新数据永远是跟数据源走的，你选择Stoken刷新那肯定是刷新当前米游社账号的数据；你选择缓存刷新，那肯定是刷新你本地客户端刚刚登录的游戏账号的数据。

**Comment by Lightczx** [comment]
> 进行刷新的则按照“祈愿记录”界面上方的数字UID选项来刷新对应记录

非Stoken刷新情况下不可能做到跟随UID刷新
