### ISSUE TITLE
[Feat]: 希望在角色资料栏目中新增“满好感度名片”的选项

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1424]
### 背景与动机

希望查看自己没有的角色的好感名片

### 想要实现或优化的功能

好感角色名片添加到角色资料那里，可单开一个小类别或直接像我的角色那里一样用作背景

**Comment by Masterain98** [comment]
#1283

**Comment by Lightczx** [comment]
Tracked by #1394
