### ISSUE TITLE
[Feat]: 养成计划中的材料统计部分，新增分类功能，按照材料类型、材料周几能刷等维度进行排序或分类

### ISSUE THREAD

**Issue by GoddessLuBoYan** [DGP-Studio/Snap.Hutao#1427]
### 背景与动机

如图所示，目前养成计划中的材料统计，按照所需材料的数量从上到下依次排列。

但对于我目前的情况（同一养成计划中列入十几名角色）这个页面存在以下不足之处：

1. 材料杂乱无章，看着很乱。按照游戏内背包的习惯，一般相同类型的材料（Boss材料、天赋材料、角色与武器培养材料等）会聚类展示，对同一种材料的不同稀有度则按照金、紫、蓝、绿、灰的稀有度顺序降序排序。
（同理，养成物品中，建议角色放在一起，武器放在一起，或者角色与其携带的武器放在一起，不要乱七八糟的，不过这不在本特性讨论范围之内）
2. 我不知道今天该刷什么。即使我背下来了每天的天赋类型，我也记不住每天的武器材料类型。如果可以按照日期进行分类，或者将今日可刷的材料靠前展示，可以减少今天刷什么的思考时间。

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/38455509/0837a607-98f2-4b5d-913f-420cc514efb8)

### 想要实现或优化的功能

我个人期望的形态：

1. 在材料统计页面中，所有材料按照游戏内合成台的材料顺序依次排序（摩拉、矿等不在合成台内的材料放在开头）
2. 对于当日可刷的材料，高亮显示或靠前（置顶）显示，或者对于当日不可刷的材料，显示为暗色
3. （可选）按照材料的类型或哪天可以刷，在页面上用一个筛选按钮来筛选掉（也可以支持智能筛选）

补充：对于1，合成台/背包的顺序未必能够通过API获取，可以使用以下替代方法：

方法1：（麻烦，需手动）手动维护材料的顺序，只对手动维护材料顺序的材料排序，其余材料全部靠前展示，排序方式不变（靠前是因为这些材料一般是新材料）

方法2：（实现难度最低）从米游社获取材料列表后，按照材料的”道具类型“字段进行筛选，再对同类型的道具按照道具id进行排序，得到的顺序基本上是按照材料顺序，稀有度从低到高排列的。我用角色与武器培养材料试了一下，少部分顺序不对，大部分都是对的。

方法3：（基于方法1，可根治，但很花费精力）依次遍历每个养成用材料的米游社链接，通过材料的用途来确定哪些道具属于同一类型的道具，他们的上下级关系是什么。举例：材料【地脉的枯叶】的用途之一是”【炼金】地脉的新芽“。使用这种方法可以自动维护方法1中的材料顺序，但耗时较长，建议仅服务端（胡桃云）每版本计算一次。

方法2的效果如图所示（使用python，只展示标题，以角色与武器培养素材为例，包括红框内只有三四处是道具没和同类道具放在一起的，此外还有两三个是稀有度降序，或者二星、四星、三星这样比较奇怪的顺序，但至少在同一类）
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/38455509/2c64af74-e43d-4f82-8d73-4787cf51a8eb)

**Comment by GoddessLuBoYan** [comment]
备注：这只是我个人的想法，实际是否去做，需要看实际用这个功能的人多不多，需求大不大，需求不大的话可以直接close，大家都挺忙的，精力尽量还是放在必要的地方上

**Comment by Lightczx** [comment]
Tracked by #1394

**Comment by GoddessLuBoYan** [comment]
原来已经在计划中了

**Comment by GoddessLuBoYan** [comment]
> 原来已经在计划中了

#889 已经在roadmap里面了，没事了
