### ISSUE TITLE
[Feat]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by lonkann** [DGP-Studio/Snap.Hutao#1428]
### 背景与动机

纯白主题跑哪去了???

### 想要实现或优化的功能

写一个按钮切换吧，找半天没找着 qoq

**Comment by qhy040404** [comment]
Duplicate of #1373 
你是活爹啊说话那么没礼貌

**Comment by lonkann** [comment]
你是傻逼吗这才叫没礼貌，你自尊心得多脆弱才觉得这冒犯到你，傻鸟 这才叫没礼貌，不会做程序就滚 写一个前端的切换按钮是要你命吗？



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月28日 12:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DGP-Studio/Snap.Hutao] [Feat]: 在这里填写一个合适的标题 (Issue #1428) |

Duplicate of #1373
你是活爹啊说话那么没礼貌

**Comment by lonkann** [comment]
叫声爹来我帮你写



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月28日 12:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DGP-Studio/Snap.Hutao] [Feat]: 在这里填写一个合适的标题 (Issue #1428) |

Duplicate of #1373
你是活爹啊说话那么没礼貌

**Comment by Masterain98** [comment]
确实没看出来你有任何礼貌的举动。

这是一个已有的功能，而很显然你完全没有探索这个应用程序，也没有查询文档，而是把功能请求议题当作你宣泄的场所。你甚至不愿意好好写一个标题，在bot快速提醒后也没有修改，那么你的议题只会被无视。
