### ISSUE TITLE
[Bug]: 主页成就卡片文本大小

### ISSUE THREAD

**Issue by lzc1999gh** [DGP-Studio/Snap.Hutao#1429]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3155

### Snap Hutao 版本

1.9.7.0

### 问题分类

用户界面

### 发生了什么？

图中成就统计界面可以看到很明显的显示问题，目前没有发现有其他人有这个问题，所以是想来询问下可能原因，显示器分辨率是2560x1440，缩放为100%
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/62326392/19391210-1687-4b2f-af5f-4b61f8373ab1)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你的文本大小是百分之几 @lzc1999gh

**Comment by lzc1999gh** [comment]
> 你的文本大小是百分之几 @lzc1999gh

124%，我试了下改为100%好了，谢谢

**Comment by Lightczx** [comment]
124%是magic number,请使用25%的整数倍的比例

**Comment by lzc1999gh** [comment]
> 124%是magic number,请使用25%的整数倍的比例
打扰了。但即使是使用整数倍比例如125，150，仍有这种现象，想问下没有适配吗。感谢。
