### ISSUE TITLE
[Feat]: 更小的图片资源尺寸

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1430]
### 背景与动机

减小图片资源尺寸，降低储存和带宽压力

### 想要实现或优化的功能

- [x] Snap.Static.Tiny
- [x] 自动化的图片子集
- [x] 后端适配
- [ ] 客户端适配

**Comment by Mikachu2333** [comment]
mozjpeg？
（相关的项目：[squoosh](https://github.com/GoogleChromeLabs/squoosh)、[rimage](https://github.com/SalOne22/rimage)）

**Comment by Masterain98** [comment]
| Quality | Minimum | Package Size   |
| ------- | ------- | -------------- |
| Raw     | False   | 510M (Current) |
| Raw     | True    | 453M           |
| High    | False   | 139M           |
| High    | True    | 116M           |
