### ISSUE TITLE
[Feat]: 武器、角色资料页里的筛选能不能提供模糊匹配，尤其找武器太麻烦了。

### ISSUE THREAD

**Issue by putaomeiyoupi** [DGP-Studio/Snap.Hutao#1435]
### 背景与动机

加快查早速度，如果真每次都精确匹配查找速度还不如点图片。关键是在网格窗口里选中之后还不能直接切回列表页，还要手动再点一下很麻烦。

### 想要实现或优化的功能

武器、角色资料页里的筛选提供模糊匹配，比如找闲云的时候只要输入一个闲就行了，因为有些武器角色的名字真的很麻烦，尤其武器。

**Comment by Lightczx** [comment]
#1421
