### ISSUE TITLE
[Bug]:背景无法正常显示

### ISSUE THREAD

**Issue by xmbdf** [DGP-Studio/Snap.Hutao#1438]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3155

### Snap Hutao 版本

1.9.7.0

### 问题分类

游戏启动器

### 发生了什么？

背景图片调为：胡桃每日一图时，启动器壁纸将无法正常显示，背景始终为白色。
但背景图片调为：本地随机图片、必应每日一图或官方启动器壁纸时，启动器壁纸可以正常显示。

### 你期望发生的行为？

背景图片调为：胡桃每日一图时，启动器壁纸将正常显示。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
Fixed

请重新启动客户端检查一下
