### ISSUE TITLE
[Hoyolab]: Globalization support

### ISSUE THREAD

**Issue by oofoever** [DGP-Studio/Snap.Hutao#144]
Hello,

Hope to support hoyolab login in regions other than mainland China.

Thank you.

**Comment by Lightczx** [comment]
Tracks

- [ ] #141

**Comment by solacens** [comment]
> We are also constantly looking for developers to take this feature into the software. There isn't any international server player in the current dev team, which obstructs push in this plan.

要幫忙嗎？

**Comment by Lightczx** [comment]
Just open PR @solacens

**Comment by solacens** [comment]
> Just open PR @solacens

容我先品一品，MSIX還真沒弄過

**Comment by Lightczx** [comment]
@solacens Hi, are you available recently?
We are going to tanslate our UI/UX onto several languages including `zh-Hant`
If you are interested in translating, you can click [here](https://crowdin.com/project/snap-hutao) to help us out.

**Comment by solacens** [comment]
Sure @Lightczx

**Comment by Masterain98** [comment]
For in-game notice:
- Url
  - https://sg-hk4e-api.hoyoverse.com/common/hk4e_global/announcement/api/getAnnList
- Query
  - `game=hk4e&game_biz=hk4e_global&lang=zh-cn&announcement_version=1.21&auth_appid=announcement&bundle_id=hk4e_global&channel_id=1&level=55&platform=pc&region=os_usa&uid=100000000`


Tested parameter in the query:
- `lang`
  - `zh-cn`
  - `zh-tw`
  - `en-us`
- region
  - `os_usa`
  - `os_asia`

**Comment by Lightczx** [comment]
> 

Any api like `getAnnContent` ?

**Comment by Lightczx** [comment]
It's where we store the api spec.
[ApiEndpoints](https://github.com/DGP-Studio/Snap.Hutao/blob/main/src/Snap.Hutao/Snap.Hutao/Web/ApiEndpoints.cs)
If there is someone interested in globalization, you can start from here.

**Comment by sheaahhoi1** [comment]
@Lightczx 找下列一些hoyolab API,多是用python編寫,對做bot 好像有用,不知有沒有參考價值

原神 API : https://github.com/thesadru/genshin.py
hoyolab API: https://github.com/vermaysha/hoyolab-api
https://vermaysha.github.io/hoyolab-api/
Genshin-DB API : https://github.com/theBowja/genshin-db

國外有點名氣的Enka Network網站https://enka.network/
Enka Network API也有能調用hoyolab api項目: https://github.com/EnkaNetwork/API-docs
https://api.enka.network/#/api_chs

**Comment by lyx20030901** [comment]
> What we really need is the details of calling the international server API and also the response data structs.

I know some network packet capturing and APP decompilation，if you still need this, maybe I can help

**Comment by Lightczx** [comment]
> > What we really need is the details of calling the international server API and also the response data structs.
> 
> I know some network packet capturing and APP decompilation，if you still need this, maybe I can help

Just open PR

**Comment by Lightczx** [comment]
> These are gained from the packets which are captured from Hoyolab website. I don't know how to request them correctly and always get a 403 response.

What fields do these requests have in Cookie header?

**Comment by Xhichn** [comment]
> > These are gained from the packets which are captured from Hoyolab website. I don't know how to request them correctly and always get a 403 response.
> 
> What fields do these requests have in Cookie header?

```
mi18nLang=zh-cn; 
_MHYUUID=; 
DEVICEFP_SEED_ID=; 
DEVICEFP_SEED_TIME=; 
_ga_HR3ZEH2708=; 
ltoken=; 
ltuid=; 
_ga_1CHR121QPG=; 
DEVICEFP=; 
_gid=; 
_ga_JRFG0HQ22J=; 
_gat=1; 
_ga_JTLS2F53NR=; 
_ga=; 
_gat_gtag_UA_206868027_11=
```

**Comment by lyx20030901** [comment]
> > What fields do these requests have in Cookie header?
> 
> ```
> mi18nLang=zh-cn; 
> _MHYUUID=; 
> DEVICEFP_SEED_ID=; 
> DEVICEFP_SEED_TIME=; 
> _ga_HR3ZEH2708=; 
> ltoken=; 
> ltuid=; 
> _ga_1CHR121QPG=; 
> DEVICEFP=; 
> _gid=; 
> _ga_JRFG0HQ22J=; 
> _gat=1; 
> _ga_JTLS2F53NR=; 
> _ga=; 
> _gat_gtag_UA_206868027_11=
> ```
The items you need is ltoken and ltuid. In addition, you also need to pay attention to the request header information.

**Comment by lyx20030901** [comment]
> There is a field called **DS** presents in request header for getting abyss and characters data. Maybe improper DS value leads to a 403 forbbiden error. But how to caluculate DS?
> 
> ```httpspec
> GET /game_record/genshin/api/spiralAbyss?server=os_asia&role_id=100000000&schedule_type=1 HTTP/1.1
> Host: bbs-api-os.hoyolab.com
> Connection: keep-alive
> sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Microsoft Edge";v="110"
> DS: 1678451758,CFpnKz,0fa1b38f759f5e42c9e587035e421535
> x-rpc-language: zh-cn
> x-rpc-app_version: 1.5.0
> sec-ch-ua-mobile: ?0
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63
> Accept: application/json, text/plain, */*
> x-rpc-client_type: 5
> sec-ch-ua-platform: "Windows"
> Origin: https://act.hoyolab.com
> Sec-Fetch-Site: same-site
> Sec-Fetch-Mode: cors
> Sec-Fetch-Dest: empty
> Referer: https://act.hoyolab.com/
> Accept-Encoding: gzip, deflate, br
> Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-US;q=0.7
> Cookie:
> ```
> 
> Some apis don't require DS, I tried another api with only `ltuid` and `ltoken` in cookie and it works well.
> 
> * GET https://api-os-takumi.hoyoverse.com/binding/api/getUserGameRolesByCookie
> * Query `game_biz=hk4e_global`
> 
> It returns game roles' uid in such format:
> 
> ```json
> {
>     "retcode": 0,
>     "message": "OK",
>     "data": {
>         "list": [
>             {
>                 "game_biz": "hk4e_global",
>                 "region": "os_usa",
>                 "game_uid": "100000000",
>                 "nickname": "",
>                 "level": 1,
>                 "is_chosen": false,
>                 "region_name": "America Server",
>                 "is_official": true
>             },
>         ]
>     }
> }
> ```

If you want to calculate DS for Web, you can find algorithm code in JavaScript. For android app, I'm trying to get key parameter，but there is still no progress

**Comment by Lightczx** [comment]
DS is not a problem, we known how to calc it.

**Comment by Xhichn** [comment]
Well, I successfully access those two API mentioned in https://github.com/DGP-Studio/Snap.Hutao/issues/144#issuecomment-1463846504 

Here are the headers. It seems cookie fields `ltuid`, `ltoken`, `cookie_token` are enough, which can be obtained from `www.hoyolab.com`.

```
'Cookie': 'ltoken=; ltuid=; cookie_token=',
'x-rpc-app_version': '1.5.0',
'x-rpc-client_type': '4',
'x-rpc-language': 'en-us',
'DS': '1678518262,qweqaZ,fe6535dab71ae3478ce5b2871fc31fa0',
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
```

**Comment by Lightczx** [comment]
#638
