### ISSUE TITLE
游戏不运行

### ISSUE THREAD

**Issue by luomi114514** [DGP-Studio/Snap.Hutao#1442]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26058.1400

### Snap Hutao 版本

1.9.7.0

### 问题分类

游戏启动器

### 发生了什么？

不知道发生什么，就没办法启动原神，换服也一样，点击启动游戏只提示游戏进程运行中，等了1个多小时还没没出现

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
用官方启动器能启动吗 @luomi114514

**Comment by luomi114514** [comment]
> 用官方启动器能启动吗 @luomi114514

能，而且运行正常

**Comment by Lightczx** [comment]
关掉启动游戏下方的设置 Discord Activity 状态

**Comment by luomi114514** [comment]
> 关掉启动游戏下方的设置 Discord Activity 状态

没有启动游戏，跟之前的情况一样

**Comment by qhy040404** [comment]
提供你的启动参数

**Comment by luomi114514** [comment]
> 在设置里打开调试控制台，在启动游戏卡住后，发下控制台的截图 @luomi114514
![屏幕截图 2024-03-06 180516](https://github.com/DGP-Studio/Snap.Hutao/assets/125117292/6c5b9656-829d-4912-bb04-7b87e76f7386)
游戏倒是不知道啥原因，可以启动了
