### ISSUE TITLE
[Bug]: 目前无法通过旅行工具-原神战绩获取实时便签了

### ISSUE THREAD

**Issue by 0xxxD** [DGP-Studio/Snap.Hutao#1447]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.9.7.0

### 问题分类

实时便笺

### 发生了什么？

实时便签-立即刷新报错：-10001 | 信息：invalid request，
通过旅行工具-原神战绩页面提示V2.1.0以下版本将无法正常使用战绩功能，请更新米游社至最新版。。

### 你期望发生的行为？

跟之前一样正常刷新便签

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/40531d32-14d1-4de0-9270-5c153cdb1e99)
I don't think so

**Comment by Lightczx** [comment]
删除用户重新添加看看

**Comment by 0xxxD** [comment]
已解决，本人系统时间错了。抱歉没看常见异常就提了issue
