### ISSUE TITLE
[Feat]: “我的角色”中无法查看主角属性，希望增加该功能

### ISSUE THREAD

**Issue by SilverSwiftblade** [DGP-Studio/Snap.Hutao#1448]
### 背景与动机

在胡桃工具箱中无法查看主角的属性以及设置培养方案，略有不便。

### 想要实现或优化的功能

如其他自机角色一样，在“我的角色”中显示主角属性（例如可由角色橱窗导入）。

**Comment by qhy040404** [comment]
Duplicate of #356
