### ISSUE TITLE
[Bug]: 【主页】-【启动游戏框】-选择账号功能不可用

### ISSUE THREAD

**Issue by BenBenHaoBa** [DGP-Studio/Snap.Hutao#1455]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.3276

### Snap Hutao 版本

1.9.7.0

### 设备 ID

5A31FE0492A547E9C593DCACB05BD645

### 问题分类

游戏启动器

### 发生了什么？

登录两个账号：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/39652768/224c2b39-4f26-486e-a2dd-b2df5f5a7984)
选择启动账号时为空：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/39652768/77695b50-0daa-4c73-a613-4e7d384f3a22)

### 你期望发生的行为？

可以正常自由切换登录账号

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
《我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答》
