### ISSUE TITLE
[Bug]: 打开Hutao后为管理员模式

### ISSUE THREAD

**Issue by mawence** [DGP-Studio/Snap.Hutao#1458]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4046

### Snap Hutao 版本

1.9.7.0

### 设备 ID

A84F7795509E79BA1D56D2733CEE3D3E

### 问题分类

安装和环境

### 发生了什么？

打开程序后就是管理员模式，无法正常进入

### 你期望发生的行为？

进入时为普通模式，非管理员模式

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
Duplicate of #1382 

《我的问题是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也是一个别人已发布的重复的问题》
