### ISSUE TITLE
stonken祈愿刷新 抽卡顺序错乱

### ISSUE THREAD

**Issue by chuyinluotian01** [DGP-Studio/Snap.Hutao#146]
### Windows 版本

22621.674

### Snap Hutao 版本

1.1.14

### 发生了什么？

祈愿记录通过stonken祈愿刷新，抽卡顺序错乱

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [ ] 是

### 我确认没有他人提出相同或类似的问题

- [ ] 是

### 我确认该问题没有在文档中解释

- [ ] 是

**Comment by Lightczx** [comment]
#93
