### ISSUE TITLE
[Feat]: 隐藏祈愿记录常驻池的“N/A”标识

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1460]
### 背景与动机

RT，太丑了

![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/1a10aea3-ca29-4eac-a661-f15817dda485)

### 想要实现或优化的功能

希望能使其居中平分，减少无用空间
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/fb29677f-f270-43ec-b966-2ccd20c35935)

**Comment by lcp1234** [comment]
我觉得应该是照搬了包含UP平均抽数的UI，但是常驻池里面没有up的机制。

**Comment by EricZhang233** [comment]
确实丑，直接隐藏吧，让5星抽数和欧非平分空间。

**Comment by Lightczx** [comment]
implemented
