### ISSUE TITLE
[Feat]: 关于不同分辨率及缩放下优化胡桃显示效果的建议

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1461]
### 背景与动机

在1920*1080，150%缩放时，胡桃的多处显示效果都无法让人十分满意。因此希望进一步优化。

### 想要实现或优化的功能

全屏状态下，出问题的各部分截图如下所示。

（祈愿页面截图同issues #994 ，希望居中或适当增加栏宽）
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/2a6129c8-c28a-444d-890c-c1ca837e3e5c)

（希望角色条和角色大图能有一定间隔并合理居中）
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/7449a1bf-6de7-45e5-a888-654f17e0c673)

（需求同上）
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/0ea2b56c-c80b-4bc5-ae1a-bb6bc7a663d3)

（同上）
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/7b7d2a69-d668-4a94-b484-8daead5710ac)

（怪物页面无上面提到的问题，但是两边宽度不同，希望居中）
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/aec081ba-7b25-40f3-88b3-2797f613b68a)

**Comment by Lightczx** [comment]
intended
