### ISSUE TITLE
[Bug]: 怪物资料 属性名称 字符串不能完整显示

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1465]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4123

### Snap Hutao 版本

2024.3.10.9

### 问题分类

安装和环境

### 发生了什么？

#863 
详见群内讨论
<img width="960" alt="1765435d3155da5cf6545b2ec78f4410" src="https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/07c7ddd7-0992-42da-b3e8-648e7785664a">

除此以外有问题的还有：
丘丘霜铠王-冰
丘丘岩盔王-岩
丘丘雷兜王-雷
嗜雷·兽境猎犬-物抗以外全部
嗜岩·兽境猎犬-物抗以外全部
黄金王兽-物抗以外全部
冰风组曲-风冰
实验性场力发生装置-岩
急冻树-冰
爆炎树-火
掣电树-雷
浮游草蕈兽-草
隐山猊兽-风水
若陀龙王-岩
阿佩普的绿洲守望者-草
吞星之鲸-水

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by shunjiankongbai-cn** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/109362925/73f4c111-0056-4b36-b5ac-f9e74f4a699c)
同样遇到这种问题了

**Comment by Lightczx** [comment]
WinUI的问题，特定缩放比大小下一定出现，目前无解决方案
