### ISSUE TITLE
启动时无法启用bettergi

### ISSUE THREAD

**Issue by d2913406181** [DGP-Studio/Snap.Hutao#1467]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3235

### Snap Hutao 版本

1.9.7.0

### 设备 ID

32215090327E0A24696C5B150985F066

### 问题分类

游戏启动器

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/117185638/cee26e2c-1698-439b-8d6b-04ae9d54eaa1)
提示如上图，概率性发生，通常第二次又可以正常启动

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
用管理员模式启动胡桃能不能避免该情况？
