### ISSUE TITLE
从SG导出的json导入胡桃后抽卡顺序及抽卡记录数不对

### ISSUE THREAD

**Issue by chuyinluotian01** [DGP-Studio/Snap.Hutao#147]
### Windows 版本

win11  22621.674

### Snap Hutao 版本

1.1.14

### 发生了什么？

从SG导出的json导入胡桃后抽卡顺序及抽卡记录数不对

### 你期望发生的行为？

![图片](https://user-images.githubusercontent.com/53629507/198987148-f5588990-3fe5-4759-8d4e-62baf3f9c2cf.png)
[106144468.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9900232/106144468.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by chuyinluotian01** [comment]
![图片](https://user-images.githubusercontent.com/53629507/198989233-09cef62b-535e-4ce4-aa76-18b17877744f.png)
删除后重新导入 还是错误的

**Comment by Lightczx** [comment]
表内的id不正确，请检查导入sg时的表格
