### ISSUE TITLE
[Bug]: 祈愿记录无法执行“从缓存刷新”

### ISSUE THREAD

**Issue by Array-Cats** [DGP-Studio/Snap.Hutao#148]
### Windows 版本

22621.755

### Snap Hutao 版本

1.1.14.0

### 发生了什么？

软件未正确寻找内置浏览器缓存路径，导致祈愿记录无法执行“从缓存刷新”，提示“找不到原神内置浏览器缓存路径 D:\Apps\Genshin Impact\YuanShen_Data\webCaches\Cache\Cache_Data\data_2”

本机launcher.exe目录：D:\Apps\Genshin Impact

本机YuanShen.exe目录：D:\Apps\Genshin Impact\Genshin Impact Game

胡桃设置页“游戏路径”设定目录：D:\Apps\Genshin Impact\Genshin Impact Game

### 你期望发生的行为？

正确识别内置浏览器缓存路径（D:\Apps\Genshin Impact\Genshin Impact Game\YuanShen_Data\webCaches\Cache\Cache_Data\data_2）

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
所以为什么不点击 `设置路径` 按钮呢

**Comment by Array-Cats** [comment]
因为手动点击过
