### ISSUE TITLE
[Bug]: 密码输入框在按下查看密码按钮时反复闪烁无法看清

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1485]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4123

### Snap Hutao 版本

1.9.8.0

### 问题分类

胡桃帐号

### 发生了什么？

如视频所示，闪烁频繁

https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/f5b902c7-c0ca-427b-88f4-20fa143ff423

### 你期望发生的行为？

不要闪烁……

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Scighost** [comment]
建议修改占位符 `PasswordChar`，并在输入框内使用等宽字体。

**Comment by Mikachu2333** [comment]
> 在输入框内使用等宽字体

不知道胡桃在设置密码的时候是否允许中文等奇形怪状的UTF8，如果是的话可能需要严格1:2的中英字符吧……

---

这里有一个怪异的解决方案，把遮挡字符和输入的字母都显示为全角的字符……这样就和中文等宽了，无需强求等宽字体（

不过有点过于粗暴了，并且还需要自己重写一遍密码的显示逻辑……刚刚自己试着实现了半天直接放弃，看看有没有现成的轮子能用？

**Comment by Scighost** [comment]
换个角度想，设置 dialog 的宽度为一个定值，让其免受输入框内字符多少的影响。

**Comment by GashByte** [comment]
TextBox有MaxWidth，TextWrapping设置成NoWrap应该就可以了
