### ISSUE TITLE
[Bug]: 鼠标DPI直线下滑

### ISSUE THREAD

**Issue by NOWorEVER** [DGP-Studio/Snap.Hutao#1486]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

版本 23H2(OS 内部版本 22631.3296)

### Snap Hutao 版本

1.9.8.0

### 设备 ID

9742471845FF82B35B5D6346F8F93917

### 问题分类

其它

### 发生了什么？

启动120帧解锁游戏后，再使用BetterGI，会让鼠标DPI直线下降
60帧率则不会有这种情况

### 你期望发生的行为？

120帧率也能正常使用BetterGI，这个情况也和BetterGI的作者发送了。希望可以帮助到你们

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你的电脑配置是什么

**Comment by qhy040404** [comment]
IO上限
偏方可以打之前重启一下

**Comment by NOWorEVER** [comment]
> IO上限 偏方可以打之前重启一下

’偏方可以打之前重启一下‘这是什么意思呢？

**Comment by Mikachu2333** [comment]
> ’偏方可以打之前重启一下‘这是什么意思呢？

他重新编辑了一下

**Comment by Masterain98** [comment]
CPU+GPU双重性能瓶颈造成的问题，BGI是OCR识图，加上解锁帧率，需要的性能会很多

**Comment by Lightczx** [comment]
可能是近期nVidia驱动的问题
