### ISSUE TITLE
[Feat]: 增强角色wiki搜索自动补全提示

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1487]
### 背景与动机

很多逆天用户不知道官方名称，比如我就一直输入长枪就是不出自动补全提示……结果才知道是长柄武器……

所以建议增强提示

### 想要实现或优化的功能

希望实现为如图所示的效果

![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/25668ac6-a447-4e46-aed7-515a807a47d8)

**Comment by Mikachu2333** [comment]
要么在搜索框左边加个按钮，用于弹窗提示可供选择的项

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/e3d2d737-95db-4bf1-91ed-b4b62309a441)

我给个参考

**Comment by Mikachu2333** [comment]
> 参考

太对了哥，就是这种样子的效果
