### ISSUE TITLE
[Feat]: 取消（删除）启动参数中“启用内置触摸布局”的选项

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1488]
### 背景与动机

经过尝试，天生与Windows不兼容，长按会自动试图唤起右键导致断触，笔记本屏幕太大导致搓玻璃板体感极差，角色转向困难（毕竟马哈鱼压根没优化过电脑的触屏客户端……），左边的导航罗盘更是不如大拇指大……一整个狗屎

建议删除无用之物

### 想要实现或优化的功能

删除该选项

**Comment by qhy040404** [comment]
有人要用

**Comment by Mikachu2333** [comment]
增加不适用于触摸屏笔记本电脑的描述
