### ISSUE TITLE
养成计划板块优化

### ISSUE THREAD

**Issue by Xuyuxiang1026** [DGP-Studio/Snap.Hutao#1489]
### 背景与动机

1.养成计划有点鸡肋。使用过程当中我需要专门点开一个页面才能知道我的养成计划，但是并没有时间上的安排，所谓的养成计划更多的是机械的汇总而非对时间的管理，因而我希望可以优化养成计划，这样每次打开启动器马上就可以知道今天能刷哪些材料。2.统计板块可以删去，因为大部分人的角色养成是一次一个的，即使有多个角色需要相同的材料也是有先后顺序而非同时进行。3.背包物品材料没有自动获取的途径，哪怕是需要手动打开插件的半自动获取途径也没有，如果是手动填写，过程繁琐且收益较低

### 想要实现或优化的功能

1.将养成计划以贴图的形式添加到主页，并优先显示现实时间可以刷取的材料。2.删除养成计划下的材料统计板块。3.背包物品栏添加类似于椰羊的识别系统用以识别，或者干脆删除这个板块

**Comment by Mikachu2333** [comment]
1，2已在计划中，无需重复开启

3的话不知道，等个开发

**Comment by Lightczx** [comment]
你要是有空可以开PR帮我们删除这个功能，反正我没空

**Comment by GoddessLuBoYan** [comment]
不建议删除统计板块，因为统计板块挺适合做材料分类的，包括roadmap中提到的材料日历之类的，在统计板块中也更适合做。
统计板块适用于已经养成了大部分角色，希望将剩余角色也都养成到期望的状态的玩家
