### ISSUE TITLE
[Bug]: 在解锁帧率失败后不会自动终止游戏进程

### ISSUE THREAD

**Issue by StandardL** [DGP-Studio/Snap.Hutao#1495]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26080.1100

### Snap Hutao 版本

1.9.8.0

### 问题分类

游戏启动器

### 发生了什么？

在旧版本胡桃工具箱（1.9.7）中，当程序解锁帧率失败时会自动关闭游戏进程。但在更新到1.9.8后即使解锁帧率失败，游戏依旧会启动。

### 你期望发生的行为？

像旧版本一样，解锁帧率失败时关闭游戏进程

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao/commit/6e8e151fff108799477b430c6bf3ce91f2f2b8a4
