### ISSUE TITLE
[Bug]: 1.9.7.0 自动更新 1.9.8.0 下载完检测到木马

### ISSUE THREAD

**Issue by lostsnow** [DGP-Studio/Snap.Hutao#1499]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3296

### Snap Hutao 版本

1.9.8.0

### 问题分类

安装和环境

### 发生了什么？

![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/220461/5d5d9f52-cfc0-446c-8075-843b30c09908)

1.9.7.0 升级 1.9.8.0 自动更新下载完检测为木马

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
手动信任一次后重新执行更新应该就行

**Comment by lostsnow** [comment]
级别显示为严重, 无法信任, 感觉是不是下载链接被劫持了? 我再从 github 单独下载安装试试

**Comment by lostsnow** [comment]
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/220461/4fcdabe2-0146-4473-8855-8d298546a648)

hash 一致

**Comment by Lightczx** [comment]
Defender描述的没啥问题，胡桃本来就很危险，信任与否看你自己

**Comment by lostsnow** [comment]
用很久了, 从 `Snap.Genshin` 一直用过来的, 因为以前没有遇到, 所以才比较奇怪是不是哪里碰到了 Defender 的 G 点导致误报之类的

**Comment by Masterain98** [comment]
![8d0964b1e66457a5e95f62e843334e72](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/32666413-23eb-4bf7-bb60-7fb98e692cbc)

我们已经向微软提交了报告，但具体能否解决，什么时候能解决是不清楚的。你可以尝试关闭 Windows Defender 中的云扫描，看能不能解决问题。

**Comment by Masterain98** [comment]
1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
