### ISSUE TITLE
[Feat]: 在鼠标悬浮时以浮窗的形式完整深境螺旋分期数据中怪物出场信息

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1505]
### 背景与动机

信息显示不完整
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/7c7317f7-c063-4ac2-9bd3-25d074418f08)

### 想要实现或优化的功能

在鼠标悬浮时，显示完整文本

或 

#863 可能也是解决方案之一，但就算实现估计在这种超长文本上效果也不好

**Comment by qhy040404** [comment]
Tracked by #1394
