### ISSUE TITLE
[Network]: HTTP | Error:SecureConnectionError : 元数据校验文件下载失败

### ISSUE THREAD

**Issue by 2376041387** [DGP-Studio/Snap.Hutao#1506]
### 提交你的网络诊断报告

网络环境：**辽宁大连** 中国移动和教育网双线 的校园网
问题：该地点多次出现“ HTTP | Error:SecureConnectionError : 元数据校验文件下载失败”的提示，伴有“状态：653366069”的三次提示。使用科学上网工具**全局代理**后软件正常（规则模式下不正常）。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52353624/86725c06-8e05-4bad-9ebf-aa29374fdab5)

### 你的地理位置

辽宁

### 你的运营商

中国移动

### 你的问题

完全无法连接服务器

### 网络诊断工具闪退

**问题描述**：首先说句抱歉，我实在无法上传“包含网络诊断报告的加密压缩包”，因为从[GitHub]和[极狐 GitLab]下载的“SH-Network-Diagnosis_2”在正常模式和管理员模式下均无法正常生成网络报告，现象为显示部分内容后自动闪退，检查软件所在文件夹亦无新增文件。

以下为**闪退前**显示的内容：

网络诊断工具版本： 1.1.0.0
本地时间: 2024-03-20 07:59:45
本机时区: ÖÐ¹ú±ê×¼Ê±¼ä

本地 DNS: 202.118.88.19

本地 DNS: 223.5.5.5

本地 DNS: 202.118.88.20

远程 DNS 判断: {'info': {'isp': '中国移动'}, 'status': {'code': '1', 'created_at': '', 'message': 'success'}}

当前 IP：39.152.151.*  来自于：中国 辽宁 大连  移动

DoH Error: illegal base64 data at input byte 0

Starting traceroute test for autopatchcn.yuanshen.com...
Starting traceroute test for jihulab.com...
Starting traceroute test for sdk-os-static.mihoyo.com...
Starting traceroute test for github.com...
Starting traceroute test for autopatchhk.yuanshen.com...
Starting traceroute test for hut.ao...
Starting traceroute test for enka-api.hut.ao...
Starting traceroute test for homa.snapgenshin.com...
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52353624/e7e56972-8851-492e-af2f-7864a3bc64d3)

### 最后一步

- [ ] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by qhy040404** [comment]
cmd运行`tracert api.snapgenshin.com`

**Comment by Masterain98** [comment]
感觉是代理在使用规则时，没有清除旧的routing规则导致的问题

**Comment by Masterain98** [comment]
网络诊断工具修好了 -> https://github.com/Masterain98/network-diagnosis-tool/releases/tag/1.1.1.0

**Comment by 2376041387** [comment]
补充：已使用新版网络诊断工具并获得压缩包，压缩包在附件中。
[SH-Report-076109e0-ec15-44da-8c51-24cf0e0abd00.zip](https://github.com/DGP-Studio/Snap.Hutao/files/14665569/SH-Report-076109e0-ec15-44da-8c51-24cf0e0abd00.zip)

**Comment by Masterain98** [comment]
在连接到胡桃通用API api.snapgenshin.com 在国内的节点时，你的网络连接在经过运营商内网时100%掉包（tracert 第二跳就失败了）。移动全责，你需要找运营商报修网络，问题来源在运营商系统内部。

在维修完成之前，你可以通过诸如 https://www.itdog.cn/ping/api.snapgenshin.com 这样的工具，寻找其它的节点，通过ping命令看哪个节点你能连上，之后通过 hosts 文件将解析暂时地改过去。需要注意的是，这只是一个临时的解决方案，因为节点IP可能会变更。
