### ISSUE TITLE
[Bug]: Hutao 启动游戏反馈

### ISSUE THREAD

**Issue by tangtangebusi** [DGP-Studio/Snap.Hutao#151]
### Windows 版本

22621.755

### Snap Hutao 版本

1.1.15.0

### 发生了什么？

以下均为管理员模式运行
1、无边框功能不能正常运行
2、关闭全屏设置分辨率后会以1920*1080的分辨率全屏运行
3、Unlock frame rate limit 未运行
4、启动游戏后设置的启动参数仅 Unlock frame rate limit 数值保存了

### 你期望发生的行为？

修复bug

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
fixed
