### ISSUE TITLE
养成计划优化

### ISSUE THREAD

**Issue by jingyxtxdy** [DGP-Studio/Snap.Hutao#1512]
### 背景与动机

目前的养成计划和我的角色以及填写背包物品的数据关联并不是实时的

### 想要实现或优化的功能

希望更新我的角色数据后能够同时更新养成计划中角色技能的等级以及武器数据
在填写背包物品数据后可以看到每种物品差多少个

**Comment by Lightczx** [comment]
> 希望更新我的角色数据后能够同时更新养成计划中角色技能的等级以及武器数据

你始终需要自行添加到养成计划，同一角色/武器重复添加视为更新

> 在填写背包物品数据后可以看到每种物品差多少个

在材料统计中已经可以查看
