### ISSUE TITLE
程序一打开就闪退

### ISSUE THREAD

**Issue by branden28** [DGP-Studio/Snap.Hutao#1514]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3155

### Snap Hutao 版本

闪退了看不到，是最新版本

### 设备 ID

01AEF742CADB9A94AD258171D41C50F2

### 问题分类

安装和环境

### 发生了什么？

安装第二天电脑启动后程序打开的一瞬间就闪退，只能一瞬间看到白屏。重新安装程序仍然这样，诊断工具显示404not found

### 你期望发生的行为？

如果可以加个qq远程看看比较好2251857903

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
删除Userdata.db后重试

**Comment by branden28** [comment]
没删除没重启他突然就能用了，下次再有问题我试试
