### ISSUE TITLE
[Bug]:无法更新1.9.9

### ISSUE THREAD

**Issue by ghh326** [DGP-Studio/Snap.Hutao#1521]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3374

### Snap Hutao 版本

1.9.8

### 设备 ID

33EC88E5C4ED0E57C70F93F539DB872B

### 问题分类

安装和环境

### 发生了什么？

通过工具箱推送的更新点击安装没有任何反应，重启之后依然没用，无法更新1.9.9

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
安装通常需要几十秒至几分钟时间，执行于后台，没有界面显示进度。
