### ISSUE TITLE
是否可以通过符号链接来实现更快速的不同区服启动

### ISSUE THREAD

**Issue by AbyssMorax** [DGP-Studio/Snap.Hutao#1524]
### 背景与动机

1. 通过对比目录结构差异和文件MD5，我发现StreamingAssets的主体文件在相同版本几乎无差别，也许可以牺牲一点空间来换取更快速的启动。
2. AssetBundles AudioAssets VideoAssets这三个文件夹几乎占了游戏文件的全部，所以可以只链接这三个文件夹，其他文件作为单独的工作目录，每次启动时可以直接运行主程序，只有第一次使用或者每个版本更新时需要释放并更新文件。
3. 这也许会占用额外的空间，但比起主体文件并不大，且更为快速。
4. 本人测试运行稳定，但可能下载扩展语音文件时，须在根目录下复制一份语音文件版本说明，来保证官方启动器更新时可以更新语音文件。

### 想要实现或优化的功能

是否可以通过将不同版本的差异文件放一个目录，然后共同文件通过符号链接（cmd：mklink /d）来实现一种更快速的方式启动，免去替换文件这一步骤。

**Comment by AbyssMorax** [comment]
注意：每个版本更新（包括游戏内小更新），需要给每个单独的工作区更新差异文件（如：*.blk），blk文件似乎时说明版本资源的，但每个小版本更新确实有差异

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/2fe9f935-140f-4539-a343-df186491f967)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/e3e8af68-f311-47d7-96e9-d9debc1a5fbc)

Assign to @Scighost

**Comment by qhy040404** [comment]
Tracked by #1394
