### ISSUE TITLE
在进行版本转换后打开原版客户端会导致胡桃工具箱和原版启动器无法识别原神资源

### ISSUE THREAD

**Issue by ymylive** [DGP-Studio/Snap.Hutao#1529]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2396

### Snap Hutao 版本

1.9.9.0

### 设备 ID

FA2D43951FFFF4149BB9BDF994657958

### 问题分类

安装和环境

### 发生了什么？

在进行版本转换后打开原版客户端会导致胡桃工具箱和原版启动器无法识别原神资源

### 你期望发生的行为？

可以对这种误操作加入一键修复功能，否则每次都要重新下载80G真的很烦

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
奇怪的问题，甚至看不懂你做了什么。

> 在进行版本转换后打开原版客户端会导致胡桃工具箱和原版启动器无法识别原神资源

1. **在进行版本转换后**，怎么还有可能打开**原版客户端**？
2. 胡桃工具箱无法识别？那你不是拿胡桃转换版本的？
3. 原版启动器无法识别，这是当然的，你都转换走了，还怎么识别？

**Comment by Masterain98** [comment]
另外，你误操作转换后，原版客户端不识别。你再自己转回去不就解决了？

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/e0aa3a6a-6d13-4a99-bf86-77b789be6814)

另外，我们的文档里也有手把手教程恢复因网络故障而导致游戏客户端无法被识别的解决方案。我不知道为什么你看不到。

**Comment by ymylive** [comment]
我的意思是在客户端实行转换后如果打开原神官方客户端会导致两方都无法识别原神资源，而导致无法启动，我已经重新下过两次了
发自我的 iPhone

在 2024年4月2日，15:28，Masterain ***@***.***> 写道：

﻿

image.png (view on web)<https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/e0aa3a6a-6d13-4a99-bf86-77b789be6814>

另外，我们的文档里也有手把手教程恢复因网络故障而导致游戏客户端无法被识别的解决方案。我不知道为什么你看不到。

**Comment by Lightczx** [comment]
> 我的意思是在客户端实行转换后如果打开原神官方客户端

你是如何在转换后打开原神客户端的

**Comment by ymylive** [comment]
打开原神官方启动器，并发现启动器显示无游戏，需重新获取资源，转回胡桃启动器，发现胡桃启动器无法识别config文件，
发自我的 iPhone

在 2024年4月2日，15:54，DismissedLight ***@***.***> 写道：

﻿

我的意思是在客户端实行转换后如果打开原神官方客户端

你是如何在转换后打开原神客户端的

**Comment by Masterain98** [comment]
测试了一下，确实有这个问题，但这个问题是原神官方启动器的逻辑，你只能遵守。
---
**发生了什么：**

当转换服务器版本后，你本地游戏中的 `config.ini` 配置文件会被修改以适配当前转换的服务器。这个配置文件，是官方服务器和胡桃用来判断当前游戏客户端的重要依据。此时，打开前一版本的官方启动器，它会识别到一个错误配置文件，故删除这个配置文件，并且让你重新下载游戏。而由于配置文件被删除，胡桃也无法判断当前的游戏版本。

---
**所以你应该做什么：**

1. 按照软件应该使用的方法去使用。如果手动转换了服务器，不要打开官方启动器，直接再转换回去。
2. 如果已经发生了问题该怎么办？多看文档，把 config 文件自己写一份塞回去。你的情况下，你应该塞转换后版本。只要让胡桃识别到了正常的配置文件，那就可以重新再开始转换。

无论如何都是可以不用重新下载游戏的，不知道为什么你会采取那种解决方式。我是不知道为什么一个需要下拉菜单才能进行操作的选项会频繁出现误操作的情况的。

**Comment by ymylive** [comment]
好的谢谢
发自我的 iPhone

在 2024年4月2日，16:10，Masterain ***@***.***> 写道：

﻿

测试了一下，确实有这个问题，但这个问题是原神官方启动器的逻辑，你只能遵守。

________________________________

发生了什么：

当转换服务器版本后，你本地游戏中的 config.ini 配置文件会被修改以适配当前转换的服务器。这个配置文件，是官方服务器和胡桃用来判断当前游戏客户端的重要依据。此时，打开前一版本的官方启动器，它会识别到一个错误配置文件，故删除这个配置文件，并且让你重新下载游戏。而由于配置文件被删除，胡桃也无法判断当前的游戏版本。

________________________________

所以你应该做什么：

  1.  按照软件应该使用的方法去使用。如果手动转换了服务器，不要打开官方启动器，直接再转换回去。
  2.  如果已经发生了问题该怎么办？多看文档，把 config 文件自己写一份塞回去。你的情况下，你应该塞转换后版本。只要让胡桃识别到了正常的配置文件，那就可以重新再开始转换。

无论如何都是可以不用重新下载游戏的，不知道为什么你会采取那种解决方式。我是不知道为什么一个需要下拉菜单才能进行操作的选项会频繁出现误操作的情况的。

**Comment by ymylive** [comment]
可以再请问一个问题吗，为什么会卡在package version获取界面，一直不成功，以前可以
发自我的 iPhone

在 2024年4月2日，16:10，Masterain ***@***.***> 写道：

﻿

测试了一下，确实有这个问题，但这个问题是原神官方启动器的逻辑，你只能遵守。

________________________________

发生了什么：

当转换服务器版本后，你本地游戏中的 config.ini 配置文件会被修改以适配当前转换的服务器。这个配置文件，是官方服务器和胡桃用来判断当前游戏客户端的重要依据。此时，打开前一版本的官方启动器，它会识别到一个错误配置文件，故删除这个配置文件，并且让你重新下载游戏。而由于配置文件被删除，胡桃也无法判断当前的游戏版本。

________________________________

所以你应该做什么：

  1.  按照软件应该使用的方法去使用。如果手动转换了服务器，不要打开官方启动器，直接再转换回去。
  2.  如果已经发生了问题该怎么办？多看文档，把 config 文件自己写一份塞回去。你的情况下，你应该塞转换后版本。只要让胡桃识别到了正常的配置文件，那就可以重新再开始转换。

无论如何都是可以不用重新下载游戏的，不知道为什么你会采取那种解决方式。我是不知道为什么一个需要下拉菜单才能进行操作的选项会频繁出现误操作的情况的。

**Comment by Lightczx** [comment]
你网炸了

**Comment by ymylive** [comment]
？我这里一切正常，我等会看看是不是dns问题
发自我的 iPhone

在 2024年4月2日，17:25，DismissedLight ***@***.***> 写道：

﻿

你网炸了

**Comment by ymylive** [comment]
我这里一切正常，我待会检查一下dns
发自我的 iPhone

在 2024年4月2日，17:25，DismissedLight ***@***.***> 写道：

﻿

你网炸了

**Comment by Masterain98** [comment]
可能只是短时间的网络波动造成的连接丢失
