### ISSUE TITLE
[Bug]: 打开WIKI栏中的角色资料时出现大量报错

### ISSUE THREAD

**Issue by Fillair19** [DGP-Studio/Snap.Hutao#153]
### Windows 版本

21H2

### Snap Hutao 版本

1.1.16.0

### 发生了什么？

打开WIKI栏中的角色资料时出现大量报错，标题为**HttpRequestException**
我不知道如何在github反馈中添加图片，我使用了外链
[https://files.catbox.moe/5mjtbc.png](url)

P.S.现在的工具栏中的属性统计，不显示人物和武器的图片

### 你期望发生的行为？

应该不显示报错并正常显示角色资料，最好包含图片

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
等待一会再使用
