### ISSUE TITLE
游戏启动相关

### ISSUE THREAD

**Issue by ChrisBZG** [DGP-Studio/Snap.Hutao#1530]
### 背景与动机

启动器的启动链接绑死了文件名，导致不能选择自己希望的启动方式

### 想要实现或优化的功能

因为我用的是反和谐的启动器，文件名不是Yuanshen.exe，如果修改文件名让hutao绑定的话，会导致反和谐启动器无法正常使用。希望可以把hutao的启动链接绑定文件名的这一项给去掉，让需要的用户可以自由选择文件启动

**Comment by Lightczx** [comment]
我们不鼓励且不会支持此类行为
