### ISSUE TITLE
[Feat]: 集成洞天套装相关培养方案，助力玩家更方便地凑齐好感度套装

### ISSUE THREAD

**Issue by GoddessLuBoYan** [DGP-Studio/Snap.Hutao#1532]
### 背景与动机

很久没玩壶了，想把壶里面的好感赠礼拿到手，于是用Excel整理，希望将来能用上胡桃APP
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/38455509/c684e3b8-67aa-4238-bd80-e10f5e700078)

而米游社-观测枢-洞天一栏中，包含全部需要的信息，这功能肯定可以做。

### 想要实现或优化的功能

考虑到玩家群体可能有只要原石的、想用套装水仙力的、想套用现成摹本的、以及想自己DIY认真玩壶的，功能拆分如下：

1. 玩家可以指定任意数量/种类的套装和单件家具，然后APP像“养成计划”那样统计需要制作的家具数与需要的总材料数
2. 提供一个默认行为：默认每样有洞天赠礼的套装各做一个，其它的一个不做
3. 对套装/家具分类，分类标准为室内/室外，以及其它游戏内支持的分类，同时支持输入框搜索
4. （不确定是否可行）支持对接米游社的摹本，即在特性1中，玩家可以指定一个摹本，然后APP自动统计该摹本需要的家具数与总材料数

**Comment by GoddessLuBoYan** [comment]
经检查，本issue与#114 #217 重合了

**Comment by Lightczx** [comment]
Close as duplicated
