### ISSUE TITLE
[Bug]: 胡桃固定到任务栏打开就不是管理员模式了

### ISSUE THREAD

**Issue by Yoimiya-993** [DGP-Studio/Snap.Hutao#1533]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4170

### Snap Hutao 版本

1.9.9.0

### 问题分类

其它

### 发生了什么？

桌面快捷方式是管理员身份启动胡桃，打开后左上角有管理员，右上角有连点器快捷键且连点器可用
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52495231/d7271cb0-12d3-459a-914c-ab6991706249)
将胡桃固定到任务栏后，关闭胡桃
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52495231/14078a5b-9a5f-43d4-92c5-8cc1d5ead04b)
之后从任务栏单击打开的胡桃不是管理员模式，右上角连点器快捷键也不见了且连点器不可用
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52495231/e0716eb6-a094-421b-9205-4be4f4c80539)

### 你期望发生的行为？

希望从任务栏图标打开的胡桃和桌面管理员快捷方式打开的是一样的

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
- [ ] 我的问题是已完成的问题也不是一个别人已发布的重复的问题

**Comment by Masterain98** [comment]
预期内的情况
