### ISSUE TITLE
每日一图的图片下载

### ISSUE THREAD

**Issue by PlutoNi908** [DGP-Studio/Snap.Hutao#1534]
### 背景与动机

本人背景图片使用胡桃每日一图，遇见喜欢的图片的时候很想储存下来，之前使用寻空的时候可以将喜欢的背景图储存，可惜胡桃没有这一功能，希望开发组能够添加一下

### 想要实现或优化的功能

背景图片使用胡桃每日一图的时候，可以添加储存图片的按钮，或者给出图片的链接地址，这样遇到喜欢的图片就可以储存（就像寻空一样）

**Comment by Masterain98** [comment]
在设置中点击版权信息即可跳转到原始来源
