### ISSUE TITLE
[Bug]: 注册表登陆记录莫名消失

### ISSUE THREAD

**Issue by CoRinoo** [DGP-Studio/Snap.Hutao#1535]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3296

### Snap Hutao 版本

1.9.9.0

### 设备 ID

5881CAD4417FA0CE7F54485F1BC3C8A2

### 问题分类

游戏启动器

### 发生了什么？

存储于注册表的账号在登录时莫名消失，无法正常登录，在进入游戏界面弹出空白登录框。
且该问题已发生两次，发生时均有以下共同特征：
1、发生于1.9.9.0更新后，第一次甚至发生于我将工具箱刚更新至1.9.9.0最新版后。
2、发生时间均在凌晨时间
3、发生时我的电脑均连接着我的手机热点
4、我均在登录别人的账号，根据我与账号所有人的沟通。据悉，
第一次时，他在我登陆他的帐号前并未登录他自己的账号；
第二次时，他在我登陆他的帐号前曾上线过一次，即在我上一次登录他的账号到问题发生这次，我登陆他账号的时间区间段内。

对于该问题我做过重启软件，更新网络状态（即重连网络）
在提交issue前我曾想过是否是因为热点连接导致网络不稳定致使登陆失败。但是在1.9.8.0版本时，我在相同的手机热点连接下从未出现过相关的情况。所以我更倾向于认为这一问题是在更新后出现的特殊病症。
debug控制台在登陆时显示如下：
![图像_2024-04-04_235910761](https://github.com/DGP-Studio/Snap.Hutao/assets/166040466/5c617d88-437b-4e26-af41-4945917f3b61)
我不知道图片是否可以正常展示，所以在下面复制了相关信息：
Snap.Hutao. Service. Game.Launching.LaunchExecutionContext[0]info:Handler LaunchExecutionGameProcessExitHandler  end execution

### 你期望发生的行为？

希望相关开发人员可以发现问题所在。
如果不是bug，而是单纯的网络波动导致，我之后会尽量调整登陆时间，并优化网络环境。毕竟目前看来就我一个人出现这样的问题，在我看来也算是比较严峻的了。
如果是在更新后确实出现的问题，希望这个问题能尽快解决。
因为据我目前已知的情况，一个账号记录出问题，注册表上所有的账号都会出现登陆失效的问题。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
https://hut.ao/zh/features/game-launcher.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B8%B8%E6%88%8F%E7%99%BB%E5%BD%95%E7%8A%B6%E6%80%81%E4%BC%9A%E5%A4%B1%E6%95%88-%E5%AF%BC%E8%87%B4%E5%88%87%E6%8D%A2%E8%B4%A6%E5%8F%B7%E5%8A%9F%E8%83%BD%E6%97%A0%E6%95%88

**Comment by qhy040404** [comment]
注册表保存的账号登录信息与你的设备网络环境、设备参数是绑定的，与他人顶号无关。根据你的情况，我更倾向于你的网络环境不稳定。按照我的理解来说，注册表和城市是绑定的。如果你刚好刚从一个城市到了另一个城市，或者住在城市边界，那就可以解释通了。你使用的手机热点在连接基站时可能连接到了隔壁市的基站，不排除这个可能性。

**Comment by CoRinoo** [comment]
@qhy040404 谢谢，我明白您的意思了
