### ISSUE TITLE
[Feat]: 希望添加一个可以查看成就获取途径的功能

### ISSUE THREAD

**Issue by CLXiao-1029** [DGP-Studio/Snap.Hutao#1536]
### 背景与动机

我心悦来潮使用了成就管理模块，却发现只能看已完成和未完成。
对于未完成的成就来说，我希望通过软件可以直接获取成就的完成途径。

### 想要实现或优化的功能

希望在点击查看未完成的成就时，可以弹出个窗口或目标地址来告诉我这个成就该如何完成它！！！谢谢

**Comment by Masterain98** [comment]
当提供一个成就的名称的时候，该如何通过这个字串符获取到攻略？

**Comment by Masterain98** [comment]
@Lightczx 可以在合适的地方增加两个按钮，一个为 `在米游社搜索该成就`，一个为 `在 HoYoLAB 搜索该成就`

### 米游社 

`https://bbs.mihoyo.com/ys/strategy/search?keyword={quest_name}`

e.g.

https://bbs.mihoyo.com/ys/strategy/search?keyword=清爽枫达，畅饮世界

### HoYoLAB

`https://www.hoyolab.com/search?keyword={quest_name}`

e.g.

https://www.hoyolab.com/search?keyword=清爽枫达，畅饮世界

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/bff1c6d3-e482-4a82-a4c9-01d185921052)

**Comment by Lightczx** [comment]
`https://bbs.mihoyo.com/ys/strategy/search?keyword={0}`

**Comment by CLXiao-1029** [comment]
谢谢~看了提供的示例，基本满足需求。对于方案来讲更倾向于方案一，但是方案二的信息表现效果更好。

**Comment by qhy040404** [comment]
Tracked by #1394
