### ISSUE TITLE
[Feat]: 新增自定义启动程序支持

### ISSUE THREAD

**Issue by jiuyan64** [DGP-Studio/Snap.Hutao#1537]
### 背景与动机

一直用的第三方程序启动的原神，看了下好像只能设置游戏路径，不能自定义启动器的路径

### 想要实现或优化的功能

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/55679684/656fcfee-b8f7-4e77-bd2e-bd1e76c91ca4)
类似于这种，可以自己选择启动程序

**Comment by qhy040404** [comment]
Duplicate of #1530

我们不鼓励且不会支持此类行为
