### ISSUE TITLE
[Bug]: 启动游戏点击检测后，无法绑定uid

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#154]
### Windows 版本

22623.875

### Snap Hutao 版本

1.1.16.0

### 发生了什么？

启动游戏后，点击“检测”后新建账号，（偶尔还会不显示右边的三个图标，需要切换左边菜单或者切屏才行）点击绑定当前用户角色，提示“当前未选择角色”
左下角米游社账号与游戏账号一致
![image](https://user-images.githubusercontent.com/2825342/199440048-076bd2d4-3276-44ed-8ba2-f6425b91ca66.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
无法切换账号是已知的问题，会在下版本修复

**Comment by Lightczx** [comment]
绑定的是角色而不是你的账号，请选择账号下的角色
