### ISSUE TITLE
[Feat]: 养成计划体力预估——#323的简化版

### ISSUE THREAD

**Issue by GoddessLuBoYan** [DGP-Studio/Snap.Hutao#1540]
### 背景与动机

在#323 中， @FlandiaYingman 提出了对养成计划的体力预估，但由于考虑因素过多（诸如不同品质的掉落概率分布、三合一概率等），至今仍未实装。但实际刷取时，并不需要如此细致，只需要给出一个估计值即可，因此我们可以给出粗略的体力消耗预估。

希望本issue可以在讨论以后再归纳到roadmap #1394 中，而不是直接归纳/关闭。

### 想要实现或优化的功能

将养成计划中的材料按照（武器材料、天赋材料、boss材料、周本材料）进行分类，并分别计算体力消耗。
对于武器材料与天赋材料，只考虑1:3的比例换算，不考虑三合一时可能的材料节约。
摩拉、经验书、矿暂不参与计算。
由于养成计划中暂无圣遗物升级相关，圣遗物升级所需狗粮的刷取次数也暂不参与计算。

**计算公式**：
刷取所需体力数 = (待刷取的总材料数 / 每x体掉落的材料数).向上取整 * x
例：角色刷取46个boss材料所需体力数 = math.ceil(46 / 2.5) * 40 = math.ceil(18.4) * 40 = 19 * 40 = 760

**计算标准**：
这里只考虑最高世界等级（世界等级8）的计算标准。
计算标准如下：
武器材料
天赋：视为平均每20体掉落1个紫的
武器材料：视为平均每20体掉落2个紫的（记不清了，可以以原帖中的google文档为准，取一个差不多的中间值）
boss材料：视为平均每40体掉落2.5个。
周本材料：视为平均每30体掉落2个，每周只打3把。

**Comment by Lightczx** [comment]
实际上我们计划实现的体力预估就是类似的，按掉落比例与合成关系推算。
