### ISSUE TITLE
无法切换国际服 显示一串代码 看不懂

### ISSUE THREAD

**Issue by TUITUIJIANG** [DGP-Studio/Snap.Hutao#1544]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

19045.4170

### Snap Hutao Version

1.9.9.0

### Device ID

C6540EA31EFC3F804AE9AB3BD528491F

### Issue Category

Game Launcher

### What Happened?

![QQ截图20240411150747](https://github.com/DGP-Studio/Snap.Hutao/assets/166692932/69d6c951-810b-43a9-a11a-27fae7f2cbb1)
切换国际服报错 但能切换b服和官服 不知道解决办法
另外 之前在切换国际服时会卡在重命名文件夹那一步 直接一直读条 无止境 最后无奈关闭之后 启动的是转换后的服务器 国际服
但想再切回官服和b服时 会发生错误 具体是什么忘了 无奈的重新下载

### What is expected?

能自由切换服务器

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
@TUITUIJIANG 在胡桃设置中打开控制台后重试，并发送控制台截图

**Comment by Lightczx** [comment]
closing for no response
