### ISSUE TITLE
[use case]: 桌面图标启动时默认使用管理员身份运行

### ISSUE THREAD

**Issue by kazetyan** [DGP-Studio/Snap.Hutao#1547]
## 背景
从开始菜单拖过来的快解方式不能以管理员身份运行
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/758772de-76bd-48c1-b397-57e55eb893ee)

找了一圈解决办法说是可能是系统问题，要安装原装系统，试错成本太高，于是采用了另一种办法，快捷方式运行shell命令启动应用。

## 1.桌面新建快捷方式
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/46fb9d13-1abe-4cf3-b9a6-ded01c060d50)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/6ae860bd-3661-4705-a5dd-a94ef9917fa8)

## 2.输入命令
`PowerShell -WindowStyle Hidden -Command "Start-Process shell:AppsFolder\xxx!App -verb runas"` 
> 需要替换xxx为实际的路径

### 2.1如何找到实际路径
运行hutao，打开任务管理器，找到hutao主任务，展开，右键子任务，选择打开文件所在的位置
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/457f9546-ff13-4587-b91b-cce44f4c74dc)
所在的文件夹去掉版本号和后面的两个下划线就得到了我们需要的xxx
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/60da7259-ee9c-42a1-a318-4d31fb4b7dc2)
`60568DGPStudio.SnapHutao_wbnnev551gwxy` 
替换第二步命令里的xxx得到
```sell
PowerShell -WindowStyle Hidden -Command "Start-Process shell:AppsFolder\60568DGPStudio.SnapHutao_wbnnev551gwxy!App -verb runas"
```
然后粘贴进创建快捷方式窗口里的输入框然后点击下一步
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/33023e10-d302-4ea7-9284-6affac76e05e)

### 2.2更改名称
按需更改名称
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/61064c93-51c4-4bdf-bf50-d441e66ced36)
点击完成，我们就得到了一个管理员运行hutao的shell快捷方式
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/e05e82b6-4832-4459-9ea5-e99dc41f73ed)

## 3.更改图标以及设置最小化启动
默认是powershell的图标，以及启动时会弹出一个powershell窗口，下面我们可以进行一点点改动优化这两点

### 3.1更改图标
右键快捷方式，打开属性
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/ba375c81-aaa3-4ea3-be62-9581b5cda087)
打开更改图标，默认是powershell的图标
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/0d8e31b9-7c02-44ad-938f-2545ddab84e3)
点击浏览后将2.1里hutao所在的路径复制到顶部的路径栏后回车
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/fc84b70f-2cc1-4565-9c86-9520d95572e1)
找到`Snap.Hutao.exe` ，双击
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/ca0bcad8-ad19-4068-949f-ce73ac1cd325)
选择图标点击确定
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/4c75ca50-74a9-4845-83f0-14bb5e543ba5)

### 3.2运行方式设置为最小化
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/937c166a-9540-4908-a75a-4e6e76f612ac)

## 4.完成
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/d7e16b3e-1d2b-43c0-81d0-eefe3c921377)
双击运行后就是管理员模式的hutao了
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/61b3fd0c-abfc-420a-992c-3be6705bf512)

**Comment by qhy040404** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/63443465-e006-4a1c-bdac-0f047d084e59)
？

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/6c38ed3f-e9cc-47e2-92a0-e544162a57ef)

**Comment by kazetyan** [comment]
尴尬了，没注意这里😂。文档里贴个图吧，从issue里找过去的一时间没看懂。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/50894526/4b81653f-251f-4554-b87d-c60f58fadf94)

**Comment by Lightczx** [comment]
@Masterain98 Seems like it's a doc request

**Comment by Masterain98** [comment]
> @Masterain98 Seems like it's a doc request

我觉得我写的没问题

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/5dd4ec27-4cd4-4d83-b29a-4c56cd464473)

**Comment by kazetyan** [comment]
> > @Masterain98 Seems like it's a doc request
> 
> 我觉得我写的没问题
> 
肯定是没问题的，只是贴个图会更直观一些😄
