### ISSUE TITLE
请求添加任务栏和开始菜单默认以管理员身份运行

### ISSUE THREAD

**Issue by ZhuFengDream** [DGP-Studio/Snap.Hutao#1558]
### 背景与动机

对于喜欢使用任务栏和开始菜单启动胡桃工具箱的人来说并不方便

### 想要实现或优化的功能

是否可以添加Windows任务栏和开始菜单默认以管理员身份运行胡桃工具箱

**Comment by Masterain98** [comment]
可以自行创建 PowerShell 快捷方式

`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Start-Process shell:AppsFolder\60568DGPStudio.SnapHutao_wbnnev551gwxy!App -verb runas"`

**Comment by ZhuFengDream** [comment]
> 可以自行创建 PowerShell 快捷方式
> 
> `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Start-Process shell:AppsFolder\60568DGPStudio.SnapHutao_wbnnev551gwxy!App -verb runas"`

多谢，不过还是建议在胡桃工具箱内添加在 开始菜单和任务栏 添加默认以管理员方式运行的按钮

**Comment by Masterain98** [comment]
> 多谢，不过还是建议在胡桃工具箱内添加在 开始菜单和任务栏 添加默认以管理员方式运行的按钮

这种方式有1.5个弊端：
1. 这是一个 PS 快捷方式，在任务栏右键不会有 Snap Hutao 原生的快捷菜单，而是 PS 的功能菜单
2. 一部分用户因为使用精简版系统，导致系统中居然没有 PS，进而导致无法使用该方法生成的快捷方式。这类用户不在少数，出了问题都会来问，很烦；这也是为什么换成了当前的快捷方式生成的方式。

**Comment by ZhuFengDream** [comment]
> > 多谢，不过还是建议在胡桃工具箱内添加在 开始菜单和任务栏 添加默认以管理员方式运行的按钮
> 
> 这种方式有1.5个弊端：
> 
> 1. 这是一个 PS 快捷方式，在任务栏右键不会有 Snap Hutao 原生的快捷菜单，而是 PS 的功能菜单
> 2. **一部分用户因为使用精简版系统，导致系统中居然没有 PS，进而导致无法使用该方法生成的快捷方式。这类用户不在少数，出了问题都会来问，很烦；这也是为什么换成了当前的快捷方式生成的方式。**

彳亍，感谢解答
