### ISSUE TITLE
[Network]: 初始化的资源无法完成下载

### ISSUE THREAD

**Issue by chccccwx** [DGP-Studio/Snap.Hutao#1559]
### 提交你的网络诊断报告

[SH-Report-c6db37e2-70a6-440c-8379-9cd6ea0b62d7.zip](https://github.com/DGP-Studio/Snap.Hutao/files/15047184/SH-Report-c6db37e2-70a6-440c-8379-9cd6ea0b62d7.zip)

### 你的地理位置

广东

### 你的运营商

中国电信

### 你的问题

连接速度慢

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Masterain98** [comment]
已切换线路

**Comment by chccccwx** [comment]
辛苦了 效率真高！给你们项目组点赞！！！
