### ISSUE TITLE
[Bug]: 无法通过登录米哈游通行证升级Stoken

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#156]
### Windows 版本

19044.2130

### Snap Hutao 版本

1.1.16

### 发生了什么？

1. 通过输入 Cookie 登录了米游社帐号
2. 尝试在胡桃内登录米哈游帐号管理已升级 Stoken
3. 点击`我已登录`后没有任何反应，胡桃中的帐号亦没有 `Stoken`标记
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9918883/Log.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
fixed internally
