### ISSUE TITLE
[Bug]: 账号验证失败 错误码12-4301

### ISSUE THREAD

**Issue by GoogleGAT** [DGP-Studio/Snap.Hutao#1564]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4291

### Snap Hutao 版本

1.9.9.0

### 设备 ID

31B6978AB9A69511D575B7DBF9D22C7B

### 问题分类

游戏启动器

### 发生了什么？

搬台式电脑换了一个省之后，在胡桃工具箱中选择另一个账号（这里称为账号2）登录出现“账号验证失败 错误码12-4301”，具体表现为：选择账号2启动游戏，自动打开原神，出现大门，点击进入游戏开门屏幕全白后，弹出“账号验证失败 错误码12-4301”，然后重新加载出现扫码登录界面。
试过扫码或输入账号密码登录都是正常可以进入可以玩的，就是从胡桃工具箱中启动账号2不行，账号1却可以。
尝试过在胡桃工具箱中选择删除账号2删除再添加，或者是更新cookie，还行不行。

### 你期望发生的行为？

正常情况应该是在胡桃工具箱中选择账号2启动游戏，自动打开原神，出现大门，点击进入游戏，成功进入游戏。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
> 试过扫码或输入账号密码登录都是正常可以进入可以玩的，就是从胡桃工具箱中启动账号2不行，账号1却可以。
> 尝试过在胡桃工具箱中选择删除账号2删除再添加，或者是更新cookie，还行不行。

在确保重启原神后也无需重新输入账号密码即可进入游戏的情况下，重新保存新的账号。
如果你在扫码登录/输入账密后立即保存账号，此时是不一定能够长期保存的
