### ISSUE TITLE
[Network]: cl-f3485468.gcdn.co域名访问异常

### ISSUE THREAD

**Issue by lunzima** [DGP-Studio/Snap.Hutao#1565]
### 提交你的网络诊断报告

[SH-Report-1fbb5e74-10e3-44fe-820d-8879a96f794f.zip](https://github.com/DGP-Studio/Snap.Hutao/files/15058594/SH-Report-1fbb5e74-10e3-44fe-820d-8879a96f794f.zip)

### 你的地理位置

上海

### 你的运营商

中国电信/中国联通/Hong Kong HGC
![QQ截图20240422145044](https://github.com/DGP-Studio/Snap.Hutao/assets/32062239/11b0d229-6690-4e4f-8e2c-8852bb2f4cc8)

### 你的问题

完全无法连接服务器

### 你的问题（补充）

仅限于 cl-f3485468.gcdn.co 域名

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by lunzima** [comment]
排查发现使用4G上网卡可以正常访问cl-f3485468.gcdn.co域名，怀疑上层有什么限制

**Comment by lunzima** [comment]
联系网管查看防火墙日志发现命中了“恶意软件”条目
![QQ截图20240422145828](https://github.com/DGP-Studio/Snap.Hutao/assets/32062239/a29d38d1-111a-4be9-970f-8707092648f6)
暂时将其拉白了。cl-f3485468.gcdn.co该域名的解析结果是固定的么？

**Comment by Masterain98** [comment]
在 cmd 中运行
```
nslookup api.snapgenshin.com 223.5.5.5
nslookup api.snapgenshin.com 114.114.114.114
```

把输出的结果截图发一下

**Comment by Masterain98** [comment]
> 公司的防火墙设备上做了静态路由接入了三家运营商

所以是三个网络轮询吗？

**Comment by lunzima** [comment]
> > 公司的防火墙设备上做了静态路由接入了三家运营商
> 
> 所以是三个网络轮询吗？

大致上是根据运营商路由表分流，个别协议如STUN特殊处理

**Comment by Masterain98** [comment]
胡桃软件支持的 API 做了中国大陆内外的不同 DNS 解析，海外地区的 CDN 服务商 G-Core 不仅在国内是被墙的状态，而且看上去还被你们公司的 IT 给拦截了（讲道理这个黑名单范围太大了，我个人认为拉黑一个 CDN 运营商是一个离谱的偷懒行为）。

解决方法：保证 `api.snapgenshin.com` 访问的是国内路由

**Comment by lunzima** [comment]
> 胡桃软件支持的 API 做了中国大陆内外的不同 DNS 解析，海外地区的 CDN 服务商 GCore 不仅在国内是被墙的状态，而且看上去还被你们公司的 IT 给拦截了（讲道理这个黑名单范围太大了，我个人认为拉黑一个 CDN 运营商是一个离谱的偷懒行为）。
> 
> 解决方法：保证 `api.snapgenshin.com` 访问的是国内路由

公司的网络可以正常访问https://hosting.gcore.com/billmgr，因此可能不是针对整个ASN进行的屏蔽
Anyway，除了拉白IP 81.28.12.12以外，让公司网管去调整snapgenshin.com域名解析结果了。

**Comment by Masterain98** [comment]
> Anyway，除了拉白IP 81.28.12.12以外，让公司网管去调整snapgenshin.com域名解析结果了。

确实有可能是这种 Anycast CDN IP 出现频率高导致单独 IP 被拉黑

**Comment by lunzima** [comment]
> > Anyway，除了拉白IP 81.28.12.12以外，让公司网管去调整snapgenshin.com域名解析结果了。
> 
> 确实有可能是这种 Anycast CDN IP 出现频率高导致单独 IP 被拉黑

软件内提供一个手动选择cdn区域的开关也许可行？
