### ISSUE TITLE
[Feat]: 可不可以添加一个背包材料一键导入功能

### ISSUE THREAD

**Issue by asd85474401** [DGP-Studio/Snap.Hutao#1566]
### 背景与动机

我新建了一个养成计划，有很多的角色，同时也有很多的材料，可是我却无法知道我游戏背包里的材料与养成计划中到底差多少，如果要手动一个一个材料的填写非常非常麻烦QAQ

### 想要实现或优化的功能

建议增加一键导入背包材料的功能！！！

**Comment by BTMuli** [comment]
#1307 #915 #914 #571 #419 #404 #347

**Comment by BTMuli** [comment]
[Amenoma](https://github.com/daydreaming666/Amenoma)都多久没更新了，如果有其他的稳定维护的背包材料识别OCR工具倒是可以考虑。
