### ISSUE TITLE
[Bug]: 快速多次点击"我的角色"界面会导致启动器崩溃 Quick multiple clicks on the "My Character" interface can cause the launcher to crash.

### ISSUE THREAD

**Issue by Jaffrez** [DGP-Studio/Snap.Hutao#1569]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3155

### Snap Hutao 版本

1.9.9.0

### 设备 ID

4A09C45C660EC847B6641291BDC1E7F3

### 问题分类

我的角色

### 发生了什么？

在主界面左侧的菜单多次快速点击“我的角色”会导致启动器崩溃，经测试仅有此项菜单会导致崩溃。
Multiple quick clicks on "My Character" in the menu on the left side of the main interface can cause the launcher to crash. After testing, only this menu can cause a crash.

### 你期望发生的行为？

多次点击不应导致崩溃。
Multiple clicks should not cause a crash.

下列文件包括录屏以及事件查看器的报告。
The following files include screen recordings and reports from the Event Viewer.
[错误报告/Error report](https://github.com/DGP-Studio/Snap.Hutao/files/15087966/error.zip)
[录屏/Screen recording](https://github.com/DGP-Studio/Snap.Hutao/assets/117080567/f612558a-e94a-4e0c-a4d9-2f129873229e)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
Reliquary被极狐封了，正在修复

**Comment by Lightczx** [comment]
已修复
