### ISSUE TITLE
[Bug]: HuTao窗口全屏时，win10的隐藏任务栏无法正常显示

### ISSUE THREAD

**Issue by hxcgl** [DGP-Studio/Snap.Hutao#1571]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4291

### Snap Hutao 版本

1.9.9.0

### 设备 ID

8A77B9F3DACBF17C7E3793532A493019

### 问题分类

其它

### 发生了什么？

当HuTao启动器窗口全屏，win10隐藏任务栏功能开启时，将鼠标划至隐藏的任务栏位置无法呼出任务栏。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by hxcgl** [comment]
这是一个微不足道的bug，不管它也没什么影响

**Comment by Mikachu2333** [comment]
已复现

**Comment by Masterain98** [comment]
恭喜你发现了一个 winui 的 bug

懒狗 Microsoft

**Comment by hxcgl** [comment]
确实

**Comment by Lightczx** [comment]
https://github.com/dechamps/RudeWindowFixer

**Comment by hxcgl** [comment]
我运行了一下上面这个程序，但并没有解决这个问题。

**Comment by hxcgl** [comment]
我运行了一下上面这个程序，但并没有解决当前操作系统版本微软的这个问题。

**Comment by Lightczx** [comment]
当然不能解决，那个只是参考文献

**Comment by Lightczx** [comment]
@hxcgl https://github.com/DGP-Studio/Snap.Hutao/actions/runs/8873008145 试一下这个版本
