### ISSUE TITLE
[Feat]: 祈愿记录支持覆盖式更新

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1576]
### 背景与动机

https://github.com/DGP-Studio/Snap.Hutao/issues/1572#issuecomment-2077316819

胡桃目前对于祈愿记录的导入仅支持更新旧记录（数据库中不存在的记录），对于新纪录不支持更新且无提示——见 #1572 及 https://github.com/DGP-Studio/Snap.Hutao.Docs/issues/125

可以参考成就导入进行改进。

### 想要实现或优化的功能

rt，参考导入成就三种模式，在UIGF的UID相同情况下，支持更新旧数据/覆盖旧数据

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/dfb762de-f75c-424b-9ed2-6cb336e33e6f)

**Comment by Lightczx** [comment]
我们对祈愿记录的准确性相比成就有更高的要求，在设计导入系统时就已经确定了以服务器返回数据为主，较老的记录允许添加
由于总是能够从服务器获取到较新的准确数据，贪婪模式在这里并没有实现的必要。
如果仍试图导入较老的数据，可以在删除现有数据后从 UIGF json 导入

**Comment by Mikachu2333** [comment]
> 对于新纪录不支持更新且无提示

听完以后发现是可理解的，毕竟用户希望导入的数据确实是不可信的，尤其是可以从服务器直接拉取的情况下。

不过加个提示我支持，所以已经在计划修改胡桃的doc了
