### ISSUE TITLE
[Bug]: 打开剪贴板失败

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1577]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26090.112

### Snap Hutao 版本

1.9.9.0

### 设备 ID

FA47BE878C143D2FE18785B660EF114A

### 问题分类

其它

### 发生了什么？

打开旅行札记，点击生成分享图时，弹出“打开剪贴板失败”

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/e5112364-f2c5-4240-ae94-a97dab1e5368)

### 你期望发生的行为？

成功将截图复制到剪贴板

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
多试几次，正常现象
