### ISSUE TITLE
[Feat]: 单用户多角色情况下支持隐藏角色

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1578]
### 背景与动机

rt，希望隐藏已经退坑的角色

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/3c8b1d75-a831-43ee-871f-1053c9142ebc)

### 想要实现或优化的功能

1. 单用户多角色下支持隐藏角色（至少显示一个）
2. 支持查看&恢复已隐藏角色

**Comment by Lightczx** [comment]
现在已经会自动选中之前选中的角色，这个需求似乎没有必要了
