### ISSUE TITLE
[Feat]: 调整网页登录逻辑

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#1582]
### 背景与动机

https://github.com/UIGF-org/mihoyo-api-collect/issues/46

### 想要实现或优化的功能

适配新的返回数据

**Comment by gszshdzz** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/issues/47

**Comment by Lightczx** [comment]
网页登录已经被米哈游限制
