### ISSUE TITLE
[Bug]: 自动连点无法使用鼠标按键

### ISSUE THREAD

**Issue by srk24** [DGP-Studio/Snap.Hutao#1585]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3527

### Snap Hutao 版本

1.9.9.0

### 设备 ID

54D934766DD68BA9796A89D92457E4D4

### 问题分类

其它

### 发生了什么？

我想把快捷键设置成鼠标侧键，也就是 XB1/XB2，但是点击鼠标无法生效，设置成键盘按键是可行的。

测试鼠标：
雷蛇 V3PRO
罗技 GPXS

已经尝试过下述，依旧无法解决
1. 在修改后重启软件、游戏
2. 添加辅助按键比如 Alt + XB1
3. 设置为鼠标左键、右键、中键

### 你期望发生的行为？

期望可以设置鼠标按键为自动连点按键

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by srk24** [comment]
`System.IO.IOException: 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。`
 那我卸载重装试试吧

**Comment by Lightczx** [comment]
不支持鼠标侧键

**Comment by srk24** [comment]
> 不支持鼠标侧键

额，issue已经close了么？其他鼠标按键也不支持吗？比如ALT+鼠标左键。如果不支持为什么会在那个按键列表里面。

**Comment by Lightczx** [comment]
我很难向你解释，但是它只是恰好出现在那里，而且不太好屏蔽

**Comment by srk24** [comment]
了解了。多谢告知。
