### ISSUE TITLE
[Bug]: 界面图片显示异常

### ISSUE THREAD

**Issue by tgsqaq** [DGP-Studio/Snap.Hutao#1586]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.9.9.0

### 设备 ID

282975A9999A42E2CC46C43EEBC69393

### 问题分类

用户界面

### 发生了什么？

界面里面应该显示图片的地方全都没有显示

![Snipaste_2024-04-29_15-42-29](https://github.com/DGP-Studio/Snap.Hutao/assets/109848474/1459acff-1a7c-4ae6-9d4e-d58c861dc163)
![Snipaste_2024-04-29_15-42-51](https://github.com/DGP-Studio/Snap.Hutao/assets/109848474/683de8d9-bc49-4cdf-b8d2-7297f3489a64)
![Snipaste_2024-04-29_15-42-59](https://github.com/DGP-Studio/Snap.Hutao/assets/109848474/8d80a796-1090-461d-856f-4fc97ae11e8d)
![Snipaste_2024-04-29_15-43-08](https://github.com/DGP-Studio/Snap.Hutao/assets/109848474/01f93d22-d53d-4e2a-9edd-2be6e70fda68)

### 你期望发生的行为？

正常显示图片

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/7239fa9e-c136-436c-9e02-a8bc1314f96a)

**Comment by Lightczx** [comment]
设置里面重置一下图片资源

**Comment by tgsqaq** [comment]
thx，bros
