### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by rszeal** [DGP-Studio/Snap.Hutao#159]
### Windows 版本

22621,674

### Snap Hutao 版本

1.1.16.0

### 发生了什么？

打开提示：元数据校验文件下载失败 403（Forbidden）
无法显示祈愿记录，点击刷新后自动退出

### 你期望发生的行为？

正常

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
Issue标题
