### ISSUE TITLE
[Bug]: 从游戏内角色橱窗同步角色信息失败

### ISSUE THREAD

**Issue by abandonstudy** [DGP-Studio/Snap.Hutao#1594]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4291

### Snap Hutao 版本

1.10.1.0

### 设备 ID

BA90B3F79A384D58FF486920A934DCC4

### 问题分类

我的角色

### 发生了什么？

从游戏内角色橱窗同步角色信息失败
提示角色展柜未开启，请前往游戏操作后重试（这个号的角色展柜1年前就开了到现在都没变过，且提瓦特小助手能正常查询角色展柜的信息）
应该不是网络问题，hutao能正常上网，没开代理
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/d0c61958-00e7-4f94-9ebd-589374a3ec6d)

附出现问题的视频
https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/72a4ae8a-69d8-40c8-985f-17e98353d0a7
### 你期望发生的行为？

正常获取角色信息

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
该问题目前是否仍然存在？

**Comment by abandonstudy** [comment]
> 该问题目前是否仍然存在？

现在没问题了，谢谢你
