### ISSUE TITLE
[Network]:文件下载异常 - [HTTP"] [Error'SecureConnectionError']

### ISSUE THREAD

**Issue by AquaMT** [DGP-Studio/Snap.Hutao#1597]
### 提交你的网络诊断报告

[流量-河南移动.zip](https://github.com/DGP-Studio/Snap.Hutao/files/15187813/-.zip)
[流量-河南广电.zip](https://github.com/DGP-Studio/Snap.Hutao/files/15187819/-.zip)
[宽带-河南移动.zip](https://github.com/DGP-Studio/Snap.Hutao/files/15187820/-.zip)

### 你的地理位置

河南

### 你的运营商

中国移动

### 你的问题

客户端图片下载错误

### 你的问题（补充）

问题表现：某些资源可以下载，但速度很慢只有几百k/s，大多数都下载不了，如下图
![1](https://github.com/DGP-Studio/Snap.Hutao/assets/55498866/fb6f82c3-a05d-434e-9db5-fc7970aa94e6)

网络详情：
路由器openwrt，安装了passwall2分流，geosite:gfw模式
  直连dns走adguardhome，只添加了运营商dns
  代理dns走smartdns，添加的有googledns、opendns
试过passwall2中下图这两个选项，甚至关掉passwall2仅直连，问题依旧
![passwall2](https://github.com/DGP-Studio/Snap.Hutao/assets/55498866/cf9632e0-0941-4586-adcd-b379a096b47f)
随后禁用电脑自带网卡，手机关掉WLAN，使用流量，并通过usb共享网络的方式分享给pc，问题依旧。

使用代理开全局，可以正常下载资源，速度也正常，但是进主界面会报653366069，如下图
![全局](https://github.com/DGP-Studio/Snap.Hutao/assets/55498866/6a1ce8cc-07f0-45a0-860d-20b463b33465)

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Masterain98** [comment]
代理的问题，HTTPS握手失败

**Comment by AquaMT** [comment]
> 代理的问题，HTTPS握手失败

但是我不论关掉代理直连、还是用流量直连都是同样的问题诶……反而用v2rayN的windows客户端开全局、或者windows设置-代理连接路由器的http节点都可以正常下载

**Comment by Lightczx** [comment]
是代理的问题，没说不要用代理
