### ISSUE TITLE
[Bug]: 启动器无法启动游戏

### ISSUE THREAD

**Issue by luomi114514** [DGP-Studio/Snap.Hutao#1598]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26100.268

### Snap Hutao 版本

1.10.1.0

### 问题分类

游戏启动器

### 发生了什么？

在启动器切换服务器或启动游戏时，不会运行游戏，仅显示游戏进程运行中
![屏幕截图 2024-05-02 213255](https://github.com/DGP-Studio/Snap.Hutao/assets/125117292/130521bf-aace-4328-aee1-62f9816d6ba6)
![屏幕截图 2024-05-02 213405](https://github.com/DGP-Studio/Snap.Hutao/assets/125117292/a429ff05-1e4f-4935-aaf2-9276fecd0b8f)

### 你期望发生的行为？

以前有过，一段时间就没有，现在又有，能不能把这个问题给快点解决

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你自己不退出管我们什么事

**Comment by luomi114514** [comment]
> 你自己不退出管我们什么事

没有运行游戏，然后用启动器启动游戏就这样

**Comment by qhy040404** [comment]
为什么不在任务管理器里检查检查呢
Yuanshen.exe或者GenshinImpact.exe

**Comment by BTMuli** [comment]
**在胡桃工具箱的反馈中心界面，你可以找到并复制你的设备 ID
如果你的问题涉及程序崩溃，请填写该项，这将有助于我们定位问题**

**Comment by luomi114514** [comment]
> 为什么不在任务管理器里检查检查呢 Yuanshen.exe或者GenshinImpact.exe

在任务管理器检查后，并没有发现你说的这两个程序

**Comment by qhy040404** [comment]
在设置里打开调试控制台，在出现游戏进程运行中后，发下控制台的截图

**Comment by luomi114514** [comment]
> 在设置里打开调试控制台，在出现游戏进程运行中后，发下控制台的截图

![屏幕截图 2024-05-03 080805](https://github.com/DGP-Studio/Snap.Hutao/assets/125117292/61c9c375-36b3-495d-aa4e-11cec4d364c7)
之前有反馈过这个问题，但没有解决，现在又是这样，它能启动游戏了，之后可能又启动不了

**Comment by Lightczx** [comment]
系统问题
