### ISSUE TITLE
[Bug]: 米游社的我已登录点击失效

### ISSUE THREAD

**Issue by BShirasawa** [DGP-Studio/Snap.Hutao#1600]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3447

### Snap Hutao 版本

1.10.1.0

### 设备 ID

537E431806A3A3582267EB423C0C583B

### 问题分类

米游社账号面板

### 发生了什么？

米游社登录成功，但是点击上方的我已登录不好使，无法记录账号

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
由于米哈游的变更，网页登录暂时不可用

**Comment by BTMuli** [comment]
#1582
