### ISSUE TITLE
[Bug]: 无法更新

### ISSUE THREAD

**Issue by SmaragdineTablet** [DGP-Studio/Snap.Hutao#1601]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows 11 专业版 23H2 22631.3527

### Snap Hutao 版本

1.9.9.0

### 设备 ID

CC3C72302E919528D002A33814BCD35A

### 问题分类

安装和环境

### 发生了什么？

无法从当前版本更新至新版本

https://github.com/DGP-Studio/Snap.Hutao/assets/142521705/8aaa951f-1a89-447b-b90b-a20acad47292

### 你期望发生的行为？

更新

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你关的太快了，后台仍未完成安装，虽然新版本已经有了安装进度反馈，但是旧版本是没有的

**Comment by SmaragdineTablet** [comment]
演示视频没录长，实际在其它次尝试的时候等过好一会儿，没有效果，当然也已经不用了，下了最新的安装包覆盖更新了

**Comment by Lightczx** [comment]
Win10的话安装30分钟都是正常的
