### ISSUE TITLE
关于胡桃的成就系统我有一个建议

### ISSUE THREAD

**Issue by hchdjjsjsjcjs123** [DGP-Studio/Snap.Hutao#1602]
### 背景与动机

我在从0开始重新勾选已完成的成就时感觉太麻烦，在有那么多的成就情况下，只能一个一个勾选，很麻烦

### 想要实现或优化的功能

我的建议时是在成就的每个部分加上一个全选的按钮，这样在我们完成这个板块的成就时就可以不用再来一个一个点，就可以直接一键全选

**Comment by Masterain98** [comment]
https://github.com/HolographicHat/YaeAchievement
