### ISSUE TITLE
[ENG][Bug]: Refreshing Wish History with Web Cache provides wish history from a different account and server

### ISSUE THREAD

**Issue by nikivan2002** [DGP-Studio/Snap.Hutao#1605]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

22H2

### Snap Hutao Version

1.10.1.0

### Issue Category

Wish Export

### What Happened?

Previously all of my wishes were imported from a UIGF file and accurate. The first time I tried Refreshing with Web Cache in 1.10.1, instead of taking the wish history from my current open account on the Europe server, it took the wish history from a different account (which I have opened the previous day) on the Asia server. I have restarted Genshin since opening the Asia account.

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
1. Close the game
2. In Hutao: delete the web cache in settings page
3. Launch the game, open the wish history web page
4. In Hutao: refresh by web cache
