### ISSUE TITLE
养成计划 物品背包筛选用到的物品

### ISSUE THREAD

**Issue by anarnwa** [DGP-Studio/Snap.Hutao#1612]
### 背景与动机

在 材料清单-养成物品 下，可以针对角色的养成物品进行勾选标记，但是如果添加了多个角色，使用同一个物品的情况下，翻找起来很麻烦，希望可以在  材料清单-材料统计 功能下添加类似于角色养成物品收集完成的标记功能。

### 想要实现或优化的功能

希望 养成计划--材料清单-材料统计 面板中，可以针对材料进行勾选标记/填写数量，而不需要再进入养成计划-背包物品去填写材料数量

**Comment by Lightczx** [comment]
材料统计页面是一个只读视图，是不可能编辑的

**Comment by anarnwa** [comment]
简单来说就是觉得背包材料这一栏，是与当前养成计划相关的，但是有很多材料是我养成计划中压根用不上的，我不关心那些用不上的材料数量到底有多少个，如果是在背包材料这一栏筛选呢？ 只显示我当前养成计划中用得上的材料

**Comment by Lightczx** [comment]
> 简单来说就是觉得背包材料这一栏，是与当前养成计划相关的，但是有很多材料是我养成计划中压根用不上的，我不关心那些用不上的材料数量到底有多少个，如果是在背包材料这一栏筛选呢？ 只显示我当前养成计划中用得上的材料

这是可以的

**Comment by BTMuli** [comment]
~~https://github.com/DGP-Studio/Snap.Hutao/issues/1606#issuecomment-2097763614~~

**Comment by qhy040404** [comment]
#1651 现在可以直接刷新背包物品了
