### ISSUE TITLE
[Bug]: 无法不通过管理员模式启动

### ISSUE THREAD

**Issue by goblock2021** [DGP-Studio/Snap.Hutao#1614]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3447

### Snap Hutao 版本

1.10.1.0

### 问题分类

实时便笺

### 发生了什么？

我希望工具箱能够自动刷新体力，但是我没有找到不通过管理员模式进入的入口
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/114788565/99d96115-4681-4fbc-b6e2-fcb779a315cf)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by goblock2021** [comment]
看了一下，为啥都是反馈的不能以管理员身份运行，我打开直接就是管理员模式都找不到地方关掉啊...

**Comment by BTMuli** [comment]
请按如下步骤查看当前UAC状况：

控制面板---系统和安全---安全和维护---更改用户账户控制设置

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/01667873-d6e4-4467-82e4-e4f00e89ddc6)

任务栏搜索 `Snap.Hutao` ，右键菜单 `固定到开始屏幕` 与 `固定到任务栏` 会将 **非管理员模式** 的打开方式固定到任务栏

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72692909/90a1b843-4fea-4e90-92fe-d1972c7fadee)

> 看了一下，为啥都是反馈的不能以管理员身份运行，我打开直接就是管理员模式都找不到地方关掉啊...

一般而言都是非管理模式打开的，然后非管理员模式→管理员模式，直接打开就是管理员可能是因为快捷方式生成是默认管理员的，采取上述方式可以生成正常（非管理员）的快捷方式。

**Comment by goblock2021** [comment]
之前已经试过了，无论在哪里创建快捷方式都是管理员模式启动，尝试过直接从开始菜单搜索启动，拖到桌面，固定到开始菜单，固定到任务栏均无效。

经检查确实是UAC设置问题，更改UAC设置并重启后正常了。
