### ISSUE TITLE
[Bug]: 修改计划任务失败

### ISSUE THREAD

**Issue by goblock2021** [DGP-Studio/Snap.Hutao#1618]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3447

### Snap Hutao 版本

1.10.1.0

### 问题分类

实时便笺

### 发生了什么？

我想打开自动刷新体力，但是提示修改计划任务失败，如图所示：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/114788565/fd6d442a-a923-404b-aacd-4acec72a232b)
尝试使用管理员模式运行，提示管理员模式下无法更改此设置

我已经看到了文档里对应的内容，但是重装系统不是解决问题的好办法。是否有手动添加计划任务的备用方案？

另外，在哪里能查看实时便笺的API，我可能需要自己重新实现这个功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
> 是否有手动添加计划任务的备用方案？

暂时没有，下版本我们将停止使用计划任务，使用托盘程序来实现定时刷新。

> 在哪里能查看实时便笺的API

UIGF-org/mihoyo-api-collect
