### ISSUE TITLE
[Bug]: 祈愿记录获取异常

### ISSUE THREAD

**Issue by lth6268** [DGP-Studio/Snap.Hutao#162]
### Windows 版本

22623.875

### Snap Hutao 版本

1.1.16.0

### 发生了什么？

角色UP池记录及武器UP池记录均已刷新出记录，使用Snap Hutao导入记录后，武器池记录导入成功，但是角色UP池记录未导入

### 相关的崩溃日志 位于 `%HOMEPATH%/Documents/Hutao/Log.db`

[issue.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9922300/issue.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [x] 是

**Comment by huang-lian** [comment]
有相同问题存在，已更新到最新版本

**Comment by Lightczx** [comment]
导入前的json提供一下

**Comment by lth6268** [comment]
[祈愿获取前后json.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9926774/json.zip)
包含更新记录前和更新记录后的json文件 获取方式是从缓存文件刷新

**Comment by Lightczx** [comment]
fixed 1.2.2
