### ISSUE TITLE
建议把祈愿记录也增加多账号

### ISSUE THREAD

**Issue by XiaoChi1010** [DGP-Studio/Snap.Hutao#1624]
### 背景与动机

我有两个账号，都想备份祈愿记录，但是目前祈愿记录只能有一个账号

### 想要实现或优化的功能

增加祈愿记录备份账号上限
![微信图片_20240518120503](https://github.com/DGP-Studio/Snap.Hutao/assets/143426884/cd2bc852-3592-492d-ab07-e747d4d468e1)

**Comment by qhy040404** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/2c83669a-85d8-43b6-8e07-175db24fa2b4)
请在左下切换到你想获取记录的账号后再通过stoken刷新
