### ISSUE TITLE
[Network]: 完全无法连接胡桃服务

### ISSUE THREAD

**Issue by ALTAiR1205** [DGP-Studio/Snap.Hutao#1638]
### 提交你的网络诊断报告

[SH-Report-7848a29d-8a0c-402f-81ca-7d04b55e0833.txt](https://github.com/DGP-Studio/Snap.Hutao/files/15439857/SH-Report-7848a29d-8a0c-402f-81ca-7d04b55e0833.txt)

### 你的地理位置

美国

### 你的运营商

其它

### 你的问题

完全无法连接服务器

### 你的问题（补充）

一直给我653366069的错误，但是我用网络是可以上米游社的，不知道是出于什么原因胡桃连接不上
<img width="1339" alt="微信图片_20240524164228" src="https://github.com/DGP-Studio/Snap.Hutao/assets/163762050/d7c17c63-46be-4b25-955e-cba13d2d939c">

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Lightczx** [comment]
看起来你的网络本身丢包率有点高

**Comment by ALTAiR1205** [comment]
可是我平时用着都没问题呀，米游社 原神 用着都挺正常的 玩国服原神也是正常的二百多一点延迟

**Comment by Lightczx** [comment]
《二百多一点》
这已经很高了，你大概能丢个20%-33%的包

**Comment by ALTAiR1205** [comment]
二百多是美国上国服的延迟 我感觉已经是相对正常的延迟了 而且我上国服网站都是很正常的 关键是程序报错说连接不上米游社 但是我正常上米游社是没问题的

**Comment by Lightczx** [comment]
@Masterain98

**Comment by Masterain98** [comment]
busy, slow in response

**Comment by qhy040404** [comment]
去胡桃设置里面打开调试控制台，然后找到任意warning并截图

**Comment by ALTAiR1205** [comment]
<img width="1339" alt="ba7f8a1864bac83566b1a3eed63ca67" src="https://github.com/DGP-Studio/Snap.Hutao/assets/163762050/a1334046-46df-4b71-af9b-46e87d487c45">

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/46d0c965-0cbd-48cf-929c-dbd287c683ab)
@ALTAiR1205

**Comment by ALTAiR1205** [comment]
在哪里找warning
<img width="1339" alt="1716940944334" src="https://github.com/DGP-Studio/Snap.Hutao/assets/163762050/703ed16c-0c29-4a06-8e14-3f93bd5be438">

**Comment by Lightczx** [comment]
控制台里面往上翻

**Comment by ALTAiR1205** [comment]
<img width="1925" alt="a9b66b2b86d5810e4213fde3c07dc3c" src="https://github.com/DGP-Studio/Snap.Hutao/assets/163762050/b2d1bb85-ee52-4821-9fa2-c49a39ea5514">

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by ALTAiR1205** [comment]
谢谢，好像已经修复了

**Comment by ALTAiR1205** [comment]
我好裂开了 昨天好了一阵 今天又开始报错了 是Spectrum这个狗屎网的问题吗
