### ISSUE TITLE
[Bug]: 成就统计中《最终枫达海》成就个数缺少

### ISSUE THREAD

**Issue by hxcgl** [DGP-Studio/Snap.Hutao#1642]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4291

### Snap Hutao 版本

1.10.1.0

### 设备 ID

8A77B9F3DACBF17C7E3793532A493019

### 问题分类

成就管理

### 发生了什么？

最终枫达海成就只有两个，参考【【原神】智勇双拳隐藏后续《最终枫达海》-哔哩哔哩】【视频标记点 00:31】 https://b23.tv/C8d9Me9
应有三个最终枫达海成就

### 你期望发生的行为？

三个最终枫达海成就

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/70537632-7d45-4cbf-9231-7f800e232db3)
I don't think so.

**Comment by hxcgl** [comment]
![a](https://github.com/DGP-Studio/Snap.Hutao/assets/155134010/f50385e4-cf19-4320-862e-fcc166788d24)
这......

**Comment by hxcgl** [comment]
搜索可以搜到三个，但直接翻只看到两个，这是什么新式彩蛋？

**Comment by hxcgl** [comment]
> ![image](https://private-user-images.githubusercontent.com/36357191/333853205-70537632-7d45-4cbf-9231-7f800e232db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDY2MDAsIm5iZiI6MTcxNjcwNjMwMCwicGF0aCI6Ii8zNjM1NzE5MS8zMzM4NTMyMDUtNzA1Mzc2MzItN2Q0NS00Y2JmLTkyMzEtN2Y4MDBlMjMyZGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwODUwZmE1ODFlNDMzOTdiZGVmYTY5NGM2M2JkODg5OWFmNDNjYTEyMDE5MDUyMmM0MDJkZTdiOWY0Yzg0YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ucpq3YXe-pghjTpYpIz4vefgGOB0iiuKZOFu-Eyj6JQ) I don't think so.
> 
> ID:[81399 81403 81404]

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/155134010/2772fb80-e963-46e1-a6ad-016c6f959c4e)
三个最终枫达海成就没有排列在一起。

**Comment by Lightczx** [comment]
如果你取消勾选了按完成优先排序就会变成乱序

**Comment by hxcgl** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/155134010/cc79d47e-8c9e-4236-9d31-90bdc540580f)
优先未完成也并没有排列在一起
