### ISSUE TITLE
[Bug]: 无法启动胡桃，即使显示安装完成

### ISSUE THREAD

**Issue by ill-never-retreat** [DGP-Studio/Snap.Hutao#1647]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3593

### Snap Hutao 版本

1.10.2.0

### 设备 ID

818AB8A676FA515F74F9AFA963F13C5D

### 问题分类

安装和环境

### 发生了什么？

[Snap.Hutao Error Log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/15448217/Snap.Hutao.Error.Log.txt)
无法正常启动snap hutao，不论正常或是管理员模式

### 你期望发生的行为？

能够重新启动胡桃，并完成区服的转换

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by ill-never-retreat** [comment]
<img width="484" alt="启启启启启动失败（" src="https://github.com/DGP-Studio/Snap.Hutao/assets/81285675/2bc05ef1-84c9-4137-98b5-9d5367ca0b78">

**Comment by qhy040404** [comment]
你是手动修改过胡桃数据目录吗

**Comment by ill-never-retreat** [comment]
> 你是手动修改过胡桃数据目录吗

应该都是默认路径，直到昨天无法打开胡桃我才开始试图寻找胡桃的安装位置

**Comment by ill-never-retreat** [comment]
> > 你是手动修改过胡桃数据目录吗
> 
> 应该都是默认路径，直到昨天无法打开胡桃我才开始试图寻找胡桃的安装位置

今天早上我又多次尝试启动胡桃，其中有一次出现了安装时的语言选择界面，但随后又闪退了

**Comment by qhy040404** [comment]
你的文档目录是什么
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/131d6bb6-a21e-4c91-8f0b-b004e9177aaf)

**Comment by ill-never-retreat** [comment]
> 你的文档目录是什么 ![image](https://private-user-images.githubusercontent.com/45379733/333932980-131d6bb6-a21e-4c91-8f0b-b004e9177aaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzQzMjAsIm5iZiI6MTcxNjc3NDAyMCwicGF0aCI6Ii80NTM3OTczMy8zMzM5MzI5ODAtMTMxZDZiYjYtYTIxZS00YzkxLThmMGItYjAwNGU5MTc3YWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAxNDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhM2NjYmQxNzZlM2JmMDRkNmMyMGU4Y2YxNTQyZDg5YzdjYjhhOTk1NDE5MDVmMDM5YTBkNDZhMmQwOWEzOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VOeUlk6MMHBbUocLyB3x2VY8DfUv21pL1yfnz0s48yg)

是指error log的目录吗

**Comment by qhy040404** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/8d149d38-7bb4-4147-a527-9221c5796300)

**Comment by ill-never-retreat** [comment]
> ![image](https://private-user-images.githubusercontent.com/45379733/333938505-8d149d38-7bb4-4147-a527-9221c5796300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzY4ODYsIm5iZiI6MTcxNjc3NjU4NiwicGF0aCI6Ii80NTM3OTczMy8zMzM5Mzg1MDUtOGQxNDlkMzgtN2JiNC00MTQ3LWE1MjctOTIyMWM1Nzk2MzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyMjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDE1YmNlZTM3M2Q0N2FmMWEwY2M1OTJjZTQ0YjhiMjcyNDM4NmY4MmMwYzgxYjEzYTliOTBkY2NkOGE0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HxKWaUmj1tfH34Uc8VQBPyAS06zW0ffpua4-OH3r988)

好的，我找到了
<img width="323" alt="文档位置" src="https://github.com/DGP-Studio/Snap.Hutao/assets/81285675/a06885de-b688-4f12-a657-81e5923b2a73">

**Comment by qhy040404** [comment]
> 好的，我找到了 <img alt="文档位置" width="323" src="https://private-user-images.githubusercontent.com/81285675/333939044-a06885de-b688-4f12-a657-81e5923b2a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzgwMjEsIm5iZiI6MTcxNjc3NzcyMSwicGF0aCI6Ii84MTI4NTY3NS8zMzM5MzkwNDQtYTA2ODg1ZGUtYjY4OC00ZjEyLWE2NTctODFlNTkyM2IyYTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyNDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NDk5NmE0ZjM5Njk3N2UwNTZjZWExMGQxN2Q4NTNiMWJjZDYyZmZhYmY5YThmNzZhMTQwMTQ5NDQ0YTAzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tdmx6cxAlAHw3gXOXoEMURQPgdQ9tLg0j5tiVQr74l4">

你这个文件夹全名是什么

**Comment by ill-never-retreat** [comment]
> > 好的，我找到了 <img alt="文档位置" width="323" src="https://private-user-images.githubusercontent.com/81285675/333939044-a06885de-b688-4f12-a657-81e5923b2a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzgwMjEsIm5iZiI6MTcxNjc3NzcyMSwicGF0aCI6Ii84MTI4NTY3NS8zMzM5MzkwNDQtYTA2ODg1ZGUtYjY4OC00ZjEyLWE2NTctODFlNTkyM2IyYTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyNDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NDk5NmE0ZjM5Njk3N2UwNTZjZWExMGQxN2Q4NTNiMWJjZDYyZmZhYmY5YThmNzZhMTQwMTQ5NDQ0YTAzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tdmx6cxAlAHw3gXOXoEMURQPgdQ9tLg0j5tiVQr74l4">
> 
> 你这个文件夹全名是什么

<img width="332" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/81285675/c9a89128-a874-4efc-b7fd-a863d59af92b">

**Comment by ill-never-retreat** [comment]
> > > 好的，我找到了 <img alt="文档位置" width="323" src="https://private-user-images.githubusercontent.com/81285675/333939044-a06885de-b688-4f12-a657-81e5923b2a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzgwMjEsIm5iZiI6MTcxNjc3NzcyMSwicGF0aCI6Ii84MTI4NTY3NS8zMzM5MzkwNDQtYTA2ODg1ZGUtYjY4OC00ZjEyLWE2NTctODFlNTkyM2IyYTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyNDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NDk5NmE0ZjM5Njk3N2UwNTZjZWExMGQxN2Q4NTNiMWJjZDYyZmZhYmY5YThmNzZhMTQwMTQ5NDQ0YTAzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tdmx6cxAlAHw3gXOXoEMURQPgdQ9tLg0j5tiVQr74l4">
> > 
> > 
> > 你这个文件夹全名是什么
> 
> <img alt="image" width="332" src="https://private-user-images.githubusercontent.com/81285675/333951852-c9a89128-a874-4efc-b7fd-a863d59af92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjgzMDksIm5iZiI6MTcxNjg2ODAwOSwicGF0aCI6Ii84MTI4NTY3NS8zMzM5NTE4NTItYzlhODkxMjgtYTg3NC00ZWZjLWI3ZmQtYTg2M2Q1OWFmOTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAzNDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmY0ZDQwMGJkMmQwMGRjOGRlZmYyMTliNTQ2MDBjM2IyZmEyOGY1NWY4MThhOTczNDlmYTMyMWEzZDJhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nM0_ugEiFCnDIyz759JCSvlWU7nwKzaHFRCVRsQIDfg">

今天能够进行完整的安装流程，包括语言选择等，但依旧无法启动

**Comment by Lightczx** [comment]
你的文档文件夹权限有点高

**Comment by ill-never-retreat** [comment]
> 你的文档文件夹权限有点高

是否有推荐的调整方案呢，我想也许有其他用户遇到了相似的问题

**Comment by Lightczx** [comment]
如果是这个版本突然出现的问题那一定不是我们的问题，我们也无能为力

**Comment by Lightczx** [comment]
Closing for no further response
