### ISSUE TITLE
祈愿记录URL已失效的Dialog没有关闭按钮

### ISSUE THREAD

**Issue by AllesUgo** [DGP-Studio/Snap.Hutao#165]
### Windows 版本

22621.608

### Snap Hutao 版本

1.1.18.0

### 发生了什么？

祈愿记录URL已失效的Dialog没有关闭按钮，只能用esc关闭
![image](https://user-images.githubusercontent.com/67179426/199734094-eeff8423-2d0f-43f1-95b2-f553988fb6d2.png)

### 你期望发生的行为？

包含关闭按钮

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
这个状态处于初始化与获取第一次物品列表期间，可能是网络较差导致的
