### ISSUE TITLE
[Bug]: 覆盖安装和重装失败，卸载也报错(未开代理)

### ISSUE THREAD

**Issue by halointernet** [DGP-Studio/Snap.Hutao#1652]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.521

### Snap Hutao 版本

1.10.2

### 设备 ID

 AB03E532175D47C7ABF9F95FDFA10890

### 问题分类

安装和环境

### 发生了什么？

今天更新用软件直接更新失败，然后直接覆盖报错，然后重装也不行
![e](https://github.com/DGP-Studio/Snap.Hutao/assets/62073674/8184ccf8-5bb2-438f-9a22-614731087362)

### 你期望发生的行为？

怎么修复

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
已优化分发网络，请重试
