### ISSUE TITLE
[Bug]: 国服转换国际服失败 JsonException

### ISSUE THREAD

**Issue by 1127626014** [DGP-Studio/Snap.Hutao#1653]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3593

### Snap Hutao 版本

1.10.2.0

### 设备 ID

F58A4404F94B308DFE89EAF8A2BCA436

### 问题分类

游戏启动器

### 发生了什么？

昨天国服和国际服之间的转换还是可以的，今天卡在获取Package Version，然后就会报错，还出现个以前没出现过的错误提示

JsonException
Expected end of string,but instead reached end of data.Path:$l
LineNumber:0 BytePositionlnLine:193.

### 你期望发生的行为？

国服可以成功转换国服

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by 1127626014** [comment]
> ### Probable Similar Topics
> 1. 67% [国际服转换官服失败 #1433](https://github.com/DGP-Studio/Snap.Hutao/issues/1433)

那个我看了，只是说修复此问题，但我这又出现了

**Comment by 1127626014** [comment]
> ### Probable Similar Topics
> 1. 67% [国际服转换官服失败 #1433](https://github.com/DGP-Studio/Snap.Hutao/issues/1433)

我们两个问题一样的，请问最后的解决办法是什么

**Comment by aaahai00** [comment]
我好像也发生这个问题了，错误翻译过来是文件占用，一直无法转，后面发现游戏主文件没了，恢复完重启胡桃就好了

**Comment by aaahai00** [comment]
> 我好像也发生这个问题了，错误翻译过来是文件占用，一直无法转，后面发现游戏主文件没了，恢复完重启胡桃就好了 版本1.10.30

后面看了一下和#1703描述一致，大概是和这个问题不相干了

**Comment by Lightczx** [comment]
#1851
