### ISSUE TITLE
后台运行

### ISSUE THREAD

**Issue by InTka** [DGP-Studio/Snap.Hutao#1654]
### 背景与动机

能不能弄一个开关，或者关掉软件后台运行这个功能，不然每次用完都得在右下角托盘那右键退出，很麻烦的

### 想要实现或优化的功能

能不能弄一个开关，或者关掉软件后台运行这个功能，不然每次用完都得在右下角托盘那右键退出，很麻烦的

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/fb45c30b-9f26-4325-951a-8149cfaebe6e)
