### ISSUE TITLE
[Bug]: hutao进程无法正常关闭

### ISSUE THREAD

**Issue by Ruinaqaq** [DGP-Studio/Snap.Hutao#1655]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4412

### Snap Hutao 版本

1.10.2.0

### 设备 ID

DAEDE8B09279F997424D68DBDDE68759

### 问题分类

游戏启动器

### 发生了什么？

在使用过程中hutao进程无法正常关闭，需要使用任务管理器进行关闭
![40D89574EC3A07CD544BF7A028A90159](https://github.com/DGP-Studio/Snap.Hutao/assets/168326315/ec3cc833-1d6e-46a8-99c0-cec843a9e8d0)

### 你期望发生的行为？

进程正常关闭

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
右下角检查托盘图标
