### ISSUE TITLE
[Feat]: 给通知区域图标添加左键点击功能

### ISSUE THREAD

**Issue by HPLZH** [DGP-Studio/Snap.Hutao#1656]
### 背景与动机

通知区域图标需要右键单击才有反应，左键单击/双击则无任何反应，但是用户更习惯于使用左键

### 想要实现或优化的功能

左键单击通知区域图标时，可以弹出和右键单击一样的功能选择界面，或者直接打开主窗口

**Comment by Mikachu2333** [comment]
补充：在已经打开软件的情况下（右下角藏着），双击桌面图标后自动打开主窗口

长时间不关闭电脑（例如晚上睡觉电脑休眠，第二天打开电脑忘了做完关没关），双击没反应以后又去几十个后台里面翻

**Comment by Mikachu2333** [comment]
注：**单击双击都需要**，此外，如果单击后紧跟了一个双击可能需要额外的处理。
