### ISSUE TITLE
[Feat]: Snap.Hutao在启动时记住上次窗口大小

### ISSUE THREAD

**Issue by EricZhang233** [DGP-Studio/Snap.Hutao#1657]
### 背景与动机

因为默认的窗口大小，在主页的固定页签上面会留有两个空白位，所以习惯调整窗口至自己喜欢的大小，但是每次重启Hutao就会恢复默认大小。
![微信截图_20240528221412](https://github.com/DGP-Studio/Snap.Hutao/assets/85214146/ea2896a9-0dec-4116-b94b-b8daebdd0a13)
![微信截图_20240528221426](https://github.com/DGP-Studio/Snap.Hutao/assets/85214146/71da7982-7a8c-4631-b328-38c9794c90f0)

### 想要实现或优化的功能

记忆Snap.Hutao窗口大小并在下次启动时应用

**Comment by Lightczx** [comment]
多个建议不要写同一个Issue里面

**Comment by Lightczx** [comment]
> 记忆Snap.Hutao窗口大小并在下次启动时应用

实测是记忆的

**Comment by EricZhang233** [comment]
但我这里无论换电脑、重装系统、还是软件，都不会记忆窗口大小，请你把窗口大小沿对角线调整到最小后重启ShapHutao以复现问题。

**Comment by Lightczx** [comment]
看了下确实有点问题
https://github.com/DGP-Studio/Snap.Hutao/blob/e5c751771c89edf3432dbe06e216739bf3b2f728/src/Snap.Hutao/Snap.Hutao/Core/Windowing/XamlWindowController.cs#L246-L249

按现在的逻辑是不会恢复到小于初始大小的尺寸的
