### ISSUE TITLE
[Bug]: 使用磁贴右键-启动游戏打开游戏启动器时会提示".SnapHutao_wbnnev551gwxy!App"文件打开方式

### ISSUE THREAD

**Issue by yEs1do** [DGP-Studio/Snap.Hutao#1658]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4412

### Snap Hutao 版本

1.10.2.0

### 设备 ID

73FF5ECCFD51DD1CD9569B8A7ACDB09E

### 问题分类

游戏启动器

### 发生了什么？

此问题在几个版本前开始出现，更新至最新版本后无法解决，暂时未通过重装等方式尝试解决。
使用磁贴右键-启动游戏打开游戏启动器时会提示（在任务栏中右键启动游戏不会出现）：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/25378493/81f1a4fc-de33-4198-ad04-ebbc05e25a92)

进入系统设置中查找，的确有该后缀的提示。使用注册表删除该后缀名相关目录后再次磁贴启动重现。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/25378493/d9a5af90-cc26-49fb-a7eb-6d67edae33d1)

### 你期望发生的行为？

正常应当可以直接打开启动器，此问题无限次复现，目前无法正常从磁贴启动。
如果此问题不易修复，请开发人员确认不会在新版本复现后，我将自行重装胡桃工具箱以避免遇到。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
无所谓，启动游戏的Task会在下版本删除，你将不再能够通过右键磁贴或任务栏图标直接启动游戏
