### ISSUE TITLE
[Bug]: Snap.Hutao.Deployment 运行失败

### ISSUE THREAD

**Issue by W4yneChen** [DGP-Studio/Snap.Hutao#1659]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4412

### Snap Hutao 版本

1.10.2

### 设备 ID

652E0C69F29AC22BD6D0524CCDF0F74B

### 问题分类

安装和环境

### 发生了什么？

按照 官方文档-快速开始 中的操作下载并运行 Snap.Hutao.Deployment，在下载包时输出错误 Response status code does not indicate success: 403 (Forbidden). 

cmd 输出如下图：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/29047653/848e33e8-d4e2-4b30-b5b6-f640799f47c5)

### 你期望发生的行为？

运行 Snap.Hutao.Deployment 后成功下载胡桃工具箱

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
我们没钱了，如果能下载完就是你的运气
