### ISSUE TITLE
[Bug]: 在右下角点击“启动游戏”无法按照预期打开启动游戏的窗口

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1660]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4291

### Snap Hutao 版本

1.10.2.0

### 问题分类

游戏启动器

### 发生了什么？

在没有胡桃窗口的情况下，右键任务栏图标的“启动游戏”直接打开了软件主页面的启动页签而非启动小窗口

**复现步骤**
1. 打开胡桃并至于右下角任务栏，关闭主页面
2. 锁屏并熄屏
3. 重新解锁
4. 双击胡桃图标（此时没有反应 **是复现的必须步骤** ）
5. 右下角“启动游戏”
6. 复现完毕

### 你期望发生的行为？

正确打开启动游戏的小窗口

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
记录：点击dev版本右下角弹出的提示（“胡桃已进入后台”）也可以导致本问题的发生

**Comment by Mikachu2333** [comment]
补充：
1. 可以不需要锁屏并解锁这一步骤
2. 详情分析见下
  - 胡桃启动，currentWindowReference.Window==null，启动主窗口，设置了 crrrent.win 为 mainWindow 的句柄
  - 胡桃主页面退出，crrrent.win 被重置为null，（若此时启动，则按照null的情况开始执行启动小窗口）
  - 点击胡桃再次启动，触发了 currentWindowReference.Window = serviceProvider.GetRequiredService<MainWindow>(); ，crrrent.win 被无意中重置为了 mainWindow 的句柄
  - 再次点击右下角，按照 mainWindow 的句柄执行了启动主页面的页签

**Comment by Lightczx** [comment]
> 4\. 双击胡桃图标（此时没有反应 **是复现的必须步骤** ）

Adjusted to `switch to the MainWindow`
Other behavior is expected.
