### ISSUE TITLE
[Quality Assurance] 质量测试问题

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1661]
**未处理的**
- [x] 因为点的太快导致同时双开了胡桃的alpha版和stable版本
- [x] 成就的描述显示不全，希望通过更改右键显示或增加左键点击的方式显示被遮挡的详细信息（文字太长导致，见下图）
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/1d0d81e8-87d3-4f5d-80d1-6ce03bee1d65)
- [ ] 启动游戏的小窗口在显示时自动居中
- [ ] 2024.6.15.4版中的添加到养成显示不全，间距过窄
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/bbbdf83d-65a9-424a-a324-4995a5b8cb18)
- [ ] 背包物品按原神内样式排序
- [ ] 在本页面禁止返回至空白页，因其无法前进只能后退
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/5ae9ff04-e723-462d-938f-539791a6bd52)
- [ ] 仆人等强敌的boss资料缺失
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/a46f6b82-cc5e-42f7-9bdf-4413432dbf78)
![11](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/f17243a3-731e-4d8b-9ce5-e7c58e8982ee)
- [ ] 未登录胡桃时，误点击上传深渊记录时无法取消，需要点登陆->返回
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/09c50ac3-2b33-4073-92c4-0667d887d819)
- [ ] 部分怪物掉落材料缺失
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/e2fec589-1d30-49d1-8c9f-5aad24aace07)
- [ ] 预下载那边的每个分类框疑似都多垫了一层
![a37641aee0aae4d468c4e306e5ac496e](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/1556af1a-b727-4e5f-8482-64b0e716ee52)
- [ ] etc.

**Comment by Mikachu2333** [comment]
**已处理的**

- [x] yae联动dev（admin）版本失败
- [x] 打开截图文件夹加入检测是否存在的机制
- [x] 主页的游戏公告和活动公告加黑色护眼蒙版
- [x] 抽卡界面增加黑色护眼蒙版
- [x] 删除转换服务器缓存的提示info与success判定
- [x] 实时便笺的按钮需要多线程以缓解动画与实际不匹配的问题
- [x] 胡桃在已经关闭的情况下点击通知，本应什么都不做的通知将唤起胡桃（等同于双击桌面图标）
- [x] 在启动游戏页签重新选择一次游戏路径时，右下角的启动游戏小窗口无法获取账号信息（即便主窗口存在相关信息）

**Comment by Mikachu2333** [comment]
**不予考虑或被放弃**

- [ ] 2024.6.15.4版中背包物品抓取后提示结果是否成功

**Comment by qhy040404** [comment]
MS Bug
- [ ] 渲染bug（微软原因导致，可忽略）
![8ab355d20c5633c375b382999b66689b](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/b9f07b1c-087e-4202-8489-78ce37d9316c)
- [ ] 在角色页面与武器页面，当列数达到某个特定极值时（恰好要多出一列），上面的搜索条条（一长条黑底）颜色会突然改变（注，疑似winui bug）
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/9eef320b-f456-48f3-ad41-bfcabdcf7086)
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/68d783f8-6050-4431-bf29-f3be34d14ced)

**Comment by Mikachu2333** [comment]
**Misunderstanding**

- [x] 对齐寄了
![898d3c626fce172579064b83c762d299](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/a26f72ab-d618-4b4a-b31e-f3aba4204322)

**Comment by Mikachu2333** [comment]
本issues搬迁完毕
