### ISSUE TITLE
能否添加一个自定义游戏参数启动的快捷方式

### ISSUE THREAD

**Issue by shiguangyibei** [DGP-Studio/Snap.Hutao#1666]
### 背景与动机

自己是多显示器用户，日月串流不方便切屏幕，用虚拟显示器来运行原神串流到手机，但是有时候要用电脑玩，就希望能出一个能固定启动参数的快捷图标

### 想要实现或优化的功能

比如我如果想串流到手机玩，我就可以把参数设置成游戏显示在虚拟显示器上，120帧运行，无边框，然后把以这样参数启动的游戏快捷方式放桌面上，方便把这个快捷方式放入sunshine的快捷启动栏里，方便我手机端直接启动。
<img width="1193" alt="PixPin_2024-05-31_23-05-23" src="https://github.com/DGP-Studio/Snap.Hutao/assets/151373404/c6f0d77e-0c8f-4538-90a5-ab02ebcc963b">

**Comment by Lightczx** [comment]
启动参数本来就会保存状态，你平时切换各种参数很频繁么 @shiguangyibei

**Comment by shiguangyibei** [comment]
感谢开发大大回复，目前这个问题解决了哈哈，还是草率了没研究透
