### ISSUE TITLE
我想问下这个工具有没有通过exe直接启动的方式

### ISSUE THREAD

**Issue by thirter** [DGP-Studio/Snap.Hutao#167]
### 你想要实现或优化的功能？

    我平常是用手柄打原神，会使用steam来启动之前的DGP.genshin.exe，为了应用steam上的手柄键位映射功能。
    可是DGP.hutao的exe似乎不能直接双击启动，会提示权限不足，我手动更改exe的权限但除了不再报错并没有其他反应。
    请问有那种就是exe启动或者一个批处理程序启动的方式么。

**Comment by Masterain98** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/184#issuecomment-1304735065
