### ISSUE TITLE
主页的公告都消失了

### ISSUE THREAD

**Issue by ErnstWang** [DGP-Studio/Snap.Hutao#1674]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3593

### Snap Hutao 版本

1.10.2.0

### 设备 ID

E6CDBB71C68FDDA2465BB9F61B8F96F6

### 问题分类

公告

### 发生了什么？

公告内容空白
![屏幕截图 2024-06-05 061919](https://github.com/DGP-Studio/Snap.Hutao/assets/83711664/a1a983ff-86a1-464e-b2a9-7b3074d7bff6)
![屏幕截图 2024-06-05 062540](https://github.com/DGP-Studio/Snap.Hutao/assets/83711664/0b484a4b-2d17-4272-a924-5d3e326421ac)

### 你期望发生的行为？

正常启动胡桃包括管理员模式（窗口模式，且公告没法在可视区域全部获取完成）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你选的哪个服务器的公告

**Comment by ErnstWang** [comment]
> 你选的哪个服务器的公告

官服
