### ISSUE TITLE
[Bug]: 4.7解锁帧率失效，无法启动游戏

### ISSUE THREAD

**Issue by luluxiaoyu** [DGP-Studio/Snap.Hutao#1675]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3672

### Snap Hutao 版本

1.10.2

### 设备 ID

A177DC0C71F6F70F35FB289C47220C3C

### 问题分类

安装和环境

### 发生了什么？

启动游戏（解锁帧率）
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/58876608/696d215f-7375-4944-84f7-f66128450051)

### 你期望发生的行为？

正常启动

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
《是这样的，普通用户等着修复就可以了，而我们开发者要考虑的就...》

**Comment by rainmiuchen** [comment]
同样的问题+1

**Comment by Ateren** [comment]
我也是同样的问题，先正常启动等修复了

**Comment by Ateren** [comment]
> 《是这样的，普通用户等着修复就可以了，而我们开发者要考虑的就...》

公式做题就是快

**Comment by 79mario** [comment]
一样问题

**Comment by lonelyzerg** [comment]
> 《是这样的，普通用户等着修复就可以了，而我们开发者要考虑的就...》

加油啊，套沟槽的公式的大哥哥！

**Comment by AleksiDB** [comment]
> 《是这样的，普通用户等着修复就可以了，而我们开发者要考虑的就...》

原来这里已经有人发了，同样问题XD，dalao加油哇，（要怎么做你才能回来QAQ, 为了帧率解锁我什么都会做的TAT...

**Comment by luluxiaoyu** [comment]
> > 《是这样的，普通用户等着修复就可以了，而我们开发者要考虑的就...》
> 
> 原来这里已经有人发了，同样问题XD，dalao加油哇，（要怎么做你才能回来QAQ, 为了帧率解锁我什么都会做的TAT...

买苹果 自带120（ bushi

**Comment by Yzh00-c** [comment]
一样的问题，我也遇到了

**Comment by HDTTT** [comment]
一样的问题

**Comment by gua12345** [comment]
这个项目还能解锁帧率https://github.com/34736384/genshin-fps-unlock/tree/v3.0.4 ，我觉得应该可以直接集成进工具箱里就好了吧（狗头保命）

**Comment by AlenhuAN** [comment]
> 《是这样的，普通用户等着修复就可以了，而我们开发者要考虑的就...》

鸣人鸣言

**Comment by Lightczx** [comment]
@luluxiaoyu 试试这个 https://github.com/DGP-Studio/Snap.Hutao/actions/runs/9379983703

**Comment by TangChang** [comment]
> 《是这样的，普通用户等着修复就可以了，而我们开发者要考虑的就...》

它们呀，工作之余还要修BUG

**Comment by luluxiaoyu** [comment]
> @luluxiaoyu 试试这个 https://github.com/DGP-Studio/Snap.Hutao/actions/runs/9379983703

启动游戏后 胡桃自动退出了，然后我看帧率还是60

**Comment by HDTTT** [comment]
各位可以暂时用这个解锁帧率过渡一下，亲测可用
https://github.com/34736384/genshin-fps-unlock

**Comment by qhy040404** [comment]
fixed by 3200c5e

**Comment by Lightczx** [comment]
测试版本 https://github.com/DGP-Studio/Snap.Hutao/actions/runs/9381555458 已经修复

**Comment by gicsy** [comment]
我超我也是这样

**Comment by p122344455** [comment]
大家都是这个问题
