### ISSUE TITLE
[Feat]: 希望添加快捷切换游戏账号功能

### ISSUE THREAD

**Issue by Fillair19** [DGP-Studio/Snap.Hutao#168]
### 你想要实现或优化的功能？

SG的时候可以在启动游戏界面选择uid以切换游戏账号，不用每次都输入账号密码，目前HUTAO的这个功能不见了。

P.S.我尝试过添加两个米游社账号并检测了两个uid，然而在HUTAO中切换uid时，进入游戏并没有切换uid（https://files.catbox.moe/vbzwcf.png）

**Comment by Lightczx** [comment]
需要在启动游戏前选中启动游戏界面中的账号
而不是用户面板中的账号，绑定UID功能在后期另有他用
