### ISSUE TITLE
[Bug]: 背景图片官方启动器壁纸选项问题

### ISSUE THREAD

**Issue by twjmy** [DGP-Studio/Snap.Hutao#1688]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3672

### Snap Hutao 版本

1.10.2.0

### 设备 ID

4B6379FDA25D058C3FA50872BAB7D316

### 问题分类

用户界面

### 发生了什么？

背景图片选取官方启动器壁纸选项时，只有英文而没有其他选项，但实则有对应其他语言的背景美术图

### 你期望发生的行为？

显示与胡桃或官方启动器相匹配的语言，找出或供用户选取官方启动器背景图文件路径取用资源

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by Masterain98** [comment]
@Lightczx 原神官方背景的请求你是不是没有带 `language` 参数？

**Comment by Masterain98** [comment]
后端是处理了语言的

https://github.com/DGP-Studio/Generic-API/blob/3b1d83f2d8c30c61d41fe7b1c57e76d839557fb4/routers/wallpaper.py#L294-L315

**Comment by Masterain98** [comment]
@twjmy 你是在中国内地使用的胡桃或者使用了中国内地的网络代理吗？

**Comment by twjmy** [comment]
> @twjmy 你是在中国内地使用的胡桃或者使用了中国内地的网络代理吗？

我是在台湾玩国际服，没用代理，语言是繁中

**Comment by Masterain98** [comment]
> > @twjmy 你是在中国内地使用的胡桃或者使用了中国内地的网络代理吗？
> 
> 我是在台湾玩国际服，没用代理，语言是繁中

麻烦在 PowerShell 中输入 `nslookup api.snapgenshin.com` 并提供一下返回的数据

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/3a76fcc5-482e-40b5-a96f-0ea3e892eb35)

@Lightczx 客户端请求后端的时候没有添加 `language` 参数

**Comment by twjmy** [comment]
> @Lightczx 客户端请求后端的时候没有添加 `language` 参数

会是这里吗

https://github.com/DGP-Studio/Snap.Hutao/blob/fd59b471cbea1d6bc177dc92a136ad4187b78a80/src/Snap.Hutao/Snap.Hutao/Web/HutaoEndpoints.cs#L281

**Comment by Lightczx** [comment]
@Masterain98 我加language code 还是 generic api 改成语言无关的？

**Comment by Masterain98** [comment]
> @Masterain98 我加language code 还是 generic api 改成语言无关的？

你加 language code 吧，无字版本单独列成 HYP 背景选项

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/32cb9751-2be7-4124-9597-427c8c32f849)


热更新了一次，现在已经换成了无字的版本
