### ISSUE TITLE
[Bug]: 按钮或字体乱码

### ISSUE THREAD

**Issue by blinkcx** [DGP-Studio/Snap.Hutao#170]
### Windows 版本

19043.2193

### Snap Hutao 版本

1.1.18

### 发生了什么？

按钮或字体乱码，如图
![image](https://user-images.githubusercontent.com/18332564/199776561-eb8445a5-4a22-4afb-b961-1c786c805f69.png)
![image](https://user-images.githubusercontent.com/18332564/199776624-399d4176-01dd-4cd4-8e6e-807d2c48cd0d.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Masterain98** [comment]
看文档
