### ISSUE TITLE
[Bug]: 国服与国际服切换后解锁帧率占用UnityPlayer导致无法进行下一次转换

### ISSUE THREAD

**Issue by Squarelan** [DGP-Studio/Snap.Hutao#1703]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.3646

### Snap Hutao 版本

1.10.3

### 设备 ID

07DE89E3C778DC29C6E1B0A8A77E9B0A

### 问题分类

游戏启动器

### 发生了什么？

已发现问题是国服与国际服切换时并不会结束对UnityPlayer.dll占用导致切换失败，然后导致游戏文件损坏。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/46771456/b82f4ac3-c49f-46dc-b175-79d3293fe79c)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Squarelan** [comment]
补充：将胡桃工具箱彻底关闭后再切换服务器正常，现在就是每次切换服务器都得彻底退出胡桃工具箱再重新打开。

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao/commit/82e6b62231057e69ff9d2398b21602ff6f024800
