### ISSUE TITLE
[Bug]: 从Yae Achievement导入成就时崩溃

### ISSUE THREAD

**Issue by CR4Player** [DGP-Studio/Snap.Hutao#1704]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3593

### Snap Hutao 版本

1.10.3.0

### 设备 ID

F7E1691750C5EFC6D10174B32E1F4EF5

### 问题分类

成就管理

### 发生了什么？

在最新版Yae Achievement获取成就并选择导出至Snap Hutao后，程序崩溃并自动重启，且自动重启后程序无法正常运行，仅显示白色空白窗体并卡死，任务管理器强行结束任务后可以正常启动程序。
使用UIAF格式导入时无问题
100%复现

### 你期望发生的行为？

正常弹出成就导入选项

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
可以先启动胡桃再导入

**Comment by CR4Player** [comment]
> fixed by [89f8ded](https://github.com/DGP-Studio/Snap.Hutao/commit/89f8dedb57c6dfea2180b882cf2881a76fe268cf)

确认。此Build中该问题已解决
