### ISSUE TITLE
[Feat]: 更新对话框提供下载超链接

### ISSUE THREAD

**Issue by XYTsunny** [DGP-Studio/Snap.Hutao#1706]
### 背景与动机

在应用内只能等自动更新弹窗然后更新，下载新版本失败后无法再次更新，除非重启应用

### 想要实现或优化的功能

建议增加检查更新及更新按钮，以方便应用更新

**Comment by Mikachu2333** [comment]
细化需求：

1. 可选是否下载更新
2. 可选是否通过胡桃或自行下载更新（例如胡桃给个网址跳转浏览器啥的）
3. 在胡桃下载时多线程下载，失败时可自动重试、断点续传

**Comment by Lightczx** [comment]
> 1. 可选是否下载更新
本就可以
> 2. 可选是否通过胡桃或自行下载更新（例如胡桃给个网址跳转浏览器啥的）
Promising
> 3. 在胡桃下载时多线程下载，失败时可自动重试、断点续传
自动重试早已实装，断点续传谁爱写谁写

**Comment by Mikachu2333** [comment]
> 断点续传谁爱写谁写

为啥不考虑考虑直接调用个curl之类的呢

**Comment by Lightczx** [comment]
> > 断点续传谁爱写谁写
> 
> 为啥不考虑考虑直接调用个curl之类的呢

调用外部程序从来不是一个合理的选项

**Comment by XYTsunny** [comment]
> > 1. 可选是否下载更新
> 
> 本就可以
> 
> > 2. 可选是否通过胡桃或自行下载更新（例如胡桃给个网址跳转浏览器啥的）
> 
> Promising
> 
> > 3. 在胡桃下载时多线程下载，失败时可自动重试、断点续传
> 
> 断点续传谁爱写谁写

下载失败后提供重新下载选项（尽量应用内更新方便点），同时提供链接

**Comment by hoshiizumiya** [comment]
软件内更新下载总是反复暂停在某一个进度......

**Comment by XYTsunny** [comment]
> 软件内更新下载总是反复暂停在某一个进度......但是在UpdateCache目录下可以看到显然安装包已经完成了下载，并且没有异常

我是越下越慢，然后就停住了，报更新失败

**Comment by Lightczx** [comment]
impl by https://github.com/DGP-Studio/Snap.Hutao/commit/57e042ec1ce3c44368c2d5e9b1794e405942552a
