### ISSUE TITLE
[Bug]: 服务器切换的时候出现问题导致游戏玩不了

### ISSUE THREAD

**Issue by 2498638068** [DGP-Studio/Snap.Hutao#1707]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3296

### Snap Hutao 版本

1.10.3.0

### 设备 ID

14364ECD19C3247A8600764B6A8E2651

### 问题分类

游戏启动器

### 发生了什么？

国际服切国服的时候切换失败导致整个游戏玩不了
![L%L(Z$OV)%N9A {W%BVJW3J](https://github.com/DGP-Studio/Snap.Hutao/assets/171955935/989a03aa-83a7-441f-a307-9d67cfa3461e)
![F8D~)@JSKT`82V%F)Y )FAC](https://github.com/DGP-Studio/Snap.Hutao/assets/171955935/134355b9-2887-4df6-90e0-d442d8b8b8e3)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
#1703
