### ISSUE TITLE
[Bug]: 开启高刷新率后，使用PS4手柄游玩时瞄准陀螺仪失灵

### ISSUE THREAD

**Issue by yukiadras** [DGP-Studio/Snap.Hutao#1709]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22000.2538

### Snap Hutao 版本

1.10.3.0

### 设备 ID

DF8678DBC47D7D0F9A36B52F9F693B50

### 问题分类

其它

### 发生了什么？

开启高刷新率时，使用PS4手柄游玩，开启陀螺仪瞄准后，游戏画面无规则疯狂转动，无法瞄准，极大影响游戏体验，还请亲身测试

### 你期望发生的行为？

修复该问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
原自己的问题
