### ISSUE TITLE
[Bug]: 启动游戏中外观设置会重置

### ISSUE THREAD

**Issue by imxdsf** [DGP-Studio/Snap.Hutao#171]
### Windows 版本

19042.1023

### Snap Hutao 版本

1.1.18.0

### 发生了什么？

启动游戏 - 外观 中的参数在每次重启Snap.HuTao的时候，都会变更为默认参数{即:全屏：开、无边框：关、宽度：1920、高度：1080}

### 你期望发生的行为？

记录并保存修改的参数，以便重新启动软件的时候不用重新设置。

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
点击启动游戏后才会保存相关设置
