### ISSUE TITLE
[Bug]: 实时便笺不自动刷新

### ISSUE THREAD

**Issue by DSakura207** [DGP-Studio/Snap.Hutao#1710]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3593

### Snap Hutao 版本

1.10.3.0

### 设备 ID

2DA44F8264495636ACC5D4C0BC30C148

### 问题分类

实时便笺

### 发生了什么？

实时便笺不自动刷新。
用户账户位于美服。已经正常登录HoyoLab。
已经确认自动刷新为开启。无论如何调整时间间隔，便笺也不自动刷新。
可以确认并非API问题。当点击“立即刷新”时，能正确从服务器取得数据并弹出通知。

### 你期望发生的行为？

实时便笺能够自动刷新。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
别关后台

**Comment by DSakura207** [comment]
没关，不如说一直保持在非焦点状态。倒是每次开启程序的时候都会自动刷新。
如图所示。
![PZV0iZujHU](https://github.com/DGP-Studio/Snap.Hutao/assets/4421906/2404fb2c-44d5-432e-a143-a4668b2110cc)
![1rOMS3iUP3](https://github.com/DGP-Studio/Snap.Hutao/assets/4421906/0e745d4e-4a90-4326-8ef6-a713207cc245)

**Comment by Lightczx** [comment]
在调整到4分钟的情况下等待至少8分钟，检查页面上的树脂刷新时间

**Comment by DSakura207** [comment]
时间保持在启动程序的时刻不变。
![rzLTua64tL](https://github.com/DGP-Studio/Snap.Hutao/assets/4421906/1ba1b3b5-a544-40e2-86fe-2dcee2ebde5a)
![RR7p8RpVyC](https://github.com/DGP-Studio/Snap.Hutao/assets/4421906/bc26faea-893c-4ac0-9960-a42bcc662ca0)
