### ISSUE TITLE
[Bug]: 软件无法再次安装

### ISSUE THREAD

**Issue by autoAnti** [DGP-Studio/Snap.Hutao#1716]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3672

### Snap Hutao 版本

1.10.3.0

### 设备 ID

D78D2DB1DDF6F25C7732AAE9C69A9007

### 问题分类

安装和环境

### 发生了什么？

第一次安装是成功的 但是在开始菜单右键卸载以后 再次安装就会报错

应用安装失败，错误消息: 从  (Snap.Hutao.msix)  使用程序包 60568DGPStudio.SnapHutao_1.10.3.0_x64__wbnnev551gwxy 中的目标卷 C: 执行的部署 Add 操作失败，错误为 0x80080206。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=235160。 (0x80080206)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你下载的包炸了
