### ISSUE TITLE
希望增加另一种形式展示抽卡记录

### ISSUE THREAD

**Issue by MTKmin** [DGP-Studio/Snap.Hutao#1718]
### 背景与动机

现在显示的抽卡分析为列表和网格形式，希望增加纯文字形式利用颜色区分不同角色，方便截图，希望能采纳，谢谢。

### 想要实现或优化的功能

![模板](https://github.com/DGP-Studio/Snap.Hutao/assets/100497697/63ac92ce-82fe-4c60-b16b-c5923c746be9)

**Comment by Masterain98** [comment]
你是希望能在一个页面上看到一个完整的抽卡记录（即使记录很长）；还是真的想要文字记录？

**Comment by MTKmin** [comment]
感谢回复，希望能在一个页面上看到一个只有五星的抽卡记录,横向排序，竖向截图截不全。目前网格显示又缺失角色名称，感觉还不长就换行显示了，谢谢

**Comment by Lightczx** [comment]
纯文本形式不符合我们的设计理念，暂时不会考虑
如果想要截图可以买个大点的显示器

**Comment by Natrium0521** [comment]
[PixPin](https://pixpinapp.com/)
