### ISSUE TITLE
[Bug]: 4.7版本更新用高刷模式启动报错【在查找必要的模块时遇到问题 无法将模块复制到指定位置】

### ISSUE THREAD

**Issue by YodaYuuk1** [DGP-Studio/Snap.Hutao#1719]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2(19045.4412)

### Snap Hutao 版本

1.10.1.0

### 设备 ID

F3B9494BBF0BC220E4294EC02D37EF43

### 问题分类

游戏启动器

### 发生了什么？

4.7版本更新之后无法用高刷模式启动，显示错误：【在查找必要的模块时遇到问题 无法将模块复制到指定位置】

无法在文档中找到对应解答，但如果我没记错，在4.7更新当日用高刷模式启动的时候提示的错误是：【在查找必要的模块时遇到问题，查找模块超时】,根据解答重复启动无数次也无果。

除了这些，在网上搜索相关词条和再一次确认启动路径之外就没做过其他事了。

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/56193605/c69ed92c-3a19-4310-aeae-c0f8d9e33203)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
> 就是打死不更新呗

看上去该用户是使用了网络代理软件，但又没有解除 Loopback 限制，导致整个 Snap Hutao 无法联网

**Comment by YodaYuuk1** [comment]
抱歉，脑抽了犯了最低级的错误。
在bot发消息之后就更新到了最新版本，看bot已经移动帖子了便没再正文更新。


我肉身在国外，虽然电脑中装有clash但没开启，也没使用过，反正能启动就行，无伤大雅。

谢谢回复。
