### ISSUE TITLE
[Feat]: 增加管理员权限要求提示

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#172]
### 你想要实现或优化的功能？

当用户设置时游戏启动路径，应当判断游戏安装路径是否有UAC权限限制（比如`C:\Program Files\Genshin Impact\Genshin Impact Game`）

在这种情况下，即使不使用帧数解锁功能，也需要以管理员权限通过胡桃启动游戏。所以需要在用户设置完路径后弹窗提示，或在启动游戏界面提示用户权限不足。

**Comment by Lightczx** [comment]
v1.1.20
