### ISSUE TITLE
[Feat]: Add More Information of 653366069 Network Error

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1720]
### Background & Motivation

So far, the `653366069` error has not shown any information. Most users may not even know this error is related to network issues.

### Detail of the Feature

- Display more details of the request
  -  [ ] Requested host
  -  [ ] Error type (DNS error, certificate error, connection reset, etc.)
- [ ] Ask the user to contact for support if seeing this error frequently

**Comment by qmhu123** [comment]
![屏幕截图 2024-07-12 021419](https://github.com/user-attachments/assets/bee1e357-22d9-45c3-b033-2ea97f70e074)

Just in case you need this. I am consistently having this issue ever since the sync inventory function is released.

**Comment by qhy040404** [comment]
@qmhu123 Looks like a HoYoLAB account. Currently we don't support to sync inventory for HoYoLAB accounts
