### ISSUE TITLE
活动“安固四方之述演”，进入/退出活动导致帧率解锁失效。 Event：”Mutual Security Enhancing Simulation"; Entering or leaving challenges leads invalid frame rate limit unlocking.

### ISSUE THREAD

**Issue by G-EZhun** [DGP-Studio/Snap.Hutao#1723]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3737

### Snap Hutao 版本

1.10.3.0

### 设备 ID

B89D3A58225453A2F5504FDC37AE1860

### 问题分类

游戏启动器

### 发生了什么？

基本如题。在使用Snap Hutao解锁帧率进入游戏中该活动后，帧率上限将被锁定在原在游戏内设定的帧率上限（30/45/60）；退出活动后该问题依然持续。(知道）再次使用Snap Hutao保持解锁帧率并重新进入后其他暂未发现问题，但进入任何该活动的相关挑战将会复现（帧率上线解锁失效）。顺带一提，该活动将与短期内（3天）结束，相较于单纯解决该问题，更希望开发者能借此发现活动导致帧率上限解锁失效的根本因素，从而改进并减少之后活动出现该问题的概率。
Basically with the title. After using Snap Hutao to unlock the frame rate and enter the game, the frame rate limit will be locked at the original frame rate limit set in the game (30/45/60); The issue persists after exiting the activity. (Until)After using Snap Hutao again with the unlocked frame rate limit and re-enter, no other issues were found; any inside challenges of this event  will cause replication(s) (unlocking at frame rate limit will fail). By the way, this activity will end in a short term (3 days). Compared to simply solving the problem, I rather hope developers to discover the fundamental factors that cause the failure of unlocking the frame rate limit during the event, so as to improve and reduce the probability of this (or any similar) problem occurring in future activities.

### 你期望发生的行为？

帧数上限解锁不在受到特定活动影响，始终生效。：）
Unlocking the frame rate limit is no longer affected by specific game events and always takes effect. :)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Kmfte** [comment]
进入副本也会导致该问题出现

**Comment by G-EZhun** [comment]
> 进入副本也会导致该问题出现

同意，似乎是原神hutao都更新版本后出现的问题（表示不确定）。

**Comment by Lightczx** [comment]
让米哈游修

**Comment by G-EZhun** [comment]
Damn，谢了
