### ISSUE TITLE
[Bug]: 解锁帧率不能稳定运行

### ISSUE THREAD

**Issue by yuebei1982** [DGP-Studio/Snap.Hutao#1724]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4529

### Snap Hutao 版本

1.10.3.0

### 问题分类

游戏启动器

### 发生了什么？

帧率解锁可以运行，但只能成功运行在进入游戏的第一次。当我进入某个圣遗物副本，读条加载后，帧率就恢复限制60帧的状态。但进行地图传送并加载，并不会影响解锁帧率。只有进入副本会导致解锁帧率失效。实际上4.7刚开始时我更新了胡桃，成功运行了一段时间。但从昨天这样出现了这个问题。

### 你期望发生的行为？

请开发者大佬看看。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
让米哈游修
