### ISSUE TITLE
[Bug]: 解锁帧率在切换场景后失效

### ISSUE THREAD

**Issue by Sivo-Moon** [DGP-Studio/Snap.Hutao#1727]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Win11专业版

### Snap Hutao 版本

1.10.3.0

### 设备 ID

ADC615F8542AF8B740B4E633F4079677

### 问题分类

游戏启动器

### 发生了什么？

官服! 在6月13日原神下午热更新(几百M)后, 解锁帧率在切换场景后(秘境、尘歌壶等)失效。
刚进入游戏能正常解锁高帧, 但只要切换地图后就会锁定60帧。电脑配置方面没问题(13600k+4070ti),之前从未遇到过。
开始以为是上周更新了新发布的N卡驱动(555.99)的问题,在装回旧版本驱动后问题依然存在。估计与N卡驱动更新没啥关系

### 你期望发生的行为？

希望能同以前一样正常使用高帧

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
重装系统就可以了
暂时没有其他的解决方法

**Comment by Lightczx** [comment]
在启动游戏前重命名 HoYoKProtect.sys
在启动游戏并解锁帧率后将其重命名回来再进门
此时理论上只要不进行多人游戏就能持续解锁
进行多人游戏会导致 10351-4001 错误

**Comment by Sivo-Moon** [comment]
> 在启动游戏前重命名 HoYoKProtect.sys 在启动游戏并解锁帧率后将其重命名回来再进门 此时理论上只要不进行多人游戏就能持续解锁 进行多人游戏会导致 10351-4001 错误

谢谢回复 但经个人测试, 即使不联机大约每分钟也都会报错一次 然后把你踹下线, 反复登录依旧如此...

**Comment by Lightczx** [comment]
由于太多人眼瞎，重新打开这个Issue

**Comment by aaahai00** [comment]
wc把注册表清了重新登录就可以了，你们试试

**Comment by aaahai00** [comment]
> wc把注册表清了重新登录就可以了，你们试试

然后我用胡桃登录了我想要的账号，然后又挂了，好像找到问题原因了

**Comment by pcdlrzxx** [comment]
@Lightczx 这个bug是新版本才出现的吗，感觉之前的版本貌似没有

**Comment by ydtname** [comment]
同进入副本会解帧失效，win10 22H2

**Comment by KNC11349** [comment]
重装系统也无法解决，真想骂死狗策划，2024还锁60，自己不开还防着别人开

**Comment by hsxazj** [comment]
进入副本或者深渊后 解锁帧率失效

**Comment by aaahai00** [comment]
https://github.com/34736384/genshin-fps-unlock/issues/415#issuecomment-2183856728
我自己试了可以用

**Comment by mm118706** [comment]
> 重新安装系统 暂时没有其他解决方法



> [34736384/genshin-fps-unlock#415 (评论)](https://github.com/34736384/genshin-fps-unlock/issues/415#issuecomment-2183856728) 我自己试了试

13600k+4070ti,使用b服，之前从没遇到过这个情况，刚进去可以满帧，但是一旦进副本或者尘歌壶，就马上回60帧。不想重装系统，使用下面引用的软件可以解决。

**Comment by aaahai00** [comment]
> > 重新安装系统 暂时没有其他解决方法
> 
> 
> 
> > [34736384/genshin-fps-unlock#415 (评论)](https://github.com/34736384/genshin-fps-unlock/issues/415#issuecomment-2183856728) 我自己试了试
> 
> 13600k+4070ti,使用b服，之前从没遇到过这个情况，刚进去可以满帧，但是一旦进副本或者尘歌壶，就马上回60帧。不想重装系统，使用下面引用的软件可以解决。

主要重装也不是一劳永逸，迟早还出问题

**Comment by Lightczx** [comment]
可以试一下这个，比较危险，游戏很容易崩
https://github.com/DGP-Studio/Snap.Hutao/actions/runs/9630735403

**Comment by ayakasuki** [comment]
+1 看来不只是我遇到

**Comment by deguo-xier** [comment]
+1，打新活动和副本就会只有60hz

**Comment by killerqueen765** [comment]
+1最近两天才遇到，进游戏帧率解锁正常，但是开启地图传送后就锁60了

**Comment by RealXLFD** [comment]
+1

**Comment by xiaozhonghh** [comment]
确实 切换场景比如进矿洞和旧日海会掉回60 传送到壶里也会 进秘境和副本也会 只能在大世界高帧

**Comment by Xiongb1113** [comment]
解锁帧率又会失效了

**Comment by Lightczx** [comment]
## TLDR

任何版本大于 `2024.6.25.4` 的胡桃测试版都具有新版解锁帧率的方式
目前没有提供界面上的开关来切换新老解锁方式

要尝试新版解锁，你需要找到测试版的`Userdata.db`并通过任何DBMS软件执行以下SQL

``` sql
INSERT INTO settings (key, value) VALUES("Launch.UnlockerKind", "Island")
```

执行成功后再次打开测试版胡桃即会使用新版解锁方式进行解锁

## 为什么老方式无效了

老版解锁使用了 `WriteProcessMemory` 对特定的目标帧数内存地址进行写入操作以达到修改最高帧率的目的  
然而米哈游更新了他们的反作弊驱动，屏蔽了所有的进程外内存操作

## 为什么是进入副本后才重新锁了60帧

只要不切换场景，实际上可以直接退出胡桃，最大帧率设置会始终有效  
在切换场景后，会重新读取一次用户的画质设置，覆盖先前设置的最大帧率  
老版解锁帧率通过每间隔一段时间强制设置目标帧率来解决这个问题

但是由于米哈游的反作弊机制启动时间随机，很有可能在进入大世界之后才会完成启动，所以大世界的帧率会达到设置的目标值

也是由于启动的时间完全随机，导致某些人在登陆界面能够保持目标帧率，而进入大世界已经锁定60（登录界面与大世界是不同的场景）

## 新版解锁是怎么做的

注入

通过直接以游戏自己的权限操作目标内存地址，暂时不会受到反作弊驱动的影响

## 为什么国际服没事

洋大人，管的宽  
国内外挂多环境差

**Comment by huzeyu123** [comment]
米哈游管的真宽

**Comment by xiaozhonghh** [comment]
新版解锁会在下个胡桃版本上线吗

**Comment by zh8416** [comment]
我按照作者方法上车了，90帧以下实在是玩不下去

**Comment by ayakasuki** [comment]
> 我按照作者方法上车了，90帧以下实在是玩不下去

你好可以问下 Userdata.db 这个文件在哪吗

**Comment by hxngu** [comment]
> > 我按照作者方法上车了，90帧以下实在是玩不下去
> 
> 你好可以问下 Userdata.db 这个文件在哪吗

打开胡桃工具箱后点击设置，拖到下面有个数据文件夹，Userdata.db在里面

**Comment by XyingGen1** [comment]
> > > 我按照作者方法上车了，90帧以下实在是玩不下去
> > 
> > 
> > 你好可以问下 Userdata.db 这个文件在哪吗
> 
> 打开胡桃工具箱后点击设置，拖到下面有个数据文件夹，Userdata.db在里面

abms软件是什么啊，需要用abms软件运行Userdata.ab吗？

**Comment by ayakasuki** [comment]
> > > 我按照作者方法上车了，90帧以下实在玩不下去
> > 
> > 
> > 你好可以问下Userdata.db这个文件在哪吗
> 
> 打开胡桃工具箱然后点击设置，拖到下面一个数据文件夹，Userdata.db在里面

好的 谢谢

**Comment by Allureall** [comment]
催更一下，实在难受死了

**Comment by acacia69** [comment]
催更啊，60帧ppt，不会玩了已经

**Comment by GUA7GUA** [comment]
【胡桃工具箱最新解锁帧率教程】https://www.bilibili.com/video/BV1Py3re5EFj?vd_source=e2c1143c5e25355139878b7d1f3bdb17
这是B站的教程，估计没那么快更正式版工具箱，看mhy下个版本的反作弊机制怎么更新再说，别前面更了后面又失效，徒增工作量

**Comment by yeliang121** [comment]
没有解决问题仍然存在

**Comment by zh8416** [comment]
> 没有解决问题仍然存在

启动游戏里要自己切换解锁帧率方式，我的已经没问题了

**Comment by yeliang121** [comment]
确实需要手动切换解锁帧率方式，已经无问题
