### ISSUE TITLE
哈希值说是有错无法安装 

### ISSUE THREAD

**Issue by xixi3535** [DGP-Studio/Snap.Hutao#1729]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.3737

### Snap Hutao 版本

1.10.3.0

### 问题分类

安装和环境

### 发生了什么？

无id，开始就下不了，诊断工具无用
哈希值说是有错无法安装 
![QQ图片20240615212229](https://github.com/DGP-Studio/Snap.Hutao/assets/172910572/577c1c8d-25cf-4512-a34d-8646a8944d47)
![QQ图片20240615212239](https://github.com/DGP-Studio/Snap.Hutao/assets/172910572/f7263c7a-954d-4960-95ab-7e1d89006f5a)
![QQ图片20240615212539](https://github.com/DGP-Studio/Snap.Hutao/assets/172910572/9b9402aa-2541-4af2-a119-8c94262f47f0)

### 你期望发生的行为？

安装成功

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
别下了，我们没钱了，请直接从Github release页面直接下载，不要使用官网的直链/自动部署工具
