### ISSUE TITLE
[Feat]: 增加怪物大立绘

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1733]
### 背景与动机

RT，现在没有怪物大立绘，例如下图

（Updated）

![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/2582c37e-bdbb-46ac-b8fd-34978410a2f2)
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/e4535758-eb31-439a-ac5e-7476c30cda3d)

### 想要实现或优化的功能

增加怪物大立绘

**Comment by Masterain98** [comment]
这是模型吧

**Comment by Mikachu2333** [comment]
emm，我的锅，截图不当，我update一下换个图

**Comment by Lightczx** [comment]
只有Boss才有立绘，没有太大的意义
