### ISSUE TITLE
[Bug]: 帧率解锁又失效了

### ISSUE THREAD

**Issue by Mugenhasen** [DGP-Studio/Snap.Hutao#1738]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3737

### Snap Hutao 版本

1.10.3.0

### 设备 ID

F84C088FB29347C07DFA75877BE44354

### 问题分类

游戏启动器

### 发生了什么？

如图，胡桃内已解锁帧率上限，但游戏内仍锁60帧（垂直同步已关闭）
![QQ截图20240617154042](https://github.com/DGP-Studio/Snap.Hutao/assets/88937217/eab295ff-201c-4251-b40a-65ec1b455d4f)
![QQ截图20240617154014](https://github.com/DGP-Studio/Snap.Hutao/assets/88937217/dbe867b0-7302-44c9-b4e6-1f9b54b56688)
![QQ截图20240617154156](https://github.com/DGP-Studio/Snap.Hutao/assets/88937217/fd2dfe89-0ab7-448d-823d-31f0f718e450)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1727

**Comment by Masterain98** [comment]
Duplicate of #1727

**Comment by Mugenhasen** [comment]
> #1727

Windows系统更新后的问题？

**Comment by LucioLusen** [comment]
客户端显示解锁了，进游戏确实是高帧率，但是一进副本就锁60帧了，出来之后就一直是60……
