### ISSUE TITLE
启动游戏功能无法使用

### ISSUE THREAD

**Issue by sxk124** [DGP-Studio/Snap.Hutao#174]
### Windows 版本

22H2（22621.675）

### Snap Hutao 版本

1.1.19.0

### 发生了什么？

在管理员启动下无法设置游戏路径，后来闪退后普通启动下设置成功，但是无法启动游戏。具体为按下启动游戏后按键给予了交互反馈但无事发生。

### 你期望发生的行为？

按下启动游戏后能够启动原神客户端或者启动器

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
更新到1.1.20
