### ISSUE TITLE
[Bug]: Hutao1.10.4.0更新失败，下载

### ISSUE THREAD

**Issue by JackLyan233** [DGP-Studio/Snap.Hutao#1749]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows10 22H2 (19045.4529）

### Snap Hutao 版本

1.10.3.0

### 设备 ID

773CC0EDEF962E78C637A4799BD3404C

### 问题分类

安装和环境

### 发生了什么？

Hutao1从1.10.3.0更新到.10.4.0失败，启动显示要更新后点下载，下载到一部分后显示下载失败
尝试运行UpdateCache中的Snap.Hutao.msix来更新，因为上次1.10.2.0更新到1.10.3.0也是报错，这样就成功了，但这次却还是报错：
![屏幕截图 2024-06-19 215102](https://github.com/DGP-Studio/Snap.Hutao/assets/173274996/0c27790c-b88a-45f8-8913-c4eba67f13c1)
报错如下：应用安装失败，错误消息: 从  (Snap.Hutao.msix)  使用程序包 60568DGPStudio.SnapHutao_1.10.4.0_x64__wbnnev551gwxy 中的目标卷 C: 执行的部署 Add 操作失败，错误为 0x80080206。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=235160。 (0x80080206)
现在不知道要怎么更新了

### 你期望发生的行为？

希望以后我的胡桃能正常更新

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
删掉重下

**Comment by JackLyan233** [comment]
重新下可以了，感谢
