### ISSUE TITLE
[Bug]: 胡桃数据库加载慢

### ISSUE THREAD

**Issue by DICKQI** [DGP-Studio/Snap.Hutao#175]
### Windows 版本

22000.1098

### Snap Hutao 版本

1.1.20.0

### 发生了什么？

点击深渊统计，还没加载好的时候整个界面都会卡住，体验不是很好。深渊统计这个界面是最卡的，其他界面加载过程中也会卡住，但是加载速度比较快没卡这么久

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Masterain98** [comment]
会卡多久？胡桃数据库功能卡顿时是在从云端获取数据，没数据自然不能加载。

**Comment by fatesealed** [comment]
确实卡。。。

**Comment by Masterain98** [comment]
> 确实卡。。。

请给出具体的信息

**Comment by Lightczx** [comment]
卡顿是指数据加载慢（界面空白）还是界面无响应（无法拖动窗口）？
@DICKQI @fatesealed

**Comment by fatesealed** [comment]
> > 确实卡。。。
> 
> 请给出具体的信息
打开深渊统计时会卡顿  一般是数据加载慢 偶尔会伴随着界面无响应 卡顿得有3s左右 开了梯子的情况下 而且重复打开会重复卡

**Comment by Lightczx** [comment]
如果重复打开依然卡顿，属于电脑性能问题
可以提供一下处理器/显卡的相关信息么

**Comment by fatesealed** [comment]
应该不是 5800h 3060laptop 
我重装一下试试看

**Comment by Lightczx** [comment]
> 应该不是 5800h 3060laptop 我重装一下试试看

其他的界面会有卡顿么，动画，滚动

**Comment by fatesealed** [comment]
> > 应该不是 5800h 3060laptop 我重装一下试试看
> 
> 其他的界面会有卡顿么，动画，滚动

没有 我录个屏吧

**Comment by fatesealed** [comment]
https://www.bilibili.com/video/BV1WP411A7EX/?vd_source=2736b9aff87daad005e7c59b2bff0ec4
我记得hutao初版我就按了 然后好久没用 之后一下子就升级到最新的了 是不是可能和这个有关？
话说hutao怎么卸载...

**Comment by Lightczx** [comment]
> https://www.bilibili.com/video/BV1WP411A7EX/?vd_source=2736b9aff87daad005e7c59b2bff0ec4 我记得hutao初版我就按了 然后好久没用 之后一下子就升级到最新的了 是不是可能和这个有关？ 话说hutao怎么卸载...

视频中的卡顿属于正常现象

**Comment by fatesealed** [comment]
> > https://www.bilibili.com/video/BV1WP411A7EX/?vd_source=2736b9aff87daad005e7c59b2bff0ec4 我记得hutao初版我就按了 然后好久没用 之后一下子就升级到最新的了 是不是可能和这个有关？ 话说hutao怎么卸载...
> 
> 视频中的卡顿属于正常现象

噢 好吧 我咋记得之前那个snap原神 这个功能体验贼顺畅来着

**Comment by Masterain98** [comment]
@Lightczx 建议增加加载动画
