### ISSUE TITLE
[Bug]: 切换国际服提示数据异常

### ISSUE THREAD

**Issue by TangChang** [DGP-Studio/Snap.Hutao#1750]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045,4529

### Snap Hutao 版本

1.10.40.0

### 问题分类

游戏启动器

### 发生了什么？

[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/15903774/Snap.Hutao.Error.Log.txt)
![2024-06-20_0-29-37](https://github.com/DGP-Studio/Snap.Hutao/assets/3685862/f8cb6cf5-c5e8-4bbc-92ad-440dea1fca28)
转换国际服启动后提示数据异常，重新切回国服可以正常使用

### 你期望发生的行为？

正常使用国际服

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@TangChang 你是从哪个选项切换到哪个选项的

**Comment by TangChang** [comment]
> @TangChang 你是从哪个选项切换到哪个选项的

从官方服|official|default 切换到 国际服|official|default
之前是没问题的 昨天更新到最新版本就不行了 但是我不确定有没有直接关系

**Comment by TangChang** [comment]
不知道怎么导致的 但是换到国际服|official|official 可以正常游玩了
