### ISSUE TITLE
原神亚服现在10尾数的uid，正常邮箱密码登录登录后刷新cookie后报错

### ISSUE THREAD

**Issue by CheneyBear** [DGP-Studio/Snap.Hutao#1751]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4529

### Snap Hutao 版本

1.10.4.0

### 设备 ID

3A0EE97C4DC5A917AF3C004E04D1F5C6

### 问题分类

米游社账号面板

### 发生了什么？

无

### 你期望发生的行为？

目前亚服uid是10尾数，我的uid是1803539873。
可能是因为这个原因导致邮箱密码登录成功后，刷新cookie，依然没有亚服的账号出现。
祈愿的界面也没有亚服uid选项。
报错是，cookie无效。红色叉叉，报错状态653366069
![1111111](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/7571f5c3-ce71-4fa0-8cb2-20689aa453bb)

我怀疑是因为萌新亚服注册的号都是18开头的10位数导致，无法导入uid。
烦请更新。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
国际服登录需要全程开梯子

**Comment by CheneyBear** [comment]
我开了梯子，全程开的梯子，依然没法录入。你的国际服是9位数的uid。我的uid是最新的亚服已经新增到十位数了。

**Comment by Masterain98** [comment]
#1358

**Comment by CheneyBear** [comment]
此cookie无效，操作失败。

**Comment by CheneyBear** [comment]
> #1358
我看到1358说1.9.6版本就已经解决了这个问题。但是现在已经是1.10.4.0依然没有解决。
不存在老亚服和新亚服的区别，互相能加好友，只是因为人数太多了，导致uid数字变多一位数。

**Comment by CheneyBear** [comment]
> 国际服登录需要全程开梯子
我全程开了梯子。


> #1358
我看到1358说1.9.6版本就已经解决了这个问题。但是现在已经是1.10.4.0依然没有解决。
不存在老亚服和新亚服的区别，互相能加好友，只是因为人数太多了，导致uid数字变多一位数。
我现在有报错啊，你们看看，或者方便远程可以预约个时间。

**Comment by qhy040404** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/b21ab8a3-6aae-42f5-9b97-b35b956d8df3)

《我开了梯子》

**Comment by qhy040404** [comment]
27.19是武汉

**Comment by CheneyBear** [comment]
> 27.19是武汉

可是，我能连国际版游戏，付费界面是日元。
能上谷歌搜索，能看youtube。
要不你远程我OK嘛？
我现在胡桃里hoyoverse登录界面是日语。

**Comment by CheneyBear** [comment]
> 27.19是武汉

如果不开梯子，现在会报错，原神开门那里见不到门，会报错退出来。
开了梯子，能进游戏，延迟很低。
我现在能用谷歌搜索，甚至在咱们app里面是日语登录界面。

**Comment by Masterain98** [comment]
建议看下文档中关于网络代理的部分

**Comment by CheneyBear** [comment]
1、有文档的链接嘛？
2、我家梯子模式就是这样，能上出去，但是代理这里就是空的。很奇怪我用代理后的抖音b站的ip地址都是香港或者日本，看我选择的地方是那里。但是胡桃软件里面，看到我还是在中国，并且在27武汉？

**Comment by CheneyBear** [comment]
> 建议看下文档中关于网络代理的部分

[CheneyBear](https://github.com/CheneyBear) commented [now](https://github.com/DGP-Studio/Snap.Hutao/issues/1751#issuecomment-2180246736)
1、有文档的链接嘛？
2、我家梯子模式就是这样，能上出去，但是代理这里就是空的。很奇怪我用代理后的抖音b站的ip地址都是香港或者日本，看我选择的地方是那里。但是胡桃软件里面，看到我还是在中国，并且在27武汉？

**Comment by Mikachu2333** [comment]
https://hut.ao/zh/advanced/exceptions.html#_653366069-%E8%AF%B7%E6%B1%82%E5%BC%82%E5%B8%B8

乐

**Comment by CheneyBear** [comment]
> 建议看下文档中关于网络代理的部分

关于代理部分，有以下疑问。
1、如果没有搭梯子，根本不可能账号密码输入正确后，进入登录成功的界面。
2、为什么胡桃的反馈中心这里看到的代理是空的，所在地ip依然在国内？
![22222222](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/e72cac60-997f-4022-9d87-19ba4dc0f9a2)
![3333333](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/e2faeeb7-8696-4fcc-8c3c-67dc48bc892b)

**Comment by CheneyBear** [comment]
> https://hut.ao/zh/advanced/exceptions.html#_653366069-%E8%AF%B7%E6%B1%82%E5%BC%82%E5%B8%B8
> 
> 乐
> 
> ![图片](https://private-user-images.githubusercontent.com/63829496/341361012-819b6a47-4987-44ec-a8c4-44960ed5468f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzcxNDksIm5iZiI6MTcxODg3Njg0OSwicGF0aCI6Ii82MzgyOTQ5Ni8zNDEzNjEwMTItODE5YjZhNDctNDk4Ny00NGVjLWE4YzQtNDQ5NjBlZDU0NjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5NDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OTE2NTQzNGVjMzVkNTE4OWYwZWQwZjMwNTJmYzdiNThmYmVjM2VlZDc2ZGVhY2Q5OGYxZTAxNWU0ZjIzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2HfhhYhPUZrTEXOxn7QpZ0PJ9AE7csB9f57pyMmND24)

![5555555](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/85e0bc31-1323-4adf-8f80-8c28ca0805cf)

好的，按照你们的提示，我早就解除了lookback的限制，可是依然还是报错。
明明我翻墙出去能正常上网登录hoyolab，能发帖，能玩游戏，但是胡桃认为我没有翻墙，没有使用代理，ip地址在国内？这是怎么回事？请结合上面三张图看，这里是一张，上面还有两张图。

**Comment by Mikachu2333** [comment]
1. 请注意微信隐私与uid信息
2. 请检查下图设置
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/c13db490-7497-48ff-b9b2-c39df35e6dc4)

**Comment by CheneyBear** [comment]
> 1. 请注意微信隐私与uid信息
> 2. 请检查下图设置
>    ![图片](https://private-user-images.githubusercontent.com/63829496/341362796-c13db490-7497-48ff-b9b2-c39df35e6dc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzcyODAsIm5iZiI6MTcxODg3Njk4MCwicGF0aCI6Ii82MzgyOTQ5Ni8zNDEzNjI3OTYtYzEzZGI0OTAtNzQ5Ny00OGZmLWI5YjItYzM5ZGYzNWU2ZGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDE5MmEwMTc0MDgwYmQ0MDcyYWQwMWY5OTFmM2MyZDdiMmIxNGRiYzM0NTExNmY4MWZjMDNlMzg2YWIzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dyJE82hg_YDLGQ4BZvoCjvAdX0CXZyXy1FtmOGDMfJs)

上面我有一张图，我已经解除了windows容器loopback限制。这个很早就操作了。

**Comment by Mikachu2333** [comment]
请先重启一次胡桃（注意要把任务栏的后台也退了）

**Comment by Lightczx** [comment]
WebView与胡桃不共享网络设置，WebView视图能打开不代表胡桃本体能够正常访问网络

**Comment by qhy040404** [comment]
你的设备ip还在国内，要么是你的梯子不是全局，要么是胡桃没走梯子

**Comment by CheneyBear** [comment]
> 请先重启一次胡桃（注意要把任务栏的后台也退了）

![335555555](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/833f7271-f505-484e-b2a1-efd733565ac1)
![666666](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/3a7e4068-b50e-4cd6-a365-2dd7e9cd3ccf)

已经按要求，重新后台打开。但是问题依旧。

**Comment by CheneyBear** [comment]
> 你的设备ip还在国内，要么是你的梯子不是全局，要么是胡桃没走梯子

如果胡桃没有走梯子，胡桃里内嵌的hoyoverse却可以登录么？

这是什么逻辑？

大佬们能否远程协助一下？

**Comment by CheneyBear** [comment]
> WebView与胡桃不共享网络设置，WebView视图能打开不代表胡桃本体能够正常访问网络

我需要怎么设置，能让我的westworld翻墙软件带着胡桃起飞？

我选择的是全局模式，其他软件都能正常使用，比如国际服的原神，浏览器，看youtube等。

**Comment by CheneyBear** [comment]
> 你的设备ip还在国内，要么是你的梯子不是全局，要么是胡桃没走梯子





搞定了，我使用了梯子里面的一个功能，叫做“编辑PAC用户自定规则”
输入如下代码：
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet

||google.com
||*.google.com

||hut.ao/
||*.hut.ao/

||hoyoverse.com/
||*.hoyoverse.com/

在网络模式，从全局模式，调整为PAC自动模式，这样的话强制，胡桃和hoyoverse连代理。
即便已经成功绑定了，我看到我的ip地址胡桃显示仍然是27武汉。因此这里不影响真正是否搭梯子，影响的是代理地址这里是空着还是有网址。
以下三张图是操作步骤，共享。
![7777777](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/c70e2e20-36a1-47e4-a8e9-c583289f742b)
![888888](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/3717c1b3-e538-4044-a784-5f336c67ca57)
![88888877777](https://github.com/DGP-Studio/Snap.Hutao/assets/173303904/1fd3d244-85b4-48cf-9ca5-44e6676ae5cd)



> WebView与胡桃不共享网络设置，WebView视图能打开不代表胡桃本体能够正常访问网络

已解决，请看上图。

> 请先重启一次胡桃（注意要把任务栏的后台也退了）

已解决，请看上图。

> 建议看下文档中关于网络代理的部分
已解决，请看上图。
