### ISSUE TITLE
[Bug]: 解锁帧率功能异常

### ISSUE THREAD

**Issue by PeaceFamily000** [DGP-Studio/Snap.Hutao#1752]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4529

### Snap Hutao 版本

1.10.4.0

### 设备 ID

5965FEAAC9436B9D1E74B91C1FFCEC89

### 问题分类

游戏启动器

### 发生了什么？

在游戏中切换维度会导致解锁帧率失效（如从提瓦特传送至旧日之海,亦或是进入秘境或深境螺旋等，但不包括在提瓦特大陆上的传送）
![原神 2024_6_20 9_43_51](https://github.com/DGP-Studio/Snap.Hutao/assets/173323486/222342d2-a667-4bd0-9e63-cf49817006b8)
![原神 2024_6_20 9_44_12](https://github.com/DGP-Studio/Snap.Hutao/assets/173323486/230a5f98-8c82-42cf-9fa7-431a77cb910f)

![原神 2024_6_20 9_45_55](https://github.com/DGP-Studio/Snap.Hutao/assets/173323486/0b9b9396-83e7-4337-994a-9057466d1734)

### 你期望发生的行为？

希望可以尽快修复。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1727

**Comment by KNC11349** [comment]
+1，星铁大更新那天我也这样了
