### ISSUE TITLE
桌面上无法启动

### ISSUE THREAD

**Issue by libiekaiyihua** [DGP-Studio/Snap.Hutao#1757]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4412

### Snap Hutao 版本

1.10.4.0

### 设备 ID

51B1ECF75328081D6077782FFDF4ABCF

### 问题分类

其它

### 发生了什么？

桌面上无法启动，重新下载安装不行，但开始菜单能正常启动
![Uploading IMG_20240620_215514.jpg…]()

### 你期望发生的行为？

希望能桌面上启动

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
图没传上来

**Comment by libiekaiyihua** [comment]
> 图没传上来

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/154238805/b8647b8f-9f0c-4cf2-ad89-1885bdb3d404)

**Comment by libiekaiyihua** [comment]
> https://aka.ms/vs/17/release/vc_redist.x64.exe

解决了，能正常启动了，谢谢

**Comment by libiekaiyihua** [comment]
> https://aka.ms/vs/17/release/vc_redist.x64.exe

解决了，能桌面上正常启动，谢谢
