### ISSUE TITLE
进入副本或者深渊时，解锁帧率会失效

### ISSUE THREAD

**Issue by LastElysia** [DGP-Studio/Snap.Hutao#1758]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3737

### Snap Hutao 版本

1.10.4.0

### 设备 ID

B5BA68FFE7B2C64941A06A269E14F8DC

### 问题分类

安装和环境

### 发生了什么？

在胡桃工具箱上显示成功解锁帧率上限，进入游戏也是正常解锁帧率上限。但是进入副本或者深渊时候就会变回60帧。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
Duplicate of #1727

**Comment by Lightczx** [comment]
#1727

**Comment by aaahai00** [comment]
我现在总结了一套流程
1，使用官方启动器登录（修改一些设置）
1，使用该解锁工具解锁（待会用胡桃试试）
各位可以试试有没有效果

使用了一个有问题的注册表尝试，使用官方启动器启动后然后再使用解锁工具进入，可以解决这个问题了
