### ISSUE TITLE
错误通知过多无法一键清除

### ISSUE THREAD

**Issue by hoiyuyiu** [DGP-Studio/Snap.Hutao#1759]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4593

### Snap Hutao 版本

1.10.4.0

### 设备 ID

26F3088D83831A15295F53BD86D4CFA1

### 问题分类

用户界面

### 发生了什么？

可能是由于默认最小化的原因，导致后台一直累计错误信息，导致再次通过快捷方式打开时会看到满屏错误通知，而且无法一键清除
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/61400426/4cf89471-0a4b-47cf-b86b-bef20eb1e76f)

### 你期望发生的行为？

能一件清除错误通知/同一类型通知之类的快捷操作

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by lonelyzerg** [comment]
我也遇到一样的问题。现在我把自动刷新关闭了

**Comment by HaloStudent233** [comment]
其实可以点右下角隐藏的

**Comment by lonelyzerg** [comment]
> 其实可以点右下角隐藏的

但是如果需要查看别的通知的时候还是必须清除所有现有通知

**Comment by 144-144** [comment]
可以用胡桃的自动点击功能自动点击错误消息的叉号。

**Comment by Lightczx** [comment]
implmented by https://github.com/DGP-Studio/Snap.Hutao/commit/bad60f1d65806656103ce482c63a84b805961925
