### ISSUE TITLE
[Feat]: 希望统一一下各个页面的左右内边距

### ISSUE THREAD

**Issue by CN-traveler** [DGP-Studio/Snap.Hutao#176]
### 你想要实现或优化的功能？

1.1.20版本下，不同页面的的内边距有较大的差异，界面看起来不协调希望统一内边距。

**Comment by Lightczx** [comment]
除了设置与启动游戏页面，其他的边距应该都是统一的
上述的页面也是统一的

**Comment by Lightczx** [comment]
fixed internally
