### ISSUE TITLE
There is a problem with the frame count

### ISSUE THREAD

**Issue by 1061704910** [DGP-Studio/Snap.Hutao#1760]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.10.4.0

### 设备 ID

1061704910@qq.com

### 问题分类

其它

### 发生了什么？

Every time I go from the big world to the activity or the dust pot it changes back to 60 frames

### 你期望发生的行为？

Quickly repair Thank you!

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
Duplicate of #1727
