### ISSUE TITLE
[Network]: HttpReque

### ISSUE THREAD

**Issue by Lingchen218** [DGP-Studio/Snap.Hutao#1761]
### 提交你的网络诊断报告

<img width="886" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/48959004/261ef65f-07d9-4080-a13b-b8bec05aa2bc">

### 你的地理位置

深圳

### 你的运营商

中国联通

### 你的问题

客户端图片下载错误

### 你的问题（补充）

<img width="886" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/48959004/261ef65f-07d9-4080-a13b-b8bec05aa2bc">

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/8248db19-bae6-4c29-bb06-42273399bbb9)
我不觉得你上传了

**Comment by Lingchen218** [comment]
我从git上下载，并卸载旧版本，现在没有这个报错了，之前用的是旧版本
