### ISSUE TITLE
[Bug]: 解锁帧率功能不能很好的运行

### ISSUE THREAD

**Issue by GavinWMI** [DGP-Studio/Snap.Hutao#1762]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3448

### Snap Hutao 版本

1.10.4.0

### 设备 ID

A2EBC8574AD3EB0E1B2B2F8801DB5EF5

### 问题分类

游戏启动器

### 发生了什么？

之前版本的时候很少遇到解锁帧率功能不能很好工作的情况。因为我是多号党，通常关掉上一个账号后就立刻进入下一个账号。大部分情况下都是进入游戏并解除锁帧，偶尔会弹出保护功能（模块？）启动未能成功解锁？的提示，这个是很早之前就有，所以没觉得有什么问题。再次开启游戏就进入游戏并且正常解锁了帧率 。
但从上个版本开始我经常发现，没有弹出提示，成功进入游戏后依然被锁定在60帧。退出再启动，也是偶尔成功，偶尔依然锁定。胡桃是管理员权限启动的。总而言之，就是现在的解锁帧率功能相较之前非常不可靠。希望可能解决一下。

### 你期望发生的行为？

让解锁帧率功能变得可靠！

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1727
