### ISSUE TITLE
無法透過第三方工具"YaeAchievement.exe"匯入成就 

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#1769]
使用"YaeAchievement.exe"取得成就後 輸入1選擇匯入 Snap Hutao 後
自動開啟胡桃工具箱的管理員模式 
![未命名](https://github.com/DGP-Studio/Snap.Hutao.Deployment/assets/107019852/951c17d1-3fcc-44e0-99ff-732481b6ce3b)
工具箱如同畫面中所看到的 整個成就頁面完全空白

**Comment by Lightczx** [comment]
#1763
