### ISSUE TITLE
[Bug]: OBS无法单独采集胡桃工具箱窗口

### ISSUE THREAD

**Issue by Cirno-NULL** [DGP-Studio/Snap.Hutao#1771]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3737

### Snap Hutao 版本

1.10.4.0

### 设备 ID

9657CD5ABA84BA6E6C780AB2B079ABF2

### 问题分类

其它

### 发生了什么？

OBS无法单独捕捉胡桃工具箱界面
只会捕捉到一个背景色窗口
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/41545185/c5c5515a-a2f7-420f-8b33-235ced8112c4)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/41545185/bf3c5c5d-cd6b-4117-bc24-274678f110bb)
目前只能全屏录制
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/41545185/3bbf9e97-59e1-4af1-bcb7-3b00f883e467)

二编补充操作:
win11，N卡，obs为最新版本

1. 任意权限打开OBS(推荐管理员权限)
2. 任意权限打开胡桃工具箱
3. 尝试捕捉胡桃工具箱主界面
  注:此处通常只能捕捉到一个纯色方块
4. 成功捕捉到方块以后**彻底关闭**胡桃工具箱(指完全退出，不保留进程的状态)
5. 重新启动工具箱
  注:此时有概率可以捕获成功
6. 关闭胡桃工具箱界面，重新打开
  注: 此时不是彻底退出，托盘可见胡桃工具箱图标
  注:重新打开后OBS无法捕获主界面

### 你期望发生的行为？

OBS可以单独捕捉到胡桃工具箱的窗口

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Cirno-NULL** [comment]
问题找到了
来自于游戏内覆盖的干扰
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/41545185/a9c1b2b5-a7e8-4fae-83ef-d8ca857e4a05)
关掉以后就正常了
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/41545185/d8286c93-4c4f-4cfb-9145-0c9ac92d9eb3)

我去和显卡驱动干一架(确信)

**Comment by Cirno-NULL** [comment]
还是有问题，关太早了
和游戏内覆盖基本无关
只有启动的一瞬间有小概率可以被捕捉到
后续只要切换一次窗口就又捕捉不到了

**Comment by Mikachu2333** [comment]
![Screenshot 2024-06-25 22-34-10](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/9dd9bea3-ee28-47a6-88e7-e5157c7712ea)

完全无法复现

请问：
OBS是用的管理员权限吗？
胡桃是用的管理员权限吗？


附：我的obs设置（场景二为捕获全屏，场景一仅捕获原神）

[OBS设置.zip](https://github.com/user-attachments/files/15973124/OBS.zip)

**Comment by Cirno-NULL** [comment]
> 
> ![Screenshot 2024-06-25 22-34-10](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/9dd9bea3-ee28-47a6-88e7-e5157c7712ea)
> 
> 完全无法复现
> 
> 请问：
> OBS是用的管理员权限吗？
> 胡桃是用的管理员权限吗？
> 
> 
> 附：我的obs设置（场景二为捕获全屏，场景一仅捕获原神）
> 
> [OBS设置.zip](https://github.com/user-attachments/files/15973124/OBS.zip)
> 

是想捕获胡桃工具箱...
原神是不管怎么折腾都能捕获的

**Comment by Mikachu2333** [comment]
@Cirno-NULL 目前已经找到临时解决方案：

胡桃：设置-通知区域图标-关闭

OBS：重启程序，按下图所示设置即可
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/32104a87-b3df-4d20-82d5-75671e99694f)

**Comment by Cirno-NULL** [comment]
> @Cirno-NULL 目前已经找到临时解决方案：
> 
> 胡桃：设置-通知区域图标-关闭
> 
> OBS：重启程序，按下图所示设置即可
> ![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/32104a87-b3df-4d20-82d5-75671e99694f)
> 

感谢，终于不用凹概率了

**Comment by qhy040404** [comment]
obsproject/obs-studio#19020
