### ISSUE TITLE
[Feat]:祈愿记录分享

### ISSUE THREAD

**Issue by qimingnan17** [DGP-Studio/Snap.Hutao#1772]
### 背景与动机

想要

### 想要实现或优化的功能

想要祈愿记录分享功能可以直接以图片形式分享而且不知道什么原因集录起源没有抽中什么的记录只有抽数

**Comment by Lightczx** [comment]
你集录祈愿出金了么

**Comment by qimingnan17** [comment]
没出金发件人: ***@***.*** ***@***.***> 代表 DismissedLight ***@***.***>发送时间: 星期二, 六月 25, 2024 8:50:50 下午收件人: Snap.Hutao ***@***.***>抄送: 3439543578 ***@***.***>; author ***@***.***>主题: Re: [DGP-Studio/Snap.Hutao] [Feat]:祈愿记录分享 (Issue #1772)
你集录祈愿出金了么

**Comment by Lightczx** [comment]
没出金当然不会有，你看左边三个会显示紫和蓝么。。。

**Comment by qimingnan17** [comment]
多谢麻烦了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月26日(周三) 中午12:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DGP-Studio/Snap.Hutao] [Feat]:祈愿记录分享 (Issue #1772)




 
没出金当然不会有，你看左边三个会显示紫和蓝么。。。

**Comment by Lightczx** [comment]
米游社养成计算器
