### ISSUE TITLE
[Bug]: 胡桃云:数据异常无法保存至云端

### ISSUE THREAD

**Issue by tommynanny** [DGP-Studio/Snap.Hutao#1776]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23H2(OS build 22631.3737(

### Snap Hutao 版本

1.10.4.0

### 设备 ID

C27A05F4E2119508452591E863723A5D

### 问题分类

祈愿记录

### 发生了什么？

之前注册的胡桃云邮箱没在用了,因为没找到更换邮箱方法,于是退出了之前登录的胡桃云账号,用新邮箱注册了新的账号,订阅了12个月胡桃云服务(订单编号：202406271004065453501039163),然后登录新的邮箱账号,祈愿记录->胡桃云->上传当前的祈愿存档->获得错误"数据异常,无法保存至云端"
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/22390882/a32fe578-21cf-4ea9-87e6-8f1b5978847e)

祈愿存档数据包含从开服1.1到现在所有的祈愿记录,早起祈愿记录生成于其他祈愿整理工具,后导入胡桃云,之前那个胡桃云的账号能正常上传,这次换了新账号之后加入最近一期卡池祈愿记录之后就不能上传了

### 你期望发生的行为？

当前祈愿存档成功上传至胡桃云

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
> 之前注册的胡桃云邮箱没在用了

你需要删除老账号内的记录

**Comment by tommynanny** [comment]
@Lightczx 谢谢,删除老账户胡桃云记录以后就好了,已经解决 - 然后我在注销老账户的时候,一直显示验证失败(输入的验证码和密码是正确的)

**Comment by Lightczx** [comment]
@tommynanny 服务端有点小问题，已经修了

**Comment by tommynanny** [comment]
感激~🧡
