### ISSUE TITLE
[Feat]: 网页缓存获取祈愿记录不必切换hutao至url对应语言

### ISSUE THREAD

**Issue by SceneryMC** [DGP-Studio/Snap.Hutao#1778]
### 背景与动机

当前使用网页缓存获取祈愿记录，必须将hutao的语言切换至url语言。下图为在hutao使用中文时网页缓存获取美服祈愿记录弹出的提示：
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/111278716/014fd15a-31bd-42e5-985c-1db0b131b354)
该提示非错误（红色感叹号），应属有意为之、不为程序bug。但我已查阅文档，没有提到“祈愿url语言需要与hutao语言相同”。另外，使用hutao切换服务器时，不要求改变hutao本身的语言；但使用网页缓存获取祈愿记录时则需要。二者不一致。

### 想要实现或优化的功能

建议将祈愿url语言与hutao语言解绑，使得在hutao语言为中文的情况下能够使用网页缓存获取美服祈愿记录。如当前行为更加合理或不便改动，也请在文档[对应部分](https://hut.ao/zh/features/wish-export.html#%E7%BD%91%E9%A1%B5%E7%BC%93%E5%AD%98%E5%88%B7%E6%96%B0)补充。

**Comment by Masterain98** [comment]
> 该提示非错误（红色感叹号），应属有意为之、不为程序bug。但我已查阅文档，没有提到“祈愿url语言需要与hutao语言相同”。另外，使用hutao切换服务器时，不要求改变hutao本身的语言；但使用网页缓存获取祈愿记录时则需要。二者不一致。

切换服务器是胡桃的本地行为，但获取祈愿记录是要从米哈游服务器上获取数据，米哈游不给指定语言的数据那我们也没办法。


@DGP-Studio/hutao-dev 请求国际服数据时，是不是把语言参数给忽略了，导致使用了服务器默认语言？

**Comment by Lightczx** [comment]
Currently, all Hoyoverse/HoYoLAB feature support is contributed by the community, and we only provide limited support when some features are not available on the it.
If anyone would like to contribute code that fixes these features, a PR to the `develop` branch is more than welcome.

**Comment by Lightczx** [comment]
出于兼容性考虑不实现此功能
