### ISSUE TITLE
原神的破解帧率失效

### ISSUE THREAD

**Issue by zhangmao258** [DGP-Studio/Snap.Hutao#1779]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23H2

### Snap Hutao 版本

1.10.4.0

### 设备 ID

E22E106530F7F99EFF5615F1DDDD584E

### 问题分类

其它

### 发生了什么？

在我启动帧率突破上限的功能后，我进入游戏时在大世界是120fps，但是当我进入副本或者去层岩巨渊、渊下宫等非大世界地图时，我的游戏帧率会被还原为60fps,并且在我回到大世界时，依然是60fps

### 你期望发生的行为？

游戏帧率突破应该一直稳定在120fps,而不是在进入副本后就变成60fps

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
Duplicate of #1727
