### ISSUE TITLE
希望能在启动游戏前启动其他应用

### ISSUE THREAD

**Issue by TheZhiheng223** [DGP-Studio/Snap.Hutao#1780]
### 背景与动机

可以在启动原神前启动3dmigoto等程序，以此去掉需要提前打开辅助软件的步骤

### 想要实现或优化的功能

类似在启动原神时自动启动BetterGI一样，允许指定程序路径，可以选择优先启动外部程序再启动原神，或者先启动原神再启动外部程序

**Comment by Masterain98** [comment]
1. 不会支持用于私服或外挂用途的软件
2. 进程间联动需要双向配对支持
