### ISSUE TITLE
解锁不了fps

### ISSUE THREAD

**Issue by 666356165** [DGP-Studio/Snap.Hutao#1781]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

11

### Snap Hutao 版本

1.10.4.0

### 设备 ID

39F088B739B75DAE90C7CC0A8832E5E4

### 问题分类

安装和环境

### 发生了什么？

![屏幕截图 2024-06-29 233056](https://github.com/DGP-Studio/Snap.Hutao/assets/173611932/f96465be-f0c9-41ba-8e92-37b4fc983132)
我打开了那个解锁fps的功能 但是进去游戏还是60fps 
![屏幕截图 2024-06-29 233401](https://github.com/DGP-Studio/Snap.Hutao/assets/173611932/765e36b6-61c8-45a3-a640-e01bde269c46)
下面那个截图是我怕打开的路径是错误的

### 你期望发生的行为？

进去游戏可以有100fps

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
#1727
