### ISSUE TITLE
Hutao挂后台之后会弹好多次验证失败，而且最近验证间隔的时间感觉有点太短了吧，是因为米这个验证更严格了吗

### ISSUE THREAD

**Issue by xl2643** [DGP-Studio/Snap.Hutao#1782]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3737

### Snap Hutao 版本

1.10.4.0

### 设备 ID

B4FE6E3B3DB5B11C2B9B34389101647E

### 问题分类

用户界面

### 发生了什么？

Hutao挂后台之后会弹好多次验证失败，而且最近验证间隔的时间感觉有点太短了吧，是因为米这个验证更严格了吗
![Uploading QQ截图20240630205848.jpg…]()

### 你期望发生的行为？

不要莫名奇妙出现这么多那种验证失败信息

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
将实时便笺自动刷新关闭或者配置无感验证

**Comment by Lightczx** [comment]
Tracked by #1759
