### ISSUE TITLE
[Bug]: 程序总是不定时自动启动, 卸载后也会持续打开hutao链接

### ISSUE THREAD

**Issue by KoN-Fantazia** [DGP-Studio/Snap.Hutao#1783]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3737

### Snap Hutao 版本

1.10.4.0

### 设备 ID

B8D0033F24D170608557B8664F19DD83

### 问题分类

游戏启动器

### 发生了什么？

无论我是把程序最小化到托盘中, 还是把程序关闭, 它都会自动重新打开
有时候5min, 有时候10min, 有时候更久.
我在设置中将"通知区域图标" 和 "实时便签" 都关闭了, 没有用.

然后我将Snap Hutao应用卸载掉, 那么就会在同上的时机出现提示:
获取打开此'hutao'链接的应用
<img width="337" alt="PixPin_2024-07-01_01-04-50" src="https://github.com/DGP-Studio/Snap.Hutao/assets/14072408/a42c26bf-5fd9-42c8-ba93-a69ca8664d98">

感觉是有什么后台服务一直在访问这个链接, 导致程序一直自动启动
而且这个后台服务无法在卸载时清理

不定时弹出一个窗口太难受了, 其他什么事情都会被它打断, 烦请告知一下处理方式

### 你期望发生的行为？

应用打开时不应不定时抢占窗口焦点
应用关闭后不应不定时自动打开窗口
应用卸载后不应不定时访问hutao链接

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by KoN-Fantazia** [comment]
PS: 电脑重启也没用

**Comment by Masterain98** [comment]
检查一下 Windows 定时任务中是不是有胡桃的计划任务

**Comment by KoN-Fantazia** [comment]
有一个 SnapHutaoDailyNoteRefreshTask
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/14072408/f4104bbb-d7f1-472d-800d-96eb1cde917f)

非常可疑, 我盯一会看看弹出时机和它的运行时间是不是一致的

**Comment by KoN-Fantazia** [comment]
确认就是它了, 删掉应该就ok了

**Comment by Masterain98** [comment]
@Lightczx 历史遗留问题

**Comment by qhy040404** [comment]
> @Lightczx 历史遗留问题

每次启动都会尝试清除便笺刷新计划任务，这种应该是很多个版本前在管理员模式下安装了计划任务导致的

**Comment by Masterain98** [comment]
> > @Lightczx 历史遗留问题
> 
> 每次启动都会尝试清除便笺刷新计划任务，这种应该是很多个版本前在管理员模式下安装了计划任务导致的

那在管理员模式下启动胡桃不会解决这个问题吗？

**Comment by qhy040404** [comment]
理论来讲是可行的
