### ISSUE TITLE
[Feat]: 更新"幻想真境劇詩"所屬成就

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#1785]
### 背景与动机

俗稱新深淵的"幻想真境劇詩"已經於2024年7月1日開放 旅行者們也相繼獲得了一些成就 但這些成就目前還無法同步到胡桃工具箱中

### 想要实现或优化的功能

在成就列表中新增"幻想真境劇詩"所屬成就

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (160)](https://github.com/DGP-Studio/Snap.Hutao/assets/107019852/dc08f41b-a3af-468c-bd4e-51432922665d)

**Comment by qhy040404** [comment]
？
![d7cd135e4c5e41c37ba7f42d13b7b45e](https://github.com/DGP-Studio/Snap.Hutao/assets/45379733/db8aa135-87d3-45dd-b57c-f3e4e58ef518)
