### ISSUE TITLE
关于添加相关元素角色数量查询功能相关事宜

### ISSUE THREAD

**Issue by scnscnscn** [DGP-Studio/Snap.Hutao#1786]
### 背景与动机

幻想真镜剧诗上线，该挑战项目困难模式对旅行者的特定元素角色等级以及数量有限制

### 想要实现或优化的功能

读取米游社角色信息后，对不同元素角色进行分类，然后等级从高到低排序，根据不同难度的等级要求返回达到要求的角色数量，在用户选择时根据相应元素排序类型判断用户是否可以进行挑战，如果不行，给出相关角色培养建议（深渊使用率和与限制等级接近程度）

**Comment by GoddessLuBoYan** [comment]
培养建议应该是不必要的，因为幻想诗只拿原石奖励的难度并不高

**Comment by GoddessLuBoYan** [comment]
我理解此需求如果要实现的话，可以仅实现一个功能：在角色养成统计界面（或主页某个角落），找个地方显示自己已有多少个角色（旅行者除外），并允许按一定规则分类展示，比如按星级，按元素，以后也可能按好感度等级、按角色等级范围等等

**Comment by Mikachu2333** [comment]
> 我理解此需求如果要实现的话，可以仅实现一个功能：在角色养成统计界面（或主页某个角落），找个地方显示自己已有多少个角色（旅行者除外），并允许按一定规则分类展示，比如按星级，按元素，以后也可能按好感度等级、按角色等级范围等等

那为啥不直接在我的角色那里接入搜索，显示个“搜索结果共xx条”（
这就全解决了

**Comment by GoddessLuBoYan** [comment]
> > 我理解此需求如果要实现的话，可以仅实现一个功能：在角色养成统计界面（或主页某个角落），找个地方显示自己已有多少个角色（旅行者除外），并允许按一定规则分类展示，比如按星级，按元素，以后也可能按好感度等级、按角色等级范围等等
> 
> 那为啥不直接在我的角色那里接入搜索，显示个“搜索结果共xx条”（
> 这就全解决了 

搜索需要操作，不确定有哪些信息是用户想不用操作一眼直接看到的，不过现阶段确实可以考虑加一个按条件筛选（或者排序）
