### ISSUE TITLE
[Bug]: 在高分屏上运行旅行工具时窗口非常小

### ISSUE THREAD

**Issue by CryoMarshal** [DGP-Studio/Snap.Hutao#1795]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4598

### Snap Hutao 版本

1.10.5.0

### 设备 ID

2A4F4282F42EA1ABA439829F606E5813

### 问题分类

用户界面

### 发生了什么？

使用2560x1600 200%的分辨率，打开旅行工具时窗口比较小。虽然可通过调整至1440x900 100%的方式临时解决，但代价就是会影响整体观感。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/63281870/ce108fb9-d003-46de-968b-912081cc6c47)

### 你期望发生的行为？

能加入对于高DPI的支持，使在200%等缩放下的窗口也能像100%一样有正常内容大小。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/23905ef5-c1d4-4765-a93f-2b9b6e7ece82)
确实有这问题
