### ISSUE TITLE
[Feat]: 实时便笺中的时间显示改进

### ISSUE THREAD

**Issue by shuhari** [DGP-Studio/Snap.Hutao#1796]
![实时便笺](https://github.com/DGP-Studio/Snap.Hutao/assets/2049955/501a79b4-714e-4f16-a458-385ef0177512)
### 背景与动机

目前实时便笺中探索派遣时间若>1小时则显示为”XX时“，不够精确。比如说，如果用户知道还需1小时58分钟的话，通常会选择过2小时再来刷新，但显示为1小时则很可能导致用户不必要地多刷一次。

### 想要实现或优化的功能

探索派遣剩余时间显示建议改为 XX时XX分，和原神内部一致。

为了方便用户决定何时更新，实时便笺下方的 ”刷新于XX-XX XX:XX“ 也建议改为 "刷新于 XX 分钟前" 或 "刷新于 XX 时 XX分前"。

**Comment by Lightczx** [comment]
米游社没给，只有小于1小时时才会有准确的`分`
