### ISSUE TITLE
[Bug]: 背景图设为每日一图不会自动更新

### ISSUE THREAD

**Issue by shuhari** [DGP-Studio/Snap.Hutao#1797]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4598

### Snap Hutao 版本

1.10.4

### 问题分类

用户界面

### 发生了什么？

如果背景图设为每日一图类型的图源，且胡桃工具箱一直保持开启，背景图只有在重新打开程序或修改设置时会更新。

### 你期望发生的行为？

当背景图设为每日一图类型的图源时，且距离上次修改背景已超过一天，则应自动触发背景图刷新。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@Masterain98 每日一图的API是固定返回的还是每次请求随机的

**Comment by Masterain98** [comment]
> @Masterain98 每日一图的API是固定返回的还是每次请求随机的

当日图片是固定的
