### ISSUE TITLE
[Feat]: 优化危险功能启动时的提示语句

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1801]
### 背景与动机

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/7b38ddb7-7757-45a6-ba28-f016b03dbf59)

### 想要实现或优化的功能

`请输入当前正在启用的功能开关的标题名称` -> `请输入当前正在启用的功能名称：{feature_title}`

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/23afecc6-db53-4d95-b20e-779ec42b517f)

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/95823235-c34f-49d0-91c9-45b6029eed51)

**Comment by winTEuser** [comment]
30秒就不必了，弹出一个协议拉到底就行
