### ISSUE TITLE
[Bug]: 新注入帧数解锁没有达到帧数突破的预期效果

### ISSUE THREAD

**Issue by tommynanny** [DGP-Studio/Snap.Hutao#1802]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

10.0.22631 N/A Build 22631

### Snap Hutao 版本

1.10.6.0

### 设备 ID

C27A05F4E2119508452591E863723A5D

### 问题分类

游戏启动器

### 发生了什么？

新的注入帧率解锁后启动游戏后Fraps显示就只有最高60祯(没有切换场景)
根据观察,在使用hutao注入帧数解锁工具启动游戏后,场景加载到登录门的时候帧数就只有60了之后就再也没突破过了
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/22390882/19f4b56e-e30d-4641-b498-30e74980f8a5)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/22390882/67d71757-6cd1-49b9-a1bc-5fa780750bf6)

### 你期望发生的行为？

帧率解锁工具能让游戏突破60帧率限制
最近用的[xiaonian233/genshin-fps-unlock](https://github.com/xiaonian233/genshin-fps-unlock)帧数解锁还是一直有用
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/22390882/b78f0c91-52d9-49c7-9761-ca3f3e16ac1a)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by YYBYX** [comment]
请问什么时候可以解决？

**Comment by qhy040404** [comment]
打开调试控制台然后使用注入方式启动游戏，到门口的时候截一张控制台的图

**Comment by emako** [comment]
我试了下，似乎改成用Kernel32.CreateProcess启动原就可以了

**Comment by tommynanny** [comment]
管理员权限重启运行胡桃工具箱 然后启动游戏帧率就没问题了 (之前我以为用管理员打开开关以后就可以普通启动了
