### ISSUE TITLE
[Feat]: 分享战绩时可以直接导出为文件

### ISSUE THREAD

**Issue by CryoMarshal** [DGP-Studio/Snap.Hutao#1804]
### 背景与动机

有时候，我可能会将自己的战绩（包括深渊，活动，角色，月历））进行图片输出，以便后续回顾。但是每次导出的时候都会以剪贴板的形式导出，虽可以导出到画图/Word等软件里，却感觉比直接导出略麻烦一些。
![屏幕截图 2024-07-07 120033](https://github.com/DGP-Studio/Snap.Hutao/assets/63281870/9efa1c01-ce7f-465d-9e3a-5a275cc5ed14)

> 如已事先将星铁等其他游戏角色绑定在同一米游社账号下，可以从旅行工具->战绩中查看星铁战绩，方式是打开原神战绩后点击左上角游戏选单来切换。

### 想要实现或优化的功能

无论是原神战绩还是星铁战绩，图片导出时可以直接导出为本地图片，或者给一个开关决定要下载至剪贴板还是本地。

**Comment by BTMuli** [comment]
~~可以试试[TeyvatGuide](https://github.com/BTMuli/TeyvatGuide)，JSBridge相关的导出都是直接导出文件到下载目录的~~
