### ISSUE TITLE
[Bug]: 为什么我运行[Snap.Hutao.Deployment.exe]用于更新后控制台内提示[未找到包文件或包文件损坏。]并程序自行[开始下载包文件...]后未出现新版本程序

### ISSUE THREAD

**Issue by little-kind-sheep** [DGP-Studio/Snap.Hutao#1805]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4529

### Snap Hutao 版本

1.10.5.0

### 设备 ID

20D84B582F9508531C4AD2F21E57C1DB

### 问题分类

安装和环境

### 发生了什么？

[Snap.Hutao.Deployment.exe]运行后控制台出现的
<img width="961" alt="搜狗截图20240707193554" src="https://github.com/DGP-Studio/Snap.Hutao/assets/174939626/932e098e-1f58-4b75-9442-c0e5e5ba4f42">

### 你期望发生的行为？

帮我查看下为什么，是缺了啥组件吗

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你网不好，挂梯子

**Comment by CryoMarshal** [comment]
我也遇到过这问题，然后看之前装的时候组件基本都在就决定用msix安装。
