### ISSUE TITLE
[ENG][Bug]: Insta crash after downloading an update

### ISSUE THREAD

**Issue by sata700** [DGP-Studio/Snap.Hutao#1806]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

22631.3810

### Snap Hutao Version

1.10.6.0

### Issue Category

Installation and Environment

### What Happened?

Few days ago, I got an update notification and updated the app. After then, I noticed that the app keeps insta crashing when opened. It will start to open normally then after few seconds, it will crash. The time between app starting and the crash is barely enough for the app to launch the game if only i start snap hutao as admin otherwise, not enough time.

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by qhy040404** [comment]
please provide your device id by using [Diagnostic Tooling](https://github.com/DGP-Automation/ISSUE_TEMPLATES/releases/download/diagnosis_tools/Snap.Hutao.Diagnostic.Tooling.exe)

**Comment by sata700** [comment]
78D074B76D7A8B8ACC142A5271FB4FCD

**Comment by qhy040404** [comment]
join our Discord server and contact admin
