### ISSUE TITLE
[Bug]: 使用者顯示問題

### ISSUE THREAD

**Issue by yuusukealmal** [DGP-Studio/Snap.Hutao#1807]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.3785

### Snap Hutao 版本

1.10.6.0

### 问题分类

用户界面

### 发生了什么？

如圖，登入使用者為不同角色，但在下方用戶顯示為同一使用者

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/170559662/0fcc4fe3-cb95-4d37-9eda-ce891ed12007)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/170559662/ed50ae91-124f-4f66-b9e0-b510b7e3af2b)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
Join our discord and contact me for support
