### ISSUE TITLE
[Bug]: 祈愿记录胡桃云存档数据异常

### ISSUE THREAD

**Issue by Toyro7356** [DGP-Studio/Snap.Hutao#1809]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26100.1150

### Snap Hutao 版本

1.10.6.0

### 问题分类

胡桃通行证/胡桃云

### 发生了什么？

上传祈愿存档至胡桃云，提示数据异常，无法保存至云端。
尝试过删除当前本地存档从stoken重新获取后上传，但无法解决问题；同时尝试将存档导出后在uifg.org进行格式检测无误。

可能造成问题的原因：
我曾经注册过另一个胡桃账号，在云端存储过一个存档，后来我换了一个账号就出现了这个问题，这个问题已经持续大约3个月了。
uid：114424210

### 你期望发生的行为？

正常上传存档

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
登录老账号删除原云存档

**Comment by Toyro7356** [comment]
> 登录老账号删除原云存档

就是因为原来账号不记得了所以注册了一个新的账号。

**Comment by Lightczx** [comment]
> 原来账号不记得了

在没有老账号的情况下我们无法验证你是否是此UID的真正持有人
