### ISSUE TITLE
1034错误导致的消息刷屏

### ISSUE THREAD

**Issue by WoshiRedstone** [DGP-Studio/Snap.Hutao#1811]
### 背景与动机

当实时便笺因为人机验证而无法请求时会1弹出1034的错误消息，而由于系统定时任务的缘故会导致一直请求，一段时间不处理便会有大量消息

### 想要实现或优化的功能

为实时便笺的请求添加一个阈值（如当前账号超过x次无法请求便停止请求直到人为进行刷新或通过人机验证为止）

**Comment by qhy040404** [comment]
#1759
