### ISSUE TITLE
[Bug]: 打开扫码窗口后关闭胡桃主窗口，会导致扫码登录按钮变灰

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#1815]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows 11 23H2

### Snap Hutao 版本

1.10.6

### 问题分类

用户界面

### 发生了什么？

![a2be0fab6ac8b71a25f843c07916c876](https://github.com/user-attachments/assets/8f37ce07-d005-4598-b64a-a59920de242a)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
扫码入口已移除
