### ISSUE TITLE
米游社账号无法登陆，扫码无反应

### ISSUE THREAD

**Issue by chaogemars** [DGP-Studio/Snap.Hutao#1819]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

win10 22H2

### Snap Hutao 版本

1.10.6.0

### 问题分类

米游社账号面板

### 发生了什么？

用米游社扫码登录没反应

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
无法复现

**Comment by chaogemars** [comment]
![屏幕截图 2024-07-17 114941](https://github.com/user-attachments/assets/b8527919-669d-464f-9899-c2ac7925aa0d)
saoma扫码后无反应一直这个界面

**Comment by Masterain98** [comment]
用的是什么软件扫的？软件版本是什么？

**Comment by chaogemars** [comment]
米游社2.73.1

**Comment by TRIM5829** [comment]
> 用的是什么软件扫的？软件版本是什么？

无法通过鉴权了。错误码-3503
之前遇到过，改device就行了。但现在米游社更新后又不行了

**Comment by Masterain98** [comment]
米哈游在新版本开服时更新了扫码相关的内容

**Comment by Lightczx** [comment]
Response [状态：-3503 | 信息：请求失败，当前设备或网络环境存在风险]

**Comment by TRIM5829** [comment]
> Response [状态：-3503 | 信息：请求失败，当前设备或网络环境存在风险]

解决方法：请求头加上x-rpc-device_id
但是，返回的不再是game_token而是stoken v2，所以无法通过game_token得到mid从而查询游戏角色信息
只要知道哪个接口可以返回mid就行了
这次他们改了挺多接口

**Comment by qhy040404** [comment]
不是stoken_v2，这个token不能换authkey相关字段
这个字段我更倾向于命名为stoken_se_v2或者exchange_token

**Comment by MiniGrayGay** [comment]
UEFI干什么，不如Legacy引导一下Snap.Hutao(x

**Comment by TRIM5829** [comment]
> 不是stoken_v2，这个token不能换authkey相关字段 这个字段我更倾向于命名为stoken_se_v2或者exchange_token

刚刚也发现了不行（尴尬）
那这样说的话，几乎没办法获取到authkey咯，验证码也只能获取到ltoken
感觉最新版本的这些游戏token几乎全是本地计算了，接口不久就要废掉

**Comment by m1x1999** [comment]
米游社ios 2.72.2扫码也无法登录，扫码后胡桃无反应

**Comment by suimeng-zero** [comment]
同样无法登录，米游社安卓2.72.2版本
我还试了Cookie手动输入登录，根据文档说明，下载了LSP模块，但是怎么也找不到形如钥匙的按钮，重新优化也没有用

**Comment by home110120** [comment]
同issue，正好这周换了24小时在线的服务器，重装了系统，服务器无法刷新便笺，只能用台式机刷新很不方便。

**Comment by XiaoChi1010** [comment]
我这边也出现了有一样的问题，但是两个账号只有一个号出问题了，另一个号过人机检测以后还能正常使用，不得已我只能删除出问题的账号想重新登，结果发现已经登不上了

**Comment by SafetyFA** [comment]
我也出现了同样的问题，没有办法进行扫码

**Comment by CryoMarshal** [comment]
我这边已经登录的还会被退出，之后怎么刷新都没用。

**Comment by BTMuli** [comment]
> 我这边已经登录的还会被退出，之后怎么刷新都没用。

stoken失效导致的，建议用其他应用获取合法的cookie后手动输入胡桃

**Comment by BTMuli** [comment]
> 有一个办法不知道有没有试过，就是通过手机端原神在进门之前点屏幕右下角扫码按钮进行扫码登录。

原神的扫码登录获取stoken2已经寄了，短期内的解决方法也有，我那个已经转向短信验证码登录了，你可以用我的登录完后复制ck到胡桃那边。

**Comment by Waldbeisepel** [comment]
我有同样的问题
