### ISSUE TITLE
游戏更新后闪退

### ISSUE THREAD

**Issue by AloneWeekend** [DGP-Studio/Snap.Hutao#1821]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4651

### Snap Hutao 版本

1.10.6

### 问题分类

游戏启动器

### 发生了什么？

进游戏准备把门搭起来时闪退

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by SyuanPo** [comment]
同樣問題，顯示的錯誤為這個
![螢幕擷取畫面 2024-07-17 111047](https://github.com/user-attachments/assets/95212543-f078-4d24-b266-27abfd6ee7c0)

關閉「解鎖fps」後可正常啟動

**Comment by Lightczx** [comment]
#1814

**Comment by XyingGen1** [comment]
有没有测试版2024.7.17.9的证书啊

**Comment by AloneWeekend** [comment]
> 有没有测试版2024.7.17.9的证书啊

没
