### ISSUE TITLE
1.10.7.0中功能“祈愿记录”没有“导出”选项，无法导出json文件

### ISSUE THREAD

**Issue by dongxiang0422** [DGP-Studio/Snap.Hutao#1827]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3593

### Snap Hutao 版本

1.10.7.0

### 设备 ID

D43359DF7953FAA83D6AF5879E8BD482

### 问题分类

祈愿记录

### 发生了什么？

1.10.7.0中功能“祈愿记录”没有“导出”选项，无法导出json文件

### 你期望发生的行为？

恢复“导出”功能，支持导出json文件

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
我要不要给你把更新日志复制过来让你看一眼啊

**Comment by Masterain98** [comment]
@Lightczx 也许可以考虑新版本第一次启动时，弹更新日志窗口后，限制60秒后才可关闭窗口（或者根据字数，每个字一秒设计限制时间）

**Comment by dongxiang0422** [comment]
有没有一种可能，我仔细阅读了弹窗的日志内容

**Comment by dongxiang0422** [comment]
我需要这个功能才反馈的

**Comment by Masterain98** [comment]
那你复制一下你读的内容吧

**Comment by qhy040404** [comment]
![QQ_1721200635794](https://github.com/user-attachments/assets/5a2ad008-6cff-46f7-a77e-59fd141a1119)
把你那眼睛捐了都没人要

**Comment by dongxiang0422** [comment]
绝了开发者处理反馈就这个态度

**Comment by qhy040404** [comment]
那样吧，你给我爆点金币，我跪下来给你磕一个道歉然后再手把手教你怎么进入设置然后导出

**Comment by Masterain98** [comment]
那你都知道有东西被移除了，又有东西被添加了，移除的是你要的，那为什么不去试试新增的呢？

更新日志就是拿来告诉你们什么东西变了的，我们不想浪费时间再解释。你既然看到了，有时间来这里浪费时间来问一个根本不会有解决方案的问题，干嘛不去尝试一下呢？

**Comment by dongxiang0422** [comment]
好的，抱歉我不知道uigf是什么东西，是我见识短浅，您大人不计小人过，和您道歉

**Comment by ShikiSuen** [comment]
> 绝了开发者处理反馈就这个态度

你最好这样假设：
只要是免费提供的软件，甭管开源不开源，开发者持这种态度都很正常。特别是开源软件，最正常了。

**Comment by qhy040404** [comment]
好的，抱歉我不知道您从来都没看过导出名，是我对您的脑子见识短浅，您大人不计小人过，和您道歉

![QQ_1721201168999](https://github.com/user-attachments/assets/d14f0086-ffc6-4360-8a5d-4fdb931fa8f5)

**Comment by dongxiang0422** [comment]
算了藏这么深，我去用旧版了，感谢大家回复
![屏幕截图 2024-07-17 153414](https://github.com/user-attachments/assets/f18b8714-78a8-4c22-ba62-d7355db30925)
![屏幕截图 2024-07-17 153421](https://github.com/user-attachments/assets/cc23586e-01a1-4dbc-bcc1-476a6ac41121)

**Comment by Masterain98** [comment]
> 设置界面新增 UIGF 4 导入导出支持，祈愿记录移除了 UIGF 2 与 UIGF 3 导入导出支持

我觉得我写的这句话还是很直白的，新的导入导出在“设置界面”，有什么更好的表述方式能让你找起来不那么费劲呢？

**Comment by ShikiSuen** [comment]
@Masterain98 在原来的位置用红色文字脚注、引导旧版使用者前往新的位置导入导出 UIGF。
这个脚注可以弄成一次性的，看过一次之后点掉了就永久消失。
