### ISSUE TITLE
最新正式版安装包打开报错0x80080206

### ISSUE THREAD

**Issue by XyingGen1** [DGP-Studio/Snap.Hutao#1828]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23H2

### Snap Hutao 版本

1.10.7.0

### 问题分类

安装和环境

### 发生了什么？

安装报错

### 你期望发生的行为？

正常安装

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
重新下载

**Comment by XyingGen1** [comment]
重新下载还是一样安装包损坏报0x80080206

**Comment by Masterain98** [comment]
从GitHub手动下

**Comment by XyingGen1** [comment]
GitHub不是也只给一个Snap.Hutao.Deployment吗，只要用这个打开就在命令行里下MSIX包，下载好以后Snap.Hutao.Deployment就报错，报错完手动打开Snap.Hutao的MSIX就报0x80080206安装包损坏或者报0x800207000D

**Comment by XyingGen1** [comment]
GitHub不是也只给一个Snap.Hutao.Deployment吗，只要用这个打开就在命令行里下MSIX包，下载好以后Snap.Hutao.Deployment就报错，报错完手动打开Snap.Hutao的MSIX就报0x80080206安装包损坏或者报0x8007000D

**Comment by XyingGen1** [comment]
大佬你有测试版2024.7.17.9的证书吗？

**Comment by qhy040404** [comment]
那么
你删没删掉msix呢

**Comment by XyingGen1** [comment]
删了

**Comment by XyingGen1** [comment]
要下载八个小时？
