### ISSUE TITLE
[Bug]:更新到最新版（1.10.7）后无法从胡桃启动游戏

### ISSUE THREAD

**Issue by ghmj1205** [DGP-Studio/Snap.Hutao#1829]

**Comment by ghmj1205** [comment]
> ### 检查清单
> 
>     * [x]  我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
> 
>     * [x]  我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
> 
>     * [x]  我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题
> 
> 
> ### Windows 版本
> 
> 22H2 19045.3208
> ### Snap Hutao 版本
> 
> 1.10.7
> ### 设备 ID
> 
> 2B564AFD2AFC2C004516FBDF31201992
> ### 问题分类
> 
> 游戏启动器
> ### 发生了什么？
> 
> 更新到最新版（1.10.7）后，从胡桃启动游戏后，右上角会弹出错误窗口，错误内容如下： localVirtualAddress (0’) must be a non-zero value.(Parameter "localVirtualAddress')Actual value was 0.
> ### 你期望发生的行为？
> 
> 能正常从胡桃启动器中启动游戏，并顺利解锁帧率。
> ### 最后一步
> 
>     * [x]  我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by ghmj1205** [comment]
已解决

**Comment by qhy040404** [comment]
怎么解决的
