### ISSUE TITLE
[Feat]: 3D地图

### ISSUE THREAD

**Issue by misaka10384** [DGP-Studio/Snap.Hutao#183]
### 你想要实现或优化的功能？

如果能力足够的话  有没有想法内置一个3D地图  就不要网页地图了  把地图3D化  
并加入 路径标记 自动寻路  资源标记  参考我的世界的[bluemap](https://www.mcmod.cn/class/3461.html)模组   
好像别的都不麻烦 就是搞这个地图有点......

**Comment by UnrealOfficial** [comment]
做成3d的话不仅工作量大，而且对显卡要求也提高了，而且先不说地上的建模，地下难度恐怕比地上还高
