### ISSUE TITLE
[Bug]: 无法卸载

### ISSUE THREAD

**Issue by chendageshuonipangle** [DGP-Studio/Snap.Hutao#1831]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

 Windows 11 Version 23H2

### Snap Hutao 版本

1.10.7.0

### 设备 ID

92071B170B8479C49C1C9A9F28E0E253

### 问题分类

安装和环境

### 发生了什么？

![屏幕截图 2024-07-17 211654](https://github.com/user-attachments/assets/ac9bde1d-9a65-4b71-b1de-b349e9884f85)

### 你期望发生的行为？

可以删除软件

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by chendageshuonipangle** [comment]
是无法卸载呀

**Comment by Lightczx** [comment]
相比之下你是怎么装上的

**Comment by chendageshuonipangle** [comment]
安装使用的是
![Uploading 屏幕截图 2024-07-17 213531.png…]()

**Comment by chendageshuonipangle** [comment]
就是这个项目给的一键安装的文件

**Comment by Lightczx** [comment]
图片传完了再发评论

**Comment by 1846333564** [comment]
我也遇到了这个问题，并且也无法用任何方式安装最新版本，只能停留在1.10.6.0版本。而且卸载同样的报错。
