### ISSUE TITLE
[Bug]: 在收起消息后会遮挡部分按钮

### ISSUE THREAD

**Issue by DuckDuckStudio** [DGP-Studio/Snap.Hutao#1832]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3880

### Snap Hutao 版本

1.10.7.0

### 设备 ID

876B52225C8ABBB67B7156DDD1C9509E

### 问题分类

用户界面

### 发生了什么？

在收起消息时可能会遮挡部分**无法调整位置的**按键，例如下面这个遮挡了“启动游戏”按键
![image](https://github.com/user-attachments/assets/1c75fdb5-99f4-4293-9621-33dcfd432e51)

### 你期望发生的行为？

在收起消息时，不会遮挡按键，或者被遮挡的按键可以轻松的移出遮挡位置
可以将消息放在左下或右下，这里的按键基本上都可以通过滚动调整位置。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
清空消息即可

**Comment by DuckDuckStudio** [comment]
> 清空消息即可

部分时候可能清空消息不太好（例如查看错误信息等）

> 另外，如果可以直接清空信息，为什么要做“收起信息”呢？
