### ISSUE TITLE
[Bug]: 扫码无法登录

### ISSUE THREAD

**Issue by CheneyBear** [DGP-Studio/Snap.Hutao#1834]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4651

### Snap Hutao 版本

1.10.7.0

### 设备 ID

3A0EE97C4DC5A917AF3C004E04D1F5C6

### 问题分类

米游社账号面板

### 发生了什么？

1、扫码无法登录，无反应。
2、手动输入，按要求路径下载了你的米游社，登录后，“我的”右上角没有钥匙标志，也就没有Stoken的cookies

### 你期望发生的行为？

正常扫码登录。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by CheneyBear** [comment]
> ### Probable Similar Topics
> 1. 67% [米游社扫码无法登录 #1826](https://github.com/DGP-Studio/Snap.Hutao/issues/1826)
> 2. 67% [[Bug]: 无法登录 #328](https://github.com/DGP-Studio/Snap.Hutao/issues/328)
> 3. 50% [[Bug]: 程序内部无法登录 #560](https://github.com/DGP-Studio/Snap.Hutao/issues/560)

以上内容都不是哦。最新版本的胡桃，最新版本的米游社

**Comment by Lightczx** [comment]
#1819

**Comment by Lightczx** [comment]
@HolographicHat 听说你的 GetToken 坏了
