### ISSUE TITLE
webhook推送

### ISSUE THREAD

**Issue by Nugent1a** [DGP-Studio/Snap.Hutao#1836]
### 背景与动机

我瞅着实时便笺页面下的通知设置中
数据互操作选项下有提供配置webhook的选项
但这个选项里只有配置webhook_url这一个选项
没有看到RequestBody以及Headers等配置项
这显然不太完整

### 想要实现或优化的功能

webhook配置中添加RequestBody以及Headers的配置项

**Comment by Lightczx** [comment]
requestbody与header均为胡桃自动填充且没有更改的必要

**Comment by Nugent1a** [comment]
或者在官方文档里面写一下
机器人（钉钉、飞书等）需要如何配置
比如添加哪些关键字等

**Comment by Masterain98** [comment]
https://hut.ao/zh/features/real-time-notes.html#%E5%85%A8%E5%B1%80%E9%80%9A%E7%9F%A5%E8%AE%BE%E7%BD%AE

文档中已经写了，胡桃只是转发米游社数据，帮助减少账号对米游社请求。如果需要自定义推送功能，还是需要自己写程序。

**Comment by Nugent1a** [comment]
那我这没什么想法了 ，作者可以关掉这条issues了
