### ISSUE TITLE
增加游戏资讯信息

### ISSUE THREAD

**Issue by zz-zhang21** [DGP-Studio/Snap.Hutao#1837]
### 背景与动机

玩家常常会对新角色非常感兴趣，比如需要什么材料，

### 想要实现或优化的功能

增加新角色的相关信息
可以参考https://gi17.hakush.in/
并注明非官方信息。

**Comment by BTMuli** [comment]
不是有角色图鉴吗，那里没有养成材料？

**Comment by Lightczx** [comment]
测试服角色不会考虑
