### ISSUE TITLE
[Bug]: 胡桃工具箱1.10.7导入祈愿记录只能使用UIGF 4格式

### ISSUE THREAD

**Issue by tutyyy** [DGP-Studio/Snap.Hutao#1839]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19025,4529

### Snap Hutao 版本

1.10.7

### 问题分类

祈愿记录

### 发生了什么？

胡桃工具箱1.10.7导入祈愿记录只能使用UIGF 4格式，用其他工具导出的格式为UIGF 3.0，到胡桃工具箱导入会报错导入失败，数据不准确

### 你期望发生的行为？

开放UIGF3.0导入

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
@Lightczx 经典搞得太猛

**Comment by Lightczx** [comment]
老米在更新游戏前也没有通知我们

**Comment by Lightczx** [comment]
原定移除UIGF2/3支持的版本会在十多天后发布，但是
1. 原神版本更新更改了UP与UA导致解锁帧率不可用
2. 米游社安全策略升级导致扫码登录不可用

包含解锁帧率修复的版本是不得已提前发布的
