### ISSUE TITLE
[Feat]: 添加默认以管理员模式运行

### ISSUE THREAD

**Issue by a2445478275** [DGP-Studio/Snap.Hutao#184]
### 你想要实现或优化的功能？

每次都要右键管理员运行太麻烦了，snap 以前可以用快捷方式 现在Hutao好像不行。

**Comment by Lightczx** [comment]
msix 包限制，不能默认管理员启动

**Comment by a2445478275** [comment]
> 



> msix 包限制，不能默认管理员启动
可以使用命令行做到么

**Comment by Lightczx** [comment]
PowerShell 脚本 
``` powershell
Start-Process shell:AppsFolder\7f0db578-026f-4e0b-a75b-d5d06bb0a74d_7jfyf5536hdrr!App -verb runas
```

**Comment by Yinr** [comment]
文件夹右击 -> 新建 -> 快捷方式，然后输入：

```
PowerShell -WindowStyle Hidden -Command "Start-Process shell:AppsFolder\7f0db578-026f-4e0b-a75b-d5d06bb0a74d_7jfyf5536hdrr!App -verb runas"
```

下一步输入名字就好了。不过这样图标是默认 PowerShell 的图标。

不想闪黑框可以在快捷方式上右击 -> 属性 -> 运行方式改为 `最小化`，同时也可以在这里手动设置图标。

**Comment by ICEBERGTEN** [comment]
现在上架微软商店后应该是输入

**Comment by ICEBERGTEN** [comment]
现在上架微软商店后应该是输入

> PowerShell -WindowStyle Hidden -Command "Start-Process shell:AppsFolder\60568DGPStudio.SnapHutao_ebfp3nyc27j86!App -verb runas"

**Comment by ICEBERGTEN** [comment]
现在上架微软商店后应该是输入

> PowerShell -WindowStyle Hidden -Command "Start-Process shell:AppsFolder\60568DGPStudio.SnapHutao_ebfp3nyc27j86!App -verb runas"

**Comment by sunying73** [comment]
卸载之后一直显示让我下载回去怎么关啊
