### ISSUE TITLE
进入副本后解锁帧率失效

### ISSUE THREAD

**Issue by IIcygnus** [DGP-Studio/Snap.Hutao#1844]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3880

### Snap Hutao 版本

1.10.7.0

### 设备 ID

46519BC0F503E248CB1659B19C37EED8

### 问题分类

游戏启动器

### 发生了什么？

使用解锁帧率启动游戏后，帧率正常解锁了，但是在游戏中
![QQ_1721449873796](https://github.com/user-attachments/assets/9d5e8297-4959-451b-939d-aa4f3f8af748)
![QQ_1721449950544](https://github.com/user-attachments/assets/af624c12-1214-4e85-a54f-5ba30658f555)
进入任意副本之后帧率上限又回到60

### 你期望发生的行为？

游戏内进入副本后解锁帧率功能仍可正常运行

### 最后一步

- [ ] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
用注入模式

**Comment by IIcygnus** [comment]
> 用注入模式

请问下注入模式具体怎么操作呀，谢谢
