### ISSUE TITLE
[Bug]: 重装系统后更新到最新胡桃 祈愿记录中的导入导出UIGF去哪里了！

### ISSUE THREAD

**Issue by Small-SaltedFish** [DGP-Studio/Snap.Hutao#1846]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3880

### Snap Hutao 版本

1.10.7.0

### 问题分类

祈愿记录

### 发生了什么？

![image](https://github.com/user-attachments/assets/06a1b426-f5ac-4d5d-af3e-27f3069407d2)
我的导入导出UIGF呢！
刚从上个版本导出的 怎么这个功能不见了呀！

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by chensiyu10000** [comment]
这个问题我能回答，祈愿记录导入导出转移到【设置】里去了。
但我也想补充一下！
为什么要移除对UIGF3.0的支持啊，我今天才下载的胡桃工具箱，从别的工具导出的抽卡记录是3.0的，现在完全没办法导入到胡桃里。

**Comment by Lightczx** [comment]
没有为什么，就是移除了

**Comment by Lightczx** [comment]
如果想要导入就去其他软件那里反馈让他们支持UIGF 4

**Comment by Small-SaltedFish** [comment]
> 如果想要导入就去其他软件那里反馈让他们支持UIGF 4

但是这样hutao上个版本迁移出来的 这个版本就直接用不了了....

**Comment by Lightczx** [comment]
老版本的记录不需要迁移，只要不删除数据文件夹，祈愿记录不会消失

**Comment by Small-SaltedFish** [comment]
> 老版本的记录不需要迁移，只要不删除数据文件夹，祈愿记录不会消失

那尴尬了 我上个版本刚好重装系统 导出之后装最新hutao就直接导入不进去了
