### ISSUE TITLE
[Feat]: 從 paimon.moe 匯入成就

### ISSUE THREAD

**Issue by yuusukealmal** [DGP-Studio/Snap.Hutao#1849]
### 背景与动机

當時不知道此應用，所以成就都是在 [paimon.moe](https://paimon.moe/achievement) 上進行確認與管理的，但後來發現此應用之後，覺得此應用在多方面實用性上好很多，但是不想從頭勾選一次成就，所以希望能從其他管道匯入

### 想要实现或优化的功能

 [paimon.moe](https://paimon.moe/achievement) 上有可以把使用者在該網站上的資料下載成 JSON ，希望能透過分析該JSON把已完成的成就會入此應用

**Comment by Lightczx** [comment]
让他们支持 UIAF

**Comment by SSB-ARFCN** [comment]
> ### 背景与动机
> 當時不知道此應用，所以成就都是在 [paimon.moe](https://paimon.moe/achievement) 上進行確認與管理的，但後來發現此應用之後，覺得此應用在多方面實用性上好很多，但是不想從頭勾選一次成就，所以希望能從其他管道匯入
> 
> ### 想要实现或优化的功能
> [paimon.moe](https://paimon.moe/achievement) 上有可以把使用者在該網站上的資料下載成 JSON ，希望能透過分析該JSON把已完成的成就會入此應用

用這個試試 直接讀取遊戲成就 匯出選擇胡桃工具箱即可
https://github.com/HolographicHat/YaeAchievement

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (199)](https://github.com/user-attachments/assets/7dfaf34a-7463-4374-9c57-9edf78c0975e)


![螢幕擷取畫面 (200)](https://github.com/user-attachments/assets/cf1d7299-d361-41cc-b4f0-eaff2010273c)
