### ISSUE TITLE
[Feat]: 将 MSIX 格式安装包添加至 winget 软件源

### ISSUE THREAD

**Issue by Dragon1573** [DGP-Studio/Snap.Hutao#1853]
### 检查清单

- [x] 我未完整阅读 胡桃工具箱文档 ，但我**已完整阅读** [其他常见问题](https://hut.ao/zh/advanced/FAQ.html)
- [x] 我不知道文档站的导航栏中有搜索功能，也没有搜索过相关关键词
- [x] 我**已查看** [受支持版本列表](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82) ，但不确定我的系统是否在此范畴中。
- [x] 我**没有**在文档站导航栏中执行搜索，但我**已搜索** GitHub Issues ，**已找到**部分关联问题，但它们均**不完全与此问题等价**。
- [x] 我**已仔细阅读**此检查清单。

### 背景与动机

- Related #514
- Related #1216
- Related microsoft/winget-pkgs#164178
- Related microsoft/winget-pkgs#164380

### 想要实现或优化的功能

应用能够被 `winget.exe` 支持。

**Comment by Lightczx** [comment]
@Masterain98 @qhy040404 Any automation possibility?

**Comment by Dragon1573** [comment]
### 更多信息

- Related https://github.com/microsoft/winget-pkgs/pull/164380#issuecomment-2248347743
- Related https://github.com/microsoft/winget-pkgs/pull/164380#discussion_r1690089933
- Related https://github.com/microsoft/winget-pkgs/pull/164380#issuecomment-2249007842

当前，`winget-pkgs` 团队已配置对此安装包进行自动化测试（包括 Azure Pipelines 无人自动化测试与 Azure VM 人工测试）。经测试发现，此应用能够被 `winget.exe` 正确在系统中完成安装，但无法被正确启动。

此安装包的元信息描述文件由 _Komac_ 产生，经其自动分析，配置文件中存在如下内容：

```yaml
RestrictedCapabilities:
- runFullTrust
- unvirtualizedResources
```

这是否表明，此应用仅能在真实（非虚拟化或嵌套虚拟化）操作系统环境上运行？另有用户在个人 Windows 11 `amd64` 设备上进行安装测试，能够正常启动应用程序。

**Comment by Masterain98** [comment]
> ```yaml
> RestrictedCapabilities:
> - runFullTrust
> - unvirtualizedResources
> ```

Snap Hutao is a Windows MSIX AppContainer application, which means virtualized file system and registry. However, to realize some features, including account switch, frame rate unlocker, etc. Snap Hutao needs to modify unvirtualized resources by gaining full access. Microsoft Store denied listing apps like this, so Winget will probably do the same.
