### ISSUE TITLE
[Feat]: 抽卡记录导入与导出

### ISSUE THREAD

**Issue by hllyd** [DGP-Studio/Snap.Hutao#1855]
### 背景与动机

以前有json的抽卡记录导入和导出功能的，现在这个功能没了？
主页上还有这个功能的描述：https://hut.ao/zh/features/wish-export.html#%E5%AF%BC%E5%85%A5-uigf-%E7%A5%88%E6%84%BF%E6%95%B0%E6%8D%AE

### 想要实现或优化的功能

恢复抽卡记录导入和导出功能

**Comment by Lightczx** [comment]
设置页面
