### ISSUE TITLE
[Bug]: 从提瓦特小助手获取的抽卡json文件无法导入胡桃

### ISSUE THREAD

**Issue by NOWorEVER** [DGP-Studio/Snap.Hutao#1856]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4651

### Snap Hutao 版本

1.10.7.0

### 设备 ID

9D0621C9C72D9E0896A23AF294308C70

### 问题分类

安装和环境

### 发生了什么？

从提瓦特小助手获取的抽卡json文件无法导入胡桃
[https://www.lelaer.com/uigf.php](url)
是不是版本太老了。能怎么解决呢？

### 你期望发生的行为？

能将从提瓦特小助手获取的json文件导入到胡桃中

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
让他们支持 UIGF 4

**Comment by NOWorEVER** [comment]
> 让他们支持 UIGF 4

公众号一直在装死，估计技术人员都离职了
