### ISSUE TITLE
[Bug]: 抽卡紀錄未更新

### ISSUE THREAD

**Issue by yuusukealmal** [DGP-Studio/Snap.Hutao#1857]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.3785

### Snap Hutao 版本

1.10.7.0

### 问题分类

祈愿记录

### 发生了什么？

遊戲內祈願紀錄已經更新並顯示，但是使用Snap.Hutao 重新整理之後並未顯示
![image](https://github.com/user-attachments/assets/cf613f7a-b419-4b7b-8e3f-53ab82ff104e)
![image](https://github.com/user-attachments/assets/458ae433-ee57-4754-b1fa-71954bb12b50)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by yuusukealmal** [comment]
阿，Snap.Hutao版本是1.10.7.0 忘了已經更新

**Comment by qhy040404** [comment]
你怎么刷新的

**Comment by yuusukealmal** [comment]
網頁快取重新整理 和 手動輸入URL 都試過

**Comment by qhy040404** [comment]
再重试一次

**Comment by yuusukealmal** [comment]
一樣沒有出現

**Comment by Lightczx** [comment]
之前的记录是从别的地方导入的吗

**Comment by yuusukealmal** [comment]
之前有用過其他其他紀錄祈願的網站
但在Snap.Hutao 是重新獲取抽卡連結之後紀錄的

**Comment by yuusukealmal** [comment]
之前用的時候都沒問題
但是最近一陣子的都不會被更新到

**Comment by Lightczx** [comment]
导出记录，删除存档，刷新记录，导入回来

**Comment by yuusukealmal** [comment]
哪裡可以導出紀錄阿

![image](https://github.com/user-attachments/assets/5f12f47f-175b-4bb7-92a7-f1ab16ad1c66)

**Comment by yuusukealmal** [comment]
重新試過了，但依舊沒有出現

**Comment by yuusukealmal** [comment]
並且在重新匯入之後，出現了問題
這刻晴當時是40多抽出得

![image](https://github.com/user-attachments/assets/b9e789e5-583e-4e10-a415-83722153d3d4)

**Comment by qhy040404** [comment]
1. 你这个uid和你抽出来的uid对的上吗
2. 你刷新之后老数据导入回去了吗，你这一看就是一年前左右出的刻晴然后再往前的获取不到了

**Comment by yuusukealmal** [comment]
1. 對的上
2. 有導入回去了，但沒有發生改變

**Comment by yuusukealmal** [comment]
還是我把導出的Json跟抽卡URL 都傳上來

**Comment by qhy040404** [comment]
#1873
