### ISSUE TITLE
[Bug]: 切换账号默认角色消失

### ISSUE THREAD

**Issue by streesobrs** [DGP-Studio/Snap.Hutao#186]
### Windows 版本

19044.2130

### Snap Hutao 版本

1.1.23.0

### 发生了什么？

选择账号，刚打开的时候角色那一栏有默认选中的角色，点击另一个账号，再点回来，默认账号就未选中了

### 你期望发生的行为？

点另一个角色，再点回来，角色的默认选中还在

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
fixed internally
