### ISSUE TITLE
[Bug]: 活动时间显示异常

### ISSUE THREAD

**Issue by huarongfei** [DGP-Studio/Snap.Hutao#1864]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3958

### Snap Hutao 版本

1.10.7.0

### 设备 ID

413609A1429C9893A0B72F2586975598

### 问题分类

其它

### 发生了什么？

我查看首页时，发现时间显示错误，其他的都正常
![image](https://github.com/user-attachments/assets/87568e10-a156-4eba-a1a5-a2648deaf656)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (214)](https://github.com/user-attachments/assets/94463cf4-2936-4a82-9c37-3fe51aeb8e7c)
紀行也是 
![螢幕擷取畫面 (215)](https://github.com/user-attachments/assets/44f9ba1f-e855-4af8-81cd-453e7d59bb3e)
https://ys.mihoyo.com/main/news/detail/124804
mhy官網寫4.8更新後開始

**Comment by qhy040404** [comment]
fixed by 5ea1557
