### ISSUE TITLE
[Bug]: 场景切换后锁60帧

### ISSUE THREAD

**Issue by DER329** [DGP-Studio/Snap.Hutao#1867]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3880

### Snap Hutao 版本

1.10.7.0

### 设备 ID

F3575DA245C7CA3F8C4EB09611DBDBFA

### 问题分类

其它

### 发生了什么？

在经典帧率解锁方式下
刚进入游戏能正常解锁高帧, 但只要切换场景后(秘境、尘歌壶等)后就会锁定60帧。
配置12700+3050笔记本（排除高温撞墙，游戏++跑了一遍）
在注入方式下
未出现以上问题
nv驱动536.45
官服

### 你期望发生的行为？

请留意

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
使用注入模式
