### ISSUE TITLE
[Bug]: 胡桃导出的 UIGFv4 不符合 UIGFv4 规范

### ISSUE THREAD

**Issue by guyutongxue** [DGP-Studio/Snap.Hutao#1868]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.4000

### Snap Hutao 版本

1.10.7.0

### 问题分类

祈愿记录

### 发生了什么？

胡桃生成的 `/hk4e/0/list/0/item_id` 为 `number` 类型：

https://github.com/DGP-Studio/Snap.Hutao/blob/a3be885c5ec2f3dc297680c102bf1d91f8909d19/src/Snap.Hutao/Snap.Hutao/Model/InterChange/GachaLog/Hk4eItem.cs#L21-L22

而 UIGFv4 要求此项为 `string` 类型：

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "hk4e": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "list": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "item_id": {
                                    "type": "string",
                                    "description": "物品的内部 ID"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

https://uigf.org/zh/standards/uigf.html#json-schema

### 你期望发生的行为？

修改 UIGF 规范或者修改胡桃实现，使得导出数据能通过 UIGFv4 校验。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by BTMuli** [comment]
该问题为已知问题，目前胡桃已经不在 [UIGFv4 支持列表](https://uigf.org/zh/#%E4%BD%BF%E7%94%A8-uigf-v4-0-%E6%A0%87%E5%87%86%E7%9A%84%E9%A1%B9%E7%9B%AE) 当中

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao/commit/22b33fcfb6d5ab1fd0360f7d921749c34165aa30
