### ISSUE TITLE
米游社扫码登陆问题

### ISSUE THREAD

**Issue by HeiSe13A** [DGP-Studio/Snap.Hutao#1872]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

190454717

### Snap Hutao 版本

1.10.7.0

### 设备 ID

21B5D55E7215D811ACBFF8D659752FBA

### 问题分类

用户界面

### 发生了什么？

使用米游社扫码登陆，已在手机米游社确认登陆，也收到了米游社的通行证登陆通知的邮件，但hutao依旧停留在扫码界面无法登陆进去

### 你期望发生的行为？

解决我的米游社登陆问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1819
