### ISSUE TITLE
[Bug]: 祈願紀錄報錯 502

### ISSUE THREAD

**Issue by yuusukealmal** [DGP-Studio/Snap.Hutao#1873]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.3785

### Snap Hutao 版本

1.10.7.0

### 设备 ID

261F44E365A6451E9B4A596852050770

### 问题分类

祈愿记录

### 发生了什么？

在看 [#1871](https://github.com/DGP-Studio/Snap.Hutao/issues/1871) 之後， 刪除快取並且重新取得URL，但也報了 502 的錯誤
![image](https://github.com/user-attachments/assets/a441c924-dab7-4f65-aa05-84d09bdb2f06)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
抓一下游戏内打开祈愿历史的包，然后去DC私发给我们

**Comment by SSB-ARFCN** [comment]
看起來要等新版本再更新祈願紀錄
Mhy把API改了

**Comment by SonGokuSSJ** [comment]
When I try to import the wish history via up to date url I get "URL is expired" and also the mentioned error (502) above. The import URL is correct and not expired though as I used it with paimon.moe, Genshin Wish Export and GI Pizza Helper (iOS App) successfully.

**Comment by SonGokuSSJ** [comment]
Thank you for the fix. The new version works again.
