### ISSUE TITLE
[Bug]: 显示解锁帧率成功，进游戏发现还是60帧

### ISSUE THREAD

**Issue by aerojhl** [DGP-Studio/Snap.Hutao#1874]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3958

### Snap Hutao 版本

1.10.7.0

### 设备 ID

F0EF6B8105F22739866EE3CC6A0A5760

### 问题分类

其它

### 发生了什么？

胡桃里面显示已经成功解锁帧率，如图所示
![image](https://github.com/user-attachments/assets/e5931044-9d9d-4fda-baa4-f4c18ff6dfa7)
但是进游戏发现还是60帧，并没有成功解锁
![image](https://github.com/user-attachments/assets/0ab54519-d9bf-4d1d-ac51-daea71279841)

### 你期望发生的行为？

希望解锁帧率功能可以正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
用注入
