### ISSUE TITLE
[Bug]: 通知报错/公告显示不正常

### ISSUE THREAD

**Issue by Waldbeisepel** [DGP-Studio/Snap.Hutao#1878]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3958

### Snap Hutao 版本

1.10.7.0

### 设备 ID

A324F3BC0FB987218CD034F5C4C325FE

### 问题分类

公告

### 发生了什么？

![Snap Hutao_qFCf6E1CHl](https://github.com/user-attachments/assets/c0d28987-99e2-4340-83a5-adb7f6f2cb2d)
![Snap Hutao_ces3wImV4t](https://github.com/user-attachments/assets/ddc2a56d-e84d-4341-a9ea-9c9bfd0be115)
打开软件时往常的游戏公告无法正常显示，且右上角的通知弹出如图所示的字样

### 你期望发生的行为？

不知道是否为bug，希望恢复正常运行

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@Masterain98 FYI
睡醒了修一下 Homa API 的访问

**Comment by Latomoyocarl** [comment]
同样出现了 502 报错：homa.snapgenshin.com 和 api.snapgenshin.com 无法连接；同时伴有「HTTP GatewayTimeout l Error:Unknown: 元数据校验 文件下载失败」的报错，以及扫码登陆后无反应

**Comment by nahco365** [comment]
一样出现问题：
![图片](https://github.com/user-attachments/assets/4386eea6-9d22-4ef1-a966-3afe45bfa49b)

**Comment by hzyder** [comment]
我也出现类似情况
![image](https://github.com/user-attachments/assets/de33499f-8930-47ae-81dd-6d1960bfa45d)

**Comment by Lightczx** [comment]
api.snapgenshin.com
homa.snapgenshin.com
应该都可以正常访问了

**Comment by Anrande** [comment]
> api.snapgenshin.com homa.snapgenshin.com 应该都可以正常访问了

好像又不能用了
今天第一次打开时正常，后面几次全部失败
![屏幕截图 2024-08-06 102956](https://github.com/user-attachments/assets/170f777c-4e0f-4de6-ae72-b4a4e9ac80de)
