### ISSUE TITLE
打开胡桃后无法连接

### ISSUE THREAD

**Issue by Atlas-1s** [DGP-Studio/Snap.Hutao#1879]
@### 提交你的网络诊断报告

[Uploading SH-Report-4dd23605-3b6c-41b7-8f4a-e8970b7ea894.zip…]()

### 你的地理位置

杭州

### 你的运营商

中国电信

### 你的问题

完全无法连接服务器

### 你的问题（补充）

![image](https://github.com/user-attachments/assets/732ef97c-efb1-4d68-99d4-8a041a9374f7)

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Skinyi** [comment]
我有一样的问题。日志输出：元数据校验文件下载失败。

**Comment by Lightczx** [comment]
#1878
