### ISSUE TITLE
hutao启动游戏账号重命名问题

### ISSUE THREAD

**Issue by 3242859343** [DGP-Studio/Snap.Hutao#188]
### Windows 版本

22000.1098

### Snap Hutao 版本

1.1.23.0

### 发生了什么？

hutao启动游戏账号重命名长了会自动关闭hutao

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
长了是多长？重命名的名称是什么

**Comment by 3242859343** [comment]
改的是：清风/十一天委托/32个无相草材料

**Comment by Lightczx** [comment]
fixed internally
