### ISSUE TITLE
[Network]: 无法使用祈愿记录、成就管理、我的角色等功能，显示502

### ISSUE THREAD

**Issue by Anrande** [DGP-Studio/Snap.Hutao#1880]
### Submit Your Network Diagnosis Report

[SH-Report-0c5ee665-66be-461e-8c82-ce7c95f7a1ce.zip](https://github.com/user-attachments/files/16495767/SH-Report-0c5ee665-66be-461e-8c82-ce7c95f7a1ce.zip)
这是没开VPN的↑
[SH-Report-7e3891a8-62cb-4041-b357-2a8996abdd91.zip](https://github.com/user-attachments/files/16495784/SH-Report-7e3891a8-62cb-4041-b357-2a8996abdd91.zip)
这是开了VPN的↑

### Your Geographical Location

中国

### Your ISP Name

中国联合网络通信集团有限公司

### Issue Category

Cannot connect to server completely

### Your Issue (cont.)

在打开时主页会一直加载没变化，进入其他其他界面时会说‘状态：502 信息： Host:api.snapgenshin.com’,有时候还会显示‘HTTP BadGateway  Error:Unknown:元数据校验文件下载失败’,但是米游社和胡桃账号都是正常登录上去，我的角色会显示未读取角色，但之前都显示。同时我尝试过使用VPN等，没用，解锁Loopback限制后还是不行，尝试多次一样

### One Last Step

- [X] I confirm I have attached the network diagnosis report archive in the issue

**Comment by chenxihao000108** [comment]
我现在新安装胡桃安装不了，因为不能下载包文件

**Comment by Lightczx** [comment]
#1878
