### ISSUE TITLE
[Bug]: 最近没办法正常使用

### ISSUE THREAD

**Issue by zheshawanyia** [DGP-Studio/Snap.Hutao#1881]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

 版本23H2（OS内部版本22631.3880）

### Snap Hutao 版本

1.10.7.0

### 设备 ID

8B9C4A0EB444D8F5231E6C5DD77FE66B

### 问题分类

深境螺旋/胡桃数据库

### 发生了什么？

最近两天打开软件就显示HttpRequestException 元数据校验文件下载失败、状态：502/信息：、Host：api.snapgenshin.com三种通知，除了启动游戏、反馈中心、设置以外的功能都没法使用，文档中说请检查胡桃客户端的网络连接，我不知道怎么检查。目前只尝试过卸载重装，还是没办法解决。

### 你期望发生的行为？

我希望能尽快修复，恢复正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1878
