### ISSUE TITLE
[Bug]: 活动公告图片无法加载

### ISSUE THREAD

**Issue by Latomoyocarl** [DGP-Studio/Snap.Hutao#1882]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4651

### Snap Hutao 版本

1.10.7.0

### 设备 ID

CDBAE21A62486FEC7319FBBCFFAFAD64

### 问题分类

公告

### 发生了什么？

自从几日前的上个版本，胡桃的 api 和 homa 无法连接网络后，主页下游戏公告就一直无法加载，空荡一片。此次更新后，账号、便签、成就等功能恢复正常，公告依旧没有。于是按照说明解除了 loopback 限制，重新连接，公告并未恢复，此次更新后又做了一遍，也不行，开启和关闭代理的情况下都试过了。此间时有报错出现，按照手册排查后依然无济于事。所以这一次卸载后重新安装，可公告依旧无法加载，以及很长时间以后弹出网络问题报错。目前胡桃 loopback 已在代理中清除，不确定应用本体是否是这样的。我并未注册胡桃账号，只知道离线下即使报错，除去公告外也依旧其他功能正常。
![1](https://github.com/user-attachments/assets/2cf95a39-a90e-442d-9218-55e956de84ef)
![2](https://github.com/user-attachments/assets/910f8cc3-d202-48ef-b994-c19d417fbd68)

### 你期望发生的行为？

启动后稍等片刻游戏公告加载完成并正常显示

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
公告无法加载 与 api.snapgenshin.com 5xx 系列状态码为不同的问题，请分别提交Issues
