### ISSUE TITLE
[Bug]: IOException: 0x80131620

### ISSUE THREAD

**Issue by Waldbeisepel** [DGP-Studio/Snap.Hutao#1887]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3958

### Snap Hutao 版本

1.10.7.0

### 设备 ID

A324F3BC0FB987218CD034F5C4C325FE

### 问题分类

安装和环境

### 发生了什么？

![Snap Hutao_m1WCUlS3qB](https://github.com/user-attachments/assets/ffe75712-e8f8-4cbe-be84-125496d8d1f4)

### 你期望发生的行为？

不太确定是不是bug，希望对软件本体修复上有所帮助

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你网炸了
