### ISSUE TITLE
[Bug]: 新角色武器图标为空

### ISSUE THREAD

**Issue by tommynanny** [DGP-Studio/Snap.Hutao#1888]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23H2

### Snap Hutao 版本

1.10.7.0

### 设备 ID

C27A05F4E2119508452591E863723A5D

### 问题分类

文件缓存

### 发生了什么？

新角色和武器图标都是空的,在设置里进行了重置图片资源也还是空图标

### 你期望发生的行为？

图标正常加载

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题
![image](https://github.com/user-attachments/assets/a8b7e2e9-0c7e-45b7-b10f-63cf80e863a6)

**Comment by Masterain98** [comment]
fixed
