### ISSUE TITLE
[Bug]: 公告消失

### ISSUE THREAD

**Issue by vvb7456** [DGP-Studio/Snap.Hutao#1890]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3672

### Snap Hutao 版本

1.10.7.0

### 设备 ID

057CC57A39401DCF1CB345EF1B2DCCF4

### 问题分类

公告

### 发生了什么？

首页的公告栏消失了
![QQ截图20240808133628](https://github.com/user-attachments/assets/e72dc465-c5e9-4fd0-917a-bea3e39b6b46)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1864
