### ISSUE TITLE
[Bug]: Version1.10.7.0，国服无法登陆米游社，操作文档中的Stoken获取方法失效

### ISSUE THREAD

**Issue by Orion-OvO** [DGP-Studio/Snap.Hutao#1892]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4651

### Snap Hutao 版本

1.10.7.0

### 问题分类

米游社账号面板

### 发生了什么？

版本1.10.7.0，国服无法登陆米游社
1.网页登陆：寄了
2.扫码登录：爆了，我知道你们知道，看到文档更新日志了
3.手动输入：要输入Stoken
PC获取方法没写，老方法F12console导出说我stoken无效
iOS获取方法：stream，也是老方法了。不过目前一抓包开米游社就掉线。
还剩一个安卓，可我没有安卓机，而且我已经连续碰壁了一个多小时了。但是最终我还是选择了开模拟器搞了一下。然后发现现在的版本根本没有🔑的入口。我已经开始怀疑是不是我的问题了，还好github上也有别人评论说找不到入口。

至此，所有方法尝试完毕，彻底上不去了。

还好第二天也就是8月8号，我收到了邮件，安卓米游社apk的作者确认为是bug修复了这个问题。虽然修复了个寂寞，钥匙出来了但是点了就闪退。我回复了以后有人回我他也一样，另一个apk能用但很麻烦。

不能登米游社的结果就是这种情况下点击我的角色或者深境螺旋都会直接卡死。

我知道扫码问题提了，卡死问题也有人提了，我也知道不能提重复问题。不过没有人提操作文档获取Stoken方法失效的事。这问题就归给Cookie了，别的就当顺带提了，毕竟扫码要是好使我也不用指望手动输入，不能说没有因果关系。

### 你期望发生的行为？

我感觉最大的问题应该还是没有交流的地方，导致出现了问题难以判断是自己的问题还是胡桃工具箱的问题，然后反复尝试发现是浪费时间。虽说Github是一个，但是也不至于人人反馈都得翻墙吧，虽然我目前住在国外不用翻，但是要是有个Q群其实也挺方便的。而且这个问题能在GitHub反馈吗？毕竟无法获取Stoken这个不是Snap Hutao软件本身的问题，但确确实实影响了使用。不在GitHub反馈我也没地方反馈了。不过设置Cookie的指引界面的操作文档超链接也确实指向了一堆获取不了Cookie的方法，这操作文档也该更新了。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
> 还好第二天也就是8月8号，我收到了邮件，安卓米游社apk的作者确认为是bug修复了这个问题。虽然修复了个寂寞，钥匙出来了但是点了就闪退。我回复了以后有人回我他也一样，另一个apk能用但很麻烦。

@HolographicHat

**Comment by Lightczx** [comment]
@Orion-OvO 急就用测试版，不急就等更新

**Comment by Lightczx** [comment]
> 虽然我目前住在国外不用翻，但是要是有个Q群其实也挺方便的。而且这个问题能在GitHub反馈吗？

Q群只用来吹水，反馈从来只看 Github

**Comment by Lightczx** [comment]
Duplicate of #1819

**Comment by HolographicHat** [comment]
fixed 2e52b58f981503998456c6030ffad88ef940748c
https://github.com/HolographicHat/GetToken/releases/tag/2.74.1
