### ISSUE TITLE
[ENG][Bug]: Failed to fetch wish history - Wish history URL is expired. 

### ISSUE THREAD

**Issue by SonGokuSSJ** [DGP-Studio/Snap.Hutao#1895]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

Windows 10 22H2 - 19045.4651

### Snap Hutao Version

1.10.7.0

### Device ID

07501442C0F1F5C9D3A8A2353E744D48

### Issue Category

Wish Export

### What Happened?

When I try to import the new wishes in Snap Hutao I get the error message "Failed to fetch wish history - Wish history URL is expired. ". It does not matter if I manually input the url (gotten via [Paimon.moe PowerShell Script](https://paimon.moe/wish/import)) or if I use the "Refresh with Web Cache" function within Snap Hutao. The manually gotten URL works fine with [Paimon.moe](https://paimon.moe/), [Genshin Wish Export](https://github.com/biuuu/genshin-wish-export) or via "GI Pizza Helper" (iOS App). They all successfully import the wishes. 

### What is expected?

That the collection of the wish history functions correctly. 

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
#1873
