### ISSUE TITLE
希望使用uigf将外部的祈愿记录导入胡桃工具箱中这个功能回归

### ISSUE THREAD

**Issue by d240523s** [DGP-Studio/Snap.Hutao#1901]
### 背景与动机

我是最近才转入pc端所以也这段时间用的胡桃工具箱，之前都是在小程序里记录的祈愿，小程序被封掉了，希望这个功能回归

### 想要实现或优化的功能

uigf导入回复

**Comment by Lightczx** [comment]
设置页面自己找

**Comment by SSB-ARFCN** [comment]
> ### 背景与动机
> 我是最近才转入pc端所以也这段时间用的胡桃工具箱，之前都是在小程序里记录的祈愿，小程序被封掉了，希望这个功能回归
> 
> ### 想要实现或优化的功能
> uigf导入回复
![未命名](https://github.com/user-attachments/assets/ca9c8dea-63fa-46d9-b03d-450b4d17927a)
這個試試
