### ISSUE TITLE
[Bug]: 昨天更新到1.11.0.0后，出现数据异常

### ISSUE THREAD

**Issue by G99LEE** [DGP-Studio/Snap.Hutao#1902]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3880

### Snap Hutao 版本

1.11.0.0

### 设备 ID

10B29D2FED6FE38385C99231C53C943E

### 问题分类

游戏启动器

### 发生了什么？

仅管理员模式下启动出现数据异常
![屏幕截图 2024-08-14 195651](https://github.com/user-attachments/assets/ff0dcfb4-13fe-4acd-a565-798ced96664c)
![无标题](https://github.com/user-attachments/assets/5a71d82b-07b9-48b6-bf8c-c1652cec7830)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by G99LEE** [comment]
应该是解锁帧率的问题，管理员模式下不开解锁帧率就能进去
![屏幕截图](https://github.com/user-attachments/assets/2a678478-b225-4a98-b811-bf65090a33a7)

**Comment by qhy040404** [comment]
![Uploading image.png…]()

**Comment by Lightczx** [comment]
经典红字不看
