### ISSUE TITLE
[Bug]: 原神修复和下载功能无法使用

### ISSUE THREAD

**Issue by halointernet** [DGP-Studio/Snap.Hutao#1903]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22362.521

### Snap Hutao 版本

1.11.0.0

### 设备 ID

142B7FE807BE1FC30C5B8C874F397C57

### 问题分类

游戏启动器

### 发生了什么？

点击修复和下载（管理员模式），新模块无法使用，未开代理，网络和hosts正常，国服official
![paths](https://github.com/user-attachments/assets/3e477f94-f26e-418c-a282-895c911033a9)
![errocode](https://github.com/user-attachments/assets/33890146-afc1-4043-88df-b27be56d4593)
![console](https://github.com/user-attachments/assets/fa2b03ac-5cc8-483d-a8df-abfd6e834851)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你安装点的国际服吧

**Comment by SSB-ARFCN** [comment]
遊戲5.0即將更新 也許很快就會有大量的使用需求 請教大佬們有考慮隨著5.0更新套用 套用這個修正嗎?

**Comment by Lightczx** [comment]
> 遊戲5.0即將更新 也許很快就會有大量的使用需求 大佬們有考慮隨著5.0更新 套用這個修正嗎?

没时间
