### ISSUE TITLE
回归帧率选项

### ISSUE THREAD

**Issue by aaahai00** [DGP-Studio/Snap.Hutao#1904]
### 背景与动机

我国际服的游戏用不了注入，显示解锁成功但实际无效果，经典模式正常
但我的国服游戏它只有注入功能正常，所以需要切换选项
现在貌似是默认使用注入，找了好久都没找到切换选项（国际服解帧无效，国服正常）

### 想要实现或优化的功能

也希望国际服也可以正常使用注入

**Comment by aaahai00** [comment]
不对唉，国际服（注入）解帧不生效这个问题应该算bug，我是不是得提交一个bug申请

**Comment by Lightczx** [comment]
BUG不要开成Feat
