### ISSUE TITLE
[Bug]: 解锁帧率失效

### ISSUE THREAD

**Issue by loveloveboy** [DGP-Studio/Snap.Hutao#1906]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.0.0

### 设备 ID

20C09C78283DB9D6A4E3FF5C09275446

### 问题分类

游戏启动器

### 发生了什么？

启动时显示尝试解锁帧率，然后变成等待进程退出，没有像之前版本看见解锁帧率成功的提示，之前版本的注入解锁帧率选项也找不到了，游戏内只有logo界面是解锁帧率的，出现大门就变成60帧

### 你期望发生的行为？

修复帧率解锁

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
调试控制台里看一下输出

**Comment by Lightczx** [comment]
Closing for no response
