### ISSUE TITLE
[Bug]: 背景启动器壁纸炸了

### ISSUE THREAD

**Issue by twjmy** [DGP-Studio/Snap.Hutao#1908]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.0.0

### 设备 ID

4B6379FDA25D058C3FA50872BAB7D316

### 问题分类

用户界面

### 发生了什么？

背景选取官方启动器壁纸无法正常显示并且不断弹出404
![image](https://github.com/user-attachments/assets/15c793b4-21b8-4d2b-8bca-6214aa115643)

### 你期望发生的行为？

正常显示启动器壁纸

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
@Lightczx API 接口少了一个 `-`

原神启动器背景图的接口是：`https://api.snapgenshin.com/wallpaper/genshin-launcher`

HYP背景图的接口是：`https://api-admin.snapgenshin.cn/global/wallpaper/hoyoplay`

**Comment by Masterain98** [comment]
@Lightczx API 接口少了一个 `-`

原神启动器背景图的接口是：`https://api.snapgenshin.com/wallpaper/genshin-launcher`

HYP背景图的接口是：`https://api.snapgenshin.com/wallpaper/hoyoplay`

**Comment by Lightczx** [comment]
临时方案：https://github.com/DGP-Studio/Snap.Hutao/issues/1924#issuecomment-2305237721
不使用原神启动器壁纸即可

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (300)](https://github.com/user-attachments/assets/466daccd-936f-4983-9f65-02f90df0c86a)
bing正常使用中
