### ISSUE TITLE
[Feat]:请求作者大大增加反和谐功能

### ISSUE THREAD

**Issue by wwwloe** [DGP-Studio/Snap.Hutao#191]
### 你想要实现或优化的功能？

不求别的，只求增加与外服一样的飞行视角，和恢复原皮的功能，还实名认证的成年玩家一个完整的游戏体验，跪谢！

**Comment by Askwind** [comment]
附议： 就是2个功能，和FPS解锁一样加到危险功能里面去，怂别用，用别怂。
1. 皮肤反和谐，跟外服一样
2. 反虚化，可选完全去除或者和外服一样的虚化角度

**Comment by AdminRoc** [comment]
一切工具的底线就是不修改游戏文件，你的请求有些过分了
