### ISSUE TITLE
[Bug]: 启动时卡住2s左右并闪退

### ISSUE THREAD

**Issue by cchenge** [DGP-Studio/Snap.Hutao#1911]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4780

### Snap Hutao 版本

1.11.0.0

### 设备 ID

CB29654FFFA80569AE18065C2C8AC65F

### 问题分类

安装和环境

### 发生了什么？

[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/16644462/Snap.Hutao.Error.Log.txt)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by cchenge** [comment]
[Userdata.zip](https://github.com/user-attachments/files/16645220/Userdata.zip)
这是我的userdata.db
把这个删除重新生成就能正常使用，但是删除后各种数据就没有了，替换继续使用这个文件就会闪退崩溃

**Comment by Lightczx** [comment]
[Userdata.zip](https://github.com/user-attachments/files/16647209/Userdata.zip)
用这个替换
