### ISSUE TITLE
[Network]: 安装时无法下载图像资源

### ISSUE THREAD

**Issue by hg429108** [DGP-Studio/Snap.Hutao#1914]
### 提交你的网络诊断报告

[SH-Report-b62867da-827c-42fb-8771-8f10a906c472.zip](https://github.com/user-attachments/files/16645751/SH-Report-b62867da-827c-42fb-8771-8f10a906c472.zip)
使用Snap.Hutao.Deployment 安装 Snap Hutao，进行至“下载最基本的图像资源”时，出现如图所示的情况，程序无法继续安装
![屏幕截图 2024-08-18 005549](https://github.com/user-attachments/assets/bd8f661e-7362-477c-bcf2-ff15426bad79)

### 你的地理位置

河南

### 你的运营商

中国移动

### 你的问题

完全无法连接服务器

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Lightczx** [comment]
@Masterain98 看上去是连接超时了

**Comment by Masterain98** [comment]
疑似有中间人攻击，用户侧的 HTTP 连接不稳定，没有服务端侧问题
