### ISSUE TITLE
[Bug]: 无法更新到最新版本

### ISSUE THREAD

**Issue by liting10275** [DGP-Studio/Snap.Hutao#1916]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4291

### Snap Hutao 版本

1.107

### 设备 ID

7079DFB7B35BC1E0F3B404DC559D3349

### 问题分类

其它

### 发生了什么？

无法从低版本更新到最新版本

### 你期望发生的行为？

我希望可以更新到最新版本

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by liting10275** [comment]
请告诉我怎么更新到新版本 谢谢

**Comment by SSB-ARFCN** [comment]
用[Snap.Hutao.Deployment](https://github.com/DGP-Studio/Snap.Hutao.Deployment) 進行覆蓋安裝
