### ISSUE TITLE
[Bug]: 我的角色页面，角色显示出错

### ISSUE THREAD

**Issue by Summerxzy520** [DGP-Studio/Snap.Hutao#1921]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Windows11

### Snap Hutao 版本

1.11.0.0

### 设备 ID

412F30C4C6DEDC1560B2BA57B633434C

### 问题分类

我的角色

### 发生了什么？

![无标题](https://github.com/user-attachments/assets/e19d7558-2a9c-44cb-806a-5c7dfd38bf1a)
珐露珊技能等级异常显示，6命，元素爆发未显示+3

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
重新同步即可
