### ISSUE TITLE
[ENG][Bug]: Realtime Notes refresh error:  Return code 10102

### ISSUE THREAD

**Issue by DeniablePlausibility** [DGP-Studio/Snap.Hutao#1922]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

19045.4780

### Snap Hutao Version

1.11.0.0

### Device ID

1A2087096CAD75D88EF9933413F94FA8

### Issue Category

Realtime Note

### What Happened?

This feature worked previously.  After installing the latest version 1.11.0.0 and trying to refresh the Realtime Note, I get the following error notification:

![image](https://github.com/user-attachments/assets/c448564c-0122-4cd7-adc8-7d6112612c7d)

I am logged in to Hoyolab in the app with a valid cookie.

### What is expected?

The expected outcome is for the Realtime Note to refresh with updated information.  Right now it is mostly blank:

![image](https://github.com/user-attachments/assets/ebd9d991-708a-4821-94c8-cd9dea5fdc35)

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
Currently, all Hoyoverse/HoYoLAB feature support is contributed by the community, and we only provide limited support when some features are not available on the it.
If anyone would like to contribute code that fixes these features, a PR to the `develop` branch is more than welcome.

**Comment by qhy040404** [comment]
Open your HoYoLAB app, switch to the last tab below, then click on your game card. There is a setting in the upper right corner of your game card. Enable real-time notes in the settings.

**Comment by DeniablePlausibility** [comment]
Thank you but I don't use the Hoyolab app.

**Comment by qhy040404** [comment]
https://www.hoyolab.com/setting/privacy
![image](https://github.com/user-attachments/assets/84bc1c34-d923-4513-84b5-e7410c62215b)

**Comment by mengling729** [comment]
你为什么不使用hoyolab应用程序，是因为你手机是华为nova11se么

**Comment by DeniablePlausibility** [comment]
I have enabled Real-Time Notes.

[image: image.png]
But now I have a different error after logging in on Snap Hutao and
clicking "I'm logged in":

[image: image.png]

I have tried quitting Snap Hutao and logging back in.  Login is successful
but I keep getting this message.

Thank you for trying to help me.

**Comment by qhy040404** [comment]
UPDATE YOUR PROGRAM

**Comment by DeniablePlausibility** [comment]
我不使用该应用程序，因为我的手机关机时间比开机时间多。

**Comment by qhy040404** [comment]
AND STOP USING YOUR EMAIL TO REPLY. I CANNOT SEE THE IMAGE

**Comment by DeniablePlausibility** [comment]
I just downloaded it, it should be the newest version.

[image: image.png]

**Comment by qhy040404** [comment]
stop use your f**king email to reply. I can't see your image and if you use email again i will lock the conversation

**Comment by DeniablePlausibility** [comment]
Sorry, logged in now.

Snap Hutao version:  
![image](https://github.com/user-attachments/assets/e7aff9ce-f147-43cd-8c9f-a3446eb3ae08)

Error after logging in to Hoyolab from Snap Hutao:
![image](https://github.com/user-attachments/assets/5f0ff3d7-aabb-45fa-827e-78bf96874cc4)

**Comment by DeniablePlausibility** [comment]
Really strange, just noticed that Real-Time Notes is refreshing despite the error.

![image](https://github.com/user-attachments/assets/96bef55b-b6ed-4cb1-b642-f922c7ff9e9a)

The web login section still prompts for me to log in.

**Comment by Lightczx** [comment]
oversea login issue #1966
