### ISSUE TITLE
添加每日材料种类以及需要这些材料的角色

### ISSUE THREAD

**Issue by Chipanphong** [DGP-Studio/Snap.Hutao#1923]
### 背景与动机

我经常有体力不知道来干什么，希望能提供一个板块，**显示今日的秘境材料，以及需要这些材料的角色**，这样就知道当日我可以去刷哪些角色的材料。

### 想要实现或优化的功能

提供一个板块，显示今日的秘境材料，以及需要这些材料的角色

**Comment by hg429108** [comment]
角色天赋升级材料周常表、武器突破材料周常表、观测枢WiKi·日历都有类似功能

**Comment by AlenhuAN** [comment]
> ### 背景与动机
> 我经常有体力不知道来干什么，希望能提供一个板块，**显示今日的秘境材料，以及需要这些材料的角色**，这样就知道当日我可以去刷哪些角色的材料。
> 
> ### 想要实现或优化的功能
> 提供一个板块，显示今日的秘境材料，以及需要这些材料的角色

米游社--> 原神版区--> 旅行工具 --> 观测枢（wiki）

**Comment by Lightczx** [comment]
![动画](https://github.com/user-attachments/assets/e02262b0-6644-4837-8306-a250848001aa)

**Comment by Mikachu2333** [comment]
神！
