### ISSUE TITLE
[Bug]: 通知一直在弹HttpRequestException: Status Code: NotFound Error: Unknown

### ISSUE THREAD

**Issue by bsgz** [DGP-Studio/Snap.Hutao#1924]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3737

### Snap Hutao 版本

1.11.0.0

### 设备 ID

40662F005CA1B11B5953547B4A4FD62F

### 问题分类

其它

### 发生了什么？

通知栏在不停弹出这个报错，但所有功能又都可以正常使用
![Snipaste_2024-08-22_18-12-55](https://github.com/user-attachments/assets/2ba05153-31ec-4df3-9a69-861e43cd8823)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
在设置中暂时将背景图由官方启动器切换成其它的

**Comment by Lightczx** [comment]
#1908

**Comment by bsgz** [comment]
> #1908

也没想到他是壁纸引起的啊
