### ISSUE TITLE
[Network]: 主窗口持续弹出请求 api.snapgenshin.com 的 404 错误通知

### ISSUE THREAD

**Issue by zhang258027** [DGP-Studio/Snap.Hutao#1925]
### 提交你的网络诊断报告

胡桃主窗口频繁弹出 api.snapgenshin.com 的 404 请求错误通知，且报错通知一直刷屏。
请问怎么才能让这个报错刷屏停下来？

![胡桃 1 11 0 0-2024-08-23_14-46](https://github.com/user-attachments/assets/eb1c53a5-1ffb-4a19-9ff7-c0a6ba2ec10b)

[SH-Report-18c7392d-4a4e-4e0b-85b0-d2a21b3c6682.zip](https://github.com/user-attachments/files/16724751/SH-Report-18c7392d-4a4e-4e0b-85b0-d2a21b3c6682.zip)

### 你的地理位置

湖南长沙

### 你的运营商

中国电信

### 你的问题

其它

### 你的问题（补充）

工具箱各项服务基本正常，api.snapgenshin.com 也能正常 ping 通

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Lightczx** [comment]
#1908
