### ISSUE TITLE
[Feat]:新版的胡桃导出的记录没有抽奖的名称和类型

### ISSUE THREAD

**Issue by TTiip** [DGP-Studio/Snap.Hutao#1928]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.2935

### Snap Hutao 版本

1.11.0.0

### 设备 ID

462E03AEE6EA6E4D8A61885CA3A75BBC

### 问题分类

祈愿记录

### 发生了什么？

新版的抽卡导出记录没有name和 type字段
![image](https://github.com/user-attachments/assets/607a57d1-ff9c-467f-a894-885290300b6c)
上图为新版导出记录

![image](https://github.com/user-attachments/assets/dca88dbe-260e-45d4-b91a-dfe3897f874b)
上图为旧版导出记录

### 你期望发生的行为？

导出记录正常展示name和type

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
UIGF 4 中 name 与 item_type 为非必要字段
