### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by CarefulDeveloper** [DGP-Studio/Snap.Hutao#193]
### Windows 版本

19041.264

### Snap Hutao 版本

1.23.0

### 发生了什么？

无法拖动程序窗口。
我查看了如下网站：
[Github WindowsAppSDK Issue](https://github.com/microsoft/WindowsAppSDK/issues/2976)
[胡桃工具箱官方文档](https://hut.ao/FAQ/most-frequent-questions.html)
我的版本是19041.264版本，满足文档要求但是依旧存在该bug。

### 你期望发生的行为？

窗口能够拖动。

### 相关的崩溃日志

```shell
无。
```

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
缩放过窗口了么

**Comment by CarefulDeveloper** [comment]
> 缩放过窗口了么

没有

**Comment by CarefulDeveloper** [comment]
为了解决这个bug，我特意把版本升到19044.2130，还是没解决

**Comment by Lightczx** [comment]
调整窗口大小后就应该能移动了

**Comment by CarefulDeveloper** [comment]
> 调整窗口大小后就应该能移动了


https://user-images.githubusercontent.com/78646351/200740756-4aefcc9c-9e85-4600-89f3-553607140fa7.mp4

**Comment by CarefulDeveloper** [comment]
> 调整窗口大小后就应该能移动了
这是我的操作录像
https://user-images.githubusercontent.com/78646351/200740965-30407eb9-afc7-47f5-8f0f-66af789f8fcb.mp4

**Comment by Lightczx** [comment]
调整大小是指鼠标移动到窗口边缘，对窗口大小进行调整，最大化/恢复不包括在缩放中

**Comment by CarefulDeveloper** [comment]
> 调整大小是指鼠标移动到窗口边缘，对窗口大小进行调整，最大化/恢复不包括在缩放中

好了好了，我的问题

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by Masterain98** [comment]
> @Masterain98 FYI

文档今日稍晚的时间会更新

**Comment by CarefulDeveloper** [comment]
> 调整大小是指鼠标移动到窗口边缘，对窗口大小进行调整，最大化/恢复不包括在缩放中

我又回去试了几下，发现他这个有时候还是会不行。
<video src="https://user-images.githubusercontent.com/78646351/200746877-228a4d41-d255-46c7-85b2-26c7efa382d4.mp4" type="video/mp4">
</videos>

**Comment by Masterain98** [comment]
> > @Masterain98 FYI
> 
> 文档今日稍晚的时间会更新

DGP-Studio/Snap.Hutao.Docs@a985892d11f4df2d23cfee2477eb4226a338daae
