### ISSUE TITLE
[Feat] 遊戲下載器繁體中文文本本地化

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#1930]
### 背景与动机

如圖 工具箱語言為繁體中文 但部分文本仍出現簡體中文
![螢幕擷取畫面 (303)](https://github.com/user-attachments/assets/d9d3afb6-346f-43e8-b7f4-48bb1b7e2a97)

![未命名](https://github.com/user-attachments/assets/cd9c54fb-f9a4-41d5-a38b-269baf7ef85e)

![螢幕擷取畫面 (314)](https://github.com/user-attachments/assets/7fa12d64-e094-4f44-9057-21fe258d105a)

![螢幕擷取畫面 (304)](https://github.com/user-attachments/assets/f3b644ec-5228-4608-a791-30faee226f64)

### 想要实现或优化的功能

將文本本地化翻譯
"x.x.x版本預下載已開啟"
"修復遊戲"
"更新遊戲"
"正在取得清單資料"
"正在加載清單文件"
"清單資料解析失敗"

**Comment by twjmy** [comment]
請前往存放庫主頁
# [本地化翻译 / Localization](https://github.com/DGP-Studio/Snap.Hutao#%E6%9C%AC%E5%9C%B0%E5%8C%96%E7%BF%BB%E8%AF%91--localization)
[![](https://camo.githubusercontent.com/449ea77d5fb94041c542f03ad4f92ec329f362f5f3879532712737844acb1032/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f636f6c6f723d626c7565266c6162656c3d7a682d5457267374796c653d666c6174266c6f676f3d63726f7764696e2671756572793d2532342e70726f67726573732535423f28402e646174612e6c616e677561676549643d3d2532377a682d5457253237292535442e646174612e7472616e736c6174696f6e50726f67726573732675726c3d68747470732533412532462532466261646765732e617765736f6d652d63726f7764696e2e636f6d25324673746174732d31353637303539372d3536353834352e6a736f6e)](https://crowdin.com/project/snap-hutao)

**Comment by Lightczx** [comment]
![image](https://github.com/user-attachments/assets/08bd80ac-43d4-4f62-a0cf-b0fc3d3c2ddf)
不明显么
