### ISSUE TITLE
[Bug]: 解锁帧率+兼容模式 游戏闪退

### ISSUE THREAD

**Issue by CreamPig233** [DGP-Studio/Snap.Hutao#1935]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.0.0

### 设备 ID

8D2277FCD8753E253C065D6907B9885A

### 问题分类

游戏启动器

### 发生了什么？

在勾选解锁帧率限制+兼容模式开启时，游戏无法启动。
表现为 点击启动游戏按钮后：
- 工具箱提示：解锁帧率上限成功>等待游戏进程退出
- 任务管理器可见游戏进程创建，任务栏有位置出现但没有图标
![image](https://github.com/user-attachments/assets/875bb6c0-1b91-4eef-ab67-1dc803fc112b)
- 几秒后游戏进程退出
调试控制台日志：https://pastebin.com/T4xKpNW7

关闭兼容模式时，游戏正常启动。但由于现在是停服维护时间，无法得知进入游戏是否报31-4302错误
(4.8.0版本时，本设备 解锁帧率限制+关闭兼容模式 会报31-4302错误)

### 你期望发生的行为？

解锁帧率功能正常使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by PeaceFamily000** [comment]
这个是5.0版本更新之后的bug（补充：有时可以看见原神启动时的背景变白，随后闪退），以及1.11.0版本的胡桃工具箱在关闭兼容模式的时候确实会有31-4302错误（4.8版本）。望尽快修复：）

**Comment by SSB-ARFCN** [comment]
有概率出現這個 仍然閃退  
![未命名](https://github.com/user-attachments/assets/00f8dc63-0e25-47d9-98eb-92a9bbad4148)

https://www.mediafire.com/file/03uctynn7rbe0oa/2024.08.28+-+09.55.10.04.mp4/file

**Comment by SSB-ARFCN** [comment]
從alt+tab發現遊戲啟動一個空白視窗

**Comment by RainSky233** [comment]
关闭兼容模式后能正常启动但解锁帧率不生效（

**Comment by nostalfinals** [comment]
我这边遇见的情况是，原神的窗口会弹出来，随后大概 1s 就闪退

**Comment by retaker** [comment]
> 我这边遇见的情况是，原神的窗口会弹出来，随后大概 1s 就闪退

+1

**Comment by NerounCstate** [comment]
+1

**Comment by lonelyzerg** [comment]
可以启动游戏，但是帧率解锁失效
![image](https://github.com/user-attachments/assets/cc8466ca-4e20-45a4-bb96-83ab729aa0b5)

**Comment by a654773927** [comment]
> 有概率出現這個 仍然閃退 ![未命名](https://private-user-images.githubusercontent.com/107019852/362093163-00f8dc63-0e25-47d9-98eb-92a9bbad4148.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjA1NDgsIm5iZiI6MTcyNDgyMDI0OCwicGF0aCI6Ii8xMDcwMTk4NTIvMzYyMDkzMTYzLTAwZjhkYzYzLTBlMjUtNDdkOS05OGViLTkyYTliYmFkNDE0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwNDQ0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGVkNjEzYzQ5MDVlOThjYTZkM2U5NjlkMDdlOWNlNmMwY2VhM2U0NjkxNGY4YWQzYTJhY2JiNDgzMTY4YTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aYJY3rvY7eugTKZk_oVhIhKSk4Tr_o9AbaCxo9uRgqc)
> 
> https://www.mediafire.com/file/03uctynn7rbe0oa/2024.08.28+-+09.55.10.04.mp4/file

这个窗口是只要启动时候按住Alt或者Ctrl就会跳出来，Unity特色

**Comment by Lightczx** [comment]
fixed

**Comment by SSB-ARFCN** [comment]
啥情況 兼容開和關都失效了 卡嘗試 退出遊戲了還等一分鐘才彈對話方塊
https://www.mediafire.com/file/ld6jqgkn7mxan51/2024.08.29+-+13.54.02.03.mp4/file

**Comment by Lightczx** [comment]
国服已经修复，如果国际服有问题请另开Issue
