### ISSUE TITLE
[Bug]: 角色界面和队伍界面角色显示问题

### ISSUE THREAD

**Issue by XiaonianChen** [DGP-Studio/Snap.Hutao#1938]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.0.0

### 设备 ID

D61F37EC994A79829E1559CF96570404

### 问题分类

其它

### 发生了什么？

第一次使用，不确定是否是个人设置问题。设置如下图所示：
![屏幕截图 2024-08-28 232259](https://github.com/user-attachments/assets/00338ec3-9231-4c0d-bba6-97c3e1529f05)
正常开启后，会出现人物角色偏小。
在不解锁帧率上限的情况下，其显示如下图所示：
![屏幕截图(73)](https://github.com/user-attachments/assets/2b3778d9-faf5-4380-9730-05c581662aaa)
但解锁后，其显示如下图所示：
![屏幕截图(74)](https://github.com/user-attachments/assets/61d753bd-6392-4053-b235-1c13d6b4d1ac)

而在队伍界面中，现象更明显：
![屏幕截图(75)](https://github.com/user-attachments/assets/d1725979-f72b-45b4-833b-54dc8a286d01)

### 你期望发生的行为？

期望显示正常

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
非兼容模式下会调整FOV
