### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by QiYue8792** [DGP-Studio/Snap.Hutao#194]
### Windows 版本

21H2

### Snap Hutao 版本

1.1.23.0

### 发生了什么？

不能改游戏无边框，改完后还是默认全屏

### 相关的崩溃日志

```shell
没有
```

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
你的全屏选项是否关闭

**Comment by QiYue8792** [comment]
确认是关闭状态，请看我发送的视频
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 晚上7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] [Bug]: 在这里填写一个合适的标题 (Issue #194)





 
你的全屏选项是否关闭
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Desktop 2022.11.08 - 19.33.48.02.mp4 (14.91M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6e313666b516279ee3f7bbe41264044e0e535204560202501a5206500749025354531b070502554c51060f5250050f54540402503440362552425d125b14165307030448055518510f111b46055d1852041f025e1a54044f5a41026609&t=exs_ftn_download&code=716f4d6a
