### ISSUE TITLE
[Bug]: 点击左侧边栏里的 角色资料 武器资料 怪物资料中的任意一个都会导致程序卡死，只能退出

### ISSUE THREAD

**Issue by zuiaiyutu** [DGP-Studio/Snap.Hutao#1940]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

win11 版本 23H2 (OS 内部版本 22631.4112)

### Snap Hutao 版本

1.11.0.0

### 设备 ID

9CBD651E52D60F42CD17F8771097A874

### 问题分类

其它

### 发生了什么？

点左侧边栏，工具-祈愿记录  无任何提示和反应，点其他任何地方都没反应，直接卡死
点角色资料 武器资料 怪物资料 提示“加载中，请稍后” 这个时候，软件直接卡死，点其他任何地方都没反应，只能退出

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
耐心等待即可，近期元数据变动较多需要下载完成后才能使用

**Comment by zuiaiyutu** [comment]
点重置图片资源，重新下载，依然是这样。而且在下载过程中，有2个明明没有下载完成，却不下载了，直接进入程序。这可能是卡的原因

**Comment by Lightczx** [comment]
> 点重置图片资源，重新下载，依然是这样。而且在下载过程中，有2个明明没有下载完成，却不下载了，直接进入程序。这可能是卡的原因

无关

**Comment by Samonyoge** [comment]
不开新问题了。
不翻墙开胡桃，就提示元数据校验文件下载失败，然后东西都显示不出，点开角色便签计划、角色武器怪物资料之类的就直接加载中无响应。
FQ以后都能打开了，而且还得开全局，别的识别不了。
福建电信。

**Comment by Lightczx** [comment]
@Samonyoge `ping static-next.snapgenshin.com` 看下结果

**Comment by Samonyoge** [comment]
> @Samonyoge `ping static-next.snapgenshin.com` 看下结果

ping这个没问题 没丢包延迟26ms，但是无代理打开胡桃依旧提示元数据校验文件下载失败，FQ后正常

**Comment by Lightczx** [comment]
ping的结果发截图

**Comment by Samonyoge** [comment]
> ping的结果发截图

![1](https://github.com/user-attachments/assets/eb208694-de70-4251-bf9c-2d924ca08437)
如图
