### ISSUE TITLE
[Bug]: 国际服不能解锁高帧率，同样设置的情况下国服没问题

### ISSUE THREAD

**Issue by RobinsonLauu** [DGP-Studio/Snap.Hutao#1942]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.0.0

### 设备 ID

18D011CDD767B78D000AB0D574A8A235

### 问题分类

游戏启动器

### 发生了什么？

国际服（亚服）不能解锁高帧率，同样设置的情况下过国服没问题
同一个电脑 同一个snaphutao，国际服解锁不了高帧率，上次更新之前是可以的 现在不行了 

### 你期望发生的行为？

国际服可解锁高帧率

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by SSB-ARFCN** [comment]
https://www.mediafire.com/file/ld6jqgkn7mxan51/2024.08.29+-+13.54.02.03.mp4/file

**Comment by bddyzpm** [comment]
> +1

注入模式无效，11.0又把经典模式删了，可以暂时退回10.7用

**Comment by Lightczx** [comment]
@SSB-ARFCN @bddyzpm 浏览器打开 https://api.snapgenshin.com/client/UnlockerIsland.json
看看结果是什么

**Comment by RobinsonLauu** [comment]
> > +1
> 
> 注入模式无效，11.0又把经典模式删了，可以暂时退回10.7用

打扰了 请问怎么装旧版本 官网只有最新的安装包

**Comment by SSB-ARFCN** [comment]
> @SSB-ARFCN @bddyzpm 浏览器打开 https://api.snapgenshin.com/client/UnlockerIsland.json 看看结果是什么

![螢幕擷取畫面 (320)](https://github.com/user-attachments/assets/ed3ff97f-6515-4e81-8670-9b7ffadad25b)

**Comment by SSB-ARFCN** [comment]
> > +1
> 
> 注入模式无效，11.0又把经典模式删了，可以暂时退回10.7用

好方法 感謝
![螢幕擷取畫面 (321)](https://github.com/user-attachments/assets/d4a28827-3530-43f0-92fe-a33635ba5a69)

**Comment by bddyzpm** [comment]
> @SSB-ARFCN @bddyzpm浏览器打开https://api.snapgenshin.com/client/UnlockerIsland.json 看看结果是什么

{
  "Oversea": {
    "FunctionOffsetFieldOfView": 28354192,
    "FunctionOffsetTargetFrameRate": 285177856,
    "FunctionOffsetFog": 284404960
  },
  "Chinese": {
    "FunctionOffsetFieldOfView": 28374672,
    "FunctionOffsetTargetFrameRate": 285179168,
    "FunctionOffsetFog": 284368800
  }
}

**Comment by Lightczx** [comment]
fixed
