### ISSUE TITLE
[Bug]: 纳塔5.0版本，就无法解除帧数上限，不管啥理由被锁60帧数

### ISSUE THREAD

**Issue by Wdszj** [DGP-Studio/Snap.Hutao#1945]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4112

### Snap Hutao 版本

1.11.0.0

### 问题分类

其它

### 发生了什么？

![Snipaste_2024-09-01_00-46-05](https://github.com/user-attachments/assets/d04f1220-c613-4a87-9073-1ff9317c8fa3)
更新到5.0版本纳塔之后，胡桃工具箱也更新了之后，发生比较奇怪BUG，不管啥理由，解锁不了帧数。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
fixed

**Comment by Wdszj** [comment]
等忙好工作，就回家研究看看。请期待~
