### ISSUE TITLE
[Feat]: 支持更低版本的UIGF文件导入最新版Snap Hutao

### ISSUE THREAD

**Issue by CTGWHWL** [DGP-Studio/Snap.Hutao#1951]
### 背景与动机

我是一位提瓦特小助手微信小程序使用者 在我今天**想要从提瓦特小助手小程序中提取很早之前的抽卡记录导入到胡桃内**后我发生了报错 随后我检查了很多问题 最终在https://uigf.org/发现了是格式问题  但胡桃已经不支持2.2的UIGF文件导入 

### 想要实现或优化的功能

目前我的情况是 我不想继续使用提瓦特小助手 我希望胡桃能再次捡起对老版本UIGF文件格式的支持（） 让我脱离提瓦特小助手并使用胡桃

**Comment by CTGWHWL** [comment]
他们公众号基本是半死不活状态了 不然我不信他们不会去适配新版本的这些记录

**Comment by qhy040404** [comment]
可前往 uigf.qhy04.com 进行升级

**Comment by SSB-ARFCN** [comment]
完整視頻 (上傳中 稍後可查看)
https://www.mediafire.com/file/ejosobnbvfdfduo/2024.09.04+-+20.59.45.03.mp4/file

**Comment by CTGWHWL** [comment]
> 可前往 [UIGF Upgrader](https://uigf.qhy04.com) 进行升级

感谢

**Comment by CTGWHWL** [comment]
> 可前往 [UIGF Upgrader](https://uigf.qhy04.com) 进行升级

 我在使用了这个工具之后胡桃工具箱在导入
[UIGF-Upgrader-1725463269397.json](https://github.com/user-attachments/files/16873122/UIGF-Upgrader-1725463269397.json)
的时候仍然报错以下是我的截图和我的文件
[导出前.json](https://github.com/user-attachments/files/16873123/default.json)

**Comment by CTGWHWL** [comment]
> > 可前往 [UIGF Upgrader](https://uigf.qhy04.com) 进行升级
> 
> 我在使用了这个工具之后胡桃工具箱在导入
> 
> 的时候仍然报错以下是我的截图和我的文件 [UIGF-Upgrader-1725463269397.json](https://github.com/user-attachments/files/16873122/UIGF-Upgrader-1725463269397.json) [导出前.json](https://github.com/user-attachments/files/16873123/default.json) ![image](https://private-user-images.githubusercontent.com/166948828/364441986-dc179100-6fe3-4e84-a5e4-0de2e0baa411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjQ1NjUsIm5iZiI6MTcyNTQ2NDI2NSwicGF0aCI6Ii8xNjY5NDg4MjgvMzY0NDQxOTg2LWRjMTc5MTAwLTZmZTMtNGU4NC1hNWU0LTBkZTJlMGJhYTQxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNTM3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDBmOTI3ZjA5NDk0ZDhiZTg2MGEwODIwNzRlOTE3MjU1ZWFkOTQwYzMwOWJhYjFhMzAwNjcwNTNhMTdkYTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4Bsa2DX-vS9AdWVKXvxPNkBN8lagICg51C6RyosYCXY)

 在我给这个玩意的头部部分就是非抽卡数据的最开始部分替换成胡桃工具箱后才成功识别 真是抽象的情况

**Comment by qhy040404** [comment]
> 在我给这个玩意的头部部分就是非抽卡数据的最开始部分替换成胡桃工具箱后才成功识别 真是抽象的情况

刚刚修复了，谢谢你的反馈

**Comment by jdy18** [comment]
请问一下导入功能在哪里呢？我刚换胡桃，好像没找到

**Comment by SSB-ARFCN** [comment]
在O置分找找看

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________

**Comment by SSB-ARFCN** [comment]
@jdy18 
![螢幕擷取畫面 (39)](https://github.com/user-attachments/assets/b77043be-c94c-49f1-aac1-f86a1dab6b83)
