### ISSUE TITLE
[Bug]: 使用我的角色功能从 米游社/HoYoLab 刷新角色时崩溃，此后只要切换到此功能即崩溃

### ISSUE THREAD

**Issue by DSakura207** [DGP-Studio/Snap.Hutao#1954]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.1.0

### 设备 ID

24F119BD7E75450A1122D23B4DC927FC

### 问题分类

我的角色

### 发生了什么？

试图使用“我的角色”功能从hoyolab拉取数据，程序崩溃。之后每次切换到这里都会导致程序崩溃。

Windows Event Log, Souce: Application Error, Event ID: 1000, Task Category Application Cashing Events
```
Faulting application name: Snap.Hutao.exe, version: 1.0.0.0, time stamp: 0x661f0000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.6.0, time stamp: 0xcb62d8fb
Exception code: 0xc000027b
Fault offset: 0x0000000000009125
Faulting process id: 0x0x8F38
Faulting application start time: 0x0x1DAFF035C085707
Faulting application path: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.11.1.0_x64__wbnnev551gwxy\Snap.Hutao.exe
Faulting module path: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.11.1.0_x64__wbnnev551gwxy\Microsoft.ui.xaml.dll
Report Id: ad4e7828-4c99-4415-976d-3c62c995a6df
Faulting package full name: 60568DGPStudio.SnapHutao_1.11.1.0_x64__wbnnev551gwxy
Faulting package-relative application ID: App
```

### 你期望发生的行为？

可以正常拉取数据，或是返回不支持的错误。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@DSakura207 给你的所有角色穿戴至少一个圣遗物即可

**Comment by Lightczx** [comment]
那就等下版本
