### ISSUE TITLE
[Bug]: 实时便笺无法刷新 -1 Data not exists

### ISSUE THREAD

**Issue by Wing11189** [DGP-Studio/Snap.Hutao#1955]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4291

### Snap Hutao 版本

1.11.1.0

### 问题分类

实时便笺

### 发生了什么？

更新完1.11.1.0后刷新实时便笺出现区域空白、报错，尝试删除角色、重置图片资源、重新安装操作仍未能恢复正常
![微信截图_20240905190359](https://github.com/user-attachments/assets/6303d20f-a4bf-4600-b355-291b45615181)

### 你期望发生的行为？

恢复实时便笺使用功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao/commit/58046110c6324d3a8c1613fe68ea87f2f982ed3f
