### ISSUE TITLE
[Bug]: 前面更新后发现高帧率的调整视野失效了，只要调整视野，连高帧率也解锁失败。昨天还可以，本来还在为能调整更高的视野高兴，结果发现不能用了

### ISSUE THREAD

**Issue by hjs0714** [DGP-Studio/Snap.Hutao#1956]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.1.0

### 设备 ID

04494FBE00318226FD4BDBB6E03B4213

### 问题分类

安装和环境

### 发生了什么？

前面更新后发现高帧率的调整视野失效了，只要调整视野，连高帧率也解锁失败。昨天还可以，本来还在为能调整更高的视野高兴，结果发现不能用了
34寸宽屏、165h 华硕的屏幕
13600kf 和 4070tisuper

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao/commit/58046110c6324d3a8c1613fe68ea87f2f982ed3f

**Comment by Lightczx** [comment]
#1957
