### ISSUE TITLE
[Bug]: 实时便签中魔神任务状态不正确

### ISSUE THREAD

**Issue by CreamPig233** [DGP-Studio/Snap.Hutao#1958]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4037

### Snap Hutao 版本

1.11.1.0

### 设备 ID

8D2277FCD8753E253C065D6907B9885A

### 问题分类

实时便笺

### 发生了什么？

实时便签中魔神任务状态显示不正确

距离完成魔神任务已经过12小时（甚至更长），米游社内状态正确，工具箱更新后仍不能正确显示

![image](https://github.com/user-attachments/assets/519ccf33-bd16-4fb7-b771-b6eb3a381616)

### 你期望发生的行为？

正确显示魔神任务状态

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1955
