### ISSUE TITLE
[Bug]: 危险功能 FPS解锁 无法保存设置

### ISSUE THREAD

**Issue by Askwind** [DGP-Studio/Snap.Hutao#196]
### Windows 版本

21H2 

### Snap Hutao 版本

1.1.23

### 发生了什么？

启动游戏 —— 危险功能——FPS解锁

用管理员权限启动hutao，FPS解锁功能设置无法 记录上一次的状态；

另此功能描述为英文。

### 你期望发生的行为？

FPS解锁功能 记录上一次的设置状态，即开关状态 和 FPS的数值；

此功能建议中文化

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by AdminRoc** [comment]
导出祈愿记录保存，在电脑中打开%userprofile%/documents/hutao目录，将此目录清空，重新安装后，检查功能是否恢复（https://hut.ao/FAQ/most-frequent-questions.html#%E5%BD%93%E7%94%A8%E6%88%B7%E5%85%B7%E6%9C%89%E5%A4%9A%E4%B8%AA%E7%A5%88%E6%84%BF%E8%AE%B0%E5%BD%95%E5%AD%98%E6%A1%A3%E6%97%B6-%E5%8F%AF%E8%83%BD%E5%87%BA%E7%8E%B0%E6%97%A0%E6%B3%95%E7%82%B9%E9%80%89%E5%88%87%E6%8D%A2%E8%87%B3%E5%85%B6%E4%BB%96uid%E5%AF%B9%E5%BA%94%E5%AD%98%E6%A1%A3%E7%9A%84%E6%83%85%E5%86%B5）

**Comment by Askwind** [comment]
> 导出祈愿记录保存，在电脑中打开%userprofile%/documents/hutao目录，将此目录清空，重新安装后，检查功能是否恢复

设置保存问题解决了，中文化问题请考虑下，谢谢！
