### ISSUE TITLE
[Bug]: 祈愿记录导出的json文件无法被提瓦特小助手识别

### ISSUE THREAD

**Issue by woditianaaaa** [DGP-Studio/Snap.Hutao#1960]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4651

### Snap Hutao 版本

1.11.1.0

### 设备 ID

E93981E452817516739A075335F4CA49

### 问题分类

祈愿记录

### 发生了什么？

在胡桃中使用祈愿记录导出功能可得到一个Snap Hutao UIGF.json文件，在微信小程序提瓦特小助手中，选择祈愿记录导入功能，选择此文件，显示不符合UIGF格式。但是提瓦特小助手下已写明胡桃支持此格式

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
json文件使用 [UIGF Upgrader](https://upgrader.uigf.org) 升级后导入
