### ISSUE TITLE
[Bug]: 打开软件后点击我的角色会闪退，账号是官服，并不是hoyolab的外服

### ISSUE THREAD

**Issue by Georgebillion** [DGP-Studio/Snap.Hutao#1963]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4651

### Snap Hutao 版本

1.11.1.0

### 设备 ID

713B2DC293772C50780E258915CA3D71

### 问题分类

我的角色

### 发生了什么？

1.打开软件
2.点击我的角色
3.闪退
4.重复1-2步骤依旧闪退

### 你期望发生的行为？

应该能打开相关界面

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
#1954
国服国际服一样的解决方案
