### ISSUE TITLE
[Bug]: 下载游戏时CPU异常高负载

### ISSUE THREAD

**Issue by zlww2n1s1s** [DGP-Studio/Snap.Hutao#1964]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4112

### Snap Hutao 版本

1.11.1.0

### 设备 ID

C98237E35B7AAA797557D28D6E460790

### 问题分类

游戏启动器

### 发生了什么？

使用胡桃下载bilibili渠道服，汉语配音版时，cpu会瞬间负载拉满到100%，同时下载至5%~15%间下载会卡死，ETA显示为--:--:--。

### 你期望发生的行为？

下载进度不会异常终止，cpu占用正常

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
非常好代码，使我的 CPU 旋转
