### ISSUE TITLE
[Bug]: 元数据校验文件下载失败，已解锁loopback

### ISSUE THREAD

**Issue by pik553** [DGP-Studio/Snap.Hutao#1965]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3803

### Snap Hutao 版本

1.11.1.0

### 问题分类

其它

### 发生了什么？

报错提示：HTTP | Error:SecureConnectionError:元数据校验文件下载失败
具体表现：除主页、反馈中心、设置，打开其他界面均白屏
尝试过的解决办法：按照文档内容，解锁loopback（无用）、重置图片资源（可行，但每次打开胡桃都必须重置资源，不然关闭胡桃五分钟左右后再次打开，依然白屏）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
访问 http://dns-detect-portal.n.cdnhwc5.cn/?domain=api.snapgenshin.com 并在其中信息完全显示出来后截图并上传

**Comment by pik553** [comment]
> 访问 http://dns-detect-portal.n.cdnhwc5.cn/?domain=api.snapgenshin.com 并在其中信息完全显示出来后截图并上传

![QQ图片20240909190114](https://github.com/user-attachments/assets/441920cc-f107-4a37-b935-166ecb54d9fc)
曾显示404和error，多次刷新后显示数据如附件。
另之后也开了VPN尝试，前几次同样显示error，后期会显示数据。

**Comment by Lightczx** [comment]
@pik553 在胡桃设置中启用调试控制台，并在主界面显示下载元数据校验文件下载失败时截控制台的错误

**Comment by SSB-ARFCN** [comment]
> 访问 http://dns-detect-portal.n.cdnhwc5.cn/?domain=api.snapgenshin.com 并在其中信息完全显示出来后截图并上传

![螢幕擷取畫面 (336)](https://github.com/user-attachments/assets/eb06ab71-56a2-4dae-b690-76b9e2364f03)

我的為啥是404

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (337)](https://github.com/user-attachments/assets/7b439a59-233f-4d43-beb8-df564b17accc)


> > 访问 http://dns-detect-portal.n.cdnhwc5.cn/?domain=api.snapgenshin.com 并在其中信息完全显示出来后截图并上传

我這也是 F5 按了10多次才出

**Comment by Lightczx** [comment]
@pik553 你确定你的日志是在下载校验文件失败后复制的么，似乎不是很全

**Comment by Lightczx** [comment]
直接在浏览器中打开 https://api.snapgenshin.com/metadata/Genshin/CHS/meta.json 试试吧

**Comment by vvb7456** [comment]
> 直接在浏览器中打开 https://api.snapgenshin.com/metadata/Genshin/CHS/Meta.json 试试吧

![0911](https://github.com/user-attachments/assets/491bb293-c4d8-4387-b9b9-56d1b981c1ce)

**Comment by Masterain98** [comment]
> Meta.json M大写

其实这个都无所谓了，404也是获取到了数据，连接是没问题的

**Comment by SSB-ARFCN** [comment]
> @SSB-ARFCN 能试一下直接浏览器访问 https://api.snapgenshin.com/metadata/Genshin/CHS/Meta.json 是否可以看到内容？浏览器跳转后的 URL 是什么？

![chrome_screenshot_2024年9月11日 下午5_21_33  GMT+08_00](https://github.com/user-attachments/assets/5581f165-9aa5-4592-a4bf-fdd017e7f441)
用安卓手機開能看到一些項目和16進位代號
一會兒用pc試試 運營商不同

**Comment by SSB-ARFCN** [comment]
> @SSB-ARFCN 能试一下直接浏览器访问 https://api.snapgenshin.com/metadata/Genshin/CHS/Meta.json 是否可以看到内容？浏览器跳转后的 URL 是什么？

URL https://hutao-metadata-pages.snapgenshin.cn/Genshin/CHS/Meta.json

**Comment by Masterain98** [comment]
> > @SSB-ARFCN 能试一下直接浏览器访问 https://api.snapgenshin.com/metadata/Genshin/CHS/Meta.json 是否可以看到内容？浏览器跳转后的 URL 是什么？
> 
> URL https://hutao-metadata-pages.snapgenshin.cn/Genshin/CHS/Meta.json

你上面的截图，和这个重定向 URL 都是预期内正确的情况。

**Comment by SSB-ARFCN** [comment]
> 你上面的截图，和这个重定向 URL 都是预期内正确的情况。
華為雲那個用安卓手機刷新3次就出了


看起來 我該試試用這台安卓手機開wlan共享至pc再試試胡桃工具箱是否正常運作

**Comment by Masterain98** [comment]
> > 你上面的截图，和这个重定向 URL 都是预期内正确的情况。
> 
> @Masterain98 華為雲那個用安卓手機刷新3次就出了
> 
> 看起來 我該試試用這台安卓手機開wlan共享至pc再試試胡桃工具箱是否正常運作

中国大陆以外地区是重定向到 GitHub 的，绝大多数情况下不会有问题，没必要刻意去连接华为云节点。

**Comment by SSB-ARFCN** [comment]
@Masterain98  感謝 用安卓手機開wlan連接PC  已可正常使用 
![螢幕擷取畫面 (347)](https://github.com/user-attachments/assets/ef210af3-9097-4d64-8831-57077d46429f)
![螢幕擷取畫面 (348)](https://github.com/user-attachments/assets/9a4737b5-9260-4b04-ad11-591f8cb830f3)
URL 
https://hutao-metadata-pages.snapgenshin.cn/Genshin/CHS/Meta.json

![螢幕擷取畫面 (349)](https://github.com/user-attachments/assets/dc3d950f-882a-4adc-8a07-e0811fb001b7)

**Comment by Masterain98** [comment]
@SSB-ARFCN 所以你的固定宽带下，会出现怎样的错误？能尝试上述的测试吗？

**Comment by SSB-ARFCN** [comment]
> @SSB-ARFCN 所以你的固定宽带下，会出现怎样的错误？能尝试上述的测试吗？

使#1953 常復現 (約30%) 即時便籤出不來 會整個工具箱變灰無法點擊任何按鈕 沒彈對話方塊抱錯  只能用工作管理員結束

一會兒試

**Comment by vvb7456** [comment]
> @SSB-ARFCN 所以你的固定宽带下，会出现怎样的错误？能尝试上述的测试吗？

我也尝试了pc禁用有线网络并连接热点 同样 可以正常打开程序 不会再出现“元数据校验文件下载失败”的提示
神奇的是 接下来我关闭热点 重新连接至有线网络 重启胡桃 程序竟然也正常启动了 @SSB-ARFCN 你可以试试
我的ISP是中国电信（手机热点与固定宽带的ISP一致）

**Comment by SSB-ARFCN** [comment]
> 我也尝试了pc禁用有线网络并连接热点 同样 可以正常打开程序 不会再出现“元数据校验文件下载失败”的提示 神奇的是 接下来我关闭热点 重新连接至有线网络 重启胡桃 程序竟然也正常启动了 @SSB-ARFCN 你可以试试 我的ISP是中国电信（手机热点与固定宽带的ISP一致）


那我得從華為路由器把APTG sim 卡拔出來試試了

**Comment by SSB-ARFCN** [comment]
> 我也尝试了pc禁用有线网络并连接热点 同样 可以正常打开程序 不会再出现“元数据校验文件下载失败”的提示 神奇的是 接下来我关闭热点 重新连接至有线网络 重启胡桃 程序竟然也正常启动了 @SSB-ARFCN 你可以试试 我的ISP是中国电信（手机热点与固定宽带的ISP一致）


一會試試RJ45和USB網路共用

**Comment by Masterain98** [comment]
在9月11日下午进行了一次路由调整，主要修复了福建地区出现的网络问题。如果近期仍然有类似的问题可以艾特我。

**Comment by jinyiwei2012** [comment]
![image](https://github.com/user-attachments/assets/465929d5-c5bc-490a-8665-69eed1fc2efb)

**Comment by SSB-ARFCN** [comment]
> 
> 我也尝试了pc禁用有线网络并连接热点 同样 可以正常打开程序 不会再出现“元数据校验文件下载失败”的提示 神奇的是 接下来我关闭热点 重新连接至有线网络 重启胡桃 程序竟然也正常启动了 @SSB-ARFCN 你可以试试 我的ISP是中国电信（手机热点与固定宽带的ISP一致）

神操作 我把華為路由器wifi和RJ45反覆切換多次後就正常了  (ISP : APTG)

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (351)](https://github.com/user-attachments/assets/f1b2f580-28a8-491b-8e32-846bfcd94ead)

https://hutao-metadata-pages.snapgenshin.cn/Genshin/CHS/Meta.json

![螢幕擷取畫面 (352)](https://github.com/user-attachments/assets/7dae6d35-39ab-463b-9a4b-d955e98a764f)

能正常使用 但載入慢了點 (5s) 


安卓手機一點就開

> @SSB-ARFCN 所以你的固定宽带下，会出现怎样的错误？能尝试上述的测试吗？

**Comment by SSB-ARFCN** [comment]
題外話 APTG 自從被FET併購後 連線品質有下降 網上一搜有不少案例
看起來是運營商的鍋 剛下載星鐵也斷兩次(瀏覽器下載2.4->2.5更新包)
