### ISSUE TITLE
[Bug]: [国际服] Hoyolab网页登录后无法获取cookie，报错网络请求异常

### ISSUE THREAD

**Issue by TheTychoStar** [DGP-Studio/Snap.Hutao#1966]
### 提交你的网络诊断报告

问题简述：使用Hoyolab登录功能，在正常登录Hoyolab账号后，点击“我已登录”报错，提示网络请求异常。
错误提示如下图。

> ![image](https://github.com/user-attachments/assets/176a4e26-a47f-47ff-bf4e-6ea767042e8c)

网络诊断数据：
[SH-Report-a59cbeed-1658-4dff-99b9-c5dff1bb84b2.zip](https://github.com/user-attachments/files/16923529/SH-Report-a59cbeed-1658-4dff-99b9-c5dff1bb84b2.zip)

详细描述：
约1周以前，当时胡桃版本为1.10，启动时发现已登录的两个账号信息丢失（国服和国际服账号各一），祈愿记录、我的角色等功能无法使用，表现为点击祈愿记录/我的角色后右侧界面空白且胡桃进入卡死状态无法操作，只能通过任务管理器强制结束进程。重启后尝试重新登录账号，国服与国际服账号均无法登录。

先尝试通过设置导出祈愿记录并重新导入，问题依旧。后彻底卸载胡桃、删除数据文件夹并重新安装，依然无法登录、无法使用祈愿记录功能。

之后看到更新了1.11版本，重新安装1.11版本后，祈愿记录功能恢复正常，国服账号也可以正常登录了，但Hoyolab依然无法成功登录。持续几日至今依然无法登录，网络环境未发生改变。人在加拿大，都是直连没有使用任何网络加速器，内置浏览器里Hoyolab账号是可以成功登录的，只是下一步里胡桃无法获取到cookie。故来github提交问题。

### 你的地理位置

加拿大

### 你的运营商

其它

### 你的问题

获取到了不正确的页面或数据

### 你的问题（补充）

网络运营商Bell Canada

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by Lightczx** [comment]
@qhy040404 看上去国际服好像也不支持login_ticket->stoken了

**Comment by Lightczx** [comment]
目前所有的国际服功能支持均由社区贡献，在国际服无法使用某些功能时我们仅提供有限的支持。
如果有人愿意贡献修复这些功能的代码，非常欢迎对 `develop` 分支发起 PR。

Currently, all Hoyoverse/HoYoLAB feature support is contributed by the community, and we only provide limited support when some features are not available on the it.
If anyone would like to contribute code that fixes these features, a PR to the 'develop' branch is more than welcome.

**Comment by SSB-ARFCN** [comment]
開了偵錯主控台 看dos視窗 用edge依賴瀏覽器登入後能取得cookie 但胡桃未成功將cookie正確登入並使用實時便籤 hoyolab聖遺物查詢 等功能

**Comment by SSB-ARFCN** [comment]
若直接用hoyolab登入呢？不要用近期已更新的通行證網頁
是否能正常使用取得的cookie？

可惜胡桃沒有建置瀏覽器手動輸入URL填寫處 要是像steam的遊戲內瀏覽器有URL填寫處就能試試

**Comment by SSB-ARFCN** [comment]
斷網能卡出舊版通行證 
![Screenshot_2024-09-12-17-29-16-295_com android chrome](https://github.com/user-attachments/assets/8178333c-60e8-4245-be61-91ac89229db7)
![Screenshot_2024-09-12-17-29-22-392_com android chrome](https://github.com/user-attachments/assets/027d12ee-a3ee-408a-964c-89934674a0da)
![Screenshot_2024-09-12-17-29-25-730_com android chrome](https://github.com/user-attachments/assets/d1882593-7ef2-4ea9-8c10-ab058e2852c9)

**Comment by galeondx** [comment]
同求

**Comment by SSB-ARFCN** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/issues/46

**Comment by SSB-ARFCN** [comment]
#2000

**Comment by ipisano** [comment]
那么，如果我使用其他方法获取 cookie/令牌，到底能不能成功？ 还有其他变通办法吗？
So if I managed to obtain the cookie/token by using other methods would it work or not? Any other workarounds?

**Comment by SSB-ARFCN** [comment]
需要包含Stoken

**Comment by sjhnight** [comment]
這問題至今有辦法解決嗎?

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11319820501
Any guys test this?

**Comment by JIFVGWHvAseSovQ** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11319820501 有人测试这个吗？

[https://i.postimg.cc/g2cPQ3DX/Snipaste-2024-10-14-20-29-15.png](url)

**Comment by SSB-ARFCN** [comment]
> [https://i.postimg.cc/g2cPQ3DX/Snipaste-2024-10-14-20-29-15.png](url)

![Screenshot_2024-10-14-20-32-39-919_com android chrome](https://github.com/user-attachments/assets/587e645b-5a69-482e-b362-068d51e19f8b)

空的

**Comment by SSB-ARFCN** [comment]
@JIFVGWHvAseSovQ 
或許憑證安裝錯位置了，重新安裝至正確位置試試

**Comment by TheTychoStar** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11319820501 Any guys test this?

This version works. I can login to my Hoyolab account with this version.
![testhoyolab](https://github.com/user-attachments/assets/7082c3d5-08e5-486f-877a-11b34b3ab22f)

**Comment by JIFVGWHvAseSovQ** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11319820501 Any guys test this?

![Snipaste_2024-10-15_07-09-08](https://github.com/user-attachments/assets/5ef6525f-8084-496e-baed-c7cc0044e091)
