### ISSUE TITLE
[Feat]: "你正在啟用一個危險功能" 字體色彩太淺 難以辨識輸入內容

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#1968]
### 背景与动机

啟用危險功能時 需輸入標題文本作為驗證 輸入錯誤的文本 會導致無法繼續開啟 
而輸入文本的填寫處 字體太淺 湳以辨識內容(14吋筆記型電腦用戶) 需在其他位置輸入後再貼上 或windows設定開啟高對比 才能辨識是否有錯字
![螢幕擷取畫面 (343)](https://github.com/user-attachments/assets/8366785e-003c-4113-83b1-3b0d0a9a52fb)
![螢幕擷取畫面 (344)](https://github.com/user-attachments/assets/6a269ad1-6270-46e5-9dc0-928a8a96ea25)
![螢幕擷取畫面 (345)](https://github.com/user-attachments/assets/16a2e806-baa2-4228-a46c-26da44453215)

### 想要实现或优化的功能

將輸入文本的填寫處 字體設為黑色

**Comment by qhy040404** [comment]
intended

**Comment by Lightczx** [comment]
@qhy040404 感觉需要对高对比度也限制一下，高对比度下相当于绕过了我们的限制

**Comment by SSB-ARFCN** [comment]
把對比度處理掉了 還有複製貼上 截圖後放大 顯卡驅動/部分顯示器銳利化等其他破解方式

或許可以把它們藏在某一個或多設定項目裡 連續開關n次或者連續點擊n次才能開啟
這樣既不會有文字難以辨識的問題 也不會有對比度繞過限制的問題

比如安卓開發者選項各家廠商都將他們藏在系統版本
菜單 連續點擊多次才能開啟 
![Screenshot_2024-09-11-18-27-04-407_com android settings](https://github.com/user-attachments/assets/0bceca4f-4aa1-4096-96b5-70fd60cc647b)

**Comment by Lightczx** [comment]
只是为了简单的防止内容创作者较为容易的创作相关的启用解锁帧率的教程视频，本身解锁步骤并会不考虑过于繁琐的操作
