### ISSUE TITLE
[Bug]: 測試版安裝失敗 0x80040154

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#1975]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2(OS組建19045.3803)

### Snap Hutao 版本

2024.9.13.12

### 设备 ID

26A3CF99630E579F6135632638122B4A

### 问题分类

安装和环境

### 发生了什么？

安裝測試版胡桃工具箱失敗  
報錯:應用程式安裝失敗，錯誤訊息為: 類別未登錄 (0x80040154)
已安裝憑證但仍無法安裝測試版胡桃工具箱 
https://www.mediafire.com/file/krej7pdedt3e66j/2024.09.13+-+20.41.51.01.mp4/file

### 你期望发生的行为？

正常安裝

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (361)](https://github.com/user-attachments/assets/75579c01-e1db-4619-bbb8-7c8f2022e4f2)

**Comment by Lightczx** [comment]
#1225
