### ISSUE TITLE
[Feat]: 请更新圣遗物评分准则

### ISSUE THREAD

**Issue by bingyang2000** [DGP-Studio/Snap.Hutao#198]
### 你想要实现或优化的功能？

更新圣遗物评分准则，例如：纳西妲

**Comment by Masterain98** [comment]
[https://hut.ao/FAQ/artifact-rating-rules.html](https://hut.ao/FAQ/artifact-rating-rules.html)

Notes here. Pending updates.

**Comment by Lightczx** [comment]
请填写下表并给出评分的说明 @bingyang2000 

|项目|评分占比(0-100)|
|-|-|
|生命值%||
|攻击力%||
|防御力%||
|暴击率||
|暴击伤害||
|元素精通||
|充能效率||
|治疗加成||
|元素伤害||

**Comment by bingyang2000** [comment]
| 项目 | 评分占比(0-100)|
| --- | --- |
| 角色名称 | 纳西妲 |
| 生命值% | 0 |
| 攻击力% | 55 |
| 防御力% | 0 |
| 暴击率% | 100 |
| 暴击伤害% | 100 |
| 元素精通% | 100 |
| 充能效率% | 55 |
| 元素伤害% | 100 |
纳西妲是一个优先于精通双暴增伤的草元素副c，伤害不过分依赖于攻击力，自身产球效率较高，对充能也不过分依赖，与生命值和防御力无关

**Comment by Lightczx** [comment]
感谢你的建议，会在后续版本实装此评分

**Comment by fuchen828** [comment]
提纳里精通词条无效，也请一并更新
![image](https://user-images.githubusercontent.com/56901043/205201901-1667ab72-905d-46d0-847c-65f9e7b46b7a.png)

**Comment by Lightczx** [comment]
@fuchen828 开个新issue
