### ISSUE TITLE
[Bug]: 成就管理界面频繁卡死

### ISSUE THREAD

**Issue by Bupleurum1020** [DGP-Studio/Snap.Hutao#1982]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23H2

### Snap Hutao 版本

1.11.1.0

### 设备 ID

36E0FC04B19B9E83969A4E68054AEF91

### 问题分类

成就管理

### 发生了什么？

切换到成就管理分页之后，会在一小段时间内卡死。
卡死之后，最小化最大化和关闭程序仍然可以使用，但软件界面内的所有点击没反应。
-------
如果在第一时间搜索某项成就可以缓解这种情况，但仍然有概率卡死。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Bupleurum1020** [comment]
确实是一样的问题……

但我的分辨率是1920*1080，缩放100%……居然也能触发bug【

**Comment by Lightczx** [comment]
无法复现

**Comment by Lightczx** [comment]
看上去是WinUI的问题
