### ISSUE TITLE
[Feat]: 我的角色同步渠道

### ISSUE THREAD

**Issue by Anrande** [DGP-Studio/Snap.Hutao#1984]
### 背景与动机

1.11.1.0之前，同步我的角色可以从橱窗、战绩、和养成计划来，但自从更新之后就再也没有了，只有战绩，这样同步天赋和命座就会很慢
![1](https://github.com/user-attachments/assets/d1c11de8-452a-471b-a11c-e06f96ca6c4d)

### 想要实现或优化的功能

推荐回复以前的我的角色同步的三个渠道，这样可以加快同步角色命座和天赋的速度

**Comment by Lightczx** [comment]
不会考虑
