### ISSUE TITLE
[Bug]:为什么“深境螺旋”这里开始时间是20年7月1日？

### ISSUE THREAD

**Issue by YYBYX** [DGP-Studio/Snap.Hutao#1985]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4780

### Snap Hutao 版本

1.11.1

### 问题分类

深境螺旋/胡桃数据库

### 发生了什么？

<img width="205" alt="Snipaste_2024-09-16_22-41-18" src="https://github.com/user-attachments/assets/fb0e506a-5864-4053-b114-d844d4e4c7e4">
如题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
为什么“深境螺旋”这里开始时间不能是20年7月1日呢？

**Comment by YYBYX** [comment]
但是游戏不应该是9月开服的吗

**Comment by Lightczx** [comment]
你不知道PC提前上线？

**Comment by Lightczx** [comment]
而且还有三测
