### ISSUE TITLE
[Bug]: 成就管理bug

### ISSUE THREAD

**Issue by Meow1026** [DGP-Studio/Snap.Hutao#1987]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4894

### Snap Hutao 版本

1.11.1.0

### 设备 ID

2E33FD342E8D1D0917D9F83D044D2308

### 问题分类

成就管理

### 发生了什么？

我有3个原神号，点成就管理，只能看到最后一个号，点下拉菜单，选别的号的成就，显示不出来。所以说，下拉菜单切成就账号这个按钮失效了，切了没反应。

### 你期望发生的行为？

之前版本下拉菜单切换是没有问题的，希望可以修复。辛苦工作人员。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Meow1026** [comment]
![image](https://github.com/user-attachments/assets/dd695d1c-49e0-4062-87bc-923447fcfc64)
只显示最后一个号的成就，点切换选择别的号是没有反应的。

**Comment by Meow1026** [comment]
您好，是这个问题已经修复，但是目前版本体现不了。要下个版本吗？

**Comment by Meow1026** [comment]
您好我更新到1.11.2.0但是和上一个版本效果一样，依然只显示一个号的成就，无法通过下拉菜单切换到别的号来显示成就

**Comment by Meow1026** [comment]
打开调试控制台后，去按成就下拉菜单试图切换显示别的号成就，依然无法实现功能，并未发现报错

**Comment by Meow1026** [comment]
![image](https://github.com/user-attachments/assets/3a56af86-7e78-4bcd-9994-c43dad2d8edd)

**Comment by Lightczx** [comment]
把你的Userdata.db发我

**Comment by Meow1026** [comment]
请问我该如何提供Userdata.db，找了一下没有找到该功能

**Comment by Lightczx** [comment]
@Meow1026 
![image](https://github.com/user-attachments/assets/32efd7ab-e5a0-4bd0-bd37-4c7c99e23439)

**Comment by Meow1026** [comment]
[Userdata.zip](https://github.com/user-attachments/files/17080336/Userdata.zip)

**Comment by Lightczx** [comment]
无法复现，建议不要再用Win10

**Comment by Mikachu2333** [comment]
> 无法复现，建议不要再用Win10

Win10也没法复现……

**Comment by Meow1026** [comment]
谢谢各位的帮助，暂时没有用Win11的打算，但是之前版本这个功能是没有问题的。暂时无法解决，那就这样吧。辛苦了！

**Comment by Mikachu2333** [comment]
> 谢谢各位的帮助，暂时没有用Win11的打算，但是之前版本这个功能是没有问题的。暂时无法解决，那就这样吧。辛苦了！

我的建议是删除配置文件，一切重来就行了……
