### ISSUE TITLE
[Feat]: 世界9怪物等级改变

### ISSUE THREAD

**Issue by halointernet** [DGP-Studio/Snap.Hutao#1988]
### 背景与动机

原神官方把世界等级最高提升到了9，能不能把怪物等级上限提高，目前世界等级9的boss提升到了103级，现在软件拖动条只能到100

### 想要实现或优化的功能

修改怪物等级在世界9的情况下提高了上限，改变胡桃怪物信息

**Comment by Mikachu2333** [comment]
关联 
https://github.com/orgs/DGP-Studio/projects/9/views/1?pane=issue&itemId=79824474
https://github.com/orgs/DGP-Studio/projects/9/views/1?pane=issue&itemId=79824559
