### ISSUE TITLE
[ENG][Bug]: Place your Issue Title Here

### ISSUE THREAD

**Issue by SylverVG** [DGP-Studio/Snap.Hutao#1995]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

22631.4169

### Snap Hutao Version

1.11.2.0

### Device ID

A3B5BDE22DC2DC0280D109BE7D3F88F9

### Issue Category

MiHoYo Account Panel

### What Happened?

![Screenshot 2024-09-18 234913](https://github.com/user-attachments/assets/f1778913-a84f-424f-b6e5-dd4cf3f5a1f4)
Cannot login always showing this pop.up

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by qhy040404** [comment]
目前所有的国际服功能支持均由社区贡献，在国际服无法使用某些功能时我们仅提供有限的支持。
如果有人愿意贡献修复这些功能的代码，非常欢迎对 develop 分支发起 PR。

Currently, all Hoyoverse/HoYoLAB feature support is contributed by the community, and we only provide limited support when some features are not available on the it.
If anyone would like to contribute code that fixes these features, a PR to the develop branch is more than welcome.

**Comment by BTMuli** [comment]
Duplicated as #1966
