### ISSUE TITLE
[Bug]: 抽卡记录的导出导入按钮没了？？？

### ISSUE THREAD

**Issue by AlbertWen-AW** [DGP-Studio/Snap.Hutao#1996]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4894（Windows 10 22H2）

### Snap Hutao 版本

1.11.2.0

### 设备 ID

4FC1ED86EBA424206ACEC3159262BC67

### 问题分类

祈愿记录

### 发生了什么？

如题如图
![QQ截图20240919154820](https://github.com/user-attachments/assets/3af70605-bb92-43a7-9a2e-78988c4ecf62)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
在设置里面

**Comment by Mikachu2333** [comment]
![Screenshot_2024-09-19-16-18-51-630_org mozilla firefox](https://github.com/user-attachments/assets/9a83a760-c0b3-4f5b-b619-bfe79e67d5bd)


参考更新日志

**Comment by AlbertWen-AW** [comment]
哦哦，发现了，不过我还是建议改回原来在祈愿记录里，这样更简便直观一些，然后可以在导入里添加升级UIGF版本的选项

**Comment by Mikachu2333** [comment]
可以另开个feature

**Comment by Lightczx** [comment]
UIGF 4 支持单文件多 UID，所以不能在祈愿页面内处理导入

**Comment by jdy18** [comment]
这也太隐蔽了，我找了老半天

建议至少祈愿位置加一个跳转入口

祈愿的导入不在祈愿反而在设置里，实在有点反直觉
