### ISSUE TITLE
[Feat]: 纳塔地方传奇资料缺失

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#1997]
科西霍等不存在

**Comment by Mikachu2333** [comment]
暂无精力解决

**Comment by Mikachu2333** [comment]
[怪物缺失汇总.txt](https://github.com/user-attachments/files/17071449/default.txt)

**Comment by SSB-ARFCN** [comment]
api 發生 not found
![螢幕擷取畫面 (12)](https://github.com/user-attachments/assets/15d37b0a-785e-494d-8b36-39fb85c80e66)

**Comment by Mikachu2333** [comment]
> api 發生 not found ![螢幕擷取畫面 (12)](https://github.com/user-attachments/assets/15d37b0a-785e-494d-8b36-39fb85c80e66)

与此无关
