### ISSUE TITLE
[Bug]: [版本无关]任意游戏版本解锁帧率功能均不可用

### ISSUE THREAD

**Issue by RobinsonLauu** [DGP-Studio/Snap.Hutao#1998]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4169

### Snap Hutao 版本

1.11.2.0

### 设备 ID

18D011CDD767B78D000AB0D574A8A235

### 问题分类

游戏启动器

### 发生了什么？

最先版本无法解锁帧率，点击启动游戏后显示正在尝试解锁，进入游戏以后还是锁60fps，过程中无报错，没有提示无法加密

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
进入后提示什么

**Comment by RobinsonLauu** [comment]
> 进入后提示什么

没有任何提示

**Comment by Lightczx** [comment]
![image](https://github.com/user-attachments/assets/f0029830-8971-4914-8f87-6643d96cca78)
会显示什么

**Comment by RobinsonLauu** [comment]
> ![image](https://private-user-images.githubusercontent.com/36357191/369606910-f0029830-8971-4914-8f87-6643d96cca78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDg5MzMsIm5iZiI6MTcyNjkwODYzMywicGF0aCI6Ii8zNjM1NzE5MS8zNjk2MDY5MTAtZjAwMjk4MzAtODk3MS00OTE0LThmODctNjY0M2Q5NmNjYTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA4NTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkODU0OGNjYThkMWNhNWVmNGEyNDU2NWI3MzJlNTU3ZGFjMGM1YWI5NjVkN2VjMjViZjJhNTU1NTBmOGZhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7vs4Hp2JteDXWMmzmEilL5QkMT_3rfk77M1DOwOzEqU) 会显示什么

这个显示完过后会显示 等待游戏进程退出 
![image](https://github.com/user-attachments/assets/96189388-f518-43e8-b562-69b7cfaa6592)

**Comment by RobinsonLauu** [comment]
我是国服+国际服两个号

之前的话国服得用注入 不然经典模式进副本回变回60fps
国际服得用经典 因为注入不起作用

请问是新版本把经典模式删除 默认注入了吗  因为我国服现在没问题了 国际服高刷不起作用

**Comment by Lightczx** [comment]
目前所有的国际服功能支持均由社区贡献，在国际服无法使用某些功能时我们仅提供有限的支持。
如果有人愿意贡献修复这些功能的代码，非常欢迎对 `develop` 分支发起 PR。

Currently, all Hoyoverse/HoYoLAB feature support is contributed by the community, and we only provide limited support when some features are not available on the it.
If anyone would like to contribute code that fixes these features, a PR to the `develop` branch is more than welcome.

**Comment by SSB-ARFCN** [comment]
關閉垂直同步後再試一次

**Comment by SSB-ARFCN** [comment]
測試版也遇到了此bug

**Comment by RobinsonLauu** [comment]
> 無法復現bug，更新1.11.2.0後開啟國際服遊戲以NVDIA APP監視幀率解鎖幀率功能與調整視野功能正常 ![圖片](https://private-user-images.githubusercontent.com/78807750/369641147-c3bee66c-45b7-4a4a-8894-211396c843c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTM3NjgsIm5iZiI6MTcyNjk5MzQ2OCwicGF0aCI6Ii83ODgwNzc1MC8zNjk2NDExNDctYzNiZWU2NmMtNDViNy00YTRhLTg4OTQtMjExMzk2Yzg0M2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA4MjQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNTk3YmM5YmE4YjkyMDRkMzQ5NTVmZWVjNzJmOGExODZlNzMzZjI4OWNiZmIyZjljZmY1YWVhZjAxNGJmZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NkifwWc_kzj8IDLNolhixgZQpOdU4AfXpxkRwnU_eJI) 建議備份本機/文件/Hutao下的使用者暫存後解除安裝並重新安裝(因為Hoyoverse網頁登入功能失效)

重新安装过了 没有用T_T 垂直同步也没开 一直锁60fps

**Comment by SSB-ARFCN** [comment]
剛把遊戲充新用官方啟動器安裝 正常了
![螢幕擷取畫面 (17)](https://github.com/user-attachments/assets/e02cfe9f-b623-4fb3-8a23-b6c6882baa4a)

**Comment by RobinsonLauu** [comment]
> 剛把遊戲重新用官方啟動器安裝 正常了 ![螢幕擷取畫面 (17)](https://private-user-images.githubusercontent.com/107019852/369674485-e02cfe9f-b623-4fb3-8a23-b6c6882baa4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTM5NzgsIm5iZiI6MTcyNjk5MzY3OCwicGF0aCI6Ii8xMDcwMTk4NTIvMzY5Njc0NDg1LWUwMmNmZTlmLWI2MjMtNGZiMy04YTIzLWI2YzY4ODJiYWE0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwODI3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTk4MWQzNTBlYmU0MmVkYWI3YWY1MDRiZmViYTIzNWVhYzQzM2FiM2IzYWRkMzhkOGY3YmIyMzAxZmQ1Y2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3QALRKpPpFkFVyli5CkaG44EBin5SQDEErSM3RultQU)

ohh ok, 那我也试一下重装游戏， 感谢

**Comment by bddyzpm** [comment]
希望能把经典模式加回来，至少失败了有提示不会直接启动游戏
现在解锁不稳定，来回开关好几次游戏，到登录页面才知道有没有解锁成功

**Comment by Lightczx** [comment]
经典模式一但失效需要更新客户端，影响开发流程，所以不会考虑回归

**Comment by RobinsonLauu** [comment]
> 经典模式一但失效需要更新客户端，影响开发流程，所以不会考虑回归

我换了台电脑重新试了一下 新版还是不行 国际服只能用之前旧版本的经典模式 国服必须用注入 很烦人T_T

**Comment by SSB-ARFCN** [comment]
國際服可以用這個 我之前遇過胡桃工具箱解鎖失敗時用這個可以
https://github.com/34736384/genshin-fps-unlock

**Comment by RobinsonLauu** [comment]
> 國際服可以用這個 我之前遇過胡桃工具箱解鎖失敗時用這個可以 https://github.com/34736384/genshin-fps-unlock

谢谢你 朋友🥹🥹🥹

**Comment by SSB-ARFCN** [comment]
還有一種方式 下載有經典模式的胡桃工具箱測試版 這樣可以讓經典模式和最新版注入模式兩者同時存在  (可能需要接受測試版的一些小bug)

**Comment by Fullang** [comment]
我是国服最近也开始有一样的问题。具体看在进入天空岛开门动画前还是解锁帧率的，之后就锁60了
![Screenshot 2024-09-28 172127](https://github.com/user-attachments/assets/a5353d5a-b3aa-4efe-979e-baffdf8dfc2b)
![Screenshot 2024-09-28 172131](https://github.com/user-attachments/assets/0454819f-0eab-41d1-bbf4-c50afda2ab2a)
![Screenshot 2024-09-28 172221](https://github.com/user-attachments/assets/8694a2a3-42cd-4b08-b3ed-aabb537fba78)

Windows 版本
22631.4169

Snap Hutao 版本
1.11.2.0

设备 ID
3012ECFFEF3CF0CDD7782D272DC3DA22

**Comment by SSB-ARFCN** [comment]
即使沒有使用解鎖工具 原神啟動動畫 米哈遊啟動動畫 遊戲警告啟動動畫 它們本身沒有鎖FPS
天空島動畫出現後才開始鎖

**Comment by SSB-ARFCN** [comment]
> 5.1更新後幀率解鎖、調整視野與移除迷霧不可用。 [34736384/genshin-fps-unlock#474](https://github.com/34736384/genshin-fps-unlock/issues/474)

5.1更新後這個工具仍然在我的電腦上生效 而胡桃工具箱失效
我把遊戲重裝了 windows也重灌了並升級到19045.4957 還是一樣的情況

**Comment by SSB-ARFCN** [comment]
官方服也是60FPS
https://www.mediafire.com/file/imyy977zyg3d9bx/2024.10.10+-+08.37.36.03.mp4/file

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11266104125
试试看这个

**Comment by SSB-ARFCN** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11266104125 试试看这个

![螢幕擷取畫面 (64)](https://github.com/user-attachments/assets/d528a699-321a-43dc-88ea-d95f5687209e)
失敗 遊戲閃退

**Comment by SSB-ARFCN** [comment]
換了一台windows11的 情況相同
![image](https://github.com/user-attachments/assets/d7bc9d74-f595-4b78-ab50-bac71ce7b299)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11269466065/job/31338130216

**Comment by SSB-ARFCN** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11269466065/job/31338130216

這個版本不會再閃退了 但是60FPS還是鎖著

**Comment by Lightczx** [comment]
fixed in https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.11.4

**Comment by SSB-ARFCN** [comment]
![螢幕擷取畫面 (67)](https://github.com/user-attachments/assets/75b95314-657a-4e48-8865-23b5eb93bdd6)
![螢幕擷取畫面 (68)](https://github.com/user-attachments/assets/8d887866-c274-4f95-8c94-701e2ede65a3)
確實修復了
