### ISSUE TITLE
[Bug]: 导入成就UIAF文件（由YaeAchievement生成的json）闪退，导入不成功

### ISSUE THREAD

**Issue by chemharuka** [DGP-Studio/Snap.Hutao#20]
### Windows 版本

22000.56

### Snap Hutao 版本

1.0.31.0

### 发生了什么？

导入由[YaeAchievement](https://github.com/HolographicHat/YaeAchievement)生成的json文件（导出目标选择的是SnapGenshin），文件如下：
[export-20220828151220-paimon.txt](https://github.com/DGP-Studio/Snap.Hutao/files/9444641/export-20220828151220-paimon.txt)
然后软件发生闪退。
该问题同时向YaeAchievement项目进行了反馈。

**Comment by Lightczx** [comment]
@HolographicHat

**Comment by Lightczx** [comment]
我不认为 `export-20220828151220-paimon.txt` 是UIAF格式的文件，这样必然会导入失败

**Comment by HolographicHat** [comment]
![图片](https://user-images.githubusercontent.com/58809250/187360342-68c8c990-c391-4dcb-a768-393141eadd77.png)
![图片](https://user-images.githubusercontent.com/58809250/187360397-75aab325-3161-4d37-bec2-0adbd9ac9764.png)
(YaeAchievement-Rel2.1.0: ebd3c01cf72e9c6aa98a0c693cb6dca9)

**Comment by chemharuka** [comment]
> 
粘贴板内容已附上 ，开头为：
`{"info":{"export_app":"YaeAchievement","export_timestamp":1661839547010,"export_app_version":"2.1","uiaf_version":"v1.1"},"list":[{"id":80138,"status":3`
[content.txt](https://github.com/DGP-Studio/Snap.Hutao/files/9450120/content.txt)
导入这一段文本仍然闪退

**Comment by chemharuka** [comment]
另外选择1的时候，出现报错：
![image](https://user-images.githubusercontent.com/29047471/187363083-a24182fa-2e19-40ae-9270-5a98e471fabe.png)
但粘贴板仍然复制有数据
