### ISSUE TITLE
[Feat]: 匯出胡桃工具箱已有的hoyolab網頁cookie

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2000]
### 背景与动机

因hoyolab在胡桃工具箱登入失效(cookie或許被老米改了) 使現有已登入的cookie特別珍貴 若能使用匯出功能 保留現有的登入狀態在外接硬碟 在未來重設胡桃工具箱 重灌電腦時 可透過輸入cookie維持登入狀態

### 想要实现或优化的功能

實現cookie匯出功能

**Comment by qhy040404** [comment]
![image](https://github.com/user-attachments/assets/ea4eb638-547d-47d1-a86e-56f85a25e0fa)
?

**Comment by qhy040404** [comment]
白瞎这个2000号了

**Comment by 16ea9f2c1d0b73** [comment]
有木有批量导出和批量导入?
