### ISSUE TITLE
[Bug]: 關閉遊戲安裝器視窗造成胡桃工具箱閃退

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2002]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2(OS組建19045.3803)

### Snap Hutao 版本

1.11.2.0

### 设备 ID

0D9E4C3D8B75970396A895DDD0CD79E4

### 问题分类

游戏启动器

### 发生了什么？

使用胡桃工具箱內建的遊戲安裝器安裝遊戲時 將遊戲安裝器視窗右上角"X"按鈕按下後 整個胡桃工具箱閃退 

https://www.mediafire.com/file/95ou0tk3ze6cn6v/Desktop+2024.09.23+-+18.32.45.03.mp4/file

### 你期望发生的行为？

只關閉遊戲安裝器 保留胡桃工具箱主體

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@qhy040404 你没做禁止关闭？
