### ISSUE TITLE
[Bug]: 首頁出現只有數字的方塊

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2003]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2(OS組建19045.3803)

### Snap Hutao 版本

2024.9.24.8

### 设备 ID

0D9E4C3D8B75970396A895DDD0CD79E4

### 问题分类

用户界面

### 发生了什么？

首頁 即時便籤方塊右方 出現只有數字的方塊  點擊後無回應 
![image](https://github.com/user-attachments/assets/8d927481-4e7f-4165-a43f-b5fc973c41a4)

### 你期望发生的行为？

跳轉至對應分頁

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你知道测试版是干什么的么

**Comment by Mikachu2333** [comment]
@SSB-ARFCN  建议换用正式版，一般情况下不建议普通用户使用测试版……
https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.11.2
