### ISSUE TITLE
国际服 登录报错653366069

### ISSUE THREAD

**Issue by Saigyoji-Chrysostom** [DGP-Studio/Snap.Hutao#2004]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4169

### Snap Hutao 版本

1.11.2.0

### 问题分类

其它

### 发生了什么？

使用个人热点和公用网络登录hoyoverse均发生报错
![Z469P58GZR4{9R@)HYOM0QS](https://github.com/user-attachments/assets/30e8bd5f-e77e-4edb-a536-5f9d77078e45)
按照常见问题说明尝试关闭代理和解除loopback无效
![7UFF_ X`F7X`SU9}D~~AT6O](https://github.com/user-attachments/assets/5f76e7d2-e52d-4f15-9652-57984f7e279f)

也有尝试过该用手动输入，但是ios上使用stream抓包并且在期间登录hoyoverse时并没有发现对应的api-takumi.mihoyo.com域名。如果无法解决前述登陆界面问题希望能够介绍一下stream的操作方法。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#1966
