### ISSUE TITLE
[Bug]: 1.2.0版本安装失败

### ISSUE THREAD

**Issue by Hankerlx** [DGP-Studio/Snap.Hutao#201]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.0

### 发生了什么？

新版本1.2.0安装失败，错误如下：
Found package: C:\Users\Hankerlx\Downloads\Snap.Hutao_1.2.0.0_x64_Test\Snap.Hutao_1.2.0.0_x64_Test\Snap.Hutao_1.2.0.0_x64.msix
                                                                                                                        Installing app...                                                                                                       Found dependency package(s):                                                                                            C:\Users\Hankerlx\Downloads\Snap.Hutao_1.2.0.0_x64_Test\Snap.Hutao_1.2.0.0_x64_Test\Dependencies\x64\Microsoft.WindowsAppRuntime.1.2.msix                                                                                                       Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.

Deployment Add operation with target volume C: on Package
7f0db578-026f-4e0b-a75b-d5d06bb0a74d_1.2.0.0_x64__7jfyf5536hdrr from:  (Snap.Hutao_1.2.0.0_x64.msix)  failed with
error 0x80004005. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.

NOTE: For additional information, look for [ActivityId] f17057cd-f5b4-0007-d344-74f1b4f5d801 in the Event Log or use
the command line Get-AppPackageLog -ActivityID f17057cd-f5b4-0007-d344-74f1b4f5d801

At C:\Users\Hankerlx\Downloads\Snap.Hutao_1.2.0.0_x64_Test\Snap.Hutao_1.2.0.0_x64_Test\Add-AppDevPackage.ps1:487
char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Hanker....2.0.0_x64.msix:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Error: Could not install the app.

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
标题

**Comment by Lightczx** [comment]
直接双击主体msix试试

**Comment by Hankerlx** [comment]
> 直接双击主体msix试试
依然报错：
App installation failed with error message: Deployment Add operation with target volume C: on Package 7f0db578-026f-4e0b-a75b-d5d06bb0a74d_1.2.0.0_x64__7jfyf5536hdrr from:  (Snap.Hutao_1.2.0.0_x64.msix)  failed with error 0x80004005. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80004005)
目前已尝试过.exe安装，主体msix安装和install.ps1 powershell安装，均不成功

**Comment by Lightczx** [comment]
把 Microsoft.WindowsAppRuntime 卸载了

**Comment by Hankerlx** [comment]
> 把 Microsoft.WindowsAppRuntime 卸载了

按照如下操作移除x86和x64（-preview2无法移除），再次进行安装依然报错，错误同上：
(base) PS C:\Users\Hankerlx\Desktop> remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe
remove-appxpackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.
Windows cannot remove framework Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe because
package(s) 7f0db578-026f-4e0b-a75b-d5d06bb0a74d currently depends on the framework. Removing all packages that depend
on the framework automatically removes the framework.
NOTE: For additional information, look for [ActivityId] f17057cd-f5b4-0008-e625-7ef1b4f5d801 in the Event Log or use
the command line Get-AppPackageLog -ActivityID f17057cd-f5b4-0008-e625-7ef1b4f5d801
At line:1 char:1
+ remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2-preview2_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Windo...__8wekyb3d8bbwe:String) [Remove-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand

(base) PS C:\Users\Hankerlx\Desktop>  remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2_2000.677.1750.0_x86__8wekyb3d8bbwe
(base) PS C:\Users\Hankerlx\Desktop> remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2_2000.677.1750.0_x64__8wekyb3d8bbwe
(base) PS C:\Users\Hankerlx\Desktop> get-appxpackage *appruntime*


Name              : Microsoft.WindowsAppRuntime.1.2-preview2
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 2000.638.7.0
PackageFullName   : Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program
                    Files\WindowsApps\Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.WindowsAppRuntime.1.2-preview2_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Developer
Status            : Ok

**Comment by a2445478275** [comment]
> > 把 Microsoft.WindowsAppRuntime 卸载了
> 
> 按照如下操作移除x86和x64（-preview2无法移除），再次进行安装依然报错，错误同上： (base) PS C:\Users\Hankerlx\Desktop> remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe remove-appxpackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation. Windows cannot remove framework Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe because package(s) 7f0db578-026f-4e0b-a75b-d5d06bb0a74d currently depends on the framework. Removing all packages that depend on the framework automatically removes the framework. NOTE: For additional information, look for [ActivityId] f17057cd-f5b4-0008-e625-7ef1b4f5d801 in the Event Log or use the command line Get-AppPackageLog -ActivityID f17057cd-f5b4-0008-e625-7ef1b4f5d801 At line:1 char:1
> 
> * remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2-preview2_ ...
> * ```
>     + CategoryInfo          : WriteError: (Microsoft.Windo...__8wekyb3d8bbwe:String) [Remove-AppxPackage], IOException
>     + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand
>   ```
> 
> (base) PS C:\Users\Hankerlx\Desktop> remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2_2000.677.1750.0_x86__8wekyb3d8bbwe (base) PS C:\Users\Hankerlx\Desktop> remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.2_2000.677.1750.0_x64__8wekyb3d8bbwe (base) PS C:\Users\Hankerlx\Desktop> get-appxpackage _appruntime_
> 
> Name : Microsoft.WindowsAppRuntime.1.2-preview2 Publisher : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US Architecture : X64 ResourceId : Version : 2000.638.7.0 PackageFullName : Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe InstallLocation : C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.2-preview2_2000.638.7.0_x64__8wekyb3d8bbwe IsFramework : True PackageFamilyName : Microsoft.WindowsAppRuntime.1.2-preview2_8wekyb3d8bbwe PublisherId : 8wekyb3d8bbwe IsResourcePackage : False IsBundle : False IsDevelopmentMode : False NonRemovable : False IsPartiallyStaged : False SignatureKind : Developer Status : Ok

旧版本与新版本不兼容，卸载旧版本后安装而不是直接覆盖安装。

**Comment by AdminRoc** [comment]
参考如下信息：
- 此用户卸载了更旧版本Hutao
- 然后通过get-appxpackage *appruntime*找到之前的WindowsAppRuntime 
- 进行remove-appxpackage -Package操作
- 直接安装msix文件
- 安装成功
