### ISSUE TITLE
[Bug]: 养成计划材料统计无响应

### ISSUE THREAD

**Issue by wen20919** [DGP-Studio/Snap.Hutao#2014]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4169

### Snap Hutao 版本

1.11.3.0

### 设备 ID

08B2B868282A00817C58233609512884

### 问题分类

养成计算

### 发生了什么？

就在刚刚第一时间更新1.11.3.0后，打开养成计划→材料清单→材料统计，往下滑，图标变白，随后直接无响应
![屏幕截图 2024-10-03 213210](https://github.com/user-attachments/assets/c2a550a0-55d5-415b-a3a4-3072331e909d)
![屏幕截图 2024-10-03 213220](https://github.com/user-attachments/assets/ee86c6c5-1147-46c4-8a9d-8170a26574aa)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by wen20919** [comment]
> ### 检查清单
> * [x]  我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
> * [x]  我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
> * [x]  我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题
> 
> ### Windows 版本
> 22631.4169
> 
> ### Snap Hutao 版本
> 1.11.3.0
> 
> ### 设备 ID
> 08B2B868282A00817C58233609512884
> 
> ### 问题分类
> 养成计算
> 
> ### 发生了什么？
> 就在刚刚第一时间更新1.11.3.0后，打开养成计划→材料清单→材料统计，往下滑，图标变白，随后直接无响应 ![屏幕截图 2024-10-03 213210](https://private-user-images.githubusercontent.com/154748075/373273608-c2a550a0-55d5-415b-a3a4-3072331e909d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjMwMDEsIm5iZiI6MTcyNzk2MjcwMSwicGF0aCI6Ii8xNTQ3NDgwNzUvMzczMjczNjA4LWMyYTU1MGEwLTU1ZDUtNDE1Yi1hM2E0LTMwNzIzMzFlOTA5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMzM4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWM4MWJjNTQ4N2QyZWY1NTllM2Y3MjRhN2JmNTA3NTFiYjE4ZWMxYmFhZmQwY2IwYjQ3MDY0ZWNlY2IxYzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RerFU0f7EVz9EiDNuPUWPHH7hUUN0LHx5Us0CjBocd8) ![屏幕截图 2024-10-03 213220](https://private-user-images.githubusercontent.com/154748075/373273673-ee86c6c5-1147-46c4-8a9d-8170a26574aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjMwMDEsIm5iZiI6MTcyNzk2MjcwMSwicGF0aCI6Ii8xNTQ3NDgwNzUvMzczMjczNjczLWVlODZjNmM1LTExNDctNDZjNC04YTlkLTgxNzBhMjY1NzRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMzM4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDA0NDFkZjMxNzQzYmUzODcwYWEwZDU3OTk4ZjhjZDI0ZDlkOGIyNDc0MTA0NTY1NzNjZTYzODFiNzEwMDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Vh-bNOQt-I2uJ4wWMo7yHEOBW7x1fUnMKq8khNCfW10)
> 
> ### 你期望发生的行为？
> _No response_
> 
> ### 最后一步
> * [x]  我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Loner-Knowledge** [comment]
个人复现了一下，补充两个可能有用的视频（**并非无响应**）：

https://github.com/user-attachments/assets/047e2850-fb44-45f4-aa52-385e02ffa829

这一个视频里可以看出从材料统计的 **第三页** 开始，每次材料图标都会全白然后重新复原，材料的位置也会有改变，同时会出现页面自动滑动的情况（视频里每次操作我只点了一次，之后发生的滑动都是自动的）

https://github.com/user-attachments/assets/1f8684e0-1192-4ba7-bea0-efbf864cd4b1

这是一个更明显的材料位置改变的例子，也是从 **第三页** 开始，图标全白然后复原，然后明显可以看出凭空多了一个位置，所有材料后移了一位。

**Comment by qhy040404** [comment]
> 多了一个位置

microsoft/microsoft-ui-xaml#9972
