### ISSUE TITLE
[Bug]: 每次更新，都会重置托盘设置

### ISSUE THREAD

**Issue by razonyang** [DGP-Studio/Snap.Hutao#2015]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Win11 22631.4249

### Snap Hutao 版本

1.11.3.0

### 问题分类

安装和环境

### 发生了什么？

每次更新后，托盘图标都会从默认“显示”状态被重置为“隐藏”状态。

![image](https://github.com/user-attachments/assets/3e578a6f-93f6-4676-8184-336c347ffd91)

### 你期望发生的行为？

不重置原本的托盘设置

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
拖一下并不是很碍事
