### ISSUE TITLE
[Bug]: 卸载后未清除任务计划任务

### ISSUE THREAD

**Issue by Deer512** [DGP-Studio/Snap.Hutao#202]
### Windows 版本

19044.2251

### Snap Hutao 版本

1.2.0

### 发生了什么？

![IMG_3653](https://user-images.githubusercontent.com/117994031/201348820-7e95dbe1-e051-48bd-bfa3-2c89d593ae27.JPG)
试图更新新版本，将旧版本卸载后频繁出现此弹窗

### 你期望发生的行为？

不再弹出此弹窗

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Deer512** [comment]
非常感谢，清除计划任务后不会再弹出窗口了。已经可以重新安装新版本了。:D

**Comment by krrr** [comment]
要在计划任务管理里面删除SnapHutaoDailyNoteRefreshTask

**Comment by AdminRoc** [comment]
Please Read [This](https://hut.ao/FAQ/most-frequent-questions.html#%E5%BC%B9%E5%87%BA%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E6%96%B0%E5%BA%94%E7%94%A8%E7%9A%84%E5%AF%B9%E8%AF%9D%E6%A1%86)
