### ISSUE TITLE
[Bug]: 更新「养成计划」时「选定的等级不需要养成材料」，会无法自动将「养成计划」中已达到养成目标的对应清单删除

### ISSUE THREAD

**Issue by Loner-Knowledge** [DGP-Studio/Snap.Hutao#2022]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4894

### Snap Hutao 版本

1.11.3.0

### 问题分类

养成计算

### 发生了什么？

「我的角色」中的「养成计算」功能，若「我的角色」中的当前角色已经达到养成目标，但未更新的「养成计划」中仍保留该角色的材料时，更新时会显示「选定的等级不需要养成材料」，更新后不会将「养成计划」中对应角色的材料清单删除。

复现：
1. 新建一个养成计划，从「数据-角色资料」中将一名角色添加到养成计划，等级天赋随便，只要能加进养成计划就行。
2. 从「我的角色」中更新养成计划，且目标等级不高于现实等级（比如目标81级，现实90级；或者目标90级，现实90级），目标天赋同理不高于现实天赋，保证触发「选定的等级不需要养成材料」。（这一步设置的目标和步骤1的无关，现实等级是指「我的角色」中的等级，目标等级是指更新时设置的目标）
3. 查看「养成计划」，会发现更新后的养成计划里对应角色仍然是步骤1的状态。

### 你期望发生的行为？

对于「选定的等级不需要养成材料」，应该加个判断吧，如果养成计划中有该角色，那么删除该角色的材料清单。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
未能复现。请在添加时选定重复条目的处理方式，如下图所示。
![图片](https://github.com/user-attachments/assets/692b0ed5-ec2b-4f22-acd7-a21c69627592)

**Comment by Mikachu2333** [comment]
> 2\. 从「我的角色」中更新养成计划，且目标等级不高于现实等级

备注，选择“更新全部”才可以复现……

**Comment by Loner-Knowledge** [comment]
> 未能复现。请在添加时选定重复条目的处理方式，如下图所示。 ![图片](https://private-user-images.githubusercontent.com/63829496/373936913-692b0ed5-ec2b-4f22-acd7-a21c69627592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjUwMTksIm5iZiI6MTcyODIyNDcxOSwicGF0aCI6Ii82MzgyOTQ5Ni8zNzM5MzY5MTMtNjkyYjBlZDUtZWMyYi00ZjIyLWFjZDctYTIxYzY5NjI3NTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE0MjUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OWM4NjUxN2NhOWUwYTQ0NTYzNTBiNzlhNDNiMzZlNTEwYTU3ZTU0ODY2ZWRiMWExMWUxYjM2NDU3MmQyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EsBMrRzviCq0HnfsUEPopNwSU5F5Ygigjjer9-0o1S4)

抱歉，我没写清，这里角色天赋等级也需要 **全部** 目标不高于现实，才能触发「选定的等级不需要养成材料」。
这里未能复现的原因是因为「普通攻击-叶阳斗技」是7->10，所以程序仍然会去更新养成计划里的清单。
如果这里是7->7，就会提示「选定的等级不需要养成材料」，然后养成计划里面的清单还会存在。

附上我复现的视频。

https://github.com/user-attachments/assets/184180e6-ac05-46a6-b2f8-2073b8e01141
