### ISSUE TITLE
[Feat]: 在工具箱中加入全域搜尋功能 

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2028]
### 背景与动机

隨著胡桃工具箱的功能越來越豐富 使用者尋找功能所需要花的時間更多 若能使用搜尋功能輸入想要的功能然後直接跳轉到對應的頁面及選項 能夠大幅增加使用效率

### 想要实现或优化的功能

可以參考Windows的設定搜尋功能 協助使用者轉到所求的選項 並在使用者點擊時自動跳轉至對應頁面和對應選項
![螢幕擷取畫面 (55)](https://github.com/user-attachments/assets/3e533f18-71f4-4084-bd6b-9742cd6a5fcd)
![螢幕擷取畫面 (59)](https://github.com/user-attachments/assets/4369203f-2a44-44bf-afa5-d193209e2bc2)
![螢幕擷取畫面 (60)](https://github.com/user-attachments/assets/a79cf975-6e32-4630-ae8b-539e73de1fcf)

我了解在角色和武器資料有搜尋功能 而此次的建議為全域搜尋 而非針對特定頁面

**Comment by SSB-ARFCN** [comment]
示意圖
![未命名](https://github.com/user-attachments/assets/60e7b075-78b1-4adc-aab7-12134e70aaf7)

**Comment by Lightczx** [comment]
``` diff
- 大幅增加使用效率 ×
+ 大幅增加维护成本 √
```

**Comment by BTMuli** [comment]
https://github.com/DGP-Studio/Snap.Hutao.Docs 欢迎给文档站提供Pr以提供及时有效的胡桃工具箱相关功能指南及常见QA

**Comment by Lightczx** [comment]
Currently not doable
