### ISSUE TITLE
实时便签功能失效，显示“账号有风险，请前往米游社查看”

### ISSUE THREAD

**Issue by chennnnnnnnnnhnnn** [DGP-Studio/Snap.Hutao#203]
### Windows 版本

19043.2251

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

实时便签功能失效，显示“账号有风险，请前往米游社查看”

### 相关的崩溃日志

![image](https://user-images.githubusercontent.com/92138386/201356665-5f2c0add-ca6c-4725-99a4-df1c5df75ed7.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
https://hut.ao/FAQ/mihoyo-risk-tip.html
