### ISSUE TITLE
[Bug]: 653366069-请求异常

### ISSUE THREAD

**Issue by 1eukocyte** [DGP-Studio/Snap.Hutao#2031]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4317

### Snap Hutao 版本

1.11.3.0

### 问题分类

我的角色

### 发生了什么？

在开始运行Snap Hutao时收到`653366069 [GetAnnouncementsAsync]问题`，游戏版本OS 5.1。已经跟随[常见问题](https://hut.ao/zh/advanced/exceptions.html#_653366069-%E8%AF%B7%E6%B1%82%E5%BC%82%E5%B8%B8)的步骤解除了Loopback限制（尽管此前从未需要如此做我也并未使用代理）。然而该问题依然存在。

在尝试通过网页登录hoyolab后，点击“我已登陆”时会显示`653366069 [GetMultiTokenByLoginTicket]问题`
![404](https://github.com/user-attachments/assets/6896a9fe-4c19-4d8d-b592-fe0d6f1f5483)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
与已有问题重复，详见 #1966
