### ISSUE TITLE
[Bug]: 5.1 更新后解锁帧率失效

### ISSUE THREAD

**Issue by MemoryDewey** [DGP-Studio/Snap.Hutao#2032]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4169

### Snap Hutao 版本

1.11.3.0

### 问题分类

游戏启动器

### 发生了什么？

5.1 更新以后解锁帧率失效

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
fixed

**Comment by MemoryDewey** [comment]
> fixed

并未解决，请问是需要修改什么配置吗

**Comment by MemoryDewey** [comment]
> 我也是遇到一樣的問題，現在還沒有解決，請問是要更改甚麼設定或重新安裝嗎?望指導，謝謝

目前暂时用另外一个仓库可以解决：https://github.com/34736384/genshin-fps-unlock

**Comment by Lightczx** [comment]
部分人确实是注入不了

**Comment by Lightczx** [comment]
感觉可以和 #1998 合并
