### ISSUE TITLE
[Bug]: 5.1版本原神的解锁帧率、去雾、视野都失效了

### ISSUE THREAD

**Issue by 3364729893** [DGP-Studio/Snap.Hutao#2033]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4780

### Snap Hutao 版本

1.11.3.0

### 设备 ID

64AE772241882444EE64E18B33BEF381

### 问题分类

游戏启动器

### 发生了什么？

帧率上限解锁失效，去雾和视野调整也失效了，没有任何错误通知
![image](https://github.com/user-attachments/assets/14339205-dc81-45c6-8987-4a88ebb5b3d6)
![image](https://github.com/user-attachments/assets/af909ff1-2041-4151-b50b-f04a7278ba78)

### 你期望发生的行为？

恢复对应的功能

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by SSB-ARFCN** [comment]
#1998  #2032

**Comment by Lightczx** [comment]
#1998
