### ISSUE TITLE
[Bug]: 游戏路径不正确，请设置更改游戏路径

### ISSUE THREAD

**Issue by xlxyvergil** [DGP-Studio/Snap.Hutao#204]
### Windows 版本

win11 22000.1098

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

设置游戏路径后，仍然显示游戏路径不正确

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
请确认选择的游戏路径是游戏本体的路径，而不是游戏启动器的路径，类似下图：
![image](https://user-images.githubusercontent.com/96916320/201395287-d667ab8f-e0a0-4d4e-8900-a016854b8be1.png)
