### ISSUE TITLE
[Bug]: 視野調整後角色介面/隊伍配置介面顯示問題

### ISSUE THREAD

**Issue by RJFAC** [DGP-Studio/Snap.Hutao#2041]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22000.3260

### Snap Hutao 版本

1.11.4.0

### 问题分类

游戏启动器

### 发生了什么？

角色介面距離變遠
![圖片](https://github.com/user-attachments/assets/b0472e90-5a9b-4d19-982d-282028155fa6)
隊伍配置畫面拉遠，不能對齊角色
![圖片](https://github.com/user-attachments/assets/8cdca195-f331-49f3-8a5a-bc2ee4835c18)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
Intended change
