### ISSUE TITLE
遇到了无法恢复的致命错误

### ISSUE THREAD

**Issue by JiJiJi-OvO** [DGP-Studio/Snap.Hutao#2042]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3930

### Snap Hutao 版本

1.11.4.0

### 设备 ID

3F50BDECB20587963C0829367EAF263E

### 问题分类

游戏启动器

### 发生了什么？

![QQ20241011-120547](https://github.com/user-attachments/assets/d3f34cfc-57e9-4dd1-ace7-13b0f407a4f9)

### 你期望发生的行为？

不清楚发生了什么，关掉错误报告窗口后重新打开就可以正常使用了。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
0x80070020: ERROR_SHARING_VIOLATION
