### ISSUE TITLE
改了视野，然后切换人的界面就成了这个样子

### ISSUE THREAD

**Issue by Fuchen182** [DGP-Studio/Snap.Hutao#2043]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

1

### Snap Hutao 版本

1.11.4.0

### 设备 ID

C0BD3E60751561C5E8CE6DAB5AD96A53

### 问题分类

游戏启动器

### 发生了什么？

![112](https://github.com/user-attachments/assets/fde25e87-4829-4627-a059-114dfb677f8c)

### 你期望发生的行为？

改了这个问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2041
