### ISSUE TITLE
[Bug]: 无法正常同步背包物品

### ISSUE THREAD

**Issue by wen20919** [DGP-Studio/Snap.Hutao#2044]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4249

### Snap Hutao 版本

1.11.4.0

### 设备 ID

08B2B868282A00817C58233609512884

### 问题分类

养成计算

### 发生了什么？

https://github.com/user-attachments/assets/fc5e86e1-6ee8-4614-9afe-d6c3f120da04

在材料统计界面如果先下滑在点击同步背包物品，会一直显示正在同步

https://github.com/user-attachments/assets/d2935b25-08e3-4d0a-929c-380e57c2051c

同样的，在背包物品界面也会出现异常情况

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
目前想要正常同步需要保持列表在最顶部位置，可以事先滚动，但同步时需要保持顶部位置
