### ISSUE TITLE
[ENG][Bug]: I can access Google, but when logging into my HoYoLab account on Hutao, the verification keeps showing network errors.

### ISSUE THREAD

**Issue by JIFVGWHvAseSovQ** [DGP-Studio/Snap.Hutao#2046]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

26100.2033

### Snap Hutao Version

1.11.4

### Issue Category

MiHoYo Account Panel

### What Happened?

[https://i.postimg.cc/x88dwHp4/Snipaste-2024-10-13-00-00-09.png](url)

### What is expected?

[https://i.postimg.cc/x88dwHp4/Snipaste-2024-10-13-00-00-09.png](url)

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
#1966

**Comment by ComPfort** [comment]
Hello,

i have the same problem when i try to login to my Eu server

![snap hutao -Clipboard-5](https://github.com/user-attachments/assets/5b553564-9768-46e8-8e20-1745c94cc2b9)
![snap hutao -Clipboard-3](https://github.com/user-attachments/assets/bd7ce59c-cb3f-4bbe-8edb-398a8e089392)
