### ISSUE TITLE
[Feat]: 在胡桃里加入一个终端

### ISSUE THREAD

**Issue by misaka10384** [DGP-Studio/Snap.Hutao#2050]
### 背景与动机

无

### 想要实现或优化的功能

希望能在胡桃里加入一个终端  没别的意思

**Comment by Lightczx** [comment]
closing for no motivation

**Comment by Mikachu2333** [comment]
？你的目的是什么？

加入终端图啥？看warning信息？那已经有了啊，听不懂……

**Comment by misaka10384** [comment]
> ？你的目的是什么？
> 
> 加入终端图啥？看warning信息？那已经有了啊，听不懂……

没有  我来整活的  原本的意思是加入一个powershell 然后可以在胡桃里打开（

**Comment by Mikachu2333** [comment]
那close没问题

**Comment by misaka10384** [comment]
> 那close没问题

希尔知道的（
![Clip_2024-10-14_17-05-12](https://github.com/user-attachments/assets/9ec4a14b-3aca-450d-817c-53cce0965cca)
