### ISSUE TITLE
[Bug]: README 本地化翻譯數值異常

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2052]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4957

### Snap Hutao 版本

1.11.4.0

### 设备 ID

0D9E4C3D8B75970396A895DDD0CD79E4

### 问题分类

其它

### 发生了什么？

位於 README 中的"本地化翻译"數值似乎無法正常顯示
目前它看起來像這樣
![image](https://github.com/user-attachments/assets/a4dafdcb-7d6b-4303-bd7a-e9c963695dad)
而 Crowdin 中數值能正常顯示
![image](https://github.com/user-attachments/assets/fb16ecce-0cfb-46aa-878a-1b6abe91212f)
這個Bug持續一段時間了

### 你期望发生的行为？

讓數值能正常顯示

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
See #638 
awesome-crowdin has removed their endpoints

**Comment by qhy040404** [comment]
https://github.com/badges/shields/issues/10594
