### ISSUE TITLE
[ENG][Bug]: 关于解锁帧率后，调整视野问题bug 

### ISSUE THREAD

**Issue by 3364729893** [DGP-Studio/Snap.Hutao#2055]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

19045.4780

### Snap Hutao Version

1.11.4

### Device ID

64AE772241882444EE64E18B33BEF381

### Issue Category

Game Launcher

### What Happened?

解锁了高帧率的视野问题，在这个版本，使用默认的视野45，游戏世界视野没有问题，但是出现了界面UI偏移缩放的问题
![屏幕截图 2024-10-17 054812](https://github.com/user-attachments/assets/791fba84-163a-4032-972a-22dbbb758528)
![无标题](https://github.com/user-attachments/assets/36f5efc8-103c-4636-a7c6-1a57f3e4f068)
这个问题倒也没啥，但是打牌的界面也发生了缩放，导致出现了BetterGI无法识别屏幕牌的位置，自动打牌无法使用
![无标题2](https://github.com/user-attachments/assets/88b72a07-5ac0-4848-9cf9-b168f2c69cca)
经过我的调整，如果视野调整到30，界面UI偏移缩放倒是没有了，但是游戏世界视野放大了
![无标题3](https://github.com/user-attachments/assets/ff20bfbe-fdd3-49c0-a16a-eced59652d7b)
![屏幕截图 2024-10-17 055227](https://github.com/user-attachments/assets/1707e464-3822-47f5-9f27-75ca18dd4f0a)

当然，如果开启了兼容模式，帧率倒是解锁了，但没有去雾功能了，问一下有没有保留去雾功能和默认视野的办法

### What is expected?

解锁高帧率，保留去雾功能和默认视野

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
intended
