### ISSUE TITLE
[Bug]: 在启动游戏中使用【调整相机视野】功能后，游戏内配队界面异常

### ISSUE THREAD

**Issue by dalinKING** [DGP-Studio/Snap.Hutao#2056]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.11.4.0

### 问题分类

其它

### 发生了什么？

在使用调整视野功能的时候，设置相机视野超过30时，游戏内打开队伍配置界面是，动态背景会缩小，信息与人物界面不匹配。
1.游戏内4K全屏
2.调整相机视野：48-100
3.游戏内各国动态配队界面均有异常，表现为人物镜头与信息背景错乱
4.手动调整相机视野到32，恢复复正常

### 你期望发生的行为？

1.希望调整相机视野之后，不影响配队界面。
2.或者在游戏内角色配队界面，不启用镜头调整

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by dalinKING** [comment]
关于游戏启动功能高级功能中，调整相机视野的小问题

**Comment by Lightczx** [comment]
#2055
