### ISSUE TITLE
[Feat]: 米哈游登录增加邮箱登录和扫码登录

### ISSUE THREAD

**Issue by Dreamvstar** [DGP-Studio/Snap.Hutao#2057]
### 背景与动机

国服登录方式太单一了。

### 想要实现或优化的功能

如标题。

**Comment by Masterain98** [comment]
成为氪佬，获取专属客服，向米哈游提议开放 SSO 登录接口

**Comment by Lightczx** [comment]
扫码有可能会回归，其他的登录方式问米哈游为什么BAN了
