### ISSUE TITLE
[Feat]: 开发 归龙潮工具箱 里面也有胡桃配音角色该角色名命名工具箱名称

### ISSUE THREAD

**Issue by qincenhua** [DGP-Studio/Snap.Hutao#2059]
### 背景与动机

胡桃工具箱进行一些改动开发一个新版本 变动工具箱名称 增加剧情识别跳过

### 想要实现或优化的功能

1.增加归龙潮官方信息
2.便签体力任务展示
3.抽卡记录分析
4.剧情自动跳过增加养成攻略
5.归龙潮可转换国际服
6.解锁真率120
7.增加可爱表情包让这个版本更有趣
8.每日一图更新归龙潮同人图
9.增加通行证功能进行云储存
10.搭建 归龙潮工具箱官方网站安装

**Comment by qhy040404** [comment]
钱呢

**Comment by SSB-ARFCN** [comment]
文件網先看看吧？ 有不少功能是已經存在的
