### ISSUE TITLE
[Bug]: 同步的背包物品与实际相比有部分偏差

### ISSUE THREAD

**Issue by Loner-Knowledge** [DGP-Studio/Snap.Hutao#2061]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5011

### Snap Hutao 版本

1.11.4.0

### 问题分类

养成计算

### 发生了什么？

没有进行角色养成，背包材料48小时内没有发生变化，刷新Cookie后从「养成计算」中进行「同步背包物品」。

同步背包物品后与实际背包物品比对，显示的周本材料数量并不能对上实际数量。
![image](https://github.com/user-attachments/assets/46a4763f-db3a-4b74-b93e-00df7347f0f2)
![image](https://github.com/user-attachments/assets/613030e4-a872-4067-9000-fea620cc8221)
如上图，显示的比实际的少，并且出错的周本材料都显示为18。但又不是全部都有问题。
此外，可合成的材料也有这种情况，见上面两图。但是经过计算好像是自动把低级的材料有误差地合成到了高级。（api自带的自动合成？[#1753](https://github.com/DGP-Studio/Snap.Hutao/issues/1753#issue-2363451964)？)

---

下面是另一个账号比较极端的例子。
![image](https://github.com/user-attachments/assets/fef413b5-b9b5-44be-b9c6-4e484edd614b)
![image](https://github.com/user-attachments/assets/e3729d7a-5f6e-443b-80eb-989c41f8580a)
![image](https://github.com/user-attachments/assets/8cb0feb3-e939-4a16-99a3-4c62e14e4719)
上图，BOSS材料也有这种情况，并且出错的BOSS材料显示都为46的倍数。但又不是全部都有问题。此外，角色元素石头也和可合成的材料一样，好像是自动把低级的材料有误差地合成到了高级。并且都是9的倍数和6的倍数？

### 你期望发生的行为？

虽然要求尽可能物品数量准确，但是能修就修，不能修就先放着吧。至少区域特产还是准确的。

另外，如果api自带了自动合成，那[#1753](https://github.com/DGP-Studio/Snap.Hutao/issues/1753#issue-2363451964)就可以关掉了。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2063
