### ISSUE TITLE
[Bug]: 開啟解鎖fps功能之後無法進入遊戲

### ISSUE THREAD

**Issue by yuusukealmal** [DGP-Studio/Snap.Hutao#2062]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4317

### Snap Hutao 版本

1.11.4.0

### 问题分类

其它

### 发生了什么？

如圖，若使解鎖fps並啟動遊戲，會無法進入並顯示下列錯誤，如果修復後並使用官方啟動器進入則正常
(不確定問題是否由解鎖fps引起)
![image](https://github.com/user-attachments/assets/41f06394-9d06-459f-b4ce-0e76196ffbf6)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
兼容模式你是一点也看不见吗
