### ISSUE TITLE
[Bug]: 建议修改解锁帧率源码

### ISSUE THREAD

**Issue by SMFDrummer** [DGP-Studio/Snap.Hutao#2064]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26100.1742

### Snap Hutao 版本

1.11.4.0

### 问题分类

游戏启动器

### 发生了什么？

每次版本更新都需要等胡桃更新才能再次解锁帧率

### 你期望发生的行为？

建议胡桃开发者参考 [genshin-fps-unlock](https://github.com/xiaonian233/genshin-fps-unlock) 源码，自4.8开始此项目始终可用从未失效，希望可以用来替换解锁帧率的代码参考，解决版本更新胡桃解帧就失效的问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
没有必要
