### ISSUE TITLE
圣遗物评分功能

### ISSUE THREAD

**Issue by YangMieMie22** [DGP-Studio/Snap.Hutao#2071]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4169

### Snap Hutao 版本

1.11.4.0

### 问题分类

我的角色

### 发生了什么？

我能在文档中查询到自动计算圣遗物评分功能，但在1.11.4.0版本使用中我的角色界面没有该功能。

### 你期望发生的行为？

我能看到角色圣遗物（双爆）评分

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
数据结构变化，不再支持评分

@Mikachu2333 你改改Docs?
