### ISSUE TITLE
[Bug]: 在使用签到奖励时闪退

### ISSUE THREAD

**Issue by tingol666** [DGP-Studio/Snap.Hutao#2074]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.4169

### Snap Hutao 版本

1.11.50

### 设备 ID

57CF3579A143F2D7757391F0942D1BBF

### 问题分类

每日签到奖励

### 发生了什么？

点击领取签到奖励后，弹出图形验证码，验证完成后直接显示图片中的内容，并且程序退出
![屏幕截图 2024-10-20 215137](https://github.com/user-attachments/assets/dd776e03-79e7-4aea-8f36-ddaf236bd56b)

### 你期望发生的行为？

显示米游社签到页面

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by ke040606** [comment]
也是一样的问题 也有致命性错误 就是在签到的时候需要验证图片时 验证后直接崩溃

**Comment by ke040606** [comment]
![image](https://github.com/user-attachments/assets/0085b47e-83b2-46c9-b9f9-337bf8784c25)
