### ISSUE TITLE
[Bug]: 使用內建更新對話方塊更新後工具列右下角系統托盤處出現兩個圖示

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2079]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5011

### Snap Hutao 版本

1.11.6.0

### 设备 ID

DC9C571C4A45D4C05834582193963D16

### 问题分类

安装和环境

### 发生了什么？

如題
![Image](https://github.com/user-attachments/assets/0fa5918a-0a1d-4cbb-86e8-e389f98f5b5f)
![Image](https://github.com/user-attachments/assets/dcb1f1ac-a1f2-4a98-85d4-4d1a5717ef58)
我將1.11.5.0 更新至最新版本1.11.6.0時出現這個Bug
要讓其中一個消失 需要將鼠標移動到這兩個圖示 其中一個才會消失 

### 你期望发生的行为？

使用更新對話方塊點擊安裝後 先將舊圖示移除 再開始更新
這可以避免出現兩個圖示

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
别用win10

**Comment by SSB-ARFCN** [comment]
win10 也可以在更新後只出現一個的
https://www.mediafire.com/file/2oy2gnh00xtwvk0/2024.10.22+-+06.00.06.01.mp4/file
