### ISSUE TITLE
[Bug]: 胡桃实时便笺体力160之后外环不满

### ISSUE THREAD

**Issue by tangtangebusi** [DGP-Studio/Snap.Hutao#208]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

胡桃实时便笺体力160之后外环不满
![QPCQ57FAR NXCIT`V~VBK7](https://user-images.githubusercontent.com/67052443/201469580-d90a70d8-3e15-40d1-8275-4b3417f788ac.png)

### 你期望发生的行为？

修好

### 相关的崩溃日志

无

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
重启后是否正常

**Comment by tangtangebusi** [comment]
> 重启后是否正常

没哦~

**Comment by Lightczx** [comment]
fixed internally

**Comment by ren-zexuan** [comment]
1.2.2.0版本这个问题还是存在
![Snipaste_2022-11-22_19-19-21](https://user-images.githubusercontent.com/45529702/203302266-e412fa52-f595-48e6-b9f1-91499e837067.png)

**Comment by ren-zexuan** [comment]
此问题1.2.2.0版本依然存在
![Snipaste_2022-11-22_19-19-21](https://user-images.githubusercontent.com/45529702/203302645-961d039f-8ca4-45a9-ad24-83541e53de0e.png)
