### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by LLCasper** [DGP-Studio/Snap.Hutao#2087]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5011

### Snap Hutao 版本

1.11.5.0

### 设备 ID

6AC6B218C1B8F2C137AB15801F5A0F81

### 问题分类

安装和环境

### 发生了什么？

![Image](https://github.com/user-attachments/assets/370ab666-14c0-42ba-8af5-e813f6b56fb0)
更新失败

### 你期望发生的行为？

成功更新刀1.11.6.0版本

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
设置里面换个数据文件夹路径，不要放OneDrive文件夹里面
