### ISSUE TITLE
[Bug]: 使用胡桃启动会触发 31-4302 错误

### ISSUE THREAD

**Issue by Xionghaizi001** [DGP-Studio/Snap.Hutao#2088]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.4894

### Snap Hutao 版本

1.11.6.0

### 设备 ID

DEAE42A08F48A30FA3057A48E7D13697

### 问题分类

游戏启动器

### 发生了什么？

使用胡桃启动 **且开启帧率解锁功能** 后，游戏无法进入，且显示如图所示错误。检查游戏完整性可以通过，其它启动器可正常启动游戏。
![Image](https://github.com/user-attachments/assets/6763b07b-b92f-4552-9e71-bb8d7409103e)

### 你期望发生的行为？

正常启动游戏（并解锁帧率）

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
兼容模式
