### ISSUE TITLE
[Bug]: 同步背包物品后与实际背包物品数量不一致

### ISSUE THREAD

**Issue by d-micA** [DGP-Studio/Snap.Hutao#2089]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5011

### Snap Hutao 版本

1.11.6

### 设备 ID

5EDBC3B274275B495ED29991CE1EAA25

### 问题分类

养成计算

### 发生了什么？

**同步背包物品后与实际背包物品数量不一致**
同步前未使用过物品
大致比对后，数量不一致的物品类型有：①区域特产；②角色突破素材；③天赋突破素材；④怪物掉落素材
40体与60体BOSS素材以及武器突破素材数量**未发现异常**

特产对比
![Image](https://github.com/user-attachments/assets/1481318f-6c81-4ddf-aa34-ee3f4495f9dd)
![Image](https://github.com/user-attachments/assets/13fef640-6ee8-4c12-a30f-9d89f691e796)

掉落素材对比
![Image](https://github.com/user-attachments/assets/019b8532-7b26-4deb-8061-f88e58b36be1)
![Image](https://github.com/user-attachments/assets/6501cbc6-2e62-4091-bee8-b970f86be0e6)

### 你期望发生的行为？

请修复它

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
修不了，米哈游的API不返回完整背包数据了
