### ISSUE TITLE
[Bug]: 祈愿界面UID选择与标题栏重合以及通过stoken获取记录会卡在常驻祈愿无法继续

### ISSUE THREAD

**Issue by Mijiu190** [DGP-Studio/Snap.Hutao#209]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

问题1：
祈愿界面在选择多个UID的时候与标题栏重合，导致只有点uid下面一点点边缘才能选中uid，uid上方点击都无效
问题2：
使用stoken获取祈愿记录的时候前两页祈愿记录正常获取，常驻祈愿获取结束后会卡在常驻祈愿界面无法进行其他祈愿的获取，而且获取界面无法关闭只能关闭主程序
问题3：在切换UID时，存在间歇性崩溃的情况以及在切换uid时无法切换至新uid的数据

### 相关的崩溃日志

问题1：
<img width="327" alt="微信截图_20221112134235" src="https://user-images.githubusercontent.com/42069191/201459298-e03963fc-4539-49d6-a30b-9f05053c3611.png">
问题2：
<img width="786" alt="微信截图_20221112134552" src="https://user-images.githubusercontent.com/42069191/201459353-8fded24e-d1f7-4b49-867c-2c2ab391aa24.png">
[json.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9994738/json.zip)
问题3：
<img width="463" alt="微信截图_20221112134308" src="https://user-images.githubusercontent.com/42069191/201459309-9bbfa9fe-3f26-43c8-854d-2a6d67ab1118.png">
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9994229/Log.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
请勿在单个Issue内包含多个问题
