### ISSUE TITLE
[Bug]: 无法启动直接崩溃

### ISSUE THREAD

**Issue by bWFuanVzYWth** [DGP-Studio/Snap.Hutao#2090]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4317

### Snap Hutao 版本

1.11.6

### 问题分类

安装和环境

### 发生了什么？

[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17500734/Snap.Hutao.Error.Log.txt)

### 你期望发生的行为？

并非首次安装，在此之前正常使用了超过一年时间。在某次更新后发现无法启动。已尝试这些操作但仍然无法解决问题：
1. 直接使用Snap.Hutao.Deployment.exe
2. 手动卸载后再次通过.msix安装

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
检查路径 `C:\Users\linlin\Documents\Hutao`

**Comment by bWFuanVzYWth** [comment]
不存在此文件夹

**Comment by bWFuanVzYWth** [comment]
```
C:\Users\linlin\Documents>ls
 3DMark
 Adobe
 Ansoft
 BaiduSyncdisk
'Blackmagic Design'
 BreeZip
'CD Projekt Red'
 DSP_Star_Sector_Resources_13060425-63.csv
 DSP_Star_Sector_Resources_14525355-64.csv
 DSP_Star_Sector_Resources_38156171-54.csv
'Dyson Sphere Program'
'Intel XTU Profiles'
 KingsoftData
 MATLAB
'My Cheat Tables'
'My Music'
'My Pictures'
'My Videos'
'Paradox Interactive'
'Tencent Files'
 TencentMeeting
'Unreal Projects'
 VTune
'Visual Studio 2022'
'WPA Files'
'WeChat Files'
 WindowsPowerShell
'Wolfram Mathematica'
 den4b
 desktop.ini
''$'\350\207\252\345\256\232\344\271\211'' Office '$'\346\250\241\346\235\277'
```

**Comment by Lightczx** [comment]
你需要创建这个文件夹

**Comment by bWFuanVzYWth** [comment]
仍然崩溃，log已经更新[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17500833/Snap.Hutao.Error.Log.txt)

**Comment by Lightczx** [comment]
你的文档文件夹权限太高了，试一下管理员运行

**Comment by bWFuanVzYWth** [comment]
管理员权限运行结果和上一处相同，还是这个异常`Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.`

**Comment by bWFuanVzYWth** [comment]
```
C:\Users\linlin\Documents\Hutao>icacls .
. NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
  BUILTIN\Administrators:(I)(OI)(CI)(F)
  DESKTOP-LINLIN\linlin:(I)(OI)(CI)(F)
```

**Comment by qhy040404** [comment]
关闭windows defender勒索软件防护中的文件夹限制访问

**Comment by bWFuanVzYWth** [comment]
问题已解决，谢谢
