### ISSUE TITLE
背景服务灾难性故障

### ISSUE THREAD

**Issue by MeAquAlex** [DGP-Studio/Snap.Hutao#2096]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26100.2161

### Snap Hutao 版本

1.11.6

### 设备 ID

D99E32FDF7FAC41A386D2E580054E2E6

### 问题分类

安装和环境

### 发生了什么？

无法启动胡桃工具箱，启动即崩溃
尝试过安装更新，仍然是无法启动
启动报错界面![Image](https://github.com/user-attachments/assets/397c373d-59c0-44f9-bdd5-43e20b0e0154)
诊断工具结果[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17529350/Snap.Hutao.Error.Log.txt)
事件监视器崩溃事件记录[胡桃工具箱崩溃.txt](https://github.com/user-attachments/files/17529439/default.txt)

### 你期望发生的行为？

无法启动胡桃工具箱，启动即崩溃

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@MeAquAlex 今天是否仍无法启动？

**Comment by Lightczx** [comment]
closing for no response
