### ISSUE TITLE
[Feat]: 讓遊戲安裝器右上角X按鈕顯示成灰色的

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2097]
### 背景与动机

現有的X按鈕和一般的X按鈕一樣可以鼠標靠過去會有反應
![Image](https://github.com/user-attachments/assets/6984d81b-3efb-4f25-b88c-e7273cf40176)
![Image](https://github.com/user-attachments/assets/f14f5bf7-3240-4a3c-bd16-5d202ad30645)

如果換成這種按鈕 能更容易了解到它不可用
![Image](https://github.com/user-attachments/assets/7dc0a318-24c5-44a8-be0b-32ad6d1ed452)

### 想要实现或优化的功能

更改按鈕背景顏色和交互方式

**Comment by Lightczx** [comment]
winui不让
