### ISSUE TITLE
安装时遇到问题

### ISSUE THREAD

**Issue by HYu7klyh42** [DGP-Studio/Snap.Hutao#21]
### Windows 版本

22000.918

### Snap Hutao 版本

1.0.31.0

### 发生了什么？

PowerShell运行脚本时如图
![image](https://user-images.githubusercontent.com/58126324/188035203-292bec99-7fe8-407e-ac36-52d679ac861f.png)
随后复制执行如图
![image](https://user-images.githubusercontent.com/58126324/188035300-f29d4bfe-44be-4ef0-a928-6eccf95a4d40.png)
由于本人对PowerShell知之甚少，便没执行其中提到的Add-AppDevPackage.ps1

### 你期望发生的行为？

给出绕过此Windows策略的方式，或提供其他安装方式

**Comment by Lightczx** [comment]
在系统设置中打开开发人员模式
