### ISSUE TITLE
[Bug]: UID选择与标题栏重合，点击无效

### ISSUE THREAD

**Issue by Mijiu190** [DGP-Studio/Snap.Hutao#210]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

祈愿界面在选择多个UID的时候与标题栏重合，导致只有点uid下面一点点边缘才能选中uid，uid上方点击都无效

### 相关的崩溃日志

<img width="327" alt="微信截图_20221112134235" src="https://user-images.githubusercontent.com/42069191/201459298-e03963fc-4539-49d6-a30b-9f05053c3611.png">

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/124
