### ISSUE TITLE
[Bug]: 队伍配置界面角色位置与角色名错位

### ISSUE THREAD

**Issue by shunjiankongbai-cn** [DGP-Studio/Snap.Hutao#2102]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5011

### Snap Hutao 版本

1.11.6.0

### 设备 ID

B2EC01EA6744C80F5D8D59DDB2FA88AB

### 问题分类

其它

### 发生了什么？

队伍配置界面角色位置错位，应该是视角距离过远导致错位了
下面这张图是错位的
![Image](https://github.com/user-attachments/assets/6f1b69d9-04f0-4ca3-8982-54e7580d0d60)

正常情况的位置：
在直接使用米哈游启动器运行游戏的情况下是正常的，就像下面的位置：
![Image](https://github.com/user-attachments/assets/6d851a35-54b8-47a7-8223-659768991555)

经过测试之后，我发现是开启了解锁帧率之后会出现这种状态，但之前的胡桃版本没有出现过。

### 你期望发生的行为？

希望修复该问题

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
《我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的重复的问题》
