### ISSUE TITLE
[Bug]: 祈愿记录获取异常

### ISSUE THREAD

**Issue by Mijiu190** [DGP-Studio/Snap.Hutao#211]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

使用stoken获取祈愿记录的时候前两页祈愿记录正常获取，常驻祈愿获取结束后会卡在常驻祈愿界面无法进行其他祈愿的获取，而且获取界面无法关闭只能关闭主程序

### 相关的崩溃日志

<img width="786" alt="微信截图_20221112134552" src="https://user-images.githubusercontent.com/42069191/201459353-8fded24e-d1f7-4b49-867c-2c2ab391aa24.png">
[json.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9994738/json.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
#200
