### ISSUE TITLE
[Feat]: 原神一条龙联动启动请求https://github.com/tignioj/minimap/issues

### ISSUE THREAD

**Issue by QJKG** [DGP-Studio/Snap.Hutao#2114]
### 背景与动机

https://github.com/tignioj/minimap/issues
这个链接里面的小地图能实现一条龙希望能联动启动和BIG一样

### 想要实现或优化的功能

增加一个选择路径弹窗打开这个应用会跳转一个网站然后网站一键运行所有实
在联合BIG启动就能解放双手了

**Comment by Lightczx** [comment]
联动启动需要对方提供URL启动协议
