### ISSUE TITLE
[Feat]: 联动启动请求https://github.com/tignioj/minimap/issues

### ISSUE THREAD

**Issue by QJKG** [DGP-Studio/Snap.Hutao#2115]
### 背景与动机

https://github.com/tignioj/minimap/issues
增加一个弹窗选择路径打开应用会跳转一个网页一键运行再返回BIG启动解放双手

### 想要实现或优化的功能

https://github.com/tignioj/minimap/issues
小地图联动启动请求由BIG作者提供代码和思路创建的小地图一条龙可再增加

**Comment by qhy040404** [comment]
连续开两个一模一样的是因为你是傻逼吗

**Comment by qhy040404** [comment]
连续开两个一模一样的是因为你是傻逼吗
