### ISSUE TITLE
[Bug]: 祈愿记录切换uid无效

### ISSUE THREAD

**Issue by streesobrs** [DGP-Studio/Snap.Hutao#212]
### Windows 版本

19044.2130

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

账号提示：账号有风险，请前往米游社查看

切换祈愿记录的uid无效
键盘切换也无效

重启胡桃，并去米游社验证码
切换祈愿记录的uid无效
并且有几率祈愿记录没有仍何东西

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
fixed
