### ISSUE TITLE
[Bug]: 国际服1.11.7.0讓我進去(兼容模式)功能失效

### ISSUE THREAD

**Issue by RJFAC** [DGP-Studio/Snap.Hutao#2121]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22000.3260

### Snap Hutao 版本

1.11.7.0

### 设备 ID

4B263104B9BECC724DFC70A8EEA7F25A

### 问题分类

游戏启动器

### 发生了什么？

在開啟視野冷開關的情況下，開啟讓我進去(兼容模式)功能失效，依然報錯31-4302
![Image](https://github.com/user-attachments/assets/b786470b-4aa7-40ce-afbc-4e374d7d05fd)

### 你期望发生的行为？

在1.11.6.0，開啟兼容模式會自動禁用視野迷霧修改

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
请注意，此时视野开关是灰色的，这代表了完全失效，也即，视野功能未开启。
因此，基于视野的其他功能是完全不可用的状态（包括“让我进去”）。

**Comment by Mikachu2333** [comment]
未复现，Win11，ltsc，24h2
![Image](https://github.com/user-attachments/assets/4fe848f6-4870-4953-b1b7-d5f801fec3b8)

**Comment by Lightczx** [comment]
已知问题：注入相关的功能可能无法正常工作。
解决方案：注入功能相关的所有开关拨动至少一次即可
