### ISSUE TITLE
[Bug]: 移除隊伍設定進度條失效

### ISSUE THREAD

**Issue by RJFAC** [DGP-Studio/Snap.Hutao#2123]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22000.3260

### Snap Hutao 版本

1.11.7.0

### 设备 ID

4B263104B9BECC724DFC70A8EEA7F25A

### 问题分类

游戏启动器

### 发生了什么？

設定如圖，幀率修改成功(依nvdia監視FPS解鎖成功)，同時隊伍設定進度條並未移除
![Image](https://github.com/user-attachments/assets/f5ad400a-4136-4e41-befc-8b292f3f1735)
![Image](https://github.com/user-attachments/assets/f22671f3-1486-46ee-8229-2661c2a36df5)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
已知问题：注入相关的功能可能无法正常工作。
解决方案：注入功能相关的所有开关拨动至少一次即可
