### ISSUE TITLE
[Feat]: 在设置中添加自定义网络代理的选项以改善更新下载困难

### ISSUE THREAD

**Issue by RemKeeper** [DGP-Studio/Snap.Hutao#2126]
### 背景与动机

广州联通，Github直接下载和github proxy下载都比较的慢，我是路由器代理用户，因为种种原因不方便配置tun这类全局网卡代理

### 想要实现或优化的功能

需求：设置http网络代理，或添加自建git代理以完成更新的高级设置选项

**Comment by Mikachu2333** [comment]
> 设置http网络代理

或许可以通过系统设置改善，比如搞个pac网络代理，或者其他的什么办法只加速GitHub相关的站点，如使用SteamCommunity302之类的玩意

话说我怎么记得这个proxy可以自动检测的来着（

手动下载也不失为一种办法

**Comment by Lightczx** [comment]
支持系统代理，需要解锁Loopback限制，这个问题问出来就说明根本没看过文档
