### ISSUE TITLE
[Bug]: 偶尔出现使用PowerShell命令管理员模式启动后，解锁帧率仍不可用

### ISSUE THREAD

**Issue by a2445478275** [DGP-Studio/Snap.Hutao#213]
### Windows 版本

22623.870

### Snap Hutao 版本

1.2.0

### 发生了什么？

管理员模式启动后仍无法解锁帧率 需要重新启动软件

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
感谢反馈，是已知情况，目前仍建议出现此种情况后，用管理员模式再次启动
具体原因未知

**Comment by j36k** [comment]
直接用右键管理员启动也有几率无法使用解锁帧率

**Comment by ZYFDroid** [comment]
如何使用powershell管理员模式启动
