### ISSUE TITLE
在开启“调整视野”后在队伍界面会出现画面显示bug

### ISSUE THREAD

**Issue by Kamisato-Ayaka1** [DGP-Studio/Snap.Hutao#2137]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4317

### Snap Hutao 版本

1.11.8.0

### 设备 ID

103BF85DE3C8593BF49D08238850412F

### 问题分类

游戏启动器

### 发生了什么？

[当启用“移除队伍配置条”后，进入游戏打开队伍配置界面，在点击角色更换时候会出现异常的画面过度bug（具体表现为画面在从点击人物后，开始一顿一顿的，直到完全打开换人界面）

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
那你别开
