### ISSUE TITLE
[Bug]: 1.11.9祈願紀錄抓不到

### ISSUE THREAD

**Issue by galeondx** [DGP-Studio/Snap.Hutao#2141]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.11.9

### 问题分类

祈愿记录

### 发生了什么？

更新到1.11.9 祈願紀錄跳出URL失效 看了一下之前別人的回報 說是1.11.8已經修正  已經使用管理員啟動了

![Image](https://github.com/user-attachments/assets/b31cbc04-7f7f-4f3b-9d24-c2037dc25231)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
清除的时候游戏关了吗

**Comment by zbh531** [comment]
1.11.8也有同样的问题

**Comment by zbh531** [comment]
> 清除的时候游戏关了吗

我试过，关了也不行

**Comment by Lightczx** [comment]
@zbh531 国际服么

**Comment by zbh531** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/83040967?s=64&amp;u=6f7d024231cf5b8f8da26443a1a40157a29bdbd0&amp;v=4">@zbh531](https://github.com/zbh531) 国际服么

是的
