### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by hzer4049** [DGP-Studio/Snap.Hutao#2142]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19041.3930

### Snap Hutao 版本

1.11.9.0

### 设备 ID

D60EB64E8427D69BD370A7676B201CE7

### 问题分类

游戏启动器

### 发生了什么？

![Image](https://github.com/user-attachments/assets/98b92e43-4e1c-4e8b-bc03-79fb102fbfce)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
更新系统，你系统差解码器
