### ISSUE TITLE
[Bug]: 运行一段时间后会闪退报错

### ISSUE THREAD

**Issue by 244030119** [DGP-Studio/Snap.Hutao#2144]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

Win11 23H2（OS内部版本22635.4145）

### Snap Hutao 版本

1.11.9.0

### 设备 ID

2A1A32D7FB541860F58D5DBFB5CB88B7

### 问题分类

用户界面

### 发生了什么？

![Image](https://github.com/user-attachments/assets/d3945ee8-2288-40da-868c-e109fc7b04dc)

Snap Hutao 1.11.9.0
Windows 10.0.22635.4145
System Architecture: X64
Process Architecture: X64
Framework: .NET 8.0.8

Exception Data:
[string]:Description:组件初始化失败。

[string]:RestrictedDescription:System.Runtime.InteropServices.COMException
[string]:RestrictedErrorReference:
[string]:RestrictedCapabilitySid:
[WinRT.ObjectReferenceWithContext<WinRT.Interop.IUnknownVftbl>]:__RestrictedErrorObjectReference:WinRT.ObjectReferenceWithContext`1[WinRT.Interop.IUnknownVftbl]
[bool]:__HasRestrictedLanguageErrorObject:False
----------------------------------------
System.Runtime.InteropServices.COMException (0x80004005)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
提供的信息过少
