### ISSUE TITLE
[Feat]: 更新功能优化

### ISSUE THREAD

**Issue by NOWorEVER** [DGP-Studio/Snap.Hutao#2146]
### 背景与动机

能否在这个地方进行客户端更新，点击更新功能后想要登录游戏账号，登录后其实胡桃就可以进行更新了，但是因为关闭了弹窗，所以只能重启启动胡桃进行更新
![Image](https://github.com/user-attachments/assets/149d66ec-f1b1-45a3-9dc4-008d000474bb)

### 想要实现或优化的功能

右上角或者其他地方点击可以重启或者呼出更新功能

**Comment by Lightczx** [comment]
我们不希望用户能够轻松的高频请求更新接口
所以设计为启动后自动检测更新
