### ISSUE TITLE
[Bug]: hutao祈愿记录历史界面卡池对应图片错位

### ISSUE THREAD

**Issue by j36k** [DGP-Studio/Snap.Hutao#215]
### Windows 版本

22623.746

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

如下图所示，2.3深秘之息对应的图片错误显示为优菈，2.3浪涌之瞬对应的图片错误显示为阿贝多
![微信截图_20221113174008](https://user-images.githubusercontent.com/104725216/201515499-c494b217-26d5-471e-8882-e5dfebc4e97b.png)
![微信截图_20221113174016](https://user-images.githubusercontent.com/104725216/201515501-fcbcf59e-38b7-4bd4-b187-d0f403dd850a.png)

### 你期望发生的行为？

修改错误对应的图片

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
@Strelitzia-Khazan

**Comment by Strelitzia-Khazan** [comment]
SH下版本更新时将修复
