### ISSUE TITLE
[Feat]: 建议于文档内添加运行库以解决Snap.Hutao.UnlockerIsland.dll的依赖异常问题

### ISSUE THREAD

**Issue by tony-sung** [DGP-Studio/Snap.Hutao#2151]
### 背景与动机

最近几个版本更新后解锁帧率一直报错:
Unable to load DLL 'C:\Users\soong\Documents\Hutao
\Snap.Hutao.Unlockerlsland.dll' or one of its
dependencies:找不到指定的模块。(0x8007007E)

经过仔细检查后发现是运行库缺失问题, Snap.Hutao.UnlockerIsland.dll同级目录`'C:\Users\<UserName>\Documents\Hutao`下没有运行库, 系统内也没有对应的运行库文件, 使用dependencies工具查找依赖后在同级目录下放入X64版本的运行库依赖得以解决, 以下依赖缺一不可:
```
# 这里的文件是必须的
msvcp140.dll
vcruntime140.dll
vcruntime140_1.dll
```
```
# 这里的文件按需添加
msvcp140_1.dll
msvcp140_2.dll
```

### 想要实现或优化的功能

所以建议开发组将如上运行库集成进资源内, 与Snap.Hutao.Unlockerlsland.dll一同下载

谢谢

**Comment by Lightczx** [comment]
《从来不装vc运行库》

**Comment by qhy040404** [comment]
关我屁事，我没有义务给你集成

**Comment by Mikachu2333** [comment]
> [@Masterain98](https://github.com/Masterain98) [@Mikachu2333](https://github.com/Mikachu2333) 文档里加一行？

111
