### ISSUE TITLE
[Bug]: 遇到了无法恢复的致命错误

### ISSUE THREAD

**Issue by flexlpf** [DGP-Studio/Snap.Hutao#2153]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26100.2314

### Snap Hutao 版本

1.11.9.0

### 设备 ID

C9B743FE2C8DE8B78ED49269688A6F52

### 问题分类

其它

### 发生了什么？

从11.14早上开始，显示国服账号显示网络异常。
![Image](https://github.com/user-attachments/assets/5d2ae05d-17e7-4ea1-8008-86daf25fb4c2)

下午突然程序卡死报错，内容如图。 
![Image](https://github.com/user-attachments/assets/1c237951-5562-47e7-83a0-982c227af98d)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@qhy040404 现在国外访问米游社也404了？

**Comment by flexlpf** [comment]
> [@qhy040404](https://github.com/qhy040404) 现在国外访问米游社也404了？

我用手机试了一下，我用的泰国TrueH的SIM卡，移动数据可以访问米游社。
但是连接到我工作单位的WiFi（某中学的校园网络）之后就不可以访问米游社了。
然后我用手机开热点，使用移动数据，胡桃工具箱是可以正常访问国服账号的。
这个问题以前并没有出现过。

**Comment by Lightczx** [comment]
> 我用手机试了一下，我用的泰国TrueH的SIM卡，移动数据可以访问米游社。
> 但是连接到我工作单位的WiFi（某中学的校园网络）之后就不可以访问米游社了。

这段话原封不动去问米哈游客服

**Comment by flexlpf** [comment]
> > 我用手机试了一下，我用的泰国TrueH的SIM卡，移动数据可以访问米游社。
> > 但是连接到我工作单位的WiFi（某中学的校园网络）之后就不可以访问米游社了。
> 
> 这段话原封不动去问米哈游客服

OK，明白了，mhy服务器的问题

**Comment by Masterain98** [comment]
不能进行的操作：
- 所有帖子
- 所有动态
- 验证码登录

能进行操作的
- 密码登录
- “我的”里面自己发的内容，能点进去
- 实时便笺
