### ISSUE TITLE
最新版本无法打开启动器窗口

### ISSUE THREAD

**Issue by David22737** [DGP-Studio/Snap.Hutao#2159]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.0

### 设备 ID

5AA8A92C14940214B611B8D5665BED63

### 问题分类

游戏启动器

### 发生了什么？

更新至最新版本，在出现命令提示符后几秒内自动闪退
[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17786660/Snap.Hutao.Error.Log.txt)
[_.txt](https://github.com/user-attachments/files/17786674/_.txt)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Kern-bit** [comment]
+1，无法打开

**Comment by JedSunCN** [comment]
已经确认安装了.NET 9.0 Runtime，依旧无法打开
