### ISSUE TITLE
[Feat]: 基于"摹本数"的尘歌壶相关材料计算

### ISSUE THREAD

**Issue by AdminRoc** [DGP-Studio/Snap.Hutao#217]
### 你想要实现或优化的功能？

期望在原有计划中的"养成计算"功能的基础上，增加一个基于"摹本数"的**尘歌壶**相关材料计算
-
参考 
- https://github.com/Le-niao/Yunzai-Bot/pull/868
- https://github.com/Le-niao/Yunzai-Bot/pull/868/commits/f032ec2ca5081ea18120b91cc37dc8d91f3e550b

**Comment by lingkai5wu** [comment]
刚提了个一样的...
可以看看我刚搓出来的，用 Excel
https://github.com/lingkai5wu/getYsFurnitureList

**Comment by Lightczx** [comment]
Tracked by #1394
