### ISSUE TITLE
[Bug]: 无法更新至1.12.1.0版本 0x80073cf9

### ISSUE THREAD

**Issue by hoiyuyiu** [DGP-Studio/Snap.Hutao#2171]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5131

### Snap Hutao 版本

1.11.9.0

### 设备 ID

26F3088D83831A15295F53BD86D4CFA1

### 问题分类

安装和环境

### 发生了什么？

无法更新至 1.12.10 版本，在程序内部更新过程中闪退，没有能自动重启至新版本
- 查看开始菜单，进度条卡住
使用更新工具无法安装/直接安装msix失败，均报错0x80073cf9
（与已关闭issue的问题似乎不太一样）
且计算机中同时存在两个版本，但开始菜单以及系统程序页中仍显示1.11.9.0，且1.11.9.0只能运行管理员模式，两版本都无法在非管理员模式运行

附截图
- 在程序内部更新时闪退，开始菜单进度条卡住
![Image](https://github.com/user-attachments/assets/a02a31d2-9386-4650-9c46-cf973d6a698e)

- 尝试使用更新工具/下载的msix包安装均失败
![Image](https://github.com/user-attachments/assets/5940ea88-40f9-45e3-8b2b-704bfcf1f5c4)
![Image](https://github.com/user-attachments/assets/55177db5-1e71-4cf1-9205-e1c79310c995)

- 查看软件安装目录能发现同时存在两个版本的Hutao
![Image](https://github.com/user-attachments/assets/596dc4a3-c2c1-4d76-87d8-514819435951)

### 你期望发生的行为？

需要协助已完成更新

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by hoiyuyiu** [comment]
闹麻了
刚好系统推送更新，重启更新完之后第一件事先尝试重新安装msix包，成功了，无事发生

**Comment by hoiyuyiu** [comment]
之前试过清除重置商店，重置应用安装器，重启都无法解决，系统更新（强制重启更新那种）之后使用msix包安装成功

**Comment by evanliu3594** [comment]
遇到一模一样的问题，但我系统是最新版的19045.5131，检查更新啥也没有，所以只能等下一个系统更新包？😅

**Comment by hoiyuyiu** [comment]
> 遇到一模一样的问题，应用图标灰掉，用dism删除旧版胡桃也删不掉，强制删除显示0x800073cfa报错 我系统是最新版的19045.5131，检查更新啥也没有，所以只能等下一个系统更新包？😅

我是昨天刚好收到更新，现在是5194了，所以等一等？或者再等下一个胡桃版本，然后直接用msix安装（不知道会不会带来更多问题）？
我的情况好像还不太一样，我的旧版还能用管理员打开正常用，当时只是更新不了，

**Comment by Lightczx** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/4881

**Comment by Mikachu2333** [comment]
@Lightczx 你感觉有必要往文档里面塞吗？

**Comment by Lightczx** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/36357191?s=64&amp;u=2523d079affae859f46ce305ee6358147416f0f1&amp;v=4">@Lightczx](https://github.com/Lightczx) 你感觉有必要往文档里面塞吗？

今晚发版，应该会解决这个，没解决再塞吧
