### ISSUE TITLE
[Bug]: 无法更新至 1.12.10 版本

### ISSUE THREAD

**Issue by hoiyuyiu** [DGP-Studio/Snap.Hutao#2172]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5131

### Snap Hutao 版本

1.12.10

### 设备 ID

26F3088D83831A15295F53BD86D4CFA1

### 问题分类

安装和环境

### 发生了什么？

见#2171 
且被自动关闭后发出了一个alpha版本的下载请求，但下载后由于无证书导致无法安装
![Image](https://github.com/user-attachments/assets/0c761fb3-2500-4cda-bf57-ab0a37bacd3d)

### 你期望发生的行为？

请协助更新至最新版本

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2171
