### ISSUE TITLE
[Bug]: 升级后无法打开

### ISSUE THREAD

**Issue by KuaiCode** [DGP-Studio/Snap.Hutao#2173]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19044.1288

### Snap Hutao 版本

1.12.1

### 问题分类

安装和环境

### 发生了什么？

今天中午也能正常启动，今晚十点左右更新1.12.1后无法启动，普通用户和管理员用户均无法启动，任务栏小图标，任务管理器也没有hutao的进程

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
升级系统

**Comment by KuaiCode** [comment]
![Image](https://github.com/user-attachments/assets/a071c5f5-3881-42fb-9cdd-8280fbcdf953)

**Comment by KuaiCode** [comment]
请问有没有办法在不启动hutao的情况下备份hutao的数据
