### ISSUE TITLE
[Bug]: 主页所有的新活动、祈愿、公告时间识别错误（正则问题）

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#2175]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

2610.2314

### Snap Hutao 版本

1.12.1.0

### 问题分类

用户界面

### 发生了什么？

![Image](https://github.com/user-attachments/assets/e0d2a449-e63e-4509-adee-d99c36062a6f)

### 你期望发生的行为？

正确显示

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by BesTiefufu** [comment]
我的是成就时间显示错误了，呜呜呜
