### ISSUE TITLE
[问题]: 预下载资源对比

### ISSUE THREAD

**Issue by twjmy** [DGP-Studio/Snap.Hutao#2176]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4112

### Snap Hutao 版本

1.11.9.0

### 设备 ID

4B6379FDA25D058C3FA50872BAB7D316

### 问题分类

游戏启动器

### 发生了什么？

![Image](https://github.com/user-attachments/assets/d04fc0f9-efea-44be-b498-bd59f1b32aaf)
发现预下载的文件资源目录与内容不一样
我的游戏是国际服谷歌版
官方启动器是预下载至`chunk`大小为`13.3 GB`且目录下仅包含2个文件夹2个对应文件夹的档案
胡桃则是预下载至`chunks`大小为`12.1 GB`且目录下全是十六位数档案以及胡桃生成的`json`档案

并且，在胡桃进行预下载，视窗分为上下方进度条，下方的进度条并未满100%，但可以点击完成按钮

点击完成后，现在我无法再点击预下载按钮
![Image](https://github.com/user-attachments/assets/1646c4b6-c1a0-434c-a24a-6c9942ad00e6)

因为在文档中搜不到使用说明，所以这里想请问两个问题
1. 资源这样正常吗
2. 后续更新时如何使用胡桃解包

### 你期望发生的行为？

正常解包，启动即玩

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
> 发现预下载的文件资源目录与内容不一样
> 我的游戏是国际服谷歌版
> 官方启动器是预下载至chunk大小为13.3 GB且目录下仅包含2个文件夹2个对应文件夹的档案
> 胡桃则是预下载至chunks大小为12.1 GB且目录下全是十六位数档案以及胡桃生成的json档案

官方启动器预下载完成后将所有差异文件合并为了一个文件并使用数据库管理，胡桃下载的是所有diff。其实内容是相同的。

> 并且，在胡桃进行预下载，视窗分为上下方进度条，下方的进度条并未满100%，但可以点击完成按钮

上方进度条为下载进度条，下放为安装进度条。预下载不涉及安装所以下方进度条是不会变化的。

> 点击完成后，现在我无法再点击预下载按钮

下载完成后信息按钮应该会变成一个√，预下载完成后按钮会变为不可用，这里没有显示√是一个bug，已经规划修复了。

> 资源这样正常吗

资源这样是正常的

> 后续更新时如何使用胡桃解包

版本更新开放后，更新游戏按钮将会变为可用状态。

**Comment by Mikachu2333** [comment]
> 上方进度条为下载进度条，下放为安装进度条。预下载不涉及安装所以下方进度条是不会变化的。

为啥不加个说明呢，类似下图（

![Image](https://github.com/user-attachments/assets/b54c43b9-8645-4193-8148-dffab8fa5b07)
