### ISSUE TITLE
[反馈]:在应用程序卸载后会弹出框

### ISSUE THREAD

**Issue by JiangTon** [DGP-Studio/Snap.Hutao#218]
### Windows 版本

22000.1098

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

如图
![image](https://user-images.githubusercontent.com/61829548/201522425-987543ee-c8a1-41b5-a0f5-7bdc569bd60a.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
#202
