### ISSUE TITLE
[Bug]: 软件窗口较小时，成就切换会缩回去导致切换不了

### ISSUE THREAD

**Issue by streesobrs** [DGP-Studio/Snap.Hutao#2181]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.4510

### Snap Hutao 版本

1.12.1.0

### 问题分类

成就管理

### 发生了什么？

在软件窗口比较小的时候，之前放在外面的成就切换会隐藏到旁边的下拉菜单，导致无法切换
![Image](https://github.com/user-attachments/assets/6fe4fd4a-da70-4497-a08d-e448d56beeac)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
可以使用键盘上下键切换与回车键选择

**Comment by Mikachu2333** [comment]
电脑屏幕过小且缩放过高导致的，我也这样（

**Comment by Lightczx** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/10181
