### ISSUE TITLE
[Bug]: 更新后无法启动-快速异常检测失败

### ISSUE THREAD

**Issue by HelloXiaoHei233** [DGP-Studio/Snap.Hutao#2182]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.2546

### Snap Hutao 版本

1.12.1

### 设备 ID

11AA98B869CBF322F7F618DC8E6AEF41

### 问题分类

游戏启动器

### 发生了什么？

从1.11.9更新到1.12.1后无法启动，但回退到1.11.9可以启动
![Image](https://github.com/user-attachments/assets/4c7dd868-d8c6-419e-8764-c7ad57348279)
我尝试安装了.NET9运行库
执行wsreset指令重置系统商店
以及将胡桃卸载重装，但都无济于事
-----
Generated by Snap Hutao Diagnosis Tool
--------------------------------------
Windows version: 10.0.19045.2546
Public IP: 114.139.112.45
Your machine id: 11AA98B869CBF322F7F618DC8E6AEF41
-----

### 你期望发生的行为？

程序正常启动

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
更新系统
