### ISSUE TITLE
成就显示时间出错：全部成就显示当前时间或最后登录时间

### ISSUE THREAD

**Issue by BesTiefufu** [DGP-Studio/Snap.Hutao#2189]
### Checklist

- [x] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [x] I and tried **search feature** in Snap Hutao document site, and no associated article
- [x] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

22631.4460

### Snap Hutao Version

1.12.1.0

### Issue Category

Achievement

### What Happened?

![Image](https://github.com/user-attachments/assets/a66467d3-5595-4366-8ca1-e8d3e2c3f596)

### What is expected?

希望显示为正确的完成时间

### Last Step

- [x] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by BesTiefufu** [comment]
又细化了一下bug描述，希望得到大佬回复qwq

**Comment by Lightczx** [comment]
#2184
