### ISSUE TITLE
[Bug]: 祈愿记录页面错误

### ISSUE THREAD

**Issue by ren-zexuan** [DGP-Studio/Snap.Hutao#219]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

![Snipaste_2022-11-13_20-58-35](https://user-images.githubusercontent.com/45529702/201522885-19756d05-38dc-4561-9dfa-863b109c311b.png)
在“祈愿记录”和“活动公告”页面来回快速切换有极大概率复现。

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by 13viTA** [comment]
我这边也有相同的问题。我这边是2个账号之间切换就会直接复现这种情况。

**Comment by Lightczx** [comment]
fixed 1.2.2
