### ISSUE TITLE
[Bug]: WIN11系统下，安装完成后无法打开软件

### ISSUE THREAD

**Issue by Zcompzhe** [DGP-Studio/Snap.Hutao#22]
### Windows 版本

22000.856

### Snap Hutao 版本

1.0.31.0

### 发生了什么？

打不开软件。。

### 你期望发生的行为？

双击无反应

**Comment by Lightczx** [comment]
请提供更详细的详细

**Comment by Zcompzhe** [comment]
下载新版本，并安装之后，双击无任何反应。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] [Bug]: 取一个合适的标题 (Issue #22)





 
请提供更详细的信息

**Comment by Lightczx** [comment]
如果之前安装过较低版本的Hutao
需要先删除 %HOMEPATH%/Documents/Hutao/ 下的 *.db 文件

**Comment by fuchen828** [comment]
有相同问题，已解决

**Comment by Zcompzhe** [comment]
> 如果之前安装过较低版本的Hutao 需要先删除 `%HOMEPATH%/Documents/Hutao/` 下的 *.db 文件

已解决，感谢。
