### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by zhoyk** [DGP-Studio/Snap.Hutao#220]
### Windows 版本

win10（19042.2251）

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

一直提示账号风险，按照文档的方法试了还是会

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
Are you OK？
![image](https://user-images.githubusercontent.com/96916320/201533066-5fd573e5-b087-44a5-a2ef-e3d1fc4b89a9.png)

https://hut.ao/FAQ/mihoyo-risk-tip.html

**Comment by AdminRoc** [comment]
修改密码，重试
