### ISSUE TITLE
在祈愿记录的历史中重现抽卡过程

### ISSUE THREAD

**Issue by zfgy-ma** [DGP-Studio/Snap.Hutao#221]
### 你想要实现或优化的功能？

既然能获取到祈愿记录与具体内容 能不能按时间顺序把每个十连重现回来 然后生成出10连图片（时间相同或者相差几秒的算为十连 为一组生成一行 单抽可以将间隙扩大或者独列一行） 按时间先后顺序向下排布 放在祈愿记录的各卡池的历史中
～(￣▽￣～)~

**Comment by Lightczx** [comment]
不符合设计预期
