### ISSUE TITLE
[Bug]: 打开程序时多次提示如图错误，但能正常使用

### ISSUE THREAD

**Issue by ndyd17** [DGP-Studio/Snap.Hutao#2214]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4317

### Snap Hutao 版本

1.12.3.0

### 设备 ID

10F46E339A6DE240BAAAE9D1BFCAC893

### 问题分类

游戏启动器

### 发生了什么？

![Image](https://github.com/user-attachments/assets/2fa38045-d320-462b-9a76-72411c618cbf)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
把你的Userdata.db发一下

**Comment by qhy040404** [comment]
close due to no response
