### ISSUE TITLE
[Bug]: 无法卸载且无法安装

### ISSUE THREAD

**Issue by ze-sweet** [DGP-Studio/Snap.Hutao#2216]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5131

### Snap Hutao 版本

1.12.3

### 设备 ID

D0B09FAA18820443361CEA1B293FB0D3

### 问题分类

安装和环境

### 发生了什么？

更新1.12.3版本时应用自动关闭后打开依旧是旧版本，使用Snap.Hutao.1.12.3.msix文件更新提示“应用安装失败，错误消息: 无法安装。请联系你的软件供应商。 (0x80073cf9)”![Image](https://github.com/user-attachments/assets/ce18bba8-316d-49b6-bae5-73632ff8267c)。
尝试卸载显示无法卸载，错误代码为0x80073cfa，![Image](https://github.com/user-attachments/assets/8a64d07e-30ec-49a6-a96c-a552dbcc60dd)
，设置-高级选项内“应用“”数据”变为0字节![Image](https://github.com/user-attachments/assets/afe9b7c4-3025-453b-8d4c-80ae0328b2e9)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2480939942

**Comment by ze-sweet** [comment]
应用无法运行

**Comment by Lightczx** [comment]
无法安装/卸载 胡桃的 或者 启动后发生快速检测失败（FailFast）的

可以使用
https://learn.microsoft.com/zh-cn/windows/apps/windows-app-sdk/downloads
中的最新稳定安装程序多次尝试安装直到成功（第一次通常会失败）

参考 
https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2489961411
------------
也可以参考 https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2480939942 中的做法重置组件
看不懂英文的请完整重装系统（重置系统是无效的）

操作完成后重新安装胡桃即可

**Comment by ze-sweet** [comment]
反复安装WinAppSDK 1.6.3那个方法灵了
