### ISSUE TITLE
[Bug]: 安装Exception(0x80073CF9)

### ISSUE THREAD

**Issue by Lamper0uge** [DGP-Studio/Snap.Hutao#2218]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2

### Snap Hutao 版本

1.12.3

### 设备 ID

F3E794CC-3AC7-4494-A3CB-8959594EA8A5

### 问题分类

安装和环境

### 发生了什么？

安装部署失败[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17842246/Snap.Hutao.Error.Log.txt)
![Image](https://github.com/user-attachments/assets/c82581e0-e7b8-44d2-a91b-e3bbd6abfc82)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2217

**Comment by Lightczx** [comment]
![Image](https://github.com/user-attachments/assets/ed20e5c8-83b0-4fe8-be27-93c28d2fbdf8)
挺搞笑的，估计没看直接勾的吧

**Comment by Lamper0uge** [comment]
感谢已解决
