### ISSUE TITLE
[Bug]: 跨版本升级后无法打开，已尝试重启和重装

### ISSUE THREAD

**Issue by TsingReiv** [DGP-Studio/Snap.Hutao#2219]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.2604

### Snap Hutao 版本

1.12.3

### 设备 ID

73BF86FAC8EAA5D8A096049ABF41DA68

### 问题分类

安装和环境

### 发生了什么？

2024/11/20 从某1.11版本更新到1.12.3后无法打开（管理员模式），只能在任务管理器看到进程出现一秒，界面没有启动，尝试了重装和重启方法没有解决，在 C:\Users\TsingReiv\AppData\Local\CrashDumps 中发现产生了一批 dmp 格式报错文件

### 你期望发生的行为？

通过网盘分享的文件：SnapHutao 1.12.3 启动报错文件链接: [https://pan.baidu.com/s/18BQjNl_dDuth50Q6GPoCOA?pwd=sn5z](url) 提取码: sn5z
不知道这些对解决问题是否会有帮助

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by xietravel** [comment]
请更新系统至19045.5131
