### ISSUE TITLE
[Bug]: “启动游戏”功能的中的“启动参数”的配置参数会在重启胡桃工具箱后重置

### ISSUE THREAD

**Issue by caotao7ds** [DGP-Studio/Snap.Hutao#2221]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4391

### Snap Hutao 版本

1.12.3.0

### 设备 ID

F9EB5E6980A5DE4D8EE84338B19E602A

### 问题分类

游戏启动器

### 发生了什么？

我在“启动游戏”工具中，配置了两项“启动参数”：`-screen-witdh `=2560 和 `-screen-height`=1380。
更新1.12.3.0版本后，在每次启动胡桃工具箱时，这两项参数都会重置为的3440、1440。

### 你期望发生的行为？

像过往的版本，保留我自己的配置参数。

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
#2229
