### ISSUE TITLE
[Bug]: 每次启动都要修改分辨率

### ISSUE THREAD

**Issue by Ochuel** [DGP-Studio/Snap.Hutao#2222]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.4317

### Snap Hutao 版本

1.12.3.0

### 设备 ID

0489CB4EBE7DF0DBB25C8B406AF3DA5E

### 问题分类

游戏启动器

### 发生了什么？

每次启动app都要修改分辨率，不管之前分辨率修改的开关是开还是关

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by lhhappy0** [comment]
我也遇到了，每次启动会被重置成显示器的默认分辨率1.12.3.0

**Comment by qhy040404** [comment]
#2229
