### ISSUE TITLE
更新1.12.3.0后无法正常使用

### ISSUE THREAD

**Issue by Rainy-An** [DGP-Studio/Snap.Hutao#2226]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26100.2314

### Snap Hutao 版本

1.12.3.0

### 设备 ID

540DEB675438D9DF3999F3BB09B8B6B6

### 问题分类

游戏启动器

### 发生了什么？

更新了最新版本后无法使用 一直提示“无法读取游戏配置文件，可能文件不存在或权限不足” 但游戏配置文件存在 胡桃也是用的管理员模式 重新设置游戏路径后问题依旧 无法启动游戏 起源记录等无法显示 米游社无法登陆

### 你期望发生的行为？

解决问题 正常使用

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Rainy-An** [comment]
那为什么会如此 更新之前一切正常

**Comment by Rainy-An** [comment]
能否提供旧版本

**Comment by misaka10384** [comment]
> 能否提供旧版本

群里找到问题了  原因是 win11的系统版本使用的win10的任务栏 
然后胡桃看到系统是win11尝试使用win11对应的逻辑 但因为任务栏是win10  胡桃找不到 炸了
