### ISSUE TITLE
[Bug]: 祈愿记录重复刷新后增加了重复的已抽出角色

### ISSUE THREAD

**Issue by Cjsah** [DGP-Studio/Snap.Hutao#2227]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.3.0

### 问题分类

祈愿记录

### 发生了什么？

在第一天已经通过SToken刷新过祈愿记录的情况下, 第二天再次点击又刷新了一遍
现在祈愿列表中显示我抽出了两个相同的角色, 时间是一样的

![Image](https://github.com/user-attachments/assets/07cd5a9b-07b3-4959-a5a5-f1c3fcb5abe5)
![Image](https://github.com/user-attachments/assets/2442bab2-48d1-4d7a-b505-59b5ede64c79)

### 你期望发生的行为？

不应该显示出80抽的那个角色

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
发你的UIGF文件

**Comment by Cjsah** [comment]
> 发你的UIGF文件

[Snap Hutao UIGF.json](https://github.com/user-attachments/files/17879232/Snap.Hutao.UIGF.json)

**Comment by qhy040404** [comment]
用全量刷新刷一遍

**Comment by Cjsah** [comment]
好了, 感谢
