### ISSUE TITLE
[Bug]: 无法保存实时便笺的通知设置

### ISSUE THREAD

**Issue by littlesunxyz** [DGP-Studio/Snap.Hutao#223]
### Windows 版本

19044.1889

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

无法保存实时便笺的通知设置
切换左侧页签再切换回来，亦或者关闭“胡桃”重新打开之后，设置就变回“8树脂”
重启计算机也无效，甚至卸载再重新安装“胡桃”之后发现所有我设置的东西完全没变，但这个还是改不了
![屏幕截图 2022-11-14 221609](https://user-images.githubusercontent.com/108925685/201683110-62df3f22-5eb6-46a0-aae4-1468dd6e99a0.png)
![屏幕截图 2022-11-14 221635](https://user-images.githubusercontent.com/108925685/201683130-a3ba4688-a3e1-4e7b-9570-7840aac01cef.png)

### 你期望发生的行为？

希望可以解决我这个问题，不知道是不是个例

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by littlesunxyz** [comment]
好像是8分钟，打错字了

**Comment by Lightczx** [comment]
已知问题

**Comment by littlesunxyz** [comment]
> 已知问题

噢噢！那是不是应该删掉这个issue

**Comment by Lightczx** [comment]
fixed 1.2.2

**Comment by littlesunxyz** [comment]
> fixed 1.2.2

还是保存不了下面这个，这个防止自动收入操作中心的提醒通知啊
![屏幕截图 2022-11-19 205938](https://user-images.githubusercontent.com/108925685/202852386-92e91291-3ec0-4614-b052-4f36db16fd6a.png)

**Comment by Lightczx** [comment]
下版本修复
