### ISSUE TITLE
[Bug]: 养成计划同步背包物品失败

### ISSUE THREAD

**Issue by buhuishaujidexiaobai** [DGP-Studio/Snap.Hutao#2232]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4249

### Snap Hutao 版本

1.12.3.0

### 设备 ID

F15F6BD80BDBB312E74A494EA63A5419

### 问题分类

养成计算

### 发生了什么？

同步背包物品失败，显示武器不存在。![Image](https://github.com/user-attachments/assets/fbde1fd1-5c04-4999-beaf-aeaff256914d)
![Image](https://github.com/user-attachments/assets/4fd723f5-b07a-49cf-b098-841cf952fc30)

### 你期望发生的行为？

修复该功能使其正常运作。

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
Duplicate of #2212
