### ISSUE TITLE
[Bug]: 无法打开应用，无法卸载，无法覆盖安装

### ISSUE THREAD

**Issue by LCYBFF** [DGP-Studio/Snap.Hutao#2233]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5131

### Snap Hutao 版本

1.11.9

### 问题分类

其它

### 发生了什么？

更新版本，已经重启应用，但是一直显示1.11.9，反复更新几次后出现以下问题

无法打开应用

![Image](https://github.com/user-attachments/assets/26b7b10a-7bf6-4dda-8201-24b7c820e339)

无法卸载

![Image](https://github.com/user-attachments/assets/7f15b715-5c40-4f2f-96a4-06c9ce94645d)

![Image](https://github.com/user-attachments/assets/f57ad6f6-872b-44fa-ba8d-b6840d6d69a8)

无法覆盖安装

![Image](https://github.com/user-attachments/assets/4113f33b-1129-4d40-8d3c-fbe45a83214b)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by LCYBFF** [comment]
就是旧版升级才出现的问题

**Comment by qhy040404** [comment]
#2217
