### ISSUE TITLE
没卸载干净，导致安装不了新的

### ISSUE THREAD

**Issue by qi0970** [DGP-Studio/Snap.Hutao#2234]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5131

### Snap Hutao 版本

1.12.3.0

### 设备 ID

526CB31BD1BC252D056D50EC58F25E6A

### 问题分类

安装和环境

### 发生了什么？

因为更新版本就卡住不动，然后我就用系统带的卸载，可是卸不了，我就用火绒把文件夹删了，如何还把60568DGPStudio.SnapHutao_wbnnev551gwxy文件夹也删了，但是还是安装不了新的，
回馈信息：应用安装失败，错误消息: 无法安装。请联系你的软件供应商。 (0x80073cf9)
[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17896178/Snap.Hutao.Error.Log.txt)

### 你期望发生的行为？

我希望可以正常安装好，并且更新也可以正常更新，不会卡住不动

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2217

**Comment by Lightczx** [comment]
![Image](https://github.com/user-attachments/assets/90b6ad39-abdf-4227-91ce-cd1dc8220f68)
《已搜索过》

**Comment by qi0970** [comment]
不好意思，我没有在问题里搜索关键词
