### ISSUE TITLE
请求添加游戏启动后自动开门功能

### ISSUE THREAD

**Issue by ShaWuSagiri** [DGP-Studio/Snap.Hutao#2245]
### 背景与动机

BetterGl·更好的原神中有【自动进入游戏原神启动后自动进入游戏（自动开门）】功能，但没有胡桃中其他启动功能所以希望胡桃也能添加此功能

### 想要实现或优化的功能

添加游戏启动后**自动开门**与**自动点击获取月卡**功能

**Comment by Lightczx** [comment]
#2243
