### ISSUE TITLE
[Bug]: 需要多次启动游戏才能正常运行游戏

### ISSUE THREAD

**Issue by cssjc** [DGP-Studio/Snap.Hutao#2247]
### Windows 版本

10.0.22631.4460

### Snap Hutao 版本

1.12.4.0

### 设备 ID

C4CED553CB9D1EB2D6AB9D9F55724D4A

### 问题分类

游戏启动器

### 发生了什么？

最近点击启动游戏无法打开原神，出现mihoyo界面后就闪退了，需要两三次才能启动游戏

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
是否启用了注入

**Comment by Lightczx** [comment]
closing for no response
