### ISSUE TITLE
[Bug]: 恰斯卡卡池重复记录抽卡记录

### ISSUE THREAD

**Issue by xiurenfuwo** [DGP-Studio/Snap.Hutao#2248]
### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.4.0

### 设备 ID

23C62C5CB677D6492B19A1BC16876FF7

### 问题分类

祈愿记录

### 发生了什么？

恰斯卡卡池开放日抽了60抽并更新抽卡记录，此时正常，此后并未再抽限定池。今日再次更新抽卡记录，在该卡池的记录被重复记录。
![Image](https://github.com/user-attachments/assets/77a7ee53-79bd-41a0-a892-e65b802b1108)

[Snap Hutao UIGF.json](https://github.com/user-attachments/files/17928160/Snap.Hutao.UIGF.json)
如第一抽id为1732076400007153726，它和id1732075560007153726就是同一抽

### 你期望发生的行为？

正确记录抽卡记录

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
勾选全量刷新后，刷新一次
