### ISSUE TITLE
胡桃工具箱退出后自动重启并弹出占用其他应用的鼠标&卸载胡桃工具箱之后自动跳出“hutao”找不到打开此链接的应用并弹出选取应用窗口

### ISSUE THREAD

**Issue by lemon918** [DGP-Studio/Snap.Hutao#2249]
### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.4.0

### 设备 ID

E82E493132741A14D4B539287570D8FE

### 问题分类

游戏启动器

### 发生了什么？

我更新了胡桃工具箱之后就会开始弹窗 关闭退出之后也会弹窗 另一台电脑卸载了胡桃工具箱之后就一直弹出“hutao”找不到打开此链接的应用并弹出选取应用窗口.

### 你期望发生的行为？

希望解决可以解除这个弹窗行为。

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
发图

**Comment by lemon918** [comment]
![image](https://github.com/user-attachments/assets/d93dd3ff-fb76-4500-9f7c-b8e32f257c87)

**Comment by lemon918** [comment]
> 发图

**Comment by Lightczx** [comment]
你之前 **安装过较老的版本** 且 **没有安装过中间的过渡版本** 且 **没有参照旧版本的卸载指南卸载旧版胡桃**

**Comment by lemon918** [comment]
> 你之前 **安装过较老的版本** 且 **没有安装过中间的过渡版本** 且 **没有参照旧版本的卸载指南卸载旧版胡桃**

这个问题能解决吗，然后我台式就是点了里面的更新之后，每次都会弹窗关闭应用后自启动

**Comment by Lightczx** [comment]
使用管理员权限运行 cmd 并执行 `schtasks /delete /tn SnapHutaoDailyNoteRefreshTask`
