### ISSUE TITLE
实时便笺的优化

### ISSUE THREAD

**Issue by MTDY0419** [DGP-Studio/Snap.Hutao#225]
### 你想要实现或优化的功能？

频繁访问或者IP问题会导致异常(应该)，只能去米*社检查。那么更改为核对数据怎么样？
从米游社获取数据后覆盖当前数据，然后根据当前时间戳进行计算剩余时间，这样就算账号异常也可以看到大概的树脂恢复时间。
然后可以手动添加数据，同步的话第一次自动，然后默认过多久同步，可以手动更改同步时间这样的

**Comment by ZYFDroid** [comment]
或许可以做一个不依赖米游社的树脂提醒工具，手动设置初始值，手动记录消耗之类的
