### ISSUE TITLE
[Bug]: 导入UIGF无法自动刷新祈愿记录

### ISSUE THREAD

**Issue by qian1ing** [DGP-Studio/Snap.Hutao#2250]
### Windows 版本

19045.2965

### Snap Hutao 版本

1.12.4.0

### 问题分类

祈愿记录

### 发生了什么？

如果先在祈愿记录里刷新获取祈愿记录，在导入UIGF文件时（和前面刷新获取祈愿记录的UID一样），祈愿记录不会刷新，需要先删除刷新获取祈愿记录的档案再导入才能刷新

### 你期望发生的行为？

希望导入UIGF文件时，能直接刷新祈愿记录里相同ID的记录

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
参见[祈愿记录导入原理](https://hut.ao/zh/features/wish-export.html#%E5%AF%BC%E5%85%A5-uigf-%E7%A5%88%E6%84%BF%E6%95%B0%E6%8D%AE)
> 在导入时，胡桃仅允许“补全”而不允许“通过备份文件更新至最新”。如果你的抽卡记录包含最新数据，请先同步一次抽卡数据再导入。

![https://hut.ao/images/202404/wish_import_zh-cn.webp](https://hut.ao/images/202404/wish_import_zh-cn.webp)

**Comment by qian1ing** [comment]
好的，感谢你的回答
