### ISSUE TITLE
[Bug]: 打开注入功能后无法正常启动游戏

### ISSUE THREAD

**Issue by happy233333** [DGP-Studio/Snap.Hutao#2251]
### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.4

### 设备 ID

42B481CC8D1A5EFE024CBFC737A3CFEA

### 问题分类

游戏启动器

### 发生了什么？

打开注入功能后无法正常启动游戏，会弹出404报错![Image](https://github.com/user-attachments/assets/13fb3987-701d-4722-801a-63c70647a6d7)

### 你期望发生的行为？

希望可以在打开注入功能后正常启动游戏

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你这是私服吧

**Comment by qhy040404** [comment]
官方版本不会出现获取不到版本号的问题

**Comment by qhy040404** [comment]
截图游戏目录和游戏目录下 `(GenshinImpact_Data|YuanShen_Data)\Persistent` 目录的内容

**Comment by qhy040404** [comment]
确实有点小问题
你可以把游戏目录下的 `config.ini` 和胡桃数据文件夹中 `ServerCache` 下的 `config.ini`删掉后重启胡桃，胡桃会给你修复的
