### ISSUE TITLE
[Bug]: 无法获取祈愿记录

### ISSUE THREAD

**Issue by DSakura207** [DGP-Studio/Snap.Hutao#2252]
### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.4.0

### 设备 ID

24F119BD7E75450A1122D23B4DC927FC

### 问题分类

祈愿记录

### 发生了什么？

服务器：国际服（北美）
无法使用网页缓存刷新或者手动输入URL获取祈愿记录。
在数个版本前，手动输入URL所需的数据可以使用[这个脚本](https://gist.github.com/MadeBaruna/1d75c1d37d19eca71591ec8a31178235)获取。
现在这个脚本获取到的URL仍旧在Paimon.moe和Starward 0.13.4中可用，但胡桃提示`祈愿记录URL已失效，请重新获取`。
当时网页缓存刷新依然可用。现在网页缓存刷新也提示一样的错误。

### 你期望发生的行为？

能够通过URL获取到祈愿数据

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
无法复现，将你的抽卡记录url发送至 qhy040404@gmail.com

**Comment by DSakura207** [comment]
@qhy040404 已发送

**Comment by qhy040404** [comment]
在你的链接后面补充 `hk4e_global` 可以临时修复这个问题，下版本修复
