### ISSUE TITLE
[Bug]: 管理员模式运行胡桃，在托盘处启动游戏不显示账号选择框而是打开软件启动游戏界面

### ISSUE THREAD

**Issue by zh8416** [DGP-Studio/Snap.Hutao#2254]
### Windows 版本

版本24H2 OS内部版本26100.2454

### Snap Hutao 版本

1.12.4.0

### 设备 ID

9F837EB166C1FBC9BA5E8FE56EA69851

### 问题分类

游戏启动器

### 发生了什么？

在1.11.9版本及之前可以通过右键点击托盘图标启动账号选择弹框，但是自从1.12.0.版本开始，右键点击托盘图标只能打开主界面，.net版本为9.0。![Image](https://github.com/user-attachments/assets/c72308a7-3e0c-4f21-b08f-104c5fad3f74)

### 你期望发生的行为？

想知道是更新版本后取消了此特性，还是由于我胡桃设置有误导致失效。

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
取消了

**Comment by zh8416** [comment]
> 取消了

好的，了解
