### ISSUE TITLE
[Bug]: 实时便签魔神任务统计出错

### ISSUE THREAD

**Issue by cx-xingchuan** [DGP-Studio/Snap.Hutao#2255]
### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.4.0

### 问题分类

实时便笺

### 发生了什么？

实时便签统计魔神任务没有加上5.2的新任务，我的没有做，但是统计显示全部完成，如图所示
![Image](https://github.com/user-attachments/assets/9d8d4b21-3e5d-4ed0-88bd-9e849bc1bd23)
![Image](https://github.com/user-attachments/assets/33d3a9b5-a182-497c-9315-df54df74af30)

### 你期望发生的行为？

希望更新魔神任务数据

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
这里的全部完成直接从米游社获取，那只能说明米游社的实时便笺显示全部完成

**Comment by qhy040404** [comment]
![Image](https://github.com/user-attachments/assets/5f579d38-1f58-4e08-a46a-fde8aaee6719)
不是有吗？

**Comment by cx-xingchuan** [comment]
当时看了，没有，估计是没刷新过来，但是其他数据刷新过来了，就觉得可能有问题，现在好了
