### ISSUE TITLE
[Bug]: 胡桃工具箱1.12.14.0在游戏中自动弹出窗口或者不玩游戏到时候也老是会自动启动弹出窗口

### ISSUE THREAD

**Issue by xingxingyo184** [DGP-Studio/Snap.Hutao#2257]
### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.14.0

### 设备 ID

DC753CB3B100321DD5E21459D9F66D28

### 问题分类

游戏启动器

### 发生了什么？

胡桃工具箱1.12.14.0在游戏中自动弹出窗口或者不玩游戏到时候也老是会自动启动弹出窗口

### 你期望发生的行为？

不会自动弹出窗口影响游戏体验

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
使用管理员权限运行 cmd 并执行 `schtasks /delete /tn SnapHutaoDailyNoteRefreshTask`
