### ISSUE TITLE
[Bug]: 无法打开与更新胡桃

### ISSUE THREAD

**Issue by Beiilin** [DGP-Studio/Snap.Hutao#2268]
### Windows 版本

26100.2454

### Snap Hutao 版本

1.12.5.0

### 设备 ID

6850CE2644248E9E6F5A6027E0A91F37

### 问题分类

安装和环境

### 发生了什么？

打不开也更新不了 提示无法注册包![Image](https://github.com/user-attachments/assets/066869f2-5d37-4922-87aa-52360ea17170)
![Image](https://github.com/user-attachments/assets/c271e7bd-82da-4f7d-ab62-c0acb5599ec1)
[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/18039034/Snap.Hutao.Error.Log.txt)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2217
