### ISSUE TITLE
[Bug]: 胡桃更新到1.12.5.0后无法正常使用，首页点击启动无任何效果，点击祈愿记录或者其他直接白屏卡死

### ISSUE THREAD

**Issue by Knighrt** [DGP-Studio/Snap.Hutao#2269]
### Windows 版本

19045.5131

### Snap Hutao 版本

1.12.5

### 设备 ID

5440EA6E9F1D967BABE5FDCCCCC8770D

### 问题分类

游戏启动器

### 发生了什么？

胡桃更新到1.12.5.0后无法正常使用，首页点击启动无任何效果，点击祈愿记录或者其他直接白屏卡死，也无法登录米游社等等。只能打开公告和设置，其他的打开就卡死

### 你期望发生的行为？

我希望可以修复这个问题，恢复原来的体验

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
等待主页卡片加载
