### ISSUE TITLE
[Bug]: 【队伍配置冷开关】及【移除队伍配置进度条】开启后无法进入游戏

### ISSUE THREAD

**Issue by Tiamat9527** [DGP-Studio/Snap.Hutao#2277]
### Windows 版本

Win10-22H2-19045.5198

### Snap Hutao 版本

1.12.5.0

### 设备 ID

96E3A4187FD1BDD87662E2262DBDE7FC

### 问题分类

游戏启动器

### 发生了什么？

启动游戏-注入功能中的【队伍配置冷开关】及【移除队伍配置进度条】功能出现异常
具体表现为开启【队伍配置冷开关】及【移除队伍配置进度条】后进入游戏，【MiHOYO】的logo出现后游戏界面进入白屏且无响应。
经另一台电脑测试也出现了这个情况。
怀疑是米哈游官方修复了这个功能。

### 你期望发生的行为？

能否使【队伍配置冷开关】及【移除队伍配置进度条】功能恢复正常

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
![Image](https://github.com/user-attachments/assets/c1033667-186f-492c-b15a-ad9bdc32c5c9)
眉毛下面挂俩蛋
