### ISSUE TITLE
[Bug]: 启动游戏程序未响应

### ISSUE THREAD

**Issue by kimberleyQiu** [DGP-Studio/Snap.Hutao#2278]
### Windows 版本

22631.4602

### Snap Hutao 版本

1.12.5.0

### 设备 ID

EFCDBCD638E4CA436C1DA1823BB3060D

### 问题分类

游戏启动器

### 发生了什么？

启动游戏程序未响应 b站各种方法都试过了 希望尽快回复

### 你期望发生的行为？

正常启动游戏

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by kimberleyQiu** [comment]
啥意思

**Comment by Lightczx** [comment]
#2277

**Comment by kimberleyQiu** [comment]
错误代码31-4302

**Comment by Lightczx** [comment]
自己去看文档

**Comment by kimberleyQiu** [comment]
没找到呢github和已知问题都没找到

**Comment by Lightczx** [comment]
![Image](https://github.com/user-attachments/assets/37373f96-f21e-4e65-a64c-d86b9f619cb9)
《我也没找到》
