### ISSUE TITLE
[Bug]: 同步背包物品时，无法同步绿色、蓝色品质的经验书，以及灰色、绿色品质的矿

### ISSUE THREAD

**Issue by GoddessLuBoYan** [DGP-Studio/Snap.Hutao#2283]
### Windows 版本

19045.5131

### Snap Hutao 版本

1.12.5

### 问题分类

养成计算

### 发生了什么？

如图所示，同步背包物品后，绿色、蓝色品质的经验书数量显示为0，然而每周可以在壶里兑换100本绿的，刷取地脉花时也会掉落大量蓝的，这两种经验书未同步成功会导致养成计算时对树脂需求的预估出现较大偏差
（灰色、绿色品质的矿同理）
![Image](https://github.com/user-attachments/assets/f4914b33-7713-4831-a558-d9b0352c1824)

### 你期望发生的行为？

1. 当养成材料中包括经验书时，同步所有品质的经验书数量。（矿同理，如果天赋书、角色突破用的晶石等有类似问题，可同理）
2. 养成计算时，将所有品质的经验书数量全部纳入考量，或将不同品质的经验书全部换算为对应数量的某种颜色的经验书，或直接按照需求的经验值进行养成计算（矿、天赋书等同理）

若难以实现，则可以考虑简化版实现法：
1本绿色经验书=1/20本紫色经验书
1本蓝色经验书=1/5本紫色经验书
将所有绿色、蓝色经验书的数量换算为紫色经验书的数量，加起来以后取整数，再与实际拥有的紫色经验书的数量加起来，作为我拥有的紫色经验书的数量。若以此法统计，则弹出一条消息：“您拥有的绿色、蓝色经验书已按经验值换算为等量的紫色经验书”或类似文本。（矿同理，但精力不足时可不做）

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
米哈游API不返回绿书蓝书白矿绿矿

**Comment by GoddessLuBoYan** [comment]
> 米哈游API不返回绿书蓝书白矿绿矿

那就无解了
