### ISSUE TITLE
[Bug]: 开启注入功能后，游戏本体有概率闪退

### ISSUE THREAD

**Issue by showx1ao** [DGP-Studio/Snap.Hutao#2287]
### Windows 版本

26100.2605

### Snap Hutao 版本

1.12.7.0

### 设备 ID

0021E50740D7E5CD3FFB064B297689E1

### 问题分类

游戏启动器

### 发生了什么？

开启注入功能后（即便里面的所有选项都没生效），游戏打开后在白屏阶段有概率闪退，并在胡桃工具箱右下角弹出相关提示。
![Image](https://github.com/user-attachments/assets/55593915-71df-48c1-a92a-73e0a1e9ad2a)

PS1️⃣：本问题最早出现在1.12.5.0版本，当时分别有两个提示出现。
第一个是在胡桃工具箱内点击启动游戏按钮后，无反应直接弹出的提示
![Image](https://github.com/user-attachments/assets/d21421b5-07db-4b1f-b235-fbc8f71272e1)
第二个是点击启动游戏后，进入游戏但在白屏阶段内直接闪退的提示
![Image](https://github.com/user-attachments/assets/25260e3e-b474-4c82-b20c-104ea4d01b2c)

PS2️⃣：关闭注入功能后，通过胡桃工具箱或者米哈游官方启动器均可正常启动，无闪退情况发生。

PS3️⃣：已通过米哈游官方启动器、胡桃工具箱、游戏本体的检测功能确定游戏本体无问题。

### 你期望发生的行为？

开启注入功能后可以正常打开游戏游玩。

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你网炸了

**Comment by showx1ao** [comment]
> 你网炸了



> 你网炸了

啊？但其实我这边是可以正常上网的-.-

**Comment by qhy040404** [comment]
那你可以直连Google吗

**Comment by showx1ao** [comment]
> 那你可以直连Google吗

不能-.-用谷歌还是得用小飞机，

**Comment by qhy040404** [comment]
《但其实我这边是可以正常上网的-.-》
