### ISSUE TITLE
[Bug]: powershell安装胡桃提示包或捆绑无数字签名或其签名已损坏

### ISSUE THREAD

**Issue by Saber9826** [DGP-Studio/Snap.Hutao#229]
### Windows 版本

17134.1304

### Snap Hutao 版本

1.1.7.0

### 发生了什么？

powershell安装胡桃提示包或捆绑无数字签名或其签名已损坏，根证书已经安装到可信任第三方机构下，还是提示不收信任的应用(胡桃)，已确认文档中无相关内容，麻烦大佬抽空余时间解答一下，非常感谢，
![image](https://user-images.githubusercontent.com/53893904/202336718-c1528033-d56c-4fee-a2c9-967283fd00da.png)

### 你期望发生的行为？

正常安装，再次感谢

### 相关的崩溃日志

未发生崩溃

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
装个新版本

**Comment by Saber9826** [comment]
win系统的新版本还是胡桃的新版本呢，胡桃的新版本我试过了，还是同样的错误，

**Comment by Lightczx** [comment]
“点我安装.exe”

**Comment by Saber9826** [comment]
![image](https://user-images.githubusercontent.com/53893904/202346073-c60a1c7a-ba1b-400f-9ec3-2225e2e32bce.png)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/201#issuecomment-1312323116
