### ISSUE TITLE
[Bug]: 每次版本升级的时候开代理会报错然后打不开

### ISSUE THREAD

**Issue by kissgo** [DGP-Studio/Snap.Hutao#2298]
### Windows 版本

19042.5198

### Snap Hutao 版本

1.12.8.0

### 设备 ID

BE9C5A62B14493ED583B58443DC34433

### 问题分类

安装和环境

### 发生了什么？

每次版本升级之后，不管是哪种方式更新，更新完之后第一次打开，如果开着代理，他会弹出“解除loopback”弹窗，然后无论点击解除与否，胡桃许多界面直接变成空白，无法打开，首页也只有启动游戏能够点击，其他均是加载中的界面，而且重启电脑和胡桃都无法解决，只有重装然后第一次运行的时候不开着代理，所有组件才能正常加载。如果需要日志和图片我下次更新的时候补上

### 你期望发生的行为？

开着代理不影响组件的加载

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
> 首页也只有启动游戏能够点击，其他均是加载中的界面

在代理中排除 api.snapgenshin.com
