### ISSUE TITLE
[Bug]: 大招动画异常

### ISSUE THREAD

**Issue by Fengbai-Su** [DGP-Studio/Snap.Hutao#2299]
### Windows 版本

22631.4602

### Snap Hutao 版本

1.12.8.0

### 设备 ID

90361E0A83CB5D23643AA4EA12F4C43C

### 问题分类

游戏启动器

### 发生了什么？

使用27寸4K显示屏游戏，在注入模块解锁帧率后，角色大招动画视野被拉近，导致动画中人物变大，动画边缘溢出屏幕。在启动游戏界面更新之前的版本没有出现过这种情况。

### 你期望发生的行为？

恢复大招动画到适配屏幕的正常比例

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
不要调整视野

**Comment by Fengbai-Su** [comment]
> 不要调整视野

视野使用的默认的视野，没有调整。刚刚尝试调整了几次，动画效果还是这样，应该不是视野的问题

**Comment by Fengbai-Su** [comment]
> 不要调整视野

视野使用的默认视野，没有调整过。其他各种场景视野都是正常的，只有大招动画有问题

**Comment by Fengbai-Su** [comment]
> 不要调整视野

关闭注入模块会恢复正常，但解帧需要打开注入模块

**Comment by qhy040404** [comment]
关闭视野冷开关

**Comment by Fengbai-Su** [comment]
> 关闭视野冷开关

解决了，感谢
