### ISSUE TITLE
颜色看不清，希望考虑一下对比

### ISSUE THREAD

**Issue by kan846** [DGP-Studio/Snap.Hutao#23]
### 你想要实现或优化的功能？

![image](https://user-images.githubusercontent.com/63768657/188580372-af9fb39a-987b-4092-916f-74bf39395871.png)

**Comment by Lightczx** [comment]
可以用文本描述一下具体哪些地方么

**Comment by kan846** [comment]
成就的图标

**Comment by Maraudern** [comment]
成就-创建新存档-确定后弹窗的文字，在win10默认应用颜色模式为亮的情况下和背景颜色的对比度不明显
![](https://s2.loli.net/2022/09/06/qQmADJHvNBin94O.png)

**Comment by kan846** [comment]
成就的图标
![image](https://user-images.githubusercontent.com/63768657/188641968-c8c4cea1-d6c6-402f-aade-70c07fda6c10.png)
角色天赋，元素爆发与元素战技和命之座的突出描写颜色，他们在白色与元素颜色的背景下，使用的颜色明度有点高以及颜色相似性都比较高了，有时候查看不太方便
![image](https://user-images.githubusercontent.com/63768657/188643123-6b635330-f1d1-4abc-a5bc-27e5cc0b36d7.png)
![image](https://user-images.githubusercontent.com/63768657/188643200-5085f7d1-9e6a-4577-9ea9-d387c742678a.png)
![image](https://user-images.githubusercontent.com/63768657/188643304-0b29ef1c-3eef-4bc2-8c0c-425dbe962c1f.png)
![image](https://user-images.githubusercontent.com/63768657/188643343-d558fbfa-7086-48f0-9bd8-f27a48d86d10.png)
![image](https://user-images.githubusercontent.com/63768657/188643383-71d4d3be-a8b2-4040-b025-46f845e5ab13.png)

**Comment by kan846** [comment]
我的笔记本屏幕色域是8bit 100%srgb的联想R7000P2020，不确定是不是我的显示问题

**Comment by kan846** [comment]
系统是win11的22000.918

**Comment by Lightczx** [comment]
角色页面的天赋描述颜色已经经过适配

**Comment by Lightczx** [comment]
底部通知的颜色已经经过适配

**Comment by YYl04** [comment]
祈愿记录出货抽数的颜色也可以考虑更改一下吗
![image](https://user-images.githubusercontent.com/95568556/230782841-48918fdb-501c-4fcb-89c1-ae821feb63f6.png)
虽然不知道你们的机制，但建议统一使用高饱和度颜色，例如目前已有的天空之翼和风鹰剑的
