### ISSUE TITLE
[Bug]: 便签相同提示重复太多了

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#230]
### Windows 版本

22623.891

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

打开便签页面放在后台，过一会就全屏都是提示了，关都关不完
应该弹提示前检测一下如果有相同uid的相同警告就不要弹出来了
![image](https://user-images.githubusercontent.com/2825342/202358091-4ad038e9-27c8-422b-b6f9-a1f06c8ed5c3.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
fixed internally
