### ISSUE TITLE
[ENG][Bug]: APP CRASH

### ISSUE THREAD

**Issue by z2w3** [DGP-Studio/Snap.Hutao#2300]
### Windows Version

win10 22h2

### Snap Hutao Version

1.12.8.0

### Device ID

186C57088EDCC056ADB60D11F00CBD55

### Issue Category

Installation and Environment

### What Happened?

Snap Hutao 1.12.8.0
Windows 10.0.19045.5247
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
[string]:Description:组件初始化失败。

[string]:RestrictedDescription:System.Runtime.InteropServices.COMException
[string]:RestrictedErrorReference:
[string]:RestrictedCapabilitySid:
[WinRT.ObjectReferenceWithContext<WinRT.Interop.IUnknownVftbl>]:__RestrictedErrorObjectReference:WinRT.ObjectReferenceWithContext`1[WinRT.Interop.IUnknownVftbl]
[bool]:__HasRestrictedLanguageErrorObject:False
----------------------------------------
System.Runtime.InteropServices.COMException (0x80004005)

### What is expected?

FILL THE CRASH

### Last Step

- [x] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by z2w3** [comment]
大概是打开软件后10分钟左右会自动崩溃（无论是否运行游戏）
已经尝试重装软件

**Comment by z2w3** [comment]
上一个版本和这一个版本都有这个问题。但上一个版本之前用着是好的
也不影响软件功能，只是会弹出崩溃提示

**Comment by Lightczx** [comment]
是否在使用自定义背景

**Comment by Lightczx** [comment]
你的背景中可能包含了HEIF图像，在没有安装解码器时是无法正常工作的
