### ISSUE TITLE
[Feat]: 增加镜头距离更改功能

### ISSUE THREAD

**Issue by buhuishaujidexiaobai** [DGP-Studio/Snap.Hutao#2302]
### 背景与动机

目前游戏内注入功能已有视野开关，但视野的改变会引起画面的畸变

### 想要实现或优化的功能

希望能够添加镜头距离更改的功能，以便在获取更大视野距离的同时能够不影响画面扭曲程度（如果改这个东西过于危险就当我没说）

**Comment by Lightczx** [comment]
> 以便在获取更大视野距离的同时能够不影响画面扭曲程度

想挺美
