### ISSUE TITLE
[Feat]: 角色资料/我的角色缺少旅行者

### ISSUE THREAD

**Issue by Aniverse** [DGP-Studio/Snap.Hutao#2305]
### 背景与动机

我注意到 https://github.com/DGP-Studio/Snap.Hutao/issues/253 已经标记为 completed 了，但是在现在的最新版本上我没有在角色资料里找到旅行者，甚至在我的角色里也没有。

### 想要实现或优化的功能

在我的角色里显示旅行者，在角色资料里添加各种属性旅行者的资料

**Comment by Lightczx** [comment]
不会考虑
