### ISSUE TITLE
[Bug]: 外观设置

### ISSUE THREAD

**Issue by readice** [DGP-Studio/Snap.Hutao#231]
### Windows 版本

19044.2251

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

设置界面背景材质切换到亚克力后切回云母和变种云母没反应，需要重启胡桃才能生效，而且没看出云母和变种云母的外观区别，看了很久感觉就是一个样子，不知道是弄重了还是有bug

- 补充：从云母/变种云母切换到亚克力---界面外观发生变化   之后无论选择哪个都不会变化，除非重启胡桃 

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
Windows 10 不支持 云母与变种云母
Mica 与 Mica Alt 是 Windows 11 独占的功能
