### ISSUE TITLE
[Bug]: 关闭游戏后胡桃内启动游戏按钮显示灰色

### ISSUE THREAD

**Issue by HIMQ** [DGP-Studio/Snap.Hutao#2314]
### Windows 版本

19045.5247

### Snap Hutao 版本

1.12.8.0

### 问题分类

游戏启动器

### 发生了什么？

关闭游戏后  启动按钮显示灰色的   几分钟后才正常

### 你期望发生的行为？

关闭游戏后  几秒内启动按钮就马上可以再次使用

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
游戏进程还在任务管理器中
