### ISSUE TITLE
[Bug]: 胡桃工具箱1.12.x所有版本安装后均无法启动

### ISSUE THREAD

**Issue by wjdxmrh39** [DGP-Studio/Snap.Hutao#2318]
### Windows 版本

19044.1288

### Snap Hutao 版本

1.12.x

### 设备 ID

8586ADD30E59A85F600325C2435A6667

### 问题分类

安装和环境

### 发生了什么？

Win10企业版LTSC(19044.1288)安装任意1.12版本胡桃工具箱后均无法启动，部署工具无报错，启动时无报错无弹窗
![Image](https://github.com/user-attachments/assets/db88a8c4-8396-45c2-86ff-0041f7cc28cf)
![Image](https://github.com/user-attachments/assets/19e67711-4cd2-45f2-af22-ff78062de554)

而在沙盒系统Win10企业版(19041.1288)中安装后则能够正常启动
![Image](https://github.com/user-attachments/assets/5bda7cd3-ece3-42d6-856d-33c5bc8c538c)
![Image](https://github.com/user-attachments/assets/570f8aa1-d0fb-48d7-85fa-8691922577c8)
![Image](https://github.com/user-attachments/assets/fcfda30d-1c04-4836-8db9-a5daa8259282)

并且Win10企业版LTSC(19044.1288)安装任意1.12之前版本的胡桃工具箱(如1.11.9)则能够正常启动
使用过https://github.com/DGP-Studio/Snap.Hutao/issues/2217 提供的两种方法均无效

### 你期望发生的行为？

安装最新版本工具箱

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
我们不推荐也不会主动支持ltsc与ltsb等特殊精简版本，如果确实有相关需求，请参考相关教程。但是，在安装过程中出现的所有问题均不会得到支持

https://hut.ao/zh/quick-start.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%A8%8B%E5%BA%8F%E4%B8%AD%E7%9A%84%E5%9B%BE%E6%A0%87%E4%BC%9A%E5%87%BA%E7%8E%B0%E4%B9%B1%E7%A0%81%E7%8E%B0%E8%B1%A1
