### ISSUE TITLE
[Bug]: 登录信息丢失，重新登录卡在【获取用户信息中，请稍后】

### ISSUE THREAD

**Issue by home110120** [DGP-Studio/Snap.Hutao#2319]
### Windows 版本

19045.5247

### Snap Hutao 版本

1.12.8.0

### 问题分类

米游社账号面板

### 发生了什么？

昨日正常使用退出。今日打开胡桃工具箱时，登录信息丢失，主页祈愿记录和实时便笺在一直闪动，检查发现登录信息丢失，左下角显示尚未登录，点进去并没有看到之前登录过的用户信息，选择验证码重新登录就卡在获取用户信息中。

### 你期望发生的行为？

成功登录米游社账号，可使用原有功能。

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
已复现，排查中

**Comment by Lightczx** [comment]
等待主页卡片加载

**Comment by Mikachu2333** [comment]
请删除胡桃的设置文件夹（删除前请妥善导出你的祈愿、成就等文件），再重启程序
