### ISSUE TITLE
[Bug]: 高帧率下异常卡顿

### ISSUE THREAD

**Issue by chy22995** [DGP-Studio/Snap.Hutao#2320]
### Windows 版本

22631.4602

### Snap Hutao 版本

1.12.8.0

### 设备 ID

F66799299022F9D7E6CA6A2078146B54

### 问题分类

安装和环境

### 发生了什么？

之前解锁帧率一直用得好好的，但两周前开始高帧率情况下异常卡顿 显卡占用 帧率显示是没问题，调回到60帧就无异常

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
问米哈游
