### ISSUE TITLE
[Bug]: 无法通过胡桃启动游戏

### ISSUE THREAD

**Issue by lilong555** [DGP-Studio/Snap.Hutao#2321]
### Windows 版本

22631.4602

### Snap Hutao 版本

1.12.8.0

### 设备 ID

07314B8EDD34EB5E93517B9601168176

### 问题分类

游戏启动器

### 发生了什么？

- 以管理员进入程序，点击启动游戏（解锁帧率模式），启动游戏的窗口略暗（但没有正常启动时的状态提示的小字）

### 你期望发生的行为？

正常启动游戏

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by lilong555** [comment]
网络：校园网和手机热点都试过，网络代理：有代理和无代理都试过；
卸载重装，重启电脑都试过
以上方法均无效

**Comment by Tiamat9527** [comment]
我也遇到了一样的问题。
Windows 10 专业版22H2    19045.5247
点击启动游戏后【启动游戏】按钮变暗，
但无游戏窗口弹出。
试过通过米哈游启动器打开游戏，结果可以。![Image](https://github.com/user-attachments/assets/0d82042d-fecc-460c-8e53-34afb38a8fe3)

**Comment by 547shiwangchu** [comment]
感觉跟登录失效有关，前几天打开后显示尚未登录，无法启动游戏，过了一小会自动登录上了，就能正常启动了，今天一直登录不上就一直启动不了，使用手机验证码无法登陆，连续三小时一直显示获取用户信息中，请稍后，卸载重装/重启电脑都无法解决

**Comment by Lightczx** [comment]
fixed

**Comment by Mikachu2333** [comment]
> 感觉跟登录失效有关，前几天打开后显示尚未登录，无法启动游戏，过了一小会自动登录上了，就能正常启动了，今天一直登录不上就一直启动不了，使用手机验证码无法登陆，连续三小时一直显示获取用户信息中，请稍后，卸载重装/重启电脑都无法解决

请重启程序，应当已经修复完毕了

**Comment by lilong555** [comment]
![Image](https://github.com/user-attachments/assets/f0becacb-ba95-48e4-9bc3-231cc9b51605)

![Image](https://github.com/user-attachments/assets/1ae0c375-620f-4888-885f-d60f4e3c3ee6)
还是进不去

**Comment by Mikachu2333** [comment]
请尝试：

1. 退出胡桃
2. 删除胡桃目录下的metadata文件夹（通常在 `%USERPROFILE%/Documents/Hutao` 目录下）
4. 切换至热点
5. 重启胡桃
6. 等待3-5分钟
7. 重启胡桃
