### ISSUE TITLE
[Feat]: 自定义安装路径&添加云原神启动项

### ISSUE THREAD

**Issue by Hefang2000** [DGP-Studio/Snap.Hutao#2323]
### 背景与动机

- 占用系统盘空间

- 原神本体过大卸载后已不愿下载

### 想要实现或优化的功能

- 安装目录**可自定义**
- 添加**云·原神**启动项

**Comment by Mikachu2333** [comment]
什么东西的路径？胡桃本体没有可能自定义安装路径，这是Windows导致的限制

原神的安装路径可以指定，也已经实现

**Comment by Hefang2000** [comment]
> 什么东西的路径？胡桃本体没有可能自定义安装路径，这是**Windows导致的限制**

- [ ] 哪我要如何做才能实现自定义安装？

> 原神的安装路径可以指定，也已经实现

- [ ] yes,it is. 但**安装路径的选择严格限制了目标的名称与类型**仅“Genshin Impact.exe”与“YuanShen.exe”被允许，而云·原神的启动项是“**Genshin Impact Cloud Game.exe**”。
原神 PC 客户端不止有“原神”还有“**云·原神**”

**Comment by Mikachu2333** [comment]
胡桃本体的迁移问题不属于我们应该解决的范畴，以下是一些相关资料，请自行参照解决

https://answers.microsoft.com/zh-hans/windows/forum/all/%E5%A6%82%E4%BD%95%E5%AE%89%E5%85%A8%E5%9C%B0/f5e1a207-8f8a-4ec6-ab80-bc992d49fda8

![Image](https://github.com/user-attachments/assets/8760d52d-5b79-427a-b9ed-d18531ec9e24)

---

云原神请参考之前的回复：暂时不予考虑

https://github.com/DGP-Studio/Snap.Hutao/issues/1202#issuecomment-1867199225

**Comment by Hefang2000** [comment]
> 云原神请参考之前的回复：暂时不予考虑

- 好吧
