### ISSUE TITLE
[Bug]: 图片不显示.深渊统计也不显示

### ISSUE THREAD

**Issue by mazhonma** [DGP-Studio/Snap.Hutao#234]
### Windows 版本

Win11

### Snap Hutao 版本

1.2

### 发生了什么？

图片不显示.深渊统计也不显示
![image](https://user-images.githubusercontent.com/118546498/202732451-4c707527-fa4a-47cb-bf49-9db6600a83f4.jpg)
![image](https://user-images.githubusercontent.com/118546498/202732498-cd6447b8-8c27-430a-9a1d-119ea20f5909.jpg)
![image](https://user-images.githubusercontent.com/118546498/202732555-446ae992-1ddc-4410-ba5c-55036bf7661f.jpg)

### 你期望发生的行为？

图片能正常显示 和深渊统计能打开

### 相关的崩溃日志

无

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by steven52880** [comment]
有相同问题
看起来是因为网络问题下载图片失败，但是进行了缓存，可以在缓存文件夹找到0kb文件
清理空的缓存后得到缓解

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by mazhonma** [comment]
> 

并没有用.删掉了0kb的.也不能解决问题 都是不显示

**Comment by mazhonma** [comment]
> @Masterain98供参考



> 有相同问题看起因是网络问题下载图片丢了，但是进行了存档，可以在存档文件夹找到 0kb
> 文件清理空间的存档后得到解析

并没有用.即使删掉0kb的.也不能解决问题.都依然不显示图片

**Comment by mazhonma** [comment]
> 有相同问题看起因是网络问题下载图片丢失，但是进行了存档，可以在存档文件夹找到 0kb
> 文件清理空间的存档后得到解析

删掉以后.再次打开 它会自动下载.下载后的存档也是0kb.所以删是没用的

**Comment by mazhonma** [comment]
> 有相同问题看起因是网络问题下载图片丢了，但是进行了存档，可以在存档文件夹找到 0kb
> 文件清理空间的存档后得到解析

但是我的网络也没有出现问题.也能流畅的链接互联网.还有什么解决方法吗？

**Comment by Lightczx** [comment]
我们服务器的问题，客户端是没办法解决的

**Comment by Lightczx** [comment]
fixed internally
