### ISSUE TITLE
添加账号无反应

### ISSUE THREAD

**Issue by Ncnci1** [DGP-Studio/Snap.Hutao#237]
### Windows 版本

25247.1000

### Snap Hutao 版本

1.2.2.0

### 发生了什么？

就是添加账号之后显示成功，然后下面用户名称是乱码，去左下角看账号也没有

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
备份祈愿与成就等数据，删除Userdata.db

**Comment by Ncnci1** [comment]
谢谢大大
