### ISSUE TITLE
[Bug]: 实时便笺——提醒通知会自动为“关”

### ISSUE THREAD

**Issue by Linaixn** [DGP-Studio/Snap.Hutao#238]
### Windows 版本

19041.450

### Snap Hutao 版本

1.2.2

### 发生了什么？

实时便笺——通知设置——提醒通知（防止自动通知收入操作中心），设置为“开”状态。
左侧如果切换条目（例如切换到祈愿记录），再切换回“实时便笺”，“提醒通知”则自动变为“关”。
![image](https://user-images.githubusercontent.com/118617727/202856324-f2f8bce2-3d1a-4997-9004-e954bdff946f.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
已知问题，下版本修复
