### ISSUE TITLE
[Bug]: 祈愿记录切换号，鼠标点不到最上的那个

### ISSUE THREAD

**Issue by Linaixn** [DGP-Studio/Snap.Hutao#239]
### Windows 版本

19041.450

### Snap Hutao 版本

1.2.2

### 发生了什么？

祈愿记录有3个号的话，切换时候最上面的号，鼠标选不中。
录了个GIF描述问题。
估计是最上面的号和SH的标题栏的冲突，居中对齐的缘故。
![bandicam 2022-11-12 02-40-26-438 00_00_00-00_00_30](https://user-images.githubusercontent.com/118617727/202856536-1b1dd473-8b66-431f-908f-b1f6cfe05a28.gif)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/53#issuecomment-1260425013
