### ISSUE TITLE
[Bug]: 实时便签通知设置无效

### ISSUE THREAD

**Issue by Mijiu190** [DGP-Studio/Snap.Hutao#241]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.2.0

### 发生了什么？

实时便签通知设置里面即使选了60分钟刷新，但实际刷新时间仍然是8分钟

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
fixed internally
