### ISSUE TITLE
[Bug]: 账号有风险，请前往米游社查看

### ISSUE THREAD

**Issue by zxsn** [DGP-Studio/Snap.Hutao#243]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.2.0

### 发生了什么？

![image](https://user-images.githubusercontent.com/29946527/202872125-d9d6cec4-cbcd-4977-a29e-f8d3348f4cc8.png)
账号登陆正常，点击实时便笺出现上图现象。重新尝试问题依旧。账号已绑定手机号。

### 相关的崩溃日志

[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10047977/Log.zip)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
![image](https://user-images.githubusercontent.com/96916320/202879564-2d9e180c-219c-46cc-8b46-de568d976a9d.png)
