### ISSUE TITLE
开机自启

### ISSUE THREAD

**Issue by renlufan** [DGP-Studio/Snap.Hutao#245]
### 你想要实现或优化的功能？

可不可以增加一个卸载选项和关闭开机自启的功能，我并没有说程序不好，只是开机自启感觉有点不太好，启动面板的卸载点击之后总是会弹出一个这样的窗口，可能是卸载不完全
![Snipaste_2022-11-20_16-47-15](https://user-images.githubusercontent.com/118655409/202893563-0fc910f2-711f-47fa-98cb-d6d85b54b424.png)

**Comment by Lightczx** [comment]
#202
