### ISSUE TITLE
[Bug]: 应用部分图标问题

### ISSUE THREAD

**Issue by MYXXTS** [DGP-Studio/Snap.Hutao#246]
### Windows 版本

22H2  19045.2311

### Snap Hutao 版本

1.2.2.0

### 发生了什么？

目前发现应用底部弹出的窗口的图标无法正常显示，类似于乱码的一种情况，最终以汉字呈现图标
![image](https://user-images.githubusercontent.com/51087760/202987519-a6087661-365e-47f7-bca4-a409cd31ab1a.png)

### 你期望发生的行为？

图标修复

### 相关的崩溃日志

无

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
#61

**Comment by MYXXTS** [comment]
没看到这个 issue，我是按照图标去搜索的，未搜到提出的此 issue，实在抱歉

**Comment by BoseCoder** [comment]
遇到相同问题了。
重新安装的过程也出现了问题：卸载后直接蓝屏了，重启并重新安装后仍然是乱码。
近期好像经常会引起系统蓝屏，希望开发组能排查一下。

**Comment by Lightczx** [comment]
> 遇到相同问题了。 重新安装的过程也出现了问题：卸载后直接蓝屏了，重启并重新安装后仍然是乱码。 近期好像经常会引起系统蓝屏，希望开发组能排查一下。

蓝屏和乱码没有关系

**Comment by Lightczx** [comment]
那你开新的Issue啊，发这里干啥
