### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by MayPoxN** [DGP-Studio/Snap.Hutao#247]
### Windows 版本

19044.1706

### Snap Hutao 版本

1.2.2.0

### 发生了什么？

在"实时便签"里面，添加了账号之后。在下方提示账号有风险，请前往米游社查看。并且实时便签不显示内容。

### 你期望发生的行为？

能正常显示实时便签该有的内容。或者能指明在米游社哪里可以解决这个问题。

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
看文档
