### ISSUE TITLE
[Bug]: 卸载之后总是过一段时间弹窗

### ISSUE THREAD

**Issue by DangeRS2** [DGP-Studio/Snap.Hutao#248]
### Windows 版本

22000.1219

### Snap Hutao 版本

1.2

### 发生了什么？

卸载工具箱之后，总是过一段时间出现如下弹窗，该怎么解决，真的很烦
![Snipaste_2022-11-21_18-19-48](https://user-images.githubusercontent.com/49086184/203177705-0e15c647-717b-4400-82a7-21894bb34621.png)

最离谱的是，为了不让它弹窗，我只能重装这个软件。。

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
https://hut.ao/FAQ/most-frequent-questions.html

**Comment by cdwmhcc** [comment]
> https://hut.ao/FAQ/most-frequent-questions.html

这个网站偶尔可以打开，大部分时间打不开。

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by Masterain98** [comment]
> > https://hut.ao/FAQ/most-frequent-questions.html
> 
> 这个网站偶尔可以打开，大部分时间打不开。

[network-diagnosis-hutao.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10081999/network-diagnosis-hutao.zip)
麻烦下载并运行上面这个诊断程序，并将生成的测试报告发送回来。

**Comment by cdwmhcc** [comment]
> > > https://hut.ao/FAQ/most-frequent-questions.html
> > 
> > 
> > 这个网站偶尔可以打开，大部分时间打不开。
> 
> [network-diagnosis-hutao.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10081999/network-diagnosis-hutao.zip) 麻烦下载并运行上面这个诊断程序，并将生成的测试报告发送回来。

https://raw.githubusercontent.com/cdwmhcc/MagiskOnWSA/master/hutao-network-log.txt
