### ISSUE TITLE
[Bug]: 启动游戏多账号切换显示bug

### ISSUE THREAD

**Issue by BlackKL065** [DGP-Studio/Snap.Hutao#249]
### Windows 版本

19044.2251

### Snap Hutao 版本

1.2.2.0

### 发生了什么？

检测新账号并命名后关闭胡桃重新开启会出现两个相同账号
![image](https://user-images.githubusercontent.com/98877368/203284398-a50c5862-eccc-40ed-817b-117776a895b2.png)
![image](https://user-images.githubusercontent.com/98877368/203284425-83e8f047-75a4-4f63-8d90-b0f92cefd7ba.png)
且多账号时绑定uid会显示同一个uid
![image](https://user-images.githubusercontent.com/98877368/203284776-c7afcc3e-82a2-4049-8c1b-d32791a21f09.png)
![image](https://user-images.githubusercontent.com/98877368/203284786-808903bb-0abd-43e2-9695-67b51c9d3e6f.png)
![image](https://user-images.githubusercontent.com/98877368/203284792-090f8c97-13a5-4170-802f-b832d038882c.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
@BlackKL065 1.2.6还能复现么

**Comment by BlackKL065** [comment]
@Lightczx 问题仍存在 
相同账号问题只在检测账号并且绑定uid后重启胡桃会发生
检测后未绑定uid重启胡桃没复现
检测后未绑定uid重启胡桃再绑定uid再重启不会复现

**Comment by Lightczx** [comment]
fixed internally
