### ISSUE TITLE
[Bug]: 问题太多了，我想要彻底移除软件

### ISSUE THREAD

**Issue by GitHuberRich** [DGP-Studio/Snap.Hutao#250]
### Windows 版本

20H2 OS组建 19042.1165

### Snap Hutao 版本

1.2.0.0

### 发生了什么？

问题太多了，时常闪退，或是无法登入帐号，通知设置打开了，重开以后又变关闭，实时便签也不正常，之前因为时常闪退移除了胡桃软件，结果一直跳窗显示『您需要新的应用程式才能开啟此 hutao 连结』，后来不得已只好又安装，安装以后还是啥都不能用，我想移除干净这个软件，结果也没找到相关说明

### 你期望发生的行为？

我要干干净净彻底的移除胡桃软件

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
- What a shame
- 
- https://hut.ao/FAQ/most-frequent-questions.html#%E5%BC%B9%E5%87%BA%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E6%96%B0%E5%BA%94%E7%94%A8%E7%9A%84%E5%AF%B9%E8%AF%9D%E6%A1%86
