### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by ivanli3** [DGP-Studio/Snap.Hutao#256]
### Windows 版本

1909

### Snap Hutao 版本

1.2.4.0

### 发生了什么？

卸载软件后，总是弹出“需要使用新应用以此打开此hutao链接”。导致电脑无法正常使用。

### 你期望发生的行为？

我想要卸载此软件

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by evanliu3594** [comment]
一样遇到了这个BUG，系统Win10 22H2

**Comment by AdminRoc** [comment]
what a shame

https://hut.ao/FAQ/most-frequent-questions.html#%E5%BC%B9%E5%87%BA%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E6%96%B0%E5%BA%94%E7%94%A8%E7%9A%84%E5%AF%B9%E8%AF%9D%E6%A1%86

**Comment by Ohlagrange** [comment]
怎么解决这个问题，，怎么给关闭了啊

**Comment by Lightczx** [comment]
> 怎么解决这个问题，，怎么给关闭了啊

https://hut.ao/FAQ/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%BC%B9%E5%87%BA%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E6%96%B0%E5%BA%94%E7%94%A8%E4%BB%A5%E6%89%93%E5%BC%80%E7%9A%84%E5%AF%B9%E8%AF%9D%E6%A1%86

**Comment by HorizonChaser** [comment]
> > 怎么解决这个问题，，怎么给关闭了啊
> 
> https://hut.ao/FAQ/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%BC%B9%E5%87%BA%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E6%96%B0%E5%BA%94%E7%94%A8%E4%BB%A5%E6%89%93%E5%BC%80%E7%9A%84%E5%AF%B9%E8%AF%9D%E6%A1%86

https://hut.ao/zh/advanced/uninstall.html

运行 `schtasks /delete /tn SnapHutaoDailyNoteRefreshTask`
