### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by misaka10384** [DGP-Studio/Snap.Hutao#257]
### Windows 版本

windows 11 版本: 25247.1000

### Snap Hutao 版本

1.2.4.0

### 发生了什么？

![image](https://user-images.githubusercontent.com/61707010/203722777-2e1ef4d9-0ae5-42c2-bec0-3a10a0e3708b.png)
深渊统计→角色使用 界面掉帧  滚动时CPU占用飙升
![背景](https://user-images.githubusercontent.com/61707010/203724801-d4a17a1a-e7f0-44fc-8b0a-6cf607ab4676.gif)

### 你期望发生的行为？

建议优化

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
正常现象
