### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by YYl04** [DGP-Studio/Snap.Hutao#258]
### Windows 版本

Win11 22623.891

### Snap Hutao 版本

1.2.3.0

### 问题分类

用户界面

### 发生了什么？

![image](https://user-images.githubusercontent.com/95568556/203781702-a8ffcf25-ca24-4284-8d0d-6977a026b567.png)

### 你期望发生的行为？

设置横幅上限

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
更新
