### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by Erfan-maki** [DGP-Studio/Snap.Hutao#259]
### Windows 版本

22000.1219

### Snap Hutao 版本

1.2.4.0

### 问题分类

用户界面

### 发生了什么？

在sh登录米游社通行证的时候点获取验证码或者登录都没反应

### 你期望发生的行为？

正常登录

### 相关的崩溃日志

无，就是没有反应。

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
点太快了，关掉重新试试

**Comment by Erfan-maki** [comment]
重新打开就点一次还是一样没反应

**Comment by Lightczx** [comment]
可以输入账号或密码么

**Comment by Erfan-maki** [comment]
可以输入

**Comment by Lightczx** [comment]
所以是点击“登录”没有反应？

**Comment by Erfan-maki** [comment]
对的，点“获取验证码”也没反应

**Comment by Lightczx** [comment]
> 对的，点“获取验证码”也没反应

先看看浏览器里面 user.mihoyo.com 能不能正常登录

**Comment by Erfan-maki** [comment]
不能，但是浏览器之前也不能登录这个，胡桃可以，现在两个都不行了

**Comment by Lightczx** [comment]
应该是你的网络问题，导致了一些脚本下载失败了

**Comment by Erfan-maki** [comment]
好吧，打扰了，谢谢
