### ISSUE TITLE
[Bug]: 启动游戏分辨率问题

### ISSUE THREAD

**Issue by fangbianxiazai** [DGP-Studio/Snap.Hutao#261]
### Windows 版本

22000.1219

### Snap Hutao 版本

1.24

### 问题分类

游戏启动

### 发生了什么？

启动分辨率无法修改 2560-1440 修改之后 换到其他页面就会变回1920-1080 分辨率

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
修改后你得先启动
