### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by cliia** [DGP-Studio/Snap.Hutao#262]
### Windows 版本

22621.819

### Snap Hutao 版本

1.2.2.0

### 问题分类

实时便笺

### 发生了什么？

![image](https://user-images.githubusercontent.com/99332059/203819687-5c258b0b-8466-4532-b784-d64fc1a7c967.png)
1. 账号有风险不断提示，不会自动消除，最终导致上图现象。
2. 几个小时前，提示账号有风险，按照文档操作后消除，但是现在又出现了该提示。

### 你期望发生的行为？

会不会是访问次数过多，能不能增加一个不自动刷新，只手动刷新，或者一天一刷新，或者打开应用时刷新

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
1.已有相近issue

2.请先更新至最新版本
