### ISSUE TITLE
[Bug]: 无法正常登录游戏帐号（无法正常获取Cookies）

### ISSUE THREAD

**Issue by Soarniner** [DGP-Studio/Snap.Hutao#264]
### Windows 版本

19045.2251

### Snap Hutao 版本

1.2.0.0

### 问题分类

角色信息面板

### 发生了什么？

我的帐号之前在开始使用胡桃工具箱的时候，已经是每隔半天多就要去米游社的原神战绩工具里验证一次的”高风险等级“帐号
这段时间使用还算正常，除此以外没遇到其他登录问题

今天我退出了手机的米游社帐号临时登录另外一个帐号，结果发现所有的能查原神战绩和实时便笺的平台全部掉登录了。

我正常地在米游社重登回了主帐号，登录时没有任何验证要求，米游社自带的小组件工作正常。
然后我尝试在胡桃里面重新登录帐号，却发现登录上去以后，点”我已登录“无法获取Cookies

![图片](https://user-images.githubusercontent.com/74642591/204093891-125df0a0-d7c5-4620-bcb1-a357d94402ef.png)

我尝试在浏览器登录米游社原神分区，发现会弹出额外的一个验证窗口

![图片](https://user-images.githubusercontent.com/74642591/204094194-612c7aaa-61f4-47eb-a38f-06a0cb0ac0ca.png)

在等待验证窗口消失以后仍然获取不到Cookies

![图片](https://user-images.githubusercontent.com/74642591/204094269-94315281-5b2b-44e1-95f2-da00bcb24095.png)

**（我不知道这里面有没有敏感信息，如果有敏感信息，请帮我删除，谢啦）**

我根据文档https://hut.ao/FAQ/mihoyo-risk-tip.html进行了密码重置工作，再进行整个过程，仍然不起作用

### 你期望发生的行为？

正常登录

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Soarniner** [comment]
这里放一个隔壁家工具的相同情况的链接
https://github.com/xunkong/xunkong/issues/315

**Comment by AdminRoc** [comment]
首先，当前的最新版本是1.2.4，提交issue之前请先确保使用的是最新版本。
其次，最新版本中，文档也详细写明，目前版本仅使用含有Stoken字段，并且为V2版本的Cookie，与你的获取逻辑完全不同。

**Comment by AdminRoc** [comment]
![image](https://user-images.githubusercontent.com/96916320/204103926-6e22d14a-3ea2-431f-ac9e-c638d59e2467.png)
![image](https://user-images.githubusercontent.com/96916320/204103933-38ad0e5e-f844-4bad-8457-1b21a826422f.png)

**Comment by Soarniner** [comment]
抄收了，感谢！

Hutao居然没有更新提醒功能的嘛，用惯了不少开源的软件，这个完成度级别的一眼就默认带更新提醒功能了（
去官网的时候也没注意哪里显示最新版本号，软件又是最近装的，压根没想起来先去看看是不是最新版的

**Comment by AdminRoc** [comment]
目前实际上是公测状态，SnapGenshin的全部功能还未全部迁移完毕至SnapHutao，可以加入我们的[用户群](https://www.snapgenshin.com/groups/)，每个版本更新时，均有全体提醒。

**Comment by Soarniner** [comment]
原来如此，这就加入~

另外希望能增加掉登录提醒的功能，我平时不一定经常打开HuTao，希望软件可以在没有正常刷新便笺的数据时进行推送提醒

**Comment by AdminRoc** [comment]
![image](https://user-images.githubusercontent.com/96916320/204106654-94738670-29e3-47eb-a2fd-2f7c3ab7890d.png)
![image](https://user-images.githubusercontent.com/96916320/204106676-5b6c25be-9d79-42ba-bb9f-9f0f11f4cee9.png)
![image](https://user-images.githubusercontent.com/96916320/204106700-6e8271ea-e997-48bd-b7dd-3b0716a01ec9.png)
这也是文档中存在此条的原因：https://hut.ao/FAQ/most-frequent-questions.html#%E5%BC%B9%E5%87%BA%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E6%96%B0%E5%BA%94%E7%94%A8%E7%9A%84%E5%AF%B9%E8%AF%9D%E6%A1%86

**Comment by Soarniner** [comment]
啊，我说的是米游社账号登录状态异常时的提醒功能，在需要重新验证的时候推送一次提醒，实时便笺目前好像没有此功能？我到现在还没触发过。
