### ISSUE TITLE
[Feat]: 开机自启动功能

### ISSUE THREAD

**Issue by JasonLuo719** [DGP-Studio/Snap.Hutao#265]
### Windows 版本

19042.1706

### Snap Hutao 版本

1.2.5.0

### 问题分类

游戏启动

### 发生了什么？

希望增加开机自启动功能

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
你管这叫BUG？

**Comment by Masterain98** [comment]
![image](https://user-images.githubusercontent.com/10614984/204123171-2e18005b-94a1-426f-9b77-dedebde35bb4.png)

8803704
