### ISSUE TITLE
胡桃祈愿界面多uid切换困难

### ISSUE THREAD

**Issue by Mrwang101** [DGP-Studio/Snap.Hutao#268]
### Windows 版本

22H2 22621.819

### Snap Hutao 版本

1.2.5.0

### 问题分类

祈愿记录

### 发生了什么？

胡桃祈愿界面切换uid查看不同账号祈愿记录时，切换困难，鼠标找不到想切换uid的焦点[相关视频链接](https://share.weiyun.com/lgwOQ2U8)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
https://hut.ao/FAQ/most-frequent-questions.html#%E6%97%A0%E6%B3%95%E5%88%87%E6%8D%A2%E8%87%B3%E5%85%B6%E4%BB%96%E7%A5%88%E6%84%BF%E8%AE%B0%E5%BD%95%E5%AD%98%E6%A1%A3
