### ISSUE TITLE
[Feat]: 像snap genshin一样获取自己uid的全部角色数据

### ISSUE THREAD

**Issue by xiazhongyv** [DGP-Studio/Snap.Hutao#269]
### 你想要实现或优化的功能？

目前只能获取角色橱窗展示的八个角色，而且必须要公开角色橱窗的详细信息。感觉snap genshin的玩家查询功能，能够直接在一个页面查看全部角色的天赋武器圣遗物，确定接下来的养成方案，十分方便，是否能在Snap Hutao实现呢？

**Comment by Lightczx** [comment]
impl internally
