### ISSUE TITLE
[Feat]: 我应该如何找到并删除剩下的那部分文件

### ISSUE THREAD

**Issue by AkutaZehy** [DGP-Studio/Snap.Hutao#270]
### 你想要实现或优化的功能？

![image](https://user-images.githubusercontent.com/42381419/204216266-1f574228-e633-4861-9f1a-fa059befaac6.png)

如题，因为不再玩原神了所以想彻底卸载这个工具，因为注意到安装工具有说这么一句就提个问。

**Comment by Lightczx** [comment]
%userprofile%/Documents/Hutao

Schtasks SnapHutaoDailyNoteRefreshTask
