### ISSUE TITLE
[Feat]: stoken获取祈愿记录后自动或手动将链接复制到剪贴板

### ISSUE THREAD

**Issue by gszshdzz** [DGP-Studio/Snap.Hutao#271]
### 你想要实现或优化的功能？

如标题，我有时候会把记录导入到其他位置（寻空，非小酋等，寻空上传云端时必须要有有效链接），希望能将请求到的链接复制，每次都要抓包太麻烦了

**Comment by Masterain98** [comment]
请使用祈愿导出功能
Ref: [统一可交换祈愿记录标准 v2.3](https://uigf.org/standards/UIGF.html)

**Comment by gszshdzz** [comment]
> 请使用祈愿导出功能 Ref: [统一可交换祈愿记录标准 v2.3](https://uigf.org/standards/UIGF.html)

某些应用要求必须使用链接

**Comment by AdminRoc** [comment]
1.你应该给你提到的软件发issue
2.祈愿记录并不是不能导出的
3.胡桃可以查看祈愿记录
4.别的软件的UIGF格式祈愿记录，你可以导入到胡桃

**Comment by Lightczx** [comment]
@Scighost FYI
