### ISSUE TITLE
[Bug]: 角色资料武器资料的等级下拉菜单显示问题

### ISSUE THREAD

**Issue by TendernessAura** [DGP-Studio/Snap.Hutao#276]
### Windows 版本

22622.598

### Snap Hutao 版本

1.2.6.0

### 问题分类

用户界面

### 发生了什么？

第一次点击不显示90级选项，必须重新点一次下拉菜单才会显示90级

### 你期望发生的行为？

第一次点击出现所有等级选项

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
你不觉得这个菜单可以滚动么

**Comment by TendernessAura** [comment]
当然可以滚动啦，第一次点击滚不动，重新点一下才行

**Comment by Lightczx** [comment]
我认为这个是微软的问题

**Comment by TendernessAura** [comment]
😄没事，这个影响也不大
