### ISSUE TITLE
[Bug]:实时便签显示异常

### ISSUE THREAD

**Issue by ame-code** [DGP-Studio/Snap.Hutao#277]
### Windows 版本

19041.208

### Snap Hutao 版本

1.2.6.0

### 问题分类

实时便笺

### 发生了什么？

实时便签只显示了各种图标，数字都消失了，使用第一次的时候显示正常，之后就出问题了

![Snipaste_2022-11-30_17-20-07](https://user-images.githubusercontent.com/71199825/204757617-60bf9783-f3f3-4f45-b856-97d40125fb9a.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by Lightczx** [comment]
点下刷新

**Comment by ame-code** [comment]
点多少次都没效果
![Snipaste_2022-11-30_17-41-55](https://user-images.githubusercontent.com/71199825/204761925-21145f38-042e-4134-9f5e-5d1aeb056b4e.png)

**Comment by Lightczx** [comment]
把你正在使用的cookie发给1686188646@qq.com

**Comment by ame-code** [comment]
> 把你正在使用的cookie发给 [1686188646@qq.com](mailto:1686188646@qq.com)
已发送

**Comment by Lightczx** [comment]
没看见

**Comment by Lightczx** [comment]
进群反馈吧

**Comment by ame-code** [comment]
> 进群反馈吧

从群里过来的

**Comment by ame-code** [comment]
> 1686188646@qq.com

又发一次

**Comment by ame-code** [comment]
把账号删了重登解决了
