### ISSUE TITLE
[Bug]: 竖屏放大时，顶部会有一条灰线

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#278]
### Windows 版本

22623.1020

### Snap Hutao 版本

1.2.5.0

### 问题分类

用户界面

### 发生了什么？

竖屏使用时，点击全屏放大会出现如图顶部情况，出现灰色条
![image](https://user-images.githubusercontent.com/2825342/204901492-1ef2e135-f4d2-4b51-ad6a-9a0b4ff6f451.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

是

### 我确认没有他人提出相同或类似的问题

是

### 我确认该问题没有在文档中解释

是

**Comment by AdminRoc** [comment]
- 1.你的版本低于最新版本
- 2.此属微软UI的显示，软件本身不可能有这种现象
