### ISSUE TITLE
[Artifact Rating] 提纳里

### ISSUE THREAD

**Issue by fuchen828** [DGP-Studio/Snap.Hutao#279]
### 评分细则

|项目|评分权重(0-100)|
|-----|-----|
|角色名称| 提纳里 |
|生命值|  0 |
|攻击力|  75 |
|防御力|  0 |
|暴击率|  100 |
|暴击伤害|  100 |
|元素精通|  75 |
|充能效率|  55 |
|治疗加成|  0 |
|元素伤害|  100 |

### 我确认当前没有其它的该角色的圣遗物评分细则建议

是

### 我确认已设置合适的标题

是

### 我确认已完整填写表格

是

**Comment by Lightczx** [comment]
下版本并入
