### ISSUE TITLE
[Feat]: 希望祈愿记录能和SnapGenshin一样显示"距上个五|四星抽数"

### ISSUE THREAD

**Issue by qiuyue0** [DGP-Studio/Snap.Hutao#284]
### 你想要实现或优化的功能？

![image](https://user-images.githubusercontent.com/18420831/206183402-fd82d614-9896-4e93-97ef-618b665edef1.png)

**Comment by xiazhongyv** [comment]
这个应该是已经实现了吧，抽数下面有黄色和紫色的进度条，进度条后面跟着的数字就是

**Comment by qiuyue0** [comment]
> 这个应该是已经实现了吧，抽数下面有黄色和紫色的进度条，进度条后面跟着的数字就是

可能是我没
