### ISSUE TITLE
[Bug]: 图片缓存文件夹打开时报错

### ISSUE THREAD

**Issue by yamiyamiiiiiiiii** [DGP-Studio/Snap.Hutao#289]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22000.1219

### Snap Hutao 版本

1.2.6.0

### 问题分类

胡桃数据库

### 发生了什么？

大部分图片数据无法显示，点击设置中的【打开 缓存 文件夹】按钮后，进入卡顿状态并于数秒后闪退程序。

### 相关的崩溃日志

[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10202650/Log.zip)

抱歉  貌似上传文件格式有限制，烦请多进行一步解压操作

**Comment by yamiyamiiiiiiiii** [comment]
> A06A6D1C141D5180D709E77031D50B76

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/files/10081999/network-diagnosis-hutao.zip

运行这个程序，并将最终输出的报告提交

**Comment by yamiyamiiiiiiiii** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/files/10081999/network-diagnosis-hutao.zip
> 
> 运行这个程序，并将最终输出的报告提交

抱歉，不清楚什么原因，当我直接打开之后就会显示这个问题，而当我使用管理员模式运行程序则会直接闪退消失。
是我的网络存在问题吗？

[Snipaste_2022-12-12_00-39-08.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10202709/Snipaste_2022-12-12_00-39-08.zip)

图片上传github也有问题....  难不成真是我网络问题？   还必须得压缩才能上传

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by Masterain98** [comment]
> > https://github.com/DGP-Studio/Snap.Hutao/files/10081999/network-diagnosis-hutao.zip
> > 运行这个程序，并将最终输出的报告提交
> 
> 抱歉，不清楚什么原因，当我直接打开之后就会显示这个问题，而当我使用管理员模式运行程序则会直接闪退消失。 是我的网络存在问题吗？
> 
> [Snipaste_2022-12-12_00-39-08.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10202709/Snipaste_2022-12-12_00-39-08.zip)
> 
> 图片上传github也有问题.... 难不成真是我网络问题？ 还必须得压缩才能上传

@yamiyamiiiiiiiii 在命令行中直接执行 `ping hutao-metadata.snapgenshin.com` 是什么结果？

**Comment by yamiyamiiiiiiiii** [comment]
ping请求超时，但是我网页直接访问的话是有结果的，403

**Comment by Masterain98** [comment]
> ping请求超时，但是我网页直接访问的话是有结果的，403

按理来说是可以ping通的，可以实现将本机的DNS服务器换一下，看能不能解决

e.g. [https://www.dnspod.cn/products/publicdns](https://www.dnspod.cn/products/publicdns)

**Comment by yamiyamiiiiiiiii** [comment]
> > ping请求超时，但是我网页直接访问的话是有结果的，403
> 
> 按理来说是可以ping通的，可以实现将本机的DNS服务器换一下，看能不能解决
> 
> e.g. https://www.dnspod.cn/products/publicdns

好的，应该是路由器的clash导致的这个问题，现在已经解决了，结果报告见附件
[hutao-network-log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/10206778/hutao-network-log.txt)

**Comment by yamiyamiiiiiiiii** [comment]
> > > ping请求超时，但是我网页直接访问的话是有结果的，403
> > 
> > 
> > 按理来说是可以ping通的，可以实现将本机的DNS服务器换一下，看能不能解决
> > e.g. https://www.dnspod.cn/products/publicdns
> 
> 好的，应该是路由器的clash导致的这个问题，现在已经解决了，结果报告见附件 [hutao-network-log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/10206778/hutao-network-log.txt)

我指的不是这个问题啊，我是说ping超时的问题  抱歉表达失误，我重新卸载胡桃并且重新安装之后，仍然会出现我开头所描述的那些问题，并没有得到解决

**Comment by Lightczx** [comment]
@Masterain98

**Comment by Masterain98** [comment]
试一下使用浏览器访问 `https://static.snapgenshin.com/HeroImageLogo.png` 能否正常下载图片。
另外客户端上有没有报错？

**Comment by yamiyamiiiiiiiii** [comment]
访问该页面可成功下载图片，客户端仅一处位置访问时会产生报错信息，见附件
[报错图片.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10213367/default.zip)

**Comment by yamiyamiiiiiiiii** [comment]
![权限](https://user-images.githubusercontent.com/45311091/207270159-8171eb3e-efcf-453c-9c41-62ee0d108de7.png)
在询问群友之后，我得到了这个路径，并且将权限设置为图中所示，仍然会出现该问题。
![image](https://user-images.githubusercontent.com/45311091/207270858-d19aa5fe-0453-42a1-ab7e-063165efab1e.png)
删除图中文件夹，再次打开胡桃后，会自动创建此文件夹，但仍然会出现问题

**Comment by Lightczx** [comment]
有开loopback么？

**Comment by yamiyamiiiiiiiii** [comment]
根据群友回答，我找到了图中的文件夹，并将权限设置为如图，重启胡桃后，仍旧出现此问题。
![image](https://user-images.githubusercontent.com/45311091/207271928-8bab0bed-e018-45b2-a813-93f6c392aff9.png)
将图二中文件夹删除后，重启胡桃，能够看到文件夹被创建，但仍然无图片显示，且文件夹大小为0
![image](https://user-images.githubusercontent.com/45311091/207272360-d146d864-1a72-4f99-889b-8f28ad6b3e89.png)

**Comment by yamiyamiiiiiiiii** [comment]
> 有开loopback么？

我不清楚此设置，应该是没有，或者有什么方法检查吗？

**Comment by yamiyamiiiiiiiii** [comment]
另外，我抓取到了点击打开图片缓存文件夹时闪退的log上传，不知是否对你们有所帮助
![image](https://user-images.githubusercontent.com/45311091/207274719-b4ecf868-dd05-485f-9b00-91ade75ec095.png)
