### ISSUE TITLE
[Feat]: 筛选的模式希望能考虑变成过滤类型的

### ISSUE THREAD

**Issue by kan846** [DGP-Studio/Snap.Hutao#29]
### 你想要实现或优化的功能？

从选择的角度来看，目前提供的选项都是基于各种方式的筛选，在个人使用中，大概率都是查询一个角色，所以，依据元素，国家，体型，武器，星级中的一个元素来进行筛选的，重复点击有点麻烦，如果后续需要多个角色进行对比，添加一个对比功能，可能也会让人使用更舒服，希望能考虑一下
另外，祝中秋节快乐
![image](https://user-images.githubusercontent.com/63768657/189484891-b7001530-9ec6-4a77-8875-8d6b600a3c84.png)

**Comment by Strelitzia-Khazan** [comment]
关于筛选方面您的意思是否为 通过一次勾选操作获得想要的“属性”

**Comment by kan846** [comment]
是的，比如选择火属性神之眼角色，就只要点击一次就可以了

**Comment by kan846** [comment]
多个角色需要对比的话可以考虑添加一个对比功能
