### ISSUE TITLE
[Bug]: 养成计划会闪退

### ISSUE THREAD

**Issue by kaerdengdeng** [DGP-Studio/Snap.Hutao#295]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.963

### Snap Hutao 版本

1.2.10.0

### 设备 ID

61B5C5E5100F76C7C14F3E79C3A39A40

### 问题分类

养成计算

### 发生了什么？

会闪退

### 你期望发生的行为？

别闪退

### 相关的崩溃日志

[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10235176/Log.zip)

**Comment by Lightczx** [comment]
#294
