### ISSUE TITLE
12月下半深渊数据未显示

### ISSUE THREAD

**Issue by fuchen828** [DGP-Studio/Snap.Hutao#297]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22000.1098

### Snap Hutao 版本

1.2.12.0

### 问题分类

胡桃数据库

### 发生了什么？

上传本期深渊数据后，本期数据未刷新，仍显示上期数据，新角色流浪者、珐露珊的持有数据未显示

**Comment by Lightczx** [comment]
fixed internally
