### ISSUE TITLE
关于启动器帧率解锁的建议

### ISSUE THREAD

**Issue by RYX-3212103383** [DGP-Studio/Snap.Hutao#298]
### 你想要实现或优化的功能？

帧率解锁的设置每次重新打开默认关闭而且最大帧都会重置为60，希望保留设置的状态和最大帧并只在管理员启动时应用，这样每次管理员启动后不必要每次都点开启功能和调最大帧。
ps：管理员启动的ps1文件打包成exe对大部分人更实用

**Comment by Lightczx** [comment]
在更改设置后是否启动过游戏？@RYX-3212103383
