### ISSUE TITLE
[Bug]: 卸载后扔有进程残留。

### ISSUE THREAD

**Issue by Kuwaaaa** [DGP-Studio/Snap.Hutao#299]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

10944.2364

### Snap Hutao 版本

1.2.0

### 问题分类

安装和环境

### 发生了什么？

每隔十分钟就会弹出来这个，卸载了或者卸载了重装再卸载都还在。
![@LWC2KH2880NQKG { RSBQK](https://user-images.githubusercontent.com/56498185/208096040-e484fe1d-1135-4beb-8e76-cb21c59f7e62.png)

**Comment by Lightczx** [comment]
#202
