### ISSUE TITLE
[Bug]: 祈愿记录页面空白

### ISSUE THREAD

**Issue by IshiKura-a** [DGP-Studio/Snap.Hutao#30]
### Windows 版本

22000.856

### Snap Hutao 版本

1.0.33.0

### 发生了什么？

打开祈愿界面空白，其余界面正常。
![image](https://user-images.githubusercontent.com/51883990/189511518-d92153c0-3b40-4d0b-a2fc-3fab991edbfe.png)
![image](https://user-images.githubusercontent.com/51883990/189511525-c7814bbc-a3b0-4333-8a10-a70958870d19.png)

### 你期望发生的行为？

看见祈愿记录/查询祈愿记录的操作页面

**Comment by Lightczx** [comment]
祈愿记录尚在开发中
