### ISSUE TITLE
[Feat]: 希望早日支持自动更新

### ISSUE THREAD

**Issue by FlyInWind1** [DGP-Studio/Snap.Hutao#300]
### 你想要实现或优化的功能？

看文档，似乎是要上架微软商城就可以支持自动更新，那希望早日上架吧。

**Comment by FeletexGee** [comment]
毕竟加了没用的按钮没用的选项，说明已经挖好坑了（

**Comment by AdminRoc** [comment]
上架的应用有限制的，起码要阉割掉部分功能  -.-
但是有一个更新推送提醒应该就够了，下载更新也不麻烦，这个想必目前已经在计划中了
