### ISSUE TITLE
[Bug]: 米游社签到提示未登录

### ISSUE THREAD

**Issue by wuqingcn520** [DGP-Studio/Snap.Hutao#302]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

win11企业版 22h2 22621.963

### Snap Hutao 版本

1.2.13.0

### 设备 ID

F3BC44962087D641128825A33BA1D2D3

### 问题分类

签到

### 发生了什么？

打开签到界面时会弹出账号未登录的提示，已在snap hutao中登录了米游社账号

**Comment by Lightczx** [comment]
重新添加账号
