### ISSUE TITLE
胡桃数据库&深渊统计

### ISSUE THREAD

**Issue by EternityFOR** [DGP-Studio/Snap.Hutao#303]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.963

### Snap Hutao 版本

1.2.13.0

### 设备 ID

C3904867330D19F1DEB0D1EE2EA40628

### 问题分类

胡桃数据库

### 发生了什么？

上传深渊数据点了上传之后没反应，点深渊统计有时候鼠标图标会开始转两下然后闪退。

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 C3904867330D19F1DEB0D1EE2EA40628

**Comment by Masterain98** [comment]
@dgp-bot 拉取日志

**Comment by Lightczx** [comment]
@EternityFOR 重新添加账号

**Comment by EternityFOR** [comment]
> 

一样，没区别
