### ISSUE TITLE
[建议]: 我在旧版本的原神时期存储了原神的旧抽卡文件（output_log.txt），希望导入

### ISSUE THREAD

**Issue by LoCCai** [DGP-Studio/Snap.Hutao#304]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.963

### Snap Hutao 版本

1.2.13.0

### 问题分类

祈愿记录

### 发生了什么？

无法导入旧版PC的抽卡缓存数据

### 你期望发生的行为？

成功导入旧版的原神抽卡数据，并可以转换为统一格式，方便后期统计抽卡分析并与其他程序交互

**Comment by Lightczx** [comment]
output_log.txt 是日志文件，不包含抽卡记录
