### ISSUE TITLE
[Bug]: 实时便笺失效

### ISSUE THREAD

**Issue by muzhixiamunai** [DGP-Studio/Snap.Hutao#305]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.2.13.0

### 设备 ID

E880382E9C8859153AFAB838B4E69F49

### 问题分类

实时便笺

### 发生了什么？

实时便笺除了名字都不显示

**Comment by muzhixiamunai** [comment]
> ### 检查清单
> * [x]  我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
> * [x]  我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
> * [x]  我确认没有其他人已经提出了相同或类似的问题
> * [x]  我会在下方的表单中附上充足的信息以帮助开发人员确定问题
> 
> ### Windows 版本
> 19044.2364
> 
> ### Snap Hutao 版本
> 1.2.13.0
> 
> ### 设备 ID
> E880382E9C8859153AFAB838B4E69F49
> 
> ### 问题分类
> 实时便笺
> 
> ### 发生了什么？
> 实时便笺除了名字都不显示
> 
> ### 你期望发生的行为？
> _No response_
> 
> ### 相关的崩溃日志
> _No response_

**Comment by muzhixiamunai** [comment]
![S8H`WTYRH`8Z4PNRR9O5Q@M](https://user-images.githubusercontent.com/55607755/208337877-204dfe6a-0405-422c-9322-3b09843b31e3.png)

**Comment by Lightczx** [comment]
@muzhixiamunai 点击立即刷新会有提示么

**Comment by muzhixiamunai** [comment]
> @muzhixiamunai 点击立即刷新会有提示么

什么都不会发生

**Comment by muzhixiamunai** [comment]
> @muzhixiamunai 点击立即刷新会有提示么

什么都没有

**Comment by Lightczx** [comment]
拉取日志 E880382E9C8859153AFAB838B4E69F49

**Comment by Lightczx** [comment]
重启删除重新添加看看@muzhixiamunai

**Comment by muzhixiamunai** [comment]
> 重启删除重新添加看看@muzhixiamunai

![BZVXB4@2COI L
)QDDHIAT](https://user-images.githubusercontent.com/55607755/208344068-93464a8d-47e0-46d8-b50b-9d46103d91f7.png)
没有变化，还是说要删除工具箱重新下载

**Comment by Lightczx** [comment]
删除后重启过么

**Comment by muzhixiamunai** [comment]
> 删除后重启过么

重启电脑和重启软件都试过了

**Comment by Lightczx** [comment]
麻烦把所有cookie私发给我的邮箱

**Comment by muzhixiamunai** [comment]
> 麻烦把所有cookie私发给我的邮箱

发了

**Comment by Lightczx** [comment]
v1 cookie已经不再受到支持，请删除用户，重新添加
