### ISSUE TITLE
养成计划添加角色/武器优化

### ISSUE THREAD

**Issue by wuqingcn520** [DGP-Studio/Snap.Hutao#307]
### 背景与动机

养成计划中添加角色/武器时按钮在别的页面，不看文档很难直接使用该功能
在养成计划中添加一条提示 可以从''我的角色''中选择一些自己有的角色

### 想要实现或优化的功能

在养成计划中添加一条提示
可以从''我的角色''中选择一些自己有的角色/武器进行计算

**Comment by Lightczx** [comment]
impl internally
