### ISSUE TITLE
[Bug]: 椰羊UIAF1.1成就记录导入闪退

### ISSUE THREAD

**Issue by linger6580** [DGP-Studio/Snap.Hutao#31]
### Windows 版本

22000.856

### Snap Hutao 版本

1.0.33.0

### 发生了什么？

操作从UIAF文件导入成就记录时（成就记录来源为椰羊导出），提示导入成就中，1-2秒后直接闪退；尝试使用管理员模式运行hutao，会在点击导入UIAF文件时直接闪退

**Comment by Lightczx** [comment]
能否提供一下导入的成就文件

**Comment by linger6580** [comment]
> 能否提供一下导入的成就文件 %HOMEPATH%/Documents/Hutao/Log.db 文件也需要提供一下

可以的，但是github如何上传附件？

**Comment by Lightczx** [comment]
已经定位问题并修复

**Comment by linger6580** [comment]
> 已经定位问题并修复

请问修复后的版本哪里下载？

**Comment by Lightczx** [comment]
> > 已经定位问题并修复
> 
> 请问修复后的版本哪里下载？

慢慢等

**Comment by gszshdzz** [comment]
椰羊可以不用导出文件直接导入到胡桃里
