### ISSUE TITLE
[Bug]: FPS解锁后，心海普攻导致游戏卡顿

### ISSUE THREAD

**Issue by Askwind** [DGP-Studio/Snap.Hutao#310]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2251

### Snap Hutao 版本

1.2.6

### 问题分类

游戏启动器

### 发生了什么？

开启FPS解锁功能后（开启144帧），心海的普攻会导致游戏画面奇卡无比。

关闭此功能后心海普攻不会导致游戏卡顿。

### 你期望发生的行为？

1.能否从启动器层面解决这个卡顿问题

2.如不能，就请在开启功能时提示用户

**Comment by Askwind** [comment]
打开游戏中的“垂直同步”可以解决这个问题，望周知！

**Comment by Lightczx** [comment]
。打开垂直同步相当于关闭了解锁帧率，当然能解决这个问题。

**Comment by hllyd** [comment]
> 

游戏内设置的垂直同步功能好像没有任何效果，至少我不管开关这个选项帧数都是解锁的，同时此bug也都会触发

**Comment by Askwind** [comment]
> > 
> 
> 游戏内设置的垂直同步功能好像没有任何效果，至少我不管开关这个选项帧数都是解锁的，同时此bug也都会触发
> 
> 我的hutao版本是1.2.19.0

是我测试不够，确实还是有这个情况。开了垂直同步，我心海也就前2次普攻不卡，第三次又开始卡了，还是有BUG。建议用心海的朋友还是先不要开高帧率解锁功能了。

**Comment by hllyd** [comment]
> 是我测试不够，确实还是有这个情况。开了垂直同步，我心海也就前2次普攻不卡，第三次又开始卡了，还是有BUG。建议用心海的朋友还是先不要开高帧率解锁功能了。

3.4这个bug好像消失了
