### ISSUE TITLE
[Bug]: 实时便签无法显示角色名称

### ISSUE THREAD

**Issue by 4O4NtFd** [DGP-Studio/Snap.Hutao#311]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.2.13.0

### 设备 ID

AAB14AD6999577C9D61DE5BB73C5441D

### 问题分类

实时便笺

### 发生了什么？

![QQ截图20221222094743](https://user-images.githubusercontent.com/49442853/209037115-486a133b-7425-4818-8e0c-9ffa4ce56e05.png)
无法显示用户名。
重新添加后能正常显示用户名，但当重启胡桃工具箱后无法显示用户名。

**Comment by Lightczx** [comment]
更新到1.2.14
