### ISSUE TITLE
[Feat]: 有望支持真正的全屏模式？

### ISSUE THREAD

**Issue by NoroHime** [DGP-Studio/Snap.Hutao#312]
### 背景与动机

原神预留了启动参数
`-window-mode exclusive`
这将启用独占全屏而非默认的无边框全屏
启用独占全屏模式后可以降低后台性能消耗，并让独显直接输出游戏画面，有效降低游戏的输入延迟和提升FPS
独占全屏模式还可使得NIS _(Nvidia Image Scaling, Nvidia用于对标FSR的技术)_ 在NVIDIA控制面板轻松打开，尽管在原神卡通渲染上不是很惊人，但配合FSR2.0低渲染倍率下效果非常不错

### 想要实现或优化的功能

可以提供自定义原神启动参数，或者直接提供独占全屏的选项，这么好的东西，为什么不呢？

**Comment by Lightczx** [comment]
全屏模式会在下个版本修正
