### ISSUE TITLE
总是提示角色橱窗尚未开启,可是我明明开启了

### ISSUE THREAD

**Issue by fanyuanhang** [DGP-Studio/Snap.Hutao#313]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.963

### Snap Hutao 版本

1.2.15.0

### 问题分类

角色信息面板

### 发生了什么？

如标题所示

**Comment by Lightczx** [comment]
游戏内橱窗，非米游社

**Comment by fanyuanhang** [comment]
> 游戏内橱窗，非米游社

![image](https://user-images.githubusercontent.com/45005609/209462092-16baba92-403b-4065-8a82-65d80a2d8db2.png)
不是这个吗?开了的

**Comment by Lightczx** [comment]
那你补上设备id

**Comment by fanyuanhang** [comment]
> 那你补上设备id

F34C7D1402130E6C17B3060E7AC728A8这个嘛

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 F34C7D1402130E6C17B3060E7AC728A8

**Comment by fanyuanhang** [comment]
> @dgp-bot 拉取日志 F34C7D1402130E6C17B3060E7AC728A8

大哥,这日志啥意思呀

**Comment by Lightczx** [comment]
你确定你选定的账号角色是正确的么

**Comment by fanyuanhang** [comment]
> 你确定你选定的账号角色是正确的么
对的嘞,我就一个账号

**Comment by Lightczx** [comment]
把cookie私发到我的邮箱

**Comment by Lightczx** [comment]
近期Enka服务不稳定
