### ISSUE TITLE
[Bug]: 胡桃启动游戏后，游戏切屏卡死

### ISSUE THREAD

**Issue by QianMoQAQ** [DGP-Studio/Snap.Hutao#316]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

25267.1000

### Snap Hutao 版本

1.2.16.0

### 设备 ID

BCCF0EF96E14EB216FA7220E856E6C10

### 问题分类

游戏启动器

### 发生了什么？

启动游戏后 ，游戏切屏会卡死 ，我用sg同样的的设置启动游戏 ，切屏就不会卡死，

**Comment by Lightczx** [comment]
fixed internally
