### ISSUE TITLE
养成计划功能无法使用

### ISSUE THREAD

**Issue by zhuqingmeipie** [DGP-Studio/Snap.Hutao#317]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.2.16.0

### 设备 ID

6FE3FE7350A5617A20D9CCE5388F89B1

### 问题分类

养成计算器

### 发生了什么？

我按照胡桃工具箱里的功能指南操作我电脑上的胡桃里的养成计划功能，但是我在角色资料里点击养成计算后，养成计划里并没有出现相应的角色养成计划表，一片空白，我在我的角色里使用养成计算，添加到养成计划里后，养成计划里面依旧是一片空白。

### 你期望发生的行为？

按照功能指南里的操作后，养成计划里会出现相应的角色养成计划表

**Comment by Lightczx** [comment]
是否选中了账号与角色
是否选中了养成计划
