### ISSUE TITLE
[Bug]: 1.2.16.0版本更新后有关全屏启动的问题

### ISSUE THREAD

**Issue by MayPoxN** [DGP-Studio/Snap.Hutao#318]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.1706

### Snap Hutao 版本

1.2.16.0

### 设备 ID

96BC614963D2330A4918C797C6304741

### 问题分类

游戏启动器

### 发生了什么？

在这个版本开启了全屏启动之后切屏会导致显示器黑屏以下，并且在使用QQ截图之后会导致游戏卡死。
![image](https://user-images.githubusercontent.com/81094897/209522752-79e205ad-c41a-4f13-a982-dff3f2a3a9d3.png)

### 你期望发生的行为？

如果使用老版本或者默认的启动方式就不会出现这类问题。
或者关闭全屏启动，使用窗口化启动，之后使用系统的alt+enter进行全屏化也不会出现此类问题。

### 相关的崩溃日志

hutao没有崩溃，但是游戏崩溃了

**Comment by Lightczx** [comment]
fixed internally
