### ISSUE TITLE
[Bug]: 无法刷新和展示祈愿记录

### ISSUE THREAD

**Issue by lvwenzhuo2003** [DGP-Studio/Snap.Hutao#319]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

25267.1000

### Snap Hutao 版本

1.2.18.0

### 设备 ID

AF83E94A05310773403EC2725A8BDDEE

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录过多时（6082至6157之间的某个值）程序无法正常处理祈愿记录，表现为：
1. 记录刷新完成时，程序不会主动刷新其展示的记录
2. 如果此时关闭程序再次启动，程序将不会展示任何的祈愿记录（0都不显示）
3. 程序在任何时候都可以正常的导出祈愿记录至JSON文件

![image](https://user-images.githubusercontent.com/51859807/209642224-f1d4dac0-af6c-4bc7-b503-f0003d3aa7e3.png)

### 你期望发生的行为？

程序应当正常的展示祈愿记录

### 相关的崩溃日志

[新建文件夹.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10307132/default.zip)

**Comment by BanshaTang** [comment]
同样问题，并且导出的json文件似乎有数据丢失。今天刚更新的池子捞了雷神，但是json文件里没有对应记录，其前后的祈愿记录都有

**Comment by GuoZhihang** [comment]
[同样的问题，但是只出现在一个uid身上，尝试删除存档、重新导入UIGF.json文件后，数据会停留在上一次切换的有效账号。重启应用后出现上面图中的情况。]
设备ID:217D19EA1A070F5C85490D4F16A4430E
胡桃版本：1.2.16.0
![image](https://user-images.githubusercontent.com/47210136/209690868-9113ec07-056d-4c9f-bed1-97b79169bf20.png)
![image](https://user-images.githubusercontent.com/47210136/209690933-cef01b87-2b19-42c1-a263-b4469038f14a.png)

**Comment by DcDarkChen** [comment]
同样问题，尝试各种方式刷新，导出JSON数据文件损坏，界面无显示
![image](https://user-images.githubusercontent.com/100990499/209692452-d0e54a3b-3ccf-4203-866c-9fc5dcd6729e.png)

设备ID：BBD1B2C3A90326BBB5465925662DB41C

（如果着急可以暂用DGP.Genshin）
![image](https://user-images.githubusercontent.com/100990499/209692576-b9e0cc01-575f-493a-b5c4-ac20f666708a.png)

**Comment by Lightczx** [comment]
fixed
