### ISSUE TITLE
Bug：程序在添加角色是无响应 闪退

### ISSUE THREAD

**Issue by misaka10384** [DGP-Studio/Snap.Hutao#32]
### Windows 版本

windows 11 版本: 25197.1000

### Snap Hutao 版本

1.0.33.0

### 发生了什么？

在使用cookie添加角色信息时程序会未响应 然后崩溃  在崩溃重启后角色依旧处于未添加状态  
有概率程序卡死 任务管理器都无法结束 直到重启  
![image](https://user-images.githubusercontent.com/61707010/190691026-184b231e-b8b8-4e35-b79f-08623bcf29d6.png)
还有 你的崩溃日志信息位置  [%HOMEPATH%/Documents/Hutao/Log.db] 地址进不去 我把 "/" 改成 "\"也进不去
至于日志 ....
[Hutao.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9586006/Hutao.zip)
我整个压缩给你了.jpg

### 相关的崩溃日志 位于 %HOMEPATH%/Documents/Hutao/Log.db

```shell
[Hutao.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9586006/Hutao.zip)
```

**Comment by Lightczx** [comment]
已知问题，已经修复
