### ISSUE TITLE
[Bug]: 祈愿记录不显示

### ISSUE THREAD

**Issue by LongkunHe** [DGP-Studio/Snap.Hutao#322]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.2.16.0

### 问题分类

祈愿记录

### 发生了什么？

12月27日晚18点雷神池更新后，我发现胡桃工具箱能够读取到我最新的抽卡记录（读取阶段能看到抽到的物品的小图标），但无法在记录界面更新。
删除后，导入之前保存的UIGF文件，也无法显示，整个界面是空白。如下图。
![image](https://user-images.githubusercontent.com/75229278/209691286-6abaa23a-1014-4b9d-b973-8ebffbcadb03.png)

**Comment by Lightczx** [comment]
fixed
