### ISSUE TITLE
[Feat]: 养成计划体力预估

### ISSUE THREAD

**Issue by FlandiaYingman** [DGP-Studio/Snap.Hutao#323]
### 背景与动机

目前的养成计划只提供了：

- **材料清单**：计算角色从目前练度，养成到预计练度所需要的材料。
- **背包物品**：提供背包物品的统计。

（似乎**背包物品**和**材料清单**没有任何功能上的关联？例如：我的背包里有某个养成计划中所需的材料，不会改变材料清单上的数字。不确定是不是我使用方法有问题）
![image](https://user-images.githubusercontent.com/9929037/209750819-3bce6b1e-0315-421e-9d56-8adcf62e1718.png)
![image](https://user-images.githubusercontent.com/9929037/209750826-2a7976ea-1317-47a1-af7a-bd8f96a599ef.png)
![image](https://user-images.githubusercontent.com/9929037/209750834-a23a6cd8-68c6-43f3-8708-e4242b5a7b97.png)
如图所示，我已在背包里设置了这些材料，但没有反映在**材料清单**功能中。

作为一个用户，我希望**养成计划**功能能够提供一些具体的方案（如下所示）来养成角色。因为这样可降低用户的思考量或计算量，使养成过程更加便捷。

### 想要实现或优化的功能

“具体的方案”如下：

1. 在**材料清单**中，显示“_所需材料_ (_已有材料_/_总所需材料_)”，如"10 (19/29)“。这样可使用户更直观地看到还需刷取多少材料。
2. 在**材料清单**中，添加面向材料获取方式的面板，而不是面向材料本身的面板。例如，我仍需要 93 个 __「巧思」的哲学__，那么在该面板中，应显示仍需刷取 __精通秘境：妙语 Ⅳ 46 次 (920 树脂)__。（数字是随手填的）
3. 在**材料清单**，面向材料获取方式的面板中，标识它们的开放时间。例如：假设今天是周一，那么应显示 __（周二/周五/周日）精通秘境：妙语 Ⅳ 46 次 (920 树脂)__，并用灰色字体或是 disabled 效果来标识今天无法获得此种材料。

**Comment by FlandiaYingman** [comment]
有用的链接：[BOSS及秘境掉落数据统计](https://docs.google.com/spreadsheets/d/1RcuniapqS6nOP05OCH0ui10Vo3bWu0AvFbhgcHzTybY)

如果作者比较忙的话，我可以抽空写一个养成计划的原型

**Comment by Lightczx** [comment]
@FlandiaYingman 
需要不引入多余的第三方库：Google.OrTools

**Comment by FlandiaYingman** [comment]
@Lightczx 
从头实现线性规划稍显困难，我会试一下

**Comment by FlandiaYingman** [comment]
@Lightczx 
目前已经实现了无需第三方库的版本。然而，这么做会使运算时间上升到~20s左右。
目前，我的程序中包含了所有的合成配方（包括尘歌壶、食物等），经过测试，我认为是这些多余的配方拖慢了运算速度。
所以，你能提供一份胡桃启动器中，**养成计划=>背包物品**中所有养成材料的名称的列表吗？我会用它将多余的配方剔除。

![image](https://user-images.githubusercontent.com/9929037/210183227-d9016925-5ac5-494a-9702-333b51c0e329.png)
换句话说，我需要这个界面中材料的名称。

**Comment by Lightczx** [comment]
自己实现的线性规划更慢？算法有问题吧？不然时间应该差不多

**Comment by FlandiaYingman** [comment]
@Lightczx 
嗯，线性代数相关的算法需要矩阵运算的基础库支持才能写的更有效些。只用数组的话，实现简单的单纯形算法已经是我能力的极限了。
不过，慢十几秒有点夸张了，我猜想是许多无效约束造成的。我会同时试着在应用层面和算法层面剔除掉这些无用约束。

**Comment by Lightczx** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.numerics

**Comment by FlandiaYingman** [comment]
@Lightczx 
你发的那些仅支持特定大小的matrix（3x2）（4x4)，没办法做大型线性方程组的运算。

**Comment by Lightczx** [comment]
那就自己实现吧

**Comment by FlandiaYingman** [comment]
> 那就自己实现吧

能力有限，无法实现

**Comment by Lightczx** [comment]
能把具体的运算过程讲解一下么

**Comment by FlandiaYingman** [comment]
@Lightczx 

刚想讲解运算过程，在写的过程中发现了算法设计的问题。

你指出的“算法有问题”是对的😭。我为无上界的约束指定的上界是 `double.PositiveInfinity`，然而，直接在约束矩阵里去除上界更有效率些。

目前的运算速度：~ 1000 ms，相比于用第三方 native 库的 ~ 400 ms，我觉得时间上已经可以接受了。

纯 C# 实现已经推到 https://github.com/FlandiaYingman/Genshin.Planner.Demo 上了

**Comment by Lightczx** [comment]
目前没有办法获取秘境入口与秘境的对应关系
合成材料的元数据可以获取

**Comment by FlandiaYingman** [comment]
@Lightczx 

我 project 里的 `QuickType.DomainJson` 里有一个 `domainentrance`，对应着各秘境的秘境入口。

数据来源于这个 API：https://genshindb-ia.netlify.app/

```https://genshin-db-api.vercel.app/api/domains?
query=names&matchCategories=true&verboseCategories=true&resultLanguage=ChineseSimplified

**Comment by Lightczx** [comment]
元数据必须从ExcelBin 中解析，不接受外界的数据，我们必须对数据源具有控制权

**Comment by FlandiaYingman** [comment]
@Lightczx 

抱歉，ExcelBin 是什么？

如果无法获取秘境入口与秘境的对应关系，那么我认为跳过秘境入口名，直接显示秘境名也可以。因为我想大部分玩家都没有看到秘境入口名就能反应该刷哪个秘境的能力，大家都是点开某个材料然后跳转到秘境去的。

**Comment by Lightczx** [comment]
看了眼他的解析方式
https://github.com/theBowja/GenshinData-scripts/blob/main/extract/extractDomain.js
我觉得还是不能做秘境对应

**Comment by FlandiaYingman** [comment]
> 看了眼他的解析方式 https://github.com/theBowja/GenshinData-scripts/blob/main/extract/extractDomain.js 我觉得还是不能做秘境对应

只是没办法做秘境和秘境入口吗？有没有什么曲线救国的方式？

如果找不到方法的话就 close 吧

**Comment by Lightczx** [comment]
秘境的材料是可以做的，秘境入口不行

**Comment by Lightczx** [comment]
稍微描述一下算法吧

**Comment by FlandiaYingman** [comment]
@Lightczx 

求解线性规划用的是单纯形法，不赘述了。

### 关于怎么构造的线性规划

由于有合成功能的存在，简单地将需求材料数乘以秘境掉落期望数的算法是不完善的。因而，我们需要找到一个最优解，使得消耗总树脂最低，即最大程度地利用背包里的材料。

设 x1, x2, ..., xn 为线性规划的变量，我们用各变量代表一个独立的**行为**（刷秘境或合成）。所以，线性规划求解完毕后，各个变量的最优值即是我们想要的结果（某个秘境刷 n 次，某种材料合成 m 个，etc.）。特别地，有一个 stock 变量恒定为 1，它的作用是代表背包里的材料。

注意，由于个别材料（例如，突破宝石）有不止一个合成方式，我为每个合成方式都赋了一个独特的 ID（就是合成产物名字后面跟一个计数器而已）。不过我的算法还没实现 BOSS 和掉落产物的对应，所以赋 ID 这一步可以省略。

然后，设 c1, c2, ..., cm 为线性规划的约束，我们用各约束代表各材料。每个材料的表达式是对每个会产出该材料的**行为**乘以该**行为**产出材料的期望值求和。注意有些**合成行为**是消耗材料的，所以该行为产出负数个此材料。最后再加上背包的材料，它用 stock 变量（即 1）乘以背包材料的数量来表示。（实际上 stock 变量放到约束里就是一个常数项而已）

如果我们不需要这个材料，那么在这个约束中，我们使这个表达式大于等于 0，这样就不会有负数材料的出现；如果我们需要这个材料，那么在这个约束中，我们使这个表达式大于等于**需要材料数**。

最后，使最优化函数=各行为需要消耗的树脂的数量的和，我们要使最优化函数最小。然后求解，结果就出来了

### 例子

约束 c1 代表“高塔孤王的断片”

这个材料有三种获取方式：
- 变量 x1：炼武秘境：水光之城 Ⅲ
- 变量 x2：炼武秘境：水光之城 Ⅳ
- 变量 x3：合成“高塔孤王的断片”

以及一种消耗方式：
- 变量 x4：合成“高塔孤王的碎梦”

那么，构造一个表达式，使它表达我们“高塔孤王的断片”的数量：

```
“高塔孤王的断片” = 0.22*x1 + 0.64*x2 + 1*x3 - 3*x4 + 背包里已有“高塔孤王的断片”的数量
```

其中 0.22，0.64 是刷一次对应秘境掉落“高塔孤王的断片”的期望值，1\*x3 的意思是合成一次“高塔孤王的断片”可以获得 1 个“高塔孤王的断片”，- 3\*x4 的意思是合成一次“高塔孤王的碎梦”会消耗 3 个“高塔孤王的断片”。

由于线性规划中不允许常数项的出现，我们使 stock 变量恒为 1，然后把`背包里已有“高塔孤王的断片”的数量`变为`背包里已有“高塔孤王的断片”的数量*stock`。

所以，最后的约束 
```
c1: 0.22*x1 + 0.64*x2 + 1*x3 - 3*x4 + 背包里已有“高塔孤王的断片”的数量*stock >= 需要的“高塔孤王的断片”的数量
```

### 一些 Trick

- 设高等级的秘境比低等级的秘境消耗的树脂要稍微少一些（0.01），这样规划程序不会在刷任意一个秘境都满足条件的情况下刷低等级的秘境。
- 设合成也会消耗少量树脂（0.01）这样规划程序不会瞎合成不需要的材料。

这些树脂仅在最优化函数中表达，等我们最后计算需要多少树脂的时候，对 x1, x2, ..., xn 乘以对应行为需消耗的真实树脂求和，重新计算一遍就可以了。

**Comment by Lightczx** [comment]
低等级的秘境应该无论如何材料掉的都比高等级的少吧

**Comment by FlandiaYingman** [comment]
@Lightczx 

对，我添加这个只是为某些可能尚未解锁高等级秘境的新手考虑。如果不考虑他们，低等级秘境可以删掉。

**Comment by Lightczx** [comment]
有个问题需要注意
* BOSS与天赋/武器本的掉率是非官方的数据
不精确的数据是难以接受的

**Comment by FlandiaYingman** [comment]
> 有个问题需要注意
> 
> * BOSS与天赋/武器本的掉率是非官方的数据
> 
> 不精确的数据是难以接受的

个人认为如：

- 圣遗物评分的算法
- 深渊统计

等系统的数据，跟此掉落数据一样是玩家上传的、非官方的、不精确的数据。因此只要标识清楚哪些数据是精确值，哪些数据是统计值，我认为是可以接受的。

**Comment by Lightczx** [comment]
主要是部分数据的样本量实在太小了

**Comment by FlandiaYingman** [comment]
> 主要是部分数据的样本量实在太小了

样本较小的情况都出现在低冒险等级的时候。我觉得把这些低冒险等级的情况剔除掉就行了

**Comment by FlandiaYingman** [comment]
@xTaiwanPingLord 

我在一开始提出该方法时确实没有经过太多的实践，
经过这些天的实践，我赞同你对该方法过于复杂的看法，因为求出最优解的收益不大，不值得为此设计一个复杂的方法。

**Comment by GashByte** [comment]
误差是不可避免的 但是我们还是缺少很多domian的Datas 我觉得 @FlandiaYingman  提供的算法example进过改良之后还是可以达到预期内的时间 我还需要一点时间来熟悉示例代码 我也需要寻找更多的能够维持正常更新的domain datas

**Comment by Lightczx** [comment]
> 误差是不可避免的 但是我们还是需要一些domian的Datas 我觉得 @FlandiaYingman 提供的算法example进过改良之后还是可以达到预期内的时间 我还需要一点时间来熟悉示例代码 我也需要寻找更多的能够维持正常更新的domain datas

@GashByte 
https://github.com/DGP-Studio/Snap.Data.Mapper
https://github.com/UIGF-org/GenshinData
https://github.com/DGP-Studio/Snap.Metadata

**Comment by FlandiaYingman** [comment]
@Lightczx 
https://github.com/UIGF-org/GenshinData 已经 404 了

**Comment by Lightczx** [comment]
> @Lightczx https://github.com/UIGF-org/GenshinData 已经 404 了

Internal Only

**Comment by AZhrZho** [comment]
以当前胡桃的用户量，可以考虑通过胡桃收集副本挑战掉落材料，样本量充足且数据源可控。
具体实现，可以在胡桃中内置截图识别+上传，结合已有用户体系，可收集到的数据有：

- 挑战的副本及等级
- 掉落物及数量
- 挑战副本的时间（可进行时间相关性统计）
- 数据来源（方便洗去恶意数据）

同时可以结合胡桃云激励时长，鼓励用户上传副本数据。收集到充足样本后，使用简单的期望估计即可解决问题。期望值可以根据背包中物品数量进行迭代而不断修正

当然也可以选择更精确的统计模型进行计算，只要样本充足，都可以实现（实际上，基于大量样本的简单期望估计一定比线性规划更准确，理由是在精确概率不可知的情况下，参数越少受误差影响越小）

此外，可以视样本的收集率，选择一定长度的滑动时间窗口进行概率估计。此举可保证即使官方暗改了概率，应用也可以自适应概率的变化。更进一步，还可以对时间进行水平划分，通过大量样本计算是否存在所谓的“玄学时间”

**Comment by Lightczx** [comment]
> 以当前胡桃的用户量，可以考虑通过胡桃收集副本挑战掉落材料，样本量充足且数据源可控。 具体实现，可以在胡桃中内置截图识别+上传，结合已有用户体系，可收集到的数据有：
> 
> * 挑战的副本及等级
> * 掉落物及数量
> * 挑战副本的时间（可进行时间相关性统计）
> * 数据来源（方便洗去恶意数据）
> 
> 同时可以结合胡桃云激励时长，鼓励用户上传副本数据。收集到充足样本后，使用简单的期望估计即可解决问题。期望值可以根据背包中物品数量进行迭代而不断修正
> 
> 当然也可以选择更精确的统计模型进行计算，只要样本充足，都可以实现（实际上，基于大量样本的简单期望估计一定比线性规划更准确，理由是在精确概率不可知的情况下，参数越少受误差影响越小）
> 
> 此外，可以视样本的收集率，选择一定长度的滑动时间窗口进行概率估计。此举可保证即使官方暗改了概率，应用也可以自适应概率的变化。更进一步，还可以对时间进行水平划分，通过大量样本计算是否存在所谓的“玄学时间”

掉落概率其实是固定的，现在是元数据没准备好

**Comment by Lightczx** [comment]
Tracked by #1394
