### ISSUE TITLE
[Bug]: 显示此cookie不完整

### ISSUE THREAD

**Issue by Lqsqin** [DGP-Studio/Snap.Hutao#324]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22000.1335

### Snap Hutao 版本

1.2.0.0

### 问题分类

用户界面

### 发生了什么？

第一次使用网页登录，按操作进行后，显示此cookie不完整；第二次使用网络上抓取cookie的方法抓到了cookie，仍是显示不完整；第三次使用stream抓取cookie，还是一样的结果。以上操作都是管理员身份运行下进行。

**Comment by Lightczx** [comment]
私发cookie到我的邮箱

**Comment by Lqsqin** [comment]
已发，请查收

**Comment by Lightczx** [comment]
在设置中找到 删除所有用户，执行后重启app再试

**Comment by Lqsqin** [comment]
没有找到【删除所有用户】，我打开设置里的【打开数据文件夹】，将里面的东西删了，仍不成功

**Comment by Lightczx** [comment]
更新

**Comment by Lqsqin** [comment]
已解决，感谢。我从【cube】上下载的软件，其尚未更新版本，所以出了问题
