### ISSUE TITLE
希望可以加入手动下载资源包功能

### ISSUE THREAD

**Issue by Colorfuldiamond** [DGP-Studio/Snap.Hutao#326]
### 背景与动机

因为这个软件似乎武器图片之类的各种各样的东西都是使用时自动在线下载，当因为各种原因无法正常在线下载，各种图标就都是一片白
比如此时此处页面的所有物品图标都是白的
github死活无法上传图片，图片丢到图床了
https://img.xhacgn.com/image/ZKzPr

### 想要实现或优化的功能

安装包自带各种图标，或者提供单独资源包

**Comment by Lightczx** [comment]
impl
