### ISSUE TITLE
[New Feature Implementation]胡桃缩小到系统右下角Demo

### ISSUE THREAD

**Issue by RogerLiu-98** [DGP-Studio/Snap.Hutao#327]
### 背景与动机

通过将胡桃App缩小到右下角让用户获得更加的用户体验（e.g. 直接从右下角启动游戏）

### 想要实现或优化的功能

**Note:** 请关闭这个issue如果我们不再需要这个feature，因为我在文档中看到了貌似这个功能已经不再被需要了

Current Progress: 
- 已经通过[H.NotifyIcon](https://github.com/HavenDV/H.NotifyIcon)实现了一个将胡桃App缩小到右下角的Demo
![traytooltip](https://user-images.githubusercontent.com/57798223/209802849-e64b477b-dcec-473c-9a73-cc15ce7b17e9.png)
- 如果我们还需要这个功能，想知道在右下角的tooltip中我们还需要什么功能（e.g. 账号设置，启动游戏，etc)

**Comment by RogerLiu-98** [comment]
Happy to contribute to this project :)

**Comment by Lightczx** [comment]
我们不希望引入整个 H.NotifyIcon 包，需要额外的工作来将他们的实现方法嵌入我们的项目中

**Comment by RogerLiu-98** [comment]
如果你们仍然需要这个功能，我可以尝试用其它方法来实现这个功能 :)

**Comment by Lightczx** [comment]
如果可以不依赖其他的包，且仅使用Win32与WinUI的功能来实现，可以考虑并入

**Comment by RogerLiu-98** [comment]
Cool，那我们可以暂时关闭这个issue，当我完成Demo之后我会创建一个新的issue
