### ISSUE TITLE
[Bug]: 胡桃更新后打开即闪退

### ISSUE THREAD

**Issue by UnrealOfficial** [DGP-Studio/Snap.Hutao#33]
### Windows 版本

22000.978

### Snap Hutao 版本

1.0.33.0

### 发生了什么？

打开即闪退，重装无效

### 相关的崩溃日志 位于 %HOMEPATH%/Documents/Hutao/Log.db

```shell
那玩意vscode一打开就是乱码，复制之后github还嫌太长
```

**Comment by Lightczx** [comment]
已知问题，已经修复
