### ISSUE TITLE
[Bug]: 调整窗口大小时崩溃

### ISSUE THREAD

**Issue by KeeLee2005** [DGP-Studio/Snap.Hutao#330]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22623.1037

### Snap Hutao 版本

1.2.19.0

### 设备 ID

9DCAEF5A488446FE3B880E68395A2C10

### 问题分类

其它

### 发生了什么？

调整窗口大小时崩溃，可靠性监视程序显示如下
问题事件名称:	MoAppCrash
程序包全名:	7f0db578-026f-4e0b-a75b-d5d06bb0a74d_1.2.19.0_x64__7jfyf5536hdrr
应用程序名:	praid:app
应用程序版本:	1.0.0.0
应用程序时间戳:	6377ba57
故障模块名称:	combase.dll
故障模块版本:	10.0.22621.1017
故障模块时间戳:	622991f2
异常代码:	80004005
异常偏移:	00000000000918bb
OS 版本:	10.0.22623.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	dad9
其他信息 2:	dad98c4e913d7013528c812dccf38c00
其他信息 3:	1645
其他信息 4:	1645096c25c8cc9dd48b92a44ff8a7fc

**Comment by Lightczx** [comment]
@KeeLee2005 调整大小时处于哪个页面

**Comment by KeeLee2005** [comment]
> @KeeLee2005 调整大小时处于哪个页面

应该是活动公告，就是刚打开时的页面。现在因为combase.dll根本打不开，看到一个空白的窗口然后就崩了。

**Comment by Lightczx** [comment]
重置一下数据

**Comment by KeeLee2005** [comment]
> 重置一下数据

![QQ截图20221231101143](https://user-images.githubusercontent.com/92454987/210121993-5273b4ef-1042-4f6b-a6c4-e586c3691f59.png)
反复几次还是打不开

**Comment by Lightczx** [comment]
重装吧，不是我们的问题
