### ISSUE TITLE
[Bug]: 关于祈愿卡池识别问题的bug反馈

### ISSUE THREAD

**Issue by Emiyawing** [DGP-Studio/Snap.Hutao#331]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [x] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.2.19.0

### 设备 ID

DA64962169CDD2F51841B592646A31FA

### 问题分类

祈愿记录

### 发生了什么？

亲爱的开发者（or团队）
你好，我最近在试用胡桃工具箱的时候发现起源记录的分析非常不准确。包括up角色跟常驻角色的错误识别、卡池角色的错误识别等等。比如将up角色识别为常驻角色，然后历史卡池记录里出现了其他卡池的角色等等。我没办法利用现在的信息制定出后面的卡池规划，希望能修复，谢谢。

**Comment by Lightczx** [comment]
祈愿记录为App内获取还是导入？@Emiyawing

**Comment by Lightczx** [comment]
祈愿记录为App内获取还是导入？@Emiyawing

**Comment by Emiyawing** [comment]
App内获取，我没有找到GitHub内上传图片的方式，所以将截图也一并发在了兔小巢中，如果有需要可以去查看一下。

**Comment by Lightczx** [comment]
描述一下正常的顺序

**Comment by Emiyawing** [comment]
首先在角色up池中，从上往下：第三个达达利亚是up角色，第七个甘雨是up角色，同时甘雨上面的温迪也不是保底。最后的up平均抽数应该是85.37而不是113.83
然后在历史记录中，3.2版本宵宫的记录应该是达达利亚卡池中的记录。我并没有抽过宵宫池，而且宵宫池里也不可能出达达利亚

**Comment by Lightczx** [comment]
全量刷新试一下

**Comment by Emiyawing** [comment]
还是一样的，记录删除重新获取也试过了，都不行

**Comment by Lightczx** [comment]
导出，上传

**Comment by Emiyawing** [comment]
[109342709.txt](https://github.com/DGP-Studio/Snap.Hutao/files/10326971/109342709.txt)
导出的文件格式不支持上传，我把后缀改成txt了，别的地方没动

**Comment by Lightczx** [comment]
无法复现，应该是你的元数据无法更新导致的，检查网络

**Comment by Emiyawing** [comment]
不好意思，元数据无法更新是什么意思啊，自己搜了一下没有找到相关资料。网络的话应该也没什么问题。可以简单讲一下解决方式吗？
