### ISSUE TITLE
LTSC 和 LTSB 版本系统

### ISSUE THREAD

**Issue by MyZafkiel** [DGP-Studio/Snap.Hutao#335]
### 背景与动机

LTSC 和 LTSB 版本系统不在支持列表中，但它们可以在修改系统模块后使用胡桃工具箱。请联系你的 IT 管理员以获取支持。
上方是文档上的写法具体需要修改那些系统模块呢

### 想要实现或优化的功能

希望在文档中说明修改哪些,如何修改

**Comment by Masterain98** [comment]
请联系你的 IT 管理员以获取支持
