### ISSUE TITLE
[Bug]: 手动点击成就闪退

### ISSUE THREAD

**Issue by Mouseiswolf** [DGP-Studio/Snap.Hutao#336]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.3.0.0

### 设备 ID

CAC676E14B437C8921C3D22845F6A3C9

### 问题分类

成就管理

### 发生了什么？

在成就管理界面，如果在部分分类（如天地万象等）下手动点击成就，程序会崩溃退出，但也有一部分分类成就正常。

### 你期望发生的行为？

手动点击成就以标记完成

### 相关的崩溃日志

[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10330056/Log.zip)

**Comment by Lightczx** [comment]
@Mouseiswolf 具体到会崩溃的成就名称

**Comment by Mouseiswolf** [comment]
详细测试了一下 目前发现 如果是多级成就（如收集类的、找宝箱类的（岩间引路人）等） 那么在手动勾选较高等级成就时会崩溃闪退（应该弹窗提示 如“需完成前置成就”） 
此外 由于未知原因 天地万象分类下**所有**成就无论有无多级均会闪退 暂未发现规律及原因

**Comment by Lightczx** [comment]
更新了么
