### ISSUE TITLE
[Bug]:深渊记录点击刷新没有反应

### ISSUE THREAD

**Issue by ame-code** [DGP-Studio/Snap.Hutao#337]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19041.208

### Snap Hutao 版本

1.3.2

### 设备 ID

D2A04CEBDFB4C83ECBF30530617D2530

### 问题分类

其他

### 发生了什么？

在“深渊记录”界面点击“刷新”按钮没有任何反馈
![Snipaste_2023-01-02_20-20-29](https://user-images.githubusercontent.com/71199825/210230983-6b8ad42d-7c29-4d58-b8d7-c62302a8455a.png)

https://user-images.githubusercontent.com/71199825/210231021-9f753655-f81d-4792-8182-8579c763c64a.mp4

### 你期望发生的行为？

能够看到正常的界面

**Comment by Lightczx** [comment]
fixed internally
