### ISSUE TITLE
[Bug]: “我的角色”无法显示角色

### ISSUE THREAD

**Issue by yangysc** [DGP-Studio/Snap.Hutao#338]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

Win11 22H2, 22621.963

### Snap Hutao 版本

1.3.1

### 问题分类

角色信息面板

### 发生了什么？

点击同步角色信息后，无法获取并显示。 三个“同步”按钮都不行

![Uploading image.png…]()

### 你期望发生的行为？

点击同步角色信息后，获取并显示

**Comment by yangysc** [comment]
![image](https://user-images.githubusercontent.com/8980981/210295460-5109f946-d7fa-420e-9d3a-810d13e35cb2.png)

**Comment by Lightczx** [comment]
fixed internally

**Comment by yangysc** [comment]
> fixed internally

![image](https://user-images.githubusercontent.com/8980981/211146535-aa0c187c-c11a-4144-bbeb-35b510566e13.png)

安装了最新的1.3.4.0，这个功能依旧无法正常使用。请问 “fixed internally”是预定在哪个版本上线吗

**Comment by Lightczx** [comment]
重新登录再同步

**Comment by yangysc** [comment]
> 重新登录再同步

重新添加了一遍用户后，依旧点击“同步”按钮无事发生，三个按钮都试过了😂 不太清楚其他设备能否正常使用
![image](https://user-images.githubusercontent.com/8980981/211146794-3fe0730a-f3da-4fc1-ba49-287115bc4606.png)

**Comment by Lightczx** [comment]
备份成就与祈愿记录后删除 `%userprofile%/Hutao/Userdata.db` 重试

**Comment by yangysc** [comment]
> 备份成就与祈愿记录后删除 `%userprofile%/Hutao/Userdata.db` 重试

![image](https://user-images.githubusercontent.com/8980981/211180215-31dd2778-222c-4c41-8fbf-089de5c9d340.png)
请问删除后 再登录为什么出现网络问题

**Comment by Lightczx** [comment]
那就是你自己的问题

**Comment by yangysc** [comment]
> 那就是你自己的问题

![image](https://user-images.githubusercontent.com/8980981/211180419-4a58b29f-754c-4683-b0bc-553d881ff234.png)
尝试卸载重装 依旧提示这个问题，版本是1.3.4. 不太清楚为什么直接删除Userdata.db后一直这样子。设备网络是确保了没问题的，并且程序第一次打开的自动下载资源也是成功的

**Comment by yangysc** [comment]
我手动输入一下cookie吧😂 打扰啦 感谢

**Comment by yangysc** [comment]
> 备份成就与祈愿记录后删除 `%userprofile%/Hutao/Userdata.db` 重试

手动输入后登录就可以显示我的角色了，感谢！
