### ISSUE TITLE
[Feat]: 应用数据云同步

### ISSUE THREAD

**Issue by misaka10384** [DGP-Studio/Snap.Hutao#34]
### 你想要实现或优化的功能？

添加绑定微软账号  每次任意数据更新时自动将记录同步并备份至onedrive
1.祈愿记录
2.成就
3.[#83]深渊数据 
4.[#385 ]每日获取的摩拉以及原石
5.[#464 ]历史每日
之类的 总之 如果能同步就一起同步上去

**Comment by yzx19981008** [comment]
刚需，养成游戏 这种记录还是很需要的

**Comment by MyZafkiel** [comment]
这种备份要是可以部署自己私有服务器就更好了

**Comment by MyZafkiel** [comment]
还对你们服务器压力降低

**Comment by earthjasonlin** [comment]
或许可以webdav？

**Comment by Lightczx** [comment]
open PR

**Comment by Lightczx** [comment]
祈愿记录同步服务将会在下版本上线，如果有其他数据的同步需求请单独提交新的 Issue
