### ISSUE TITLE
[Bug]: 祈愿记录数字排版问题

### ISSUE THREAD

**Issue by QingXi-z** [DGP-Studio/Snap.Hutao#340]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22000.1335

### Snap Hutao 版本

1.3.0.0

### 设备 ID

84F81B67BFFDE7AD9CACA12BC1CC80A6

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录下方每个角色的抽取计数排版出现问题，不是横着的是竖着的
![}VW UYFRF4{WPP4X7GS0MO](https://user-images.githubusercontent.com/121853905/210318140-cd8fedd5-1806-4e5b-9543-c89a33b07419.png)

### 你期望发生的行为？

更改为横板数字

**Comment by Lightczx** [comment]
屏幕DPI是多少@QingXi-z

**Comment by QingXi-z** [comment]
我用的100%，笔记本推荐125%，1920*1080的屏幕

**Comment by Lightczx** [comment]
是否替换了系统默认字体

**Comment by Lightczx** [comment]
fixed

**Comment by QingXi-z** [comment]
需要重新下载吗是

**Comment by QingXi-z** [comment]
欧我看到文档里的教程了，感谢！
