### ISSUE TITLE
[Bug]: 添加不了材料清单

### ISSUE THREAD

**Issue by doub-one** [DGP-Studio/Snap.Hutao#341]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22h2

### Snap Hutao 版本

1.3.3.0

### 设备 ID

6A1B4241E6516AB5305AFB907B1BB4B5

### 问题分类

养成计算器

### 发生了什么？

添加不了材料清单

### 你期望发生的行为？

可以看到材料的具体数据

**Comment by Lightczx** [comment]
@doub-one 详细描述你的问题，至少得能看懂。
