### ISSUE TITLE
[Bug]: 中文Windows系统下翻译错误

### ISSUE THREAD

**Issue by CzHUV** [DGP-Studio/Snap.Hutao#343]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.3.3.0

### 设备 ID

EA4D2A18959A26C2504A17F061AB272F

### 问题分类

用户界面

### 发生了什么？

![image](https://user-images.githubusercontent.com/100004265/210720802-601faf93-be50-4cd4-9a8a-288e6efd5331.png)
如图，简体中文Windows系统下“解锁FPS限制”功能未翻译.

**Comment by Lightczx** [comment]
intended behavior

**Comment by CzHUV** [comment]
> intended behavior

got it.
