### ISSUE TITLE
[Bug]: 奔行世间没有up的角色或武器

### ISSUE THREAD

**Issue by Tu-Chenjia** [DGP-Studio/Snap.Hutao#346]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.963

### Snap Hutao 版本

1.3.3.0

### 设备 ID

BE025FAA5819DD8F0E7D3DF23AB7BD53

### 问题分类

祈愿记录

### 发生了什么？

奔行世间并不含有角色和武器的up，而界面里有一个“up平均抽数”的数据，这会误导使用者
<img width="889" alt="微信图片_20230106184458" src="https://user-images.githubusercontent.com/87529322/210995110-b2fb5005-525d-4e87-889c-2cc8221190d8.png">

### 你期望发生的行为？

可以将“up平均抽数”修改成“四星平均抽数”或直接删去

**Comment by Lightczx** [comment]
该字段是为了与其他两个视图对齐存在的，将来会考虑如何调整

**Comment by Masterain98** [comment]
可以考虑替换为五星角色或五星武器的平均抽数
