### ISSUE TITLE
[Bug]: 游戏公告增加返回按钮

### ISSUE THREAD

**Issue by icimence** [DGP-Studio/Snap.Hutao#350]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.963

### Snap Hutao 版本

1.3.7

### 问题分类

用户界面

### 发生了什么？

活动公告和游戏公告点击后都没有返回按钮，查看活动公告时可以使用侧边栏直接回到活动公告页面，但是游戏公告点击侧边栏则是回到活动公告，需要浏览多个游戏公告时比较麻烦。

### 你期望发生的行为？

游戏公告和活动公告详情界面增加一个包含标题和返回按钮的header

**Comment by Lightczx** [comment]
你觉得左上角那玩意是摆设么？

**Comment by icimence** [comment]
啊这，真没注意到
