### ISSUE TITLE
[Bug]: 系统频繁弹窗提示缓冲区溢出

### ISSUE THREAD

**Issue by Jolkssn** [DGP-Studio/Snap.Hutao#354]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19043.1200

### Snap Hutao 版本

1.3.7

### 问题分类

其它

### 发生了什么？

系统频繁弹窗提示检测到基于堆栈的缓冲区溢出，大概每小时弹三四次，翻阅文档未找到相关解决方案

![bug](https://user-images.githubusercontent.com/50570270/211584643-74af3012-07bc-4fc6-a71f-e8ed5a5eaae9.jpg)

**Comment by Lightczx** [comment]
请提供设备ID

**Comment by Jolkssn** [comment]
> 请提供设备ID

A425CB3C50C15A7284ECA334593DE927

**Comment by Masterain98** [comment]
@dgp-bot 拉取日志 A425CB3C50C15A7284ECA334593DE927

**Comment by Lightczx** [comment]
fixed
