### ISSUE TITLE
[Network]: 无法下载基本图像资源

### ISSUE THREAD

**Issue by lvwenzhuo2003** [DGP-Studio/Snap.Hutao#358]
### 提交你的网络诊断报告

正在诊断网络环境...
这可能需要至多10分钟，请耐心等待。
诊断程序可以在最小化的情况下运行，结束后将生成报告文件。

本地时间: 2023-01-11 11:19:03
本机时区: 中部标准时间

本地 DNS: 10.0.0.1
本地 DNS: 8.8.8.8
本地 DNS: 1.1.1.1
本地 DNS: 172.20.10.1
本地 DNS: 8.8.4.4

当前 IP：50.220.*.186  来自于：美国 伊利诺伊州 尚佩恩  comcast.com

====================
正在检查 元数据 的网络连接情况
IP 地址: 81.28.12.12

正在 Ping cl-f3485468.gcdn.co [81.28.12.12] 具有 32 字节的数据:
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55

81.28.12.12 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 4ms，最长 = 4ms，平均 = 4ms

正在进行 traceroute 测试，请耐心等待...

通过最多 30 个跃点跟踪
到 cl-f3485468.gcdn.co [81.28.12.12] 的路由:

  1    <1 毫秒   <1 毫秒   <1 毫秒 10.3.17.1
  2     1 ms     1 ms     1 ms  50.200.239.141
  3     1 ms    <1 毫秒   <1 毫秒 162.151.144.9
  4     5 ms     4 ms     4 ms  68.85.176.113
  5     6 ms     5 ms     5 ms  96.110.40.57
  6     5 ms     5 ms     5 ms  96.110.37.26
  7     *        *        *     请求超时。
  8     *        *        *     请求超时。
  9     4 ms     4 ms     4 ms  81.28.12.12

跟踪完成。

====================
正在检查 静态资源 - 1 的网络连接情况
IP 地址: 81.28.12.12

正在 Ping cl-glbd9c040d.gcdn.co [81.28.12.12] 具有 32 字节的数据:
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55

81.28.12.12 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 4ms，最长 = 5ms，平均 = 4ms

正在进行 traceroute 测试，请耐心等待...

通过最多 30 个跃点跟踪
到 cl-glbd9c040d.gcdn.co [81.28.12.12] 的路由:

  1    <1 毫秒   <1 毫秒   <1 毫秒 10.3.17.1
  2     1 ms     1 ms     1 ms  50.200.239.141
  3     1 ms    <1 毫秒   <1 毫秒 162.151.144.9
  4     5 ms     5 ms     5 ms  68.85.176.113
  5     6 ms     5 ms     6 ms  96.110.40.57
  6     5 ms     5 ms     5 ms  96.110.37.26
  7     *        *        *     请求超时。
  8     *        *        *     请求超时。
  9     5 ms     4 ms     4 ms  81.28.12.12

跟踪完成。

====================
正在检查 静态资源 - 2 的网络连接情况
IP 地址: 81.28.12.12

正在 Ping cl-glbd9c040d.gcdn.co [81.28.12.12] 具有 32 字节的数据:
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55

81.28.12.12 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 4ms，最长 = 5ms，平均 = 4ms

正在进行 traceroute 测试，请耐心等待...

通过最多 30 个跃点跟踪
到 cl-glbd9c040d.gcdn.co [81.28.12.12] 的路由:

  1    <1 毫秒   <1 毫秒   <1 毫秒 10.3.17.1
  2     1 ms     1 ms     2 ms  50.200.239.141
  3    <1 毫秒   <1 毫秒   <1 毫秒 162.151.144.9
  4     5 ms     4 ms     4 ms  68.85.176.113
  5     5 ms     5 ms     5 ms  96.110.40.57
  6     5 ms     5 ms     5 ms  96.110.37.26
  7     *        *        *     请求超时。
  8     *        *        *     请求超时。
  9     4 ms     4 ms     4 ms  81.28.12.12

跟踪完成。

====================
正在检查 胡桃数据库 的网络连接情况
IP 地址: 81.28.12.12

正在 Ping cl-glbd9c040d.gcdn.co [81.28.12.12] 具有 32 字节的数据:
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55

81.28.12.12 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 4ms，最长 = 5ms，平均 = 4ms

正在进行 traceroute 测试，请耐心等待...

通过最多 30 个跃点跟踪
到 cl-glbd9c040d.gcdn.co [81.28.12.12] 的路由:

  1    <1 毫秒   <1 毫秒   <1 毫秒 10.3.17.1
  2     1 ms     1 ms     1 ms  50.200.239.141
  3     1 ms    <1 毫秒   <1 毫秒 162.151.144.9
  4     5 ms     5 ms     5 ms  68.85.176.113
  5     6 ms     5 ms     5 ms  96.110.40.57
  6     5 ms     5 ms     5 ms  96.110.37.26
  7     *        *        *     请求超时。
  8     *        *        *     请求超时。
  9     6 ms     6 ms     5 ms  81.28.12.12

跟踪完成。

====================
正在检查 胡桃工具箱 - 主页 的网络连接情况
IP 地址: 81.28.12.12

正在 Ping cl-f3485468.gcdn.co [81.28.12.12] 具有 32 字节的数据:
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=4ms TTL=55
来自 81.28.12.12 的回复: 字节=32 时间=5ms TTL=55

81.28.12.12 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 4ms，最长 = 5ms，平均 = 4ms

正在进行 traceroute 测试，请耐心等待...

通过最多 30 个跃点跟踪
到 cl-f3485468.gcdn.co [81.28.12.12] 的路由:

  1    <1 毫秒   <1 毫秒   <1 毫秒 10.3.17.1
  2     1 ms     1 ms     1 ms  50.200.239.141
  3     1 ms    <1 毫秒   <1 毫秒 162.151.144.9
  4     5 ms     4 ms     4 ms  68.85.176.113
  5     6 ms     5 ms     5 ms  96.110.40.57
  6     5 ms     5 ms     5 ms  96.110.37.26
  7     *        *        *     请求超时。
  8     *        *        *     请求超时。
  9     4 ms     4 ms     4 ms  81.28.12.12

跟踪完成。

====================
正在检查 Snap.Genshin - 主页 的网络连接情况
IP 地址: 14.204.85.40

正在 Ping frx7rff6.legotcb.sched.tdnsv8.com [113.207.30.58] 具有 32 字节的数据:
来自 113.207.30.58 的回复: 字节=32 时间=279ms TTL=38
来自 113.207.30.58 的回复: 字节=32 时间=276ms TTL=38
来自 113.207.30.58 的回复: 字节=32 时间=269ms TTL=38
来自 113.207.30.58 的回复: 字节=32 时间=272ms TTL=38

113.207.30.58 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 269ms，最长 = 279ms，平均 = 274ms

正在进行 traceroute 测试，请耐心等待...

通过最多 30 个跃点跟踪
到 frx7rff6.legotcb.sched.tdnsv8.com [113.207.30.58] 的路由:

  1    <1 毫秒   <1 毫秒   <1 毫秒 10.3.17.1
  2     1 ms     1 ms     1 ms  50.200.239.141
  3     1 ms    <1 毫秒    1 ms  162.151.144.9
  4     5 ms     5 ms     5 ms  68.85.176.113
  5     5 ms     5 ms     5 ms  96.110.40.53
  6     7 ms     7 ms     5 ms  68.86.82.246
  7    28 ms    28 ms    28 ms  96.110.37.158
  8    27 ms    27 ms    27 ms  96.110.39.65
  9    28 ms    27 ms    27 ms  96.110.39.114
 10    28 ms    28 ms    28 ms  96.110.39.9
 11    28 ms    27 ms    28 ms  96.110.37.241
 12    28 ms    28 ms    28 ms  96.110.37.210
 13    52 ms    52 ms    52 ms  96.110.39.22
 14    52 ms    52 ms    52 ms  96.110.46.25
 15    52 ms    52 ms    52 ms  96.110.46.30
 16    53 ms    52 ms    52 ms  96.110.37.178
 17    53 ms    52 ms    53 ms  68.86.166.145
 18    53 ms    53 ms    53 ms  96.110.36.222
 19    53 ms    55 ms    55 ms  219.158.40.117
 20   205 ms   207 ms   207 ms  219.158.96.41
 21   204 ms   207 ms   207 ms  219.158.3.181
 22     *        *      238 ms  219.158.5.157
 23   239 ms   239 ms   255 ms  219.158.101.106
 24   264 ms   260 ms   259 ms  113.207.25.182
 25   273 ms   266 ms   264 ms  113.207.25.78
 26   267 ms   266 ms   264 ms  113.207.25.81
 27     *        *        *     请求超时。
 28     *        *        *     请求超时。
 29   260 ms   266 ms   270 ms  113.207.30.58

跟踪完成。

====================
正在进行 Speedtest 测试
下载速度: 686.79 Mbps
上传速度: 289.14 Mbps
服务器: Indianapolis, IN - LightBound

====================
日志已保存至 hutao-network-log.txt
请提交 hutao-network-log.txt 文件至 GitHub 或管理员
测试结束。你可以点击回车或者直接关闭该窗口

### 你的地理位置

美国

### 你的运营商

其它

### 你的问题

图片下载错误（429 Error）

### 你的问题（补充）

![image](https://user-images.githubusercontent.com/51859807/211879873-c9622c1d-2d4a-404e-9e3d-26dc51dda546.png)

**Comment by Masterain98** [comment]
是否已经恢复？

**Comment by Masterain98** [comment]
@Lightczx static2 需要 fail-over

**Comment by lvwenzhuo2003** [comment]
没有，一直提示等待中

**Comment by Lightczx** [comment]
@lvwenzhuo2003 429相关的截图能提供一下么

**Comment by Lightczx** [comment]
> 没有，一直提示等待中

等待了多长时间

**Comment by lvwenzhuo2003** [comment]
没有提示429，但一直卡在等待中
至少有半小时

**Comment by Lightczx** [comment]
一般超过3分钟就是彻底失败了，可以试试重启

**Comment by lvwenzhuo2003** [comment]
重启过了，还是不行
重置winsock和dns也不行

**Comment by Lightczx** [comment]
fixed
