### ISSUE TITLE
下次启动时恢复窗口大小

### ISSUE THREAD

**Issue by AllesUgo** [DGP-Studio/Snap.Hutao#359]
### 背景与动机

当前记住窗口大小只会记录为非最大化状态的窗口大小，如果我在最大化状态下关闭窗口，下次打开会以非最大化模式打开并将窗口大小调整为最大化的大小，在这种状态下窗口位置与真正的最大化有一点偏差，且无法通过拖动标题栏来使窗口变小

### 想要实现或优化的功能

建议改动方法有两种：
1.若窗口在最大化状态被关闭，下一次打开时直接以最大化窗口打开而不是以非最大化窗口将大小调整为最大化大小。
2.若窗口以最大化窗口被关闭，下次打开以上一次设置为最大化之前的大小打开或以默认窗口大小打开。

**Comment by Lightczx** [comment]
fixed internally
