### ISSUE TITLE
[Bug]: 祈愿记录刷新进程崩溃

### ISSUE THREAD

**Issue by rookuuuu** [DGP-Studio/Snap.Hutao#36]
### Windows 版本

19044.1288

### Snap Hutao 版本

1.1.0.0

### 发生了什么？

祈愿记录----刷新----从缓存刷新(点击后界面卡住然后进程消失)

**Comment by rookuuuu** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9624342/Log.zip)

**Comment by rookuuuu** [comment]
[new.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9624368/new.zip)

**Comment by leafmoes** [comment]
我也遇到了同样的问题

**Comment by Lightczx** [comment]
#56
