### ISSUE TITLE
[Bug]: 在导出祈愿记录时，会出现奇怪的报错

### ISSUE THREAD

**Issue by CraftYouMe** [DGP-Studio/Snap.Hutao#360]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22623.1095

### Snap Hutao 版本

1.3.8.0

### 设备 ID

A434DA271FB475F107FC467B231AECBC

### 问题分类

祈愿记录

### 发生了什么？

在导出/导入祈愿记录的时候会出现，无法打开文件选择器 Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by Lightczx** [comment]
Win11 预览版的问题
