### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Aquan666** [DGP-Studio/Snap.Hutao#362]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2364

### Snap Hutao 版本

1.3.10.0

### 问题分类

实时便笺

### 发生了什么？

![状态](https://user-images.githubusercontent.com/110881471/212538718-bc1c680d-ac7f-4443-ac11-d4c4b10a50bc.png)
长期挂机，出现该情况，但不影响sh的使用，所有工具仍能照常使用。

**Comment by Lightczx** [comment]
正常现象
