### ISSUE TITLE
如何从Snap.Genshin迁移祈愿记录

### ISSUE THREAD

**Issue by li0817** [DGP-Studio/Snap.Hutao#363]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.3.10.0

### 问题分类

祈愿记录

### 发生了什么？

Snap.Genshin里找到了JSON文件，但无法导入
![image](https://user-images.githubusercontent.com/27659768/212563015-919a4f38-de69-4e58-839b-dacddc65d57b.png)
里面包含了基本整个2021年的数据，所以想导过来，毕竟还是有4000多行
![image](https://user-images.githubusercontent.com/27659768/212563460-025eabc8-3397-41a3-aaff-4f0eebd84ded.png)

### 你期望发生的行为？

将Snap.Genshin的数据导入至Snap.Hutao，主要是祈愿记录；
当然，如果不方便的话，就算了，可以直接关掉本issue，反正也不算什么大事

**Comment by Masterain98** [comment]
提供原始文件

**Comment by Lightczx** [comment]
请从SG导出uigf json，再导入SH

**Comment by li0817** [comment]
![image](https://user-images.githubusercontent.com/27659768/212723637-a57dae3c-75e0-45a0-ab3e-61acaa82c07a.png)
@Lightczx 没有找到可以导出json的选项，是我找错地方了吗

**Comment by Masterain98** [comment]
> ![image](https://user-images.githubusercontent.com/27659768/212723637-a57dae3c-75e0-45a0-ab3e-61acaa82c07a.png) @Lightczx 没有找到可以导出json的选项，是我找错地方了吗

你的SG版本太低，先到[SG Releases](https://github.com/DGP-Studio/Snap.Genshin/releases)中下载一个新版本导出

**Comment by li0817** [comment]
> > ![image](https://user-images.githubusercontent.com/27659768/212723637-a57dae3c-75e0-45a0-ab3e-61acaa82c07a.png) @Lightczx 没有找到可以导出json的选项，是我找错地方了吗
> 
> 你的SG版本太低，先到[SG Releases](https://github.com/DGP-Studio/Snap.Genshin/releases)中下载一个新版本导出

好；我当初想过更新版本，但看到说转到胡桃了就没去更新……是我陷入盲区了

**Comment by KagamigawaMeguri** [comment]
同问，SG需要cookie登录才可以进一步使用，但如今因为cookie问题snap无法登录，就无法进行下一步操作。

**Comment by Masterain98** [comment]
> 同问，SG需要cookie登录才可以进一步使用，但如今因为cookie问题snap无法登录，就无法进行下一步操作。

https://hut.ao/features/wish-export.html#%E4%BB%8E-snap-genshin-%E8%BD%AC%E7%A7%BB%E7%A5%88%E6%84%BF%E8%AE%B0%E5%BD%95%E6%95%B0%E6%8D%AE
