### ISSUE TITLE
[Bug]: 无法删除所有计划

### ISSUE THREAD

**Issue by linuslink57** [DGP-Studio/Snap.Hutao#367]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.3.12.0

### 问题分类

其它

### 发生了什么？

我在第一次卸载前没有执行 删除所有计划任务 这一操作，导致卸载后不停跳出“使用新应用以打开hutao链接”的弹窗，为此我重新安装了胡桃，但是在执行 删除所有计划任务 时出现清楚任务计划失败这一问题，请问如何解决

### 你期望发生的行为？

应该出现清楚任务计划成功字样

**Comment by Lightczx** [comment]
管理员模式下执行
