### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by HensonYing** [DGP-Studio/Snap.Hutao#371]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.1766

### Snap Hutao 版本

1.3.12.0

### 问题分类

安装和环境

### 发生了什么？

![hutao](https://user-images.githubusercontent.com/122778357/212685407-1e21b006-55d4-4d17-814e-97413c82fd9d.png)
![hutao2](https://user-images.githubusercontent.com/122778357/212685427-55509cda-f53a-4016-a24b-8be7306924e5.png)
无法正常安装

### 你期望发生的行为？

可以正常安装使用

**Comment by Lightczx** [comment]
请自行百度错误代码解决，我们不认为这是我们的问题
