### ISSUE TITLE
[External]: 我们遇到的外部问题

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Hutao#373]
下面给出 Issue 链接 与 解决方案源码 (如果有):

### Issue
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/2504

### Workaround
None.

---

### Issue
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/2931

### Workaround
Set `FileTypeFilter` on win10 picker

---

### Issue
- [ ] https://github.com/microsoft/microsoft-ui-xaml/issues/7756

### Workaround
[ComboBoxExtendsContentIntoTitleBarWorkaroundBehavior](https://github.com/DGP-Studio/Snap.Hutao/blob/main/src/Snap.Hutao/Snap.Hutao/Control/Behavior/ComboBoxExtendsContentIntoTitleBarWorkaroundBehavior.cs)

---

### Issue
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/2976

### Workaround
[UpdateDragRectangles](https://github.com/DGP-Studio/Snap.Hutao/blob/main/src/Snap.Hutao/Snap.Hutao/Core/Windowing/ExtendedWindow.cs#L200)

---

**Comment by YexuanXiao** [comment]
请问使用SetDragRectangles之后，无法通过标题栏调整窗口高度有办法解决吗 ，已经试过

**Comment by Lightczx** [comment]
> 请问使用SetDragRectangles之后，无法通过标题栏调整窗口高度有办法解决吗 ，已经试过 // workaround for [microsoft/WindowsAppSDK#2976](https://github.com/microsoft/WindowsAppSDK/issues/2976) SizeInt32 size = options.AppWindow.ClientSize; size.Height -= (int)(31 * scale); options.AppWindow.ResizeClient(size);

目前没有解决办法

**Comment by Lightczx** [comment]
Track https://github.com/microsoft/microsoft-ui-xaml/issues/8414
