### ISSUE TITLE
[Feat]: 软件字体自定义

### ISSUE THREAD

**Issue by YifePlayte** [DGP-Studio/Snap.Hutao#374]
### 背景与动机

新的MiSans在我的电脑屏幕上要看花眼了，整个糊成一团，眼睛很累。

### 想要实现或优化的功能

提供字体自定义选项，给用户以选择

**Comment by Lightczx** [comment]
提供屏幕尺寸与分辨率

**Comment by YifePlayte** [comment]
> 提供屏幕尺寸与分辨率@YifePlayte

1920*1080 缩放100% 15.6英寸

**Comment by Lightczx** [comment]
自定义字体是不会做的
如果看不清可以试试125%
