### ISSUE TITLE
[Feat]: 添加武器和角色筛选功能

### ISSUE THREAD

**Issue by icimence** [DGP-Studio/Snap.Hutao#375]
### 背景与动机

查看武器资料页面时希望对比同种类型武器之间数值差距，频繁使用搜索有些低效，如果用图标视图四星武器有点难找，希望添加星级和武器类型的筛选功能。
角色资料页面问题小一些，基本上可以用图标视图找出来，但是还是希望能增加星级和属性的筛选功能

### 想要实现或优化的功能

能够通过选中的武器类型（角色属性）和星级过滤显示的武器列表（角色列表）

**Comment by Lightczx** [comment]
在搜索框中 键入 `四星` 以筛选星级
在搜索框中 键入 `火` 以筛选元素
