### ISSUE TITLE
[Feat]: 实时便笺：验证角色窗口添加关闭按钮

### ISSUE THREAD

**Issue by UnrealOfficial** [DGP-Studio/Snap.Hutao#378]
### 背景与动机

如图，有人在验证角色时手痒，点了其他地方跳到其他页面，然后关不掉
**我不说那个手痒的人是谁，反正不是我（**

![010W`KZHJ97YFAUCI_IRE@K](https://user-images.githubusercontent.com/105903609/213178280-597d08db-d16a-4c12-bfeb-b07728c9e764.png)

### 想要实现或优化的功能

像签到页面那样添加一个关闭窗口的按钮

![image](https://user-images.githubusercontent.com/105903609/213178478-6a0d033e-1885-4876-9b2e-412bf4c60954.png)

**Comment by Lightczx** [comment]
按Esc有反应么

**Comment by UnrealOfficial** [comment]
点到其他页面的话，按esc就没反应了

**Comment by UnrealOfficial** [comment]
> 按Esc有反应么

点到其他页面的话，按esc就没有反应了
