### ISSUE TITLE
[Bug]: MiSans 对于小号文本稍显模糊

### ISSUE THREAD

**Issue by FlandiaYingman** [DGP-Studio/Snap.Hutao#379]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.12.0

### 问题分类

用户界面

### 发生了什么？

![image](https://user-images.githubusercontent.com/9929037/213184853-a686d7fd-574d-4656-90b7-8f8689e87a06.png)
![image](https://user-images.githubusercontent.com/9929037/213185356-187dec38-6f0e-4249-bf73-0bd433fd12f8.png)

可见在小号文本中，笔画较多的字显示较模糊。

而同样大小的字（12px），使用默认字体的显示效果（取自 Microsoft TODO）就显著较清晰：

![image](https://user-images.githubusercontent.com/9929037/213185501-121202ab-8547-4c34-b933-d42d9505e18d.png)
![image](https://user-images.githubusercontent.com/9929037/213185583-f6b2a8f7-0405-4151-990a-6e0599401864.png)

### 你期望发生的行为？

猜想：Mi Sans 没有为小号字做点阵优化？或是某些字体兼容问题？

建议：将字体修改回微软雅黑，或增加一个设置选项控制界面字体。

**Comment by Lightczx** [comment]
@FlandiaYingman 提供分辨率与缩放比

**Comment by FlandiaYingman** [comment]
> @FlandiaYingman 提供分辨率与缩放比

2560x1440, 100％

**Comment by Masterain98** [comment]
![image](https://user-images.githubusercontent.com/10614984/213689418-5fc604ec-b08c-45e4-a594-899edfdc2e08.png)

我这里的2560x1440, 100% 放大到300%的情况，似乎不太一样（原因我不清楚，仅参考）

@FlandiaYingman 你的 ClearType 启动状态？

**Comment by FlandiaYingman** [comment]
@Masterain98 我的 ClearType 是打开的状态。

你的图片放大使用了插值，没法对比字形的像素。能否发一张无缩放或者缩放方式是“邻近”的截图？
这样我们可以确认这个问题是不是普遍的

**Comment by FlandiaYingman** [comment]
根据 #398 的提示，用笔记本的内置显示器（1920x1080）外接大显示器（2560x1440）尝试复现了一下，结果：
![image](https://user-images.githubusercontent.com/9929037/215282614-04039821-9d5e-4760-ba35-97f2249d3b01.png)

- 缩放为 100%
- 顶层的 Microsoft TODO 作为对比，可对比出 MiSans 的显示模糊。
- 在两个屏幕的交界线中，并无明显的字体渲染差异。
- 将截图放到大屏幕上观看，字体显得模糊；将截图放到小屏幕上观看，字体显得没那么模糊了。证明此问题不与字体渲染的差异有关。
- 承上，我猜想这是由于模糊的字变小的话就显得不那么模糊而导致的。

猜想：MiSans 可能并未以 Windows 系统支持的方式进行 Hinting（即 TrueType Hinting）。

**Comment by Lightczx** [comment]
新版本会有一定的改进
