### ISSUE TITLE
[Feat]: 希望能够添加自定义提醒项

### ISSUE THREAD

**Issue by 13viTA** [DGP-Studio/Snap.Hutao#38]
### 你想要实现或优化的功能？

希望能够添加一个自定义提醒项。需求来源是每天会交替A/B捡圣遗物狗粮、定期采矿（多个小号资源）、其他需要定时的任务总是会记混乱。
具体实现的流程大概如下：
**TASK1---RECORDED---REACH ALARM TIME---NOTIFY ME**
Input: 自定义提醒任务名称、是否记录已执行、循环提醒时间（按小时，例如12、24、48、72小时）
Output：启动软件检查一次系统时间超过循环提醒时间，执行提醒行为，若软件一直运行，每小时（或者用户自定义时长）检测一次时间。
非常感谢制作团队的奉献。

**Comment by Lightczx** [comment]
闹钟App不能满足你的需求么

**Comment by 13viTA** [comment]
(⊙o⊙)…希望能整合在一起，之前snap genshin已经做了树脂之类api读取类的东西。可能我想能够整合会更方便。现在对于其他的app主要太分散。有点略微强迫症，用了一个就不想多开很多app的强迫症？抱歉。如果给你们增加负担，那就没必要了。
