### ISSUE TITLE
[Bug]: 无法验证当前账号角色，实时便签、深渊记录、我的角色无法正常获取

### ISSUE THREAD

**Issue by leafmoes** [DGP-Studio/Snap.Hutao#382]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.12.0

### 设备 ID

6F46C270974CB3C7E07563565FE7ADBF

### 问题分类

实时便笺

### 发生了什么？

![image](https://user-images.githubusercontent.com/44945631/213619574-c6aede83-0027-46a0-9d04-e403a52fb3b8.png)

如图，无法获取实时便签，我的角色，深渊，以及验证账号角色

**Comment by leafmoes** [comment]
![image](https://user-images.githubusercontent.com/44945631/213621089-fea3fdfe-ceb3-433d-b931-54a33a058841.png)
签到功能也无法使用

**Comment by Lightczx** [comment]
更新你的cookie

**Comment by leafmoes** [comment]
我更新过了，试过好多次，重新安装也是这样

**Comment by leafmoes** [comment]
登陆的米哈游通行证

**Comment by Lightczx** [comment]
导出所有记录，删除 %userprofile%/Hutao/userdata.db
重试

**Comment by leafmoes** [comment]
我尝试过了删除userdata.db
也尝试过使用从GetToken 获取的包含Stoken的Cookie也无法获取信息

**Comment by Lightczx** [comment]
将你当前的cookie私发给我

**Comment by leafmoes** [comment]
好的

**Comment by Lightczx** [comment]
![image](https://user-images.githubusercontent.com/36357191/213651332-0f901ea7-7854-45dd-952c-32f79266e2a3.png)

无法复现，可能是IP被米游社BAN了

**Comment by leafmoes** [comment]
好吧

**Comment by leafmoes** [comment]
应该是之前用的一个签到脚本一直失败，没有去管他
