### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by 0xiaoyu** [DGP-Studio/Snap.Hutao#383]
### 背景与动机

想要这个软件能够吸取别的好功能，能够一个软件享受极致体验

### 想要实现或优化的功能

1.地图追踪（椰羊）
2.圣遗物扫描（莫娜占星铺）
3.壶的材料统计，拥有扫描统计
4。摹本的展示，并显示或缺

**Comment by Lightczx** [comment]
摹本可以在 #217 提出相关的想法，其他的功能暂时不会考虑
