### ISSUE TITLE
[Feat]: 在"启动游戏"功能中添加"官方启动器"的选项

### ISSUE THREAD

**Issue by CzHUV** [DGP-Studio/Snap.Hutao#384]
### 背景与动机

以Snap Hutao第一次启动新版本原神时(已预下载),会打断登录并提示用户打开官方启动器.
另,由于Snap Hutao目前未实现预下载的功能,我认为添加一个打开官方启动器的选项较为实用.

### 想要实现或优化的功能

![image](https://user-images.githubusercontent.com/100004265/213637303-74384612-61b8-4411-abe4-a0d014826c0e.png)
如图，能否将Snap Genshin中打开官方启动器的功能迁移过来/有没有迁移的打算?

**Comment by Lightczx** [comment]
#166
