### ISSUE TITLE
[Feat]: 建议在应用中加入直达胡桃官方文档的链接

### ISSUE THREAD

**Issue by YYl04** [DGP-Studio/Snap.Hutao#386]
### 背景与动机

目前版本中缺少直达胡桃官网的超链接，仅有github链接，对于记不住官网url且没有收藏和不方便访问github的用户，想要找到胡桃官网只能通过加群或使用搜索引擎，应用内并没有展示群号而目前搜索引擎并不能很快找到胡桃官网，仅在搜索胡桃官网时百度才会在第三条结果展示snaphutao.com 搜索胡桃、dgp studio均没有正确结果。

### 想要实现或优化的功能

建议在应用设置第一栏"胡桃及版本号"右侧加入https://hut.ao/features 的超链接并命名为功能指南与常见问题，与下方反馈的前往反馈对齐。

**Comment by Masterain98** [comment]
hut.ao 

拼音读一遍，记不住没办法了

**Comment by Lightczx** [comment]
也是非常奇怪啊
如果你安装了胡桃App，那么你100%通过了某些途径了解到我们
* GitHub
* QQ 群
* 我们的官网

Github 页面中已经带有前往 hut.ao 的超链接
QQ 群甚至不需要前往 hut.ao

所以究竟是什么样的情形才会需要在这个地方加一个链接？

@YYl04

**Comment by Lightczx** [comment]
snapgenshin.com 是我们为 SG 注册的域名，在国内注册，曾用于 SG 的官网/文档/基础服务，现用于 SH 的各类基础服务
snaphutao.com 是我们为 SH 抢注的域名，在国内注册，用于 重定向到 hut.ao
hut.ao 是 我们我们为 SH 注册的域名，在国外注册， 用于官网/文档/资源中心
