### ISSUE TITLE
[Bug]: Window 11 使用 PowerShell 运行 `Install.ps1` 闪退

### ISSUE THREAD

**Issue by wordlesswind** [DGP-Studio/Snap.Hutao#387]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/most-frequent-questions.html)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.13.0

### 问题分类

安装和环境

### 发生了什么？

使用 PowerShell 运行 `Install.ps1` 闪退。

### 你期望发生的行为？

正常运行。

---

通过`在终端中打开`文件夹，在 [PowerShell](https://www.microsoft.com/store/apps/9MZ1SNWT0N5D) 7.1 中执行 `.\Install.ps1` 可正常运行。

**Comment by FlandiaYingman** [comment]
Windows 11 右键的**使用 PowerShell 运行**实际上是使用 Windows PowerShell 运行的，跟终端的 PowerShell 7.1 不是一个东西。你应该在安装 PowerShell 7 的时候勾选 **Add 'Run with PowerShell 7' context menu for PowerShell files**（不确定中文叫啥）

**Comment by wordlesswind** [comment]
> Windows 11 右键的**使用 PowerShell 运行**实际上是使用 Windows PowerShell 运行的

是唤起终端中的 PowerShell 5.1

> 跟终端的 PowerShell 7.1 不是一个东西。你应该在安装 PowerShell 7 的时候勾选 **Add 'Run with PowerShell 7' context menu for PowerShell files**

我知道，但我的 PowerShell 7.1 是通过 Microsoft Store 安装的，没有你说的东西。

而且你的说法，这跟我用文档中的方式运行后闪退没有关系。

我倾向于微软不知道加了什么判断逻辑，通过终端唤起 PowerShell 5.1 后，检测到安装了 PowerShell 7.1 时，会尝试切换到 PowerShell 7.1，但是切换失败所以变成了闪退。

**Comment by FlandiaYingman** [comment]
### 关于 Windows PowerShell 和 PowerShell Core

5.1 版本的 PowerShell 就是 Windows PowerShell，7.1 版本的 PowerShell 就是 PowerShell Core，这与你说的没有矛盾。
你可创建一个脚本：
```powershell
echo $PSVersionTable
pause
```
然后分别用终端和右键运行，查看`PSVersion`和`PSEdition`字段来验证我以上的断言：
```
PSEdition                      Desktop
```
说明这是 Windows PowerShell，
```
PSEdition                      Core
```
说明这是 PowerShell Core。
另外，利用 Microsoft Store 安装 PowerShell Core 是一种**临时方法**，详情请阅读[本文](https://learn.microsoft.com/zh-cn/powershell/scripting/install/installing-powershell-on-windows)。

> [Microsoft Store 包](https://learn.microsoft.com/zh-cn/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#msstore) - 适用于 PowerShell 临时用户进行安装的一种简单方法，但有一些限制

### 关于你的问题

我可在 Windows 11，22621.1105 上复现你的问题。

不过，开启**隐私和安全性>开发者选项>PowerShell>更改执行策略，以允许地PowerSheII脚本在未签名的情况下运行。远程本需要签名**后，问题消失了。你可以试一试。

而这一操作在文档中有提及：
>在系统设置中打开开发者设置界面，勾选 `开发人员模式` 和 `允许 PowerShell 脚本`。

**Comment by wordlesswind** [comment]
我并没有说 PowerShell 5.1 和 7.1 是一个东西，我只是在陈述我在 5.1 遇到的问题，以及成功在 7.1 运行脚本的事情，你想太多了。
