### ISSUE TITLE
[Bug]: 胡桃启动游戏后有概率崩溃闪退

### ISSUE THREAD

**Issue by UnrealOfficial** [DGP-Studio/Snap.Hutao#390]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [x] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.13.0

### 设备 ID

84CAC7A3667D7AEC29A4121CCA1B2BFB

### 问题分类

游戏启动器

### 发生了什么？

点击启动游戏，授予管理员权限后，游戏启动，然后胡桃崩溃闪退

### 你期望发生的行为？

保持打开状态而不是有概率闪退

### 相关的崩溃日志

gayhub不让传db格式，没办法只能用网盘
https://unreal.lanzout.com/idS6U0lo1m4d

**Comment by Masterain98** [comment]
将文件压缩即可上传

**Comment by UnrealOfficial** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10497319/Log.zip)

**Comment by Lightczx** [comment]
被杀软之类的撅了
