### ISSUE TITLE
[Bug]: HttpRequestException

### ISSUE THREAD

**Issue by ywzkevin99** [DGP-Studio/Snap.Hutao#391]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.13.0

### 设备 ID

34B596D5663606119AD4C218D6DB44D2

### 问题分类

文件缓存

### 发生了什么？

HttpRequestException
元数据校验文件下载失败
An error occurred while sending the request.

<img width="477" alt="屏幕截图 2023-01-23 121157" src="https://user-images.githubusercontent.com/97654557/214106027-c0c9aaee-9b8f-4dd0-97f5-b48462606d47.png">

所有内容无法显示并且无法同步，但是可以登录自己的账号

按照 https://hut.ao/FAQ/HttpRequestException.html 中的解决方案，系统无代理且网络连接无问题，也使用 Windows 8 AppContainer Loopback Utility 打开了胡桃
<img width="574" alt="屏幕截图 2023-01-23 122231" src="https://user-images.githubusercontent.com/97654557/214107175-3a1c9f26-5724-4b56-beea-3024ed98cc40.png">

以下是主机tracert的结果 地理位置 美国 匹兹堡

<img width="727" alt="屏幕截图 2023-01-23 122507" src="https://user-images.githubusercontent.com/97654557/214107631-35bce816-0dd4-4450-92d8-43704f69b5e3.png">

**Comment by Lightczx** [comment]
https://hutao-metadata.snapgenshin.com/Meta.json

**Comment by ywzkevin99** [comment]
请问是把这个json文件拷贝进 Document/Hutao/Metadata 文件夹吗，试了下还是有相同的问题

**Comment by Lightczx** [comment]
能访问这个网址，胡桃却会报错？

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by Masterain98** [comment]
> @Masterain98 FYI

用户能手动访问并下载，但胡桃客户端无法访问，难以判断。最好有更详细的信息。

**Comment by ywzkevin99** [comment]
可以访问，但是需要reset几下

**Comment by Masterain98** [comment]
> 可以访问，但是需要reset几下

你的地区和运营商？

**Comment by ywzkevin99** [comment]
地区是 美国匹兹堡 网络运营商是xfinity

**Comment by ywzkevin99** [comment]
还有就是当我尝试重新安装的时候，经常会卡在这个界面
<img width="886" alt="屏幕截图 2023-01-23 214357" src="https://user-images.githubusercontent.com/97654557/214201959-5bd36321-0e8b-415e-8ff0-065a17f13ee1.png">

**Comment by Lightczx** [comment]
static-zip.snapgenshin.com

**Comment by ywzkevin99** [comment]
这个貌似不行，显示 ‘你访问到了错误的链接’

**Comment by Lightczx** [comment]
ping

**Comment by ywzkevin99** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/97654557/214202461-21444754-03c4-475b-a305-5790f4495a70.png">

**Comment by ywzkevin99** [comment]
如果想完全卸载胡桃，除了删除Document/Hutao里的内容，还有什么需要删除的

**Comment by Masterain98** [comment]
> 如果想完全卸载胡桃，除了删除Document/Hutao里的内容，还有什么需要删除的

https://hut.ao/quick-start.html#%E5%8D%B8%E8%BD%BD%E8%83%A1%E6%A1%83%E5%B7%A5%E5%85%B7%E7%AE%B1

**Comment by Masterain98** [comment]
应该是程序的问题，而不是网络问题，正在排查

**Comment by Lightczx** [comment]
@ywzkevin99 上传 `%userprofile%/Documents/Hutao/log.db`

**Comment by FlandiaYingman** [comment]
感觉可能与ipv6有关

**Comment by ywzkevin99** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10494101/Log.zip)
貌似没法直接发db文件 所以zip里

**Comment by Lightczx** [comment]
BG_ERROR_CONTEXT_REMOTE_FILE, Error code: 0x80190191
错误与指定的远程文件相关。 例如，URL 不可访问。

BG_ERROR_CONTEXT_GENERAL_QUEUE_MANAGER, Error code: 0x8020006F
传输队列管理器生成了错误。

似乎确实和IPv6有关

**Comment by Lightczx** [comment]
可以试试代理回国

**Comment by Masterain98** [comment]
xfinity的话可以在路由器里禁用IPv6，如果方便的话可以禁用后试一段时间看问题能不能解决。

**Comment by ywzkevin99** [comment]
> xfinity的话可以在路由器里禁用IPv6，如果方便的话可以禁用后试一段时间看问题能不能解决。

试了下在WLAN状态中禁用IPv6就可以 多谢！
