### ISSUE TITLE
[Bug]: 从我的角色页面添加养成计算报错

### ISSUE THREAD

**Issue by icimence** [DGP-Studio/Snap.Hutao#392]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.13

### 问题分类

养成计算器

### 发生了什么？

在我的角色界面设置养成计算并点击确定，会出现报错提示请先登录
<img width="857" alt="image" src="https://user-images.githubusercontent.com/34977758/214243429-847cd9e1-2f67-446d-b500-35dc9d5b84ae.png">

### 你期望发生的行为？

正常添加到养成计划中

**Comment by Lightczx** [comment]
重新登录。

**Comment by icimence** [comment]
你确定你测试过了？我重新登陆之后提示更新用户信息成功依然会有报错。
<img width="857" alt="image" src="https://user-images.githubusercontent.com/34977758/214510468-77928a16-372e-465b-8dc7-e30970cacbca.png">

**Comment by icimence** [comment]
还是需要删除账号后重新添加

**Comment by Lightczx** [comment]
去设置里打开签到
会刷新你的ck

**Comment by icimence** [comment]
第一次打开签到对话框会提示尚未登录，第二次之后就可以了，养成计划也正常了
