### ISSUE TITLE
[Feat]: 圣遗物评分机制合并请求

### ISSUE THREAD

**Issue by Aliorpse** [DGP-Studio/Snap.Hutao#393]
### 背景与动机

使用本程序的面板查询功能时，因为与其他的主流面板查询程序机制不符，导致无法直观的看出圣遗物评分差别

### 想要实现或优化的功能

建议与其他面板查询程序作者交流，统一面板查询机制，以方便玩家使用
这里是我经常使用的圣遗物评分程序的一个案例，这个项目基于node.js，通过qq机器人实现面板查询功能
项目原仓库: https://github.com/Le-niao/Yunzai-Bot
含有拓展面板查询功能 插件仓库: https://github.com/yoimiya-kokomi/miao-plugin/

**Comment by Masterain98** [comment]
read doc plz 

[https://hut.ao/FAQ/artifact-rating-rules.html](https://hut.ao/FAQ/artifact-rating-rules.html)
