### ISSUE TITLE
[Feat]: 一些实用性功能建议

### ISSUE THREAD

**Issue by Aliorpse** [DGP-Studio/Snap.Hutao#394]
### 背景与动机

(理由编号对应想要添加的功能编号)
1. 强迫症每次运行游戏必须把启动器关掉，游戏结束后再次开启启动器很麻烦
2. 每次 如想解锁帧数进入原神，必须先右键程序，选择管理员权限运行，很麻烦
3. 每次点开诸如【深渊数据】这类功能，需要刷新一遍，影响使用体验
4. 电脑不好掉的用户如想打开本程序 需要花费一定时间，影响使用体验

### 想要实现或优化的功能

1. 添加 在游戏运行时启动器保持最小化 退出游戏启动器窗口显示 的功能
2. 添加 默认使用管理员权限运行 功能
3. 添加 定时刷新米游社数据 功能
4. 添加 随系统启动而自启 功能

**Comment by Masterain98** [comment]
Duplicate of #373

**Comment by Lightczx** [comment]
3 如果每次打开都是空数据需要刷新 说明数据文件已经炸了 保存祈愿与成就后删除 %userprofile%/Hutao/Docuements/Userdata.db

**Comment by Lightczx** [comment]
1 你是窗口化了原神么，如果是全屏的话，游戏画面反正遮住了也没啥影响吧。

**Comment by Aliorpse** [comment]
不是每次都是空数据 是每次都是以前的数据，无法更新到新数据

**Comment by Lightczx** [comment]
重度深渊玩家么？

**Comment by Aliorpse** [comment]
深渊数据只是一个例子，所有通过米游社接口获取的角色数据貌似都不能自动更新

**Comment by Aliorpse** [comment]
我的意思是 定时刷新米游社数据 而不是每次都需要用户手动点击刷新按钮

**Comment by Aliorpse** [comment]
并没有要求多频繁

**Comment by Lightczx** [comment]
所以具体是什么数据？

**Comment by Aliorpse** [comment]
祈愿记录，我的角色，深渊记录

**Comment by Aliorpse** [comment]
祈愿记录，我的角色，深渊记录

**Comment by Lightczx** [comment]
祈愿记录基本上不可能实现自动刷新
我的角色与深渊记录你想多久刷一次。

**Comment by Aliorpse** [comment]
在程序启动时默认刷新一次，之后每隔一小时刷新一次

**Comment by Lightczx** [comment]
需要注意的是这样的刷新非常耗时，如果你愿意启动时卡10s左右（

**Comment by Aliorpse** [comment]
emmm 能否让刷新线程与主线程分开

**Comment by Lightczx** [comment]
你可以注意到在刷新我的角色时会有阻止用户交互的弹窗出现，
弹窗是为了保证有足够的时间来写入数据库/请求API

关于线程的问题其实不是主要导致卡顿的因素
在请求API时会占用一个socket来进行网络数据传输，本身启动时已经有很多的请求在进行了
继续加入像我的角色相关的API请求很有可能会导致socket竞争

而且也需要编写额外的代码来确认你切换到对应的页面时
要正确的等待先前的刷新任务完成来呈现正确的，刷新后的数据
对于目前来说是非常不值得的，如果你愿意帮助我们编写相关的逻辑

我们非常欢迎

**Comment by Aliorpse** [comment]
好的 那我不打扰了
