### ISSUE TITLE
[Bug]: 某些未知情况下，鼠标滚轮无法控制界面滚动。

### ISSUE THREAD

**Issue by Ker0123** [DGP-Studio/Snap.Hutao#395]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.3.13.0

### 设备 ID

E02081A3BAAD06FE9E312FA09C5CC9DF

### 问题分类

用户界面

### 发生了什么？

滚动鼠标滚轮无法控制页面滚动，但利用触摸板可以，拖动界面右侧滚动条也可以。（我使用的是笔记本外接键盘鼠标）

### 你期望发生的行为？

滚动鼠标滚轮也能控制界面滚动

### 相关的崩溃日志

无崩溃情况

**Comment by Lightczx** [comment]
你开启看这个么
![image](https://user-images.githubusercontent.com/36357191/214503901-ecc7d084-8c42-4f72-b52c-a5de74c15e63.png)

**Comment by Ker0123** [comment]
已解决。
猜测是因为鼠标键位自定义软件 X-Mouse Button Control 的设置产生了某种冲突，关闭该选项问题消失。
![image](https://user-images.githubusercontent.com/73691442/214541315-64b2f502-2174-4ba7-bc4f-5b16682b4396.png)

**Comment by ywbear** [comment]
感谢大佬们，我也是类似的问题，已解决
