### ISSUE TITLE
[Bug]: Windows 10的alt+tab切换窗口处图标显示不正确

### ISSUE THREAD

**Issue by Mouseiswolf** [DGP-Studio/Snap.Hutao#397]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.3.13.0

### 问题分类

用户界面

### 发生了什么？

如图所示 程序在alt+tab窗口中无法显示正确的程序图标（胡桃头像）而是Windows默认的可执行文件图标 其他uwp应用（如Microsoft Store）则可以正常显示
![pic](https://user-images.githubusercontent.com/43296193/214575889-5b54b3b6-8b58-4be0-b2d8-8705aa1e0261.png)

### 你期望发生的行为？

应该在窗口中正确显示胡桃头像

**Comment by Masterain98** [comment]
#373

**Comment by Lightczx** [comment]
fixed
