### ISSUE TITLE
[Bug]: 字体在低 DPI 的显示器上显示效果不佳

### ISSUE THREAD

**Issue by mingyang2009** [DGP-Studio/Snap.Hutao#398]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.13.0

### 问题分类

用户界面

### 发生了什么？

程序所使用的字体在低 DPI 的显示器上显示效果不佳。
![image](https://user-images.githubusercontent.com/85012903/214592030-e42f6c6a-d75e-484c-a593-75ea18ed72bb.png)

如图所示，部分笔画多的汉字糊成了一团，在电脑上使用手机系统的字体并不是好的选择

### 你期望发生的行为？

1.将字体更换为微软雅黑或其他显示效果出色的字体
2.新增切换字体功能

**Comment by Lightczx** [comment]
#379
