### ISSUE TITLE
[Bug]: 无法更换主题，一直卡在亚克力

### ISSUE THREAD

**Issue by WuHuanHere** [DGP-Studio/Snap.Hutao#399]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.3.13.0

### 设备 ID

ED952115EFC0798C187C40B36A0FD633

### 问题分类

用户界面

### 发生了什么？

无法更换主题，一直卡在亚克力，材质名称变了，但是实际上的界面没变

**Comment by Lightczx** [comment]
win10是这样的
