### ISSUE TITLE
[Bug]: 手动安装无法下载图标，一键安装无法打开

### ISSUE THREAD

**Issue by nirvanan-zhang** [DGP-Studio/Snap.Hutao#400]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22622.575

### Snap Hutao 版本

1.3.12.0及1.3.13.0

### 设备 ID

无法打开

### 问题分类

安装和环境

### 发生了什么？

按照步骤安装之后，胡桃工具箱图标无法下载

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/new?assignees=Lightczx%2CMasterain98&labels=area-Network&template=network-issue.yml&title=%5BNetwork%5D%3A+%E5%9C%A8%E8%BF%99%E9%87%8C%E5%A1%AB%E5%86%99%E4%B8%80%E4%B8%AA%E5%90%88%E9%80%82%E7%9A%84%E6%A0%87%E9%A2%98
