### ISSUE TITLE
[Bug]: UserdataCorruptedException

### ISSUE THREAD

**Issue by Tian-Jiangyi** [DGP-Studio/Snap.Hutao#402]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.13.0

### 问题分类

成就管理

### 发生了什么？

从YaeAchievement导入成就，并且手动点击完成成就后关闭胡桃，再次打开胡桃进入成就管理页面时会报错，具体内容为以下：

UserdataCorruptedException
用户数据已损坏：单个成就存档内发现多个相同的成就id

且所有成就不管完不完成都未显示

**Comment by Lightczx** [comment]
截点图。。

**Comment by Tian-Jiangyi** [comment]
![O)EM7CASEYWI}XH5_E2U6PH](https://user-images.githubusercontent.com/59260897/215266875-d77d3417-b89c-41e0-8e8f-1e31f22966b3.png)
就是打个勾然后关掉再重开就这样了

**Comment by FlandiaYingman** [comment]
目测导入数据有问题（大概），方便发一下导入的数据吗

**Comment by Tian-Jiangyi** [comment]
文件不知道为啥传不上来，发网盘了

https://www.aliyundrive.com/s/uzKYPKsdrhf

**Comment by Tian-Jiangyi** [comment]
我是导入了再导出的

**Comment by Tian-Jiangyi** [comment]
微软商店版本已无该问题
