### ISSUE TITLE
点击Windows菜单右键胡桃卸载并清空%userprofile%/documents/Hutao后BUG弹出

### ISSUE THREAD

**Issue by qinsi001** [DGP-Studio/Snap.Hutao#403]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.3.13.0_x64

### 问题分类

安装和环境

### 发生了什么？

![image](https://user-images.githubusercontent.com/72976095/215025279-30a1c5b5-b8db-4c50-980f-80c420a6916a.png)

### 你期望发生的行为？

完全卸载之后没有有关任何Hutao的信息

**Comment by Lightczx** [comment]
《我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)》
