### ISSUE TITLE
[Feat]: 养成计划背包物品支持GOOD格式导入

### ISSUE THREAD

**Issue by adchoufeng** [DGP-Studio/Snap.Hutao#404]
### 背景与动机

背包物品一个一个填数量还是太慢了，但背包扫描工具例如天目Amenoma支持导出材料为GOOD格式的json文件

### 想要实现或优化的功能

在养成计划中支持导入其他背包扫描工具的导出文件

**Comment by Lightczx** [comment]
GOOD格式没什么好支持的。
