### ISSUE TITLE
可不可以增加多游戏路径

### ISSUE THREAD

**Issue by tggfaa** [DGP-Studio/Snap.Hutao#405]
### 背景与动机

我是一位双服玩家，游玩着国际和国内两个端，但是启动器只允许添加一个游戏路径

### 想要实现或优化的功能

希望可以添加多个游戏路径，并且在启动界面上放两个按钮来启动不同的游戏谢谢比如游戏路径1，2等

**Comment by Masterain98** [comment]
https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.4.0

1.4版本已支持切换服务器
