### ISSUE TITLE
[Bug]: 祈愿记录导入js后白屏

### ISSUE THREAD

**Issue by Fafaery** [DGP-Studio/Snap.Hutao#407]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22000.1455

### Snap Hutao 版本

1.4.0.0

### 问题分类

祈愿记录

### 发生了什么？

在使用Genshin-Wish-Exportv0.8.14的js导入胡桃后祈愿记录出现白屏现象，重装胡桃仍无法解决
<img width="592" alt="2be068ad7edf7b6cb7bd4dc4bf77c6b" src="https://user-images.githubusercontent.com/44135343/215258626-edb68643-61b5-4406-971f-9cceda52db6a.png">

**Comment by Lightczx** [comment]
那你倒是上传js啊

**Comment by Fafaery** [comment]
[Uploading UIGF_203982902_202301281834.zip…]()

**Comment by Fafaery** [comment]
> 那你倒是上传js啊
抱歉 这个是js
[UIGF_203982902_202301281834.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10527334/UIGF_203982902_202301281834.zip)

**Comment by Lightczx** [comment]
json包含我们不支持的繁体中文
