### ISSUE TITLE
[Feat]: 为“启动游戏”界面新增的两个提醒添加关闭按钮并不再显示

### ISSUE THREAD

**Issue by FlandiaYingman** [DGP-Studio/Snap.Hutao#408]
### 背景与动机

这种 tips 的信息不应该一直存在，当用户知悉相关信息后，这些信息便不再有继续出现的意义了

### 想要实现或优化的功能

加个关闭按钮，只显示一次后不再显示（或每次更新后显示）。

**Comment by Lightczx** [comment]
impl internally
