### ISSUE TITLE
[Bug]: 打开“角色资料”界面或在角色资料界面切换角色时报出TargetInvocationException

### ISSUE THREAD

**Issue by RadonTRD** [DGP-Studio/Snap.Hutao#409]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1194

### Snap Hutao 版本

1.4.0.0

### 设备 ID

81E448B6E42A6E6BEBABF5FC6841C230

### 问题分类

Wiki

### 发生了什么？

打开“角色资料”界面或在角色资料界面切换角色时报出大量异常，每次报出数量不等

![image](https://user-images.githubusercontent.com/99179101/215282417-d250793f-05b2-4f73-8d19-da428b1bf4c9.png)

### 相关的崩溃日志

[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10527892/Log.zip)

**Comment by Lightczx** [comment]
检查一下是否有图片没有显示

**Comment by RadonTRD** [comment]
> 检查一下是否有图片没有显示

只有页面背景没显示，不过重启几次应用，突然就显示出来了，然后也没报错了
