### ISSUE TITLE
“高级启动器”无法

### ISSUE THREAD

**Issue by shenbourne** [DGP-Studio/Snap.Hutao#412]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.3.13.0

### 设备 ID

BD0B9AC5B03D1858748E7959C552153E

### 问题分类

游戏启动器

### 发生了什么？

 胡桃工具箱
1.以管理员身份运行
2.登录了米游社通行证
3.绑定了该通行证对应的游戏角色
![Snipaste_2023-01-29_12-45-26](https://user-images.githubusercontent.com/121733766/215305467-7dcd6fbf-335a-48ee-90b9-853083501d32.png)

问题：
在上述前提下，点击右下角的“启动游戏”打开原神依旧弹出了登录界面
![Snipaste_2023-01-29_12-47-58](https://user-images.githubusercontent.com/121733766/215305536-0a9f5d15-b32c-47eb-bb12-4cb0e84d6b5d.png)

如有需要，我可以录制完整操作的视频

**Comment by shenbourne** [comment]
更新至最新版本（1.4.0.0）之后 ，依旧无法启动原神并自动登录
![Snipaste_2023-01-29_13-14-46](https://user-images.githubusercontent.com/121733766/215306515-26e1a0ea-75f6-44e2-a63c-ceff0d0ee2e6.png)

**Comment by Lightczx** [comment]
绑定UID与实际登录的账号无关

**Comment by shenbourne** [comment]
所以无法通过胡桃工具箱实现如同手机的切换账号的功能吗？就如下图，不用输入账号和密码就可以切换新的账号
![Snipaste_2023-01-29_13-21-57](https://user-images.githubusercontent.com/121733766/215306728-c5c2ac06-f895-4654-bdca-8996b25ddd4b.png)
