### ISSUE TITLE
[Network]: 启动原神国际服时近乎无法下载

### ISSUE THREAD

**Issue by konoluoboda** [DGP-Studio/Snap.Hutao#413]
### 提交你的网络诊断报告

问题如题，开了加速器和挂梯子都不行

### 你的地理位置

广东

### 你的运营商

中国移动

### 你的问题

连接速度慢

**Comment by Masterain98** [comment]
## 提交你的网络诊断报告
停下！
在填写下面的问题之前请先使用我们的网络诊断工具
这个工具将会生成一份报告，请将这份报告拖入下面的框中，让其与你的工单一起被上传提交

你可以点击下面的链接以下载网络诊断工具：
[胡桃资源站](https://d.hut.ao/d/tools/network-diagnosis-tool.exe)
[GitHub](https://github.com/Masterain98/network-diagnosis-tool/releases/latest/download/network-diagnosis-hutao.exe)

**Comment by Masterain98** [comment]
自行检测到米哈游国际服资源站点的连接情况 

autopatchhk.yuanshen.com

**Comment by shikukuya** [comment]
可以把collapse launcher的下载抄过来（neon-nyan/Collapse
