### ISSUE TITLE
[Bug]: 已设置好游戏路径的情况下，任务栏内的胡桃无法快捷启动游戏

### ISSUE THREAD

**Issue by JrantKing** [DGP-Studio/Snap.Hutao#414]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1194

### Snap Hutao 版本

1.4.0.0

### 问题分类

游戏启动器

### 发生了什么？

已设置好游戏路径的情况下，任务栏内的胡桃无法快捷启动游戏
![C0{O%A5CZ5$5YTO7Z@A3Y)E](https://user-images.githubusercontent.com/16501400/215312369-f8b3a5cb-0908-46c9-8f8e-599600a82b39.png)
正常情况应该是下图（群友的图）
![5LRWY$3QU7(Q@~RRR(5LFU](https://user-images.githubusercontent.com/16501400/215312390-3b0e7445-9489-4680-99a8-1f110926352e.jpg)

**Comment by Lightczx** [comment]
可能是魔改系统

**Comment by JrantKing** [comment]
next.itellyou下载的镜像并且是格式化后全新安装的，应该不可能是魔改系统

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/blob/f7f2d9c86775dfe08d2890f907214397419a4823/src/Snap.Hutao/Snap.Hutao/Core/JumpListHelper.cs#L20

**Comment by JrantKing** [comment]
我使用图中这个镜像安装了3个虚拟机测试，发现有两个虚拟机会出现这样的问题，有一个是正常的
我认为这可能是微软方面的bug
![QQ截图20230129231352](https://user-images.githubusercontent.com/16501400/215371772-f6ae3792-9e45-4eb7-89e7-d43ca3275452.png)

**Comment by JrantKing** [comment]
已经排查到问题了
![QQ截图20230202221328](https://user-images.githubusercontent.com/16501400/216348520-85459259-22fd-4e43-bd2d-1388cadaef4c.png)
在“开始”、“跳转列表”和“文件资源管理器”中显示最近打开的项目
这个选项是影响JumpList.IsSupported()的返回值的
![QQ截图20230202221339](https://user-images.githubusercontent.com/16501400/216348966-9767e423-0d54-4e26-8a24-9d108357b906.png)
