### ISSUE TITLE
[Feat]: 在应用中加入“”以管理员身份重启”按钮

### ISSUE THREAD

**Issue by konoluoboda** [DGP-Studio/Snap.Hutao#416]
### 背景与动机

每次以管理员身份启动都要退出后再右键启动，个人觉得为小白可能不太友好

### 想要实现或优化的功能

一个更简便的按钮，就像powertoys那样
![image](https://user-images.githubusercontent.com/76270408/215313449-f47edf0e-08d9-4eb3-982c-d8b8caae4a63.png)

**Comment by Lightczx** [comment]
无法实现
