### ISSUE TITLE
[祈愿记录导入]: 无法导入以前的祈愿记录

### ISSUE THREAD

**Issue by Barrrrrry1** [DGP-Studio/Snap.Hutao#418]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.3.13.0

### 设备 ID

7EFB36978A3DEEB82A639BF39EAB6290

### 问题分类

祈愿记录

### 发生了什么？

我按照UIGF的Excel 工作簿的原始数据表结构，把我的以前的祈愿记录也按照这个排版了，但是一直显示“文件的数据格式不正确”，我不知道哪里出了问题。可以帮我看一下哪里有问题吗？我来修改
![ZT8DFSKBOJJJ4EFLQMD`W%V](https://user-images.githubusercontent.com/123822531/215320715-ce45f1d7-e50a-4ba5-ad95-d07a61471367.png)
![)1A~)C_945X{T1H26GR1GW6](https://user-images.githubusercontent.com/123822531/215320721-ada0a18a-3615-40d0-8ef6-e1afe12b281f.png)
![NQJE4Z{R2DC2{D9$1K0{9VY](https://user-images.githubusercontent.com/123822531/215320734-9b6429b0-cbf6-4e99-9088-8007704d13c6.png)

### 你期望发生的行为？

期望：能导入进去原来的祈愿记录
现状：显示“文件的数据格式不正确”

**Comment by Masterain98** [comment]
胡桃仅支持 UIGF Json 导入

**Comment by Barrrrrry1** [comment]
> 

你好，我不知道怎么转成UIGF Json格式，可以教一下吗？

**Comment by Masterain98** [comment]
你的数据来源是什么？

**Comment by Barrrrrry1** [comment]
> 

我是找“提瓦特小助手”帮我把以前在他们那里的祈愿记录导出来了，给我的就是json格式的。我有试过把那个文件直接导入进去，但是显示“数据的 UIGF 版本过低，无法导入”，所以我才想着用文档导入

**Comment by Masterain98** [comment]
他们不是 UIGF 数据格式，你把你的 Json 文件发出来吧，我明天看能不能转换

**Comment by Barrrrrry1** [comment]
[抽卡记录.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10529716/default.zip)
你好，里面的json就是“提瓦特小助手”发我的文件，那个文档是我按照UIGF的文档格式自己做的文档，麻烦大佬了，非常感谢！

**Comment by Barrrrrry1** [comment]
> 

你好，我刚刚把文件发了出来，不知道你那边可不可以成功下载？

**Comment by Masterain98** [comment]
> 你好，我刚刚把文件发了出来，不知道你那边可不可以成功下载？

可以

**Comment by Barrrrrry1** [comment]
好的，麻烦大佬了，非常感谢！

**Comment by Masterain98** [comment]
[194421401.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10529881/194421401.zip)

**Comment by Barrrrrry1** [comment]
> [194421401.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10529881/194421401.zip)

还是显示“数据的 UIGF 版本过低，无法导入”
![_R}V)89IFP2%Y~SJY)UPQSO](https://user-images.githubusercontent.com/123822531/215330081-1ee9fd3c-5933-4d08-aac5-c4b3c5421fb9.png)

**Comment by Masterain98** [comment]
把`"uigf_version": "v2.3"`改成`"uigf_version": "v2.2"`

忘改了

**Comment by Barrrrrry1** [comment]
> 



> 

可以了！非常感谢大佬！爱你！
![013C41CA](https://user-images.githubusercontent.com/123822531/215330364-c1d5bc04-a90e-4014-b5e9-0cf354cdb9df.png)
