### ISSUE TITLE
养成计划—背包物品自动识别功能

### ISSUE THREAD

**Issue by yuluoyun** [DGP-Studio/Snap.Hutao#419]
### 背景与动机

在使用胡桃—养成计划时，背包物品手动输入过于麻烦，且此角色养成完毕后背包物品不变，导致下一个需养成角色要重新输入背包物品，过于麻烦。

### 想要实现或优化的功能

ocr识别功能或其他识别功能，角色添加“已完成计划”按钮，按下相应减少背包对应所需物品功能及防误触二次确认。

**Comment by Lew-1** [comment]
有没有好的开源ocr项目

**Comment by InMapleWoods** [comment]
> 有没有好的开源ocr项目

天目
