### ISSUE TITLE
[Bug]: 难以解决的HttpRequestException报错，根据文档教程操作无效

### ISSUE THREAD

**Issue by Mobius-Klein** [DGP-Studio/Snap.Hutao#420]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2546

### Snap Hutao 版本

1.4.0.0

### 问题分类

公告

### 发生了什么？

打开软件后提示“HttpRequestException
元数据校验文件下载失败
以一种访问权限不允许的方式做了一个访问套接字的尝试。（hutao-metadata.snapgenshin.com:80)"，
多次尝试重启应用和刷新无效，且尝试登录米哈游通行证显示
”状态：653366069 信息：[ListWrapper`1]请求异常“

**Comment by Mobius-Klein** [comment]
更新版本后仍未解决
![S8JM11(WYVD8VR0C_~$BZ_G](https://user-images.githubusercontent.com/123919764/215386732-8e7e7378-1920-492a-b1e1-e080b797cfd6.png)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/new?assignees=Lightczx%2CMasterain98&labels=area-Network&template=network-issue.yml&title=%5BNetwork%5D%3A+%E5%9C%A8%E8%BF%99%E9%87%8C%E5%A1%AB%E5%86%99%E4%B8%80%E4%B8%AA%E5%90%88%E9%80%82%E7%9A%84%E6%A0%87%E9%A2%98

**Comment by Mobius-Klein** [comment]
填写时按要求下载并运行了网络诊断工具（network-diagnosis-hutao），但是没有找到生成的报告

**Comment by Lightczx** [comment]
@Masterain98

**Comment by Mobius-Klein** [comment]
前几天家里网从电信换成了移动，现在感觉网速慢了很多，有没有可能是这个原因？

**Comment by Masterain98** [comment]
https://hutao-metadata.snapgenshin.com/Meta.json

这个是否可以访问

**Comment by Mobius-Klein** [comment]
![image](https://user-images.githubusercontent.com/123919764/215392593-ad3c84fe-9ce1-4126-858b-9f5d4d03e3d3.png)

**Comment by Masterain98** [comment]
cmd或PS中执行 `nslookup hutao-metadata.snapgenshin.com` 看下结果是什么

**Comment by Mobius-Klein** [comment]
![image](https://user-images.githubusercontent.com/123919764/215392959-77597c40-530b-466e-9972-b79471b277e5.png)

**Comment by Lightczx** [comment]
移动的DNS是这样的。

**Comment by Mobius-Klein** [comment]
难怪感觉网差了好多，现在玩原延迟有时候上100

**Comment by Masterain98** [comment]
中国大陆地区推荐使用以下 DNS
[DNSPod](https://www.dnspod.cn/Products/Public.DNS)
[114DNS](https://www.114dns.com/)
[Aliyun DNS](https://alidns.com/)

**Comment by Mobius-Klein** [comment]
翻其他案例的时候尝试了下这个命令：tracert hutao-metadata.snapgenshin.com
然后出了这玩应
![image](https://user-images.githubusercontent.com/123919764/215394340-5182d41a-3d50-4ab4-9803-382293478ccd.png)

**Comment by Mobius-Klein** [comment]
DNS怎么用？是连VPN吗？

**Comment by Mobius-Klein** [comment]
尝试过三家的DNS了，但还是加载不了
![image](https://user-images.githubusercontent.com/123919764/215395795-19cd60c7-3736-4089-a3ab-31de9cf6caed.png)

**Comment by Mobius-Klein** [comment]
尝试过三家的DNS了，但还是加载不了
![Uploading image.png…]()

**Comment by Masterain98** [comment]
重启系统或`ipconfig /flushdns`以确认应用新的DNS设置
之后还是`nslookup hutao-metadata.snapgenshin.com`检查

**Comment by Mobius-Klein** [comment]
![image](https://user-images.githubusercontent.com/123919764/215396802-6a57bcf9-b398-407f-b28c-2c1a623eacff.png)

**Comment by Masterain98** [comment]
很显然，没有更换DNS服务器

**Comment by Mobius-Klein** [comment]
手动换了，还是不行
![image](https://user-images.githubusercontent.com/123919764/215398727-67f60932-2d80-4d0c-8601-848a1e5ece51.png)

**Comment by Masterain98** [comment]
1. 你的链路速度只有 10Mbps，如果不是刻意设置，大概率是有网络基础设施故障
2. 你的 IP 地址是手动分配的，这通常是高级做法，请检查配置
3. 尝试禁用 IPv6

**Comment by Lightczx** [comment]
有一个很简单的方法，打10086，骂他们说网速慢（

**Comment by Mobius-Klein** [comment]
6，我没管它，换回自动之后突然跑到1000Mps了，但还是加载不出来

**Comment by Mobius-Klein** [comment]
![image](https://user-images.githubusercontent.com/123919764/215400774-750f36a4-bb59-4ee4-a509-1164c429f544.png)

**Comment by Mobius-Klein** [comment]
![image](https://user-images.githubusercontent.com/123919764/215400812-eeb64e3a-4db0-46a7-aedf-52b0668a369c.png)

**Comment by Masterain98** [comment]
尝试执行：
1. 在路由器的DHCP设置中使用上述的DNS供应商
2. 在路由器中禁用IPv6
3. 重启路由器和电脑，让IP地址重新分配

**Comment by Mobius-Klein** [comment]
![image](https://user-images.githubusercontent.com/123919764/215402404-a9a33f6f-04e1-4a5f-a539-3b83f303a183.png)

**Comment by Mobius-Klein** [comment]
死都进不了后台，密码明明是对的还说有误

**Comment by Mobius-Klein** [comment]
![image](https://user-images.githubusercontent.com/123919764/215403939-fda3f704-5b07-496b-a791-4d89ca16e426.png)

**Comment by Mobius-Klein** [comment]
还是不行
![image](https://user-images.githubusercontent.com/123919764/215404329-4b3de051-8c8f-403d-b3ad-cf1ca8f05cc7.png)

**Comment by Masterain98** [comment]
联系你的运营商解决网络问题，这是你的本地网络问题

**Comment by Mobius-Klein** [comment]
ok，有时间去跟10086对线
