### ISSUE TITLE
[Bug]: 管理员权限启动软件没有主界面弹出

### ISSUE THREAD

**Issue by novaho1999** [DGP-Studio/Snap.Hutao#421]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

win 10.0.19043.1165

### Snap Hutao 版本

1.4.0.0及1.4.1.0   x64

### 设备 ID

F4ADB967DB1953387880A16CE86EDC5B

### 问题分类

安装和环境

### 发生了什么？

双击启动软件 功能正常，可以启动游戏。
无法使用管理员权限启动软件：点击 “以管理员身份运行” 选项后，有弹出 ”用户账户控制“ 窗口，选择 “是”后，没有主界面弹窗，也没有后续反应。

尝试过 安装后重启系统；卸载后，手动安装、脚本安装、一键安装；使用其他版本，都无法解决问题。

### 你期望发生的行为？

在管理员身份下 显示主界面 并能使用 启动器功能

**Comment by Lightczx** [comment]
检查 eventvwr

**Comment by novaho1999** [comment]
> 检查 eventvwr
具体应该怎么看

**Comment by Lightczx** [comment]
www.baidu.com

**Comment by novaho1999** [comment]
> [www.baidu.com](http://www.baidu.com)
这个嘛？

错误应用程序名称: Snap.Hutao.exe，版本: 1.0.0.0，时间戳: 0x6377ba57
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.1151，时间戳: 0x891df6d3
异常代码: 0xc000027b
错误偏移量: 0x000000000010bd3e
错误进程 ID: 0x4180
错误应用程序启动时间: 0x01d9346f9093c3c3
错误应用程序路径: C:\Program Files\WindowsApps\7f0db578-026f-4e0b-a75b-d5d06bb0a74d_1.4.0.0_x64__7jfyf5536hdrr\Snap.Hutao.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 1d9473dc-784b-48cc-ae1d-817f7c7a9a3e
错误程序包全名: 7f0db578-026f-4e0b-a75b-d5d06bb0a74d_1.4.0.0_x64__7jfyf5536hdrr
错误程序包相对应用程序 ID: App

**Comment by Lightczx** [comment]
找 .NET Runtime Error，不需要 Application Error

**Comment by novaho1999** [comment]
> 找 .NET Runtime Error，不需要 Application Error
相关且最近的只有这个

Application: Snap.Hutao.exe
CoreCLR Version: 7.0.122.56804
.NET Version: 7.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFBA08147F8
Stack:

**Comment by wen12389** [comment]
找不到.NET Runtime Error，管理员模式打不开，错误记录只有Application Error

**Comment by Lightczx** [comment]
#533 可能是没有.NET 7 Runtime 的问题

**Comment by Lightczx** [comment]
将系统升级至 22H2
