### ISSUE TITLE
无法启动游戏[Bug]: 

### ISSUE THREAD

**Issue by zb7777** [DGP-Studio/Snap.Hutao#423]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22000.1455

### Snap Hutao 版本

1.4.1.0

### 问题分类

游戏启动器

### 发生了什么？

设置启动路径后，点击启动游戏，没有反应，没有弹窗，没有提示
![image](https://user-images.githubusercontent.com/106429521/215501126-ab480370-12a3-4011-8a45-2dd19147d6d4.png)
![image](https://user-images.githubusercontent.com/106429521/215501280-3f737881-c243-4352-8d02-cb0ca4e1226b.png)
固定到任务栏也没有启动游戏选项
![image](https://user-images.githubusercontent.com/106429521/215501629-d919dc76-fb06-4f92-9a58-9b2b17e32a6d.png)
隔壁寻空选择同一路径可正常启动
![image](https://user-images.githubusercontent.com/106429521/215501855-d0a8a421-221e-4b92-af96-11298b25131c.png)
![image](https://user-images.githubusercontent.com/106429521/215502197-1199d533-703f-443b-b86e-25a5eed72ddf.png)

### 你期望发生的行为？

期望正常启动

**Comment by zb7777** [comment]
> 请提供设备Id

24066BE8F1B79EBAF12D5755B6D5B234

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 24066BE8F1B79EBAF12D5755B6D5B234

**Comment by zb7777** [comment]
> @dgp-bot 拉取日志 24066BE8F1B79EBAF12D5755B6D5B234

空日志，我卸载重装过..

**Comment by Lightczx** [comment]
卸载不影响日志

**Comment by zb7777** [comment]
> 卸载不影响日志

那我现在还要提供啥吗

**Comment by Lightczx** [comment]
等下版本再看

**Comment by zb7777** [comment]
新安装完，设置路径，管理员启动，服务器选择为国服，启动，转化，在之后可正常启动了。​
启动正常，不过任务栏还是没有右键启动​

**Comment by Lightczx** [comment]
#414
