### ISSUE TITLE
[Feat]: 期望在【我的角色】内【属性】有角色期望属性数值显示，以快速了解该角色需要优化的

### ISSUE THREAD

**Issue by gzyhelloworld** [DGP-Studio/Snap.Hutao#424]
### 背景与动机

![image](https://user-images.githubusercontent.com/26321154/215512233-fa7a61fa-4591-4ea7-9f92-d4a325d85cdc.png)
例如上图我想要看角色属性游戏内也可以看到，希望有一个期望数值对比一下，让我知道我的充能是高了还是低了或者攻击是无效溢出啥的

### 想要实现或优化的功能

角色属性有一个期望数值对比

**Comment by Lightczx** [comment]
面板无绝对
