### ISSUE TITLE
[Bug]: TargetlnvocationException

### ISSUE THREAD

**Issue by asjhdfjh** [DGP-Studio/Snap.Hutao#425]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [x] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.1.0

### 设备 ID

7D3E0553FD53B6E947DA8C886C5C55EB

### 问题分类

胡桃数据库

### 发生了什么？

点击【角色资料】，弹出一堆报错，这里摘取一条错误，如下：
． TargetlnvocationException
应用 Compositionlmage 的源时发生异常
Exception has been th rown by the ta rg et Of a n invocation.

### 你期望发生的行为？

无响应

**Comment by Lightczx** [comment]
图片加载问题

**Comment by asjhdfjh** [comment]
那要如何解决？
