### ISSUE TITLE
无法提交深渊记录

### ISSUE THREAD

**Issue by zxs721** [DGP-Studio/Snap.Hutao#426]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2486

### Snap Hutao 版本

1.4.1.0

### 问题分类

胡桃数据库

### 发生了什么？

在“深渊记录”中点击”刷新数据“后，弹出如下提示
![1675093359767](https://user-images.githubusercontent.com/75251152/215523502-b39e0997-3afc-4497-a268-9afaed2ab080.jpg)

### 你期望发生的行为？

无法读取深渊数据

**Comment by Lightczx** [comment]
重新登录
