### ISSUE TITLE
第一次转换国际服会重复下载同一个文件

### ISSUE THREAD

**Issue by FYDmalingshu** [DGP-Studio/Snap.Hutao#427]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.1.0

### 问题分类

安装和环境

### 发生了什么？

第一次使用转换国际服功能 自动下载一直在反复下载同一个文件显示路径是 Genshinlmpact_Data/globalgamemannagers.assets 是一个37.8MB的文件
![QQ图片20230131003634](https://user-images.githubusercontent.com/52628041/215538358-82c324e5-2982-44c5-ab53-6641b8040f80.jpg)

### 你期望发生的行为？

正常安装？

**Comment by Lightczx** [comment]
网络问题，文件校验失败会无限反复下载，直到校验成功

**Comment by FYDmalingshu** [comment]
昨天反复验证那个文件半小时没成功 我就结束了进程 然后旧版和新版胡桃启动器都不能正常打开原了
![QQ图片20230131213020](https://user-images.githubusercontent.com/52628041/215774134-c1d1b5ad-1e6f-4a57-b502-d3b8720c7f02.png)
弹了这个报错然后×掉或者确认都会蓝屏     现在正在用官方启动器效验重新下载游戏文件  之后就能恢复吗

**Comment by Lightczx** [comment]
如果是国服转国际服 将游戏目录的 GenshinImpact_Data 重命名为 YuanShen_Data,反之亦然
然后使用官方启动器校验游戏完整性
