### ISSUE TITLE
[Feat]: 为实时便笺的通知添加webhook和/或命令的支持

### ISSUE THREAD

**Issue by ohto-ai** [DGP-Studio/Snap.Hutao#431]
### 背景与动机

有一定基础的开发者，可以利用webhook发送更多样的通知，如直接发送到飞书、企业微信等支持webhook机器人的通讯软件，甚至可以利用自建的服务器深度定制一些功能。

### 想要实现或优化的功能

1. 为原粹树脂、洞天宝钱、参量质变仪添加webhook的通知接口，并将具体的数据作为payload发送。
2. [可选] 为原粹树脂、洞天宝钱、参量质变仪添加命令的通知接口，并将具体的数据作为执行参数。

**Comment by Lightczx** [comment]
webhook需要每个服务单独适配，可以给出你期望的webhook服务

**Comment by Ohto-Ai** [comment]
> webhook需要每个服务单独适配，可以给出你期望的webhook服务

飞书、钉钉、企业微信这些平台的差异很大，我觉得有三个方案可以考虑一下：

1. 为飞书、钉钉、企业微信等常用的平台均提供对应的适配，但这需要一定的工作量，并且不适合用户自定义的webhook；
2. 提供一个最**基本的payload**，要求用户搭建Server处理这个payload，后续适配飞书、钉钉等平台完全交给用户去做，自由度会很高；
3. 采用**插件**/**脚本**形式实现这个功能，针对不同平台，可以自制插件/脚本完成这个功能。

-----
简单的payload或许可以类似如下这个例子，那么程序需要用户提供的就是webhook的地址以及约定的secret（或许不需要？）。
```json
{
    "uid": 114514,
    "timestamp": 1610000000,
    "secret": "FakeSecret",
    "daily_note": {
        "resin": 140,
        "home_coin": 2000,
        "expedition": [3600, 3600, 3600, 3600, 3600]
    }
}
```

**Comment by Ohto-Ai** [comment]
如果是直接在软件上实现，能否优先实现飞书呢？
这是一个示例payload
```json
{
    "msg_type": "post",
    "content": {
        "post": {
            "zh_cn": {
                "title": "Title",
                "content": [
                    [
                        {
                            "tag": "text",
                            "text": "This is a "
                        },
                        {
                            "tag": "a",
                            "text": "URL",
                            "href": "https://github.com/"
                        }
                    ]
                ]
            }
        }
    }
}
```

**Comment by Masterain98** [comment]
https://github.com/y1ndan/onepush/tree/main/onepush/providers

这里有很多接口可以参考

**Comment by Lightczx** [comment]
为Webhook添加了最低限度的支持

**Comment by ohto-ai** [comment]
> 为Webhook添加了最低限度的支持

Thanks! 晚上会试一下

**Comment by Lightczx** [comment]
仅支持 POST 到指定地址，格式固定为整个实时便笺数据的 Json
你始终可以通过中转服务器达成自己的目的

另外由于尚未正式发布，需要安装最新测试版

**Comment by ohto-ai** [comment]
好的，会试试包含commit的dev版本 [2023.10.26.2](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/2023.10.26.2)

**Comment by ohto-ai** [comment]
Hi, 使用 [2023.10.26.3](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/2023.10.26.3) 版本，设置webhook后app会崩溃

hook url: https://hook.ohtoai.top/post/hutao_notify

screenshot
![hutao_alpha_test](https://github.com/DGP-Studio/Snap.Hutao/assets/46275725/e53a7274-c168-4091-9eaf-1861afd07fa3)


使用 `api fox` 测试
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/46275725/e6b4fb02-7dad-49a4-8c16-b725cc76d723)

**Comment by Masterain98** [comment]
问题能复现，服务端没有收到请求

**Comment by Lightczx** [comment]
@Masterain98 @ohto-ai fixed

**Comment by Masterain98** [comment]
> @Masterain98 @ohto-ai fixed

Build failed

**Comment by Lightczx** [comment]
https://learn.microsoft.com/en-us/dotnet/framework/tools/resgen-exe-resource-file-generator

CI 需要修改

> Creates a strongly typed class that provides access to individual named resources and to the [ResourceManager](https://learn.microsoft.com/en-us/dotnet/api/system.resources.resourcemanager) instance.

**Comment by ohto-ai** [comment]
使用 [2023.10.27.2](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/2023.10.27.2) 版本验证成功
```log
[2023-10-27 19:35:54.165] [webhook] [info] Trigger hook `post_test`
[2023-10-27 19:35:54.180] [webhook] [info] 50.114.59.28 POST /post/hutao_notify 3300 bytes User-Agent: Snap Hutao/2023.10.27.2
```
