### ISSUE TITLE
[Bug]: 胡桃内使用登陆米哈游通行证登录报错

### ISSUE THREAD

**Issue by tangtangebusi** [DGP-Studio/Snap.Hutao#433]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.1.0

### 设备 ID

A2B363A84BBD3743A3F4CDFBC85B43C4

### 问题分类

用户界面

### 发生了什么？

胡桃内使用登陆米哈游通行证登录  登录米哈游通行证账号后点我已登陆报错  换另一个账号同样报错
![image](https://user-images.githubusercontent.com/67052443/216022971-af3ff966-79f8-4fdc-85b5-970c908854a3.png)
![image](https://user-images.githubusercontent.com/67052443/216023418-492cba74-bac5-41b4-b457-e837e922f3aa.png)

### 你期望发生的行为？

fix up

### 相关的崩溃日志

网盘
https://www.123pan.com/s/MWPlVv-2g8G

**Comment by Lightczx** [comment]
网络问题
