### ISSUE TITLE
使用管理员身份打开没反应

### ISSUE THREAD

**Issue by ljy888666** [DGP-Studio/Snap.Hutao#434]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19042.928

### Snap Hutao 版本

1.4.1.0

### 问题分类

安装和环境

### 发生了什么？

可以正常打开软件，但是无法通过管理员身份打开软件。
![image](https://user-images.githubusercontent.com/61298509/216099755-f162726a-48f1-4cc2-aa78-a0c704485a1e.png)
如图，点开后无反应，杀毒软件已全部关闭。
![image](https://user-images.githubusercontent.com/61298509/216100256-d6fa8fe2-6c8c-4acf-a6c5-a603bf6ead4f.png)
每两次用管理员身份运行，任务管理器中显示运行一次，这次打开显示运行，下次打开完全没反应。

**Comment by Masterain98** [comment]
在 eventvwr 中找 .NET runtime error

**Comment by Masterain98** [comment]
#421

**Comment by ljy888666** [comment]
![image](https://user-images.githubusercontent.com/61298509/216104582-037c5476-281c-4722-b00a-9f63d76f60ba.png)
这边显示找不到

**Comment by ljy888666** [comment]
![image](https://user-images.githubusercontent.com/61298509/216105698-91dbf253-7107-4a6c-b831-c82b7c0a3332.png)
是这样看吗

**Comment by Masterain98** [comment]
找跟 `Snap.Hutao.exe` 相关的错误

**Comment by ljy888666** [comment]
无法打开情况都是显示这样的错误

**Comment by Lightczx** [comment]
#421

**Comment by wen12389** [comment]
我也有一样的问题，请问如何解决的

**Comment by Masterain98** [comment]
> 我也有一样的问题，请问如何解决的
> 

提交你的日志
