### ISSUE TITLE
[Bug]: 转化国际服时，一直重复下载一个大小为47.1MB的相同文件

### ISSUE THREAD

**Issue by YIMUYONG** [DGP-Studio/Snap.Hutao#436]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.1.0

### 问题分类

游戏启动器

### 发生了什么？

当我转换国际服并启动游戏时，软件在重复下载一个名为global-metadata的文件，大小为47.1MB，以及位置为Genshin Impact\Genshin Impact Game\GenshinImpact_Data\Native\Data\Metadata
然后一直重复此循环，并不启动游戏，此循环持续了半小时之久，且不会自动终止。

![image](https://user-images.githubusercontent.com/42272766/216269549-5029968f-123e-4567-be33-40c3f7e0bedf.png)

### 你期望发生的行为？

希望可以将官服转国际服所需要的文件（软件的下载速度也十分感人），提供一个单独的下载链接，来让个人下载并装载。

**Comment by Lightczx** [comment]
#427
