### ISSUE TITLE
希望增加图片缓存功能，方便离线使用

### ISSUE THREAD

**Issue by tiantianyigntao5** [DGP-Studio/Snap.Hutao#440]
### 背景与动机

因为在线加载总是出现奇奇怪怪的问题，尤其是角色资料和武器资料那里，用的是微软商店的最新版本
![QQ截图20230203112530](https://user-images.githubusercontent.com/119735343/216505547-fd9a8285-87f3-4284-a8bb-4f5c47039bf2.png)
![QQ截图20230203112722](https://user-images.githubusercontent.com/119735343/216505642-ce5bf6ef-90f2-4b78-80bc-d28ded67b954.png)

### 想要实现或优化的功能

实现武器资料 角色资料 等一切需要加载图片等资源的离线下载功能

**Comment by Lightczx** [comment]
#441
