### ISSUE TITLE
[Bug]: 切换账号

### ISSUE THREAD

**Issue by yuluoyun** [DGP-Studio/Snap.Hutao#443]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.11.0

### 问题分类

游戏启动器

### 发生了什么？

错误描述：
Win32Exception
An errpr occurred teying to start process 'PowerShell'with working directory 'C:\WINDOWS\system32'. 文件名或拓展名太长

安装方式为：Microsoft Store直装
其他问题已排除 重装/重启电脑/注册表修改都无效。

### 你期望发生的行为？

解决这个问题。

**Comment by Masterain98** [comment]
参照该文档来解决

https://hut.ao/FAQ/exceptions.html#win32exception
