### ISSUE TITLE
[Bug]: 在这里填写一个合适的标题

### ISSUE THREAD

**Issue by zhangxufeng717** [DGP-Studio/Snap.Hutao#444]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2364

### Snap Hutao 版本

1.2.13.0

### 问题分类

其它

### 发生了什么？

上传深渊数据的时候报错 状态500020 信息无效的提交数据

**Comment by Lightczx** [comment]
更新
