### ISSUE TITLE
snap 胡桃有明显字体模糊

### ISSUE THREAD

**Issue by LeiRent** [DGP-Studio/Snap.Hutao#445]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2364

### Snap Hutao 版本

1.4.11.0

### 设备 ID

952885D02D16C81BDC0D7908209E20B3

### 问题分类

用户界面

### 发生了什么？

之前用的胡桃资源站里面下的1.3.9.0没有什么毛病，现在打开胡桃工具箱网页，用微软商店下的1.4.11.0有明显的字体模糊
第一张是1.4.11.0第二张是1.3.9.0第三张是对比
![(9DWNDNPQR (5{6RLX72{MK](https://user-images.githubusercontent.com/124379155/216643650-7e9dda5b-2675-4bea-9c30-e4335394eb34.png)
![QG7CMJYG$F W)SOJSJ2S6S](https://user-images.githubusercontent.com/124379155/216643823-95b4ca01-de51-4a2d-b33e-21afb23a2ffb.png)
![BF9TN_PKUSISAB{}_KXGPMF](https://user-images.githubusercontent.com/124379155/216643908-fa43516b-3cfe-4a70-9433-479f78f4da91.png)

**Comment by LeiRent** [comment]
分辨率为1920×1080，缩放比为100%

**Comment by Lightczx** [comment]
#379
