### ISSUE TITLE
管理员运行后无法弹出窗口

### ISSUE THREAD

**Issue by jinyan-hub** [DGP-Studio/Snap.Hutao#448]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

10.0.18363.592

### Snap Hutao 版本

1.4.0.0

### 问题分类

安装和环境

### 发生了什么？

鼠标右键选择管理员运行时不弹出窗口

### 你期望发生的行为？

弹出Snap Hutao窗口

**Comment by jinyan-hub** [comment]
怎么开issue

**Comment by Masterain98** [comment]
在 eventvwr 中找 .NET runtime error

**Comment by jinyan-hub** [comment]
NET_6.0可以用吗

**Comment by Masterain98** [comment]
> NET_6.0可以用吗

容器化应用会在容器内自动下载需要的环境，你宿主机上装不装无所谓

**Comment by jinyan-hub** [comment]
好的
