### ISSUE TITLE
[Feat]: 希望能从胡桃直接打开启动器和截图文件夹

### ISSUE THREAD

**Issue by Donte1l** [DGP-Studio/Snap.Hutao#450]
### 背景与动机

1.打开启动器是为了能够在大版本更新时更新启动器；
2.打开截图文件夹是为了省去先打开启动器，再通过启动器点击右上角的截图文件夹这两个步骤。

### 想要实现或优化的功能

希望能像snap一样将软件添加到右下角（这个不是重点，但是也希望能有），右键可以选择打开游戏、打开启动器、打开截图文件夹。或者说在软件主题的工具->启动游戏这个界面中添加这两个新按键。

**Comment by Lightczx** [comment]
截图文件夹可以打开，打开启动器暂时不考虑
