### ISSUE TITLE
[Feat]: 希望从Windows通知中进入游戏步骤不要这么繁琐

### ISSUE THREAD

**Issue by Donte1l** [DGP-Studio/Snap.Hutao#452]
### 背景与动机

在Windows中弹出的体力已满通知中点击启动游戏，乍一看什么都没发生，实际上是hutao自己开了个选择登录账号的窗口（而且也没有将这个窗口置顶，必须手动在任务栏中点开才行），需要手动选择这个窗口再点一次启动游戏才行。

### 想要实现或优化的功能

希望能在hutao中只记录了一个账号的前提下能够直接启动游戏，并且在有两个及以上账号的情况下点击启动游戏，将选择账号的窗口置顶，以便选择。

**Comment by Masterain98** [comment]
> 没有将这个窗口置顶，必须手动在任务栏中点开才行

#373 来自微软的上游问题
