### ISSUE TITLE
[Feat]: 希望增加圣遗物图鉴功能

### ISSUE THREAD

**Issue by tiantianyigntao5** [DGP-Studio/Snap.Hutao#454]
### 背景与动机

方便查询圣遗物信息，以及圣遗物故事，圣遗物适配角色等等

### 想要实现或优化的功能

增加圣遗物图鉴，展示圣遗物信息，以及适配角色，实现类似于角色搭配使用率和武器角色使用率等的功能

**Comment by Lightczx** [comment]
#272
