### ISSUE TITLE
摹本工具：获取摆件列表，支持数量修改

### ISSUE THREAD

**Issue by lingkai5wu** [DGP-Studio/Snap.Hutao#455]
### 背景与动机

原神尘歌壶开放了摹本功能，但想要复制一个摹本需要准备不少摆件。
在游戏内查看摹本的摆件较为繁琐，且难以记录和利用，米游社的养成查询同样不便。
希望能够有更方便更优雅获取摹本摆件列表，并指导摆件制作的工具。

### 想要实现或优化的功能

https://github.com/lingkai5wu/getYsFurnitureList

额外功能：能够在胡桃工具箱内管理所有的摆设，类似培养计划一样，加入新摹本即可直接获取已有数量。

**Comment by Lightczx** [comment]
#217
