### ISSUE TITLE
[Bug]: 导入寻空导出的uigf格式json文件无反应

### ISSUE THREAD

**Issue by QinMoMeak** [DGP-Studio/Snap.Hutao#456]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.11.0

### 问题分类

祈愿记录

### 发生了什么？

如果之前未导入过任何祈愿记录，导入后该页面为白屏
如果之前导入过任何祈愿记录，导入后该页面不变化
（因上传限制，请删除后缀txt）
[Wishlog_193563882_20230205_103252.json.txt](https://github.com/DGP-Studio/Snap.Hutao/files/10670895/Wishlog_193563882_20230205_103252.json.txt)

**Comment by Lightczx** [comment]
https://github.com/xunkong/xunkong/issues/403

**Comment by Scighost** [comment]
寻空不会对 `item_type` 做校验和修改，这证明获取记录的时候该值就是英文，但鉴于你的记录中 `name` 又是中文，可能是这些数据你是从别的地方导入到寻空中的，也可能是米哈游的服务器出错了。
