### ISSUE TITLE
启动游戏时，文件或扩展名太长

### ISSUE THREAD

**Issue by 1634913821** [DGP-Studio/Snap.Hutao#457]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

10

### Snap Hutao 版本

最新

### 设备 ID

F8D0E99337CE75506859D2B31DEA365D

### 问题分类

游戏启动器

### 发生了什么？

启动游戏时，文件或扩展名太长
![TIQK$LEJ{UXKZ`II6581MES](https://user-images.githubusercontent.com/124655374/217157585-9f937604-a2b1-421e-9136-e4134da9d210.jpg)

**Comment by Masterain98** [comment]
https://hut.ao/FAQ/exceptions.html#win32exception
