### ISSUE TITLE
[Bug]: 频繁弹出堆栈错误

### ISSUE THREAD

**Issue by hhhggg233** [DGP-Studio/Snap.Hutao#458]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.1.0

### 设备 ID

1C084EB185FA452509EF7B37B56B8894

### 问题分类

其它

### 发生了什么？

不定时弹出堆栈错误对话框
![L6RM)}U%HM84)EA)(T(_{ R](https://user-images.githubusercontent.com/25274882/217179306-cf2c1865-4a17-4557-bb36-738800fb4506.png)

**Comment by Lightczx** [comment]
使用商店版
