### ISSUE TITLE
安装了微软商店的版本后就再也打不开了

### ISSUE THREAD

**Issue by summer-breeze123** [DGP-Studio/Snap.Hutao#461]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.11.0

### 问题分类

安装和环境

### 发生了什么？

卸载了之前用压缩包安装的版本，安装了微软商店的版本，然后就无法打开了。

**Comment by Masterain98** [comment]
在 eventvwr 中找  .NET runtime error 和 胡桃的应用程序错误
