### ISSUE TITLE
[Network]: 首次加载资源可以设置使用系统代理

### ISSUE THREAD

**Issue by wanyunr** [DGP-Studio/Snap.Hutao#462]
### 提交你的网络诊断报告

首次启动，会卡在这里很长时间。
请问资源是在哪托管的呢？如果是GitHub之类的，能否增加`使用系统代理`进行下载的设置
![image](https://user-images.githubusercontent.com/105478325/217292292-9bc065a9-0105-4636-831d-88b8e9cd932c.png)

### 你的地理位置

湖南长沙

### 你的运营商

中国电信

### 你的问题

连接速度慢

**Comment by Masterain98** [comment]
微软，IP地址是`13.107.136.8`。感觉只是临时抽风。

如果用代理的话使用系统代理并解除容器限制即可，文档中有描述。
