### ISSUE TITLE
过多的错误提示

### ISSUE THREAD

**Issue by shenbourne** [DGP-Studio/Snap.Hutao#463]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本 ：
19045.2486
### Snap Hutao 版本 ：
1.4.0.0

### 问题分类
用户界面

### 发生了什么？
![image](https://user-images.githubusercontent.com/121733766/217303351-53c9f559-c394-43dc-b906-a5384edbc985.png)
过多的错误提示挡住了我的界面。在我使用之前，我不得不一项项的叉掉。
几乎每次打开界面都会有几十条错误通知

### 期望

1. 是否能将错误提示集成至导航栏？

2. 或者将同类型的错误聚集至一条中（**例如这样**）？
> ![image](https://user-images.githubusercontent.com/121733766/217302773-77b1ce55-cd44-458c-a5f0-181c125c2ad5.png)
（我的米游社账号有限制 现在就是登不上）

3. 抑或提供一键关闭的按钮？

**Comment by shenbourne** [comment]
> 请更新至最新版本： 稳定版： [1.4.1](https://github.com/DGP-Studio/Snap.Hutao/releases/download/1.4.1/Snap.Hutao_1.4.1.0_x64_Test.zip) 测试版： [2023.1.30.1](https://github.com/DGP-Studio/Snap.Hutao/releases/download/2023.1.30.1/Snap.Hutao.Alpha-2023.1.30.1.msix)

……胡桃工具箱在 Microsoft Store 中无更新选项

**Comment by Lightczx** [comment]
去设置界面打开两次签到对话框

**Comment by shenbourne** [comment]
谢谢！
话说能把这些图标放大些吗？这些图标实在是太小了，我想稍微放大点一定会改善视觉体验。
如同我的笔记本屏幕只有14英寸，每个图标在我的显示器上只有1cm长宽
![image](https://user-images.githubusercontent.com/121733766/218026343-341a2141-0c4f-4c8e-817d-9e8360648e8d.png)
