### ISSUE TITLE
[Bug]: 深渊记录上传失败

### ISSUE THREAD

**Issue by WanLI660** [DGP-Studio/Snap.Hutao#465]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22000.1516

### Snap Hutao 版本

1.4.11.0

### 设备 ID

258B6820E926AA68DEC53DC10AC98EB4

### 问题分类

胡桃数据库

### 发生了什么？

深渊数据上传失败，如图。

尝试了删除账号，还有卸载重装，问题同样发生。
<img width="890" alt="image" src="https://user-images.githubusercontent.com/81896668/217381417-e87b4796-ff1e-405e-9da1-083f559533ab.png">

### 你期望发生的行为？

感谢大佬，辛苦了！
希望能成功上传吧。

**Comment by Lightczx** [comment]
fixed
