### ISSUE TITLE
[Bug]: 养成计划上传数据信息请求异常

### ISSUE THREAD

**Issue by HojoRenka** [DGP-Studio/Snap.Hutao#470]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.11.0

### 设备 ID

FFDCAEEBE9DED2E3786FDA1F98A1DB81

### 问题分类

胡桃数据库

### 发生了什么？

养成计算上传失败，如图。
无论从任何界面建立养成计划均报错653366069
尝试了删除账号，还有卸载重装，问题同样发生。
![QQ截图20230208143452](https://user-images.githubusercontent.com/124763816/217453596-1e2a22d8-f367-4598-8ce0-0b197d262a06.png)

### 你期望发生的行为？

大佬辛苦了
这个问题比较频繁发生，希望大佬有空看看。

**Comment by Lightczx** [comment]
#460

**Comment by Masterain98** [comment]
Duplicate of #460
