### ISSUE TITLE
[Bug]: 用胡桃导出的祈愿记录.json文件发送给云崽机器人,机器人获取到的记录是顺序错乱的

### ISSUE THREAD

**Issue by BeggingHorse** [DGP-Studio/Snap.Hutao#473]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.819

### Snap Hutao 版本

1.4.0.0

### 问题分类

祈愿记录

### 发生了什么？

[Bug]: 用胡桃导出的祈愿记录.json文件发送给云崽机器人,机器人获取到的记录是顺序错乱的.把json文件导入到刻记牛杂店再导出.xlsx文件导入到云崽就正常了

**Comment by Lightczx** [comment]
@Le-niao

**Comment by 43887016** [comment]
胡桃工具箱导出的json文件时间是乱序的，yunzai应该是顺序读的，新版本胡桃仍然存在此问题，且胡桃导出的json文件不包含uid和lang字段导致部分软件读取异常

**Comment by Lightczx** [comment]
我们始终坚持使用 v2.2的UIGF格式
https://uigf.org/standards/UIGF.html
其他软件不适配我们也没办法
