### ISSUE TITLE
在祈愿记录里，添加现在已经垫了多少抽

### ISSUE THREAD

**Issue by zhangqing520** [DGP-Studio/Snap.Hutao#475]
### 背景与动机

胡桃工具箱里，祈愿记录，只显示了五星的抽数，但是没有累计多少抽的数据，建议参考软件 Genshin Wish Export

### 想要实现或优化的功能

具体参考软件Genshin Wish Export

**Comment by Masterain98** [comment]
你确定没有吗？

**Comment by zhangqing520** [comment]
找到了，原来这个是，没有提示，没看出来对比了其他软件才知道这个数据的含义






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月8日(星期三) 晚上8:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DGP-Studio/Snap.Hutao] 在祈愿记录里，添加现在已经垫了多少抽 (Issue #475)





 
你确定没有吗？

**Comment by Masterain98** [comment]
这叫圆形进度条，是一种非常常见的进度条风格。
