### ISSUE TITLE
祈愿问题

### ISSUE THREAD

**Issue by rddduru6** [DGP-Studio/Snap.Hutao#478]
### 检查清单

- [x] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

10.0.19045.2130

### Snap Hutao 版本

1.4.11.0

### 设备 ID

255AE03643FA41EE5A99EBA406196B45

### 问题分类

祈愿记录

### 发生了什么？

导入祈愿json文件，无论怎么刷新都会使旧的文件里祈愿与新导入的半年祈愿角色武器重叠

### 相关的崩溃日志

刷新前后的文件
[2.json.txt](https://github.com/DGP-Studio/Snap.Hutao/files/10696295/2.json.txt)

[1.json.txt](https://github.com/DGP-Studio/Snap.Hutao/files/10696292/1.json.txt)

**Comment by Lightczx** [comment]
文件没传完

**Comment by rddduru6** [comment]
文件传完了，1是导入前文件，2是刷新后文件

**Comment by Lightczx** [comment]
从哪导的，提供那个文件

**Comment by rddduru6** [comment]
Genshin Wish Expor，zip压缩后80MB传不了

**Comment by Lightczx** [comment]
。。。提供导出的json，不是整个app

**Comment by rddduru6** [comment]
json文件传不了

**Comment by Lightczx** [comment]
导入之前把会重复的部分删掉就行了
