### ISSUE TITLE
[Feat]: 希望添加快捷启动方式和小白安装运行教程

### ISSUE THREAD

**Issue by NOXMI** [DGP-Studio/Snap.Hutao#48]
### 你想要实现或优化的功能？

系统 win10 19042.928
hutao版本 1.1.5.0
按照安装方法运行install.ps1后，显示安装成功，回车后没有powershell关闭没有反馈。能在“程序与应用”中找到Hutao，但是桌面与菜单栏没有生成快捷方式，找到安装目录运行Snap.Hutao.exe后没有响应，没有崩溃日志，任务管理器中未找到相应进程。希望添加快捷启动方式和小白安装运行教程。

**Comment by tz3300** [comment]
咸鱼表示没有看到install.ps1文件在哪，弱小无助。。。

**Comment by NOXMI** [comment]
> 咸鱼表示没有看到install.ps1文件在哪，弱小无助。。。

就在release的压缩包里......

**Comment by NOXMI** [comment]
我是SB，该电脑不能直接运行.msix文件，换个电脑安装就明白了
