### ISSUE TITLE
[Bug]: 删除胡桃之后，电脑会经常性弹窗。

### ISSUE THREAD

**Issue by jxz2333** [DGP-Studio/Snap.Hutao#480]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

21H2 19044.2486

### Snap Hutao 版本

已删除

### 问题分类

安装和环境

### 发生了什么？

在删除胡桃之后，系统会经常性弹窗，需要使用新应用以打开此hutao 链接。
重新在微软商店下载失败，错误代码: 0x80070005

**Comment by LincRui** [comment]
更新了最新的，卸载后也还是会出现这个问题
