### ISSUE TITLE
[Bug]: 养成计算器出现请求异常

### ISSUE THREAD

**Issue by KeplerSun8023** [DGP-Studio/Snap.Hutao#481]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.11.0

### 设备 ID

3C8A554B35ED8AEB3589CF3AEBAE15F9

### 问题分类

养成计算器

### 发生了什么？

![微信截图_20230209172747](https://user-images.githubusercontent.com/103730824/217772274-c7580d38-2989-4116-9e95-663d47809a81.png)
角色养成无法计算，计算时显示
状态：653366069信息请求异常
前天刚下载的时候时可以用的
昨天以为是新开池子流量
今天在公司电脑试了下可以计算
回到家里电脑就无法计算

### 你期望发生的行为？

期望可以计算

**Comment by Lightczx** [comment]
更新到1.4.14

**Comment by void0red** [comment]
> 更新到1.4.14

ci/cd挂了 release没有构建完成

**Comment by Lightczx** [comment]
去商店下

**Comment by void0red** [comment]
> 去商店下

microsoft store也还是1.4.11.0版本

**Comment by Lightczx** [comment]
那是你自己的问题了
