### ISSUE TITLE
[Bug]: 每次都需要重新登陆

### ISSUE THREAD

**Issue by xingxiyue** [DGP-Studio/Snap.Hutao#482]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.11974

### Snap Hutao 版本

1.4.1.0

### 设备 ID

E1444F79306452B520342B28285AA8C5

### 问题分类

游戏启动器

### 发生了什么？

不管是否使用管理员身份启动胡桃，每次点击工具栏的启动游戏-常规-勾选角色，点击启动游戏后，在登陆界面都需要我重新输入账号密码。这种情况发生在电脑每一次重启后
如果电脑不重启，那么第一次输入账户密码后，之后再登录则不需要输入密码
每次开机第一次登陆游戏都得输入账号密码

### 你期望发生的行为？

我希望除非我进行版本更新，否则应该一个版本输入一次账号密码就行了

**Comment by Masterain98** [comment]
三种可能的情况
1. 你保存的那份存档记录实际上没有登录状态
2. 你的设备ID一重启就变
3. 你的网络环境天天变
