### ISSUE TITLE
[Bug]: 无法添加养成计划

### ISSUE THREAD

**Issue by flm128** [DGP-Studio/Snap.Hutao#484]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.14.0

### 问题分类

养成计算器

### 发生了什么？

已经有成功添加的养成计划，现在添加武器计划出现错误提示：
状态：-100 信息：请先登录
而且现在切换左侧功能到养成计划，没有默认选中已有的计划，需要手动右上角在下拉框里选择计划

**Comment by flm128** [comment]
相关截图

**Comment by Lightczx** [comment]
去设置里面打开签到2次
删掉所有养成计划重新添加
