### ISSUE TITLE
[Bug]: 转换国际服提示数据异常（游戏内）

### ISSUE THREAD

**Issue by luluxiaoyu** [DGP-Studio/Snap.Hutao#485]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

2023.2.10.2

### 问题分类

游戏启动器

### 发生了什么？

转换国际服后无法登录，提示数据异常请完整删除并重新安装游戏

**Comment by Lightczx** [comment]
下版本修复

**Comment by muzhixiamunai** [comment]
> 下版本修复，国际服需要移除 `Screenshot` 文件夹内的 `HutaoCache` 文件夹

国际服转国服也会报错
