### ISSUE TITLE
[Feat]: 允许养成计划材料统计页面编辑材料总数

### ISSUE THREAD

**Issue by pooneyy** [DGP-Studio/Snap.Hutao#487]
### 背景与动机

提高「材料统计」功能的易用性。

### 现状
当前的情况是，在「背包物品」栏目编辑目前已有的材料数量：
![image](https://user-images.githubusercontent.com/85266337/218140728-647f3c4a-6c7e-47f5-a440-b4325c26612d.png)
「背包物品」栏目包含了较多的素材，而用户仅仅需要记录其中的一小部分，还需要从茫茫众多素材中寻找自己需要标记的素材，这一过程会花费不少时间，造成诸多不便。

### 解决方案
当前除了「背包物品」栏目以外，还有一个「材料统计」栏目，如图：
![image](https://user-images.githubusercontent.com/85266337/218142088-d48f1a39-08ec-4098-b47f-3f044e26bbc1.png)
「材料统计」包含了养成计划里所有需要的素材，我们不妨直接在此处编辑用户背包里已有的素材的数量，这样对玩家会更便利

**Comment by Ar-Hyk** [comment]
嗯……说到「材料统计」功能
能不能直接直接扫游戏游戏背包啊，手动输入好痛苦……

**Comment by Lightczx** [comment]
几乎不可能实现
