### ISSUE TITLE
[Bug]: 已经设置高级启动器功能，但通过底部任务栏启动程序没有解锁帧率

### ISSUE THREAD

**Issue by MrAgNO3** [DGP-Studio/Snap.Hutao#488]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.14.0

### 问题分类

游戏启动器

### 发生了什么？

已经设置高级启动器功能中的参数，并解锁帧率。通过任务栏右键中快捷启动游戏后，并没有解锁帧率

### 你期望发生的行为？

成功依照配置项启动游戏并解锁帧率

**Comment by Masterain98** [comment]
微软没有提供管理员启动方式的接口

**Comment by Lightczx** [comment]
任务栏中的快捷启动理论上不能实现管理员模式下才能使用的功能
