### ISSUE TITLE
[Bug]: 应用 Compositionlmage 的源时发生异常

### ISSUE THREAD

**Issue by asjhdfjh** [DGP-Studio/Snap.Hutao#489]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.14.0

### 设备 ID

7D3E0553FD53B6E947DA8C886C5C55EB

### 问题分类

胡桃数据库

### 发生了什么？

COMException
应用 Compositionlmage 的源时发生异常
<img width="890" alt="屏幕截图 2023-02-11 141822" src="https://user-images.githubusercontent.com/119153102/218243792-9e2bc21e-1355-4c7f-b87c-5797ea0c6c26.png">

没有注册类 （ 0X80040154 (REGDB_E_CLASSNOTREG))

**Comment by Masterain98** [comment]
你确定这是胡桃数据库相关功能？

**Comment by Lightczx** [comment]
网络问题
