### ISSUE TITLE
[Bug]: 胡桃App的图标不应该默认加圆角

### ISSUE THREAD

**Issue by liyuhaolol** [DGP-Studio/Snap.Hutao#490]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.14.0

### 问题分类

用户界面

### 发生了什么？

![QQ截图20230211153023](https://user-images.githubusercontent.com/16422963/218246447-6b060dd7-2df1-4023-b24e-8c27336d8d29.png)
#### 如图一所示，胡桃的App图标默认加了圆角，但是图标却是蓝底而不是一般app常用的透明底，就造成图标显示会出现蓝角，十分影响观感。
![QQ截图20230211153424](https://user-images.githubusercontent.com/16422963/218246527-b615ecff-b371-4587-a568-3d69b1991289.png)
### 你期望发生的行为？

- 1，我希望胡桃的App图标能去掉圆角，因为windows需要加圆角的地方会自动给图标加圆角，不需要开发者自己去给图标加圆角。
- 2，我希望胡桃的App图标能适配大比例的图标，避免windows放大以后，图标变得很丑陋
- 3，如果以上两条都完全不考虑做，希望作者能把图标的蓝底换为透明底，因为蓝底确实太难看了。

**Comment by Lightczx** [comment]
开始菜单中并不会自动添加圆角
