### ISSUE TITLE
[Bug]: 切屏卡死

### ISSUE THREAD

**Issue by Formerly9501** [DGP-Studio/Snap.Hutao#491]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.2.16.0

### 设备 ID

C63194F9C99DCE967D4A05DD0838D512

### 问题分类

其它

### 发生了什么？

在游戏过程中切屏会卡死，屏幕直接被原神占据，alt+f4无法使用，用快捷键调出任务管理器也不能显示在卡死屏幕上端

**Comment by Formerly9501** [comment]
新版本除了从微软商店还能从哪下，我微软下不下来

**Comment by Masterain98** [comment]
> 新版本除了从微软商店还能从哪下，我微软下不下来

That is not an **issue**
