### ISSUE TITLE
[Bug]: 通过胡桃无法启动游戏

### ISSUE THREAD

**Issue by Xing688** [DGP-Studio/Snap.Hutao#493]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

25290.1010

### Snap Hutao 版本

1.4.11.0

### 设备 ID

1EE593786F2AF6789DE0CF3E63E736AA

### 问题分类

游戏启动器

### 发生了什么？

![QQ图片20230211223932](https://user-images.githubusercontent.com/98017796/218263933-5b838c5b-2bf7-4fd7-a009-37a61721b215.png)
单机启动游戏后，启动游戏并未变成灰色的已点击状态，观看后台的同时启动游戏，发现并未唤起游戏程序，已确定游戏目录并未错误，管理员模式依然如此。

### 你期望发生的行为？

希望能解决无法启动的问题

**Comment by Lightczx** [comment]
更新到1.4.14

**Comment by Xing688** [comment]
更新到1.4.14仍未解决问题

**Comment by Lightczx** [comment]
你的路径是？

**Comment by Lightczx** [comment]
游戏路径。。。。

**Comment by Xing688** [comment]
D:\Genshin Impact

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 1EE593786F2AF6789DE0CF3E63E736AA

**Comment by Xing688** [comment]
D:\Genshin Impact\Genshin Impact Game

**Comment by Lightczx** [comment]
使用管理员模式选中对应的服务器再启动

**Comment by Xing688** [comment]
解决

**Comment by zb7777** [comment]
> 解决

能正常启动后，固定胡桃到任务栏，有右键快速启动游戏吗
使用胡桃前，有用过寻空，反和谐插件 等工具吗

**Comment by Xing688** [comment]
已设置，之前是Sgnp Genshin的用户，并未使用过其他工具
