### ISSUE TITLE
[Feat]: 服务器切换导致31-4302报错

### ISSUE THREAD

**Issue by StarGolx** [DGP-Studio/Snap.Hutao#494]
### 背景与动机

用胡桃工具箱从**国服**切换到**国际服**会在Genshin Impact game下的ScreenShot文件夹创建一个叫HutaoCache的文件夹，导致进游戏后会出现**31-4302报错**

### 想要实现或优化的功能

建议在胡桃工具箱的目录下创建

**Comment by muzhixiamunai** [comment]
同，希望尽快修复

**Comment by Lightczx** [comment]
#485
