### ISSUE TITLE
国际服支持

### ISSUE THREAD

**Issue by xxxTexcitarxx** [DGP-Studio/Snap.Hutao#495]
### 背景与动机

能否在软件中直接登录国际服？

### 想要实现或优化的功能

现在国际服无法登录，导入抽卡记录（导入链接提示过期），以及查看角色详情，希望尽早支持国际服的相关内容

**Comment by Masterain98** [comment]
duplicate of 447, #255, #254, #141, #144

Please search issues before you submit a duplicate one

**Comment by Masterain98** [comment]
> 导入抽卡记录（导入链接提示过期）

更新至最新版
