### ISSUE TITLE
[Bug]: 无法打开

### ISSUE THREAD

**Issue by dudu-Dev0** [DGP-Studio/Snap.Hutao#497]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.14

### 问题分类

安装和环境

### 发生了什么？

因为无法使用微软商店安装，于是从 https://store.rg-adguard.net/ 下载了胡桃工具箱的appx安装
但是安装后无法打开
附下图
![屏幕截图 2023-02-12 201443](https://user-images.githubusercontent.com/86507157/218310456-be95b4a1-9947-4afb-86de-767f4cb55644.png)

**Comment by Lightczx** [comment]
装证书
