### ISSUE TITLE
[Feat]: 天赋武器材料日历

### ISSUE THREAD

**Issue by ligolq** [DGP-Studio/Snap.Hutao#501]
### 背景与动机

![image](https://user-images.githubusercontent.com/87518465/218494717-ffdf754a-6752-4b58-8381-a30281327396.png)
在使用养成计划时，不能方便查阅今日培养角色材料副本是否刷新

### 想要实现或优化的功能

添加一个类似寻空养成子菜单的内容
![image](https://user-images.githubusercontent.com/87518465/218495212-e9d6f411-b5e1-425f-a711-026e5576a112.png)

**Comment by qakcn** [comment]
附议

**Comment by Lightczx** [comment]
Tracked by #1394
