### ISSUE TITLE
[Bug]: 启动器转国际服进游戏页面提示游戏异常请卸载 错误码31-4302

### ISSUE THREAD

**Issue by fly-far-and-stay-high** [DGP-Studio/Snap.Hutao#502]
### 检查清单

- [ ] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.1.0

### 设备 ID

CAF7E841C27CDC8FC7168C52A2E2B8D7

### 问题分类

游戏启动器

### 发生了什么？

背景：2/13之前(一周内)使用了转换启动服均无问题，但是在2/13之后使用了转换器转为国际服，且注册了一个新的hoyolab,再进游戏就弹窗：数据异常，请完全卸载游戏，并从官方渠道重新下载安装，错误码：31-4302
之后的行为：之后转换为国服就没有错误，再转回国际服登录旧的国际服账号也有同样的错误，回到游戏主界面也没有要下载游戏数据。

### 你期望发生的行为？

期望即使是新账号也能进入游戏（我个人猜测是新账号的部分数据不包括在游戏在内）请问需要重新安装可以解决该问题吗？安装国际服还是国服。这儿原版是国服出安装的。

### 相关的崩溃日志

这我感觉不算是崩溃日志，期待开发者大大的回复交流

**Comment by Masterain98** [comment]
[RTFM](https://hut.ao/FAQ/known-issue.html#_2-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%88%87%E6%8D%A2%E5%AF%BC%E8%87%B431-4302%E6%8A%A5%E9%94%99)
