### ISSUE TITLE
[Bug]: Please do not turn of the software

### ISSUE THREAD

**Issue by ssswang** [DGP-Studio/Snap.Hutao#504]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.15

### 问题分类

用户界面

### 发生了什么？

https://github.com/DGP-Studio/Snap.Hutao/blob/main/src/Snap.Hutao/Snap.Hutao/Resource/Localization/SH.en-US.resx#L1405

Please do not turn **of** the software

英文版拼写错误

**Comment by Lightczx** [comment]
@Masterain98

**Comment by Masterain98** [comment]
@Lightczx fixed
