### ISSUE TITLE
[Bug]: 无法打开

### ISSUE THREAD

**Issue by duan-1** [DGP-Studio/Snap.Hutao#505]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

25295.1000

### Snap Hutao 版本

1.4.15.0

### 问题分类

其它

### 发生了什么？

打开应用后只显示窗口框架，随后自动关闭

### 相关的崩溃日志

![image](https://user-images.githubusercontent.com/61895588/218923602-df2b9063-4f00-4c44-b922-47eca3305305.png)

**Comment by Lightczx** [comment]
找 .NET Runtime Error,你目前提供的信息没什么用

**Comment by duan-1** [comment]
> 找 .NET Runtime Error,你目前提供的信息没什么用

如何查看呢？如果也是在事件查看器里面的话，那我就没有找到 .NET 相关的错误

**Comment by Lightczx** [comment]
没有的话我们也没办法修复这种问题
