### ISSUE TITLE
[Bug]: 游戏花屏

### ISSUE THREAD

**Issue by pddljc** [DGP-Studio/Snap.Hutao#507]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.15.0

### 设备 ID

BCBBBA141D7B7C376D8F8660D19D528B

### 问题分类

游戏启动器

### 发生了什么？

启动后原神游戏界面间歇性雪花屏，在游戏内设置中的分辨率选项内切换到非独占全屏的选项才能解决，一旦选择独占全屏就会变成雪花屏。或者退出游戏，在胡桃启动器内关闭全屏和独占全屏两个选项重新启动也可恢复正常。

### 你期望发生的行为？

恢复正常屏幕显示

### 相关的崩溃日志

[新建 ZIP 压缩文件.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10740733/ZIP.zip)

**Comment by pddljc** [comment]
压缩文件密码genshin77

**Comment by Lightczx** [comment]
独占全屏选项本就有兼容性问题

**Comment by pddljc** [comment]
> 独占全屏选项本就有兼容性问题
请问这个可以通过什么方法自行解决吗？

**Comment by Lightczx** [comment]
不选立即解决。

**Comment by pddljc** [comment]
> 不选立即解决
大佬我去试验了一下，前一段时间我都是关闭hdr进行游戏，出现这个问题的时候正好就是开启了hdr进行游戏。我控制了一下变量，60/解锁高帧率为一个变量，hdr/不开为一组变量。60帧不会出现任何问题不论开不开hdr，而不开hdr解锁高帧率也不会有问题。只有既解锁高帧率又开hdr会出现花屏问题。这就是您说的兼容性问题吗？

**Comment by Lightczx** [comment]
游戏本身就不支持我们的独占全屏
