### ISSUE TITLE
[Bug]: 跳转到下载页面后不能下载Hutao

### ISSUE THREAD

**Issue by WismyYao** [DGP-Studio/Snap.Hutao#51]
### Windows 版本

WIN10 + Edge

### Snap Hutao 版本

-

### 发生了什么？

![image](https://user-images.githubusercontent.com/16497598/192671531-df5ea3d7-da32-43ff-a529-f13627079eca.png)

点击下载页面看到的就是这样，不能下载Hutao

### 你期望发生的行为？

-

### 相关的崩溃日志 位于 %HOMEPATH%/Documents/Hutao/Log.db

```shell
-
```

**Comment by Masterain98** [comment]
使用 https://go.hut.ao/down 下载
On 9/27/2022 7:11:22 PM, Wismy ***@***.***> wrote:
Windows 版本
WIN10 + Edge
Snap Hutao 版本
*
发生了什么？
[image] [https://user-images.githubusercontent.com/16497598/192671531-df5ea3d7-da32-43ff-a529-f13627079eca.png]
点击下载页面看到的就是这样，不能下载Hutao
你期望发生的行为？
*
相关的崩溃日志 位于 %HOMEPATH%/Documents/Hutao/Log.db
-
