### ISSUE TITLE
[Bug]: 我的角色——导出图片BUG

### ISSUE THREAD

**Issue by pooneyy** [DGP-Studio/Snap.Hutao#510]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

0

### Snap Hutao 版本

1.4.15.0

### 问题分类

角色信息面板

### 发生了什么？

图中红框，只有“详细数据”里的导出图片有用，“总览数据”里的导出图片没有用
![image](https://user-images.githubusercontent.com/85266337/219082587-2f1063be-2243-403c-b9d0-69e8f7cd0ca0.png)

**Comment by Lightczx** [comment]
#503
