### ISSUE TITLE
祈愿记录导出功能添加，导出记录为Excel格式的文件

### ISSUE THREAD

**Issue by zhangqing520** [DGP-Studio/Snap.Hutao#511]
### 背景与动机

json格式的数据，只适合导入其他软件，不适合看，而软件的只能看到出金的记录，看不到该抽的时间等记录，具体像Genshin Wish Export软件一样

### 想要实现或优化的功能

方便导出查看

**Comment by Lightczx** [comment]
鼠标悬浮在上方即可查看时间。
