### ISSUE TITLE
[Bug]: 启动游戏时触发长路径限制

### ISSUE THREAD

**Issue by DWThunderAsh** [DGP-Studio/Snap.Hutao#512]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [x] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22623.1255

### Snap Hutao 版本

1.4.15.0

### 设备 ID

D78DE1E38D79B61969937695DF2E5F3A

### 问题分类

游戏启动器

### 发生了什么？

商店版的snap hutao在选择账号启动游戏时，会弹出长路径的错误。相关注册表和组策略项我都已经打开，而且用侧载版的胡桃1.4.1.0可以正常选择账号启动游戏。
<img width="892" alt="err" src="https://user-images.githubusercontent.com/124812590/219262371-6193a84a-43cf-49f5-818c-7f483778bcb8.png">

**Comment by Lightczx** [comment]
《我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答》
