### ISSUE TITLE
[Bug]: winget无法从微软商店安装胡桃

### ISSUE THREAD

**Issue by CarefulDeveloper** [DGP-Studio/Snap.Hutao#514]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2486

### Snap Hutao 版本

微软商店的第一个版本

### 问题分类

安装和环境

### 发生了什么？

![image](https://user-images.githubusercontent.com/78646351/219379471-13a06a82-7fc9-4faa-937a-ed511cfda80c.png)

如上图，我使用了winget工具对胡桃工具进行安装提示安装失败。我在安装前已经卸载了自己旧版的胡桃。

**Comment by CarefulDeveloper** [comment]
我正在切换网络环境测试，确保这个bug不是由我的网络问题导致的。

**Comment by CarefulDeveloper** [comment]
winget.exe安装方式并没有解决我的问题，最后我通过使用powershell命令安装程序离线包解决问题。

![image](https://user-images.githubusercontent.com/78646351/219384266-c9bbe3a5-a1a6-43db-951e-822f3fe5baef.png)

**Comment by Masterain98** [comment]
![image](https://user-images.githubusercontent.com/10614984/219495510-d2f5a8f1-c7d1-4762-a4b9-5d2785a711ac.png)

检查你的网络和本机组件是否完整
