### ISSUE TITLE
[Bug]: 元数据校验文件下载失败

### ISSUE THREAD

**Issue by qijiuyaonie21** [DGP-Studio/Snap.Hutao#515]
### 检查清单

- [ ] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19042.1706

### Snap Hutao 版本

1.3.12.0

### 设备 ID

EC5EAFB3B8273D466587EBF3F942BFDB

### 问题分类

其它

### 发生了什么？

打开胡桃一直显示这个元数据校验文件下载失败，除了便签以外都无法正常使用，

![image](https://user-images.githubusercontent.com/125574032/219383491-50f0d3d4-99a3-4ff6-a2bb-409df424621f.png)

**Comment by Masterain98** [comment]
- [ ] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答

打上这✅时，希望你是真的做过了，而不是像读用户协议一样随手一点

**Comment by xlong0425** [comment]
> ### 检查清单
> * [ ]  我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
> * [x]  我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
> * [x]  我确认没有其他人已经提出了相同或类似的问题
> * [x]  我会在下方的表单中附上充足的信息以帮助开发人员确定问题
> 
> ### Windows 版本
> 19042.1706
> 
> ### Snap Hutao 版本
> 1.3.12.0
> 
> ### 设备 ID
> EC5EAFB3B8273D466587EBF3F942BFDB
> 
> ### 问题分类
> 其它
> 
> ### 发生了什么？
> 打开胡桃一直显示这个元数据校验文件下载失败，除了便签以外都无法正常使用，
> 
> ![image](https://user-images.githubusercontent.com/125574032/219383491-50f0d3d4-99a3-4ff6-a2bb-409df424621f.png)
> 
> ### 你期望发生的行为？
> _No response_
> 
> ### 相关的崩溃日志
> _No response_

我也出现了这个错误
