### ISSUE TITLE
[Bug]: 用户网络异常

### ISSUE THREAD

**Issue by feisays** [DGP-Studio/Snap.Hutao#517]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2604

### Snap Hutao 版本

1.4.15.0

### 问题分类

用户面板

### 发生了什么？

用户网络异常
状态:653366069 | 信息:[GetActionTicketByStokenAsync]中的[ActionTicketWrapper]请求异常
![2023-02-16_233801](https://user-images.githubusercontent.com/61895325/219418269-1e7bfcda-cbd8-4f02-b08e-17bb082ada9a.png)

**Comment by Lightczx** [comment]
偶发现象？

**Comment by feisays** [comment]
可能是了，今天重新打开的时候一切正常。
