### ISSUE TITLE
[Bug]: 安装后无法打开

### ISSUE THREAD

**Issue by jinyiwei2012** [DGP-Studio/Snap.Hutao#520]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19041.1415

### Snap Hutao 版本

1.4.15.0

### 问题分类

安装和环境

### 发生了什么？

正常下载安装后,尝试启动,弹出窗口
![无标题](https://user-images.githubusercontent.com/116472418/219650963-e8dd65f8-f951-4a97-8cf0-91138583502b.png)

**Comment by xiurenfuwo** [comment]
同样的问题。
在C盘的安装位置不能打开，只能从开始菜单打开。

**Comment by Lightczx** [comment]
windows应用设计如此，本就不允许从安装目录打开
