### ISSUE TITLE
[Bug]: 原神切换国际服再关闭后，无法启动官方服

### ISSUE THREAD

**Issue by Barrrrrry1** [DGP-Studio/Snap.Hutao#522]
### 检查清单

- [x] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2604

### Snap Hutao 版本

1.4.15.0

### 设备 ID

7EFB36978A3DEEB82A639BF39EAB6290

### 问题分类

安装和环境

### 发生了什么？

我在使用hutao切换国际服使用后，将国际服关闭，然后切换官方服，就显示“无法读取游戏配置文件”。使用原神启动器也无法定位游戏。

### 你期望发生的行为？

我想能正常打开原神，我不知道为什么hutao和原神启动器都开启不了原神

**Comment by Barrrrrry1** [comment]
![A`3N%S5T~_UR1}5{NT}TL%I](https://user-images.githubusercontent.com/123822531/219715942-591762f5-831d-40c9-9c41-2b7c4d381f1d.png)

**Comment by Lightczx** [comment]
在提示的路径处能否找到文件，发个截图看看

**Comment by Barrrrrry1** [comment]
> 

你好，我中午着急重新下载了。提示路径能找到国际服的文件，打开之后也是国际服。这个路径是我原本安装官方服的。

**Comment by Lightczx** [comment]
改成英文路径试试
