### ISSUE TITLE
[Bug]: 为什么经过管理员启动，正确设置游戏本体路径之后，点击启动游戏，没有任何反应。

### ISSUE THREAD

**Issue by AirScarlet** [DGP-Studio/Snap.Hutao#523]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 设备 ID

D78A4DCB0EB5CED81E5382B51262258F

### 问题分类

游戏启动器

### 发生了什么？

为什么经过管理员启动，正确设置游戏本体路径之后，点击启动游戏，没有任何反应。

**Comment by AirScarlet** [comment]
没有错误日志，就是点击启动游戏按键，没有任何反应。

**Comment by AirScarlet** [comment]
游戏的路径必须要全英文路径吗？

**Comment by wen12389** [comment]
我也有一样的问题，解决了吗？

**Comment by Lightczx** [comment]
理论上不需要全英文路径
但是可以试试

**Comment by AirScarlet** [comment]
问题已经解决了，重新安装了一遍游戏之后发现，我游戏本体存在于两个盘，分别有两个游戏本体，之前选择的时候选择了其中一个游戏本体，我在重装游戏之后删除了其他所有的游戏备份，重新选择了游戏本体路径，已经能够成功使用了。
