### ISSUE TITLE
[Feat]: 启动游戏支持多个游戏路径

### ISSUE THREAD

**Issue by i-ccrru** [DGP-Studio/Snap.Hutao#526]
### 背景与动机

之前SG的时候试过一个国际服切换，国际服和国服来回切换很容易导致数据冲突（反正就是原神启动报错）那时候我就保留了两个本体。这项功能提议主要是给储存空间多的人用。

### 想要实现或优化的功能

启动器设置路径可以设置两个（这样切换完全用改文件导致游戏崩溃重下）对于储存空间大玩双服或者多服务器玩家会很友善。

**Comment by TechOtakupoi233** [comment]
装双端就是每次都要更新两份游戏，说实话挺花时间的。

**Comment by i-ccrru** [comment]
> 

我觉得更新两份文件必游戏彻底切死后全部重下要好（欲哭无泪）

**Comment by sweetcolaer** [comment]
其实不需要更新两个游戏，只需要更新一个主玩的服务器然后复制成两份，用胡桃来转其中一个的服务器就行，毕竟本体数据都是一样的
