### ISSUE TITLE
[Feat]: [Bug]: 祈愿记录功能 UIFG json 求更新& 追加EXCEL 匯入功能

### ISSUE THREAD

**Issue by sheaahhoi1** [DGP-Studio/Snap.Hutao#528]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22261.1194

### Snap Hutao 版本

1.4.15.0

### 设备 ID

A34DD2F85F3677B44E03C785024292CD

### 问题分类

祈愿记录

### 发生了什么？

![2023-02-18 143609](https://user-images.githubusercontent.com/10239384/219845434-81b79a62-5f97-47c6-a069-dc831e1f3193.png)
1.這"匯出"位置應該譯錯吧?
功能是匯入

2.UIFG json匯入功能太舊請更新,
我試圖將"原神祈愿记录导出工具"的記錄轉化的json匯入出現錯誤
工具下載網址:
[https://github.com/biuuu/genshin-wish-export](https://github.com/biuuu/genshin-wish-export)
所提供的轉換工具網
[https://genshin-gacha-export.danmu9.com/](https://genshin-gacha-export.danmu9.com/)

![2023-02-18 143946](https://user-images.githubusercontent.com/10239384/219846938-4470fd84-75cc-4cc7-9496-8445f0a19a64.png)

### 你期望发生的行为？

1.UIFG json 按鈕"匯出"改"匯入"
2.UIFG json 請更新
3.(延伸功能)能直接提供EXCEL匯入嗎?(只少支援原神祈愿记录导出工具的輸出格式)

**Comment by Lightczx** [comment]
1. fixed
2. UIGF json 不会支持非简体中文
