### ISSUE TITLE
[Bug]: 多用户时，导入各自的祈愿记录后，点击上方的UID切换不了

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#53]
### Windows 版本

22622.601

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

多用户时，导入各自的祈愿记录后，点击上方的UID切换不了
![动画](https://user-images.githubusercontent.com/2825342/192676075-21f17cc6-6fcb-4c15-9dfb-970019745a02.gif)

**Comment by Lightczx** [comment]
微软的已知问题
https://github.com/microsoft/microsoft-ui-xaml/issues/7756

**Comment by AlbertWen-AW** [comment]
目前可以尝试再往下一些的位置点击应该是可以切换的
