### ISSUE TITLE
Win11应用商店版卸载之后时不时弹窗口 获取打开此'hutao'链接的应用 

### ISSUE THREAD

**Issue by LiuDanK** [DGP-Studio/Snap.Hutao#531]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22623.1028

### Snap Hutao 版本

1.4.15

### 问题分类

安装和环境

### 发生了什么？

![1676728649718](https://user-images.githubusercontent.com/32576900/219869871-7b78bafe-7422-4643-97c7-93601af01203.jpg)
卸载掉之后老出来这个弹窗，太烦人了

### 你期望发生的行为？

解决该问题

**Comment by Lightczx** [comment]
看文档

**Comment by LiuDanK** [comment]
> 看文档

![image](https://user-images.githubusercontent.com/32576900/219871379-56e12586-b9d8-4d41-bc0c-658ac1e45e77.png)
只有删除用户按钮，没有删除计划任务按钮

**Comment by Lightczx** [comment]
进实时便笺换一下刷新时间看看会不会有提示

**Comment by LiuDanK** [comment]
> 进实时便笺换一下刷新时间看看会不会有提示
没有，重新打开也是没有唉
![image](https://user-images.githubusercontent.com/32576900/219871485-14d28301-2c21-4833-bd0a-55e247bd9d11.png)
![image](https://user-images.githubusercontent.com/32576900/219871489-a9280f07-ac1e-4023-b440-3d05bdfc90ce.png)
![image](https://user-images.githubusercontent.com/32576900/219871507-0671748a-f9ee-42d3-99ab-7b0ba20d55b1.png)
![image](https://user-images.githubusercontent.com/32576900/219871517-df03a16a-851f-4829-a7db-e0f1a4e45ebc.png)

**Comment by Lightczx** [comment]
在任务计划程序里找下 SnapHutaoDailyNoteRefreshTask
看看它的操作页签里面是啥

**Comment by LiuDanK** [comment]
> 在任务计划程序里找下 SnapHutaoDailyNoteRefreshTask 看看它的操作页签里面是啥

![image](https://user-images.githubusercontent.com/32576900/219871686-a0ae895b-c92c-4897-8a58-93c52937659e.png)
这个删掉是否就可以了？

**Comment by Lightczx** [comment]
先看看操作页签

**Comment by LiuDanK** [comment]
> 先看看操作页签

![image](https://user-images.githubusercontent.com/32576900/219871767-1a371d6a-042e-44ef-b1b8-962296533e2e.png)

**Comment by Lightczx** [comment]
理论上这样卸载是不会弹窗的

**Comment by LiuDanK** [comment]
> 理论上这样卸载是不会弹窗的

那这也太奇怪了。任务计划删掉应该OK的吧？

**Comment by Lightczx** [comment]
你是第一次打开1.4.15的实时便笺页面吧
可以删除

**Comment by LiuDanK** [comment]
> 你是第一次打开1.4.15的实时便笺页面吧 可以删除

好的，谢谢。我删掉试试还出来弹窗了不

**Comment by Lightczx** [comment]
所以是第一次打开吧

**Comment by LiuDanK** [comment]
> 所以是第一次打开吧

应该是，因为我卸载重装的

**Comment by Lightczx** [comment]
只要打开过再卸载就不会弹窗了

**Comment by LiuDanK** [comment]
> 只要打开过再卸载就不会弹窗了

嗯嗯，好的

**Comment by ProfessorX** [comment]
类似问题。

删除了应该搞定了。
-------
现在是1.4.15安装不了，卡 15%囧
