### ISSUE TITLE
[Feat]: 关于”我的角色”UI的一些建议

### ISSUE THREAD

**Issue by AndyLonly** [DGP-Studio/Snap.Hutao#532]
### 背景与动机

感觉UI用起来有优化的地方，希望能够调整（题外话：伤害计算大概什么时候能做好quq）

### 对于总览数据
![image](https://user-images.githubusercontent.com/15814794/219871949-606eab3c-5ddd-480c-b747-48b31666c98d.png)

1. 在总览数据界面中希望能增加过滤器（如按稀有度，属性，武器）或者自定义排序的选项（如按等级，按属性，按获取时间，按名字等），位置的话可以替换掉左上角切换列表或网格的下拉选单（不知道是bug还是什么对总览数据不起作用）

2. 交互方面能否增加双击人物跳转到该人物的详细数据呢

3. 还有就是能否增加人物是否同步过圣遗物的标识呢，就和名座一样加在左下角或者右下角，然后设定里可以选择是否显示
### 对于详细数据
![image](https://user-images.githubusercontent.com/15814794/219872340-9f28d77d-1286-4374-b6b0-65d73f997ea7.png)
有没有可能优化一下全屏+宽屏的显示方法
比如增加左边人物选单的占比之类的，或者右半边加入角色资料之类的？

**Comment by Lightczx** [comment]
同步时间将会在 1.7 中实现，其他的若确有需求可重新单独开 issue
