### ISSUE TITLE
[Bug]: 通过高级启动器启动游戏时不时要求重新输入账密

### ISSUE THREAD

**Issue by mraliqq** [DGP-Studio/Snap.Hutao#536]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 问题分类

游戏启动器

### 发生了什么？

请问，使用用高级启动器登官方服，只使用一个账号，点击启动游戏进入游戏界面后，时不时会出现需要重新输入账密的情况，之后也需要重新检测并添加账号到启动器里，才能在下次启动后自动登录。该问题的发生没有明显规律。

**Comment by Lightczx** [comment]
简单描述网络环境

**Comment by Masterain98** [comment]
[RTFM](https://hut.ao/FAQ/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B8%B8%E6%88%8F%E7%99%BB%E5%BD%95%E7%8A%B6%E6%80%81%E4%BC%9A%E5%A4%B1%E6%95%88-%E5%AF%BC%E8%87%B4%E5%88%87%E6%8D%A2%E5%B8%90%E5%8F%B7%E5%8A%9F%E8%83%BD%E6%97%A0%E6%95%88)
