### ISSUE TITLE
[Bug]: 成就系统ID重复

### ISSUE THREAD

**Issue by icimence** [DGP-Studio/Snap.Hutao#537]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1105

### Snap Hutao 版本

1.4.15

### 问题分类

成就管理

### 发生了什么？

在达成了一个成就之后，在胡桃的成就管理页面勾选完成，重新打开胡桃或者点击其他页面重新切换回成就管理页面后显示同一个成就存档中有重复ID，查看数据库发现是手动勾选的成就出现了重复（原有成就使用导入工具导入成功）。
![image](https://user-images.githubusercontent.com/34977758/219965625-c1740d45-e105-4aa6-aa29-9868b8b68be3.png)
<img width="829" alt="image" src="https://user-images.githubusercontent.com/34977758/219965634-8edf1f99-c080-4c6f-97f1-fce50b2f8efc.png">
删除异常数据后恢复正常。

**Comment by icimence** [comment]
只要是手动勾选完成成就稳定触发，只需要进行页面切换即可

**Comment by Lightczx** [comment]
下版本修复
