### ISSUE TITLE
[Bug]: 直接打开开不了，管理员模式能开但设置不了游戏路径

### ISSUE THREAD

**Issue by Emiya867188849** [DGP-Studio/Snap.Hutao#538]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2604

### Snap Hutao 版本

1.4.15.0

### 设备 ID

3BEEC36BB80A34A96FEC5DF1F043B5CC

### 问题分类

安装和环境

### 发生了什么？

直接打开不了，可以用管理员模式打开，但是改不了游戏路径，无法用工具箱开启游戏

### 你期望发生的行为？

能直接打开设置路径后用工具箱解锁帧率

### 相关的崩溃日志

没有崩溃 单纯打不开

**Comment by Lightczx** [comment]
至少升级到 22H2版本
