### ISSUE TITLE
[Bug]: 祈愿记录导入缺失部分数据

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#54]
### Windows 版本

22622.601

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

从SG导出起源记录json，导入后提示成功，但是缺失今天抽卡的数据
角色活动少了70抽的数据，常驻少了7抽的数据
![image](https://user-images.githubusercontent.com/2825342/192697510-666c1f03-82c4-439c-aa46-1ad2364b43b5.png)
![image](https://user-images.githubusercontent.com/2825342/192697602-73e4fb57-28b1-4c54-a0dd-267592d20671.png)

**Comment by Masterain98** [comment]
最好附加一下原始JSON文件

**Comment by anpoz** [comment]
[祈愿记录.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9661866/default.zip)

**Comment by Lightczx** [comment]
在胡桃内刷新一下祈愿记录

**Comment by anpoz** [comment]
> 在胡桃内刷新一下祈愿记录

点击全量刷新没变化，点击从缓存刷新崩溃了

**Comment by anpoz** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9661881/Log.zip)

**Comment by Lightczx** [comment]
缓存刷新前是否出现过选择文件对话框

**Comment by anpoz** [comment]
> 缓存刷新前是否出现过选择文件对话框
没有，之前出现过一次卡死，任务管理器都结束不了，挂着自动退出了，刚才再点一次就直接退出了

**Comment by Lightczx** [comment]
注册表中是否存在以下键
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\原神
```

**Comment by anpoz** [comment]
> 注册表中是否存在以下键
> 
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\原神
> ```

![image](https://user-images.githubusercontent.com/2825342/192700773-dedc5959-f268-4d8f-aa2c-eed911e85de6.png)

**Comment by Lightczx** [comment]
请尝试管理员运行

**Comment by anpoz** [comment]
> 请尝试管理员运行

还是这样，没有变化

**Comment by anpoz** [comment]
但是删除存档再导入却可以

**Comment by Lightczx** [comment]
你的游戏本体位置是否经过移动

**Comment by anpoz** [comment]
> 你的游戏本体位置是否经过移动

应该是没有的

**Comment by Lightczx** [comment]
#36
