### ISSUE TITLE
角色信息服务[Enka API]当前不可用

### ISSUE THREAD

**Issue by yjc20061008** [DGP-Studio/Snap.Hutao#540]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

Windows 10 18363.1139

### Snap Hutao 版本

1.4.15.0 Microsoft Store版

### 设备 ID

没有程序崩溃

### 问题分类

角色信息面板

### 发生了什么？

1.启动Snap.Hutao
2.点击“我的角色”
3.点击“同步角色信息”
4.从Enka API同步
下方提示“角色信息服务[Enka API]当前不可用”，如图
![屏幕截图 2023-02-20 185002](https://user-images.githubusercontent.com/94227484/220087295-529798df-9101-45fc-b218-90b3746ef7ab.png)

### 你期望发生的行为？

使用Enka API同步角色信息

**Comment by yjc20061008** [comment]
y以前用侧载版就没有这个问题，这个问题是换用商店版后才有的

**Comment by Lightczx** [comment]
检查你的网络连接
