### ISSUE TITLE
[Bug]: 无法访问网络位置

### ISSUE THREAD

**Issue by ProfessorX** [DGP-Studio/Snap.Hutao#541]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2670

### Snap Hutao 版本

1.4.15

### 问题分类

安装和环境

### 发生了什么？

![image](https://user-images.githubusercontent.com/1704352/220222463-f400ad0c-b408-4b74-af95-fb4e0cc432e4.png)

1. 卸载了老的版本 （先windows 卸载应用，再BCUninstaller卸载，删除了计划任务）
2. 之前重新安装卡 15%
3. 现在安装是秒装，但是装完就报错。

在我家用电脑正常，在办公室这台电脑就有问题。

### 你期望发生的行为？

1.4.11 可以用的，我等下release 里面换新版本试下。

1.4.15装不了。

**Comment by ProfessorX** [comment]
补充一下，
1. 电脑在内网
2. 可以联网的，有科学上网。
3. 但是网络那里提示 无Internet

**Comment by ProfessorX** [comment]
![image](https://user-images.githubusercontent.com/1704352/220489849-7c4cad99-6167-4e2e-b84f-b70a70aa50ac.png)

结论：
1. 初步判断为 系统认为Windows 没有联网导致的。
2. 家里的电脑 WebProbe没有问题，系统判定已连上网。
3. 这台目前能上网，但是系统判定未联网----然后导致windows应用打不开。（UWP这种）
-------
你们要复现可以采用这样的方法。

**Comment by Lightczx** [comment]
如果你其他的应用能联网
你就需要允许 UWP Loopback

**Comment by ProfessorX** [comment]
![image](https://user-images.githubusercontent.com/1704352/220578359-40e8d49b-13c9-42c8-9791-07dd7475af41.png)

UWP早就开了。1.4.11版本就开了。

我说了1.4.11 能用的。现在网络搞定了，重新下的安装包还是用不了，可能是bug吧。看一下？

**Comment by ProfessorX** [comment]
别没事乱关issue，确认了再关闭，红豆泥阿狸嘎多。

**Comment by Lightczx** [comment]
非软件问题

**Comment by ProfessorX** [comment]
> 别没事乱关issue，确认了再关闭，红豆泥阿狸嘎多。

用BCUninstall 卸载的时候，把注册表里面的清空了。

是需要重新配置 loopback，我小丑了。

**Comment by ProfessorX** [comment]
![image](https://user-images.githubusercontent.com/1704352/220579854-fc1c24ce-cf80-4a73-81ff-86e282df6d41.png)

更新下最新情况：
1. 重新安装了
2. 设置了loopback
3. 
![image](https://user-images.githubusercontent.com/1704352/220580207-2072d7c2-149e-435f-8ad7-9fafcdd9061e.png)

还是会提示网络错误，打不开；在家里的电脑安装就挺顺利的。

**Comment by ProfessorX** [comment]
![image](https://user-images.githubusercontent.com/1704352/220608950-ab0e5f70-3111-40f4-8882-4b639deb1615.png)

1. 保留了一个之前1.4.1.0版本的离线安装包。
2. 本地解压缩，安装正常。
3. 可以直接打开并下载资源。
-------
等下试下用安装包更新版本，看能不能玩。不行就先老版本将就这。

1.4.15 可能有点问题的，最开始在我老婆笔记本、我台式机（家里那台）装都不行，后面忽然一下行了。
怀疑为Windows Store网络问题。
