### ISSUE TITLE
卸载后的问题

### ISSUE THREAD

**Issue by SmallAirplaneX** [DGP-Studio/Snap.Hutao#542]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1265

### Snap Hutao 版本

卸载前的版本，不知道

### 问题分类

其它

### 发生了什么？

卸载后的一段时间没有出现此问题，直到今天（2023/2/21）

表现为无征兆的重复弹出该窗口
![2023-02-21 (2)](https://user-images.githubusercontent.com/68679240/220237961-95149d8e-75fa-471c-9fe3-4d6a8534ee09.png)

### 你期望发生的行为？

什么都不做

**Comment by SmallAirplaneX** [comment]
这是卸载的遗留问题，重新安装不是我需要的

**Comment by Lightczx** [comment]
看文档。

**Comment by Masterain98** [comment]
你怎么好意思点checklist第一条的
