### ISSUE TITLE
[Bug]: 1.4.15.0,启动游戏就提示未开启长路径功能

### ISSUE THREAD

**Issue by genhenGH** [DGP-Studio/Snap.Hutao#543]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

win10 21H2(19044.2604)

### Snap Hutao 版本

1.4.15.0

### 设备 ID

35AAAB7A55676A5447C8A44CB841A72B

### 问题分类

安装和环境

### 发生了什么？

不清楚为何只要启动游戏就提示未开启长路径功能。同时游戏无法启动。
用了工具箱文档的reg，也看到各种参数都被更改了，但是启动游戏还是提示“未开启长路径功能”。
试过早前的1.14.10版本，是没有这个问题的，其余版本未测试过。

### 你期望发生的行为？

希望能解决这个问题。

**Comment by Lightczx** [comment]
你的powershell安装位置在哪

**Comment by genhenGH** [comment]
> 你的powershell安装位置在哪

M:\Windows\System32。
M盘为我系统盘

**Comment by Lightczx** [comment]
等待下版本修复

**Comment by genhenGH** [comment]
> 等待下版本修复

好的

**Comment by EvenDa** [comment]
@genhenGH  请问更新了最新版本之后 启动游戏还提升未开启长路径功能这个提示吗？

**Comment by genhenGH** [comment]
> 

个人版本1.5.10这个问题已经修复了。但是据一位阿b好友说他的还存在这个问题 ，不清楚原因

**Comment by genhenGH** [comment]
> @genhenGH 请问更新了最新版本之后 启动游戏还提升未开启长路径功能这个提示吗？

个人版本1.5.10这个问题已经修复了。但是据一位阿b好友说他的还存在这个问题 ，不清楚原因
