### ISSUE TITLE
[Feat]: 增加祈愿记录中小保底不歪概率以及支持在统计中删去最早抽数

### ISSUE THREAD

**Issue by KZdavid** [DGP-Studio/Snap.Hutao#544]
### 背景与动机

目前祈愿记录中总览分页是按照五星角色抽取顺序排列的，且标注了每个角色分别抽取了多少抽：
![image](https://user-images.githubusercontent.com/11251965/220452768-f2f7ae6a-5fd2-4d10-83e2-727d831dcc5d.png)
但是，查看祈愿记录的一个重要目的是查看当前已垫抽数，就像某著名小助手一样，包含当前累计非5星的数量放在最前面显示；
第二，增加统计在限定角色池子统计中增加统计小保底不歪的概率，这也是一个展示欧非程度的重要指标；
另外，抽卡记录中，最早一名角色的抽取可能包含已垫的过往抽取记录，导致统计不准。例如上图中，角色活动最早一个5星神里凌华只花费了2抽，但这并非是很幸运，只是在该池之前已垫了一个大保底。所以建议增加选项从统计中删去最早一名角色的数据，并在显示中对最早一名角色/武器的图标做适当标注。

### 想要实现或优化的功能

1. 增加显示最新累计非5星角色/武器的数量，方便玩家规划抽卡；
2. 增加统计限定角色池小保底不歪概率；
3. 增加设置选项允许在统计中不考虑最早一名3、4、5星角色/武器之前的记录(可以针对3、4、5星的比例分别删去对应的抽数，如果要统计小保底不歪概率，则最早的一个非up角色也应当被排除出统计)，从而防止由于时间过久统计不全导致的统计误差。在这样做的情形下，最多会排除最早一名5星角色以及之前的抽数，此时可以对那个角色的图标做标注(变灰或增加标记)。

最终形成如下效果
![无标题](https://user-images.githubusercontent.com/11251965/220459271-28f732cc-da2d-40c8-bad5-41676640a067.png)
其中神里凌华的标识样式只是一个示例(画图随手弄的，你们可以弄漂亮点)

**Comment by Masterain98** [comment]
## 增加显示最新累计非5星角色/武器的数量
你猜猜这一排进度条是什么？
![image](https://user-images.githubusercontent.com/10614984/220489290-a79bffc3-e8fb-4952-a578-c57297f45fbf.png)


## 增加统计限定角色池小保底不歪概率
- 如果只是想看看自己抽卡运气如何，`五星平均抽数`和`UP平均抽数`已经是最可靠的数据
- 如果你是想预测概率，那么
  - 上一次没歪则50%
  - 上一次歪了则100%
