### ISSUE TITLE
[Feat]: [祈愿记录]希望可以增加一行显示已垫多少抽

### ISSUE THREAD

**Issue by SheldonHoo233** [DGP-Studio/Snap.Hutao#547]
### 背景与动机

（虽然改变不了非洲的事实，但是）希望可以看看离小/大保底还差多少抽。

### 想要实现或优化的功能

如果可以实现的话，在角色卡最左边加一个空白的五星卡下面写着已垫的抽数，或者加一行字写已垫多少抽都很美观。

**Comment by Masterain98** [comment]
Duplicate of 544

#544
