### ISSUE TITLE
[Bug]: 祈愿导入显示成功，实际没有成功，json数据有id

### ISSUE THREAD

**Issue by Synlvejo** [DGP-Studio/Snap.Hutao#548]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 设备 ID

F2ABA03C0101CD4ED587397FEE2121AB

### 问题分类

祈愿记录

### 发生了什么？

导入祈愿记录，可以识别内容、版本、条数等信息，点击确认导入以后显示导入成功，实际没有导入。
确认过之前类似的issue，id号有。
详细的文件请见上传文件。
谢谢

### 相关的崩溃日志

[姝﹀櫒娲诲姩绁堟効.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10809845/default.zip)

**Comment by Lightczx** [comment]
gacha_type 是你自己乱填的吧

**Comment by Synlvejo** [comment]
> 

虽然是我自己写脚本从excel提的，
但为什么这么说呢？
这是我武器祈愿的记录，gacha_type不是302吗？

**Comment by Lightczx** [comment]
武器我看了是可以的，有数据显示的

**Comment by Synlvejo** [comment]
> 武器我看了是可以的，有数据显示的

导入选择文件时，六条导入参数都可以识别，app，时间，app版本，uigf版本，记录条数1113，uid都有。
点击确认，闪过导入狂，app左下角显示导入成功，然后依然是未导入时的316条，因为之前用app内部读取过，所以有一些基础数据。
不知道哪里可以有log或者一些信息，进一步debug一下？

**Comment by Lightczx** [comment]
提供原始数据与导入文件

**Comment by Synlvejo** [comment]
[import.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10810918/import.zip)
请见附件。json仅仅是武器祈愿数据。

**Comment by Lightczx** [comment]
> 点击确认，闪过导入狂，app左下角显示导入成功，然后依然是未导入时的316条，因为之前用app内部读取过，所以有一些基础数据。

这个数据

**Comment by Synlvejo** [comment]
> > 点击确认，闪过导入狂，app左下角显示导入成功，然后依然是未导入时的316条，因为之前用app内部读取过，所以有一些基础数据。
> 
> 这个数据

就是这个数据，316是我之前在hutao app内就存在的，我要导入的是这新的1113条

**Comment by Lightczx** [comment]
提供一下啊

**Comment by Synlvejo** [comment]
> 提供一下啊

import.zip我上传 了啊……
什么情况？
https://github.com/DGP-Studio/Snap.Hutao/issues/548#issuecomment-1441279157
这个回复里

**Comment by Lightczx** [comment]
你确定你给的是316条数据？import.zip里面的全是武器池

**Comment by Synlvejo** [comment]
> 你确定你给的是316条数据？import.zip里面的全是武器池

我胡桃里本来有316条武器数据，我新导入1113条导入不进去，我发给你了你传不上去的1113条数据的原始数据和json文件。
你需要我导出已经在胡桃里的316条武器池数据？

**Comment by Lightczx** [comment]
当然需要。。。

**Comment by Synlvejo** [comment]
> 当然需要。。。

[已有数据.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10810956/default.zip)
这是已存在与胡桃内的数据，这数据是app上登录mys自己爬的，不是我上传的。

**Comment by Lightczx** [comment]
看上去导入的是比已经存在的更新的数据
这是不支持的
我们只支持导入比已存在数据更老的数据

**Comment by Synlvejo** [comment]
> 看上去导入的是比已经存在的更新的数据 这是不支持的 我们只支持导入比已存在数据更老的数据

也就是说，我先在app里更新一下数据，再导入应该可以？

**Comment by Lightczx** [comment]
先导入再刷新数据

**Comment by Lightczx** [comment]
目前只能在外部拼接后再全新导入

**Comment by Synlvejo** [comment]
>

> 目前只能在外部拼接后再全新导入

好的了解了，谢谢

**Comment by Synlvejo** [comment]
> 目前只能在外部拼接后再全新导入

另外还有个小bug，我删掉现有数据以后，祈愿界面四个导入的选项，最后一个 导入UIGF Json的后面的按钮是 导出，应该替换为导入……

**Comment by Synlvejo** [comment]
> 目前只能在外部拼接后再全新导入

我总计分三个文件导入的，第二个第三个都没有完全导入，最后三个文件合在一个文件里导入导入是成功的，看样子好像是已有数据和新文件数据冲突导致的。

**Comment by Lightczx** [comment]
总是先导入更新的记录即可
