### ISSUE TITLE
[Bug]: 我的角色一栏同步角色信息有误

### ISSUE THREAD

**Issue by EyanAB** [DGP-Studio/Snap.Hutao#549]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2673

### Snap Hutao 版本

1.4.15.0

### 问题分类

角色信息面板

### 发生了什么？

我在工作电脑和私人电脑分别安装了客户端，从微软商店下载的，第一次登陆读取刷新过【我的角色】，之后每次提升或是有变化再次刷新的时候，角色信息不匹配【例如：武器，角色等级，技能等级，圣遗物，命座，】，多次刷新无效。其他功能正常使用，未出现问题。

**Comment by EyanAB** [comment]
此处版本标写错误，正确应为【19045.2673】
![image](https://user-images.githubusercontent.com/126131873/220813824-38f7024d-b89e-49fc-9107-a602e9d38803.png)

**Comment by Lightczx** [comment]
发设备Id

**Comment by EyanAB** [comment]
> 发设备Id

C9D5527342421A8064F542119ECB6EAB，这台是工作电脑的设备id，另外一台需要晚些才能看见

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 C9D5527342421A8064F542119ECB6EAB

**Comment by Lightczx** [comment]
游戏内更改后等了多久

**Comment by EyanAB** [comment]
很久，大概隔了一宿左右吧，我是晚上下班玩，然后第二天上班摸鱼的时候用胡桃看一眼，或者胡桃提示我体力满了，去刷新一下看看，几次发现没有更新



只有从这里获得已经放在公开展示的正确资料，从米游社同步的依旧没有变化，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] [Bug]: 我的角色一栏同步角色信息有误 (Issue #549)





 
游戏内更改后等了多久

**Comment by Lightczx** [comment]
橱窗的优先级高于米游社

**Comment by EyanAB** [comment]
这个是了解的，反馈的核心就是同步米游社的话同步过来也不是实时更新的，今天清除了账号文件重新登录米游社账号，同步才变成最新的 1A77A474FEDB43340EF29769909C5025 这是设备号 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月25日(星期六) 中午11:21
收件人: "DGP-Studio/Snap.Hutao";
抄送: "Author";
主题: Re: [DGP-Studio/Snap.Hutao] [Bug]: 我的角色一栏同步角色信息有误 (Issue #549)





 
橱窗的优先级高于米游社
 
&mdash;

**Comment by Lightczx** [comment]
相关的行为会在下版本更改

**Comment by EyanAB** [comment]
> 相关的行为会在下版本更改

好的，辛苦了，祝你今晚开心
