### ISSUE TITLE
[Bug]: 无法从米游社获得完整的角色资料

### ISSUE THREAD

**Issue by noiz321** [DGP-Studio/Snap.Hutao#551]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 问题分类

角色信息面板

### 发生了什么？

同步米游社角色资料的时候会显示下列错误，导致一些资料无法显示，如圣遗物

<img width="889" alt="屏幕截图 2023-02-23 115228" src="https://user-images.githubusercontent.com/126134079/220826236-1232fabf-d281-44a0-9a6a-faeb0b7dedfb.png">

<img width="869" alt="屏幕截图 2023-02-23 133000" src="https://user-images.githubusercontent.com/126134079/220827883-b977abf0-1ecc-4ea3-b2ce-05f015562f46.png">

**Comment by Lightczx** [comment]
网络问题
