### ISSUE TITLE
[Bug]: ListWrapper请求异常 653366069

### ISSUE THREAD

**Issue by ProfessorX** [DGP-Studio/Snap.Hutao#552]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19045.2486

### Snap Hutao 版本

1.4.15.0

### 问题分类

其它

### 发生了什么？

1. 已成功安装。
2. 已下载离线数据包。（这次是笔记本电脑的环境）
3. 电脑有网络环境。
4. 登录通行证后获取cookie报错了。

<img width="934" alt="Snipaste_2023-02-23_15-14-40" src="https://user-images.githubusercontent.com/1704352/220842841-8712b7c5-548a-4b16-a612-29f98965896b.png">

<img width="889" alt="Snipaste_2023-02-23_15-20-51" src="https://user-images.githubusercontent.com/1704352/220842867-38f04665-d8bb-4cad-95f8-d3ba05690d96.png">

### 你期望发生的行为？

能够正确获取账号信息。

**Comment by Lightczx** [comment]
网络问题请不要发本体问题Issue
![image](https://user-images.githubusercontent.com/36357191/220843059-fb7a0cc2-f6fc-4397-81cb-c4b2a38a886f.png)

**Comment by ProfessorX** [comment]
这个应该不是网络问题。

可以正常登录的。
-------
网络问题是公司台式机，笔记本可以正常安装。

台式机那个是真不知道咋整了，1.4.1.0 安装了用不了，15.0安装了报错。
-------
笔记本这个退出重新进一下好了。

**Comment by Lightczx** [comment]
6553366069 100%是你的基础网络设施问题
