### ISSUE TITLE
主页显示异常

### ISSUE THREAD

**Issue by moye12325** [DGP-Studio/Snap.Hutao#553]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

19044.2604

### Snap Hutao 版本

1.4.15.0

### 设备 ID

02B34297E4FD4AECE4ED290BAA140629

### 问题分类

公告

### 发生了什么？

![image](https://user-images.githubusercontent.com/43414308/220842265-7307369c-cbd5-43f1-b293-9d67c65d750a.png)
![image](https://user-images.githubusercontent.com/43414308/220842337-87debc60-a2ff-4ba4-8058-0a384713b13a.png)

主页显示异常，内置网页登陆打不开（已关闭代理，本地浏览器能够打开网页）
工具栏数据栏正常

### 相关的崩溃日志

地址下只含有这三个文件
![image](https://user-images.githubusercontent.com/43414308/220842868-fc4e57cd-2074-413e-bf94-acf36b424b67.png)

**Comment by Lightczx** [comment]
#552
