### ISSUE TITLE
[Bug]: 无法正常加载页面

### ISSUE THREAD

**Issue by tiantianyigntao5** [DGP-Studio/Snap.Hutao#554]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/FAQ/)，并认为我的问题没有在文档中得到解答
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我确认没有其他人已经提出了相同或类似的问题
- [X] 我会在下方的表单中附上充足的信息以帮助开发人员确定问题

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 设备 ID

CD4C478679D39B351BE727E1714DDDFA

### 问题分类

用户界面

### 发生了什么？

祈愿记录 成就管理 深渊记录 养成计划白屏。
我的角色卡在获取数据中。
深渊统计 角色资料 武器资料卡在加载中。
![QQ截图20230223160102](https://user-images.githubusercontent.com/119735343/220851458-a533b07f-e3e1-4bdf-80e2-943cff8f9606.png)
![QQ截图20230223160128](https://user-images.githubusercontent.com/119735343/220851468-a7c02a3b-6418-4657-92c0-9a7f7cc0518b.png)
![QQ截图20230223160133](https://user-images.githubusercontent.com/119735343/220851469-564a6aaa-3587-4f38-944b-aea6489c385a.png)
![QQ截图20230223160140](https://user-images.githubusercontent.com/119735343/220851470-aebb7e08-457c-4072-8dfd-e625ad8364b5.png)
![QQ截图20230223160144](https://user-images.githubusercontent.com/119735343/220851471-527deba5-4268-46a1-819b-96ea41691d55.png)
![QQ截图20230223160149](https://user-images.githubusercontent.com/119735343/220851476-b7738e23-9d36-4870-9f0f-4acdf5d8af7f.png)
![QQ截图20230223160153](https://user-images.githubusercontent.com/119735343/220851478-025d51da-5567-405d-932b-42f5d43da54b.png)
![QQ截图20230223160157](https://user-images.githubusercontent.com/119735343/220851483-569d4788-7cdd-4b5e-95c2-148b2ea0a963.png)

### 你期望发生的行为？

不知道是不是服务器崩溃了还是别的问题，希望能恢复正常

**Comment by Lightczx** [comment]
元数据服务升级中，稍等片刻
