### ISSUE TITLE
[Bug]: 启动游戏中账号绑定用户当前的角色uid只会是第一个绑定的账号

### ISSUE THREAD

**Issue by iysrmt** [DGP-Studio/Snap.Hutao#555]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 设备 ID

BC282D06F5985CC39776C72185A8402A

### 问题分类

游戏启动器

### 发生了什么？

游戏启动器 -> 账号 -> 检测 -> 绑定当前用户的角色。第一个绑定是显示正确的uid，换上第二个号，同样的操作，uid会显示第一个绑定的uid。(账号切换的功能是正常的)

**Comment by Masterain98** [comment]
切换米游社帐号后绑定

**Comment by iysrmt** [comment]
是我把功能理解错了，抱歉！
