### ISSUE TITLE
养成计划：请问一下养成计划我不论是从我的角色添加还是从角色资料添加，都会提醒我先登录，这个登录是指登陆什么？

### ISSUE THREAD

**Issue by kpl0111** [DGP-Studio/Snap.Hutao#556]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2604

### Snap Hutao 版本

1.4.15.0

### 问题分类

养成计算器

### 发生了什么？

请问一下养成计划我不论是从我的角色添加还是从角色资料添加，都会提醒我先登录，这个登录是指登录什么？胡桃我已经登录
![image](https://user-images.githubusercontent.com/73956723/221262734-85ed7edd-c9e6-43d2-aa8a-4106369376ff.png)

但还是提醒我请先登录，我不知道这个是指什么？
![image](https://user-images.githubusercontent.com/73956723/221262851-04ea9bcd-8d83-4212-b9c2-234e0439a78c.png)

**Comment by Masterain98** [comment]
刷新 Cookie
