### ISSUE TITLE
[Bug]: 深渊记录无法获取的问题

### ISSUE THREAD

**Issue by yuandl** [DGP-Studio/Snap.Hutao#558]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19042.1466

### Snap Hutao 版本

1.4.15.0

### 设备 ID

4D886BAE571980BF4DE8ABB073B9AD7B

### 问题分类

其它

### 发生了什么？

深渊记录查询异常，提示10001 please login

在胡桃官方文档中看到10001需要刷新cookie，已刷新，刷新后两个角色中一个角色可以正常获取深渊记录，一个扔提示10001

在git上搜索10001以及please login未能找到解决本问题的方案

商店中未发现新版本

截止提问题的时候，根据问题关键字搜索能找到的解决方案只有刷新cookie，但是只对两个角色中的一个生效。手机上打开米有社深渊或者便签不需要额外验证操作。

![image](https://user-images.githubusercontent.com/7816984/221339953-4a487739-2251-44d4-b57e-5873be6e40ae.png)

### 你期望发生的行为？

期望正确获取角色深渊记录

**Comment by yuandl** [comment]
我先升级一下win10版本试一下

**Comment by Lightczx** [comment]
刷新cookie

**Comment by yuandl** [comment]
> 刷新cookie

您好，截图中我特意展示已经刷新cookie了，并且两个角色都刷新后，有一个可以正常获取深渊数据，另一个始终不能。
![image](https://user-images.githubusercontent.com/7816984/221340097-e13e19fd-3e13-408e-82bc-a3f0f93d8667.png)

**Comment by yuandl** [comment]
> 刷新cookie

再次刷新cookie仍未解决问题，请问是否只能升级系统试一下？

**Comment by Lightczx** [comment]
与系统无关

**Comment by yuandl** [comment]
> 与系统无关

感谢回答，当前除了刷新cookie未进行其他操作，也未解决问题，目前还是一个角色可以正常获取，一个角色提示10001,。

**Comment by Lightczx** [comment]
刷新不出的cookie删了重新添加

**Comment by yuandl** [comment]
> 刷新不出的cookie删了重新添加

删除重新添加后正常，可以将相关提醒添加到可搜索的帮助文档中，非常感谢您的帮助

**Comment by Lightczx** [comment]
@Masterain98

**Comment by Masterain98** [comment]
DGP-Studio/Snap.Hutao.Docs@18beeeb
