### ISSUE TITLE
[Bug]: WIN11打开闪退，已装.NET DESKTOP和WEBVIEW2，LOGS.DB无任何记录

### ISSUE THREAD

**Issue by vivienicepig** [DGP-Studio/Snap.Hutao#56]
### Windows 版本

22000.978

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

WIN11打开闪退，已装.NET DESKTOP和WEBVIEW2，LOGS.DB无任何记录

### 你期望发生的行为？

能打开

### 相关的崩溃日志 位于 %HOMEPATH%/Documents/Hutao/Log.db

```shell
无任何记录
```

**Comment by Lightczx** [comment]
删除  %HOMEPATH%/Documents/Hutao  文件夹

**Comment by vivienicepig** [comment]
> 

一样。。。

**Comment by Lightczx** [comment]
在系统设置-应用 中找到胡桃并通过 高级选项-重置 胡桃

**Comment by vivienicepig** [comment]
> 

也不行。。。

**Comment by vivienicepig** [comment]
> 在系统设置-应用 中找到胡桃并通过 高级选项-重置 胡桃

下了源码，编译成功，DEBUG UNPACKAGE运行时提示
System.DllNotFoundException:“Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)”

**Comment by Lightczx** [comment]
Debug (Packaged)

**Comment by Lightczx** [comment]
应该是由于未安装相关依赖导致的
Xaml检查失败
https://github.com/DGP-Studio/Snap.Hutao/blob/fd35213741385afbf7f7bfffe934ade2e6709f0e/src/Snap.Hutao/Snap.Hutao/Program.cs#L34
