### ISSUE TITLE
[Bug]: 程序内部无法登录

### ISSUE THREAD

**Issue by szYuanGoa** [DGP-Studio/Snap.Hutao#560]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 设备 ID

FF4A49A972FEB15392F4D3F26A67AA8C

### 问题分类

用户界面

### 发生了什么？

无法在程序内部登录
![image](https://user-images.githubusercontent.com/126322930/221352108-f04d86d3-93c7-4337-9a67-58c298eb44f8.png)

**Comment by Lightczx** [comment]
没装 Webview2 Runtime ?

**Comment by szYuanGoa** [comment]
> 没装 Webview2 Runtime ?

![image](https://user-images.githubusercontent.com/126322930/221352738-added817-b5b3-433e-a554-a7e9eb867215.png)

**Comment by Lightczx** [comment]
右键刷新

**Comment by szYuanGoa** [comment]
> 右键刷新

这程序里右键没反应呀

**Comment by Lightczx** [comment]
WebView2 是开着胡桃装的？

**Comment by szYuanGoa** [comment]
> WebView2 是开着胡桃装的？

 对啊 这个不是和edge捆绑的东西吗

**Comment by Lightczx** [comment]
重启胡桃

**Comment by szYuanGoa** [comment]
> 重启胡桃

重启过很多次了 其它界面都能打开 就是在程序内部登录这个米哈游就是不行

**Comment by Lightczx** [comment]
那你需要重启电脑

**Comment by szYuanGoa** [comment]
> 那你需要重启电脑

重启过了 还是打不开

**Comment by Lightczx** [comment]
Edge 浏览器装着么

**Comment by szYuanGoa** [comment]
> Edge 浏览器装着么

装着的
