### ISSUE TITLE
深渊刷新提示（状态: 10001 I信息: Please login）文档读了，按文档办了，还是不行

### ISSUE THREAD

**Issue by XinYiheng6** [DGP-Studio/Snap.Hutao#562]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2673

### Snap Hutao 版本

1.4.15.0

### 设备 ID

4051B5535117BAB7D6748433C0E35841

### 问题分类

其它

### 发生了什么？

![FX}HP68EP46~UE7FL~J)Y4V](https://user-images.githubusercontent.com/87703709/221356666-01312e13-96ee-4dd9-a808-101021b23219.png)
![6( B`M4FQ A6RA}B3}WNAMT](https://user-images.githubusercontent.com/87703709/221356680-de6e4676-5e6b-460a-a166-3ca70960c3e6.png)

### 你期望发生的行为？

可以正常使用

**Comment by Lightczx** [comment]
删了重新添加

**Comment by XinYiheng6** [comment]
现在已经可以了

**Comment by XinYiheng6** [comment]
多谢
