### ISSUE TITLE
[Bug]: 无法导入抽卡记录

### ISSUE THREAD

**Issue by Georgebillion** [DGP-Studio/Snap.Hutao#564]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22H2(19045.2604)通过WINDOWS UPDATE更新上来的

### Snap Hutao 版本

2023.2.24.1

### 设备 ID

713B2DC293772C50780E258915CA3D71

### 问题分类

祈愿记录

### 发生了什么？

使用老版1.1.8.0胡桃导出的V2.2 UIGF JSON数据导入到最新版本是发生错误，显示导入失败，不支持的数据格式，已通过UIGF检查器检查数据格式正确

### 你期望发生的行为？

可以正常导入数据

**Comment by Lightczx** [comment]
提供文件

**Comment by Georgebillion** [comment]
[抽卡数据.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10833402/default.zip)
数据在此

**Comment by Georgebillion** [comment]
不太明白，难道2023.1.30.1比2023.2.24.1更新？

**Comment by Masterain98** [comment]
Valid count: 1558/1558

**Comment by Lightczx** [comment]
2023.2.24.1是测试版本，你不应该下载

**Comment by Georgebillion** [comment]
> 2023.2.24.1是测试版本，你不应该下载

先不管测试不测试版本，我现在想问的就是老版胡桃数据不互通？

**Comment by Lightczx** [comment]
> Valid count: 1558/1558

测试了是可以导入的

**Comment by Georgebillion** [comment]
> 

但我这里不可以

**Comment by Georgebillion** [comment]
![image](https://user-images.githubusercontent.com/40432824/221404595-1547153e-b065-4602-bd0c-235f0aa99a1c.png)

**Comment by Lightczx** [comment]
用正式版试一下

**Comment by Georgebillion** [comment]
等我几分钟

**Comment by Georgebillion** [comment]
> 用正式版试一下

在测试版出现这个问题算不算bug？

**Comment by Lightczx** [comment]
不算

**Comment by Lightczx** [comment]
测试版本就不稳定

**Comment by Georgebillion** [comment]
> 测试版本就不稳定

会不会和导出时候用的胡桃版本过老有关系？

**Comment by Lightczx** [comment]
无关

**Comment by Georgebillion** [comment]
正式版测试正常，我等会儿自行关闭issues

**Comment by Georgebillion** [comment]
> 实际上有一定的关系，1.1.8版本的胡桃存在导出BUG

后续是否会对这类情况对针对性修复？

**Comment by Lightczx** [comment]
1.2+就已经修复了导出的格式，先前导出的文件无法兼容
