### ISSUE TITLE
[Bug]: 祈愿记录导入失败

### ISSUE THREAD

**Issue by lullizhang** [DGP-Studio/Snap.Hutao#565]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1265

### Snap Hutao 版本

1.4.15.0

### 设备 ID

F43FFAE532C6A61E7E7702C667382ADB

### 问题分类

祈愿记录

## 当前问题
在祈愿记录功能中导入 UIGF v2.2 版本的 Json 文件时提示「导入失败 导入数据中包含了不支持的物品」
![Snipaste_2023-02-27_15-30-25](https://user-images.githubusercontent.com/7028372/221509011-cec79d1f-817c-4c66-a614-6d2dd872901e.png)

当前的问题是在试图处理前置问题后遇到的

## 前置问题
打开祈愿记录后不显示任何内容，仅提示「UserdataCorruptedException 用户数据已损坏：不支持的 Item Id：0」
为了解决祈愿记录打不开的问题，我删除了 Documents 中的 Hutao 文件夹后，祈愿记录可正常打开
备注：上次安装胡桃是很久之前的事（具体版本想不起来了），当时使用的版本还未上架 Microsoft Store
![Snipaste_2023-02-27_16-11-14](https://user-images.githubusercontent.com/7028372/221510001-3872cada-b3d5-4766-955f-5e7fb1df2f7d.png)

## 祈愿记录文件
[Wishlog_170486980_20230227_152857.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10837495/Wishlog_170486980_20230227_152857.zip)

### 你期望发生的行为？

能正常导入祈愿记录

**Comment by Lightczx** [comment]
![image](https://user-images.githubusercontent.com/36357191/221512974-6edacb6b-eed8-4733-b2ec-5a4a8fefa746.png)
