### ISSUE TITLE
[Bug]: 国际服转换一直下载资源

### ISSUE THREAD

**Issue by jovensun** [DGP-Studio/Snap.Hutao#566]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2604

### Snap Hutao 版本

1.5.1.0

### 设备 ID

846D6FC7E55E8BA7E0901ED65BDD04AF

### 问题分类

游戏启动器

### 发生了什么？

开发者们，你们好。
关于服务器转换，我看了文档和视频教程后出现下面问题：
我在从官方服转换到国际服过程中一直重复下载  global-metadata.dat 文件，然后我通过手动下载转换文件并替换后，成功转为国际服。  然后再通过胡桃转为官方服依然出现相同的问题。
转换文件下载地址：https://cloud.06dn.com/s/xeabIk?path=%2F  （来自 https://github.com/DawnFz/Genshin.Launcher.Plus）

我知道此问题，和 #427 、 #436  类似。
但我感觉并不是网络问题造成的。

我尝试了裸连和梯子都卡在这一步。

出现此问题后文件一直重复累计下载，过几分钟后关闭胡桃可以看到文件已经达到了4G。
![F`JFGJ$832GE`JQO%Z)X6K9](https://user-images.githubusercontent.com/19667184/221624200-d27afa45-7fc1-4b4e-a305-74b2374c7802.png)

### 你期望发生的行为？

希望能正常切换服务器。

**Comment by TechOtakupoi233** [comment]
类似问题，不同的是Hutao下载这个文件到一半直接卡死了（未响应），却一直有下载流量和硬盘写入，结束进程才停下来。
已经尝试重新安装商店版。

**Comment by HubertYoung** [comment]
昨晚下载了最新的2023.2.28.2测试版的程序并安装成功了，但是从国服切换到国际服并未解决global那个文件一直下载的问题

**Comment by Lightczx** [comment]
可能是文件夹权限问题，global-metadata.dat的权限可能不足，可以手动修改为完全控制

**Comment by Lightczx** [comment]
下版本修复
