### ISSUE TITLE
[Bug]: 无法启动游戏，提示找不到PowerShell的安装目录

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#567]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22623.1325

### Snap Hutao 版本

1.5.1.0

### 设备 ID

E0238BE05E5071D48B78227BC23443A8

### 问题分类

游戏启动器

### 发生了什么？

微软商店更新最新版后，启动游戏提示错误“找不到powershell的安装目录”
Path里有powershell路径，安装powershell7也一样提示错误
![image](https://user-images.githubusercontent.com/2825342/221666562-ce340177-bdc6-4ef3-aef3-e87113ddfb67.png)
![image](https://user-images.githubusercontent.com/2825342/221666317-21310e66-2043-400e-81f6-8c5c1fe2e447.png)

**Comment by congcong0623** [comment]
为什么最新版还是会这样

**Comment by Lightczx** [comment]
找不到路径可以去设置里面自行选择 @congcong0623
