### ISSUE TITLE
[Bug]: 关于1.5.1.0工具箱中 用多账号启动游戏显示 未开启长路径功能

### ISSUE THREAD

**Issue by EvenDa** [DGP-Studio/Snap.Hutao#568]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

版本 win11 21H2

### Snap Hutao 版本

1.5.1.0

### 设备 ID

C39A3AEC181C5AF309E0440479513BA6

### 问题分类

游戏启动器

### 发生了什么？

在启动切换账号时提示未开启长路径功能 异常：RuntimeEnvironmentException，也确实按照工具箱中文档所给到的下载 EnableLongPaths.zip 后解压所给到的方案 也未解决此问题，另外参考了此Issues [https://github.com/DGP-Studio/Snap.Hutao/issues/543]  我powershell安装位置为：C:\Windows\System32\WindowsPowerShell\v1.0  

### 你期望发生的行为？

希望开发者大大可以帮助一下我 特别是我这种拥有多账号切换的玩家~

**Comment by EvenDa** [comment]
更新到 win11 22H2版本之后 还是多账号启动不了游戏 提示未开启长路径功能

**Comment by Masterain98** [comment]
@Lightczx [check this](https://answers.microsoft.com/en-us/windows/forum/all/long-file-path-issues-in-windows-11-pro-with/0c440721-e35a-4b58-9f5a-645656768f9d?page=4)

**Comment by EvenDa** [comment]
> 截图下组策略中面`Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem`的配置

![111111](https://user-images.githubusercontent.com/126536833/222434749-fd1ac2ba-bcea-441c-a49c-d96d77f836d6.png)
是这个么
