### ISSUE TITLE
[Feat]: 添加一个配置文件和游戏信息云同步功能

### ISSUE THREAD

**Issue by ZhiJuan0724** [DGP-Studio/Snap.Hutao#570]
### 背景与动机

原神抽卡信息官方保存时间较短，在软件的更新，或者使用不同设备的人，希望能能做到自动信息同步，而不是手动去备份json
对于同步的信息，也可以同时包括软件配置信息，游戏成就等

### 想要实现或优化的功能

可以让玩家选择第三方的webdav服务商进行同步的方式
这样也不会增加服务器的开销

**Comment by Lightczx** [comment]
#34
