### ISSUE TITLE
[Feat]: 请求抽卡历史中增加当前已抽抽数

### ISSUE THREAD

**Issue by Zj031210** [DGP-Studio/Snap.Hutao#572]
### 背景与动机

背景：目前用这个功能的想必都是看自己抽卡历史的，目前各个方面都做的非常好，但是就唯独没有这个功能

动机：每次想看自己抽数的时候，总是要开计算器一个个减掉来看自己目前抽数

### 想要实现或优化的功能

在当前已抽抽数旁新增一个卡池当前抽数就好力

**Comment by Lightczx** [comment]
![image](https://user-images.githubusercontent.com/36357191/222032197-07b95d4a-82a5-415c-a7f9-827026016eec.png)
这两个是什么

**Comment by Zj031210** [comment]
> ![image](https://user-images.githubusercontent.com/36357191/222032197-07b95d4a-82a5-415c-a7f9-827026016eec.png) 这两个是什么

这两个不是目前已抽的五星四星数量吗 我指的是距离上次出五星已抽抽数

**Comment by Masterain98** [comment]
Duplicate of #547 
Duplicate of #544

**Comment by Lightczx** [comment]
自己好好算算吧

**Comment by Masterain98** [comment]
> > ![image](https://user-images.githubusercontent.com/36357191/222032197-07b95d4a-82a5-415c-a7f9-827026016eec.png) 这两个是什么
> 
> 这两个不是目前已抽的五星四星数量吗 我指的是距离上次出五星已抽抽数

你猜猜为什么会有一个进度条在那里，而不是单纯一个数字
