### ISSUE TITLE
[Feat]: 请求增加一个默认以管理员方式运行的设置

### ISSUE THREAD

**Issue by YunJiStarrySky** [DGP-Studio/Snap.Hutao#573]
### 背景与动机

如果想要不锁帧的话，每次都要右键—》更多 —》以管理员方式运行，感觉有点麻烦，而且还容易忘。

但从微软应用商店下载的胡桃工具箱自己又无法设置默认以管理员方式运行。

### 想要实现或优化的功能

可以在胡桃工具箱里的设置加一个默认以管理员方式运行的选项。

**Comment by Lightczx** [comment]
无法实现

**Comment by Masterain98** [comment]
能不能先看看文档
