### ISSUE TITLE
[Bug]: 无法启动Hutao程序，无任何反应

### ISSUE THREAD

**Issue by diazynez** [DGP-Studio/Snap.Hutao#574]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

Windows 10 Build 19045 (22H2)

### Snap Hutao 版本

3月1日在Microsoft Store下载的最新版本，无法启动程序因此无法查看

### 设备 ID

3月1日在Microsoft Store下载的最新版本，无法启动程序因此无法查看

### 问题分类

安装和环境

### 发生了什么？

3月1日，在Microsoft Store下载的最新版本Snap Hutao无法启动程序，无论是否为管理员模式启动。
启动时会短暂在后台运行，但一段时间后自动结束。
![Snipaste_2023-03-01_14-53-07](https://user-images.githubusercontent.com/21095959/222065845-d0df9487-13d0-4e0f-ad85-e2a51bf500d1.png)

### 你期望发生的行为？

希望能正常使用

**Comment by Masterain98** [comment]
系统日志查看器中查找相关日志

**Comment by diazynez** [comment]
![NET Runtime](https://user-images.githubusercontent.com/21095959/222379266-1ff5f703-fdd5-4fc5-9434-c04307c799f5.jpeg)
![Application Error](https://user-images.githubusercontent.com/21095959/222379302-a7bb12fa-eede-4c1a-9c05-e358c4295a46.jpeg)

**Comment by Lightczx** [comment]
删除Userdata.db

**Comment by diazynez** [comment]
问题已解决，感谢解答
