### ISSUE TITLE
[Bug][Blocking]: GachaLog Page Localization

### ISSUE THREAD

**Issue by NeonCao** [DGP-Studio/Snap.Hutao#577]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2604

### Snap Hutao 版本

1.5.1.0

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录页在英文UI中显示为空白页，如图中文ui情况下正确显示，其他标签页正常
![image](https://user-images.githubusercontent.com/69925487/222177051-9383f41d-04e7-4606-8f1e-83be790033d6.png)
![image](https://user-images.githubusercontent.com/69925487/222177609-a04e9945-f5f0-46e2-96d9-62090ff88e0c.png)

**Comment by Masterain98** [comment]
可复现。应该是因为之前的祈愿记录是全靠中文记录的原因，应该需要后续维护将物品名称更改为物品 ID。

**Comment by Lightczx** [comment]
According to this issue
https://github.com/DGP-Studio/Snap.Data.Mapper/issues/1
Mapper need to be modifed to compat with globalization metadata.
The problem here is really blocking, and we can't provide a fix now.

**Comment by Lightczx** [comment]
Before the mapper is patched, gacha log besides CHS won't be supported.
