### ISSUE TITLE
关于启动

### ISSUE THREAD

**Issue by doge-47** [DGP-Studio/Snap.Hutao#578]
### 背景与动机

你好，听说可以高帧启动原神我因此下载了此应用，但是每次启动需要右键选择管理员启动，这样非常麻烦。右键快捷方式点高级发现不能打开默认管理员启动，修改权限将安装文件夹复制出win store则不能打开该应用，请问是否有办法解决这一问题或者能否提供其他的下载方式来解决这一问题。

### 想要实现或优化的功能

双击桌面上的快捷方式图标时默认以管理员身份启动

**Comment by Masterain98** [comment]
看文档
