### ISSUE TITLE
[Feat]: 点击弹出通知的“开始游戏”按钮时也能以高帧率运行游戏

### ISSUE THREAD

**Issue by RA1NO3O** [DGP-Studio/Snap.Hutao#583]
### 背景与动机

目前的应用可以通过按住Ctrl+Alt+Shift组合键快速以管理员模式启动从而以高帧率运行。

但是，在点击通知中的“开始游戏”时按住这些组合键来启动游戏并不会使高帧率功能生效。

### 想要实现或优化的功能

在点击通知中的“开始游戏”按钮并弹出选择账号对话框后，可以考虑设置一个监听器来监听一个或多个组合键(比如Shift键)是否按下，并决定是否替换启动游戏按钮的行为(以高帧率运行)。

**Comment by Lightczx** [comment]
无法实现
