### ISSUE TITLE
[Feat]: 调用第三方启动器

### ISSUE THREAD

**Issue by snouker** [DGP-Studio/Snap.Hutao#585]
### 背景与动机

1. 因反和谐和解锁视角有第三方启动器的需求(第三方启动器闭源)
2. 有多个游戏本体和云原神的请求也许可以合并

### 想要实现或优化的功能

- 启动游戏中添加额外可选择```启动配置```,并可添加额外配置,每个配置可指定```游戏路径```与```额外参数```.
- 外观设置保留,```启动配置```中可在```额外参数```通过变量将外观参数引入
- 按照之前逻辑判断```游戏路径```以判断是否保留```高级功能```
- 在某处添加设置可以强制启用```高级功能```(目前感觉没用)

**Comment by Lightczx** [comment]
> 1. 因反和谐和解锁视角有第三方启动器的需求(第三方启动器闭源)

为什么要用启动器去启动启动器呢？

**Comment by snouker** [comment]
看完之后去创建了一个快捷方式,然后开始给自己~~傻~~找借口:

- 习惯了便捷,不想手动去启动启动器
- 第三方启动器单文件 纯命令行并把参数转发给```YuanShen.exe```,启动完游戏就自己退出.~~我就直接把它当成```YuanShen.exe```忘了它是启动器了~~
- 尝试用胡桃选择第三方启动器,但是胡桃不应用(可能因为不是游戏目录);将第三方启动器放于游戏目录,第三方启动器~~因为安全问题~~直接开摆

感觉没必要的话直接close就好
