### ISSUE TITLE
[Network]:元数据无法访问

### ISSUE THREAD

**Issue by q12p1** [DGP-Studio/Snap.Hutao#586]
### 提交你的网络诊断报告

无法进入官网，snap Hutao所有与网络有关的均无法使用（网络诊断工具也无法访问）

### 你的地理位置

天津

### 你的运营商

中国联通

### 你的问题

完全无法连接服务器

**Comment by q12p1** [comment]
刚刚

**Comment by Lightczx** [comment]
![image](https://user-images.githubusercontent.com/36357191/222948127-b173c4a7-5a13-4147-8cd6-359ed52be62f.png)

**Comment by q12p1** [comment]
> ![image](https://user-images.githubusercontent.com/36357191/222948127-b173c4a7-5a13-4147-8cd6-359ed52be62f.png)

github链接会直接跳转github.com

**Comment by Lightczx** [comment]
这完全是你的问题了，我这里完全正常

**Comment by q12p1** [comment]
> 

edge提示拼写错误，我可能点错了233333

**Comment by Masterain98** [comment]
> > 
> 
> edge提示拼写错误，我可能点错了233333

更换你的DNS

**Comment by q12p1** [comment]
> > > 
> > 
> > 
> > edge提示拼写错误，我可能点错了233333
> 
> 更换你的DNS

那得等一下，我正在进行网络测试（大部分都是丢包）

**Comment by q12p1** [comment]
刚才网络测试直接闪退了。。。。

**Comment by Masterain98** [comment]
> @Lightczx 网络测试完诊断报告会在哪里（软件直接闪退了，没看见诊断报告存在了哪里）

用控制台运行下看看

**Comment by q12p1** [comment]
得，白跑了

**Comment by Masterain98** [comment]
> 无法进入官网，snap Hutao所有与网络有关的均无法使用（网络诊断工具也无法访问）

使用客户端时元数据是否能下载成功？

**Comment by q12p1** [comment]
> > 无法进入官网，snap Hutao所有与网络有关的均无法使用（网络诊断工具也无法访问）
> 
> 使用客户端时元数据是否能下载成功？

不能

**Comment by q12p1** [comment]
> > > 无法进入官网，snap Hutao所有与网络有关的均无法使用（网络诊断工具也无法访问）
> > 
> > 
> > 使用客户端时元数据是否能下载成功？
> 
> 不能

要不然我也不会来这里提问hhh

**Comment by Lightczx** [comment]
请勿在反馈时评论与反馈本身无关的内容（语气词，非问题本身的内容）@q12p1

**Comment by q12p1** [comment]
> 请勿在反馈时评论与反馈本身无关的内容（语气词，非问题本身的内容）@q12p1

呃呃，好的

**Comment by Masterain98** [comment]
> > 使用客户端时元数据是否能下载成功？
> 
> 不能

那大概率是你网络问题，元数据是完全的国内服务器。

使用控制台属于下面三个命令看下输出结果是什么
```
nslookup hut.ao
nslookup hutao-metadata.snapgenshin.com
ipconfig
```

![image](https://user-images.githubusercontent.com/10614984/222949206-e0674257-eda5-492a-bb6a-5a2b13ce5562.png)

**Comment by q12p1** [comment]
> 

输出我复制下来了
C:\Windows\System32>nslookup hut.ao
服务器:  one.one.one.one
Address:  1.1.1.1

非权威应答:
名称:    cl-f3485468.gcdn.co
Addresses:  2a03:90c0:999c::12
          81.28.12.12
Aliases:  hut.ao


C:\Windows\System32>nslookup hutao-metadata.snapgenshin.com
服务器:  one.one.one.one
Address:  1.1.1.1

非权威应答:
名称:    cl-f3485468.gcdn.co
Addresses:  2a03:90c0:999c::12
          81.28.12.12
Aliases:  hutao-metadata.snapgenshin.com


C:\Windows\System32>ipconfig

Windows IP 配置


无线局域网适配器 本地连接* 9:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::6487:cc96:c5f0:a141%12
   IPv4 地址 . . . . . . . . . . . . : 192.168.31.235
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.31.1

以太网适配器 蓝牙网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

**Comment by Masterain98** [comment]
将你的DNS换成国内的DNS，你被解析到海外线路去了

**Comment by q12p1** [comment]
> 将你的DNS换成国内的DNS，你被解析到海外线路去了

我先试一下（谷歌的行吗）

**Comment by q12p1** [comment]
省流：DNS整的
