### ISSUE TITLE
[BUG]软件卸载后频繁弹窗无法影响电脑正常使用

### ISSUE THREAD

**Issue by NeetMochi** [DGP-Studio/Snap.Hutao#588]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22000.1574

### Snap Hutao 版本

1.5.1

### 问题分类

其它

### 发生了什么？

卸载软件后频繁弹出弹窗 打开hutao链接, 并导向微软应用商店中的对应页面.

### 你期望发生的行为？

不再弹出相关弹窗

**Comment by NeetMochi** [comment]
安装1.5.1版本后重新卸载仍存在此问题

**Comment by NeetMochi** [comment]
我手动删除了任务计划, 目前已经不会弹窗了.

**Comment by Masterain98** [comment]
https://hut.ao/advanced/uninstall.html
