### ISSUE TITLE
已经按照常见的应用程序异常改过长文件限制，也手动确定过已经更改“”

### ISSUE THREAD

**Issue by wilsonfd** [DGP-Studio/Snap.Hutao#589]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2604

### Snap Hutao 版本

1.5.1.0

### 设备 ID

B4EAD6D134E3D258C80034EC0691A31F

### 问题分类

安装和环境

### 发生了什么？

已经开启了长文件功能，并且已经重新启动过电脑，仍然显示一样的报错

### 你期望发生的行为？

提供解决办法

**Comment by Lightczx** [comment]
#568
