### ISSUE TITLE
[Bug]: 多账号下祈愿记录刷新后UID未正确显示

### ISSUE THREAD

**Issue by JahooYoung** [DGP-Studio/Snap.Hutao#590]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1265

### Snap Hutao 版本

1.5.1.0

### 设备 ID

DE2D1D35514A54EA13B1B3684CB8FD7C

### 问题分类

祈愿记录

### 发生了什么？

在登陆了多个账号的情况下，假如现在我正在查看账号A的祈愿记录，然后用账号B的Stoken刷新记录，刷新后下面三个面板的信息是正确的账号B的记录，但左上角仍然显示的是账号A的UID。此时若要翻看账号A的记录，则需要点击账号B的UID后再点击账号A的UID才能切换到账号A的祈愿记录。

### 你期望发生的行为？

Stoken刷新后应该更新左上角的UID，使得下面三个面板展示的信息与左上角的UID是对应的。

**Comment by Lightczx** [comment]
提供设备Id @JahooYoung

**Comment by JahooYoung** [comment]
已加上设备ID

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 DE2D1D35514A54EA13B1B3684CB8FD7C

**Comment by Lightczx** [comment]
Might related with https://github.com/microsoft/microsoft-ui-xaml/issues/8125

**Comment by Lightczx** [comment]
下版本修复
