### ISSUE TITLE
[Bug]: SG祈愿记录导入Hutao错误

### ISSUE THREAD

**Issue by Gomboc-9** [DGP-Studio/Snap.Hutao#592]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2604

### Snap Hutao 版本

1.5.1.0

### 问题分类

祈愿记录

### 发生了什么？

我在SG中导出了json格式的祈愿记录文件，版本号2022.8.26.5230，UIGFv2.2.但将其导入最近版的Hutao中却出现了最早期记录混乱的情况（出错数据一共800左右，记录总抽数2800），出现100多抽保底的数据，甚至每次导入的错误抽数的数字和人物都会变，有时候还会少计入某个角色。我下载了最后一版SG版本号2022.10.25.10000，UIGFv2.2并将这份记录导入发现是正常的，并且用此版本生成了新的json记录导入Hutao发现仍是错误。

### 你期望发生的行为？

祈愿记录导入正常

**Comment by Lightczx** [comment]
请提供源文件
SG导入导出时并不会校验数据正确性，胡桃的校验更加严格

**Comment by Lightczx** [comment]
同时提供设备ID

**Comment by Gomboc-9** [comment]
设备ID  D945F6B1A3ED4CCD6C87560EB8E97BC8
[101023031.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10941688/101023031.zip)
这是原始版本
[101023031-1.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10941690/101023031-1.zip)
这是经最后一版SG重新导出的版本

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 D945F6B1A3ED4CCD6C87560EB8E97BC8

**Comment by Lightczx** [comment]
日志中存在多个重复Id
1623218760001373602

**Comment by Gomboc-9** [comment]
此记录是否有修复的方法？

**Comment by Lightczx** [comment]
@Masterain98

**Comment by Masterain98** [comment]
[101023031_indexreset.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10945622/101023031_indexreset.zip)
试一下这个版本

**Comment by Gomboc-9** [comment]
还是错误     我另外拥有.xlsx的格式，打开发现最早的850条记录却只有两个ID。不知是否可以通过此文件修复？
[101023031.xlsx](https://github.com/DGP-Studio/Snap.Hutao/files/10946903/101023031.xlsx)

**Comment by Masterain98** [comment]
上面那个已经是修过了的，我本地试过是没问题的。你还有什么错误？

**Comment by Gomboc-9** [comment]
这个抽数和次序全是错的  而且你看看角色活动的UP平均抽数是多少

**Comment by Masterain98** [comment]
你发来的数据一共就2843条数据，1832+506+505你算算多少？

**Comment by Masterain98** [comment]
顺序问题的修复

[101023031_indexreset_v2.zip](https://github.com/DGP-Studio/Snap.Hutao/files/10947359/101023031_indexreset_v2.zip)

**Comment by Lightczx** [comment]
五星和UP的区别。。。。

**Comment by Masterain98** [comment]
> 保底90抽 记录里没一个过90的还平均95抽是吧

以你的图，刻晴+钟离=138，七七+胡桃=156，这叫不超90？
