### ISSUE TITLE
[Bug]: 活动公告日期和时间显示与详情内部的时间不匹配

### ISSUE THREAD

**Issue by vwh** [DGP-Studio/Snap.Hutao#596]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1344

### Snap Hutao 版本

1.5.1.0

### 问题分类

公告

### 发生了什么？

活动公告日期和时间显示与详情内部的时间不匹配。
![image](https://user-images.githubusercontent.com/7691760/224538273-4fafbf14-0ebb-4cdf-8ff0-9d7fc6ab3781.png)
![image](https://user-images.githubusercontent.com/7691760/224538292-59f9898a-9754-4f81-ac53-e144bf4a149f.png)

**Comment by Masterain98** [comment]
![image](https://user-images.githubusercontent.com/10614984/226088112-b453889d-ab67-44b1-934f-622414269756.png)
