### ISSUE TITLE
手动设置圣遗物组合，词条，武器，并自动计算伤害的工具

### ISSUE THREAD

**Issue by CGBB0** [DGP-Studio/Snap.Hutao#597]
### 背景与动机

省了很大的计算时间，同时对我这种不会算伤害的人很有帮助。（如果觉得太麻烦或者没有必要的话，把这个issue删掉或者告诉我删掉就行）

### 想要实现或优化的功能

自定义圣遗物组合，自定义圣遗物词条，自定义武器，然后自动算伤害的功能。目前提瓦特小助手和云仔有替换武器的功能，但是光有武器感觉不太够。因为一个角色一个计算方法，所以一个一个角色出也行。

**Comment by Lightczx** [comment]
#42
