### ISSUE TITLE
[Feat]: 我的角色/角色资料/武器资料支持排序

### ISSUE THREAD

**Issue by AnLisaWae** [DGP-Studio/Snap.Hutao#599]
### 背景与动机

在这几个显示角色以及武器的页面，角色以及武器的默认排序无特别规律的排序，寻找某一特定角色或武器需要少量时间从所有选项中检索
![未标题-1](https://user-images.githubusercontent.com/93753833/224747155-83217f9d-7d54-4d05-85b1-7eb21ef20296.jpg)

如果能增加列表框或单选框类型的过滤器，过滤规则比如说通过武器类型来分门别类显示特定规则下的所有武器或使用该武器的角色，也许能进一步优化使用体验

### 想要实现或优化的功能

希望能在这几个界面，为角色和武器增加过滤器，方便更快速的查找对应的内容
![未标题-1](https://user-images.githubusercontent.com/93753833/224747414-4e45f880-5633-415a-ba44-29323751b727.jpg)

**Comment by Lightczx** [comment]
Tracked by #1394
