### ISSUE TITLE
【建议】添加关闭程序的首选项

### ISSUE THREAD

**Issue by AdminRoc** [DGP-Studio/Snap.Hutao#60]
### 你想要实现或优化的功能？

点击关闭键时，选择直接退出程序或最小化程序到系统托盘的选项
![image](https://user-images.githubusercontent.com/96916320/192815345-b722af23-a037-40b3-9c68-f348587590d0.png)

**Comment by Lightczx** [comment]
由于WinUI的限制，不太可能实现这个功能

**Comment by imxdsf** [comment]
那以后的Snap.HuTao的右上角关闭按钮只会产生关闭进程的效果吗
