### ISSUE TITLE
[Bug]: 从设置切换到其他页面时程序重启

### ISSUE THREAD

**Issue by AllesUgo** [DGP-Studio/Snap.Hutao#600]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1265

### Snap Hutao 版本

1.5.3.0

### 设备 ID

BF2E61F1F6A08AC34E35BB490DE5FAFA

### 问题分类

其它

### 发生了什么？

进入设置页面，选择任意一种语言后，切换至任何其他页面，程序都会重启一次。且下一次打开后只需要进入设置页面，无需切换任何语言，再切换到其他页面也会发生重启。

### 你期望发生的行为？

在没有切换语言时切换页面不发生重启

**Comment by Lightczx** [comment]
1.5.3 的已知问题，等待1.5.4修复
