### ISSUE TITLE
关于【养成计划】优化的建议

### ISSUE THREAD

**Issue by wujl1020** [DGP-Studio/Snap.Hutao#601]
### 背景与动机

当前【养成计划】是支持从【我的角色】菜单中添加的，这是一个非常方便的功能；但原神的角色养成周期是较长的，尤其天赋提升需要较长的时间来积攒材料和摩拉；在培养过程中，【养成计划】不能更新，只能删除重新创建。

### 想要实现或优化的功能

【养成计划】菜单中，对来自于【我的角色】创建的角色或武器养成计划单独标识；当【我的角色】中获取到角色等级，天赋等级等更新信息时，【养成计划】中创建自【我的角色】的养成计划信息同步更新。

**Comment by MCXCC** [comment]
能否做成类似 https://ark-nights.com/ 这样按天赋等级、突破等级、人物等级逐条设置的养成列表，完成后提供勾选服务。在统计材料时能自动计算合成的下级材料。
