### ISSUE TITLE
[Bug]: 浏览器无法正确显示官网

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#602]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2546

### Snap Hutao 版本

1.5.4.0

### 问题分类

其它

### 发生了什么？

我为了访问git平时默认首选dns为223.6.6.6，备用为119.29.29.29。但访问其他网站无相关情况发生。
无梯子等相关使用情况。电脑火狐浏览器，111.0最新版，已关闭adguard插件，edge同样最新版，也是炸了。
同时胡桃显示403错误。

edge：
![图片](https://user-images.githubusercontent.com/63829496/225059046-50add21b-47c3-49db-80d2-e945d216c37f.png)

firefox：
![图片](https://user-images.githubusercontent.com/63829496/225059236-bf679405-eb5d-4e88-925b-f09fa0288a00.png)

f12检查相关错误：
![图片](https://user-images.githubusercontent.com/63829496/225059508-5af6bd8e-c120-4f56-98f0-00ed2d4906e4.png)
![图片](https://user-images.githubusercontent.com/63829496/225059604-0eb32436-2108-4935-be78-554564dd922e.png)

### 你期望发生的行为？

我希望网站正常显示……

**Comment by Mikachu2333** [comment]
我反对Closed，网站故障啊大哥，这机器人不对劲啊……

**Comment by Masterain98** [comment]
fixed
