### ISSUE TITLE
启动游戏

### ISSUE THREAD

**Issue by 3242859343** [DGP-Studio/Snap.Hutao#606]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22000.1696

### Snap Hutao 版本

1.5.4

### 设备 ID

CC5AF610FA5D5F48EB1DE6B7AD445DD7

### 问题分类

游戏启动器

### 发生了什么？

点击启动游戏弹出NullReferenceExemption Obje reference not set to an instance of an object.

**Comment by Lightczx** [comment]
有截图么

**Comment by 3242859343** [comment]
3242859343
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] 启动游戏 (Issue #606)





 
有截图么

**Comment by Lightczx** [comment]
图呢？
