### ISSUE TITLE
[Bug]: 无法显示实时便笺

### ISSUE THREAD

**Issue by zy19970** [DGP-Studio/Snap.Hutao#607]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.382

### Snap Hutao 版本

1.5.4.0

### 设备 ID

246B3A5BEE14E12A6B427FB1EF723262

### 问题分类

安装和环境

### 发生了什么？

![微信截图_20230317154330](https://user-images.githubusercontent.com/22004812/225843615-4a59dde4-a702-4be5-a696-e392a3f6400f.png)
点击验证当前用户与角色信息没问题，但是实时便笺不显示内容

### 你期望发生的行为？

显示实时便笺的内容

**Comment by zy19970** [comment]
1.5.4.0 就是最新的稳定版

**Comment by Lightczx** [comment]
添加角色了么

**Comment by zy19970** [comment]
可以close了，需要添加角色才能刷新，还需要多一步操作
