### ISSUE TITLE
[Bug]: 关于界面上的乱码bug问题

### ISSUE THREAD

**Issue by shunjiankongbai-cn** [DGP-Studio/Snap.Hutao#61]
### Windows 版本

系统版本windows 10 21H2 内部版本：19044.2006

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

红圈处的乱码， 目前一发现这两处了，刚安装就发现了这个问题，前后并没有其他操作。
![image](https://user-images.githubusercontent.com/109362925/192829122-5caaedc8-f3e5-450c-bebe-149430b651eb.png)
![image](https://user-images.githubusercontent.com/109362925/192830172-12d245bc-2878-4135-aecd-1f282577813e.png)

**Comment by Lightczx** [comment]
安装 [Segoe Fluent Icon](https://aka.ms/SegoeFluentIcons) 字体 可以 临时解决

**Comment by shunjiankongbai-cn** [comment]
谢谢，确实有效搞定了
