### ISSUE TITLE
[Bug]: 使用‘多客户端’启动游戏时显示数据异常

### ISSUE THREAD

**Issue by tangtangebusi** [DGP-Studio/Snap.Hutao#610]
### 检查清单

- [x] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1265

### Snap Hutao 版本

1.5.4.0

### 设备 ID

A2B363A84BBD3743A3F4CDFBC85B43C4

### 问题分类

游戏启动器

### 发生了什么？

![image](https://user-images.githubusercontent.com/67052443/225940572-f801e5eb-a0cb-4b2d-a3c9-61652b323336.png)
开启‘多客户端’按钮进入游戏时开门就会显示数据异常    关闭则不会

### 你期望发生的行为？

fix up

**Comment by Seven66677731** [comment]
运行两个官方服时会出现，一个官方服一个渠道服时不会

**Comment by tangtangebusi** [comment]
> 运行两个官方服时会出现，一个官方服一个渠道服时不会

emmm 我一个没开 想要进行多开 打开多客户端按钮启动游戏 就进不去的 甚至还没启动第二个客户端

**Comment by tangtangebusi** [comment]
没用过转服功能  上个版本的胡桃可用 更新后就寄了

**Comment by Lightczx** [comment]
当前版本多开前需要等待12秒以上
