### ISSUE TITLE
一个手滑带来的惨案

### ISSUE THREAD

**Issue by ill-never-retreat** [DGP-Studio/Snap.Hutao#611]
### 背景与动机

今天照例打开胡桃准备米游社签到，然后手滑点到了删除所有用户....

### 想要实现或优化的功能

希望可以加一个二次确认吧，现在都还没重新登上自己的账号（悲）
感谢各位大佬的努力

**Comment by Lightczx** [comment]
@GashByte

**Comment by GashByte** [comment]
👌
