### ISSUE TITLE
[Bug]: 祈愿记录页面为空

### ISSUE THREAD

**Issue by ckfrank** [DGP-Studio/Snap.Hutao#615]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

25314.1010

### Snap Hutao 版本

1.5.4.0

### 设备 ID

D0553B74B6523ABC5F47DAC78D2F36B2

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录页面完全空白，卸载后再安装也是一样的效果，其他页面工作正常，管理员模式启动无法解决，附图
![image](https://user-images.githubusercontent.com/19375542/226165458-240aed5b-c24f-4b7b-b4cf-2de4f21dd693.png)

### 你期望发生的行为？

祈愿记录应该像视频内一样有四个图标

**Comment by Masterain98** [comment]
什么时候开始出现的错误？出现错误前是否从其它源导入过祈愿数据？

**Comment by ckfrank** [comment]
> 

没有，安装完之后就祈愿页面就是空的了

**Comment by Lightczx** [comment]
角色武器怪物资料有东西么

**Comment by ckfrank** [comment]
> , c

有，其他页面正常，联网正常

**Comment by ckfrank** [comment]
删除hutao文件夹重新安装后解决；由于我的documents被迁移到了非C盘所以%userprofile%/Documents/Hutao没有找到该文件夹
