### ISSUE TITLE
[Bug]: 导入成就窗口错误的程序语言

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#617]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

19045.2728

### Snap Hutao 版本

1.5.4.0

### 设备 ID

B79BE49B93492821FAD389E82374C6D9

### 问题分类

成就管理

### 发生了什么？

![image](https://user-images.githubusercontent.com/10614984/226220176-c98cf582-07c3-45a8-9bb8-c822c2c6b67b.png)

## 语言环境
1. 系统语言英语
2. 胡桃设置为中文

## 复现方法
- 使用 YaeAchievement 导入数据，但在导入确认窗口选择取消
- 再次使用 YaeAchievement 导入数据，此时导入确认窗口会变成英语

**Comment by Lightczx** [comment]
检查 下 Userdata.db 中 settings 表的 Culture 的值

**Comment by Masterain98** [comment]
> 检查 下 Userdata.db 中 settings 表的 Culture 的值

![image](https://user-images.githubusercontent.com/10614984/226249679-8b3ddefb-0535-4ed2-9e8d-afb5c1aa7190.png)

**Comment by Lightczx** [comment]
首次导入前胡桃开着么

**Comment by Lightczx** [comment]
Probably related: https://github.com/microsoft/microsoft-ui-xaml/issues/6318

**Comment by Masterain98** [comment]
> 首次导入前胡桃开着么

没有，被唤起的

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/releases/tag/2023.4.14.1
这个版本修复了么

**Comment by Masterain98** [comment]
> https://github.com/DGP-Studio/Snap.Hutao/releases/tag/2023.4.14.1 这个版本修复了么

![image](https://user-images.githubusercontent.com/10614984/232031479-cd4d8215-513f-4d0c-95e1-1ed8156131bf.png)
fixed
