### ISSUE TITLE
[Bug]: 使用启动器启动游戏会报出 ArgumentOutOfRange 的错误

### ISSUE THREAD

**Issue by MYXXTS** [DGP-Studio/Snap.Hutao#622]
### 检查清单

- [X] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)，并认为我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我**通过搜索功能**确认没有其他人已经提出了相同或类似的问题
- [X] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22H2  19045.2728

### Snap Hutao 版本

1.5.4.0

### 设备 ID

7B9BC6DE804D3D69E38C67F47CD25A38

### 问题分类

游戏启动器

### 发生了什么？

使用游戏启动器启动游戏会报出 ArgumentOutOfRange（或者 IndexOutOfRange） 的错误
![Snipaste_2023-03-22_16-31-56](https://user-images.githubusercontent.com/51087760/226847334-63d0016a-d88b-494a-977b-6e436148b43e.png)

**Comment by MYXXTS** [comment]
![image](https://user-images.githubusercontent.com/51087760/226849425-a94c0a7f-0474-439f-b38a-bd1ade929222.png)

**Comment by Lightczx** [comment]
选择一下显示器
