### ISSUE TITLE
[Bug]: 主页活动公告无法显示，报错[GetAnnouncementsAsync]中的[AnnouncementsWrapper]请求异常

### ISSUE THREAD

**Issue by FlyingPolaris** [DGP-Studio/Snap.Hutao#627]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1413

### Snap Hutao 版本

1.5.4.0

### 设备 ID

4B3941FF6CA842CE6EA6F9EA57EE29AD

### 问题分类

用户界面

### 发生了什么？

一打开Snap.Hutao,进入首页时，立刻报错：
[GetAnnouncementsAsync]中的[AnnouncementsWrapper]请求异常，
不显示活动公告和游戏公告

**Comment by Lightczx** [comment]
多重启试试

**Comment by FlyingPolaris** [comment]
已经好了，似乎是偶发问题
