### ISSUE TITLE
[Feat]: 转服功能添加让玩家自己下载pkg

### ISSUE THREAD

**Issue by idhaname** [DGP-Studio/Snap.Hutao#628]
### 背景与动机

我之前在用国服转国际服的时候，经常会因为网络原因导致下载的文件损坏以致转换失败
我了解到开发组曾经为Genshin Lancher Plus开发了[pkg转服包](https://cloud.06dn.com/s/VqYEhY)，但现在GLP疑似停止维护
请问能否为胡桃加入相关功能，可以让用户在网络环境不佳的时候选择本地换服包

### 想要实现或优化的功能

可以在设置或高级启动器内加入一个手动选择功能，让用户选择是使用本地pkg换服包还是从米哈游的服务器在线下载

**Comment by Masterain98** [comment]
pkg是一个过时的方案
