### ISSUE TITLE
关于1.5.4.0工具箱中 用多账号启动游戏显示 未开启长路径功能[Bug] 

### ISSUE THREAD

**Issue by EvenDa** [DGP-Studio/Snap.Hutao#629]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [X] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [X] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [X] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

版本 win11 21H2

### Snap Hutao 版本

1.5.4.0

### 设备 ID

C39A3AEC181C5AF309E0440479513BA6

### 问题分类

游戏启动器

### 发生了什么？

在启动切换账号时提示未开启长路径功能 异常：RuntimeEnvironmentException，也确实按照工具箱中文档所给到的下载 EnableLongPaths.zip 后解压所给到的方案 也未解决此问题，另外参考了此Issues [https://github.com/https://github.com/DGP-Studio/Snap.Hutao/issues/543] 我powershell安装位置为：C:\Windows\System32\WindowsPowerShell\v1.0

### 你期望发生的行为？

希望开发者大大可以帮助一下我 特别是我这种拥有多账号切换的玩家~

**Comment by EvenDa** [comment]
![QQ截图20230325141351](https://user-images.githubusercontent.com/126536833/227700312-36742bda-01a1-454a-8cb5-e22dda43e1a5.png)

**Comment by Lightczx** [comment]
21H2不受支持

**Comment by EvenDa** [comment]
可是我另外一台电脑 是win10 却可以正常切换账号   这是win11这个版本特定的问题么

**Comment by Lightczx** [comment]
给一下5位版本号

**Comment by EvenDa** [comment]
版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎1/‎13
操作系统版本	22000.556

**Comment by EvenDa** [comment]
能不能修复下 实在是不想折腾重新安装系统了 哪怕我付费都可以

**Comment by Masterain98** [comment]
Windows 10 也是21H2？

**Comment by EvenDa** [comment]
win10那台电脑一切正常  但是win11这台机器一直是提示未开启长路径
