### ISSUE TITLE
[Bug]: 错误提示不够明确

### ISSUE THREAD

**Issue by char-46** [DGP-Studio/Snap.Hutao#630]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1413

### Snap Hutao 版本

1.5.4.0

### 问题分类

实时便笺

### 发生了什么？

![PasteEx_20230326_103245](https://user-images.githubusercontent.com/53117560/227752155-7e633858-6736-43ce-8cde-028cd284fd5b.png)
该提示不够明确，不能确定是哪一个账号丢失登录信息。

### 你期望发生的行为？

提示内容包含uid或米游社用户名。

**Comment by Lightczx** [comment]
只会是你当前选中的账号
