### ISSUE TITLE
养成计算

### ISSUE THREAD

**Issue by alberthuang666** [DGP-Studio/Snap.Hutao#631]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1413

### Snap Hutao 版本

1.5.4.0

### 问题分类

养成计算器

### 发生了什么？

在选择角色，天赋等级后点确认跳出来请先登录，但是我已经登陆过了，实时便签也是有的，并且在回去看养成计划并没有增加内容

### 你期望发生的行为？

在我点确认之后能在我的养成计划里出现我选择的新增内容

**Comment by Lightczx** [comment]
刷新CK
