### ISSUE TITLE
错误：请求的名称有效，但是找不到请求的类型的数据

### ISSUE THREAD

**Issue by loker-coper** [DGP-Studio/Snap.Hutao#636]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2728

### Snap Hutao 版本

1.5.4.0

### 设备 ID

EE335D86C75016D812FFC2C5B110DFDC

### 问题分类

其它

### 发生了什么？

启动游戏、主页、设置正常，其他功能均空白，打开时弹出以下警告:
HttpRequestException
元数据校验文件下载失败
请求的名称有效，但是找不到请求的类型的数据。（hutao-
metada.snapgenshin.com:80)

### 你期望发生的行为？

所有功能正常打开

**Comment by Masterain98** [comment]
使用了网络代理？
