### ISSUE TITLE
[Bug]: 文件系统错误(12029).

### ISSUE THREAD

**Issue by NULL053** [DGP-Studio/Snap.Hutao#640]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1413

### Snap Hutao 版本

1.5.4

### 问题分类

安装和环境

### 发生了什么？

通过发行页面下载并安装了1.5.4版本,双击启动后没有出现主界面,任务管理器也没有出现相关进程,几分钟后explorer.exe提示文件系统错误(12029).

![QQ图片20230401023906](https://user-images.githubusercontent.com/104975624/229203057-ed81c156-3cc3-4cbc-a816-b85426b87643.png)

**Comment by Lightczx** [comment]
ERROR_WINHTTP_INVALID_SERVER_RESPONSE

12152

无法分析服务器响应。
