### ISSUE TITLE
[Feat]: 养成计算允许指定添加到的养成计划

### ISSUE THREAD

**Issue by yuluoyun** [DGP-Studio/Snap.Hutao#641]
### 背景与动机

使用养成计划时 默认全选角色、武器、天赋，当仅有一种需求时：需要手动一个个调，非常麻烦
所以 希望能出一个区分功能。 

### 想要实现或优化的功能

在新建养成计划时，添加养成方式弹窗。
弹窗内容为：角色等级养成，武器养成，角色天赋养成，毕业养成。
其中：角色等级养成仅显示角色等级突破所需资源，武器养成仅显示武器所需资源，角色天赋养成仅显示天赋所需资源，毕业养成全选。
如有可能，建议增加角色推荐天赋等级，默认非10，10，10全满天赋推荐。

**Comment by Lightczx** [comment]
已与1.7.4实现
