### ISSUE TITLE
[Bug]: 切换游戏版本后游戏配置文件丢失

### ISSUE THREAD

**Issue by ZTJun** [DGP-Studio/Snap.Hutao#642]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22624.1537

### Snap Hutao 版本

1.5.4.0

### 设备 ID

AE91E1E5B888F84898165A48158DE08F

### 问题分类

游戏启动器

### 发生了什么？

![image](https://user-images.githubusercontent.com/46193857/229333813-8511cacb-c901-4117-a4e2-997a2d38358f.png)
如图，Hutao无法启动游戏

**Comment by ZTJun** [comment]
在游戏本体文件夹中config.ini文件丢失
![image](https://user-images.githubusercontent.com/46193857/229333897-bd709db6-6fe3-4925-89fd-5ef7f7c38ed4.png)

**Comment by Lightczx** [comment]
你文件夹里怎么会有 `blob_storage` `steam` 和一个中文乱码文件

**Comment by ZTJun** [comment]
> 你文件夹里怎么会有 `blob_storage` `steam` 和一个中文乱码文件

steam文件夹是之前添加到steam非游戏库留下的文件夹
blob_storage来源未知,但文件夹为空

**Comment by Lightczx** [comment]
你的目标是转换到国服么

**Comment by ZTJun** [comment]
> 你的目标是转换到国服么

是，但是失败了

**Comment by Lightczx** [comment]
1. 删除不应该出现的文件/文件夹
2. 将 `GenshinImpact_Data` 重命名为 `Yuanshen_Data`
3. 将 `GenshinImpact.exe` 删除
4. 创建 `config.ini` 内容输入
```
[General]
channel=1
cps=mihoyo
game_version=3.5.0
sub_channel=1
```
5.使用国服启动器定位到此文件夹
6.使用启动器的一键修复功能

**Comment by ZTJun** [comment]
已解决
![image](https://user-images.githubusercontent.com/46193857/229345681-c175c752-386d-4c57-a9f9-8e1a4cf71ca4.png)

**Comment by ZTJun** [comment]
已解决
![image](https://user-images.githubusercontent.com/46193857/229345809-fc523e2f-0b13-4781-86a8-935fc66c33a7.png)
