### ISSUE TITLE
[Bug]: 添加hoyolab账号时报错

### ISSUE THREAD

**Issue by cjl0222** [DGP-Studio/Snap.Hutao#644]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1413

### Snap Hutao 版本

1.6.0.0

### 问题分类

用户面板

### 发生了什么？

添加hoyolab账号，使用“网页登录”时，输入账号密码点击登录，然后点击右上角“我已登录”后，提示“此cookie无效”，出现如图所示的报错。

![QQ截图20230403103023](https://user-images.githubusercontent.com/32232720/229398486-b5836258-befc-40b9-acd7-b2efef70fdb6.png)

**Comment by Masterain98** [comment]
本地网络问题
