### ISSUE TITLE
[Bug]: 祈愿记录时间排序出现问题

### ISSUE THREAD

**Issue by RiZhiZhaoYi** [DGP-Studio/Snap.Hutao#645]
### 检查清单

- [x] 我已完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [x] 我知道文档站的导航栏中有**搜索功能**，也搜索过相关关键词
- [x] 我使用的操作系统是[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [x] 我**通过搜索功能**确认其他人没有提出过相同或类似的问题
- [x] 我明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而不是随手确认的选项

### Windows 版本

22621.1485

### Snap Hutao 版本

1.6.0.0

### 设备 ID

9E3A7979539F8AD572E00490382AD5DE

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录中2021年以及之前的记录中，有一些时间排序出现错误。
比如 2020.10.02的迪卢克与2020.12.23的阿贝多位置错了，导致迪卢克显示抽卡次数为102次
这是我的祈愿记录：[祈愿记录](https://github.com/RiZhiZhaoYi/WishRecord/blob/main/100569108.json)

**Comment by Lightczx** [comment]
从哪导入的

**Comment by RiZhiZhaoYi** [comment]
> 从哪导入的 @RiZhiZhaoYi

最初是从[genshin-wish-export](https://github.com/biuuu/genshin-wish-export)记录自己的抽卡记录，
之后认识到SnapGenshin后，将记录导入到了SnapGenshin，当时还没有任何问题，从某一次更新后，SnapGenshin的抽卡记录就变成这样了，SnapGenshin项目结束后，Hutao暂未正式上线那段时间，将数据导出，换用寻空，寻空直接读取不了那部分记录，最近发现Hutao有正式版了，回来看看，问题仍然还在，就来开Issue了

**Comment by Lightczx** [comment]
发原始的数据，不要再从胡桃导出

**Comment by RiZhiZhaoYi** [comment]
> 发原始的数据，不要再从胡桃导出

这是我还能找到的最早的导出数据，更早的数据已经找不到了
[2022-09-28 12:12:16](https://github.com/RiZhiZhaoYi/WishRecord/blob/main/100569108SnapGenshin.json)

**Comment by Lightczx** [comment]
存在重复Id，没办法正常添加的
