### ISSUE TITLE
[Bug]: 2023年04月03日【解除帧数】功能莫名其妙消失

### ISSUE THREAD

**Issue by RuJingNiao** [DGP-Studio/Snap.Hutao#646]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

226221.1413

### Snap Hutao 版本

1.6.0

### 设备 ID

282430D7D613EE65C3A9B9DA3BD695F7

### 问题分类

游戏启动器

### 发生了什么？

急急急！！！就在今天2023年04月03日发现胡桃的【解锁帧数】功能不能用了！！在界面直接没有了？？这是怎么回事啊，习惯了高帧后，没有解锁帧数，60帧感觉就像PPT一样！根本玩不下去😫😫😫😭😭😭
![1](https://user-images.githubusercontent.com/129717866/229418031-40ea12b5-a3e0-4da3-87b8-b4f9b2a97257.png)

### 你期望发生的行为？

希望能解决一下，球球啦😫😭

**Comment by lnnh** [comment]
因为自动升级成了1.6.0版本。有一项优化是 帧数解锁和游戏多开功能现在需要用户先在设置中手动解锁高级功能。

**Comment by Masterain98** [comment]
[更新日志](https://hut.ao/zh/statements/update-log.html#_1-6-0)
