### ISSUE TITLE
[Bug]: hoyolab签到界面显示“请旋转手机”，无法进行签到。

### ISSUE THREAD

**Issue by cjl0222** [DGP-Studio/Snap.Hutao#647]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1413

### Snap Hutao 版本

1.6.0.0

### 设备 ID

AB18C954200A149DBD4985AFD7EA96AD

### 问题分类

签到

### 发生了什么？

hoyolab签到界面显示“请旋转手机”，无法进行签到。（如图所示）

![QQ截图20230403170031](https://user-images.githubusercontent.com/32232720/229462864-0e3f9ba5-ae1c-4992-aaea-bb9ed89a310d.png)

**Comment by Lightczx** [comment]
暂时可以直接去网页签到

**Comment by Xhichn** [comment]
hoyolab 签到网页上判断屏幕方向的 js 代码片段

```javascript
o = t.IS_SCREEN_SUPPORT_ORIENTATION = window.screen.orientation && Object.prototype.hasOwnProperty.call(window, "onorientationchange");
function i() {
  if (o)
      return window.screen.orientation.type.includes("landscape") ? r.ORIENTATION.LANDSCAPE : r.ORIENTATION.PORTRAIT;
  var e = window.screen.width
      , t = window.screen.height
      , n = Math.min(e, t)
      , i = window.document.documentElement.clientWidth;
  return i - r.ORIENTATION_REGION <= n && n <= i + r.ORIENTATION_REGION ? r.ORIENTATION.PORTRAIT : r.ORIENTATION.LANDSCAPE
}
```

似乎因为 `window.screen.orientation.type.includes("landscape")` 判断为 true，就有横屏的提示

**Comment by Lightczx** [comment]
下版本修复
