### ISSUE TITLE
[Bug]: 程序无法自行重启

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#648]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2788

### Snap Hutao 版本

1.6.0.0

### 设备 ID

0F608BDDE01D799F11CD6C4DEC4465E7

### 问题分类

安装和环境

### 发生了什么？

在使用会让程序重新启动的功能（比如切换语言和重置图片资源）时，主程序在主动退出后不会自行启动。此外，固定在任务栏中的图标也会被删除，在下一次手动启动程序时能看到类似于更新/安装的进度条，切换语言和重置图片资源的操作仍然会完成。

**Comment by Lightczx** [comment]
1.6.2 是否修复了此问题 @Masterain98

**Comment by Masterain98** [comment]
没有；但 `2023.4.18.1` 是没问题的

**Comment by Masterain98** [comment]
> 固定在任务栏中的图标也会被删除

@Lightczx  这个问题仍然存在

**Comment by Lightczx** [comment]
应该是Win10特定问题，Win11无法复现

**Comment by Lightczx** [comment]
应该是 Restart API 的问题

**Comment by Lightczx** [comment]
1.6.3是否存在@Masterain98

**Comment by Masterain98** [comment]
> 1.6.3是否存在@Masterain98

fixed
