### ISSUE TITLE
[Bug]: 關於獲取hoyolab國際版Stoken問題&諮詢細節

### ISSUE THREAD

**Issue by sheaahhoi1** [DGP-Studio/Snap.Hutao#650]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1485

### Snap Hutao 版本

1.6.0.0

### 设备 ID

A34DD2F85F3677B44E03C785024292CD

### 问题分类

其它

### 发生了什么？

關於獲取hoyolab國際版Stoken問題&諮詢細節
1.在登錄後從網頁中獲取訊息會發生錯誤
[https://account.hoyolab.com/](https://account.hoyolab.com/)推測你們想從這裡獲取Stoken,但自動化失敗
![error](https://user-images.githubusercontent.com/10239384/229820740-2db304cd-ad4f-45ab-94aa-d8530fcd74c1.png)

2.Stoken 獲取教學[https://hut.ao/en/features/mhy-account-switch.html](https://hut.ao/en/features/mhy-account-switch.html)推薦的第三方工具,應該是不兼容hoyolab 的APK吧,檔名描述[miyoushe-361-lspatched.apk](https://github.com/HolographicHat/GetToken/releases/download/2.47.1/miyoushe-361-lspatched.apk)

我查看過這篇提問提及cookie_token之類訊息,因為這篇而更新1.6.0.0吧?
[https://github.com/DGP-Studio/Snap.Hutao/pull/608](https://github.com/DGP-Studio/Snap.Hutao/pull/608)

網上找到以下3~4種方法,獲取Stoken 以連結某種機械人?(大概吧)
方法A(以MHY為本):
[https://www.bilibili.com/read/cv16187561](https://www.bilibili.com/read/cv16187561
)
獲取cookie,好像無關,(按F12主控台輸入,限定電腦端)
```
var cookie = document.cookie;

var Str_Num = cookie.indexOf('_MHYUUID=');

cookie = '添加 ' + cookie.substring(Str_Num);

var ask = confirm('Cookie:' + cookie + '\n\n按确认，然后粘贴发送给机器人');

if (ask == true) {

  copy(cookie);

  msg = cookie

} else {

  msg = 'Cancel'

} 
```

方法B.
獲取米游社 Stoken指令(按F12主控台輸入,限定電腦端)
```var cookie = document.cookie;

var ask = confirm('Cookie:' + cookie + '\n\nDo you want to copy the cookie to the clipboard?');

if (ask == true) {

  copy("添加stoken " + cookie);

  msg = cookie

} else {

  msg = 'Cancel'

} 
```

先看獲取MHY Stoken結果
![+MHY-code1](https://user-images.githubusercontent.com/10239384/229842358-a9e86687-748f-433d-95c4-a68977982fcb.png)

那這句用在HYL Stoken結果
![+hyl-code1](https://user-images.githubusercontent.com/10239384/229842703-2b65f1cd-cfc1-417a-a69f-25d215e8e7d8.png)

格式上沒有標明Stoken 但存在itoken, cookie_token 這2項訊息

如果結論這正是你們正在尋找的Stoken,那我過去提交過issues,說用機械人獲取到的方法.,不說這code 指令還有別的辦法獲取,

方法C.
BOT 作者教學
[https://hackmd.io/66fq-6NsT1Kqxqbpkj1xTA](https://hackmd.io/66fq-6NsT1Kqxqbpkj1xTA)
獲取HYL&MHY Stoken指令(按F12主控台輸入,限定電腦端)
```
c=document.cookie; confirm('將Cookie複製到剪貼簿?') && copy(c)
```
這句直接儲存在記憶體,可以直接貼出內容

方法D.
唯一適用所有瀏覽器方法(只要能打網址都可以)獲取HYL&MHY Stoken指令(任何手機/電腦瀏覽器,必要條件能打網址)
在網址上copy指令
```
avascript: document.write(document.cookie)
```
之後補充j 在最前方

所以全句應該是
```
Javascript: document.write(document.cookie)
```
如果是全句複製&貼上會直接生呑`Javascript: `
網站會變為這樣

MHY的結果
![+MHY-code2](https://user-images.githubusercontent.com/10239384/229847768-909c10a8-0fbb-4c35-981a-64967ed2d129.png)

HYL的結果
![+hyl-code2](https://user-images.githubusercontent.com/10239384/229847930-5b81673a-25c1-4c89-be79-b639de929f24.png)

account.hoyolab.com
上取得的訊息和www.hoyolab.com 社區上取得訊息一致

這些訊息如果有幫助請盡快更新,你們的胡桃工具箱,我非常期待使用

### 你期望发生的行为？

這些訊息如果有幫助請盡快更新,你們的胡桃工具箱,我非常期待使用。

**Comment by Xhichn** [comment]
在调试后发现这个问题应该与stoken无关，而是因为在添加用户时查询用户信息失败导致无法添加用户。

**Comment by Lightczx** [comment]
fixed by #652
