### ISSUE TITLE
[Bug]: 突破帧数无法使用

### ISSUE THREAD

**Issue by bsxv** [DGP-Studio/Snap.Hutao#653]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

win11

### Snap Hutao 版本

1.6.0.0

### 设备 ID

313361A4AF583090427597F2603C5ACF

### 问题分类

游戏启动器

### 发生了什么？

从昨天开始，突破帧数限制这个功能直接没了

**Comment by Masterain98** [comment]
RTFM

**Comment by Lightczx** [comment]
#646
