### ISSUE TITLE
[Bug]: 开屏显示位置bug

### ISSUE THREAD

**Issue by lushi78778** [DGP-Studio/Snap.Hutao#655]
### Windows 版本

19044.2728

### Snap Hutao 版本

1.6.0.0

### 设备 ID

BCA3C8A0DF903E81B35F072408F1F197

### 问题分类

用户界面

### 发生了什么？

第一次打开位置不太对，是那种初始位置我鼠标无法到达最上边最大化那一行，就卡着呆着
![image](https://user-images.githubusercontent.com/64238218/230123947-f8bdce25-b2bc-47ed-9989-bf6cc2bf730b.png)
如上图所示
调整任务栏靠左后可以显示
![image](https://user-images.githubusercontent.com/64238218/230124264-2f8a11a1-4fca-481a-bfcf-0c9736214704.png)
看红色部分我圈起来了，出来了可以调整了。不能每次我都调整任务栏吧？

### 你期望发生的行为？

位置正常现实，可以最大化现实按钮出现可点击

**Comment by Lightczx** [comment]
分辨率多少，屏幕又是多大

**Comment by lushi78778** [comment]
![image](https://user-images.githubusercontent.com/64238218/230258570-cfefb464-4378-4f80-b4ea-8a175e711af6.png)
13.3寸

**Comment by lushi78778** [comment]
> Windows 10 Build 21H2 是一个过时的 Windows 版本。
> 
> ## Windows 10 生命周期
> ![image](https://user-images.githubusercontent.com/10614984/220493442-cad6b7e9-3e06-4184-8e42-950ee8587e11.png)
> 
> ## Snap Hutao 最低系统要求
> * Windows 10 Build 19045 (22H2)
>   
>   * 低于该版本可能会导致程序会有不可预知的错误

目前还未结束支持吧~

**Comment by Lightczx** [comment]
缩放比是多少

**Comment by lushi78778** [comment]
> 缩放比是多少

175%

**Comment by Lightczx** [comment]
不要在最大化时关闭窗口
重启应该就正常了

**Comment by lushi78778** [comment]
确实，感谢
