### ISSUE TITLE
[Feat]: 建议增加胡桃和原神官方的TOS链接

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#658]
### 背景与动机

![image](https://user-images.githubusercontent.com/10614984/230584076-f28eca41-b364-4ca4-8125-cc57d390c5b0.png)

### 想要实现或优化的功能

![image](https://user-images.githubusercontent.com/10614984/230584181-7f06b885-92d9-48e2-9444-9423d43754d2.png)

如果可行的话，允许用户直接点击跳转访问

**Comment by Lightczx** [comment]
实现此功能与国际化冲突
