### ISSUE TITLE
[Bug]: 卸载之后定时弹出使用Hutao打开此链接的弹窗

### ISSUE THREAD

**Issue by FangLin2001** [DGP-Studio/Snap.Hutao#660]
### 检查清单

- [x] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.2728

### Snap Hutao 版本

1.6.0.0

### 设备 ID

1F5AF75A50C42CF8FBA7C749FF915BE6

### 问题分类

其它

### 发生了什么？

在Microsoft Store下载安装Snap Hutao之后，正常使用一段时间。将其卸载，之后就会定时弹出Win10提醒，使用Hutao打开此链接

### 你期望发生的行为？

卸载之后不应该残留定时任务

**Comment by Lightczx** [comment]
https://hut.ao/zh/advanced/uninstall.html
