### ISSUE TITLE
[建议]: 想要一个半透明的没有菜单栏的浏览器插件，用来打开大地图工具~

### ISSUE THREAD

**Issue by zejianglm001** [DGP-Studio/Snap.Hutao#661]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

WIN11H2

### Snap Hutao 版本

1.6.0.0

### 问题分类

其它

### 发生了什么？

想要一个半透明的没有菜单栏的浏览器插件，用来打开大地图工具
另外还想要天赋本武器本分别每天能打的本可以统计出来=-= 有点记不住...每次上游戏看有些麻烦

### 你期望发生的行为？

想要一个半透明的没有菜单栏的浏览器插件，用来打开大地图工具
另外还想要天赋本武器本分别每天能打的本可以统计出来=-= 有点记不住...每次上游戏看有些麻烦

**Comment by Lightczx** [comment]
建议就发建议，不要发反馈
