### ISSUE TITLE
养成计算器登录问题？

### ISSUE THREAD

**Issue by sumengmsm** [DGP-Studio/Snap.Hutao#662]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

Windows 11 家庭中文版 版本	22H2-22621.1485

### Snap Hutao 版本

1.6.0.0

### 设备 ID

7452318C96FDF286DEB3903CC9D49E4B

### 问题分类

养成计算器

### 发生了什么？

此问题在 #631 中被另一位提及，你的回复是刷新ck，但是我已经尝试此操作，不起作用。

详情：添加角色养成时会弹出：`状态：-100 | 信息：请先登录`，如下图所示：
![2023-04-08_15-35](https://user-images.githubusercontent.com/62458709/230710133-f546968b-7e9b-4458-b263-57ad02d7dbeb.png)

且需要登录的地方都已登录：
![2023-04-08_154721](https://user-images.githubusercontent.com/62458709/230710191-2be3f70e-5f00-42f9-bf17-6ab147327f3e.png)
![2023-04-08_154855](https://user-images.githubusercontent.com/62458709/230710238-dcd380f2-c3f3-4d42-aba3-832b73c83e90.png)

### 你期望发生的行为？

期望得到回复和解决。

**Comment by Lightczx** [comment]
删了重新添加

**Comment by sumengmsm** [comment]
`删除游戏内网页缓存`和`删除所有用户`选项都不管用，卸载后重新安装才好。

**Comment by Lightczx** [comment]
![image](https://user-images.githubusercontent.com/36357191/230712484-17210e80-eb5f-4e87-acfd-8805c89d0805.png)

**Comment by sumengmsm** [comment]
好吧，下次出问题的时候试试。
