### ISSUE TITLE
[Bug]: 实时便笺刷新失败

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#664]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1.1413

### Snap Hutao 版本

1.6.0.0

### 设备 ID

FA47BE878C143D2FE18785B660EF114A

### 问题分类

实时便笺

### 发生了什么？

实时便笺页面显示：

![image](https://user-images.githubusercontent.com/72692909/230719945-c62a422c-fc8d-425c-af3c-0108eebf3916.png)

刷新数据错误，验证当前用户与角色可正常显示

![image](https://user-images.githubusercontent.com/72692909/230719980-a0ea5eb3-4670-47dc-b9c2-6a307df9d247.png)

### 你期望发生的行为？

实时便笺页面数据正常获取

**Comment by Lightczx** [comment]
#649
