### ISSUE TITLE
[Bug]:不能保留自定义窗口大小

### ISSUE THREAD

**Issue by YYl04** [DGP-Studio/Snap.Hutao#666]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22624.1546

### Snap Hutao 版本

1.6.0.0

### 设备 ID

1BAFF5939662C9E65E9223F768278B5A

### 问题分类

用户界面

### 发生了什么？

重新启动胡桃会让窗口大小恢复至默认值。(在1080p显示下窗口默认尺寸为1185x733)

### 你期望发生的行为？

用户手动调整窗口大小后，重启能保留设置

**Comment by Lightczx** [comment]
不要在最大化的情况下关闭胡桃

**Comment by YYl04** [comment]
https://user-images.githubusercontent.com/95568556/232090551-8aef84b9-6a73-4a5c-a08d-24a0f0872604.mp4
