### ISSUE TITLE
[Feat]: 祈愿记录出货抽数的颜色更改

### ISSUE THREAD

**Issue by YYl04** [DGP-Studio/Snap.Hutao#667]
祈愿记录出货抽数的颜色也可以考虑更改一下吗
![image](https://user-images.githubusercontent.com/95568556/230782841-48918fdb-501c-4fcb-89c1-ae821feb63f6.png)
虽然不知道你们的机制，但建议统一使用高饱和度颜色，例如目前已有的天空之翼和风鹰剑的

_Originally posted by @YYl04 in https://github.com/DGP-Studio/Snap.Hutao/issues/23#issuecomment-1501158372_

**Comment by Lightczx** [comment]
这个是目前使用的物品颜色生成代码
如果有更好的方案欢迎讨论

https://github.com/DGP-Studio/Snap.Hutao/blob/e5c5c1c95cebd9c505f6dac18e1f433e415db154/src/Snap.Hutao/Snap.Hutao/Service/GachaLog/Factory/GachaStatisticsExtension.cs#L76-L80

**Comment by TremblingMoeNew** [comment]
> 这个是目前使用的物品颜色生成代码 如果有更好的方案欢迎讨论
> 
> https://github.com/DGP-Studio/Snap.Hutao/blob/e5c5c1c95cebd9c505f6dac18e1f433e415db154/src/Snap.Hutao/Snap.Hutao/Service/GachaLog/Factory/GachaStatisticsExtension.cs#L76-L80

用HSL或者HSV色彩空间 然后卡一下色域？(

**Comment by Lightczx** [comment]
> 然后卡一下色域

?
