### ISSUE TITLE
[Bug]: UIGF的JSON格式数据导入错误

### ISSUE THREAD

**Issue by HexaMPA** [DGP-Studio/Snap.Hutao#67]
### Windows 版本

19042.1706

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

祈愿记录使用原神祈愿记录导出工具导出的UIGF格式的JSON文件，无法导入进胡桃软件使用。导入结果如图。但该JSON文件可以运用于其他软件的导入过程。
![image](https://user-images.githubusercontent.com/66836840/193403645-4f132e1f-735d-44b7-b0ba-43b676d0ed39.png)

### 你期望发生的行为？

希望可以成功导入相关祈愿分析记录。

**Comment by Lightczx** [comment]
请附上Json文件
