### ISSUE TITLE
[Bug]: 启动游戏的指定显示器功能偶尔会出错

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#672]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1485

### Snap Hutao 版本

1.6.2.0

### 设备 ID

E0238BE05E5071D48B78227BC23443A8

### 问题分类

游戏启动器

### 发生了什么？

指定显示器运行所设定的显示器ID偶尔会重置为默认的1号显示器（我设定的是2号显示器），但是没有进行过显示器方面的设置，就是正常的重启电脑，也没有修改“启动游戏”页面的选项
似乎上个版本是没有这个问题的，不清楚是软件问题还是系统问题

**Comment by Lightczx** [comment]
显示器2是通过什么连接的

**Comment by anpoz** [comment]
显示器1和2都是接DP的

**Comment by Lightczx** [comment]
等待下版本修复
