### ISSUE TITLE
[Bug]: 角色信息服务[Enka API]不可用

### ISSUE THREAD

**Issue by qingchenddd** [DGP-Studio/Snap.Hutao#674]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [X] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [X] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [X] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2728

### Snap Hutao 版本

1.6.2.0

### 设备 ID

34EC11C897658CD8634901324D1A6856

### 问题分类

角色信息面板

### 发生了什么？

第一次使用工具箱，三个同步功能中两个从米游社同步的可用，enka不可用

### 你期望发生的行为？

enka可用

**Comment by Masterain98** [comment]
Enka API 升级中，暂时不可用

@Lightczx 建议在客户端中为 Enka API HTTP 424 Error 做专门的错误提示，提醒用户系统升级，稍后重试。

**Comment by qingchenddd** [comment]
升级windows系统吗

**Comment by Lightczx** [comment]
> Enka API 升级中，暂时不可用
> 
> @Lightczx 建议在客户端中为 Enka API HTTP 424 Error 做专门的错误提示，提醒用户系统升级，稍后重试。

下版本添加
