### ISSUE TITLE
[Bug]: 使用被限制的高級功能後,付費方式被更變

### ISSUE THREAD

**Issue by sheaahhoi1** [DGP-Studio/Snap.Hutao#675]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1485

### Snap Hutao 版本

1.6.2

### 设备 ID

A34DD2F85F3677B44E03C785024292CD

### 问题分类

其它

### 发生了什么？

![螢幕擷取畫面 2023-04-12 214908](https://user-images.githubusercontent.com/10239384/231479861-37c49e71-e0ad-405e-8000-d1db4956ee60.png)
使用工具箱限制項目後的高級功能(例:解鎖FPS)後,付費方式被更變為palpay & 信用卡

本身國際版因為版本流通性有著不同付費方式,也能在不同遊戲平台中下載,例PC端:Epic Games ,google play

因為我在google play store 上下載因此,我的遊戲在付費預設為google play,和國際版安卓客戶端相同,
在過去舊版工具箱都發生過這情況,向來工具箱在某定義中更變了付費方式

### 你期望发生的行为？

祈望不要嘗試更改付費方式,但要更變的話,請提供還原/切換付費方式

**Comment by Lightczx** [comment]
你确定只使用了解锁帧率功能么@sheaahhoi1

**Comment by sheaahhoi1** [comment]
@Lightczx 確定沒動別的
![1](https://user-images.githubusercontent.com/10239384/231491683-2a549969-1f61-4376-8f74-400f76467f76.png)
![2](https://user-images.githubusercontent.com/10239384/231491700-76fc7f06-1206-4b25-9e8f-c0ceda871d70.png)

**Comment by sheaahhoi1** [comment]
`[launcher]
game_install_path=E:/um_Program_Files_64/Genshin Impact/Genshin Impact game
cps=pcgoogle
channel=1
sub_channel=6
game_dynamic_bg_name=10f25a33cb5bc889e42ae39869cf2d18_2488789946687632484.png
game_dynamic_bg_md5=5e3ddec407e48ec6c86ee7775b1398e8
game_start_name=GenshinImpact.exe
zh-tw_proto_version=2.0
download_flag=2
download_transaction_no=168130311771338803
is_first_exit=false
exit_type=1
task_start_posted=true
task_finish_posted=true
game_screenshot_clicked=true
game_screenshot_tip_visible=false
`

**Comment by Lightczx** [comment]
这个是launcher的config
我需要genshin impact 的 config

**Comment by sheaahhoi1** [comment]
[config.ini.txt](https://github.com/DGP-Studio/Snap.Hutao/files/11212904/config.ini.txt)

**Comment by yaozijin** [comment]
> [config.ini.txt](https://github.com/DGP-Studio/Snap.Hutao/files/11212904/config.ini.txt)

CPS有问题，试试：
cps=pcadbdpz

**Comment by sheaahhoi1** [comment]
我以把操作錄製一次,
不過從片中測試好像與遊戲本體無關,到底那裡被修改?
[https://youtu.be/ab-qCJFNx_4](https://youtu.be/ab-qCJFNx_4)

※:需要更高清影像,大約1小時候後再看吧

**Comment by Lightczx** [comment]
@sheaahhoi1 请确认以下信息：
1. 是否在使用胡桃的同时，使用了其他的第三方工具（原神/HoYoLAB 均包括）？
2. 是否在使用胡桃的同时，修改了 Hoyoverse 账号的相关设置？
3. 有其他可能会影响的行为？

**Comment by sheaahhoi1** [comment]
@Lightczx 

我這次找到被修改位置了
..\Genshin Impact\Genshin Impact game\config.ini
[General]
channel=1
cps=pcgoogle
game_version=3.6.0
sub_channel=0

多謝在前文提醒config.ini我保留了初始數據,原文中的sub_channel值被更變了
sub_channel=0(在國際服上0=官方直付,2/4也是5無效,其他數字沒測試,但6的值就是google付款端口,Epic 版付款端口未知,有空再找,現在去玩一玩遊戲)
所以修改/復原
sub_channel=6
6此值就是google付款端口
,希望不要更變此項或者在選擇國際服時該添加更變付款端口

**Comment by sheaahhoi1** [comment]
@Lightczx 
Epic 版國際服付款接口sub_channel=3
原文件內容:
[General]
channel=1
cps=pcseaepic
game_version=3.6.0
sub_channel=3
plugin_sdk_version=2.14.2

**Comment by Lightczx** [comment]
Channel与Subchannel已经完全明白了，等待更新
