### ISSUE TITLE
[Bug]: 安装时提示【应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。】

### ISSUE THREAD

**Issue by LetEmKnow** [DGP-Studio/Snap.Hutao#676]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

windows 10 专业工作站版 22H2 19045.2546

### Snap Hutao 版本

1.6.2

### 问题分类

安装和环境

### 发生了什么？

按照说明卸载了1.4.1.0，但是安装时提示【应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。】

**Comment by Lightczx** [comment]
去商店装

**Comment by hoixding** [comment]
> 去商店装

我的电脑无法使用商店，商店中所有应用都无法安装，已经确实和授权服务器无关。

**Comment by Lightczx** [comment]
所有应用都装不了大概就是授权服务器的问题。
