### ISSUE TITLE
关于抽卡记录导出

### ISSUE THREAD

**Issue by Hoshina-chan** [DGP-Studio/Snap.Hutao#678]
### 背景与动机

非小酋网站只支持excel导入，我把uigf手动excel后非小酋仍然无法识别，而且excel也能更直观展示抽卡记录中的4星啥的

### 想要实现或优化的功能

抽卡记录导出除了uigf，可以支持别的吗，比如excel

**Comment by Lightczx** [comment]
让他们支持UIGF就可以了

**Comment by Masterain98** [comment]
## 为什么不支持 Excel 导出
Excel也许对人而言是直观的，但它储存的是高级且结构复杂的数据，这对于软件而言是“不直观”的（事实上，Json 数据结构本身是简洁的，是人类可读的）。相比 Json 格式而言，Excel文件：
1. 体积更大
2. 程序必须消耗更多的性能
3. 用户能轻而易举修改数据，降低数据可信性

## 你的问题本身是错误的
即使胡桃支持导出 Excel，那XXX能理解其中的数据吗？你当然可以导入一份`XX班级期中考试成绩`列表给一个程序，那也很有可能Excel工作簿文件，那原神程序能理解里面的数据吗？

## 如何导入数据到XXX呢？
非常简单。让XXX支持 UIGF 数据格式（UIGF 是一种数据格式标准，而不是文件类型）

## 最后

其实，你所说的“直观”只是另一种数据可视化。在支持 UIGF 数据格式的原神第三方程序中，就有专门提供数据分析和可视化的程序（比如 [https://genshin.voderl.cn/](https://genshin.voderl.cn/)），也有视觉效果做得更华丽的工具类程序。与其去搞一个封闭的软件，不如在更广大的生态中寻找你需要的东西。
