### ISSUE TITLE
[Feat]: 游戏内悬浮窗显示养成UI

### ISSUE THREAD

**Issue by Xing688** [DGP-Studio/Snap.Hutao#679]
### 背景与动机

觉得养成计划使用起来有点麻烦

### 想要实现或优化的功能

添加一个快捷键，能实现在游戏内呼出一个小标签，在游戏内快捷查看养成计划，并能划掉已经收集完的材料

**Comment by sinkkin** [comment]
能不能在养成计划页面可以点击材料查看材料的获取途径，因为刚开始玩十几天，好多材料都不认识，看图标并不知道打哪个boss才能出

**Comment by Lightczx** [comment]
Tracked by #1394
