### ISSUE TITLE
[Bug]: 界面无法正常显示

### ISSUE THREAD

**Issue by zmf0510** [DGP-Studio/Snap.Hutao#68]
### Windows 版本

19042.928

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

界面无法正常显示

1. 主界面显示为白屏
2. 点击首页链接（看不见）后能正常显示网页
3. 可见设置图标，点击后右侧界面只显示下拉图标，没有文字内容

下为实际图片
![image](https://user-images.githubusercontent.com/63844300/193411957-257467d1-018c-413b-958a-6759ac97cb8f.png)
![image](https://user-images.githubusercontent.com/63844300/193411956-0d74d032-c4ae-4113-a777-2c9ca992955e.png)
![image](https://user-images.githubusercontent.com/63844300/193411975-ba549e62-7707-4729-86be-bb7254cb7ef7.png)

**Comment by Lightczx** [comment]
什么显卡

**Comment by zmf0510** [comment]
> 什么显卡
AMD Radeon(TM) 530 和 AMD Radeon(TM) R2 Graphics（笔记本电脑）
驱动是从AMD官网下的

**Comment by zmf0510** [comment]
关闭独显后已经可以正常显示，应该是驱动问题
