### ISSUE TITLE
用户数据出现损坏

### ISSUE THREAD

**Issue by tao111x** [DGP-Studio/Snap.Hutao#682]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

Windows 10 专业版 22h2

### Snap Hutao 版本

1.6.2.0

### 设备 ID

21C193BF-F06D-40E2-B954-76D6498911C4

### 问题分类

祈愿记录

### 发生了什么？

我在导入了抽卡小助手的祈愿记录后就这样了，无论是清除用户数据还是卸载重装还是这样
![Snap Hutao 2023_4_16 9_31_56](https://user-images.githubusercontent.com/130878381/232261398-06460f36-58c3-4a14-ac89-8da2e39b88c9.png)

### 你期望发生的行为？

可以正常导入

**Comment by Masterain98** [comment]
发一下导入的 Json 文件

**Comment by tao111x** [comment]
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] 用户数据出现损坏 (Issue #682)





 
发一下导入的 Json 文件

**Comment by Kytrex5625** [comment]
same

**Comment by Kytrex5625** [comment]
[UIGF_848733850_202304161742.txt](https://github.com/DGP-Studio/Snap.Hutao/files/11242140/UIGF_848733850_202304161742.txt)

change it back to json

**Comment by tao111x** [comment]
什么意思







***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] 用户数据出现损坏 (Issue #682)





 
UIGF_848733850_202304161742.txt
 
change it back to json

**Comment by tao111x** [comment]
现在是用户数据有问题，告诉我这怎么解决





***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] 用户数据出现损坏 (Issue #682)





 
UIGF_848733850_202304161742.txt
 
change it back to json

**Comment by tao111x** [comment]
导入第一次不刷新，第二次有提示用户文件损坏

**Comment by Lightczx** [comment]
@tao111x 你的文件呢

**Comment by Lightczx** [comment]
> [UIGF_848733850_202304161742.txt](https://github.com/DGP-Studio/Snap.Hutao/files/11242140/UIGF_848733850_202304161742.txt)
> 
> change it back to json

We DO NOT support lang `zh-tw` file, since it's just not a uigf 2.2 file.

**Comment by tao111x** [comment]
没有用




***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DGP-Studio/Snap.Hutao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 晚上10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DGP-Studio/Snap.Hutao] 用户数据出现损坏 (Issue #682)





 
Closed #682 as completed.

**Comment by Lightczx** [comment]
@tao111x 我问的是你的文件
什么东西有用没用

**Comment by tao111x** [comment]
导入后，关闭应用在重新打开没有用&nbsp;



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 晚上10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DGP-Studio/Snap.Hutao] 用户数据出现损坏 (Issue #682)






@tao111x我问的是你的文件
什么东西有用没用

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.
