### ISSUE TITLE
[功能请求]: 希望能提供webdav同步

### ISSUE THREAD

**Issue by windowBR** [DGP-Studio/Snap.Hutao#685]
### 背景与动机

胡桃云最近有点问题，然后刚好自己有webdav盘可以用来同步

### 想要实现或优化的功能

希望可以增加一个同步盘的选项让用户能接入自己的webdav网盘进行数据云同步而不是只能通过胡桃云

**Comment by Lightczx** [comment]
暂无计划，欢迎PR
