### ISSUE TITLE
[Bug]: 无法安装/安装后无法启动

### ISSUE THREAD

**Issue by Weixiang** [DGP-Studio/Snap.Hutao#686]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1555

### Snap Hutao 版本

1.6.2

### 问题分类

安装和环境

### 发生了什么？

无法通过 Windows Store 安装，点按安装按钮后，按钮变灰一段时间，而后变蓝，无反应。

无法通过 winget 安装，输入命令后，显示用户协议，y同意后卡住，无反应。

可以通过 MSIX 应用包 安装，但是安装完成后无法启动。

---

此前安装卸载过一次，已经再次按照文档中的方法进行完全卸载。

已经尝试使用过多个网络代理，排除网络问题。

Windows Store 可以正常下载其他应用。

**Comment by Masterain98** [comment]
[Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64.msix.zip](https://github.com/DGP-Studio/Snap.Hutao/files/11241974/Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64.zip)

试一下安装这个环境包能否解决问题

**Comment by Lightczx** [comment]
检查 eventvwr中的 .NET Runtime Error

**Comment by Weixiang** [comment]
> [Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64.msix.zip](https://github.com/DGP-Studio/Snap.Hutao/files/11241974/Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64.zip)
> 
> 试一下安装这个环境包能否解决问题

安装后并没有解决，尝试过重启。


> 检查 eventvwr中的 .NET Runtime Error

已经检查，eventvwr 中没有发现 .NET Runtime Error 相关的日志，请问还有哪里可以查看日志？

**Comment by Masterain98** [comment]
检查一下 Windows Defender 或其他反病毒程序是否有对胡桃进行操作的记录

**Comment by Lightczx** [comment]
ERROR_WINHTTP_INVALID_SERVER_RESPONSE

12152

无法分析服务器响应。

**Comment by 1803233552** [comment]
我今天也是卡在安装15%就不动了，[Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64.msix.zip](https://github.com/DGP-Studio/Snap.Hutao/files/11241974/Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64.zip)

用上面的安装包安装后就好了
