### ISSUE TITLE
[Bug]: HoYoLab 无 FaceBook SSO 登录

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#687]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

Windows 10 22H2

### Snap Hutao 版本

1.6.2

### 问题分类

用户面板

## 胡桃
![image](https://user-images.githubusercontent.com/10614984/232346467-5e4bbbd7-ac25-4413-bb83-36cd546347ca.png)

## 浏览器
![image](https://user-images.githubusercontent.com/10614984/232346636-b2322fac-816a-4f17-8fc8-302b566d0b20.png)

**Comment by Masterain98** [comment]
Try to use https://account.hoyoverse.com/ instead of  https://account.hoyolab.com/

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao/commit/97c7671595d7ad471623ae3dba9667b2c2dcf631
