### ISSUE TITLE
[Bug]: 启动游戏页面有时候打开很慢

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#689]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1631

### Snap Hutao 版本

1.6.2.0

### 设备 ID

E0238BE05E5071D48B78227BC23443A8

### 问题分类

游戏启动器

### 发生了什么？

启动游戏页面有时候打开很慢，慢的时候要3-10秒，印象中几个版本前不会这样的。是不是资源下载页面影响了游戏启动页面的加载？

### 你期望发生的行为？

希望可以做到加载完游戏启动设置和账号信息就立刻显示页面，资源下载页面可以做到懒加载，这个tab其实使用率很低，远远比不上启动页面

**Comment by Lightczx** [comment]
与 资源下载页面无关，Windows App SDK 1.2 的 BUG
会在下版本修复
