### ISSUE TITLE
[Bug]: 开启帧率解锁后，使用游戏内浏览器浏览公告时显示不正常

### ISSUE THREAD

**Issue by retaker** [DGP-Studio/Snap.Hutao#692]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1555

### Snap Hutao 版本

1.6.2.0

### 问题分类

游戏启动器

### 发生了什么？

使用快捷方式关联powershell脚本，以管理员权限执行snap.hutao
解锁帧率开关打开后并设置帧率上限为165fps
之后在游戏内打开公告，弹出的游戏内自带浏览器无法正常显示，需要使用alt+tab切换到其他应用之后才能正常显示，切回来再操作的话又不可以正常显示和操作了。

**Comment by Lightczx** [comment]
是否同时开启了独占全屏

**Comment by retaker** [comment]
> 是否同时开启了独占全屏

![image](https://user-images.githubusercontent.com/3334662/233637532-ab4f277d-83c6-47ff-b7f8-cb103e8e9ca3.png)
没有同时开启独占全屏

**Comment by retaker** [comment]
游戏更新后问题不复现。
