### ISSUE TITLE
[Bug]: 第一次导入祈愿记录程序崩溃

### ISSUE THREAD

**Issue by Xarth-Mai** [DGP-Studio/Snap.Hutao#694]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22624.1537

### Snap Hutao 版本

1.6.20

### 设备 ID

8E9B110A3DD5F9BEF35BA3A26C31E3B8

### 问题分类

祈愿记录

### 发生了什么？

这是第一次导入祈愿记录,程序中无存档. 我使用了stoken方式刷新 经历了漫长的等待后程序崩溃 重启再次使用stoken刷新获得相同的结果,第三次我使用了缓存刷新 但我并没有打开游戏进程 然后刷新成功了.这里的缓存应该来自胡桃工具箱先前的刷新
录屏:https://lzzz.fun/hutao1.mp4 https://lzzz.fun/hutao2.mp4
因为GitHub文件大小限制我把视频分成了两部分

### 你期望发生的行为？

刷新不应该崩溃 可能是数据量太大了?后续的刷新就不会崩溃了

**Comment by Lightczx** [comment]
#702
