### ISSUE TITLE
[Bug]: 祈愿记录导入 

### ISSUE THREAD

**Issue by chuchu-z** [DGP-Studio/Snap.Hutao#695]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

win10 19044.2728

### Snap Hutao 版本

1.6.2.0

### 设备 ID

D2C91128B3B3EBC5717671465F08D918

### 问题分类

安装和环境

### 发生了什么？

1. 我曾经在胡桃工具箱通过抽卡链接获取过我的祈愿记录, 但只有最近6个月的记录
2. 我打算从提瓦特助手小程序导出我的抽卡记录到胡桃工具箱, 因为那有我的完整祈愿记录
3. 我通过提瓦特小助手导出了UIGF格式的抽卡记录，后缀名为.json的文件, UIGF版本为 [(UIGF) v2.2标准](https://uigf.org/zh/standards/UIGF.html)
4. 我打开胡桃工具箱选择文件了我的json文件并导入, 在此之前 我没有更改过json文件且确定文件格式是正确的json文件
5. 导入文件后弹出提示如下
![image](https://user-images.githubusercontent.com/33407400/233818068-d845f523-4f43-4e44-995f-47f2180dafe9.png)
6. 我尝试通过文档查找方法和检查item_id是否错误, 通过查找文档, 我认为item_id为空是没有问题的, 至少导出的文件应该没有问题, 或许是我使用的版本问题或API接口兼容问题 但我无法获取更多信息进行判断和处理
7. json文件格式如下

```json
{
    "info": {
        "uid": "189045168",
        "lang": "zh-cn",
        "export_time": "2023-04-23 10:53:28",
        "export_timestamp": 1682218408000,
        "export_app": "提瓦特小助手",
        "export_app_version": "v3.0.0",
        "uigf_version": "v2.2"
    },
    "list": [{
        "uid": "189045168",
        "gacha_type": "301",
        "item_id": "",
        "count": "1",
        "time": "2023-04-19 07:12:09",
        "name": "铁影阔剑",
        "lang": "zh-cn",
        "item_type": "武器",
        "rank_type": "3",
        "id": "1681859160000109668",
        "uigf_gacha_type": "301"
    }, {
        "uid": "189045168",
        "gacha_type": "301",
        "item_id": "",
        "count": "1",
        "time": "2023-04-19 07:12:04",
        "name": "魔导绪论",
        "lang": "zh-cn",
        "item_type": "武器",
        "rank_type": "3",
        "id": "1681859160000108868",
        "uigf_gacha_type": "301"
    }, {
        "uid": "189045168",
        "gacha_type": "301",
        "item_id": "",
        "count": "1",
        "time": "2023-04-19 07:11:00",
        "name": "讨龙英杰谭",
        "lang": "zh-cn",
        "item_type": "武器",
        "rank_type": "3",
        "id": "1681859160000098868",
        "uigf_gacha_type": "301"
    }, {
        "uid": "189045168",
        "gacha_type": "301",
        "item_id": "",
        "count": "1",
        "time": "2023-04-19 07:11:00",
        "name": "沐浴龙血的剑",
        "lang": "zh-cn",
        "item_type": "武器",
        "rank_type": "3",
        "id": "1681859160000098768",
        "uigf_gacha_type": "301"
    }, {
        "uid": "189045168",
        "gacha_type": "301",
        "item_id": "",
        "count": "1",
        "time": "2023-04-19 07:11:00",
        "name": "黑缨枪",
        "lang": "zh-cn",
        "item_type": "武器",
        "rank_type": "3",
        "id": "1681859160000098668",
        "uigf_gacha_type": "301"
    }, {
        "uid": "189045168",
        "gacha_type": "301",
        "item_id": "",
        "count": "1",
        "time": "2023-04-19 07:11:00",
        "name": "莫娜",
        "lang": "zh-cn",
        "item_type": "角色",
        "rank_type": "5",
        "id": "1681859160000098568",
        "uigf_gacha_type": "301"
    }, {
        "uid": "189045168",
        "gacha_type": "301",
        "item_id": "",
        "count": "1",
        "time": "2023-04-19 07:11:00",
        "name": "翡玉法球",
        "lang": "zh-cn",
        "item_type": "武器",
        "rank_type": "3",
        "id": "1681859160000098468",
        "uigf_gacha_type": "301"
    }
    //此处省略...
    ]
}
```

### 你期望发生的行为？

期望可以正常的进行祈愿记录导入

**Comment by chuchu-z** [comment]
> win10 19044.2728 是一个过时的 Windows 版本。
> 
> ## Windows 10 生命周期
> ![image](https://user-images.githubusercontent.com/10614984/220493442-cad6b7e9-3e06-4184-8e42-950ee8587e11.png)
> 
> ## Snap Hutao 最低系统要求
> * Windows 10 Build 19045 (22H2)
>   
>   * 低于该版本可能会导致程序会有不可预知的错误

感谢回复 所以我目前除了更换设备没有其他办法解决这个问题了吗

**Comment by Masterain98** [comment]
将 Json 数据文件发上来；将数据目录中的 UserData.db 发送到 support@dgp-studio.cn

**Comment by chuchu-z** [comment]
> 

json数据及userdata.db已发送到support@dgp-studio.cn

**Comment by Masterain98** [comment]
![L)%UC}GOLCVRT2PP3{}G@ 2](https://user-images.githubusercontent.com/10614984/234353624-77cf7d96-5bb0-4816-9807-725a4cb67a5d.png)

填充数据有错误，已经联系小助手作者去修复了，等待数据源程序修复后即可重新导入。
从你的用户数据中将抽卡记录删除了，附件已通过邮件回复。
