### ISSUE TITLE
[Feat]: 预设分辨率列表

### ISSUE THREAD

**Issue by liuzipeng** [DGP-Studio/Snap.Hutao#697]
### 背景与动机

需要频繁切换窗口化和全屏，树手动输入分辨率有点麻烦。

### 想要实现或优化的功能

希望能添加一个预设分辨率列表然，并且可以添加自定义分辨率选项。感谢

**Comment by Lightczx** [comment]
你希望哪些分辨率出现在预设中呢

**Comment by Lightczx** [comment]
closing as no response
