### ISSUE TITLE
[Bug]: 祈愿记录存档无法默认选中

### ISSUE THREAD

**Issue by adam484546** [DGP-Studio/Snap.Hutao#698]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.2846

### Snap Hutao 版本

1.6.2.0

### 设备 ID

A06163192DAE94A9D66E8E0A3F220573

### 问题分类

祈愿记录

### 发生了什么？

![image](https://user-images.githubusercontent.com/86906809/235033510-e48bfb2f-c3b4-49f2-90d5-aba905f31d20.png)

**Comment by Masterain98** [comment]
从什么地方导入的数据？

**Comment by SavitarC** [comment]
同样的问题

Windows 版本
22621.1635

Snap Hutao 版本
1.6.2.0

设备 ID
32F40CCA856D9FC84382B4F747C0D3E3

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 32F40CCA856D9FC84382B4F747C0D3E3

**Comment by Lightczx** [comment]
上一次打开祈愿记录时做了什么？@adam484546 @SavitarC

**Comment by SavitarC** [comment]
> 上一次打开祈愿记录时做了什么？@adam484546 @SavitarC

没记错的话应该是stoken刷新

**Comment by Lightczx** [comment]
fixed in 5 mins
