### ISSUE TITLE
[Bug]: 祈愿记录白屏

### ISSUE THREAD

**Issue by ChrisKimZHT** [DGP-Studio/Snap.Hutao#699]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.2846

### Snap Hutao 版本

1.6.2.0

### 设备 ID

AF0D95B7A0BD9EB0B98D425202F4BEAF

### 问题分类

祈愿记录

### 发生了什么？

祈愿记录页面突然变成空白了，截图：

![image](https://user-images.githubusercontent.com/49368462/235054368-2bf40bd5-6023-4c51-aa67-f22b7e59bacc.png)

系统为 Windows 10 LTSC 2021 (21H2)，版本 `19044.2846`，低于官方文档中最低支持版本 `19045`. 但程序之前一直正常使用，今天出现这个问题。

### 你期望发生的行为？

正常显示祈愿记录

**Comment by Lightczx** [comment]
fixed in 5 mins
