### ISSUE TITLE
[Feat]: 支持 UIGF v2.3 & v2.2 with non-CHS locale

### ISSUE THREAD

**Issue by LekaOuO** [DGP-Studio/Snap.Hutao#702]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1555

### Snap Hutao 版本

1.6.2.0

### 设备 ID

0F99D77BF56C7E7635AB0B2DCA8B34BF

### 问题分类

祈愿记录

### 发生了什么？

我試圖從Genshin-Wish-Export(v0.8.16)導出祈願紀錄並導入到Snap Hutao
導入失敗並顯示"用戶數據已損壞:不支持的ltem id:0"
之後只要點選祈願紀錄就會顯示錯誤並且沒有任何畫面
把Snap Hutao移除從新安裝依然如此
![image](https://user-images.githubusercontent.com/132276251/235980760-01eaa036-e4b0-432f-beb5-e1fc72230617.png)

**Comment by Lightczx** [comment]
是繁体中文的记录吧

**Comment by Masterain98** [comment]
将数据目录下的 `Userdata.db`  发送到 support@dgp-studio.cn ，帮你把这个祈愿存档删除掉。下一版本应该能能应对多语言的情况了。

**Comment by LekaOuO** [comment]
是繁體中文的沒錯
Userdata.db已發送
謝謝

**Comment by Masterain98** [comment]
原因是当前版本的胡桃客户端暂时不支持非简体中文以外的祈愿**数据**，数据确实存在，但客户端无法从角色/武器元数据中读取到非简体中文的信息。这个问题会通过在接下来版本中使用 [UIGF v2.3 数据格式](https://uigf.org/zh/standards/UIGF.html) 来解决，将允许用户使用其它语言导入数据。

如果目前版本需要使用祈愿记录，你可以
1. 如果是从第三方程序导入 UIGF 数据，则需要保证祈愿数据使用的是简体中文
2. 如果是从原神客户端导出数据，可以暂时将游戏语言设置为简体中文，这样导出的数据也会是简中的

**Comment by LekaOuO** [comment]
好的，了解了，謝謝你
