### ISSUE TITLE
[Feat]: 程序本身高刷新率支持

### ISSUE THREAD

**Issue by Mugenhasen** [DGP-Studio/Snap.Hutao#703]
### 背景与动机

DGP.Genshin有着适配屏幕刷新率的功能（比如我笔记本是165Hz的），然后转用胡桃的时候就发现程序本身貌似是固定60帧运行的，不习惯，能否请开发者在有空闲的情况下支持下高刷屏，优化下程序的刷新率

### 想要实现或优化的功能

优化下《胡桃》程序本身的刷新率/帧率，最好从固定60fps变为自适应屏幕刷新率，谢谢

**Comment by Lightczx** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/6031

**Comment by Mugenhasen** [comment]
> [微软/微软-ui-xaml#6031](https://github.com/microsoft/microsoft-ui-xaml/issues/6031)

了解了，就是说是微软WinUI的问题。
安装了2023.4更新后发现《胡桃》似乎是流畅了点，但有点说不上来的卡顿，只能说希望微软后期继续优化。
