### ISSUE TITLE
[Bug]: 导入Json格式祈愿记录时会闪退

### ISSUE THREAD

**Issue by Laplace321** [DGP-Studio/Snap.Hutao#71]
### Windows 版本

22000.978

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

[104176877.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9690664/104176877.zip)
上传Json格式的祈愿记录时在导入后会闪退 该Json文件是通过 Snap Genshin导出的

**Comment by Lightczx** [comment]
请上传一下json
