### ISSUE TITLE
[Bug]: 已注册胡桃账号再次登录提示账号未注册

### ISSUE THREAD

**Issue by AsouLin** [DGP-Studio/Snap.Hutao#710]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2006

### Snap Hutao 版本

1.6.2.0

### 设备 ID

66ACA5937BB148FE58CEA7407B4392C5

### 问题分类

用户界面

### 发生了什么？

在重装系统后，重新下载hutao后重新登录胡桃账号登录失败，重置密码后得知账号不存在。以下是注册过胡桃账号的历史验证码记录和尝试重置密码所遇到的情况：
![image](https://user-images.githubusercontent.com/80609053/236661534-9c112292-9e37-417b-be46-f3b8ea4ba7b5.png)

**Comment by Lightczx** [comment]
![S$%WNNW5D~T0ONF$4`WY1PX](https://user-images.githubusercontent.com/36357191/236662060-51d7e83c-8a54-46c1-8c6f-5e77f44232c5.png)

**Comment by Lightczx** [comment]
不是很清楚你是怎么注册成功的

**Comment by AsouLin** [comment]
私密马赛（好像当时是太久没收到验证码，找希尔私发的，我重新注册一个罢
