### ISSUE TITLE
[Feat]: 成就列表全选

### ISSUE THREAD

**Issue by Ricky158** [DGP-Studio/Snap.Hutao#711]
### 背景与动机

![屏幕截图 2023-05-09 155958](https://user-images.githubusercontent.com/52778594/237033898-c44c6e0b-6bcb-49b3-ae8d-8fce9610a585.png)
在成就管理的过程当中，我发现成就需要单独进行勾选。对于一些很容易完成的成就分类（如地图探索类），缺少能够快捷勾选全部的功能。

### 想要实现或优化的功能

希望能够增加“全选/全不选一类成就的功能。
比如，通过右击图中的框起的列表item，可以弹出选项卡，一键全部勾选/全部取消选中的一类成就。减少用户的操作次数。

**Comment by Masterain98** [comment]
https://github.com/HolographicHat/YaeAchievement

**Comment by Lightczx** [comment]
由于可以使用工具精确获取成就状态，所以批量管理成就不是很有必要
