### ISSUE TITLE
[Bug]: 未开启长路径功能

### ISSUE THREAD

**Issue by 1235789gzy1** [DGP-Studio/Snap.Hutao#713]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

25357.1

### Snap Hutao 版本

1.6.3.0

### 设备 ID

CC5AF610FA5D5F48EB1DE6B7AD445DD7

### 问题分类

游戏启动器

### 发生了什么？

仅在选中账户启动游戏时发生
已尝试文档中的配置脚本
![error](https://github.com/DGP-Studio/Snap.Hutao/assets/52618207/a08aba8c-25f5-489e-96e4-ee987874cb0a)

### 你期望发生的行为？

正常启动游戏

**Comment by 1235789gzy1** [comment]
组策略如图
![1](https://github.com/DGP-Studio/Snap.Hutao/assets/52618207/9325d351-3e4e-49f3-a02c-05383d6f986b)

**Comment by Lightczx** [comment]
#716
