### ISSUE TITLE
[Bug]: 未开启长路径，无法设置注册表键值

### ISSUE THREAD

**Issue by YouYouLip** [DGP-Studio/Snap.Hutao#716]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

Windows 11 版本22H2 (OS内部版本22621.1702)

### Snap Hutao 版本

1.6.3.0

### 设备 ID

3E95CF7E08D3EA1E8340FF177338F865

### 问题分类

游戏启动器

### 发生了什么？

在这个图片里命名角色名后启动会出现未开启长路径
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/af3d0f48-e25d-497a-b9b1-24a37426bf94)

我已经通过文档中的reg注册表添加了进我的电脑，我也用组策略编辑器开启了win32解除长度限制，但是还是会有错误
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/e71d7296-74d4-47b2-afc6-d292ac3807cc)

不过我注意到了一点，当我选中我设置的用户名就会触发这个报错，但是当我直接启动而不去选择用户名便能启动，也可以通过启动游戏中的设置的右上角启动游戏来启动原神，我一开始还以为是中文用户名的原因，但是我改成英文后同样有这个问题
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/44c99689-7434-42f6-9fa6-deaa5fe5898f)

### 你期望发生的行为？

希望可以通过账号用户名正常启动游戏

**Comment by YouYouLip** [comment]
在不选择用户名以及账号时进行启动可以正常启动
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/5e60efa7-9d42-4eef-9401-1d98f7aadae5)
但是当我选择了账号名后便会触发未开启长路径这个bug
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/5a454db3-2426-4ad3-8f52-0c2ca2c7ab5c)

**Comment by YouYouLip** [comment]
> 可以试试装个python，装的时候勾选解除路径长度限制

嗯....看来早就解除路径长度限制了，因为安装python之前我看了注册表的值是1
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/9f290f90-40cb-4582-bd1c-ab46068fced2)
在安装python的时候未发现解除路径长度限制选项，自己又把数值改成了0，通过python安装修改后还是无效，是管理员启动的

**Comment by Lightczx** [comment]
理论上应该已经在1.7.3版本修复，如果仍然存在问题可以重新开新的issue
