### ISSUE TITLE
[Bug]: 状态1034 验证失败

### ISSUE THREAD

**Issue by SmallYii** [DGP-Studio/Snap.Hutao#717]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2965

### Snap Hutao 版本

1.6.3.0

### 问题分类

角色信息面板

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/112681916/f00111ad-b1a4-4de9-84e3-c285c23a5fc2)
用的网页登录，老是验证失败，只能启动游戏  其他数据都看不了

**Comment by Masterain98** [comment]
刷新 cookie

**Comment by SmallYii** [comment]
> 刷新 cookie

刷新也是这样 不然我就不会发Issues了

**Comment by Masterain98** [comment]
> 刷新也是这样 不然我就不会发Issues了

但是你没有提到。
实时便笺 -> 验证当前用户与角色

**Comment by SmallYii** [comment]
> > 刷新也是这样 不然我就不会发Issues了
> 
> 但是你没有提到。 实时便笺 -> 验证当前用户与角色

原来如此  但是我之前也照你说的做了，要我选择一个用户，我明明已经选择了的，不过现在问题解决了

**Comment by ShikiSuen** [comment]
@Masterain98 请问你们最近几天是否有收到更多的关于 1034 验证失败的问题的提报？

我是隔壁的原神披萨助手（iOS / macOS 平台限定 App）这边的日语翻译担当，只是想留言确认一下情况。我们怀疑米游社可能针对咱们这一类副厂助手应用做了持续的限制行动。

刚刚我们这边群内有人用 Snap Hutao 也发生了类似的情形（见下图），但不知其后续状况如何。

![7244c93b5731a8b3aead094ea4e7381d](https://github.com/DGP-Studio/Snap.Hutao/assets/3164826/f4ffebb0-f885-4f75-a3b8-491d565dbb82)
