### ISSUE TITLE
祈愿记录无法刷新

### ISSUE THREAD

**Issue by lunaticcjx** [DGP-Studio/Snap.Hutao#72]
### Windows 版本

19041.928

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

在获取祈愿记录页面，点击刷新->从缓存刷新后，弹出窗口要求我选择一个.exe文件，不知道怎么进行选择，同时祈愿记录没有刷新。
点击手动输入URL后，程序发生崩溃，无法输入URL

**Comment by Lightczx** [comment]
需要选择 YuanShen.exe
