### ISSUE TITLE
[Bug]: 无法登录外服mihoyo账号

### ISSUE THREAD

**Issue by floro677** [DGP-Studio/Snap.Hutao#721]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [X] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [X] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [X] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1555

### Snap Hutao 版本

1.6.3.0

### 设备 ID

B15CB9CA3AF450DDAF42E6DC8C24F738

### 问题分类

用户界面

### 发生了什么？

1，主页中的启动游戏选项无法选择账号.
2，所有工具栏中的功能都显示无法获取角色信息。enka同步，米友社我的角色同步和养成计算同步点了都没反应
3，登陆选项中，无法查看角色（已登录了一个外服账号。
4，hoyolab网页登陆时显示''此cookie无效，操作失败''，错误码2001。这是在我已经成功登录后并点击 我已登陆 后发生的。

注: 我已经登陆了一个账号，当时并没出现任何问题。我已经细读帮助文档并确定上面的所有方法都不适用

**Comment by Masterain98** [comment]
RTFM
