### ISSUE TITLE
[Bug]: 角色橱窗 UI 问题

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#722]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2965

### Snap Hutao 版本

1.6.3.0

### 设备 ID

0F608BDDE01D799F11CD6C4DEC4465E7

### 问题分类

玩家查询

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/27062811-4367-4c61-afd4-87e3c9062962)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/87226db7-a907-41b8-a927-9877b8e0af44)

1. 神里绫华的被动技能被显示出来，导致 UI 错误；一样的原因也造成详细数据中`双爆评分`和`普攻等级`距离过近
2. 13级技能显示为10级

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/commit/46f58730dc48cf510f4337e54be2c8dddd72ebea
