### ISSUE TITLE
[Feat]: snap hutao的启动游戏栏目

### ISSUE THREAD

**Issue by 1stfrom** [DGP-Studio/Snap.Hutao#73]
### 你想要实现或优化的功能？

请实现或优化snap genshin中的解锁帧率上限选项，对于少部分硬件质量过硬的玩家，这个选项曾经成为了日常游玩原神必备的启动项，请在snap hutao中还原或优化该项功能
优化：例如实现避免”以管理员模式重启“的要求

**Comment by Genicur** [comment]
你可以在程序属性的兼容性选项卡里勾选 以管理员模式启动
