### ISSUE TITLE
[Bug]: 角色总览有特殊技能的角色大招天赋等级无法显示

### ISSUE THREAD

**Issue by AsouLin** [DGP-Studio/Snap.Hutao#730]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1702

### Snap Hutao 版本

1.6.3.0

### 问题分类

角色信息面板

### 发生了什么？

像神里凌华等有多一个特殊天赋的角色，在角色总览数据处天赋等级会导致大招天赋位置被特殊天赋占用，无法显示大招等级
<img width="232" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/80609053/f5e3158a-e331-4b42-9800-9debbb3b514c">

### 你期望发生的行为？

不应该让有特殊天赋角色的大招位置被占用

**Comment by Lightczx** [comment]
已知问题，下版本修复
