### ISSUE TITLE
[Feat]: 一些关于首页仪表盘的建议

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#732]
### 背景与动机

因为实时便签老是要求验证码验证，所以个人是实时便签关了，但是首页仪表盘会出现一个空白卡片
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/2825342/c1373070-c975-48d8-bde3-89e371c5f6cd)

### 想要实现或优化的功能

如果仪表盘没有数据，可以隐藏或者添加相应的提示，看起来没那么突兀。另外保底计数的左右切换按钮不应该使用与背景相似的颜色，不好辨别边界。

**Comment by cworld1** [comment]
+1

**Comment by Lightczx** [comment]
1.7 优化
