### ISSUE TITLE
[Blocking] 帧率解锁失效

### ISSUE THREAD

**Issue by SteveHe24** [DGP-Studio/Snap.Hutao#733]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22623.1020

### Snap Hutao 版本

1.6.3.0

### 问题分类

安装和环境

### 发生了什么？

在更新3.7版本之后帧率解锁失效.

### 你期望发生的行为？

或许能自动更新帧率解锁??

**Comment by Lightczx** [comment]
Tracking https://github.com/34736384/genshin-fps-unlock/issues/137

**Comment by ZTJun** [comment]
已在 https://github.com/34736384/genshin-fps-unlock/releases/tag/v2.1.0 修复，请求更新

**Comment by Lightczx** [comment]
在转换到 C# 时遇到阻塞性问题
https://github.com/DGP-Studio/Snap.Hutao/blob/e44a20f202ad51925331ce54968b85203f66dc56/src/Snap.Hutao/Snap.Hutao/Service/Game/Unlocker/GameFpsUnlocker.cs#L228-L242
暂时无法找到原因

**Comment by twjmy** [comment]
> 在转换到 C# 时遇到阻塞性问题
> 
> https://github.com/DGP-Studio/Snap.Hutao/blob/e44a20f202ad51925331ce54968b85203f66dc56/src/Snap.Hutao/Snap.Hutao/Service/Game/Unlocker/GameFpsUnlocker.cs#L228-L242
> 
> 
> 暂时无法找到原因
> https://github.com/DGP-Studio/Snap.Hutao/issues/733#issuecomment-1562856374 @Lightczx

觀察到最新的推改為使用 `ulong `，
請問有試過這邊 `(uint)sizeof(nuint)` 改為 `(nuint)sizeof(nuint)` 的嗎？
https://github.com/DGP-Studio/Snap.Hutao/blob/e44a20f202ad51925331ce54968b85203f66dc56/src/Snap.Hutao/Snap.Hutao/Service/Game/Unlocker/GameFpsUnlocker.cs#L80

**Comment by Lightczx** [comment]
是 pValue 类型的问题，不能向ReadProcessMemory传入 nuint* 类型的指针（ulong**）

**Comment by twjmy** [comment]
> 是 pValue 类型的问题，不能向ReadProcessMemory传入 nuint* 类型的指针（ulong**）

原來如此，謝謝大佬
