### ISSUE TITLE
[Bug]: 游戏更新3.7.0之后unlockfps失效

### ISSUE THREAD

**Issue by Fantsies** [DGP-Studio/Snap.Hutao#735]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.2295 LTSC

### Snap Hutao 版本

1.6.3.0 UWP

### 问题分类

游戏启动器

### 发生了什么？

开启unlockfps后拉起游戏，游戏内仍为60fps

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/733

**Comment by zh8416** [comment]
看这里提到修复了，不过我启动时仍然是60帧，在微软商店重装也是一样，是什么原因

**Comment by Lightczx** [comment]
> 看这里提到修复了，不过我启动时仍然是60帧，在微软商店重装也是一样，是什么原因

等更新

**Comment by zh8416** [comment]
> > 看这里提到修复了，不过我启动时仍然是60帧，在微软商店重装也是一样，是什么原因
> 
> 等更新

收到，多谢
