### ISSUE TITLE
[Bug]: 解锁 FPS 出现错误讯息

### ISSUE THREAD

**Issue by twjmy** [DGP-Studio/Snap.Hutao#737]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

23451.1000

### Snap Hutao 版本

1.6.3.0

### 设备 ID

62A02AEA05DD75D32CDB0165D7E2895B

### 问题分类

用户界面

### 发生了什么？

1. crowdin 似乎未提供此處的翻譯 https://github.com/DGP-Studio/Snap.Hutao/blob/96b3e6d092b8a540bd4adf2981974e7160a9b921/src/Snap.Hutao/Snap.Hutao/View/Card/LaunchGameCard.xaml#L69 
2. 3.7 版本用官方登入器更新後，解鎖 FPS 出現錯誤訊息
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/32490451/963c7e6c-61a8-4ab8-8f9d-ecf8e663e86d)

### 你期望发生的行为？

1. 提供翻譯管道
2. 正常運行

**Comment by Masterain98** [comment]
FPS 上限解锁问题会在接下来的版本中修复 #733

**Comment by twjmy** [comment]
> FPS 上限解锁问题会在接下来的版本中修复 #733

收到，多谢
