### ISSUE TITLE
[Feat]: 客户端转换

### ISSUE THREAD

**Issue by earthjasonlin** [DGP-Studio/Snap.Hutao#739]
### 背景与动机

由于国内网络原因，有时转国际服可以下载很快，有时非常慢。当发现非常慢时往往已经晚了，而且没有取消操作按钮，只能看着他10kb慢慢跑

### 想要实现或优化的功能

1. 一直走系统代理
2. 把要下载的文件都下载完了再对游戏本体操作

**Comment by Lightczx** [comment]
系统代理本就可以设置，自行查阅 AppContainer Loopback
#811
