### ISSUE TITLE
HttpRequestException 元数据校验文件下载失败 Response status code does not indicate success: 503 (Service Unavailable).

### ISSUE THREAD

**Issue by KOTORIJAH** [DGP-Studio/Snap.Hutao#740]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2965

### Snap Hutao 版本

1.6.3.0

### 设备 ID

B444C54327F5F24C3CDDE01D3D274F61

### 问题分类

安装和环境

### 发生了什么？

![微信截图_20230528002447](https://github.com/DGP-Studio/Snap.Hutao/assets/20436716/255a2b35-cce3-4d5b-bd5f-25a240c178a9)
除了实时便签，其他的打开都是空白，下面显示503错误

### 你期望发生的行为？

正常打开

**Comment by Masterain98** [comment]
fixed
