### ISSUE TITLE
因无法找到fps字段而帧数解锁失败

### ISSUE THREAD

**Issue by ill-never-retreat** [DGP-Studio/Snap.Hutao#741]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [x] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1702

### Snap Hutao 版本

1.6.3.0

### 设备 ID

818AB8A676FA515F74F9AFA963F13C5D

### 问题分类

游戏启动器

### 发生了什么？

启动游戏时显示未找到fps字段，从而无法进行帧数上限的解锁。重新安装后暂时修复但重启后再次出现这一问题

**Comment by Masterain98** [comment]
Duplicate of #733

Please search for existing issues before posting a new one.
