### ISSUE TITLE
[Bug]: 多显示器热插拔支持

### ISSUE THREAD

**Issue by TangTangawa** [DGP-Studio/Snap.Hutao#743]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

25357.1

### Snap Hutao 版本

2023.5.26.2

### 设备 ID

A2B363A84BBD3743A3F4CDFBC85B43C4

### 问题分类

游戏启动器

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67052443/d39c2615-7a25-43db-b6da-d3cfa5aa35c6)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67052443/4921813c-7c84-4192-a6a5-a9c33237ae00)
以管理员身份启动 胡桃Alpha 报错 如图所示

### 你期望发生的行为？

fix up

**Comment by tangtangebusi** [comment]
多显示器导致的此问题  选的显示器2启动  保存设置   断开显示器2   如图1
重启胡桃   启动游戏  多显示器里默认没有选择显示器   导致的问题   如图2
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67052443/e65d2e5a-e31c-4d9d-833b-e7f6b5afab73)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67052443/04529ebc-5cbc-4ed6-b17c-987b9a23ec96)
