### ISSUE TITLE
[Feat]: 实时便签关闭自动刷新或关闭窗口最小化到托盘

### ISSUE THREAD

**Issue by zhangyina1** [DGP-Studio/Snap.Hutao#744]
### 背景与动机

![123](https://github.com/DGP-Studio/Snap.Hutao/assets/38777924/31118c69-bad8-4a95-842b-e5578e36257f)
本人有四个原神号，一打开hutao就会弹出来8个刷新失败，4红4黄
之前每次看都必定刷新失败
计划任务里删掉了自动刷新感觉好了点
但是neet一天要开软件七八次，其中好几次还是会报错
如果彻底切手动挡对我来说会减少很多的鼠标点击次数和痛苦。。
或者最小化到托盘避免打开软件时的那次刷新也可以解决我的情况

### 想要实现或优化的功能

添加一个关闭自动刷新的按钮，来关闭实时便签启动软件时的自动刷新和间隔时长自动刷新
或者关闭窗口时加个  最小化到托盘/退出程序  +记住我的选项

**Comment by ding-js** [comment]
同意，希望可以增加开关。现在风控卡的太严了，重置密码也没什么用

**Comment by Lightczx** [comment]
关闭刷新功能已于 1.7.0 版本实装
