### ISSUE TITLE
[Bug]: 无法添加武器养成计划

### ISSUE THREAD

**Issue by DengXy** [DGP-Studio/Snap.Hutao#745]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1778

### Snap Hutao 版本

1.6.4.0

### 设备 ID

FBCD895560859BE212487514B62AB154

### 问题分类

养成计算器

### 发生了什么？

武器资料中选择任一武器添加养成计划时，软件出现大约5s的卡顿，卡顿恢复后养成计划未能成功添加，重复点击添加计划时偶尔触发闪退。
若添加角色养成计划则未出现上述情况。
已尝试以下方法：非管理员模式、管理员模式、新建计划时绑定当前角色、新建计划时未绑定当前角色、登录胡桃账号、重置及重装工具箱

**Comment by MiXiu233** [comment]
**Windows 版本**

19045.2846

**Snap Hutao 版本**

1.6.4.0

**设备ID**

C841AA6CB60E3973682F38D44106F43B



**发生了同样问题，无法添加武器养成计划**

**Comment by tea1time1** [comment]
Windows版本
22621.1702
Snap Hutao 版本
1.6.4.0
遇到了同样的问题
