### ISSUE TITLE
[Bug]: 读取游戏内存失败

### ISSUE THREAD

**Issue by arika333** [DGP-Studio/Snap.Hutao#746]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.2965

### Snap Hutao 版本

1.6.4.0

### 设备 ID

234608E1D9EC802DDB518B7112D07AD7

### 问题分类

游戏启动器

### 发生了什么？

更新后启动游戏就会出现这个提示
![L_R62P`AQNII%%HJL)WNR)5](https://github.com/DGP-Studio/Snap.Hutao/assets/135236571/e517d6d8-f731-4366-806a-a2953d1003ae)
ArgumentException 读取游戏内存失败（Parameter 'moduleEntryInfo.HasValue'）

**Comment by arika333** [comment]
不知道会不会是影响帧率还是60的原因 现在就是出现这个提示 然后还是60帧

**Comment by Lightczx** [comment]
重启电脑

**Comment by Lightczx** [comment]
自行检查是否存在其他第三方软件/杀软

**Comment by arika333** [comment]
并没有发现什么第三方 自从3.7帧率失效后也没有下载过什么东西， 杀软我刚才甚至把唯一的火绒卸载了试试，也没有什么用。qwq

**Comment by Lightczx** [comment]
#747
