### ISSUE TITLE
[Bug]:b服帧率解锁失效

### ISSUE THREAD

**Issue by zixiaOOO** [DGP-Studio/Snap.Hutao#747]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.2251

### Snap Hutao 版本

1.6.4.0

### 设备 ID

3D1C4E7F8FFA3B50CD09F1A7ED54C44F

### 问题分类

其它

### 发生了什么？

更新1.6.4之后第一次进B服帧率解锁有效，切换成官服后再切回来就失效了，之后b服帧率解锁就一直失效
![屏幕截图(307)](https://github.com/DGP-Studio/Snap.Hutao/assets/135304451/371585b2-a99b-4ac7-b319-e71e400d0603)
![屏幕截图(309)](https://github.com/DGP-Studio/Snap.Hutao/assets/135304451/f51d8530-4b5a-41d0-9fc8-6b556ddbec0d)

### 你期望发生的行为？

b服帧率解锁正确生效

**Comment by Mugenhasen** [comment]
我刚刚官服也失效了，貌似是米哈游热更新导致的？

**Comment by Masterain98** [comment]
无法复现问题，检查安全类软件日志

**Comment by zixiaOOO** [comment]
> 无法复现问题，检查安全类软件日志

![QQ图片20230602182517](https://github.com/DGP-Studio/Snap.Hutao/assets/135304451/2825ddf2-043b-4f88-ae19-dbbe38dc488c)
没有hutao相关的日志

**Comment by Masterain98** [comment]
> > 无法复现问题，检查安全类软件日志

触发问题后，检查一下系统日志 (`event viewer`) 中是否有胡桃客户端相关的错误

**Comment by zixiaOOO** [comment]
> > > 无法复现问题，检查安全类软件日志
> 
> 触发问题后，检查一下系统日志 () 中是否有胡桃客户端相关的错误`event viewer`

![屏幕截图(310)](https://github.com/DGP-Studio/Snap.Hutao/assets/135304451/94f3a428-01a7-4089-b0aa-2191ebdd465c)
没有相关错误

**Comment by zixiaOOO** [comment]
@Masterain98 刚刚因为误触发现了打开多个原神是帧率解锁都是正常生效的，只打开一个会锁60帧

**Comment by Lightczx** [comment]
@zixiaOOO 检查一下 `Yuanshen.exe`/`UnityPlayer.dll`/`Native\UserAssembly.dll`的文件Md5

**Comment by zixiaOOO** [comment]
> @zixiaOOO 检查一下 `Yuanshen.exe`/`UnityPlayer.dll`/`Native\UserAssembly.dll`的文件Md5

要如何检查?

**Comment by Lightczx** [comment]
> > @zixiaOOO 检查一下 `Yuanshen.exe`/`UnityPlayer.dll`/`Native\UserAssembly.dll`的文件Md5
> 
> 要如何检查?

去搜

**Comment by zixiaOOO** [comment]
> > > @zixiaOOO 检查一下 `Yuanshen.exe`/`UnityPlayer.dll`/`Native\UserAssembly.dll`的文件Md5
> > 
> > 
> > 要如何检查?
> 
> 去搜

没有专业知识我拿头搜

**Comment by zixiaOOO** [comment]
> > > @zixiaOOO 检查一下 //的文件Md5`Yuanshen.exe``UnityPlayer.dll``Native\UserAssembly.dll`
> > 
> > 
> > 要如何检查?
> 
> 去搜

佬你能发一下你的MD5码吗，我比对一下，暂时找不到别人

**Comment by Lightczx** [comment]
你直接发你的

**Comment by zixiaOOO** [comment]
> 你直接发你的

d5e5fe87a9e32fba55bcdb6f608c5d32

**Comment by Lightczx** [comment]
> > 你直接发你的
> 
> d5e5fe87a9e32fba55bcdb6f608c5d32

这是哪个文件的

**Comment by zixiaOOO** [comment]
> > > 你直接发你的
> > 
> > 
> > d5e5fe87a9e32fba55bcdb6f608c5d32
> 
> 这是哪个文件的

那个UnityPlayer.dll

**Comment by arika333** [comment]
这是把746的工单挪过来了？ 是否有什么头绪嘛qwq

**Comment by Lightczx** [comment]
检查一下 Yuanshen.exe/UnityPlayer.dll/Native\UserAssembly.dll的文件Md5

**Comment by arika333** [comment]
ADF870706595A0C38ED41A67B45A0BC3

**Comment by arika333** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/135236571/76a509fe-0ee3-4e35-83af-e607b404288c)

**Comment by arika333** [comment]
ADF870706595A0C38ED41A67B45A0BC3  YuanShen.exe
D5E5FE87A9E32FBA55BCDB6F608C5D32  UnityPlayer.dll
92CD7BF1FBDB87926293A3123A911D25  UserAssembly.dll
分别是

**Comment by zixiaOOO** [comment]
> 

我这仨跟你一样的
![QQ图片20230602231056](https://github.com/DGP-Studio/Snap.Hutao/assets/135304451/8ffeaa19-5dd2-4aab-b2ea-0ebceec0061a)

**Comment by a2445478275** [comment]
有提示 
![微信截图_20230602231447](https://github.com/DGP-Studio/Snap.Hutao/assets/73330178/ba70af2d-9956-44a7-9ef4-f62ef5b47c7d)

**Comment by a2445478275** [comment]
> 检查一下 `Yuanshen.exe`/`UnityPlayer.dll`/`Native\UserAssembly.dll`的文件Md5

https://github.com/34736384/genshin-fps-unlock/releases/tag/v2.1.1
fpsunlock 那边更新了2.1.1 
不着急 慢慢排查

**Comment by Lightczx** [comment]
1.6.4 解锁帧率有问题的加 812818449 QQ群集中处理

**Comment by arika333** [comment]
> 1.6.4 解锁率有问题的加812818449 QQ群中央处理
搜索不到群号x

**Comment by Lightczx** [comment]
现在应该可以了

**Comment by arika333** [comment]
> 现在应该可以了

ty

**Comment by zh8416** [comment]
您好，群搜不到了，官服也报内存读取失败

**Comment by Lightczx** [comment]
等更新
