### ISSUE TITLE
[Feat]:  需要账户格子管理功能

### ISSUE THREAD

**Issue by Xian0Grem** [DGP-Studio/Snap.Hutao#748]
### 背景与动机

账户太多了，管理起来不太方便

### 想要实现或优化的功能

想要账户格子可以分组，折叠，手动调整排序，这样嘎嘎舒服

**Comment by Lightczx** [comment]
可以描述的详细一些么

**Comment by Xian0Grem** [comment]
在启动游戏选项卡下的常规账户管理栏（既检测账户按钮下方），我希望它能够和windows资源管理器，管理文件一样方便，创建分组，手动调整显示顺序

**Comment by Lightczx** [comment]
无法实现排序与分组
