### ISSUE TITLE
[Feat]: 优化养成计划中材料统计的排序

### ISSUE THREAD

**Issue by Tian-Jiangyi** [DGP-Studio/Snap.Hutao#749]
### 背景与动机

初次使用该功能，在材料统计中完全没有看出来材料排列的逻辑，一个一个找的话也很费眼睛

### 想要实现或优化的功能

希望可以优化一下材料的排列，将大世界怪物掉落材料、大世界boss材料、副本材料按顺序排列，或者来一个筛选功能让用户自己排列

**Comment by Lightczx** [comment]
目前按持有材料数量排序

**Comment by Tian-Jiangyi** [comment]
okokok，但是也希望可以多加一些排列的方式
