### ISSUE TITLE
[Bug]: 启动无主界面弹出 报错 The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by miaopasimiao** [DGP-Studio/Snap.Hutao#752]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

win10 19045.2965

### Snap Hutao 版本

1.6.4

### 问题分类

安装和环境

### 发生了什么？

windows10 22H2 打开胡桃无任何显示

Application: Snap.Hutao.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference, Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Snap.Hutao.Program.Main(System.String[])

**Comment by Lightczx** [comment]
更新Windows

**Comment by Lightczx** [comment]
不支持，但通常可以启动

**Comment by miaopasimiao** [comment]
我另外一台电脑可以正常启动 同一个系统版本的 然后这台就是不行 重新注册过系统程序也不行

**Comment by miaopasimiao** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/35228123/36f69188-3aa0-426f-ac1f-4d8f43721529)

**Comment by Lightczx** [comment]
如果调试胡桃你需要确保安装了C++桌面开发与通用平台开发
