### ISSUE TITLE
[Bug]: 1.6.4.0版本帧率解锁失效

### ISSUE THREAD

**Issue by Yuang520** [DGP-Studio/Snap.Hutao#753]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

版本22H2（OS内部版本22621.1702）

### Snap Hutao 版本

1.6.4.0

### 设备 ID

B01337916FBAAF9802D7DAE18FA8DCC4

### 问题分类

游戏启动器

### 发生了什么？

帧率解锁失效，报错ArgumentException 读取游戏内存失败（Parameter 'moduleEntryInfo.HasValue')
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/78641667/7a8cdd51-0b97-4f6a-ba12-f7d085b48f97)

**Comment by Masterain98** [comment]
Duplicate of 747
