### ISSUE TITLE
[Bug]: FPS解锁功能失效

### ISSUE THREAD

**Issue by Dirodzz** [DGP-Studio/Snap.Hutao#754]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1702

### Snap Hutao 版本

1.6.4.0

### 设备 ID

773FF3428B7B96A60BD0864F72F4375A

### 问题分类

游戏启动器

### 发生了什么？

使用管理员模式运行Snap Hutao工具箱，在使用解锁帧率功能时，游戏可以正常启动，但工具箱会报错。

外观设置：
独占全屏：关
全屏：开
无边框：关
宽度：3840
高度：2160

高级功能：
多客户端：关
解锁帧率限制：165fps 开

报错信息：
ArgumentException  读取游戏内存失败（Parameter 'moduleEntryInfo.HasValue')

### 你期望发生的行为？

解锁帧率功能正常运行

**Comment by Masterain98** [comment]
Duplicate of #747

**Comment by Lightczx** [comment]
fixed by https://github.com/DGP-Studio/Snap.Hutao/commit/be4fa571cd6f6dee556088aa01205b746906837c
