### ISSUE TITLE
[Feat]: 主界面左侧导航栏支持自定义功能

### ISSUE THREAD

**Issue by TangTangawa** [DGP-Studio/Snap.Hutao#755]
### 背景与动机

支持自定义功能   例如：排序、显示、隐藏 等，可以根据个人习惯来进行修改操作，不常使用的可以选择隐藏起来，避免在不需要的一些选项中进行不必要的筛选

### 想要实现或优化的功能

支持导航栏排序，某一项选择显示隐藏，自定义分组？还可以加一下自定义调整导航栏位置的功能

**Comment by Lightczx** [comment]
已经在主页推出了仪表板卡片
故不再会考虑再自定义导航栏
