### ISSUE TITLE
[Bug]: 祈愿数据导入错误

### ISSUE THREAD

**Issue by Maiomi9** [DGP-Studio/Snap.Hutao#76]
### Windows 版本

22000.978

### Snap Hutao 版本

1.1.5.0

### 发生了什么？

SG祈愿没更新记录不了 胡桃祈愿记录导入SG导出的json数据 显示有问题（无法正常排序以及显示所用抽数），不能导入excel数据（点击后无反应或闪退）

### 你期望发生的行为？

祈愿记录导入后正常排序

**Comment by shoucandanghehe** [comment]
同样的问题
系统版本 22622.601
hutao版本 1.1.7.0
![image](https://user-images.githubusercontent.com/51957264/194277960-2dceb791-7ebf-45d0-be4d-e1d48a4bf891.png)
![image](https://user-images.githubusercontent.com/51957264/194277992-e8dee965-308f-461f-9a5d-423e42380f69.png)
导入成功后依旧无记录显示
[UIGF.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9723619/UIGF_gachaData-100684238-20221003223104.zip)
