### ISSUE TITLE
[Bug]: HttpRequestException 元数据校验文件下载失败 Response status code does not indicate success: 404 (Not found)

### ISSUE THREAD

**Issue by Meltemi-9264** [DGP-Studio/Snap.Hutao#762]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1778

### Snap Hutao 版本

1.6.4.0

### 设备 ID

1572EFEBA9BD59874F8A6E393F5CE0AA

### 问题分类

安装和环境

### 发生了什么？

仅启动游戏功能生效
![胡桃 1 6 4 0 2023_6_12_星期一 18_11_27](https://github.com/DGP-Studio/Snap.Hutao/assets/38545541/80dc00f8-f497-48c6-bb5f-d32c51f75e2f)
![胡桃 1 6 4 0 2023_6_12_星期一 18_12_45](https://github.com/DGP-Studio/Snap.Hutao/assets/38545541/b849f989-4aa3-4ca3-b8a2-d424df427078)

### 你期望发生的行为？

正常使用

**Comment by Lightczx** [comment]
fixed
