### ISSUE TITLE
[Bug]: HttpRequestException

### ISSUE THREAD

**Issue by SMFDrummer** [DGP-Studio/Snap.Hutao#763]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22631.1835

### Snap Hutao 版本

1.6.5.0

### 设备 ID

FDD8AE5B9C079743873EB31B21BA0F8D

### 问题分类

文件缓存

### 发生了什么？

打开软件显示HttpRequestException
元数据校验文件下载失败 ：ErrorCode 404
除启动游戏外的任何功能均失效且无法加载
我已确认更新为最新胡桃，人在国内，没有挂代理，网络环境为校园网

**Comment by SMFDrummer** [comment]
微软商店所用版本已高于1.6.4，请求与开发者协调

**Comment by Lightczx** [comment]
fixed
