### ISSUE TITLE
[Bug]: 在查找必要的模块时遇到问题

### ISSUE THREAD

**Issue by anpoz** [DGP-Studio/Snap.Hutao#767]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1778

### Snap Hutao 版本

1.6.5.0

### 设备 ID

E0238BE05E5071D48B78227BC23443A8

### 问题分类

其它

### 发生了什么？

启动后报错
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/2825342/3d62e354-6b89-4376-a344-fced2450b43e)

**Comment by Lightczx** [comment]
多试几次就好了

**Comment by tangtangebusi** [comment]
> 多试几次就好了

这种情况下也会启动，但是启动后的游戏没高帧
 设备id
 A2B363A84BBD3743A3F4CDFBC85B43C4

**Comment by Lightczx** [comment]
正常现象，游戏关了再开
