### ISSUE TITLE
使用WIN+D，返回桌面的时候会卡死

### ISSUE THREAD

**Issue by April0117** [DGP-Studio/Snap.Hutao#775]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

23481.1000

### Snap Hutao 版本

1.6.5.0

### 设备 ID

645E8FB7620AEFD7E7C33B2A186C9FF7

### 问题分类

安装和环境

### 发生了什么？

在管理员运行工具箱后，打开游戏，再使用WIn+D返回桌面就会卡死。过程中 鼠标可移动，但是仅限在任务栏，其他区域不显示鼠标的移动轨迹，切换应用或者任务管理器也没效果，只能通过重启来解除。

### 你期望发生的行为？

请尽快修复这个bug，多谢大佬

**Comment by Lightczx** [comment]
你勾选了哪些启动选项@April0117

**Comment by Lightczx** [comment]
独占全屏是这样的

**Comment by April0117** [comment]
好，多谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月19日(周一) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DGP-Studio/Snap.Hutao] 使用WIN+D，返回桌面的时候会卡死 (Issue #775)




 
独占全屏是这样的
