### ISSUE TITLE
无法正常使用胡桃工具箱多开功能

### ISSUE THREAD

**Issue by ewiqurshjk** [DGP-Studio/Snap.Hutao#776]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22624.1848

### Snap Hutao 版本

1.6.5.0

### 设备 ID

1DBB3C7B86D90C8A80EBE3EF55B6FA29

### 问题分类

游戏启动器

### 发生了什么？

5月14日后使用胡桃工具箱多开原神进入游戏开始加载时，原神会弹出”数据异常，请重新登陆游戏“报错弹窗
胡桃工具箱吧和跟我遇到一样问题的人
![Screenshot_2023-06-20-22-06-45-98_2b95b5a1545d19c](https://github.com/DGP-Studio/Snap.Hutao/assets/137188156/bce5bcb4-5614-439b-a237-7e7281cbfbb9)
![Uploading Yuan Shen 原神 Screenshot 2023.06.20 - 20.55.48.49.png…]()
未使用多开功能时则不会

### 你期望发生的行为？

不排除是我自身操作设置使用原因导致的，但希望作者给我一个回复，因为不常用github，所以希望回复邮箱1255722274@qq.com，或者发送短信到手机号15570039907

**Comment by Lightczx** [comment]
多开问题不会修复
