### ISSUE TITLE
[Feat]: 祈愿记录记忆显示模式

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#778]
### 背景与动机

太难看了，并且个人喜欢使用列表视图，每一次都需要手动调整，不能记住设置是个痛点。

### 想要实现或优化的功能

如下图，希望把一圈黑色框去掉，太影响观感了，
<img width="828" alt="06月21日20时17分43秒" src="https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/dece51e3-22ed-47c9-ae49-8029359fc630">

以及，希望优化列表试图或网格视图的默认选项，让人选择一次以后能自动记住上次的结果
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/8ff27348-bb4e-47b0-9b65-7562c0952344)

**Comment by Lightczx** [comment]
黑框应该是你显卡驱动的问题

**Comment by Mikachu2333** [comment]
> 黑框应该是你显卡驱动的问题

竟然是驱动的问题吗！核显哎，我排查一下去，谢谢告知！
