### ISSUE TITLE
[Bug]: InvalidOperationException

### ISSUE THREAD

**Issue by thuhli1620** [DGP-Studio/Snap.Hutao#785]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3086

### Snap Hutao 版本

1.6.5.0

### 问题分类

游戏启动器

### 发生了什么？

通过主页-选择用户-启动游戏启动游戏时，弹出报错：在查找必要的模块时遇到问题:无法读取任何模块，可能是保护驱动已经加载完成，同时无法记住游戏用户，每次都需要重新输入手机号或扫码，每次！

### 你期望发生的行为？

希望通过选择了用户后进入游戏时，不需要再重新输入手机号或扫码！求求了！

**Comment by Lightczx** [comment]
#767
