### ISSUE TITLE
[Feat]: 集成YaeAchievement导入工具

### ISSUE THREAD

**Issue by RA1NO3O** [DGP-Studio/Snap.Hutao#787]
### 背景与动机

目前，导入成就要使用其他工具

### 想要实现或优化的功能

在成就页面集成[YaeAchievement工具](https://github.com/HolographicHat/YaeAchievement)，以快速导入成就

**Comment by Lightczx** [comment]
YaeAchievement需要跟随版本更换注入dll，目前无法简单的嵌入

**Comment by Masterain98** [comment]
也许可以考虑**点击后自动下载并运行** YaeAchievement 作为一个折中的方案。但大陆用户无法稳定地下载 GitHub 源是一个问题，YaeAchievement 亦无本地化翻译。

**Comment by Lightczx** [comment]
YaeAchievement支持EN @Masterain98

**Comment by Lightczx** [comment]
而且YaeAchievement需要 .NET 7 Runtime/C++ v143 下载体验是不如用户自己去安装的
