### ISSUE TITLE
[Crowdin] My account don't have access to page translate.hut.ao

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao#788]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.3086

### Snap Hutao 版本

1.6.5

### 设备 ID

FA1D62A0F8737EF738814EF8F70B6208

### 问题分类

其它

### 发生了什么？

My Crowdin account not access to translate.hut.ao
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/44dae91c-db9f-4380-9bdb-44035f005c9a)

I wish to be granted access to your translation. Thank you.

**Comment by Lightczx** [comment]
@Masterain98 Can you take a look? I can't find access restriction settings

**Comment by Masterain98** [comment]
Please do not just use `Crowdin Suggested Translate`. The translation content needs to be based on the context and context and follow the in-game translation terms.
