### ISSUE TITLE
[Feat]: 实时便笺使用小组件 v2 接口

### ISSUE THREAD

**Issue by ayakasuki** [DGP-Studio/Snap.Hutao#789]
### 背景与动机

原因：现在每次登录都需要验证码才能实时刷新，导致提醒无效
想法：看到有人用小组件的api可以实时更新，只是选项不更新。但主要的体力，派遣都是可以更新的。这里推荐IOS的小组件接口，因为安卓的不及时的实时更新

### 想要实现或优化的功能

可以在不验证的时期自动接入ios接口，需要显示所有现有选项现时状况，依然保留手动验证

**Comment by Lightczx** [comment]
小组件接口虽然不会返回验证码，但是在本应弹出验证码的情况下会返回上次的数据，相当于依旧需要验证

**Comment by Lightczx** [comment]
#823
