### ISSUE TITLE
[Bug]:关于原神3.8版本的胡桃工具箱的网络链接及帧率解锁问题的反馈

### ISSUE THREAD

**Issue by douyuezhang** [DGP-Studio/Snap.Hutao#790]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1

### Snap Hutao 版本

1.6.5.0

### 设备 ID

B7B9847E82DD4107DD77BAC8A511141D

### 问题分类

游戏启动器

### 发生了什么？

原神3.8更新后启动胡桃工具箱网络会链接失败，并有Message弹框，而且帧率解锁不能应用在游戏中

### 你期望发生的行为？

胡桃工具箱网络连接正常并且帧率解锁应用正常

**Comment by Lightczx** [comment]
你的图呢？

**Comment by douyuezhang** [comment]
不好意思，好像是我原来住的地方的网络有波动，今天换了网络后恢复了，
