### ISSUE TITLE
[Bug]: Snap Genshin导入Snap Hutao出现错误：UserdataCorruptedException 用户数据已损坏:不支持的Item ld: 0

### ISSUE THREAD

**Issue by Tenrolby** [DGP-Studio/Snap.Hutao#792]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1848

### Snap Hutao 版本

1.6.5.0

### 设备 ID

559149865DA997B7435FADEB48E1E45D

### 问题分类

安装和环境

### 发生了什么？

我查询并阅读了Snap Hutao官网的祈愿记录相关的文档，使用了最新版本（2022.10.15.10000）的Snap Genshin的导出UIFG Json文件的功能，导出原来的祈愿记录。同时我在常见问题、常见的程序异常、已知问题当中都没有找到我遇到的这个问题。同时我已经按照文档“卸载胡桃工具箱”中的方法，进行过清除数据文件夹和软件卸载重装，以下问题仍然存在。

![Genshin20230708225502](https://github.com/DGP-Studio/Snap.Hutao/assets/108726084/c2905458-c66a-43ce-a7d0-91265a26a2a8)
![Genshin20230708225054](https://github.com/DGP-Studio/Snap.Hutao/assets/108726084/82728e7a-a127-4f7e-828c-8f22b469533f)
在导入Snap Hutao时遇到以下情况。
![胡桃20230708224441](https://github.com/DGP-Studio/Snap.Hutao/assets/108726084/af3033a6-1d80-424c-bff9-bbef9b31c9b3)
![胡桃20230708224454](https://github.com/DGP-Studio/Snap.Hutao/assets/108726084/37ef3059-0b2f-42a3-909b-542aa9a152cb)
我原本在Snap Genshin中的祈愿记录存在一些问题：贴图丢失、繁体字乱入，这也许是问题的成因。
![Genshin20230708224906](https://github.com/DGP-Studio/Snap.Hutao/assets/108726084/923a96b5-cba4-4b18-a5a8-90d912560bb6)
![Genshin20230708224929](https://github.com/DGP-Studio/Snap.Hutao/assets/108726084/a8cb899a-3747-4f36-81cb-8fa4c900984a)

### 你期望发生的行为？

我希望能够成功将Snap Genshin中的祈愿记录导入Snap Hutao。

**Comment by Lightczx** [comment]
不支持繁体

**Comment by Wieso97** [comment]
我有相同的问题。也是在导入UIFG Json文件后，先弹窗已读到文件的内容，点击确定开始后出现的UserdataCorruptedException 用户数据已损坏:不支持的Item ld: 0

**Comment by Wieso97** [comment]
> 

已解决，查看了下Hutao的文档，发现我Metadata文件夹下格式不是chs，而是DE。更换了计算机的区域为中国后，Metadata文件夹下格式变成是chs。再重新导入json文件就恢复了。
