### ISSUE TITLE
[Bug]: 无法显示已经链接的账号

### ISSUE THREAD

**Issue by ONLYLOVELYKISS** [DGP-Studio/Snap.Hutao#793]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22623.891

### Snap Hutao 版本

1.6.5.0

### 设备 ID

16A620A3981C917D6509623767634703

### 问题分类

游戏启动器

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/88222714/82230339-f9d9-4cf0-ae3d-6da2387aec44)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/88222714/7e463a75-6c9f-41e2-bcf6-5421a978020f)
新检测的账号在设置昵称后也无法显示并UID链接

### 你期望发生的行为？

可以显示

**Comment by Lightczx** [comment]
提供 Genshin Impact/YuanShen.exe 旁边的 config.ini 文件

**Comment by ONLYLOVELYKISS** [comment]
[config.zip](https://github.com/DGP-Studio/Snap.Hutao/files/11996923/config.zip)
我放在压缩包里了，ini无法直接上传

**Comment by Lightczx** [comment]
在使用胡桃前使用过其他的启动器？

**Comment by ONLYLOVELYKISS** [comment]
之前用过、

**Comment by ONLYLOVELYKISS** [comment]
我重装游戏后就好了、谢谢，但是如果不重装游戏的话，是不是可以通过更改config.ini文件然后让它正常

**Comment by Lightczx** [comment]
理论上是这样的

**Comment by Lightczx** [comment]
> ![image](https://user-images.githubusercontent.com/88222714/252183934-7e463a75-6c9f-41e2-bcf6-5421a978020f.png)
> 新检测的账号在设置昵称后也无法显示并UID链接

这个地方默认就是不选择的，需要自己选
如果你的意思是在运行时检测了账号且在启动游戏页面显示了而在主页不显示那可能是bug，需要重新开issue
