### ISSUE TITLE
[Bug]: 无法检测到第二个账号

### ISSUE THREAD

**Issue by capulin** [DGP-Studio/Snap.Hutao#794]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

21H2（19044.3086）

### Snap Hutao 版本

1.6.5.0

### 设备 ID

F8097F0FC59809207883C6EB7A9639F0

### 问题分类

游戏启动器

### 发生了什么？

启动游戏内的检测账号功能现在只能检测一个账号，当第二次检测账号时没有反应。此时重新打开胡桃可以再检测账号，但是生成的账号和第一次检测到的账号是相同的，即使她显示的uid不相同
ps：第一次下载的时候是正常的，后来有变过网络环境，那之后就功能异常了。现在即使卸载重新安装也无法恢复正常

**Comment by capulin** [comment]
刚打开出现了一个报错：653366069信息【GetUserGameRolesByActionTicketAsync】中的【ListWrapper1】网络请求异常。
未使用网络代理等工具

**Comment by Lightczx** [comment]
更换网络就是这样的

**Comment by capulin** [comment]
更换网络不是已添加的账号失效要重新添加么？我现在是添加不了第二个账号

**Comment by capulin** [comment]
已经很久没有再更换过网络了。也一直都添加不了第二个

**Comment by Lightczx** [comment]
把你第一个账号删了
