### ISSUE TITLE
服务器切换建议和仪表盘建议

### ISSUE THREAD

**Issue by Mr-chen-0** [DGP-Studio/Snap.Hutao#798]
### 背景与动机

1.服务器切换问题：
官到渠道可以，官到国际服可以。但是渠道服和国际服没法相互转换。打完官服打渠道服，然后在想打国际服就得先转回官服（而且得启动游戏才转），然后关闭官服游戏再转国际服才行。
2.仪表盘建议：
主页功能很全，但是不是每个人都需要这么多功能的，大多数人只是需要启动的少数几个功能，但是每次都要在七个里面扫一眼。就比如我，需要的只有启动，祈愿记录，深渊记录。但是这三个分散而且在七个里。容易点错之类的。

### 想要实现或优化的功能

1.服务器切换
建议增加渠道服和国际服的切换。如果不好实现的话也可以增加一个切换按钮（就是不是非得启动游戏才切换服务器）
2.仪表盘建议
建议设置里可以设置自己需要的功能，然后只显示自己需要的功能。或者把自己需要的功能置顶表红

**Comment by Lightczx** [comment]
多个建议不要发在同一个Issue内
