### ISSUE TITLE
[Bug]: 帧率解锁需要二次开启游戏才会生效

### ISSUE THREAD

**Issue by Mxskyt** [DGP-Studio/Snap.Hutao#801]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1992

### Snap Hutao 版本

1.6.6.0

### 设备 ID

EAC664378A4D6A8CC4B75D8CEA869542

### 问题分类

游戏启动器

### 发生了什么？

从1.6.4.0修复完帧率解锁后直到现在1.6.6.0，第一次通过胡桃打开游戏解锁帧率是失效的只有60帧（胡桃软件内已开启解锁帧率限制），需要关闭游戏再次通过胡桃打开游戏才会解锁帧率。

PS：安全日志正常；事件查看器内无hutao、原神相关事件；MD5值如下
YuanShen.exe：af104358d1647fb870006e274b66f336
UnityPlayer.dll：cf7d4ebf1f4216ef58c2a39b630ef2ca
UserAssembly.dll：8fc1f278ce15016940549b9d851f67f8
另外每次开机首次启动Snap.Hutao，胡桃软件内会提示“InvalidOperationException 在查找必要的模块时遇到问题：无法读取任何模块，可能是保护驱动已经加载完成”。不知道是否与此相关。

### 你期望发生的行为？

首次通过胡桃打开游戏帧率便已解锁

**Comment by Lightczx** [comment]
#767

**Comment by Mxskyt** [comment]
> 

解决方案还是二次启动。。能解决这个问题吗……
