### ISSUE TITLE
[Bug]: 無法利用網頁緩存刷新抽卡紀錄

### ISSUE THREAD

**Issue by dase1353** [DGP-Studio/Snap.Hutao#803]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1992

### Snap Hutao 版本

1.6.6

### 设备 ID

FB3D87095079C39A01B005F2CAAE3144

### 问题分类

祈愿记录

### 发生了什么？

在遊戲開啟抽卡紀錄之後，在胡桃進行網頁緩存刷新的動作，會有兩種結果
1.找不到data_2這個檔案
2.出現新手祈願之後，胡桃閃退

### 你期望发生的行为？

正常刷新紀錄

**Comment by Lightczx** [comment]
#802
