### ISSUE TITLE
7月16日帧数解锁功能失效

### ISSUE THREAD

**Issue by 0101010101012** [DGP-Studio/Snap.Hutao#805]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.2728

### Snap Hutao 版本

1.6.6.0

### 设备 ID

D992141950D74A8093E6C5DE186E8515

### 问题分类

游戏启动器

### 发生了什么？

7月15日登陆后帧率解锁功能失效.

**Comment by Lightczx** [comment]
#767

**Comment by 0101010101012** [comment]
登上去没有报错，试过二次开启游戏了 没有效果

**Comment by Lightczx** [comment]
用管理员开了么
