### ISSUE TITLE
[Bug]: Importing data contains unsupported items

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao#806]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.3086

### Snap Hutao 版本

1.6.6.0

### 设备 ID

FA1D62A0F8737EF738814EF8F70B6208

### 问题分类

安装和环境

### 发生了什么？

Error while trying to import data from Genshin Wish Export application

I don't know if this error was caused by the data of Gacha in Vietnamese, please check. Thank you very much.

The UIGF.txt file is a Gacha data file with Vietnamese language.

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/618e124d-a2d5-44eb-b5d2-44a3f5697020)
[UIGF_816657831_202307160109.txt](https://github.com/DGP-Studio/Snap.Hutao/files/12064255/UIGF_816657831_202307160109.txt)

### 你期望发生的行为？

Import Data Successful.

**Comment by Lightczx** [comment]
UIGF v2.2 dosen't support language other than CHS
