### ISSUE TITLE
[Feat]: 增加设置选项在祈愿历史中只显示抽过的卡池

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#81]
### 你想要实现或优化的功能？

![image](https://user-images.githubusercontent.com/10614984/193712627-6bf45600-7999-447b-9b8b-120f411a1366.png)

【SG已有功能】
如上图，希望增加选项不显示像温迪池、终末弓池、心海池、不灭月华池这种实际未抽卡的记录

**Comment by huang-lian** [comment]
对对对，我也觉得有必要

**Comment by Lightczx** [comment]
impl internal
