### ISSUE TITLE
[Bug]: 国际服转国服后yuanshen.exe和UnityPlayer.dll消失

### ISSUE THREAD

**Issue by JIANGFENG20040206** [DGP-Studio/Snap.Hutao#811]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1992

### Snap Hutao 版本

1.6.6.0

### 设备 ID

F11DD716B44AA0DC75F55D9C33393F29

### 问题分类

游戏启动器

### 发生了什么？

国际服转为国服后Program Files\Genshin Impact\Genshin Impact Game路径中的yuanshen.exe和UnityPlayer.dll会消失。hutao和官方启动器都无法定位到文件位置。

**Comment by JIANGFENG20040206** [comment]
![Cache_33bc74f766f1191f](https://github.com/DGP-Studio/Snap.Hutao/assets/127121733/5ac3a54d-9faa-4e00-a5d9-c0b754bab812)
![Cache_719c6b4ab8d9e0e8](https://github.com/DGP-Studio/Snap.Hutao/assets/127121733/e3b46bed-22ca-4a1b-b6a5-9a94f4713d4e)
![QQ图片20230717231749](https://github.com/DGP-Studio/Snap.Hutao/assets/127121733/093dea0c-161f-49f6-a5c6-7ea310022c97)
如图，昨天发生过一遍，重新下载游戏后恢复，今天国际服转回国服后发生一样的情况，把yuanshen.exe和UnityPlayer.dll贴回来后可以正常运行

**Comment by JIANGFENG20040206** [comment]
今天国服转国际服时出现
![5H}DZC% 9${$J_GR691N}V7](https://github.com/DGP-Studio/Snap.Hutao/assets/127121733/d01f64f1-e3d2-4e33-80fc-238eeedeb0c9)
官方启动器：
![CMRTK~PGV7_C`IK6S EZIJI](https://github.com/DGP-Studio/Snap.Hutao/assets/127121733/5a3e3708-66d9-4d74-9041-1320bcba20b2)
更新后：
![~G C7GAKZASK(PWEF115 L5](https://github.com/DGP-Studio/Snap.Hutao/assets/127121733/0ff4730f-5cf9-40de-b7f7-1727a0f2b13b)

**Comment by Masterain98** [comment]
https://hut.ao/zh/advanced/FAQ.html#%E8%BD%AC%E6%8D%A2%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%A4%B1%E8%B4%A5%E5%90%8E%E5%A6%82%E4%BD%95%E6%81%A2%E5%A4%8D%E6%B8%B8%E6%88%8F%E7%A8%8B%E5%BA%8F

文档中其实有详细描述的解决方法，你自己没查罢了
