### ISSUE TITLE
[Feat]: 是否能添加始终以管理员执行的功能

### ISSUE THREAD

**Issue by QaQ-top** [DGP-Studio/Snap.Hutao#813]
### 背景与动机

[每次启动程序都需要以管理员启动，但是有的软件可以找到始终以管理员启动([PowerToys](https://github.com/microsoft/PowerToys))，是否能参考一下如何实现？

### 想要实现或优化的功能

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/53463795/67bac86a-2da8-4070-80ad-7a3ecda19a3b)

**Comment by Lightczx** [comment]
#573
