### ISSUE TITLE
打开游戏设备会自动锁win键 

### ISSUE THREAD

**Issue by Tbaia** [DGP-Studio/Snap.Hutao#814]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

win10

### Snap Hutao 版本

1.6.6.0

### 问题分类

安装和环境

### 发生了什么？

启用原神后 自动锁win键 导致win键无任何反应 关闭软件恢复正常  以前从未出现过这种状况

**Comment by Lightczx** [comment]
@Tbaia 有装360或者其他的电脑管家么

**Comment by Tbaia** [comment]
没装过杀毒软件 其他游戏都正常 我原游戏启动也不锁win 使用软件启动就会直接锁win

**Comment by Tbaia** [comment]
win+TAB会变成切换选项 然后就不会使用了  咋天使用还一切正常今天打开电脑就成这个样子了 重启过电脑  恢复过默认设置还是这个样子

**Comment by Lightczx** [comment]
@Tbaia 你的游戏启动选项是什么样的

**Comment by Tbaia** [comment]
已经修复了
