### ISSUE TITLE
[Bug]: 在组策略中禁用管理员批准模式后无法打开米游社网页登录

### ISSUE THREAD

**Issue by diazynez** [DGP-Studio/Snap.Hutao#818]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3271

### Snap Hutao 版本

1.6.6.0

### 设备 ID

9F41C3D309B1BE01A17D9EBB68CDA201

### 问题分类

安装和环境

### 发生了什么？

在组策略中禁用管理员批准模式后无法打开米游社网页登录

NullReferenceException
Object reference not set to an instance of an object.

### 你期望发生的行为？

大概……希望兼容一下吧（）

**Comment by Lightczx** [comment]
微软的问题，无法修复
