### ISSUE TITLE
[Bug]: 请允许在汇入 UIGF 资料时指定（或自动辨识）该资料的原始语言。

### ISSUE THREAD

**Issue by ShikiSuen** [DGP-Studio/Snap.Hutao#819]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

Windows 10 Enterprise 2022

### Snap Hutao 版本

1.6.6 (Microsoft Store)

### 问题分类

祈愿记录

### 发生了什么？

Windows 系统语言是繁体中文，安装 Snap Hutao 之后 Snap Hutao 预设以繁体中文介面启动。

此时尝试读入由原神披萨助手导出的祈愿记录（游戏帐号是国服帐号）：
[UIGF_176227546_202306021727.json.zip](https://github.com/DGP-Studio/Snap.Hutao/files/12208468/UIGF_176227546_202306021727.json.zip)

然后直接导致资料损毁，非得在档案总管内手动删掉全部的资料记录之后才出现新的祈愿资料读入选项。

然后我将 Snap Hutao 的介面换成简体中文，重复上述步骤，问题消失。

### 你期望发生的行为？

A. 允许使用者在出现这种灾难状况时彻底真正移除全部的受损的祈愿记录，而不是一锅端。

B. 二选一：
 1. 自动判定 UIGF 档案的语言。
 2. 允许使用者手动指定 UIGF 档案的语言。

**Comment by Lightczx** [comment]
下版本修复
