### ISSUE TITLE
[Bug]: 上传深渊记录时报错

### ISSUE THREAD

**Issue by swqa7697** [DGP-Studio/Snap.Hutao#822]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3208

### Snap Hutao 版本

1.6.6.0

### 设备 ID

D74297399A949C7821CD8F87B73084D4

### 问题分类

其它

### 发生了什么？

上传深渊记录时报错"10001: Please login"，如图：![alt text](https://s3.bmp.ovh/imgs/2023/08/01/a987fe15a2c34915.png)
已在实时便签界面完成米游社验证，并且刷新cookie，并且登录了胡桃账号

**Comment by Lightczx** [comment]
刷新Cookie

**Comment by swqa7697** [comment]
> 刷新Cookie

尝试过了，无效

**Comment by Lightczx** [comment]
删掉cookie重新添加

**Comment by Lightczx** [comment]
另外至少用米游社打开我的角色一次，可能是风控了

**Comment by swqa7697** [comment]
解决了，谢谢
