### ISSUE TITLE
祈愿分析用不了

### ISSUE THREAD

**Issue by MU56dwa** [DGP-Studio/Snap.Hutao#824]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1848

### Snap Hutao 版本

1.6.6.0

### 设备 ID

5D2D8021D1E5FF872E0BE9AF99BDA474

### 问题分类

祈愿记录

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/129649647/cbb274ce-14ad-43ff-8bee-366e6c5458f6)

**Comment by Lightczx** [comment]
从哪里导入的 @MU56dwa
