### ISSUE TITLE
[Bug]: 服务器切换失败

### ISSUE THREAD

**Issue by WenfengBei** [DGP-Studio/Snap.Hutao#826]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3208

### Snap Hutao 版本

1.6.6.0

### 问题分类

游戏启动器

### 发生了什么？

目标：把游戏从官方服official切换为国际服default。
过程：使用管理员权限打开，启动游戏→常规显示了服务器选项和下拉菜单，选择国际服default，点击右上角启动游戏。
现象：游戏被启动，但仍然是官服。
现象2：通过阅读文档，我想进入 `%userprofile%/Documents/Hutao/ServerCache` 目录，但它并不存在。

**Comment by Asaa511** [comment]
一样的问题，
应该不是版本问题我的是19045.3324。

**Comment by Asaa511** [comment]
我现在可以了，我操作是先切换渠道服，等进游戏切换成功时，再退出
关闭胡桃
普通模式进入，此时它会显示是渠道服并锁定
再次关闭
管理员模式进入
切换服务器，切换至国际服，稍等，会显示切换服务器下载界面
进入游戏，显示切换成功。

**Comment by Asaa511** [comment]
> 同样的问题，准确地说完全没有开始转换（没有出现任何窗口），也没有提示问题，游戏直接就启动了Windows版本：22621.1265 Snap Hutao 版本1.6.6.0顺带询问一下你是否一样 使用 了 其他 的国际服转换工具，我觉得这个可能是问题所在 顺带一提我的渠道服与国际服转换是正常的，但似乎每次都要重新下载文件（出来测试的国际服转官服也是类似的）情况，并没有发生转换）

看我新的回复，可以切换

**Comment by aaahai00** [comment]
我不是说了我的渠道服跟国际服可以切换吗，但是切回来还是有问题的，依旧是国际服，没有发生转换，我想我转回来还得转一次渠道服，问题这样切不是很麻烦吗

**Comment by aaahai00** [comment]
> > 同样的问题，准确地说完全没有开始转换（没有出现任何窗口），也没有提示问题，游戏直接就启动了Windows版本：22621.1265 Snap Hutao 版本1.6.6.0顺带询问一下你是否一样 使用 了 其他 的国际服转换工具，我觉得这个可能是问题所在 顺带一提我的渠道服与国际服转换是正常的，但似乎每次都要重新下载文件（出来测试的国际服转官服也是类似的）情况，并没有发生转换）
> 
> 看我新的回复，可以切换
我不是说了我的渠道服跟国际服可以切换吗，但是切回来还是有问题的，依旧是国际服，没有发生转换，我想我转回来还得转一次渠道服，问题这样切不是很麻烦吗

**Comment by Lightczx** [comment]
等待1.7修复

**Comment by WenfengBei** [comment]
大家好！首先感谢大家的回复，其次很抱歉的是我没能及时回复，在此之后正好我要换电脑玩游戏，因此这个问题对我来说就没有了。

**Comment by WenfengBei** [comment]
> 你们正常来说每一次都要下几百兆的资源吗，还是说有缓存后面可以直接转 ，每次都要下怪麻烦的 ，而且我电信网络来下简直是龟速，只有几百kb那种 ，移动就很快 （可能是我电信用了公共的DNS服务器

我之前看过了官方文档，说是有缓存目录的，不必每次都下载

**Comment by aaahai00** [comment]
> > 你们正常来说每一次都要下几百兆的资源吗，还是说有缓存后面可以直接转 ，每次都要下怪麻烦的 ，而且我电信网络来下简直是龟速，只有几百kb那种 ，移动就很快 （可能是我电信用了公共的DNS服务器
> 
> 我之前看过了官方文档，说是有缓存目录的，不必每次都下载

那应该是bug了，不过把切换修了应该就可以了

**Comment by aaahai00** [comment]
> 大家好！首先感谢大家的回复，其次很抱歉的是我没能及时回复，在此之后正好我要换电脑玩游戏，因此这个问题对我来说就没有了。

其实你回不回都差不多，本质上都是给胡桃提供信息，不过信息当然是越多越好了。

**Comment by aaahai00** [comment]
我感觉是不是识别成国服的同时识别成国际服了，所以才没发生转换（毕竟不能保证其他转换器是不是会留下些什么）

**Comment by Lightczx** [comment]
最新的测试版已经修复了这个问题，可以试试
