### ISSUE TITLE
[Feat]: 如果可以，需要一个”过场动画”功能

### ISSUE THREAD

**Issue by parad15o** [DGP-Studio/Snap.Hutao#829]
### 背景与动机

如果可以，需要一个”过场动画”功能

### 想要实现或优化的功能

如果可以，需要一个”过场动画”功能

**Comment by QGhappyChenCheng** [comment]
个人感觉 在B站去搜也可以。或者如果真想应用内看的话弄那个播放器就还是走B站的服务器

**Comment by Masterain98** [comment]
https://github.com/xunkong/cutscene

**Comment by Lightczx** [comment]
游戏内置的过场动画资源只会包含主线/当前版本活动的过场动画，任何限时剧情的CG都会在版本更新后移除

**Comment by Lightczx** [comment]
没有太大的实现意义
