### ISSUE TITLE
[Bug]: 电脑重启后账号清空了

### ISSUE THREAD

**Issue by kmzkyusei** [DGP-Studio/Snap.Hutao#832]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2134

### Snap Hutao 版本

1.6.6.0

### 设备 ID

FA609532BE95FE79472B9DB4721B0863

### 问题分类

用户面板

### 发生了什么？

有时电脑重启之后，虽然工具箱启动界面的账号还在，但是启动游戏后是空的，需要重新录入账号密码
但不是每次重启都会清空，有几次大概是前面下了或者卸载了鼠标驱动，又或者是调了英伟达控制面板的设置，然后再重启号就没了

**Comment by Lightczx** [comment]
网络问题，重启后你的网络环境变了
