### ISSUE TITLE
养成计划的背包物品

### ISSUE THREAD

**Issue by mijjgtvec** [DGP-Studio/Snap.Hutao#833]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [X] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19043.985

### Snap Hutao 版本

1.6.60

### 设备 ID

F375C1A057127C541EF291D19CB47262

### 问题分类

养成计算器

### 发生了什么？

能不能把养成计划的背包物品加一个导入的选项

### 你期望发生的行为？

能不能把养成计划的背包物品加一个导入的选项

**Comment by Lightczx** [comment]
你的内容是功能请求，但是你使用了问题反馈模板
