### ISSUE TITLE
点击我的角色无响应

### ISSUE THREAD

**Issue by 157152816** [DGP-Studio/Snap.Hutao#834]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22631.2191

### Snap Hutao 版本

1.6.6.0

### 问题分类

角色信息面板

### 发生了什么？

[在打开胡桃时我的角色无法从米游社信息同步过来，点击我的角色同步信息之后页面无响应！后续又尝试了刷新cookie，依旧无法刷新出我的角色信息
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/130037682/c74b54a7-47b5-473f-a129-d801fab0d214)

### 你期望发生的行为？

在点击同步信息之后相关页面会自动呈现

**Comment by Lightczx** [comment]
右下角选中你的角色
