### ISSUE TITLE
建议加一个游戏版本更新检测

### ISSUE THREAD

**Issue by xiaoyekong2** [DGP-Studio/Snap.Hutao#835]
### 背景与动机

版本更新没有提示，点击启动游戏直接就把游戏打开了，进游戏之后游戏又提示我需要前往启动器更新，有点麻烦

### 想要实现或优化的功能

建议加个**检测游戏版本更新**的功能，最新版游戏md5和当前游戏md5不一样就提示游戏有新版本，然后帮我打开官方启动器

**Comment by Lightczx** [comment]
在 #786 实现后无需此功能
