### ISSUE TITLE
用户界面操作闪退

### ISSUE THREAD

**Issue by Asaa511** [DGP-Studio/Snap.Hutao#842]
### 检查清单

- [X] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [X] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3324

### Snap Hutao 版本

1.6.6.0

### 设备 ID

3A503FB60C579420D72A91B40D25EE51

### 问题分类

用户界面

### 发生了什么？

全部点击左侧菜单，在点击到角色资料时偶现闪退

同样的操作，在点击我的角色时偶现闪退

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 3A503FB60C579420D72A91B40D25EE51

**Comment by Lightczx** [comment]
fixed by server
