### ISSUE TITLE
[Bug]: 无法启动游戏

### ISSUE THREAD

**Issue by SavitarC** [DGP-Studio/Snap.Hutao#843]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2066

### Snap Hutao 版本

1.6.6.0

### 设备 ID

32F40CCA856D9FC84382B4F747C0D3E3

### 问题分类

游戏启动器

### 发生了什么？

点击启动游戏弹出通知，无法启动
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/71271200/22cf16ab-5d79-4406-a299-a325678072c3)

**Comment by Lightczx** [comment]
是有多个显示器么

**Comment by SavitarC** [comment]
> 是有多个显示器么

是的

**Comment by SavitarC** [comment]
是显示器的选择问题，修正后启动成功

**Comment by Lightczx** [comment]
#743
