### ISSUE TITLE
[Bug]: 祈愿记录无法上传云端？

### ISSUE THREAD

**Issue by Focalorss** [DGP-Studio/Snap.Hutao#846]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2134

### Snap Hutao 版本

1.6.6.0

### 设备 ID

E1703E62CCCA4F0EC32F476C40C34105

### 问题分类

祈愿记录

### 发生了什么？

上传祈愿记录到胡桃云时，提示：数据异常，无法保存至云端
有胡桃云时长，但无法上传，上传失败

**Comment by Lightczx** [comment]
你的数据中包含无效的物品，自行检查

**Comment by Focalorss** [comment]
请问何为无效物品？

**Comment by Focalorss** [comment]
> 你的数据中包含无效的物品，自行检查



> 你的数据中包含无效的物品，自行检查

请问何为无效物品，我的数据都是正常导入的

**Comment by Lightczx** [comment]
那你发导入的文件

**Comment by Focalorss** [comment]
> 那你发导入的文件
我该使用网盘发吗？

**Comment by Focalorss** [comment]
> 那你发导入的文件

从胡桃导出的json文件是吗？github貌似不能发送json文件，所以网盘发送
链接[https://www.123pan.com/s/eWLRVv-u95Ch.html](url)

**Comment by Lightczx** [comment]
打包zip发

**Comment by Focalorss** [comment]
> 打包zip发
[258719570.zip](https://github.com/DGP-Studio/Snap.Hutao/files/12567704/258719570.zip)

**Comment by Lightczx** [comment]
看了一眼服务器数据库里是有这个UID的记录的
数据持有者是`focalors_fu@outlook.com`

**Comment by Focalorss** [comment]
> 看了一眼服务器数据库里是有这个UID的记录的 数据持有者是`focalors_fu@outlook.com`

是的，几个月前我可以上传云端，但现在无法更新数据进去

**Comment by Lightczx** [comment]
把以前的删了重新上传

**Comment by Focalorss** [comment]
> 把以前的删了重新上传

好的可以了，感谢帮助！
