### ISSUE TITLE
[Feat]: 添加反和谐功能

### ISSUE THREAD

**Issue by Lion-LiHaoyi** [DGP-Studio/Snap.Hutao#847]
### 背景与动机

到了枫丹游泳的时候角色背后一直跟着个小水泡看着实在碍眼

### 想要实现或优化的功能

可以去除角色不同状态出现的虚化，类似于[fhx](https://www.bilibili.com/opus/830345490732154899)，放在高级功能区

**Comment by Lightczx** [comment]
这个没开源，抄不了（bushi
