### ISSUE TITLE
[Bug]: 解锁帧率限制后水下卡顿

### ISSUE THREAD

**Issue by maodanhh** [DGP-Studio/Snap.Hutao#848]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2134

### Snap Hutao 版本

1.6.6.0

### 问题分类

游戏启动器

### 发生了什么？

使用无边框窗口, 解锁帧率限制启动游戏后, 在进入水下之前任何区域都正常(240fps), 进入水下之后开始卡顿(降到1-20fps), 出水后依然卡顿, 直到远离可以下潜的水域后恢复正常, 接近水域后开始卡顿.
使用官方启动器或使用胡桃工具箱但不解锁帧数启动不会出现水下卡顿状况.
已排除设备性能问题.

**Comment by Lightczx** [comment]
什么显卡

**Comment by maodanhh** [comment]
有两张显卡, 一张4080, 接主屏幕(4k240hz), 一个13700k带的核显好像是uhd770, 接一块副屏(2k60hz)放攻略.
游戏启动在主屏幕上.

**Comment by Lightczx** [comment]
检查卡顿时的显存使用情况

**Comment by maodanhh** [comment]
> 检查卡顿时的显存使用情况

占用在3.9-5G, 进入水下卡顿时和正常差不多

**Comment by Lightczx** [comment]
应该是原神本身的优化问题

**Comment by CirnoSalt** [comment]
![image](https://user-images.githubusercontent.com/23478997/263032162-492eedc4-0faf-4a2f-9684-706792c77425.png)
4.0开始帧生成时间爆炸了所以才这样，开放120fps的M1/M2iPad/13Pro大概率也受影响了，
4.0.1也并没有修好这个bug，建议以苹果用户的名义向官方反馈一波。

**Comment by maodanhh** [comment]
> ![图像](https://user-images.githubusercontent.com/23478997/263032162-492eedc4-0faf-4a2f-9684-706792c77425.png) 4.0开始帧生成时间爆炸了所以才这样，开放120fps的M1/M2iPad/13Pro大概率也受影响了， 4.0.1也并没有修好这个bug，建议以苹果用户的名义向官方反馈一波。

我昨晚也发现了, 小飞机里显示数字的帧数和帧生成时间都正常, 但是打开曲线就和你图片里一样, 实际体验巨卡
