### ISSUE TITLE
[Feat]: 取消服务器转化功能

### ISSUE THREAD

**Issue by earthjasonlin** [DGP-Studio/Snap.Hutao#850]
### 背景与动机

有时候在服务器转化开始的时候忘了开代理之类的，导致转换过程很慢，但这时候又不能直接关闭胡桃，只能慢慢等着

### 想要实现或优化的功能

增加一个取消转化的功能

**Comment by Lightczx** [comment]
已在 1.7 修复，可以下载测试版试用
