### ISSUE TITLE
[Feat]: 在应用内添加帮助页面

### ISSUE THREAD

**Issue by AllesUgo** [DGP-Studio/Snap.Hutao#852]
### 背景与动机

前往网站获取帮助需要额外操作，且对于部分用户（懒得去官网找）获取帮助存在困难

### 想要实现或优化的功能

在应用内内置帮助页面，可以快速获取常用帮助，类似哔哩的做法
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/67179426/e0aa6dab-3408-4292-bbc2-5286f7da13b2)

**Comment by Lightczx** [comment]
#1039
