### ISSUE TITLE
[Bug]: 无法从米游社养成计算同步角色信息

### ISSUE THREAD

**Issue by mocksonline** [DGP-Studio/Snap.Hutao#853]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2134

### Snap Hutao 版本

1.6.6.0

### 设备 ID

E248EC462B9FDF93DFF2642C56AC946B

### 问题分类

玩家查询

### 发生了什么？

使用管理员权限打开本工具箱；登录账户(欧服账号)；在左侧快捷栏选择了工具栏下的“我的角色”，点击右上的“同步角色信息”，分别使用三种方式同步。当且仅当使用“从米游社养成计算同步”时会报错误码，为-502002，信息为“Please allow authorization to continue”。
本人使用欧服账号，第二个同步选项是可以使用的，第三个同步选项“从米游社养成计算同步”是功能还没完成 (同步游戏内角色信息功能可在hoyolab app中查看)？还是其他的设置问题？

### 你期望发生的行为？

希望可以使用“从米游社养成计算同步”从而同步所有佩戴的圣遗物信息

**Comment by Lightczx** [comment]
需要去HoYoLAB里操作
