### ISSUE TITLE
[Feat]: 未开通状态下建议不自动上传抽卡记录到云服务

### ISSUE THREAD

**Issue by jinsulive** [DGP-Studio/Snap.Hutao#854]
### 背景与动机

未开通状态下每次打开祈愿记录都会弹出这个提示，影响体验
![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/73291319/0a7f9ab7-26b0-4606-8cfe-74807c890425)

### 想要实现或优化的功能

未开通状态下建议不自动上传抽卡记录到云服务

**Comment by Masterain98** [comment]
下版本修复
