### ISSUE TITLE
关于账号登录时的填充建议

### ISSUE THREAD

**Issue by kudoukouki** [DGP-Studio/Snap.Hutao#855]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2215

### Snap Hutao 版本

1.6.6.0

### 设备 ID

F1867665F4B2C91D77DA0EF3D893DD81

### 问题分类

其它

### 发生了什么？

我不知道为什么这个软件会保存我的输入记录，这样在我下次输入的时候会挡着我的视线。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/104427289/114f32ce-f7f7-4712-bfab-f971384f75d0)

### 你期望发生的行为？

请问这个问题要怎么解决，是不是和webview2有关？没接触过这个东西，不知道怎么删除填充建议，还有不启用填充建议功能

**Comment by Masterain98** [comment]
自动填充是由你本地的 Edge 浏览器处理的

**Comment by kudoukouki** [comment]
> 自动填充是由你本地的 Edge 浏览器处理的

我把edge功能全关了试试
