### ISSUE TITLE
用户数据已损坏

### ISSUE THREAD

**Issue by leishen1518** [DGP-Studio/Snap.Hutao#856]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

win11

### Snap Hutao 版本

1.6.6.0

### 设备 ID

A0223B05AD18799AE525F6A20743DA48

### 问题分类

安装和环境

### 发生了什么？

祈愿记录无法查询，显示用户数据已损坏。
![3FMI L~ O0W`S(%VP0_@1$X](https://github.com/DGP-Studio/Snap.Hutao/assets/143325048/24f0688d-7183-41db-ab0e-3a75437052c4)

**Comment by Masterain98** [comment]
导入了错误格式的数据，在设置中重置数据

**Comment by Lightczx** [comment]
1.7 开始将不再能导入包含不正确物品的祈愿记录，
在此之前需要手动删除Userdata.db
