### ISSUE TITLE
[Bug]: 属性统计闪退

### ISSUE THREAD

**Issue by thz-hub** [DGP-Studio/Snap.Hutao#86]
### Windows 版本

22H2

### Snap Hutao 版本

1.1.6

### 发生了什么？

属性统计闪退闪退，上次反馈的祈愿缓存刷新依旧闪退。

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] #87

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by thz-hub** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9708894/Log.zip)

**Comment by Lightczx** [comment]
先切换到角色资料页面等待角色列表出现，再打开属性统计

**Comment by thz-hub** [comment]
已尝试，依旧闪退
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9712748/Log.zip)

**Comment by thz-hub** [comment]
[Userdata.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9712988/Userdata.zip)
我chang's尝试了删除、重装，依旧不行，且stoken刷新失效，cookie获取失效
![image](https://user-images.githubusercontent.com/62689630/193987937-46bfd80a-f057-41ac-a77b-109d43a63efa.png)

**Comment by Lightczx** [comment]
重新上传，数据库内容明显不正确

**Comment by thz-hub** [comment]
[Userdata.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9713007/Userdata.zip)

**Comment by thz-hub** [comment]
这个我打开看了有内容

**Comment by thz-hub** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9713013/Log.zip)
这是之前尝试的日志

**Comment by Lightczx** [comment]
你的截图显示有祈愿记录，但是数据库里完全没有，显然是不正确的

**Comment by thz-hub** [comment]
这个啊 我这个截图是第二次重装的，后面又重装了一次 ，同样尝试了没有导入祈愿，但bug依旧存在，就没有重新截图了

**Comment by thz-hub** [comment]
图中的记录是json导入的，stoken导入无反应

**Comment by thz-hub** [comment]
图中的记录是json导入的，stoken导入无反应

**Comment by thz-hub** [comment]
我又试了一下，1.1.5版本填入cookie后有升级stoken按钮，升级后祈愿可用，升级1.1.6版本后可用。单独安装1.1.6版本无升级按钮，只有获取cookie按钮，且获取失败。属性统计依旧闪退。
![image](https://user-images.githubusercontent.com/62689630/194031834-e1467a3b-fa73-48ad-83fb-22741b0f38d3.png)
![image](https://user-images.githubusercontent.com/62689630/194031850-8c2d1221-ead8-46c0-8a3f-243ad5b89460.png)

**Comment by Lightczx** [comment]
请更新1.1.7后重新上传日志

**Comment by thz-hub** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9721193/Log.zip)

**Comment by Lightczx** [comment]
崩溃后立即上传，不能再次打开胡桃

**Comment by thz-hub** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9721219/Log.zip)
b不打开发现log.db未更新

**Comment by Lightczx** [comment]
> [Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9721219/Log.zip) b不打开发现log.db未更新

删除文件，尝试操作，崩溃后上传

**Comment by thz-hub** [comment]
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9721239/Log.zip)
