### ISSUE TITLE
[Bug]: 导入从其他工具获取的祈愿记录失效

### ISSUE THREAD

**Issue by VsentK** [DGP-Studio/Snap.Hutao#860]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2215

### Snap Hutao 版本

1.6.6.0

### 问题分类

祈愿记录

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/137362493/56588aca-c24b-46ce-b4ce-b729caad0622)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/137362493/c810404d-c767-4ed0-8251-1708e1a2a14e)
如图，导入前后并没有变化，但是提示导入成功

**Comment by Lightczx** [comment]
只会导入比当前记录更老的记录，新与当前记录最老记录的部分不会导入

**Comment by VsentK** [comment]
> 只会导入比当前记录更老的记录，新于当前记录最老物品的部分不会导入

胡桃里保存的已经是六个月之前的了，而我要导入的都是晚于胡桃内储存的记录

**Comment by VsentK** [comment]
> 只会导入比当前记录更老的记录，新于当前记录最老物品的部分不会导入

意思是说从外部导入的只能补充之前的记录，而不能增加新的记录，就是这么设计的吗？
