### ISSUE TITLE
[Bug]: UI 除设置外无法点击

### ISSUE THREAD

**Issue by HuanLinOTO** [DGP-Studio/Snap.Hutao#861]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1825

### Snap Hutao 版本

1.6.6.0

### 设备 ID

F9F27F46FCD5B89C45B9D7DE18A74845

### 问题分类

用户界面

### 发生了什么？

演示视频可在 910780153 群( Snap Hutao )中找到，文件名为 `2023-08-28 22-08-40.mkv`

在左侧 menubar 中除 `设置` 外其他选项均无法点击（显示鼠标样式为 `ns-resize`，拖动设置页面内的滚动条后变成了 `ew-resize`）

反复重启 SnapGenshin 都无效

下载渠道：微软商店

### 你期望发生的行为？

正常点击

**Comment by HuanLinOTO** [comment]
多次重启之后 `用户` 也可以点了，疑似有个遮罩层没去掉（

**Comment by Lightczx** [comment]
WinUI问题，没有堆栈几乎无法解决
