### ISSUE TITLE
[Feat]: 超长字串符自动滚动

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#863]
### 背景与动机

![D}{(9(WKNB)PRU{DY$1U69B](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/b331527c-3abe-4624-bf15-08bdeb4996ab)

### 想要实现或优化的功能

针对非中文环境下部分字串符过长而发起的提议

**Comment by Lightczx** [comment]
https://github.com/CommunityToolkit/Labs-Windows/issues/426

**Comment by Lightczx** [comment]
Tracked by #1394
