### ISSUE TITLE
深渊记录上传失败

### ISSUE THREAD

**Issue by sanye9** [DGP-Studio/Snap.Hutao#864]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3324

### Snap Hutao 版本

1.6.6.0

### 设备 ID

4A414573099280D90D11F07AEFFAB0F3

### 问题分类

其它

### 发生了什么？

1.我在想要上传深渊数据的时候，提示我需要登陆，但实际上已经登陆过了
2.在祈愿记录界面每次打开都会弹出至少5个通知，提示我未开通云服务，每次都要手动点x，很是烦恼

**Comment by Lightczx** [comment]
1.7 修复
我们会在 1.7 修复后对所有持有胡桃通行证的账号进行时长补偿
具体时间请等待通知

**Comment by Masterain98** [comment]
提出新的 issue 之前请先搜索别人已经发布的，不要发布重复的 issue

Duplicate of #854

**Comment by Masterain98** [comment]
Duplicate of #854

**Comment by sanye9** [comment]
> Duplicate of #854

抱歉，看到了

**Comment by sanye9** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/106089708/0d5b54b3-4a6e-4939-9877-644a23ef7e0a)
设置里面也登陆了胡桃账号

**Comment by sanye9** [comment]
帮我关闭吧，找到原因了。。

**Comment by Lightczx** [comment]
> ![image](https://user-images.githubusercontent.com/106089708/263957647-0d5b54b3-4a6e-4939-9877-644a23ef7e0a.png) 设置里面也登陆了胡桃账号

你需要删除再重新添加账号
如有必要甚至需要去米游社我的角色页面查看
有时风控了也是这个提示
