### ISSUE TITLE
有适合 LTSC 2019 的版本吗？

### ISSUE THREAD

**Issue by fang-yj** [DGP-Studio/Snap.Hutao#866]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

LTSC 2019     17763.4737

### Snap Hutao 版本

1.6.6

### 问题分类

安装和环境

### 发生了什么？

LTSC 2019 安装不了最新版本的，有没有大神提供一下以前的版本

**Comment by Lightczx** [comment]
最低支持19041

**Comment by huzhiyuan1994** [comment]
Mark：
系统：win10 ltsc 2021，21H2 build 19044.3930
在powershell中执行安装如下包后可以手动安装
```
Add-AppPackage .\Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe.Appx
Add-AppPackage .\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe.Appx
Add-AppPackage .\Microsoft.VCLibs.140.00_14.0.33321.0_x64__8wekyb3d8bbwe.Appx
```
类似上面再手动安装下
```
Add-AppPackage .\Snap.Hutao.1.9.5.msix
```
PS：不过目前网页说明文档上写着不支持

**Comment by qhy040404** [comment]
你要自己愿意研究那无所谓

**Comment by Lightczx** [comment]
> 不过目前网页说明文档上写着不支持

可运行与受我们支持是两回事
