### ISSUE TITLE
[Feat]: 希望在启动游戏界面增加一个快速更改输入设备的设置,且全屏运行分辨率也可以快捷更换无需键盘

### ISSUE THREAD

**Issue by wzxyisme** [DGP-Studio/Snap.Hutao#868]
### 背景与动机

使用串流软件使电脑游戏画面串流到手机上，但远程只能用手柄操作或者触摸操作，而想要更换输入得按ALT才能移动鼠标进入设置，这使得手柄暂无法远程更换输入，且想要画面填充满现在的全面屏手机只能更改分辨率，大概率会卡画面，而且用完还是要改回去非常麻烦

### 想要实现或优化的功能

我希望在启动游戏界面增加一个快捷更改输入设备的设置,且全屏运行分辨率也可以便捷更换无需键盘，可自行增加或者直接读取系统信息添加在显卡控制面板内自定义的分辨率参数（快捷更换输入设备比较重要，更改分辨率次之）

**Comment by wzxyisme** [comment]
> 更改分辨

更改分辨率是指做成下拉菜单，提供分辨率预设，是在游戏运行前设置
更改分辨率可有可无，主要是游戏运行前可以指定输入设备吗？

**Comment by Lightczx** [comment]
Tracked by #1394
