### ISSUE TITLE
希望可以加入关闭后最小化到任务栏选项设置。以及开机自启动设置 （最好可以选择是否以管理员权限开机自启）

### ISSUE THREAD

**Issue by msir9426340** [DGP-Studio/Snap.Hutao#873]
### 背景与动机

希望可以加入关闭后最小化到任务栏选项设置：
因为个人习惯和其他原因吧，启动完原神本体后，我总是下意识的关闭胡桃工具箱，然后这样工具箱里的设置就不会应用到游戏里了。而且启动后，任务栏总是有一个工具箱在占用位置，这让我切窗口很不方便（因为有时候可能会看攻略视频），并且我也希望任务栏简洁一些，不显示暂时用不到的应用。
开机自启动设置：
由于是通过微软商店安装下载的，通过一些搜索，我并未找到这类软件的自启动方法。所以我希望工具箱可以内置这个设置。
（一定要有以管理员权限自启动啊！）

### 想要实现或优化的功能

关闭工具箱窗口后最小化到任务栏的设置。隐藏到任务栏通知区域，不退出程序。
设置开机自启动！ （一定要有以管理员权限启动的设置）

**Comment by Lightczx** [comment]
如果你有其他折衷的方案可以另开issue说明
