### ISSUE TITLE
导入数据中存在不支持的物品

### ISSUE THREAD

**Issue by yechoo0321** [DGP-Studio/Snap.Hutao#879]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.3086

### Snap Hutao 版本

1.7.0.0

### 问题分类

祈愿记录

### 发生了什么？

2023年9月2号上午7点
我从提瓦特小助手，导出抽奖数据
https://www.lelaer.com/uigf.php
导入胡桃工具箱时，导入失败
并提示，存在不支持物品

**Comment by yechoo0321** [comment]
已经把系统升级到了
22h2
19045.3324
再次试了试还是同样的错误

**Comment by yechoo0321** [comment]
@Masterain98  应该怎么导入抽奖数据，才能成功

**Comment by Masterain98** [comment]
联系数据提供方解决

**Comment by vspirit803** [comment]
使用https://github.com/biuuu/genshin-wish-export v0.9.1导出的UIGF也无法导入胡桃工具箱v1.7.0.0
win11 22H2  22621.2215
怀疑是导出的UIGF为v2.2版本, 不存在item_id字段, 导入时根据name生成item_id逻辑存在问题

**Comment by vspirit803** [comment]
> 联系数据提供方解决
直接用胡桃导出的json,把版本改为v2.2也能复现
