### ISSUE TITLE
[Bug]: 自带页面登录米游社，提示登录失败

### ISSUE THREAD

**Issue by yinghualuowu** [DGP-Studio/Snap.Hutao#88]
### Windows 版本

21H1 19043.2006

### Snap Hutao 版本

1.1.6.0

### 发生了什么？

点击账号->cookie操作->登录米哈游通行证（看到个人中心页面）->点击继续按钮-> 提示登录失败
![企业微信截图_16649733153036](https://user-images.githubusercontent.com/22371568/194063122-1982a2fd-b0e1-4e2a-96ba-490b58c058a2.png)
![企业微信截图_16649733279414](https://user-images.githubusercontent.com/22371568/194063267-96e8e82e-8efe-4fac-881e-af26eecd5054.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
fix internally
