### ISSUE TITLE
[Bug]: 祈愿记录导入失败：导入数据中包含了不支持的物品

### ISSUE THREAD

**Issue by ouious** [DGP-Studio/Snap.Hutao#881]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2134

### Snap Hutao 版本

1.7.0.0

### 设备 ID

77EA821F504E62126C9D283382CE9F00

### 问题分类

祈愿记录

### 发生了什么？

准备将Genshin Wish Export导出的UIGF文件导入Snap Hutao时，弹出错误提示：
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/38485716/138223d5-e3fe-4ad5-8439-1b7b62c8545f)

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/38485716/c4848526-2e0b-4eef-bb58-7f3a81cb882d)

多次尝试将list中的抽卡记录只保留一条，保留的条目来自于各卡池都仍然弹出错误。
文件内容例：
{"info":{"uid":"176408499","lang":"zh-cn","export_time":"2023-09-02 10:37:52","export_timestamp":1693622272024,"export_app":"genshin-wish-export","export_app_version":"v0.9.1","uigf_version":"v2.2"},"list":[{"gacha_type":"200","time":"2021-07-05 10:50:20","name":"翡玉法球","item_type":"武器","rank_type":"3","id":"1625450760000611669","uigf_gacha_type":"200"}]}

猜测可能是格式不匹配。

### 你期望发生的行为？

希望能够正常导入。
如果真有个别物品无法支持，也希望可以导入正常的部分，系统可以作出Warning，但不要整体拒绝。

**Comment by Lightczx** [comment]
> 如果真有个别物品无法支持，也希望可以导入正常的部分，系统可以作出Warning，但不要整体拒绝。

那就会出现记录少金的情况

**Comment by Lightczx** [comment]
上传你的完整文件，例没有用

**Comment by Suwmlee** [comment]
[116172563-bak.zip](https://github.com/DGP-Studio/Snap.Hutao/files/12503452/116172563-bak.zip)

你好，遇到同样问题

**Comment by ouious** [comment]
楼上已经有完整文件了，为保护隐私就不上传我自己的了，事实上我举的例子只要保存到文本里也可以看成一个完整抽卡记录。

又做了一些测试，目测问题原因是现在只对UIGF v2.3有支持，v2.2的文件无法正确读取。
 

测试1：只改变问题描述中例子的版本号。无法导入，提示包含不支持的物品。

> {"info":{"uid":"176408499","lang":"zh-cn","export_time":"2023-09-02 10:37:52","export_timestamp":1693622272024,"export_app":"genshin-wish-export","export_app_version":"v0.9.1",**"uigf_version":"v2.3"**},"list":[{"gacha_type":"200","time":"2021-07-05 10:50:20","name":"翡玉法球","item_type":"武器","rank_type":"3","id":"1625450760000611669","uigf_gacha_type":"200"}]}

测试2：改变版本号，且根据[UIGF v2.3规则](https://uigf.org/zh/standards/UIGF.html)添加必要字段item_id（从[UIGF API](https://uigf.org/zh/API.html)字典查询后手动添加），成功导入。（根据规则v2.3每件物品只要有5个必备字段，将name, item_type, rank_type删除后进行测试，依然导入成功）

> {"info":{"uid":"176408499","lang":"zh-cn","export_time":"2023-09-02 10:37:52","export_timestamp":1693622272024,"export_app":"genshin-wish-export","export_app_version":"v0.9.1",**"uigf_version":"v2.3"**},"list":[{"gacha_type":"200","time":"2021-07-05 10:50:20",**"item_id":"14304"**,"name":"翡玉法球","item_type":"武器","rank_type":"3","id":"1625450760000611669","uigf_gacha_type":"200"}]}

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/38485716/bfc986a9-c81c-447d-a5b1-3db07345857a)


测试3：删除上述存档，再次确认[UIGF v2.2规则](https://github.com/DGP-Studio/Snap.Genshin.Docs/blob/4d6727e90a8272b862b460b38705f74e50e52709/docs/development/StandardFormat.md)，item_id是允许的非必要字段，无论是尝试将测试2用例的uigf_version改为v2.2，还是之后又尝试将所有不必要字段补齐或删除，均无法导入，提示包含不支持的物品。


测试4：搞怪测试，常驻池抽神里，且item_id与name等信息不匹配的情况：成功导入，以item_id为唯一标识符，无其他校验。

> {"info":{"uid":"176408499","lang":"zh-cn","export_time":"2023-09-02 10:37:52","export_timestamp":1693622272024,"export_app":"genshin-wish-export","export_app_version":"v0.9.1","uigf_version":"v2.3"},"list":[{"gacha_type":"200","time":"2021-07-05 10:50:20","item_id":"10000002","name":"菲米尼","item_type":"武器","rank_type":"3","id":"1625450760000611669","uigf_gacha_type":"200"}]}

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/38485716/83ee5d0a-6531-428b-9bc9-014b174661db)

**Comment by ouious** [comment]
归根结底，UIGF v2.3不是一个向下兼容的版本，因为有了新的必要字段。
为了保证和其他软件的交互，最好是暂时保留v2.2（可以向下兼容）的读取功能。（总不能等大家都更新吧，捂脸）

**Comment by Lightczx** [comment]
v2.3 格式本质上向下兼容
但是不是app说支持 v2.3 他就支持 v2.3
至于导入数据，目前存在无法正确合并数据的问题
这是1.7.0已知问题 已在1.7.2 修复 请等待更新

**Comment by Lightczx** [comment]
至于你说的v2.2无法读取多半是因为导出方没有遵守v2.2格式的规范，导出时itemtype与name不匹配或者缺少了关键的id字段导致的

v2.2 同样也是 不是app说支持 v2.2 他就支持 v2.2
如果提示了不支持的物品可以 100% 确定数据的导出方是没有严格遵守 v2.2标准的
可以去给相关的导出软件开 issue

**Comment by zh8416** [comment]
按照你的测试2，我把云崽机器人的记录转过来了，还好只有两千多条。云崽这个项目打一开始就没记录item_id，uigf一更新直接完蛋。

**Comment by Lightczx** [comment]
yunzai只支持v2.2

**Comment by ouious** [comment]
咱就是说，付出的热情不被理解还是蛮让人伤心的。上面这些测试已经做得非常详尽了，足够定位问题了，但你似乎并没有仔细看过。比如，测试4已经说明了 itemtype与name不匹配并不会导致问题，是可以正确读取的（正确是指读取行为符合v2.3规则描述），再比如测试用例本身就是genshin-wish-export导出的结果，它是否符合v2.2是可以直接观察出来的，完全不理解为什么会有其不遵守规范的揣测。既然提出了这个怀疑，我去尝试了一下，genshin-wish-export的记录是可以和yunzai、寻空等互通的，互相导入导出都没有问题，所以肯定是这边的issue呀。
　
重新阐述一下的话，我所说的兼容性是指一个符合v2.2规则的json文件，能不能直接被一个v2.3的解析器读取？现实是，取决于各家解析器的写法。v2.2缺少item_id，直接读取肯定是读不了的，那么，需要一些glue code去调用一下UIGF API，但似乎现版本的snap hutao并没有写这部分代码。
　
可能，严格来说，这个issue并不算是bug，而是一个snap hutao现版本的feat：只支持v2.3的导入。
那么诉求是希望增加对v2.2的支持。
至于是否做出更改，由你们决定就好了。
作为用户，只能做这么多了。

**Comment by Lightczx** [comment]
目前在正确数据格式导入成功后确实存在一些问题，但是这是导入成功后的行为
如果在导入成功前就提示错误绝对是导出方的问题，另外一个仅支持 v2.2 格式的文件不可以通过只修改版本号达到升级的目的

> 测试4已经说明了 itemtype与name不匹配并不会导致问题，是可以正确读取的

v2.3 规范指出 list 中的物品必须要包含正确的 item_id

> 它是否符合v2.2是可以直接观察出来的

符合规范问题肉眼确实能够看出，但是需要仔细与严谨
部分物品包含了不正确的 item_type,所以并未严格遵循 v2.2格式规范

> genshin-wish-export的记录是可以和yunzai、寻空等互通的

那是因为他们的实现相对宽松，并不会校验诸如 刻晴是武器，以及info中的language为 zh-cn 时出现繁体中文的情况
而胡桃的实现要求非常严格，不允许出现任何的错误

> 我所说的兼容性是指一个符合v2.2规则的json文件，能不能直接被一个v2.3的解析器读取

不能，所以胡桃内置的实现中区分了 v2.2 与 v2.3 的解析方式

> 测试4已经说明了 itemtype与name不匹配并不会导致问题

v2.3 版本只读取 item_id item_type 与 name 只在 v2.2 下读取

胡桃导出的 v2.3 格式文件是同时兼容了 v2.2 的，因为大多数 其他的软件并没有支持 v2.3

**Comment by Lightczx** [comment]
只要你不提供你的json我就始终无法确认问题，这才是问题所在，希望你也能够理解

**Comment by Lightczx** [comment]
> [116172563-bak.zip](https://github.com/DGP-Studio/Snap.Hutao/files/12503452/116172563-bak.zip)
> 
> 你好，遇到同样问题

感谢你提供的文件，问题已经定位，会在后续版本修复

**Comment by Masterain98** [comment]
**恕我直言，你这个 issue 就是一份垃圾。你的主题，回复和测试都对这个问题毫无帮助。** 胡桃支持 UIGF v2.2 数据格式的导入，这个问题也跟 UIGF 版本和 item_id 没有任何关系。虽然洋洋洒洒写了一大串，但除了让人知道有导入问题以外没有任何有效信息。

出现导入问题却不在 issue 中包含原始文件，丢弃了复现问题的关键就已经使得这个 issue 变得无用。如果没有其他人的帮助，这个 issue 最终只会因缺少信息而被忽略。我也不知道 UIGF 数据格式下的祈愿记录能有什么隐私数据能让一份游戏数据文件跟真人信息挂上钩。

你所谓的测试，是基于你对必要字段的错误理解而做出的。当你的 UIGF 数据提示程序所对应的版本，那么程序就只会执行对应版本的数据解析流程，也就是读取必要资源，其它数据都只会被忽略。

**你所谓的热情，不过是在错误的道路上钻牛角尖，甚至在有人引导的情况下也不愿转变方向。**
