### ISSUE TITLE
[Bug]: Snap Hutao crash after open Game Launcher Tab

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao#883]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.3324

### Snap Hutao 版本

1.7.0.0

### 设备 ID

FA1D62A0F8737EF738814EF8F70B6208

### 问题分类

游戏启动器

### 发生了什么？

Details can be viewed at the video below.

https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/5fe5d760-5cdd-42b8-a46d-787580cb1dff

**Comment by Lightczx** [comment]
open eventvwr check any .NET Runtime error related with Snap.Hutao

**Comment by prpjzz** [comment]
Faulting application name: Snap.Hutao.exe, version: 1.0.0.0, time stamp: 0x64b07659
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3324, time stamp: 0x6967c799
Exception code: 0xc000027b
Fault offset: 0x000000000012d9b2
Faulting process id: 0x128c
Faulting application start time: 0x01d9dd84aaf74d76
Faulting application path: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.0.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 27c12e6c-98f9-4394-a940-1885a0c0de4e
Faulting package full name: 60568DGPStudio.SnapHutao_1.7.0.0_x64__ebfp3nyc27j86
Faulting package-relative application ID: App

**Comment by prpjzz** [comment]
This is the error I found by Snap Hutao in Event Viewer.

**Comment by Lightczx** [comment]
try reselect game path in settings page

**Comment by prpjzz** [comment]
It's work. Thanks for your support.

**Comment by prpjzz** [comment]
In 1.7.6, this error has reappeared. I try reselect game path, but it didn't work.

The same error appears in the Event Viewer.

Faulting application name: Snap.Hutao.exe, version: 1.0.0.0, time stamp: 0x64e841c5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3324, time stamp: 0x6967c799
Exception code: 0xc000027b
Fault offset: 0x000000000012d9b2
Faulting process id: 0x1f0c
Faulting application start time: 0x01d9f1412bcb90b6
Faulting application path: C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.6.0_x64__ebfp3nyc27j86\Snap.Hutao.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 3d4dcceb-2a02-41b0-8378-5183a700724a
Faulting package full name: 60568DGPStudio.SnapHutao_1.7.6.0_x64__ebfp3nyc27j86
Faulting package-relative application ID: App

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 FA1D62A0F8737EF738814EF8F70B6208

**Comment by Lightczx** [comment]
try set config.ini's content which next to GenshinImpact.exe 

```
other content

channel=1
sub_channel=0

other content
```

**Comment by prpjzz** [comment]
and.... It work. Leave blank or set sub_channel = 0 will fix this error.
