### ISSUE TITLE
增加以DirectX 12运行游戏的模式

### ISSUE THREAD

**Issue by qisijie** [DGP-Studio/Snap.Hutao#884]
### 背景与动机

现在原神pc端的图形API是DirectX 11,但是原神是支持DirectX 12的.希望添加一个功能,使原神以DirectX 12运行.有一些显卡对DirectX 12的支持也比DirectX 11好,米哈游用DirectX 11纯属是为了照顾Windows 7玩家.考虑到Snap.Hutao的用户至少都是Windows 10,这个功能我觉得可以有.根据我的实测DirectX 12模式确实比DirectX 11模式要流畅一些,但我不能保证这个结论的正确性,你们可以做个测试验证一下

### 想要实现或优化的功能

实现的方法很简单,利用Unity的启动参数就行,即使用"-force-d3d12"
举个例子,我直接用快捷方式启动原神本体
快捷方式的默认的"目标"参数是

"G:\miHoYo\Genshin Impact\Genshin Impact Game\YuanShen.exe"

改成

"G:\miHoYo\Genshin Impact\Genshin Impact Game\YuanShen.exe" -force-d3d12

即可以DirectX 12运行

**Comment by qisijie** [comment]
![屏幕截图 2023-09-02 190807](https://github.com/DGP-Studio/Snap.Hutao/assets/36663291/72359a87-58eb-4862-b2b7-0016ae4d2a24)
补充一句,就是在这个地方加个开关就行

**Comment by orilights** [comment]
翻了一下 [Unity 文档](https://docs.unity.cn/2019.3/Documentation/Manual/CommandLineArguments.html)， `-force-d3d12` 这个参数从 Unity 2019.3 版本开始才支持，原神是基于 Unity 2017.4 开发的，添加这个启动参数大概率是没有实际作用的

测试了一下，添加 `-force-d3d12` 参数后，软件检测到游戏依旧是使用 DX11 运行

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/61224409/55e25ea1-2923-4301-9cfd-eb4ce28523bd)

**Comment by Lightczx** [comment]
> 根据我的实测DirectX 12模式确实比DirectX 11模式要流畅一些

所以是怎么测的

**Comment by qisijie** [comment]
> 翻了一下 [Unity 文档](https://docs.unity.cn/2019.3/Documentation/Manual/CommandLineArguments.html)， `-force-d3d12` 这个参数从 Unity 2019.3 版本开始才支持，原神是基于 Unity 2017.4 开发的，添加这个启动参数大概率是没有实际作用的
> 

怎么说呢,原神用的unity版本是魔改的,官方文档不一定适用.
而且根据一些帖子,例如[米游社](https://www.miyoushe.com/ys/article/2027199),[知乎](https://www.zhihu.com/question/421353324/answer/1529634275),[知乎](
https://www.zhihu.com/question/421353324/answer/1480390965),可以得知,在2020年使用"-force-d3d12"会使游戏画面渲染出现严重的bug.说明这个参数是有作用的.现在是没有bug了

**Comment by orilights** [comment]
> > 翻了一下 [Unity 文档](https://docs.unity.cn/2019.3/Documentation/Manual/CommandLineArguments.html)， `-force-d3d12` 这个参数从 Unity 2019.3 版本开始才支持，原神是基于 Unity 2017.4 开发的，添加这个启动参数大概率是没有实际作用的
> 
> 怎么说呢,原神用的unity版本是魔改的,官方文档不一定适用. 而且根据一些帖子,例如[米游社](https://www.miyoushe.com/ys/article/2027199),[知乎](https://www.zhihu.com/question/421353324/answer/1529634275),[知乎](https://www.zhihu.com/question/421353324/answer/1480390965),可以得知,在2020年使用"-force-d3d12"会使游戏画面渲染出现严重的bug.说明这个参数是有作用的.现在是没有bug了

我翻出了电脑里的十几个 Unity 游戏进行测试（包括星穹铁道），不论游戏能不能正常运行，加上参数后微星小飞机都能检测到切换为了 DX12

但是原神加上这个参数后软件检测到的依旧是 DX11 ，而且显卡占用、显存占用、帧数与不加参数没有任何区别，其他游戏切换图形 API 这几个数值或多或少都会变化的但是原神没有

我个人倾向于不是修了 Bug，而是原神后面的版本把这个启动参数屏蔽了

我还想翻出原神 20 年的版本进行测试，可惜目前下了几个版本不知道是签名过期了还是什么问题，反作弊驱动无法加载导致游戏无法启动，暂时没办法测试

**Comment by Lightczx** [comment]
简单看一下帧数有没有实质上的提升就行

**Comment by qisijie** [comment]
啊这,我之前测是有作用的(离现在有段时间了),如果真被屏蔽那真没辙了..
