### ISSUE TITLE
[Feat]: 养成计划-材料清单-材料统计，按一定规则排序

### ISSUE THREAD

**Issue by Ar-Hyk** [DGP-Studio/Snap.Hutao#889]
### 背景与动机

长草期摆烂时，想把众角色拉倒71级，白嫖”蓝石头“。

有部分角色的突破所需要Boss掉落物是一样的，我计划先收集Boss的掉落物……
于是添加了养成计划，进行材料统计，准备逐一去找Boss们聊天

但混乱的材料统计页面让我感到无从下手
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/55748412/88b08a2b-6aa9-4cf8-9043-c6a5cf395a36)

### 想要实现或优化的功能

养成计划-材料清单-材料统计，按照原神背包里的排序顺序进行排序
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/55748412/8039005c-3a85-4ae8-b75a-bb4ed7d3bf89)

**Comment by Lightczx** [comment]
Tracked by #1394
