### ISSUE TITLE
[Bug]: 胡桃：祈愿从缓存刷新未能工作

### ISSUE THREAD

**Issue by Parsifa1** [DGP-Studio/Snap.Hutao#89]
### Windows 版本

22000.856

### Snap Hutao 版本

1.1.6.0

### 发生了什么？

<img width="1280" alt="屏幕截图 2022-10-05 213109" src="https://user-images.githubusercontent.com/31800073/194073183-4e13c021-2c78-4295-a5b0-6fc399f64113.png">
点击从缓存刷新之后并未如教程所述正常工作，弹出了一个选择文件的对话框
<img width="1280" alt="屏幕截图 2022-10-05 213127" src="https://user-images.githubusercontent.com/31800073/194073415-446c7eb9-9472-4260-8a5c-f2a4fd8dc680.png">

### 你期望发生的行为？

正常刷新祈愿记录

### 相关的崩溃日志 位于 `%HOMEPATH%/Documents/Hutao/Log.db`

```shell
未发生崩溃
```

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Parsifa1** [comment]
另：点击手动输入url后本体直接闪退

**Comment by Parsifa1** [comment]
log如上

**Comment by Masterain98** [comment]
选择`Yuanshen.exe`即可
