### ISSUE TITLE
[Feat]: 成就列表只显示未完成

### ISSUE THREAD

**Issue by Haku247** [DGP-Studio/Snap.Hutao#896]
### 背景与动机

成就列表很多100%完成的都在中间，每次看枫丹的成就都需要拉到最下边，还有一些90%+的成就很难在列表中找到。

### 想要实现或优化的功能

需要在成就页面添加一个选项 - 仅显示未完成
下方列表中筛选去掉100%的成就类别
未达到100%的类别中只显示未完成的成就

**Comment by Haku247** [comment]
成就分类和一条条成就两个都有，不过未完成的分类里，未完成成就已经自动前置了。

**Comment by Lightczx** [comment]
Tracked by #1394

**Comment by AkagiYui** [comment]
目前似乎是表现为勾选了`优先未完成`将会把`成就分类`根据完成百分比升序排列。
如果将 完成度为100%的类别 置于尾部，完成度未达到100%的类别 按照游戏内的顺序进行排列是否更好？

**Comment by qhy040404** [comment]
不好
