### ISSUE TITLE
[Feat]: 为成就添加分类

### ISSUE THREAD

**Issue by dyxa** [DGP-Studio/Snap.Hutao#897]
### 背景与动机

便于完成能马上完成的成就

### 想要实现或优化的功能

将成就分为 是否通过每日委托完成的两类（通过勾选）

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Metadata/issues/3

**Comment by Lightczx** [comment]
Tracked by #1394

**Comment by Masterain98** [comment]
@Lightczx 元数据

https://github.com/Masterain98/Genshin_Regional_Quest_Achievement_ID/blob/main/DailyQuestAchievement.json

**Comment by Mikachu2333** [comment]
感觉没能达到预期“能马上完成”。部分简易成就例如“「好烫！好烫！」”也属于“易完成”类型的，感觉可以再加一类

**Comment by Lightczx** [comment]
> 感觉没能达到预期“能马上完成”。部分简易成就例如“「好烫！好烫！」”也属于“易完成”类型的，感觉可以再加一类

不考虑
