### ISSUE TITLE
[Feat]: 双击网格视图下的项跳转到列表视图

### ISSUE THREAD

**Issue by BTMuli** [DGP-Studio/Snap.Hutao#898]
### 背景与动机

观察到诸如`成就`，`角色列表`等页面存在`列表`，`网格`两种布局

对于前者，左侧显示成就系列或角色简略，右侧显示对应的成就详情或角色详情

对于后者，仅显示简略信息，但是单击时有选中反馈，此时切换到列表布局右侧会显示网格布局下选中的内容

虽然网格布局与列表布局有一定联系，但是实际切换体验并不好

### 想要实现或优化的功能

考虑如下交互：

网格布局下，单击选中，双击切换至列表布局

**Comment by Lightczx** [comment]
由于实现了 #778, 此功能不再有积极意义
