### ISSUE TITLE
[Feat]: 希望祈愿记录的时间范围能添加回来

### ISSUE THREAD

**Issue by Avengers-Duty** [DGP-Studio/Snap.Hutao#899]
### 背景与动机

我有通过看祈愿记录的时间范围来判断最近是否刷新过记录的习惯，也可以知道自己最后一次抽卡是什么时候，算是经常会用到的功能了，现在没有了之后还得去其他祈愿导出工具里看时间，会比较麻烦

### 想要实现或优化的功能

希望能把祈愿记录总览里的抽卡时间范围添加回来。

关于UI布局的问题，在如图的位置加时间是否可以考虑一下呢？
![参考](https://github.com/DGP-Studio/Snap.Hutao/assets/69253622/d07e0470-fde8-481b-b288-7e23917d0edb)

或者像以前一样的位置把字体调小一点也行

**Comment by Lightczx** [comment]
![Image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/6e9cfd5a-0fa8-46dc-b908-71a74a6f2f39)
