### ISSUE TITLE
[Feat]: 请求在设置里添加“打开签到对话框”功能

### ISSUE THREAD

**Issue by Avengers-Duty** [DGP-Studio/Snap.Hutao#902]
### 背景与动机

当前版本的一键签到太容易触发人机验证，无感验证的接口设置门槛太高，遇到验证只能去米游社手动签到，没有之前在胡桃里手动签到方便了

### 想要实现或优化的功能

希望能在软件设置里添加“打开签到对话框”功能以便进行手动签到

**Comment by lonelyzerg** [comment]
同意，一键签到很容易失败，之前可以打开签到网页，现在只能从手机上签到了

**Comment by Lightczx** [comment]
下版本将在签到验证失败后自动打开签到网页
