### ISSUE TITLE
[Bug]: 我的角色武器详情数据错误

### ISSUE THREAD

**Issue by DawnFz** [DGP-Studio/Snap.Hutao#907]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

25941.1000

### Snap Hutao 版本

1.7.3.0

### 设备 ID

A326D483B629352F127FF61BBBD74390

### 问题分类

角色信息面板

### 发生了什么？

![623a012a038baf9a7574f10b24e1e542](https://github.com/DGP-Studio/Snap.Hutao/assets/19362176/0bf5747e-d754-4580-a9ce-7bec8cf3bdc7)
武器副词条数据错误

### 你期望发生的行为？

小数点左移两位

**Comment by Lightczx** [comment]
看上去是Enka的问题
