### ISSUE TITLE
[Feat]:建议提供胡桃账号注销渠道

### ISSUE THREAD

**Issue by mufengXD** [DGP-Studio/Snap.Hutao#908]
### 背景与动机

保护用户权利与隐私
依据《电信和互联网用户个人信息保护规定》（部令第24号）第九条第三款：  
*电信业务经营者、互联网信息服务提供者在用户终止使用电信服务或者互联网信息服务后，应当停止对用户个人信息的收集和使用，并为用户提供注销号码或者账号的服务。*

### 想要实现或优化的功能

在用户选择停止使用Snap Huato时提供注销胡桃账号的功能，以保护用户权利与隐私

**Comment by Lightczx** [comment]
虽然我们没有收集所谓的"用户的个人信息",但是提供注销渠道确实是很有必要的

**Comment by Masterain98** [comment]
> 个人信息是以电子或者其他方式记录的与已识别或者可识别的自然人有关的各种信息，不包括匿名化处理后的信息。

http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml

> Snap Hutao 的项目性质决定了其不会收集任何个人信息数据  

https://hut.ao/zh/statements/privacy-notice.html

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/Snap.Hutao/commit/fa640d27f075c15c8b4b966c00d58d9271966a1a
