### ISSUE TITLE
[Question]: Enable Auto Refresh in Administrator mode?

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao#910]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.3324

### Snap Hutao 版本

1.7.3.0

### 设备 ID

FA1D62A0F8737EF738814EF8F70B6208

### 问题分类

实时便笺

### 发生了什么？

Is there a way to enable Auto Refresh in the Realtime Notes -> Notification Settings section with Admin privileges?
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/e61b5953-55c2-4434-a21a-0680c2145678)

**Comment by Lightczx** [comment]
The auto refresh of the resin data is achieved by creating a scheduled task in windows,
If the task is created when the requesting process is elevated,
then the task will never been deleted or modified by non-elevated process,
and will return E_PERM error, thus we only allow this operation happen in non-elevated mode,
which is deletable and modifible in both mode(although we do not allow oueseleves).
