### ISSUE TITLE
[Feat]: 胡桃帐号页面

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#911]
### 背景与动机

当前胡桃帐号一栏过于简陋，操作逻辑不明确

### 想要实现或优化的功能

- 若未登录，点击后进入登录界面
- 若已登录，应显示单独的帐号管理界面，而不再是一个登录界面。管理界面可以包含以下内容：
  - 胡桃云激活状态
  - 胡桃云开发者许可证状态
  - 胡桃云过期时间
  - 兑换码使用
  - 修改密码
  - 退出登录
  - 注销账号 #908

**Comment by sanye9** [comment]
同楼主，希望再加一个账户邮箱换绑，加一个用户名功能
