### ISSUE TITLE
[Bug]: 快捷方式更改图标的方法需在每次版本更新后失效

### ISSUE THREAD

**Issue by Blackviking2024** [DGP-Studio/Snap.Hutao#912]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3324

### Snap Hutao 版本

1.7.3.0

### 问题分类

其它

### 发生了什么？

在目前提供的更改Powershell脚本的代码方法中（%ProgramFiles%\WindowsApps\60568DGPStudio.SnapHutao_1.6.6.0_x64__ebfp3nyc27j86\Snap.Hutao.exe），调用了Hutao.exe的应用图标。然而，该代码中涉及到Hutao的版本序号，例如网站上给出的1.6.6.0，这导致每次版本更新后，当版本序号发生变化时，该方法都将失效。必须手动更改上述代码中的版本号进行恢复，且需要重新将其添加至开始菜单/应用栏。

### 你期望发生的行为？

我希望能够保留以前给出的手动下载并添加Hutao图标的方法，这将会给予极大的便利

**Comment by Masterain98** [comment]
之后的版本中会提供程序内创建快捷方式的功能，当前你可以从 [https://github.com/DGP-Studio/Snap.Hutao/blob/main/src/Snap.Hutao/Snap.Hutao/Assets/Logo.ico](https://github.com/DGP-Studio/Snap.Hutao/blob/main/src/Snap.Hutao/Snap.Hutao/Assets/Logo.ico) 下载图标

**Comment by Lightczx** [comment]
fixed in https://github.com/DGP-Studio/Snap.Hutao/commit/52353b7a5a5d307e8fbc8677ffbbf965528a6f38
