### ISSUE TITLE
所以背包功能的意义是什么？

### ISSUE THREAD

**Issue by RTX310** [DGP-Studio/Snap.Hutao#914]
### 所以这个功能的意义是什么？一个一个输入吗？

https://s1.ax1x.com/2023/09/09/pPcezYn.png

### 想要实现或优化的功能

能够自动导入

**Comment by Lightczx** [comment]
导入功能确实存在但是仅限于极少一部分人使用，由于获取背包物品是高风险行为，所以我们暂时没有公开的计划
