### ISSUE TITLE
[Feat]: 关于获取背包功能

### ISSUE THREAD

**Issue by RTX310** [DGP-Studio/Snap.Hutao#915]
### 背景与动机

可不可以考虑用Amenoma试试？https://github.com/daydreaming666/Amenoma
我**感觉**不会有太大问题
因为它是扫描屏幕识别而非读取内存（开发者原话），应该会安全一些

### 想要实现或优化的功能

用Amenoma试试？

**Comment by Lightczx** [comment]
https://github.com/orgs/UIGF-org/discussions/3

**Comment by Lightczx** [comment]
需要支持UIIF格式才能导入胡桃

**Comment by RTX310** [comment]
> 需要支持UIIF格式才能导入胡桃
