### ISSUE TITLE
[Feat]: 为“筛选角色”功能添加支持模糊匹配

### ISSUE THREAD

**Issue by 2376041387** [DGP-Studio/Snap.Hutao#916]
### 背景与动机

要为多个角色创建培养计划，但是“角色资料——筛选角色”的文本框只支持全字匹配，效率较低。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52353624/18c4a1cc-c206-4336-87ce-e8ccc15744cd)

### 想要实现或优化的功能

支持模糊匹配并加入如下图所示候选栏，（如果可能的话）最好在输入法确认字符之前就显示。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/52353624/caed17c5-4403-475f-99b0-d0609f95a7f3)

**Comment by Lightczx** [comment]
批量添加角色养成项功能会在下个版本添加
