### ISSUE TITLE
[Bug]: HttpRequestException when open Character Attributes

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao#919]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19044.3324

### Snap Hutao 版本

1.7.3.0

### 设备 ID

FA1D62A0F8737EF738814EF8F70B6208

### 问题分类

玩家查询

### 发生了什么？

When open drop-down Character Attributes for character with the Data, this error is 

https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/2ff83530-676c-4b9d-87d4-a9aadb122582

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/40a564f6-e6ef-4d81-a83b-029516e7199c)

I tried using a browser and opened it to the relevant directory, but it seems there are no files on the server and they all return 404 errors as shown in the image below.
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/78275cf4-e147-43ae-ab3e-7f2de5507e3c)

**Comment by Lightczx** [comment]
I suggest you check you network settings yourself,
it's not our end.

**Comment by prpjzz** [comment]
I used a different device, a different network, but the result was the same as above.

**Comment by Masterain98** [comment]
I'm working on static network structure remodeling. It should be acceptable in one day.

**Comment by Masterain98** [comment]
@prpjzz The issue should have been fixed now.

**Comment by prpjzz** [comment]
As the picture below, there's an icon on the server, right?

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/e770c4f6-30b7-4136-937c-11e26f68c28f)

It seems that some of the icons are not loaded on my machine, possibly for some reason (in the application's notification only reports an error related to the icon of the fire element, even though I checked on the server, this icon already exists)

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/e174a5a4-191e-48be-ba8a-a66f23871a69)

**Comment by Masterain98** [comment]
For SSL connection errors, it is most likely due to an occasional network connection failure (the connection process to the server is interrupted). 

At this moment, you can try the following steps to fix this issue:
1. Open cache folder from the settings page
2. Delete all files in `ImageCache` folder
3. Reset image resource in the settings page, then Snap Hutao will restart to download image assets again
