### ISSUE TITLE
[Bug]: 出现各种闪退

### ISSUE THREAD

**Issue by Fillair19** [DGP-Studio/Snap.Hutao#920]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [x] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

19045.3324

### Snap Hutao 版本

1.7.3

### 设备 ID

9FB5CB742CB7370F97C6AB0F8A52B752

### 问题分类

安装和环境

### 发生了什么？

在获取祈愿界面中，获取到常驻祈愿最后一页时会闪退
在登录胡桃云时，重置密码确认时会闪退
已经尝试过：
删除祈愿存档
删除胡桃用户表
从Windows商店重装软件

**Comment by Lightczx** [comment]
> 在获取祈愿界面中，获取到常驻祈愿最后一页时会闪退

已知问题 #917，下版本修复

> 在登录胡桃云时，重置密码确认时会闪退

感谢反馈，会尽快通过服务器维护进行热修

**Comment by Lightczx** [comment]
从日志来看你的祈愿数据已经损坏了，可以在下版本修复后删除数据文件夹中的`userdata.db`重试

**Comment by Lightczx** [comment]
重置密码时崩溃的问题已经修复，如果还有其他问题可以追问或另开issue
