### ISSUE TITLE
想要米游社每日签到增加填写人机验证的功能

### ISSUE THREAD

**Issue by fengzhou0w0** [DGP-Studio/Snap.Hutao#922]
### Background & Motivation 背景与动机

现在点米游社的签到，经常弹出人机验证，这时候就用不了胡桃启动器的签到功能了

### Detail of the Feature 想要实现或优化的功能

想要米游社每日签到增加填写人机验证的功能，这样就能用胡桃启动器继续签到

**Comment by Lightczx** [comment]
如果是无感验证，已经在设置中给出配置入口
如果是弹出窗口手动验证，#902

**Comment by TMGyes** [comment]
> 如果是无感验证，已在设置中给出配置入口 ，如果是弹出窗口手动验证，#902

那么无感验证具体怎么配置？

**Comment by TMGyes** [comment]
> 如果是无感验证，已在设置中给出配置入口 ，如果是弹出窗口手动验证，#902

那么无感验证具体怎么配置？

**Comment by Lightczx** [comment]
[广告](https://buy.microgg.cn)

**Comment by TMGyes** [comment]
> [广告](https://buy.microgg.cn)

我想用自己的极验账号来配置无感验证，如果配置的过程很麻烦就算了

**Comment by Masterain98** [comment]
> 我想用自己的极验账号来配置无感验证，如果配置的过程很麻烦就算了

程序内已经提供了参数技术细节描述，如果你有能力的话自己设计服务端并填入即可
