### ISSUE TITLE
[Feat]: 关于安装Segoe Fluent Icons的一些建议

### ISSUE THREAD

**Issue by Alex134003** [DGP-Studio/Snap.Hutao#926]
### Background & Motivation 背景与动机

我在Win11系统上使用Hutao时，在系统能正确显示Segoe Fluent Icons的情况下安装了字体。由于微软官网给出的字体版本较低，安装之后导致系统部分图标显示异常。虽然对Hutao的使用没有影响，但是会影响用户的正常使用。我写了一篇博客记录了详细信息和解决方法：https://blog.csdn.net/weixin_43863644/article/details/132873600。

### Detail of the Feature 想要实现或优化的功能

希望能在导航界面中安装Segoe Fluent Icons的地方添加提示，说明下载的字体版本为旧版本，Win11用户和图标显示正常的用户无需另外下载安装字体。

**Comment by Alex134003** [comment]
访问链接的时候需要把。去掉，否则打不开。。。

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/a61ba440-73f8-439a-b337-f1ff4ed2ec9a)
我觉得写的很清楚
