### ISSUE TITLE
[Feat]: Image Asset Optimzation

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#927]
### Background & Motivation 背景与动机

- [x] Property image assets cannot be reset by `Reset Image Resource` in the settings page
- [x] Property does not have a zip package for the initial download process
- [x] Make a CRIT DMG picture

We also need to check if any other image resources have the same issue

### Detail of the Feature 想要实现或优化的功能

Need work on both Snap.Hutao and Snap.Static

**Comment by Masterain98** [comment]
#919

**Comment by prpjzz** [comment]
In my opinion, it should be as in the picture below. Or, like in the game, only the Crit Rate's image will be displayed, and Crit DMG will be blank.
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/89702898/8302ed79-5df2-4afa-b570-b30feba6fe6f)

**Comment by Masterain98** [comment]
Realized in 1.7.6
