### ISSUE TITLE
[Bug]: 1.7.4.0【主页卡片-启动游戏】无法切换账号

### ISSUE THREAD

**Issue by XY-admain** [DGP-Studio/Snap.Hutao#931]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.4.0

### 问题分类

游戏启动器

### 发生了什么？

1、游戏路径或许存在识别错误。在非管理员模式下不能更改。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72969012/4b914809-d7d5-4a42-8bf7-35b33d644146)
2、通过工具——>启动游戏界面可以正常使用。但是主页选择账号处没有显示，也就是说，在绑定账号的情况下，不能在主页选择账号然后登录。
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/72969012/64018ee1-4a59-463f-95ea-6b657c22beac)

### 你期望发生的行为？

可以正常在首页选择账号登录。

**Comment by Lightczx** [comment]
#924
