### ISSUE TITLE
[Bug]: 成就状态无法置为未达成

### ISSUE THREAD

**Issue by xdianrdna** [DGP-Studio/Snap.Hutao#932]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2134

### Snap Hutao 版本

1.7.4.0

### 设备 ID

640C59DF278A923D861FC190DD53BB2C

### 问题分类

成就管理

### 发生了什么？

1. 在成就管理页将「西风佑我」（或其他成就）由「达成」置为「未达成」。
2. 点击主页。
3. 回到成就管理页，发现「西风佑我」依然为「达成」状态。

### 你期望发生的行为？

可以正确地取消成就达成标记。

**Comment by Lightczx** [comment]
已知问题，下版本修复
