### ISSUE TITLE
[Bug]: 无法创建新的成就文档

### ISSUE THREAD

**Issue by Guest-Liang** [DGP-Studio/Snap.Hutao#933]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.4.0

### 设备 ID

908AE36E00746998FB6C0FB50CE989AC

### 问题分类

成就管理

### 发生了什么？

电脑重装系统之后，通过应用商店重新下载了胡桃工具箱，试图创建新的成就存档时，输入名称一直提示“不能添加名称无效的存档”，包括留空也会提示不能添加
![QQ截图20230917092916](https://github.com/DGP-Studio/Snap.Hutao/assets/47164120/075ec0da-ba78-4065-9e7d-91189552f821)

### 你期望发生的行为？

应当成功创建新的成就存档

**Comment by Guest-Liang** [comment]
我尝试使用管理员身份运行，仍然是同样的结果

**Comment by Masterain98** [comment]
具体描述添加流程

**Comment by Guest-Liang** [comment]
在开始菜单中以管理员身份启动胡桃----左侧导航栏选择“成就管理”----点击创建新存档----输入“20230916”失败----输入“存档new”失败----输入“achievement”失败

**Comment by Lightczx** [comment]
不要按回车

**Comment by Lightczx** [comment]
无法复现，输入名称完成后点一下背景区域再点确定呢

**Comment by Guest-Liang** [comment]
> 无法复现，输入名称完成后点一下背景区域再点确定呢

刚才看到上一条，输入“存档”使用鼠标点击来创建存档，现在成功创建了

**Comment by Guest-Liang** [comment]
> > 无法复现，输入名称完成后点一下背景区域再点确定呢
> 
> 刚才看到上一条，输入“存档”使用鼠标点击来创建存档，现在成功创建了

使用鼠标点击确认按钮就可以成功创建，输入名称结束后按回车键就无法创建

**Comment by Lightczx** [comment]
回车有时无法正常工作，只有某些情况下可以这么做
