### ISSUE TITLE
[Bug]: 切换语言会导致已关闭的公告重新被获取

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#934]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

Windows 10 22H2

### Snap Hutao 版本

1.7.4

### 问题分类

用户界面

### 发生了什么？

切换客户端语言后会导致已关闭的公告重新被显示出来并导致刷屏
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/48af456e-0c5c-4e38-b1f2-c648138af879)

### 你期望发生的行为？

- 公告关闭标记不应在切换语言后被重置
- 增加公告过期时间字段，而不是固定时间（或许还可以设计为某版本之后不显示）

**Comment by Lightczx** [comment]
设计如此，不同语言不共享Id
