### ISSUE TITLE
[Bug]: 首页启动游戏小方框内无法选择账号启动游戏

### ISSUE THREAD

**Issue by retaker** [DGP-Studio/Snap.Hutao#936]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.4.0

### 设备 ID

C0F4530068C9437487873404D3A9FE4A

### 问题分类

游戏启动器

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/3334662/974d075f-e9e8-4e2a-a590-33b3223ba0c6)
点击首页中的启动游戏处的账号选择下拉列表时无法正常显示账号列表。

通过左侧的启动游戏页面选择账号启动游戏是可以正常启动的

### 你期望发生的行为？

能够选择预设的账号并正常启动游戏

**Comment by Masterain98** [comment]
Duplicate of #924
