### ISSUE TITLE
安装失败提示缺少应用包

### ISSUE THREAD

**Issue by xuewei233** [DGP-Studio/Snap.Hutao#94]
### Windows 版本

22621.608

### Snap Hutao 版本

1.1.7.0

### 发生了什么？

应用安装程序无法安装应用包相关项。请向开发人员索要 Microsoft.WindowsAppRuntime.1.2-preview2 应用包。

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
@Masterain98 issue template 加个文档的链接？

**Comment by Masterain98** [comment]
> @Masterain98 issue template 加个文档的链接？

你尝试一下开 Issue 的流程，是有的
