### ISSUE TITLE
[Bug]无法切换B服

### ISSUE THREAD

**Issue by YouYouLip** [DGP-Studio/Snap.Hutao#940]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

Windows 11 版本 22H2(0S 内部版本 22621.2283)

### Snap Hutao 版本

1.7.4.0

### 设备 ID

3E95CF7E08D3EA1E8340FF177338F865

### 问题分类

游戏启动器

### 发生了什么？

在切换渠道服服务器切换后进行启动并非渠道服，而是无TapTap启动或官方服|Default的界面
渠道服理应来说应该是B服，但显示的并非B服

**Comment by Lightczx** [comment]
启动时有弹出一个短暂的对话框么

**Comment by YouYouLip** [comment]
> 启动时有弹出一个短暂的对话框么

![25091152f2c1609047927ea15868e3da](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/1517aee5-28f8-4be0-8861-d94270d90325)

**Comment by YouYouLip** [comment]
> > 启动时有弹出一个短暂的对话框么
> 
> ![25091152f2c1609047927ea15868e3da](https://user-images.githubusercontent.com/119958263/268671551-1517aee5-28f8-4be0-8861-d94270d90325.png)

仅仅只有这个对话框，看了一下介绍里面的评论，有人和我一样

**Comment by Lightczx** [comment]
从哪个选项切换到的渠道服

**Comment by YouYouLip** [comment]
> 从哪个选项切换到的渠道服

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/a262a495-4852-4ff6-9cb2-27f2bea3f73d)

**Comment by Lightczx** [comment]
你的游戏路径是什么

**Comment by YouYouLip** [comment]
> 你的游戏路径是什么

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/c249c971-eada-4479-b6a7-150d9e50d527)

**Comment by YouYouLip** [comment]
> 你的游戏路径是什么

之前一直好使 大概是这次更新后就失效了，应该是这2个星期内

**Comment by Lightczx** [comment]
检查一下 `YuanShen_Data\Plugins` 下是否存在 `PCGameSDK.dll.backup`

**Comment by YouYouLip** [comment]
D:\Genshin Impact\Genshin Impact Game下的yuanshen_data\plugin和Hutao\ServerCache\Chinese\YuanShen_Data\Plugins下有
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/d878c5e0-f396-4aa7-af84-f39322b03ce1)
但是Hutao\ServerCache\YuanShen_Data下面的文件夹均没有PCGameSDK.dll.backup

**Comment by Lightczx** [comment]
ServerCache在渠道服官服转换下本就不会用到

**Comment by YouYouLip** [comment]
> ServerCache在渠道服官服转换下本就不会用到

既然文件都不缺那会是什么问题呢，也有其他人复现了这个问题
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/163534ea-0958-40bc-992e-f847b3d93a95)

**Comment by Lightczx** [comment]
在浏览器里打开[链接](https://sdk-static.mihoyo.com/hk4e_cn/mdk/launcher/api/resource?key=KAtdSsoQ&launcher_id=17&channel_id=14&sub_channel_id=0)

查找一下是否有以下内容

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/a6f1178a-d4bd-427f-9662-b43d5fb7ffea)

**Comment by YouYouLip** [comment]
> 在浏览器里打开[链接](https://sdk-static.mihoyo.com/hk4e_cn/mdk/launcher/api/resource?key=KAtdSsoQ&launcher_id=17&channel_id=14&sub_channel_id=0)
> 
> 查找一下是否有以下内容
> 
> ![image](https://user-images.githubusercontent.com/36357191/268679826-a6f1178a-d4bd-427f-9662-b43d5fb7ffea.png)

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/7d8642b9-1ff3-4208-8cae-6538823ee0d9)
有以下内容

**Comment by Lightczx** [comment]
很奇怪
我自己测试时，切换到渠道服是会重命名文件的
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/8e684050-8309-48d0-bd9d-ed607a0ef81e)

**Comment by YouYouLip** [comment]
> 很奇怪 我自己测试时，切换到渠道服是会重命名文件的 ![image](https://user-images.githubusercontent.com/36357191/268681671-8e684050-8309-48d0-bd9d-ed607a0ef81e.png)

我也测试了一遍 盯着本体游戏Plugin目录下 也是会重命名，并且当没有文件时也会重新生成PCGameSDK.dll文件

**Comment by YouYouLip** [comment]
> > 很奇怪 我自己测试时，切换到渠道服是会重命名文件的 ![image](https://user-images.githubusercontent.com/36357191/268681671-8e684050-8309-48d0-bd9d-ed607a0ef81e.png)
> 
> 我也测试了一遍 盯着本体游戏Plugin目录下 也是会重命名，并且当没有文件时也会重新生成PCGameSDK.dll文件

重新生成的文件再切换回官方服也是会改成PCGameSDK.dll.backup

**Comment by Lightczx** [comment]
既然重命名了理论上进游戏应该就是渠道服的

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/80d6c4c9-3200-48a2-b227-6ca85ba79340)
我自己测试是完全没问题的

是否有使用过其他的第三方软件

**Comment by YouYouLip** [comment]
> ![image](https://user-images.githubusercontent.com/36357191/268684140-80d6c4c9-3200-48a2-b227-6ca85ba79340.png) 我自己测试是完全没问题的
> 
> 是否有使用过其他的第三方软件

被我误打误撞解开了（雾）首先就是我没用过其他第三方软件，因为之前这个假b服显示的是官服界面嘛，我就尝试扫码登录了，结果显示了二级地址解析错误？然后下面有个错误代码我忘了，这次我尝试输入了账号密码，然后出现了该报错
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/24dab1d9-a11f-4839-8c57-4f9d6691c15a)
出现完这个报错后，我再点开账号界面就显示b服的了
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/e2c595b6-6591-4e93-be64-79b661238021)

**Comment by YouYouLip** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/10bd879f-3aa3-428d-acdc-a077394ef0f0)

**Comment by YouYouLip** [comment]
但实际上输入账号密码后会显示系统错误，请重试
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/119958263/911e8f62-2e1a-4e34-9007-e2dd841616e2)

**Comment by YouYouLip** [comment]
解决了，显示上面图片的时候登录会显示系统错误，请重试，重新启动后便正常显示界面了，也是正常的b服，所以大概和我出现这个情况的人应该都和我一样，切换渠道服的时候套了个官服皮，扫码会显示二级地址解析错误是因为b服没有扫码而导致无法识别，如果账号密码则会立刻识别出渠道不懂，但是实际上在这之前我也测试过输入账号密码，会显示账号密码错误或者新设备验证码，这次是出现了渠道错误的报错（胡言乱语）

**Comment by Lightczx** [comment]
桌面端似乎是不能扫码的，必须填B站弹出的独立窗口的账号密码
