### ISSUE TITLE
胡桃无法运行，无论是不是管理员权限

### ISSUE THREAD

**Issue by essarely** [DGP-Studio/Snap.Hutao#946]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.4.0

### 设备 ID

610E1D4024B4A265D3BACB2F7CDCB50A

### 问题分类

游戏启动器

### 发生了什么？

打开就自动闪退，无论是不是管理员权限
<img width="758" alt="97e812d42e1bc65f720e964faff87ab0" src="https://github.com/DGP-Studio/Snap.Hutao/assets/138873890/8ba69568-fb28-49eb-83da-f08932899703">
<img width="758" alt="adc7d9c46f94596eb7f3c52e9310e058" src="https://github.com/DGP-Studio/Snap.Hutao/assets/138873890/cdcc372a-8e82-4770-bf9b-579f7a6941b7">
无安装任何新软件，电脑状态不变，某天早上开机就这样了。且重启无用，snap hutao重下无用

**Comment by essarely** [comment]
已更新至1.7.5.0版本。问题依旧

**Comment by essarely** [comment]
补充，能正常安装，也就是安装引导页面一切正常，而进主页面就卡死闪退，稳定触发，也就是完全用不了的状态

**Comment by Lightczx** [comment]
userdata.db删了
你的祈愿记录里面有无效的物品

**Comment by essarely** [comment]
> userdata.db删了 你的祈愿记录里面有无效的物品
能更详细的说明下如何操作吗

**Comment by Lightczx** [comment]
你有移动过数据文件夹么

**Comment by essarely** [comment]
感谢楼上回复，问题已解决，祈愿记录是很久之前将提瓦特小助手的json导入胡桃，导入后胡桃祈愿页面直接崩溃，但转服以及高级功能仍能正常使用，就没再管过，结果现在突然导致崩溃，
另外是趁着胡桃打开瞬间没崩溃才找到userdata.db的位置的

**Comment by essarely** [comment]
数据文件夹没动过，默认在《文档》文件夹内，（这是卡着没崩溃的时间从应用跳转过去找到的）另外，问题已解决，再次感谢回复
