### ISSUE TITLE
属性统计功能下可否添加数据保存功能

### ISSUE THREAD

**Issue by YSC-yes** [DGP-Studio/Snap.Hutao#95]
### 你想要实现或优化的功能？

1、一个账号只能搜索8个角色的装备圣遗物面板等，那么可否设定一个保存功能，可以让我们分批将自己账号下的所有角色的数据都存下来。
2、可否像Snap.Ginshin中的祈愿记录那样，分帐号保存数据。
3、保存功能可以设定为可选项，即可以检索他人，然后观看角色橱窗，若不想保存数据可以不保存，防止搜索过多占用内存？

**Comment by Lightczx** [comment]
刷新按钮
