### ISSUE TITLE
[Feat]: 添加 YaeAcheivement

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#950]
### Background & Motivation 背景与动机

增强成就管理功能

### Detail of the Feature 想要实现或优化的功能

- 用户可以通过胡桃**自动地**下载并运行 YaeAchievement 并将数据导入胡桃
- 胡桃需要在本地缓存版本 tag
- 胡桃需要判断 .NET 7 Desktop Runtime 环境是否安装
  - 或者需要在点击运行 YaeAchievement 后提示用户若未启动需要安装该环境，并提供超链接

**Comment by Masterain98** [comment]
https://yae-api.snapgenshin.com

```json
{
  "tagName": "3.1.0",
  "url": "https://github.com/HolographicHat/YaeAchievement/releases/download/3.1.0/YaeAchievement.exe",
  "source": "github",
  "frameworkUrl": "https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.11-windows-x64-installer"
}
```

**Comment by Lightczx** [comment]
Tracked by #1394

**Comment by Masterain98** [comment]
在成就管理功能菜单中增加一个跳转到 Yae release 页面的按钮也会很方便
