### ISSUE TITLE
[Bug]: 无法切换服务器，时好时坏

### ISSUE THREAD

**Issue by LBW11451419** [DGP-Studio/Snap.Hutao#951]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22261.2283

### Snap Hutao 版本

1.7.5.0

### 设备 ID

01CBDE72E476062BD55F299B61A0C8D8

### 问题分类

游戏启动器

### 发生了什么？

点开工具栏的启动游戏，弹出界面，过一会闪退

### 你期望发生的行为？

弹出界面，可以切换和启动原神

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
国际服？

**Comment by LBW11451419** [comment]
是的

**Comment by Lightczx** [comment]
不使用胡桃能直接打开国际服么

**Comment by 1235789gzy1** [comment]
转换服务器失败的时候，可以提供游戏路径下 config.ini 中的内容和您想转换的服务器渠道

**Comment by LBW11451419** [comment]
[General]
uapc=f990761e5a50
config.ini里的内容只有这个 
我前天把国服的文件粘贴进去又可以玩国服了
不过胡桃里面的启动游戏界面一打开就闪退

**Comment by Lightczx** [comment]
闪退需要提供设备Id

**Comment by vsncn** [comment]
同样问题
应该是账号登录时造成的闪退
切换服务器后，如果没有保存该服务器账号，则会一直闪退
如果保存了该服务器账号，则选择该账号后，闪退一次，之后不切换账号就不会再闪退了
如果切换相同服务器账号，则会在闪退一次后正常进入该账号

**Comment by Lightczx** [comment]
> 闪退需要提供设备Id

提供设备Id

**Comment by vsncn** [comment]
> > 闪退需要提供设备Id
> 
> 提供设备Id

9F411B0B1A43C69A23A87C5E24C90685

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 9F411B0B1A43C69A23A87C5E24C90685

**Comment by LBW11451419** [comment]
01CBDE72E476062BD55F299B61A0C8D8我的设备id

**Comment by LBW11451419** [comment]
01CBDE72E476062BD55F299B61A0C8D8我的设备id

**Comment by LBW11451419** [comment]
01CBDE72E476062BD55F299B61A0C8D8我的设备id

**Comment by Lightczx** [comment]
@dgp-bot 拉取日志 01CBDE72E476062BD55F299B61A0C8D8

**Comment by Lightczx** [comment]
#883

**Comment by Rock-46** [comment]
从国服切换到国际服的时候是没有问题的，但是我有一次从国际服切回国服的时候，就会弹出"403"网络问题的报错，我查看了一下config.ini，它还是国际服配置，没有被改为国服配置，也就是说是配置文件没有被正确修改，理论上是程序问题，它没有修改后的验证行为

并且我还发现了个问题：当服务端与config.ini文件无法对应时，胡桃启动器点击左侧“启动游戏”就会出现闪退问题（比如游戏文件为国际服，但config.ini是国服配置文件就会出现这样的问题）

**Comment by Lightczx** [comment]
1.7.7修复了这个问题
