### ISSUE TITLE
[ENG][Bug]: Search interface exception

### ISSUE THREAD

**Issue by moyanj** [DGP-Studio/Snap.Hutao#952]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [fixed issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D), and it's not a duplicated issue

### Windows Version

Windows11 21H2 22000.795

### Snap Hutao Version

1.7.5.0

### Issue Category

User Interface

### What Happened?

The search box in the character wiki does not match what is displayed.（角色wiki中的搜索框搜到的与显示的不一样）:
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/88998238/c10d4aa7-6c0d-4e68-a086-e7b67d14d615)
I tried my previous operation (first searching for a word, then clearing the search bar, entering, and then searching for the full name), but couldn't successfully reproduce it?（我尝试了我之前的操作（先搜索一个字，然后清空搜索栏，回车，再搜索全名），但无法成功复现？）

### What is expected?

I hope to find the cause of this strange problem and fix it（希望找到发生此奇怪问题的原因，并且修复他）

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by Lightczx** [comment]
close as a occasional problem
