### ISSUE TITLE
[Bug]: 提瓦特小助手导出JSON文件在胡桃导出出现异常

### ISSUE THREAD

**Issue by ass-i-xh** [DGP-Studio/Snap.Hutao#953]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.5.0

### 设备 ID

AAC4E8C096794BBE03E069CE00A9AA23

### 问题分类

祈愿记录

### 发生了什么？

在提瓦特小助手导出json文件在胡桃导出出现不可导出的情况
uid:210842887
URL:[https://hk4e-api.mihoyo.com/event/gacha_info/api/getGachaLog?win_mode=fullscreen&authkey_ver=1&sign_type=2&auth_appid=webview_gacha&init_type=301&gacha_id=b4ac24d133739b7b1d55173f30ccf980e0b73fc1&lang=zh-cn&device_type=mobile&game_version=CNRELiOS3.0.0_R10283122_S10446836_D10316937&plat_type=ios&game_biz=hk4e_cn&size=20&authkey=6JFMf1wwfN7neBFN0TqdlkMcV9Kgu478bwLYvuIH5W3APVEb9%2B2i137SA93jU8CWwU5ZeC5UejhEhFONyXsIJqQV2gWLAqgnsa5zjjy0KbIZDNRLpnqRqtXIrX7a4rNmA8GkBUvCD4Usc2L2w0ivA3J1n39vPib6ho%2FmGH4knBRQMeYfi83wCNDWQ8pnVABOarGHNVqsofrHL2CMTa6Z3xjA7Fwx87lx%2FFJM5GGbjCZNlZYOS1yAmMkYG0U6DV%2F9bl9XMfEuObK436xUDiaIb9XQ75LlAyebXdC8nTeIVZM2qQyPZYGbN59SOxm2UkFvzEWUoet8j4FabWLSZkYBug%3D%3D&region=cn_gf01&timestamp=1664481732&gacha_type=200&page=1&end_id=0](url)
JSON文件[https://wwp.lanzoup.com/iVZ7S19lgshi](url)
应用内截图：
提瓦特小助手:
![new ducument](https://github.com/DGP-Studio/Snap.Hutao/assets/90611619/6eddc2bf-007b-481a-b5f0-2eeeb825fc6e)
胡桃：
<img width="891" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/90611619/8ce8af6c-3235-445a-bd9a-cc611165ff05">
<img width="891" alt="image" src="https://github.com/DGP-Studio/Snap.Hutao/assets/90611619/557d7ee0-a59f-4b9b-862a-67a927c6dbc7">

### 你期望发生的行为？

在提瓦特小助手内导出能在胡桃内导入

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
这个问题不应该找胡桃，而是找你的小助手去，他们导出了非法的数据。

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/43c7a9c8-d46f-4542-b787-89e056bdd369)
明显小助手问题
