### ISSUE TITLE
国际服获取Stoken后无法使工具箱功能请修复

### ISSUE THREAD

**Issue by sheaahhoi1** [DGP-Studio/Snap.Hutao#954]
### Background & Motivation 背景与动机

我在Q群中取得了国际服获取Stoken办法的apk,
[全服(包含国际服)获取Ck或Stoken_3.3.1_release.zip](https://github.com/DGP-Studio/Snap.Hutao/files/12707667/Ck.Stoken_3.3.1_release.zip)

获取讯息如下
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10239384/98413790-4889-4c46-8bc5-d7e7bc0a4aa1)
成功导入工具箱
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10239384/8564c481-9725-48fc-ba20-3fc412fcdc9f)

但是签到功能&祈愿导入不支援(无效)hoyolab,请求修正

### Detail of the Feature 想要实现或优化的功能

但是签到功能&祈愿导入不支援(无效)hoyolab,请求修正
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10239384/19fb9834-5dc6-4f4e-af72-5cf7d2bfd6c2)

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10239384/7daa54ed-8ca4-4186-b2a3-083931f4b75b)

**Comment by Lightczx** [comment]
祈愿记录本就无法支持，签到功能需要社区贡献相关逻辑
