### ISSUE TITLE
請求支援從Genshin-Wish-Export工具的json文件導入祈願記錄

### ISSUE THREAD

**Issue by sheaahhoi1** [DGP-Studio/Snap.Hutao#955]
### Background & Motivation 背景与动机

請求支援從Genshin-Wish-Export工具的json文件導入祈願記錄

[https://github.com/biuuu/genshin-wish-export](url)

我發現導入徵信小助手記錄是可行,但是從Genshin-Wish-Export的json文件導入胡桃工具箱就會在處理過程中崩溃

查看文件兩者文件格式是不一樣,但擁有相同關鍵訊息

### Detail of the Feature 想要实现或优化的功能

請求支援從Genshin-Wish-Export工具的json文件導入祈願記錄

Genshin-Wish-Export工具的json文件位置
Genshin-Wish-Export\userData

文件名稱:
gacha-list-[UID號].json

json文件記錄示範
[gacha-list-820105753 - 示範.zip](https://github.com/DGP-Studio/Snap.Hutao/files/12707707/gacha-list-820105753.-.zip)

**Comment by Lightczx** [comment]
点开他的设置，找到导出UIGF文件，用那个
