### ISSUE TITLE
[Feat]: 换服不启动游戏

### ISSUE THREAD

**Issue by streesobrs** [DGP-Studio/Snap.Hutao#957]
### Background & Motivation 背景与动机

现在换服只能点启动游戏才能换起

### Detail of the Feature 想要实现或优化的功能

单独的切换服务器，而不是切换须要启动游戏才行

**Comment by Lightczx** [comment]
为什么换完了不启动，你要在切换完了之后做什么

**Comment by streesobrs** [comment]
换完之后用的starward启动来记录时间

**Comment by Lightczx** [comment]
#216

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md#%E8%BD%AC%E6%8D%A2%E6%B8%B8%E6%88%8F%E5%AE%A2%E6%88%B7%E7%AB%AF

![v2-ea513c3f88882a1ebe13393009479a98_720w](https://github.com/DGP-Studio/Snap.Hutao/assets/61003590/116f10ca-d2cb-4912-95f9-cc32afc37d75)
