### ISSUE TITLE
[Bug]: 属性面板缺少词条

### ISSUE THREAD

**Issue by YSC-yes** [DGP-Studio/Snap.Hutao#96]
### Windows 版本

22623.730

### Snap Hutao 版本

1.1.8.0

### 发生了什么？

属性统计中优菈的面板只有冰元素伤害加成，雷泽等还未测试
![image](https://user-images.githubusercontent.com/81900755/194700882-f1f21675-1a87-4079-96ee-fd2875142580.png)

### 你期望发生的行为？

优菈这类物理角色额外加一行物理伤害加成显示

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Lightczx** [comment]
fixed-internally
