### ISSUE TITLE
[Bug]: 深境螺旋分頁點開後直接Crash

### ISSUE THREAD

**Issue by twinklevania** [DGP-Studio/Snap.Hutao#960]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.5.0

### 设备 ID

71A9C779E4DA4D7663995BE7D548AC3D

### 问题分类

其它

### 发生了什么？

國際服-亞服
1.使用啟動遊戲分頁，按檢測帳號按紐；未能偵測已登入遊戲內帳號
2.胡桃介面設為繁體，首頁分頁往下捲動未顯示活動公告及遊戲公告內容
*3.未登入Hoyoverse之前，點按深境螺旋分頁；還能查看本期統計
而登入之後，僅是在深境螺旋->分期詳情分頁就會讓程式Crash

### 你期望发生的行为？

希望修正以上問題
第一次使用github，希望步驟和格式沒有錯
感謝辛苦的開發人員

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/8e80bf1b-1ad5-492d-bf9e-7e65ca7fa1c6)
