### ISSUE TITLE
[Feat]: 关于胡桃的自动连点功能

### ISSUE THREAD

**Issue by RekiAriel** [DGP-Studio/Snap.Hutao#961]
### Background & Motivation 背景与动机

胡桃更新的自动连点占用了F8快捷键

### Detail of the Feature 想要实现或优化的功能

希望能有关闭自动连点功能的选项和自定义快捷键的功能

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/1758b237-15f4-4bf2-ac84-986d8b294d46)
而且占着右上角空间，丑爆了

**Comment by xueshanqiu** [comment]
https://github.com/phonowell/genshin-impact-script
这个项目功能强大，可以参考

**Comment by Lightczx** [comment]
- [ ] 禁用后需要隐藏标题栏按钮

**Comment by twjmy** [comment]
回坑活动预设使用F8，不在F5内，就挺难受
