### ISSUE TITLE
[Bug]: 管理员模式下启动无法唤起游戏路径选择对话框

### ISSUE THREAD

**Issue by DawnFz** [DGP-Studio/Snap.Hutao#962]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

25951.1010

### Snap Hutao 版本

1.7.6.0

### 设备 ID

A326D483B629352F127FF61BBBD74390

### 问题分类

安装和环境

### 发生了什么？

![QQ截图20230926225539](https://github.com/DGP-Studio/Snap.Hutao/assets/19362176/25b70c40-c515-4556-b281-029813a43858)
![QQ截图20230926225600](https://github.com/DGP-Studio/Snap.Hutao/assets/19362176/d187b954-560f-4bba-8632-457d9bd80acc)
如图一，管理员模式下启动Hutao点击红框框选部分无法唤出图二（非管理员启动）中红框框选部分的对话框

### 你期望发生的行为？

管理员模式启动及非管理员模式启动均可唤出路径选择对话框

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
WinUI 问题
