### ISSUE TITLE
关于签到功能

### ISSUE THREAD

**Issue by nine1309** [DGP-Studio/Snap.Hutao#963]
### Background & Motivation 背景与动机

现在使用自动签到必定会出发验证失败的提示，只能手动签到

### Detail of the Feature 想要实现或优化的功能

可否将之前的签到方式更换回来呢？

**Comment by Masterain98** [comment]
Duplicate of #902

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/e272f1d4-57f4-4956-a9cb-6d259cc54697)

**Comment by Masterain98** [comment]
Duplicate of #902
