### ISSUE TITLE
[Feat]:从其它祈愿导出程序导入祈愿数据 

### ISSUE THREAD

**Issue by Curlytc** [DGP-Studio/Snap.Hutao#966]
### Background & Motivation 背景与动机

希望胡桃工具箱支持导入更多数据格式的祈愿记录数据，例：excel
部分祈愿记录数据超过半年而无法获取，只保存在“非小酋”，导出的祈愿记录数据文件为excel
附链接：https://feixiaoqiu.com/rank_list/

### Detail of the Feature 想要实现或优化的功能

希望同UIGF 数据格式 一般，可以做到：
启动胡桃工具箱，从左侧菜单栏进入祈愿记录
点击右上角的导入
选择你的 excel数据文件
根据界面确认导入数据

**Comment by Masterain98** [comment]
那你找他们去，找我们没用。所有支持UIGF格式的程序都是主动兼容的。

**Comment by Masterain98** [comment]
另外非小酋数据不完整，他们只存五星数据。数据完整性已经不符合UIGF要求了。
