### ISSUE TITLE
最新版本1.7.6程序崩溃

### ISSUE THREAD

**Issue by milkbing** [DGP-Studio/Snap.Hutao#968]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22H2 19045.2728

### Snap Hutao 版本

1.7.6

### 问题分类

其它

### 发生了什么？

通过Github文件下载更新后，提示更新资源文件完成，最后打开程序就会崩溃；
尝试卸载重新在应用商店安装，问题仍然存在；
环境和胡桃需要下载的图片资源都可以正常下载完毕，但是打开程序会崩溃；
管理员模式也是崩溃

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by milkbing** [comment]
补充1：安装1.7.4版本程序正常，1.7.5版本更新时，我也安装过，但是该版本点击启动游戏就直接崩溃。

补充2：我重新安装1.7.6版本后，并没有之前的协议（需要我打√的东西）和前面环境检测之类的，而是直接跳转到资源的下载。

补充3：我的设备ID（1.7.4版本上显示的）：E3F4AF52CD93A85EA36E39DC03BB9F82

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/773fd5e3-dca9-4a43-ae67-4238d795f7fa)

**Comment by Masterain98** [comment]
@dgp-bot 拉取日志 E3F4AF52CD93A85EA36E39DC03BB9F82

**Comment by Masterain98** [comment]
尝试将目录数据下的 `userdata.db` 删除，看能不能启动

删除前记得做备份

**Comment by milkbing** [comment]
userdata.db 删除后成功启动，粗略检查应该没有问题了，感谢大佬的解答。

**Comment by milkbing** [comment]
补充：userdata.db，备份并替换后就会出现崩溃，我已经删除原userdata文件，重新添加账号信息。
