### ISSUE TITLE
[Bug]: 抽卡记录导入时崩溃

### ISSUE THREAD

**Issue by SmaragdineTablet** [DGP-Studio/Snap.Hutao#969]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.6.0

### 设备 ID

CC3C72302E919528D002A33814BCD35A

### 问题分类

祈愿记录

### 发生了什么？

由非小酋导出excel后，经由genshin-gacha-analyzer及genshin wish export导出为json文件，但工具箱无法正常识别，且在识别过程中崩溃。

### 你期望发生的行为？

正常识别此json文件

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Masterain98** [comment]
> 正常识别此json文件
> [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**此json文件**在哪呢？

**Comment by SmaragdineTablet** [comment]
[原神抽卡记录.zip](https://github.com/DGP-Studio/Snap.Hutao/files/12756116/default.zip)

**Comment by Masterain98** [comment]
没有有效的 UIGF 数据文件

**Comment by SmaragdineTablet** [comment]
那么以这三份文件为基础，有办法转换为有效的UIGF数据吗？

**Comment by Masterain98** [comment]
三份都不是 UIGF 数据格式

genshin wish export 肯定是可以导入的，但你应该是搞错了方法

**Comment by SmaragdineTablet** [comment]
找到盲点了，此json还要再次被genshin wish export的抽卡记录恢复，并再次导出由genshin wish export为UIGF
