### ISSUE TITLE
[Bug]: 安装失败

### ISSUE THREAD

**Issue by SmallYii** [DGP-Studio/Snap.Hutao#97]
### Windows 版本

Windows10 21H1 19043.2006

### Snap Hutao 版本

1.1.8.0

### 发生了什么？

更新安装失败
应用安装程序无法安装应用包相关项。请向开发人员索要 Microsoft.WindowsAppRuntime.1.2-preview2 应用包。
![image](https://user-images.githubusercontent.com/112681916/194705375-64b7f405-a7ad-457a-bb5a-2aaf3273fd67.png)

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认该问题是一个新问题，没有其他人已经提出相同的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by Masterain98** [comment]
RTFM
