### ISSUE TITLE
成就页面天地万象中的“最终枫达海”重复出现了三次

### ISSUE THREAD

**Issue by mengxiliyu** [DGP-Studio/Snap.Hutao#970]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

25951.1010

### Snap Hutao 版本

1.7.6.0

### 问题分类

成就管理

### 发生了什么？

成就重复出现

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
阶段性成就 使用 1/13/16 个枫达奖杯

**Comment by mengxiliyu** [comment]
感谢
