### ISSUE TITLE
[Feat]: 希望能打包一个exe版本

### ISSUE THREAD

**Issue by R29kTA** [DGP-Studio/Snap.Hutao#972]
### Background & Motivation 背景与动机

现在使用proton已经可以在linux下玩原神了。

### Detail of the Feature 想要实现或优化的功能

希望能打包一个exe版本，以便可能在linux下使用工具箱

**Comment by Masterain98** [comment]
先让微软提供一份 Linxu 下的 .NET Desktop Runtime

**Comment by Lightczx** [comment]
胡桃依赖WinRT运行，linux运行不了的

**Comment by R29kTA** [comment]
> 先让微软提供一份 Linux 下的 .NET Desktop Runtime

我已经成功使用proton运行带有需要.NET Desktop Runtime的软件

**Comment by Lightczx** [comment]
你可以自行尝试编译

**Comment by R29kTA** [comment]
> 你可以自行尝试编译

我编译后打开遇到这个问题
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/35038406/73505041-26c4-425c-8c45-f973f2aaaa5f)

**Comment by Lightczx** [comment]
winui3依赖
你自己想办法解决
