### ISSUE TITLE
胡桃工具箱导致无法登录原神

### ISSUE THREAD

**Issue by Meow1026** [DGP-Studio/Snap.Hutao#975]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3448

### Snap Hutao 版本

1.7

### 问题分类

游戏启动器

### 发生了什么？

在米哈游通行证清除了所有登录设备后，再登录pc端游戏，因为胡桃工具箱的存在，游戏无法登陆了。 登录时，系统输出手机验证码，我点验证码发送，系统显示“该设备已信任”就发送不了验证码。卸载了胡桃工具箱，问题依然存在

### 你期望发生的行为？

救救我！！！！

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Meow1026** [comment]
我是1.7.6

**Comment by Masterain98** [comment]
米哈游帐号系统的问题，找米哈游去，胡桃没有强大到能影响米哈游帐号系统

> 卸载了胡桃工具箱，问题依然存在

其实你自己都发现了

![_NA$GHSH78~PWZGYC5)INF](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/f58e1f1e-6511-4475-9341-25ca2eaae926)
