### ISSUE TITLE
[Bug]: 游戏公告白屏

### ISSUE THREAD

**Issue by bakaomg** [DGP-Studio/Snap.Hutao#977]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2283

### Snap Hutao 版本

1.7.6.0

### 设备 ID

9E7D20450904049989F5581AD8BB1E67

### 问题分类

公告

## 复现步骤
1. 正常启动胡桃（窗口模式，且公告没法在可视区域全部获取完成）
2. 等待胡桃的公告加载完成下滑到 `活动公告`
3. 此时切换到 `游戏公告` 的 Tab 并滑至底部等待下一页的公告加载完成，即会直接空白

## 相关截图
![36ZQG49GL0I0SC~T4CXJ D0](https://github.com/DGP-Studio/Snap.Hutao/assets/40896676/5dd25ea0-86df-41f2-a025-bbff73445e55)

### 你期望发生的行为？

正常显示 `游戏公告` 列表

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
https://github.com/CommunityToolkit/Windows/issues/244

**Comment by Lightczx** [comment]
实际上WinUI3也有BUG，两个同时作用产生了这个奇异的现象

**Comment by Lightczx** [comment]
1.7.7应该已经修复
