### ISSUE TITLE
[Feat]: 分别设置国际服与国服启动路径

### ISSUE THREAD

**Issue by DarkSissi** [DGP-Studio/Snap.Hutao#979]
### Background & Motivation 背景与动机

不是使用官方启动器安装的游戏，启动胡桃后目录下没有config文件，即便修改启动路径为国际服，手动添加config或者登录国际服，胡桃工具箱也无法检测到国际服账号，只能检测到国服账号

### Detail of the Feature 想要实现或优化的功能

可以像之前的寻空一样设置双启动路径看看能否解决config与账号检测问题

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/534507c0-08ed-40f1-bf5e-2ea014207b41)
