### ISSUE TITLE
[Bug]: 深渊和我的角色无法刷新

### ISSUE THREAD

**Issue by earthjasonlin** [DGP-Studio/Snap.Hutao#980]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3208

### Snap Hutao 版本

2023.10.1.2/latest stable

### 设备 ID

A6E971E2E988D22A596C1B30A005DFCA

### 问题分类

角色信息面板

### 发生了什么？

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/83632110/dc0c5f3e-d5a3-4eae-9f50-debbed7fdecd)
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/83632110/3980c306-c07f-4d62-8193-490990ae7f25)
（已刷新cookie）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by csbo** [comment]
补充： YunzaiBot 和 Ysin 里的 获取深渊数据/上传深渊数据到胡桃榜 都没法正常使用。
感觉都是无法从米游社获取相关信息导致的。

**Comment by Witnesscm** [comment]
简单测试了一下，目前请求头不加x-rpc-device_fp基本必出1034，加上暂时就正常了

**Comment by Simplxss** [comment]
补充: 1034应该是需要过验证码的错误代码

**Comment by Suwmlee** [comment]
我的角色 —  同步角色信息— 从米游社我的角色同步  ⚠️  1034
我的角色 —  同步角色信息— 从米游社养成计算同步  ✅  正常
