### ISSUE TITLE
[Bug]: 导入祈愿时崩溃，导入出现异常数据

### ISSUE THREAD

**Issue by pubproprietary** [DGP-Studio/Snap.Hutao#983]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22621.2361

### Snap Hutao 版本

1.7.60.

### 设备 ID

F787FF8EE2EEA16AC02B127BFD88C48B

### 问题分类

祈愿记录

### 发生了什么？

从小助手上导出的json，导入时显示出现数据包含异常物品id1615301200000000204，随后删除这个id及其相似id204-0，再次导入出现崩溃现象

- System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2023-10-02T11:59:00.2717422Z 
 
   EventRecordID 3876 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  1204 
   [ ThreadID]  3004 
 
   Channel Application 
 
   Computer HUAWEI-STRIX 
 
  - Security 

   [ UserID]  S-1-5-21-670136458-2052679060-551584628-1001 
 

- EventData 

  AppName Snap.Hutao.exe 
  AppVersion 1.0.0.0 
  AppTimeStamp 64e841c5 
  ModuleName Microsoft.ui.xaml.dll 
  ModuleVersion 3.1.4.0 
  ModuleTimeStamp 343afd70 
  ExceptionCode c000027b 
  FaultingOffset 00000000003b9584 
  ProcessId 0x5464 
  ProcessCreationTime 0x1d9f527cc5af333 
  AppPath C:\Program Files\WindowsApps\60568DGPStudio.SnapHutao_1.7.6.0_x64__ebfp3nyc27j86\Snap.Hutao.exe 
  ModulePath C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.986.611.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll 
  IntegratorReportId 38257a24-321b-4959-b6c3-c5d2b7f11496 
  PackageFullName 60568DGPStudio.SnapHutao_1.7.6.0_x64__ebfp3nyc27j86 
  PackageRelativeAppId App 

### 你期望发生的行为？

正常导入

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
删错东西了
