### ISSUE TITLE
[Feat]: 祈愿记录跳转

### ISSUE THREAD

**Issue by 1235789gzy1** [DGP-Studio/Snap.Hutao#986]
### Background & Motivation 背景与动机

祈愿记录界面只显示了每个 武器/角色 出货的抽数,我希望能点击某个 武器/角色 直接跳转到相应的历史卡池

### Detail of the Feature 想要实现或优化的功能

点击 武器/角色 直接跳转到对应的卡池

**Comment by Lightczx** [comment]
basically impossible
