### ISSUE TITLE
添加导出祈愿记录为为excel（把Snap.Genshin的搬过来呗）

### ISSUE THREAD

**Issue by abandonstudy** [DGP-Studio/Snap.Hutao#987]
### Background & Motivation 背景与动机

方便查看，在没有安装snap hutao或别的祈愿记录分析软件时，json的可读性太差了
excel大部分电脑都装了

### Detail of the Feature 想要实现或优化的功能

导出祈愿记录为excel，类似下图
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/94209629/1f705c20-4b59-4956-aa85-431b582f5c73)

**Comment by Masterain98** [comment]
可以使用 https://genshin.voderl.cn/

**Comment by Masterain98** [comment]
Json 不是给人读的，而是让各平台的程序有一个通用的文件格式。

Excel 带来了过多的程序复杂性且不利于数据在应用之间传输，[UIGF-Org](https://uigf.org/zh/standards/UIGF.html) 已删除 Excel 文件格式下的标准。
