### ISSUE TITLE
[ENG][Bug]: Unable to load UIGFv2.3 Json while Language Does not Match

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#990]
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [fixed issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D), and it's not a duplicated issue

### Windows Version

Windows 10 22H2

### Snap Hutao Version

1.7.6

### Issue Category

Wish Export

## Wrong Error Message When Language Does Not Match for UIGFv2.2
When language does not match in UIGFv2.2, this message pops up
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/dabec8eb-7a06-41c0-8fa8-526dbd1c28a4)
This should be expected
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/4ce9a502-c4f5-47af-a1e7-61f542c75ec4)

## Unable to Load Records from UIGFv2.3 When Language does not Match
When using UIGFv2.3, language block should not happen, but it does
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/4ce9a502-c4f5-47af-a1e7-61f542c75ec4)

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by prpjzz** [comment]
With this error, I propose the following idea: Can allow conversion of all gacha data about the language specified in Snap.Hutao after importing the UIGF Json file if the language in that json file does not match the language of Snap.Hutao.
