### ISSUE TITLE
[Feat]: 增加元素战绩产球机制

### ISSUE THREAD

**Issue by fuchen828** [DGP-Studio/Snap.Hutao#991]
### Background & Motivation 背景与动机

在计算循环及充能效率时需要产球数据，而目前的Wiki对此有缺失

### Detail of the Feature 想要实现或优化的功能

在元素战技-冷却时间下增加一列产球数，数据来源
https://wiki.biligame.com/ys/元素能量学/角色数据

**Comment by Lightczx** [comment]
角色产球数据需要等待妮可完工

**Comment by Lightczx** [comment]
Tracked by #1394
