### ISSUE TITLE
[Network]: 图片资源下载一半就卡住动不了

### ISSUE THREAD

**Issue by kiripeng214** [DGP-Studio/Snap.Hutao#992]
### 提交你的网络诊断报告

![image](https://github.com/DGP-Studio/Snap.Hutao/assets/22195747/8171025f-ef08-4988-a42f-d2d384f2f9e6)

### 你的地理位置

福建

### 你的运营商

中国电信

### 你的问题

客户端图片下载错误

### 你的问题（补充）

一开始下载很快，下载一半就卡住，重新打开又是重新全部下载，直接在这个页面发呆了

**Comment by Lightczx** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/36357191/26205d6b-cc93-42fa-9dc3-a2f8903e4ffc)

**Comment by kiripeng214** [comment]
目前复现不出来

**Comment by 1sunxiaoshou** [comment]
同样的问题，用的校园网
![Uploading image.png…]()
