### ISSUE TITLE
[Bug]: 启动游戏时闪退

### ISSUE THREAD

**Issue by QGhappyChenCheng** [DGP-Studio/Snap.Hutao#993]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.3448

### Snap Hutao 版本

1.7.6

### 设备 ID

5C5C9AB81DE3F8E0C97880829971AD1E

### 问题分类

游戏启动器

### 发生了什么？

想换服，但胡桃直接闪退。（还没有进行换服）点别的功能没事，启动游戏会直接闪退，重启电脑以及重新下载胡桃还是无法解决问题。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
手动修改config文件
