### ISSUE TITLE
[Feat]: 改进祈愿界面抽卡记录显示，使之居中

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao#994]
### Background & Motivation 背景与动机

![图片](https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/63e9cb6e-d5f6-40f9-8b0b-846b7dbab7a0)
**如图，我的笔记本是1920*1080，放大150%的显示情况，在软件全屏的时候出现了右侧空隙宽度不够一栏，但是整体布局未自动调整居中的情况，希望改进**

### Detail of the Feature 想要实现或优化的功能

在宽度不够一栏时要么约束整体，使整个“角色活动”栏都不自动变宽（也就是让限定、武器、常驻各栏宽度不变，栏间隙宽度增加），要么约束每个栏的下方的抽卡记录，让他们分别居中，各大栏宽度仍保持现状。

**Comment by Lightczx** [comment]
> 在宽度不够一栏时要么约束整体，使整个“角色活动”栏都不自动变宽（也就是让限定、武器、常驻各栏宽度不变，栏间隙宽度增加）

我不知道如何实现

> 要么约束每个栏的下方的抽卡记录，让他们分别居中，各大栏宽度仍保持现状。

居中的效果很差，不会考虑

出于目前的情况关闭此Issue，如果后续有其他方面的优化建议可以开新的Issue
