### ISSUE TITLE
HoyoLAB 登录问题

### ISSUE THREAD

**Issue by yang2050** [DGP-Studio/Snap.Hutao#995]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

25931.1000 rs prerelease

### Snap Hutao 版本

1.7.6.0

### 设备 ID

2B923B5636603854E37633A08D8B7C82

### 问题分类

其它

### 发生了什么？

出现登录问题，系统：Windows 11 Insider Preview build: 25931.1000 rs prerelease.网页登录成功后点击“我已登录”后无法获取cookie并提示“状态:-200011信息: user not exist”。

### 你期望发生的行为？

出现登录问题，系统：Windows 11 Insider Preview build: 25931.1000 rs prerelease.网页登录成功后点击“我已登录”后无法获取cookie并提示“状态:-200011信息: user not exist”。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@yang2050 你使用了推特/Facebook/谷歌登录么

**Comment by chrzc** [comment]
Windows 版本
Windows11 22621.2283
Snap Hutao 版本
1.7.7.0
设备 ID
DE6DC692B46E47760447E6651506960F

同样出现了问题 ：登录米游社 点击"我已登录"无反应

**Comment by Lightczx** [comment]
@chrzc 米游社还是HoYoLAB

**Comment by chrzc** [comment]
> @chrzc 米游社还是HoYoLAB

米游社  AMD的cpu

**Comment by chrzc** [comment]
> @chrzc 米游社还是HoYoLAB


@chrzc 米游社还是HoYoLAB

@Lightczx  米游社 AMD的cpu

**Comment by Xhichn** [comment]
> Windows 版本 Windows11 22621.2283 Snap Hutao 版本 1.7.7.0 设备 ID DE6DC692B46E47760447E6651506960F
> 
> 同样出现了问题 ：登录米游社 点击"我已登录"无反应

@Lightczx 看起来是这里的问题 https://github.com/DGP-Studio/Snap.Hutao/blob/65179a340f9c49704d7c4e034f57c3c339fa39e3/src/Snap.Hutao/Snap.Hutao/View/Page/LoginMihoyoUserPage.xaml.cs#L47

**Comment by Lightczx** [comment]
1.7.9版本已经发布，应该修复了此问题，如果问题依然存在请务必开个新的Issue

**Comment by yang2050** [comment]
没有使用



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月07日 09:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DGP-Studio/Snap.Hutao] 登录问题 (Issue #995) |

@yang2050 你使用了推特/Facebook/谷歌登录么

**Comment by yang2050** [comment]
是的问题已经解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月13日 13:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DGP-Studio/Snap.Hutao] HoyoLAB 登录问题 (Issue #995) |

1.7.9版本已经发布，应该修复了此问题，如果问题依然存在请务必开个新的Issue
