### ISSUE TITLE
关于成就的错误

### ISSUE THREAD

**Issue by GLAFOX-g** [DGP-Studio/Snap.Hutao#996]
### 想要的文档

成就：一个冬天的童话、冰冷的钢铁、逆子的归乡是1.2版本加入游戏的而不是1.0加入游戏
成就：雷电将至、开战！是2.0版本加入游戏而不是1.6加入游戏

**Comment by Lightczx** [comment]
> 一个冬天的童话、冰冷的钢铁、逆子的归乡

确实是 1.2 版本，已经修正

> 雷电将至、开战！

1.6 版本，正确无误

**Comment by Lightczx** [comment]
元数据已更新
