### ISSUE TITLE
[Feat]: 自定义窗口大小

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao#997]
### Background & Motivation 背景与动机
> 支持.jpg.jpeg.png格式；尺寸：1280px*720px；不大于5M；需上传3~5张

我要做截图

![M8J~K%M0W_`I 3@1 {{Q4VQ](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/91b611b5-6237-47fe-9b30-a8d6aa3573ef)

### Detail of the Feature 想要实现或优化的功能

指定精确的自定义窗口大小

**Comment by Lightczx** [comment]
已实现
